import type { PlatformInput } from '../models/types.js';
import { run128SeedPlatforms } from './run128PlatformSeeds.js';

export const run127SeedPlatforms: PlatformInput[] = [
  {
    name: "WPRB Physical Priority and Email Music Submission Route",
    websiteUrl: "https://wprb.com/",
    submissionUrl: "mailto:music@wprb.com",
    sourceUrl: "https://wprb.com/music-submissions/",
    sourceType: "automation_run_127_public_research",
    country: "US / New Jersey freeform college radio physical-priority and email music submission route",
    language: "en",
    genres: ["wprb", "college-radio", "freeform-radio", "music-submissions", "physical-submission", "cd", "vinyl", "email-route", "manual-review"],
    submissionMethod: "official-wprb-physical-priority-email-music-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WPRB prioritizes physical submissions and also exposes a public music email route. Package preparation, media-format choice, one-sheet/metadata, pitch copy, email delivery and any physical mailing must remain owner-reviewed.",
    notes: "Official public research confirmed WPRB publishes a Music Submissions page for artists, labels and promoters, accepts CDs, CD-Rs, LPs, 12-inch, 10-inch and 7-inch records, lists a Music Director postal route and states music@wprb.com can be used while physical submissions are prioritized. No email was sent and no physical package was prepared or mailed."
  },
  {
    name: "WMBR MIT Freeform Physical Music Director and Genre Contact Route",
    websiteUrl: "https://wmbr.org/",
    submissionUrl: "https://wmbr.org/www/md",
    sourceUrl: "https://wmbr.org/www/md",
    sourceType: "automation_run_127_public_research",
    country: "US / Massachusetts MIT freeform college radio physical music submission and genre-contact route",
    language: "en",
    genres: ["wmbr", "mit", "college-radio", "freeform-radio", "physical-submission", "music-director", "rpm-techno", "world", "hiphop", "obfuscated-contact", "manual-review"],
    submissionMethod: "official-wmbr-mit-freeform-physical-music-director-genre-contact-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WMBR urges tangible physical music submissions, discourages MP3 review requests, uses genre-specific contact choices shown as protected image links and leaves airplay to individual freeform DJs. Physical mail, genre targeting and any protected contact handling must remain manual.",
    notes: "Official public research confirmed WMBR is active, freeform and publishes a 'How To Get Your Music Played on WMBR' route with a Music Director physical mailing address, explicit unsigned-band acceptance, physical-format preference and genre contacts including RPM/Techno and World. Protected image-based email contacts were not decoded, no contact was guessed and no message was sent."
  },
  {
    name: "CFUV Music Director Digital Download Link Campus Radio Submission Route",
    websiteUrl: "https://cfuv.uvic.ca/",
    submissionUrl: "mailto:music@cfuv.ca",
    sourceUrl: "https://cfuv.uvic.ca/music-submissions/",
    sourceType: "automation_run_127_public_research",
    country: "Canada / Victoria campus community radio digital download-link music submission route",
    language: "en",
    genres: ["cfuv", "campus-radio", "community-radio", "music-director", "digital-download-link", "320kbps-mp3", "three-tracks", "independent-artists", "electronic", "world", "manual-review"],
    submissionMethod: "official-cfuv-music-director-digital-download-link-campus-radio-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because CFUV requires at least three unique tracks, 320 kbps MP3 digital download links, proper artist/album/track metadata and a one-page biography, and only accepts physical submissions in limited local circumstances. Track selection, link packaging and rights/metadata review must remain owner-controlled.",
    notes: "Official public research confirmed CFUV publishes Music Department FAQ/submission guidelines, lists Music Director Troy Lemberg and music@cfuv.ca, covers all formats including electronic and world, requires at least three unique tracks and asks submissions to be sent by digital download link. No email was sent, no download link was delivered and no files were transferred."
  },
  {
    name: "CIUT 89.5FM New Music Email Submission Route",
    websiteUrl: "https://ciut.fm/",
    submissionUrl: "mailto:newmusic@ciut.fm",
    sourceUrl: "https://ciut.fm/contact/",
    sourceType: "automation_run_127_public_research",
    country: "Canada / Toronto campus and community radio new-music email submission route",
    language: "en",
    genres: ["ciut", "campus-radio", "community-radio", "new-music", "music-submission", "email-route", "electronic", "ragga-jungle", "world", "manual-review"],
    submissionMethod: "official-ciut-895fm-new-music-email-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because CIUT exposes a concise public new-music email route but no complete safe auto-submit form or detailed file-format policy. Music fit, show targeting, pitch copy, link delivery and rights metadata must remain owner-reviewed.",
    notes: "Official public research confirmed CIUT 89.5FM is active in 2026 as University of Toronto campus/community radio, publishes new/current show activity including electronic/ragga-jungle and global music programming, and directs music submissions to newmusic@ciut.fm. No email was sent and no links or files were delivered."
  },
  {
    name: "KTRU Rice Radio Physical-Only Music Department Submission and Contact Form Route",
    websiteUrl: "https://ktru.org/",
    submissionUrl: "https://ktru.org/contact/",
    sourceUrl: "https://ktru.org/contact/",
    sourceType: "automation_run_127_public_research",
    country: "US / Houston Rice University freeform radio physical-only music department submission route",
    language: "en",
    genres: ["ktru", "rice-radio", "college-radio", "freeform", "music-department", "physical-submission", "cd", "lp", "seven-inch", "contact-form", "manual-review"],
    submissionMethod: "official-ktru-rice-radio-physical-only-music-department-submission-contact-form-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KTRU states music submissions must use physical formats through USPS or UPS, while the public contact page also exposes a department selector/contact form. Package preparation, format choice, mailing and any contact-form message must remain manual.",
    notes: "Official public research confirmed KTRU is active in 2026 with current blog posts and setlist routes, exposes a public contact form with Music Director as a recipient option, and states all music submissions are physical-only CD, LP or 7-inch through USPS/UPS addresses. No form was submitted and no physical package was prepared or sent."
  },
  ...run128SeedPlatforms
];
