import type { PlatformInput } from '../models/types.js';

export const run180SeedPlatforms: PlatformInput[] = [
  {
    name: "Radio Milwaukee 88Nine WAV No Physical Music Submission Route",
    websiteUrl: "https://radiomilwaukee.org/",
    submissionUrl: "https://radiomilwaukee.org/music-submission",
    sourceUrl: "https://radiomilwaukee.org/music-submission",
    sourceType: "automation_run_180_public_research",
    country: "United States / Milwaukee public radio music submission route",
    language: "en",
    genres: ["public-radio", "aaa", "independent", "local-music", "new-music", "electronic", "alternative", "world", "radio-airplay", "wav", "manual-review"],
    submissionMethod: "official-radio-milwaukee-88nine-wav-music-submission-route",
    feeRequired: false,
    feeAmount: "No submission fee observed on the official public submission page; physical media is explicitly not accepted.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Radio Milwaukee asks for uncompressed mixed/mastered WAV files, radio edits, lyrics, bio, musician names, track comments, release/show context and links; owner approval is needed before any file/link transfer or pitch.",
    notes: "Public research verified Radio Milwaukee's official Submit Music navigation, current July 2026 site activity and submission requirements. No form was submitted and no audio was uploaded or transferred."
  },
  {
    name: "KRCL 90.9FM Physical CD Utah Google Form Airplay Submission Route",
    websiteUrl: "https://krcl.org/",
    submissionUrl: "https://krcl.org/about/how-to-submit-music/",
    sourceUrl: "https://krcl.org/about/how-to-submit-music/",
    sourceType: "automation_run_180_public_research",
    country: "United States / Utah community radio physical and local digital airplay route",
    language: "en",
    genres: ["community-radio", "freeform", "local-music", "physical-cd", "google-form", "independent", "electronic", "world", "reggae", "manual-review"],
    submissionMethod: "official-krcl-physical-cd-utah-google-form-airplay-submission-route",
    feeRequired: false,
    feeAmount: "No submission fee observed; physical CD route and Utah-local digital Google Form route are public, but materials become station property and are not returned.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KRCL separates physical CD submissions from Utah-based local digital uploads, uses a Google Form boundary for local music, does not return submitted music, and airplay is DJ-discretionary.",
    notes: "Public research verified KRCL's official How to Submit Music page, physical CD postal route and Utah-local digital-upload Google Form link. No Google Form was opened beyond public discovery, no package was prepared and no files were transferred."
  },
  {
    name: "A&R Factory Free Paid Review Music Blog Submission Form Route",
    websiteUrl: "https://www.anrfactory.com/",
    submissionUrl: "https://www.anrfactory.com/submit-demo/",
    sourceUrl: "https://www.anrfactory.com/submit-demo/",
    sourceType: "automation_run_180_public_research",
    country: "Global / UK music blog and A&R discovery submission form route",
    language: "en",
    genres: ["music-blog", "a-and-r", "independent-artists", "electronic", "edm", "drum-and-bass", "reggae", "world", "free-submission", "paid-review", "manual-review"],
    submissionMethod: "official-a-and-r-factory-free-paid-review-submission-form-route",
    feeRequired: false,
    feeAmount: "Free submission option observed; Standard Submission £20 and Premium Donation Submission £30 options plus PayPal/card payment fields were also present.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because A&R Factory offers free and paid package choices, asks for one track link, genre, release status/date, artwork/photo URL, social links, EPK/bio, email and marketing-budget context; package/payment selection must be owner-approved.",
    notes: "Public research verified A&R Factory's official active 2026 blog, Submit Your Music form, genre coverage including electronic/dance/EDM/reggae/world and free/paid options. No form fields were submitted and no payment path was used."
  },
  {
    name: "MusoSoup Free Review Paid Campaign Curator Marketplace Route",
    websiteUrl: "https://musosoup.com/",
    submissionUrl: "https://app.musosoup.com/sign-up-artist",
    sourceUrl: "https://musosoup.com/pricing",
    sourceType: "automation_run_180_public_research",
    country: "Global / curator playlist blog radio promotion marketplace route",
    language: "en",
    genres: ["music-promotion", "curators", "blogs", "playlists", "radio", "influencers", "electronic", "world", "freemium", "paid-campaign", "manual-review"],
    submissionMethod: "official-musosoup-free-review-paid-campaign-curator-marketplace-route",
    feeRequired: false,
    feeAmount: "Initial submission is described as free and reviewed first; campaign activation is listed at £42 after acceptance, with optional paid promotions commonly ranging around £8-£12 and free coverage options available.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because MusoSoup uses artist signup/sign-in, submission acceptance, campaign activation fee, curator marketplace targeting, paid/free coverage choices, budget decisions and platform terms.",
    notes: "Public research verified MusoSoup's official Submit Music app boundary, pricing page, curator/partner network, sign-in boundary and coverage marketplace. No account was created, no campaign was activated and no payment was initiated."
  },
  {
    name: "DailyPlaylists Free Spotify Playlist Submission Marketplace Route",
    websiteUrl: "https://dailyplaylists.com/",
    submissionUrl: "https://dailyplaylists.com/",
    sourceUrl: "https://dailyplaylists.com/",
    sourceType: "automation_run_180_public_research",
    country: "Global / Spotify playlist curator marketplace submission route",
    language: "en",
    genres: ["playlist-submission", "spotify", "curators", "independent-artists", "electronic", "dance", "pop", "world", "free-route", "premium-credits", "manual-review"],
    submissionMethod: "official-dailyplaylists-free-spotify-playlist-submission-marketplace-route",
    feeRequired: false,
    feeAmount: "Standard tier states artists can submit music for free; premium credits and Professional tier tools are also offered.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because DailyPlaylists asks artists to sign in, search/paste a song link, target relevant playlists, manage weekly submission limits, assess Premium Credits/Professional tools and comply with platform terms before outreach.",
    notes: "Public research verified DailyPlaylists' official submission marketplace, free standard submission route, 18,000+ playlist marketplace, sign-in boundary and public info@dailyplaylists.com business contact. No login, song lookup or submission was performed."
  }
];