import type { PlatformInput } from '../models/types.js';
import { run140SeedPlatforms } from './run140PlatformSeeds.js';

export const run139SeedPlatforms: PlatformInput[] = [
  {
    name: "TuneCore Digital Music Distribution Artist Release Upload Route",
    websiteUrl: "https://www.tunecore.com/",
    submissionUrl: "https://web.tunecore.com/",
    sourceUrl: "https://www.tunecore.com/",
    sourceType: "automation_run_139_public_research",
    country: "United States / global independent digital music distribution, publishing administration and artist-services platform",
    language: "en",
    genres: ["tunecore", "digital-distribution", "release-upload", "spotify", "apple-music", "tiktok", "youtube", "tidal", "beatport", "music-publishing", "artist-services", "account-required", "annual-plan", "payment-required", "manual-review"],
    submissionMethod: "official-tunecore-digital-music-distribution-artist-release-upload-route",
    feeRequired: true,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because TuneCore is an account/session-bound distribution route with annual plan pricing, release upload, ownership, metadata, cover art, publishing, store delivery and artist-growth settings that must remain owner-controlled.",
    notes: "Official TuneCore pages show Sell Your Music, Login, Sign Up, digital distribution to Spotify, Apple Music, TikTok, YouTube, Tidal, Tencent and more, 150+ stores, unlimited releases starting at $24.99/year, publishing administration and artist services. No account was created, no login was used, no release was configured, no music/artwork was uploaded, no store delivery was selected and no payment was initiated."
  },
  {
    name: "CD Baby One-Time Digital Distribution Release Upload Route",
    websiteUrl: "https://cdbaby.com/",
    submissionUrl: "https://members.cdbaby.com/",
    sourceUrl: "https://cdbaby.com/",
    sourceType: "automation_run_139_public_research",
    country: "United States / worldwide independent music distribution platform with one-time per-release pricing and promotion resources",
    language: "en/es/pt",
    genres: ["cd-baby", "digital-distribution", "release-upload", "spotify", "apple-music", "tiktok", "amazon", "pandora", "youtube", "deezer", "one-time-fee", "artist-account", "payment-required", "manual-review"],
    submissionMethod: "official-cd-baby-one-time-digital-distribution-release-upload-route",
    feeRequired: true,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because CD Baby requires account access, one-time per-release payment, release metadata, rights, artwork, store selection, cover licensing and promotion-option decisions before distribution.",
    notes: "Official CD Baby pages show Get Started/Login, worldwide digital music distribution to 150+ streaming and download services, starting at $9.99 per release, no subscription fees, per-single/per-album pricing, reports/analytics, cover-song licensing and promotion resources. No account was created, no login was used, no release was configured, no music/artwork was uploaded, no partner delivery was selected and no payment was initiated."
  },
  {
    name: "Ditto Music Free Signup Unlimited Release and Playlist Pitch Route",
    websiteUrl: "https://dittomusic.com/en",
    submissionUrl: "https://login.dittomusic.com/",
    sourceUrl: "https://dittomusic.com/en",
    sourceType: "automation_run_139_public_research",
    country: "United Kingdom / global independent distribution, monetization, sync, publishing and playlist-pitching platform",
    language: "en/es/pt/fr/de",
    genres: ["ditto-music", "digital-distribution", "release-upload", "spotify", "apple-music", "tiktok", "beatport", "sync-licensing", "playlist-pitching", "pre-save", "free-signup", "paid-plan", "account-required", "payment-required", "manual-review"],
    submissionMethod: "official-ditto-music-free-signup-unlimited-release-and-playlist-pitch-route",
    feeRequired: true,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Ditto exposes free account creation but release, pricing plan, playlist pitch, sync, publishing, Content ID, royalty split and Beatport/store delivery decisions must remain owner-controlled.",
    notes: "Official Ditto pages show Login, Try for Free, sign-up free form, distribution to 150+ platforms, unlimited releases, 100% royalty payouts, free pre-save links, playlist pitching, sync licensing, YouTube Content ID, pricing from $19/year and June 2026 review activity. No account was created, no login or social sign-in was used, no release was configured, no playlist pitch was submitted, no sync brief was entered and no payment was initiated."
  },
  {
    name: "ONErpm Global Join Distribution Marketing and Artist Services Route",
    websiteUrl: "https://onerpm.com/",
    submissionUrl: "https://dashboard.onerpm.com/",
    sourceUrl: "https://onerpm.com/",
    sourceType: "automation_run_139_public_research",
    country: "United States / global music business, digital distribution, marketing, rights-management, publishing and artist-services company",
    language: "en/pt/es/ru/fr/it/de/ar/pl/tr/ja/sw/nl/ko/vi/zh/th/id/hi/tl",
    genres: ["onerpm", "digital-distribution", "music-marketing", "rights-management", "publishing-administration", "music-analytics", "royalty-sharing", "global-offices", "join-route", "account-required", "unknown-pricing", "manual-review"],
    submissionMethod: "official-onerpm-global-join-distribution-marketing-and-artist-services-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because ONErpm exposes a Join/Login route but commercial terms, service model, artist stage fit, release upload, rights-management, marketing, publishing and regional-support choices need owner approval before onboarding.",
    notes: "Official ONErpm pages show Join/Login, digital distribution, marketing methodology, publishing, business intelligence, music analytics, royalty sharing, rights management, global offices and multilingual support. The public page did not expose a safe auto-submit form or pricing terms, so it is queued for manual commercial review. No account was created, no login was used, no release/upload workflow was entered and no payment or service commitment was made."
  },
  {
    name: "LANDR Studio Distribution Mastering and Release Upload Route",
    websiteUrl: "https://www.landr.com/",
    submissionUrl: "https://app.landr.com/",
    sourceUrl: "https://www.landr.com/",
    sourceType: "automation_run_139_public_research",
    country: "Canada / global music creation, AI mastering, distribution, collaboration and release platform",
    language: "en/fr/de/it/ja/pt/es",
    genres: ["landr", "music-distribution", "release-upload", "ai-mastering", "spotify", "apple-music", "tiktok", "youtube", "streaming-platforms", "collaboration", "subscription", "account-required", "payment-required", "manual-review"],
    submissionMethod: "official-landr-studio-distribution-mastering-and-release-upload-route",
    feeRequired: true,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because LANDR combines mastering, distribution and collaboration tools; account access, plan choice, master/export settings, release metadata, rights, store delivery and subscription/payment decisions require owner control.",
    notes: "Official LANDR pages show Distribution, Log in, Sign up free, LANDR Studio pricing context, unlimited distribution to 150+ streaming platforms, Apple Music/Spotify/TikTok/YouTube delivery, 100% royalties and connected mastering/collaboration tools. No account was created, no login was used, no file was uploaded/mastered, no release was configured, no store delivery was selected and no subscription/payment was initiated."
  },
  ...run140SeedPlatforms
];
