import type { PlatformInput } from '../models/types.js';

export const run179BaseSeedPlatforms: PlatformInput[] = [
  {
    name: "Amazing Radio Emerging Artist Upload Airplay App Route",
    websiteUrl: "https://amazingradio.com/",
    submissionUrl: "https://amazingradio.com/",
    sourceUrl: "https://amazingradio.com/",
    sourceType: "automation_run_179_public_research",
    country: "Global / UK US emerging-artist radio upload discovery route",
    language: "en",
    genres: ["internet-radio", "emerging-artists", "new-music", "independent", "unsigned", "electronic", "indie", "alternative", "radio-airplay", "app-boundary", "manual-review"],
    submissionMethod: "official-amazing-radio-emerging-artist-upload-app-route",
    feeRequired: false,
    feeAmount: "No submission fee was confirmed from the public sources consulted; route is behind an official JavaScript application boundary and requires manual owner review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because artist upload/submission is routed through Amazing Radio's JavaScript app, likely requiring account/session handling, rights confirmation, release metadata, track selection and fit for emerging-artist radio programming.",
    notes: "Public research verified Amazing Radio's official site, worldwide/new-and-emerging-artist positioning and current web-app boundary. No account was created, no login was used and no audio was uploaded."
  },
  {
    name: "Groover Curator Radio Label Playlist Paid Campaign Route",
    websiteUrl: "https://groover.co/en/",
    submissionUrl: "https://groover.co/en/",
    sourceUrl: "https://groover.co/en/",
    sourceType: "automation_run_179_public_research",
    country: "Global / curator playlist radio label music promotion marketplace route",
    language: "en",
    genres: ["music-promotion", "curators", "playlists", "radio", "labels", "blogs", "djs", "electronic", "world", "paid-campaign", "manual-review"],
    submissionMethod: "official-groover-paid-curator-radio-label-playlist-campaign-route",
    feeRequired: true,
    feeAmount: "Paid Grooviz credit route observed; Groover states one Grooviz equals one euro, contacting a curator/pro costs two Grooviz, and top-tier curators may cost more.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Groover requires artist signup/login, paid credit purchase, curator targeting, pitch copy, release-link selection, budget control and acceptance of campaign/platform terms.",
    notes: "Public research verified Groover's official campaign route, 3,000+ curator/pro marketplace, upload/pitch flow, guaranteed-feedback/refund framing and paid Grooviz pricing. No signup, payment or campaign was started."
  },
  {
    name: "Soundplate Free Spotify Deezer Playlist Submission Route",
    websiteUrl: "https://play.soundplate.com/",
    submissionUrl: "https://play.soundplate.com/",
    sourceUrl: "https://play.soundplate.com/",
    sourceType: "automation_run_179_public_research",
    country: "Global / Spotify Deezer independent playlist curator submission route",
    language: "en",
    genres: ["playlist-submission", "spotify", "deezer", "independent-curators", "electronic", "house", "bass", "garage", "festival", "free-route", "manual-review"],
    submissionMethod: "official-soundplate-free-spotify-deezer-playlist-submission-route",
    feeRequired: false,
    feeAmount: "No submission fee observed; Soundplate describes Play.Soundplate as a free service for submitting music to independent Spotify and Deezer playlist curators.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Soundplate asks artists to select only relevant playlists and avoid spam, so genre fit, track-link quality, curator targeting and platform terms must be reviewed before submission.",
    notes: "Public research verified Soundplate's official playlist-submission page, Spotify/Deezer playlist grid, free-service statement, relevance/no-spam guidance and active playlist categories. No playlist was selected and no submission was sent."
  },
  {
    name: "TIDAL Upload US Independent Artist Self Publishing Route",
    websiteUrl: "https://tidal.com/",
    submissionUrl: "https://tidal.com/",
    sourceUrl: "https://tidal.com/",
    sourceType: "automation_run_179_public_research",
    country: "United States / TIDAL direct upload independent artist route with eligibility restrictions",
    language: "en",
    genres: ["streaming", "direct-upload", "independent-artists", "tidal", "self-publishing", "editorial-review", "electronic", "rights-review", "ai-disclosure", "manual-review"],
    submissionMethod: "tidal-upload-independent-artist-self-publishing-app-route",
    feeRequired: false,
    feeAmount: "Public reporting describes TIDAL Upload as free-to-use, but uploaded files do not earn royalties; eligibility, incentives and terms require manual review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because TIDAL Upload includes US/age eligibility, rights ownership, copyright protection, no-royalty economics, file/track limits, editorial/Spotlight incentives and updated AI-content/distributor-labeling policy considerations.",
    notes: "Public research verified TIDAL Upload through current music-industry reporting and current TIDAL AI-policy coverage. No account was created, no login was used and no music was uploaded."
  },
  {
    name: "SoundOn TikTok Music Distribution Artist Upload Route",
    websiteUrl: "https://www.soundon.global/",
    submissionUrl: "https://www.soundon.global/",
    sourceUrl: "https://www.soundon.global/",
    sourceType: "automation_run_179_public_research",
    country: "Global / TikTok powered music distribution route with territory availability review",
    language: "en",
    genres: ["music-distribution", "tiktok", "artist-upload", "short-video", "streaming-distribution", "publishing-admin", "electronic", "afrobeats", "world", "rights-review", "manual-review"],
    submissionMethod: "official-soundon-tiktok-music-distribution-artist-upload-route",
    feeRequired: false,
    feeAmount: "No upfront submission fee was confirmed from public sources consulted; royalty-share, territory availability and platform terms require manual review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because SoundOn is a TikTok/ByteDance distribution platform with signup/app boundaries, territory availability, copyright retention, royalty economics, publishing administration, TikTok delivery and DSP distribution terms that need owner approval.",
    notes: "Public research verified SoundOn's official global site and public description as TikTok's music marketing/distribution platform. No signup, upload, release configuration or royalty/publishing action was started."
  }
];