import type { PlatformInput } from '../models/types.js';

export const run112SeedPlatforms: PlatformInput[] = [
  {
    name: "KVRX 91.7FM Music Department Digital and Physical Airplay Submission Route",
    websiteUrl: "https://www.kvrx.org/",
    submissionUrl: "https://www.kvrx.org/app/contact/",
    sourceUrl: "https://www.kvrx.org/app/contact/",
    sourceType: "automation_run_112_public_research",
    country: "United States / Austin student-run independent radio airplay submission route",
    language: "en",
    genres: ["kvrx", "college-radio", "student-radio", "austin", "independent-music", "underground", "freeform", "electronic", "reggae", "dub", "world", "hip-hop", "local-music", "digital-submission", "physical-submission", "ai-policy", "free-first", "manual-review"],
    submissionMethod: "official-kvrx-music-department-digital-and-physical-airplay-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KVRX accepts public music submissions through Music Department routes, currently supports both physical and digital submissions, blocks AI-assisted/generated music from consideration, and needs owner review for pitch copy, rights status, metadata, clean/radio edit suitability and delivery format before any outreach occurs.",
    notes: "Public research confirmed KVRX is active as a student-run underground/independent station and its official contact page lists authorized Music Department submission routing. No email was sent, no files or download links were delivered, no physical package was prepared, no login was used and no mailbox probing was performed."
  },
  {
    name: "KSCU 103.3FM Music Director Airplay Submission Email Route",
    websiteUrl: "https://kscu.org/",
    submissionUrl: "https://kscu.org/about/",
    sourceUrl: "https://kscu.org/about/",
    sourceType: "automation_run_112_public_research",
    country: "United States / Santa Clara University student radio airplay email route",
    language: "en",
    genres: ["kscu", "college-radio", "student-radio", "santa-clara", "underground-sound", "independent-music", "alternative", "soul", "jazz", "electronic", "reggae", "dub", "world", "hip-hop", "music-director-email", "free-first", "manual-review"],
    submissionMethod: "official-kscu-music-director-airplay-submission-email-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KSCU provides a public Music Director email route for airplay consideration but does not expose a complete safe auto-submit form; pitch copy, link/file format, metadata, rights, FCC-clean suitability and station fit need owner review.",
    notes: "Public research confirmed KSCU is an active Santa Clara University student-run station, its site shows recent activity and its About page explicitly says to submit music for airplay through the Music Director route. No email was sent, no files or download links were delivered and no SMTP or MX probing was performed."
  },
  {
    name: "KALX 90.7FM Berkeley Physical CD LP Music Director Airplay Route",
    websiteUrl: "https://kalx.berkeley.edu/",
    submissionUrl: "https://kalx.berkeley.edu/about/contact/",
    sourceUrl: "https://kalx.berkeley.edu/about/contact/",
    sourceType: "automation_run_112_public_research",
    country: "United States / Berkeley freeform radio physical-only airplay submission route",
    language: "en",
    genres: ["kalx", "college-radio", "community-radio", "freeform", "berkeley", "independent-music", "eclectic", "electronic", "reggae", "dub", "world", "hip-hop", "physical-only", "pressed-cd", "lp", "music-director", "free-first", "manual-review"],
    submissionMethod: "official-kalx-physical-cd-lp-music-director-airplay-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KALX currently accepts only physical professionally pressed CDs or LPs for airplay consideration, explicitly excludes downloads, file transfers, Bandcamp/Spotify links, YouTube videos, CD-Rs and other digital forms, and requires physical package preparation for the Music Director.",
    notes: "Public research confirmed KALX is active in July 2026 with current playlists and coming attractions, and the official contact page lists Music Directors, a public music route and physical-only airplay submission instructions. No email was sent, no physical mail was prepared and no mailbox probing was performed."
  },
  {
    name: "KZSC Santa Cruz Music Directors Package and Contact Form Submission Route",
    websiteUrl: "https://kzsc.org/",
    submissionUrl: "https://kzsc.org/send-us-a-message/",
    sourceUrl: "https://kzsc.org/send-us-a-message/",
    sourceType: "automation_run_112_public_research",
    country: "United States / UC Santa Cruz college radio music package and contact form route",
    language: "en",
    genres: ["kzsc", "college-radio", "community-radio", "santa-cruz", "independent-music", "reggae", "electronica", "hip-hop", "international", "jazz", "blues", "music-directors", "physical-package", "public-form", "validation-field", "redacted-contact", "free-first", "manual-review"],
    submissionMethod: "official-kzsc-music-directors-package-and-contact-form-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KZSC exposes Music Director contact roles, package addresses and a public contact form with a Music Submission selector plus validation field; staff email values were redacted by the fetch layer and must not be decoded or guessed, and physical package/form handling requires owner review.",
    notes: "Public research confirmed KZSC is active in 2026 with recent posts and an official contact workflow for Music Directors, packages and Music Submission form routing. No form was submitted, no package was prepared, no redacted contact was decoded and no SMTP or MX probing was performed."
  },
  {
    name: "KCSB Santa Barbara Artist Inquiry Live Airplay Library and Premiere Form Route",
    websiteUrl: "https://www.kcsb.org/",
    submissionUrl: "https://www.kcsb.org/contact/artist-inquiry/",
    sourceUrl: "https://www.kcsb.org/contact/artist-inquiry/",
    sourceType: "automation_run_112_public_research",
    country: "United States / Santa Barbara college radio artist inquiry and music-library form route",
    language: "en",
    genres: ["kcsb", "college-radio", "community-radio", "santa-barbara", "artist-inquiry", "live-on-air", "station-events", "music-library", "premiere", "independent-music", "electronic", "reggae", "dub", "world", "hip-hop", "external-form", "free-first", "manual-review"],
    submissionMethod: "official-kcsb-artist-inquiry-live-airplay-library-premiere-form-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KCSB's artist inquiry route uses an external public form for live on-air performance, station events, music-library addition and song/video premiere opportunities; form/session handling, pitch scope, music-package readiness and editorial fit must be reviewed before use.",
    notes: "Public research confirmed KCSB is active in 2026 with current music posts and an official Artist Inquiry page linking to an authorized external form. No external form was opened beyond public page discovery, no form was submitted, no files were uploaded and no session controls were bypassed."
  }
];