import type { PlatformInput } from '../models/types.js';
import { run123SeedPlatforms } from './run123PlatformSeeds.js';

export const run122SeedPlatforms: PlatformInput[] = [
  {
    name: "A&R Factory Free and Paid Blog Review Submission Route",
    websiteUrl: "https://www.anrfactory.com/",
    submissionUrl: "https://www.anrfactory.com/submit-demo/",
    sourceUrl: "https://www.anrfactory.com/submit-demo/",
    sourceType: "automation_run_122_public_research",
    country: "United Kingdom / global A&R music-blog review and artist discovery route",
    language: "en",
    genres: ["a-and-r-factory", "music-blog", "a-and-r", "independent-artists", "electronic", "edm", "dancehall", "drum-and-bass", "reggae", "world", "form", "captcha", "freemium", "manual-review"],
    submissionMethod: "official-a-and-r-factory-free-paid-blog-review-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because A&R Factory exposes a multi-step submission form with required artist, genre, one-track link, social, artwork/photo, EPK/bio and email fields, plus CAPTCHA and optional Standard/Premium paid package choices. Form interaction, package selection, pitch fit and payment avoidance require owner review.",
    notes: "Official public research confirmed A&R Factory is active through 2026, accepts global independent artists across many genres and publishes a Submit Your Music form. No CAPTCHA interaction occurred, no form was submitted, no payment path was started and no track link was delivered."
  },
  {
    name: "DailyPlaylists Free Spotify Playlist Marketplace Submission Route",
    websiteUrl: "https://dailyplaylists.com/",
    submissionUrl: "https://dailyplaylists.com/",
    sourceUrl: "https://dailyplaylists.com/",
    sourceType: "automation_run_122_public_research",
    country: "Global / Spotify playlist marketplace and artist submission route",
    language: "en",
    genres: ["dailyplaylists", "spotify", "playlist-submission", "playlist-marketplace", "curators", "artist-tools", "standard-submissions", "premium-credits", "business-email", "freemium", "login", "manual-review"],
    submissionMethod: "official-dailyplaylists-free-spotify-playlist-marketplace-submission-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because DailyPlaylists routes artists through sign-in, song search/link handling and playlist/curator selection. It offers free Standard submissions alongside Premium Credits and Professional tier options, so account access, curator fit, pricing boundaries and link selection require owner review.",
    notes: "Official public research confirmed DailyPlaylists is active in 2026, lists Submit a Song, reports large-scale submission activity, exposes info@dailyplaylists.com as a public business contact and describes free access to 18,000+ playlists plus paid/pro options. No login was used and no song was submitted."
  },
  {
    name: "SoundCampaign Spotify Playlist and TikTok Creator Paid Campaign Route",
    websiteUrl: "https://soundcamps.com/",
    submissionUrl: "https://soundcamps.com/",
    sourceUrl: "https://soundcamps.com/",
    sourceType: "automation_run_122_public_research",
    country: "Global / paid Spotify playlist and TikTok creator music promotion route",
    language: "en",
    genres: ["soundcampaign", "spotify-promotion", "tiktok-promotion", "playlist-curators", "creator-campaigns", "paid", "campaign-budget", "curator-feedback", "app-login", "manual-review"],
    submissionMethod: "official-soundcampaign-spotify-playlist-tiktok-creator-paid-campaign-route",
    feeRequired: true,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because SoundCampaign is a paid campaign route with app login, budget/payment approval, Spotify/TikTok campaign configuration and track matching. It pays curators for reviews rather than guaranteed placement, so campaign setup, budget, rights and risk controls require owner review.",
    notes: "Official public research confirmed SoundCampaign is active, offers Spotify playlist and TikTok creator promotion, states that curators are compensated for reviews rather than guaranteed placements, and describes real-time campaign reporting. No account was opened, no campaign was configured and no payment was initiated."
  },
  {
    name: "MusoSoup Global Curator Coverage Campaign Submission Route",
    websiteUrl: "https://musosoup.com/",
    submissionUrl: "https://musosoup.com/",
    sourceUrl: "https://musosoup.com/",
    sourceType: "automation_run_122_public_research",
    country: "Global / curator marketplace for blog playlist radio and social coverage",
    language: "en",
    genres: ["musosoup", "curator-marketplace", "music-blogs", "playlist-submission", "radio-coverage", "social-coverage", "mp3-upload", "music-link", "campaign-fee", "freemium", "login", "manual-review"],
    submissionMethod: "official-musosoup-global-curator-coverage-campaign-submission-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because MusoSoup starts with a free music upload/link submission but, if approved, requires account creation and campaign-fee decisions before coverage generation. Paid/free curator offers, MP3 or link handling, release timing and rights metadata must be owner-reviewed.",
    notes: "Official public research confirmed MusoSoup is active in 2026, lists many partner curators, lets artists submit a single, EP or album by link or MP3, and says approved campaigns require an account and fee while also offering free coverage options. No app session was entered and no music was uploaded."
  },
  {
    name: "Spotify for Artists Editorial Playlist Pitching Route",
    websiteUrl: "https://artists.spotify.com/",
    submissionUrl: "https://support.spotify.com/us/artists/article/pitching-music-to-playlist-editors/",
    sourceUrl: "https://support.spotify.com/us/artists/article/pitching-music-to-playlist-editors/",
    sourceType: "automation_run_122_public_research",
    country: "Global / official Spotify editorial playlist pitching route for unreleased music",
    language: "en",
    genres: ["spotify-for-artists", "editorial-playlist-pitch", "unreleased-music", "release-radar", "artist-admin", "artist-editor", "metadata", "spotify", "free-first", "login", "manual-review"],
    submissionMethod: "official-spotify-for-artists-editorial-playlist-pitching-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Spotify pitching requires Spotify for Artists Admin or Editor access, an upcoming unreleased track, distributor delivery timing, detailed pitch metadata and one active song pitch at a time. Account/session access and release strategy must remain owner-reviewed.",
    notes: "Official public research confirmed Spotify documents a playlist-editor pitching workflow for upcoming unreleased songs, requires login to Spotify for Artists, recommends pitching at least 7 days before release and notes pitching does not guarantee placement. No login was used and no pitch was created."
  },
  ...run123SeedPlatforms
];