import type { PlatformInput } from '../models/types.js';

export const run175SeedPlatforms: PlatformInput[] = [
  {
    name: "Radio K KUOM Music Submissions and Off The Record Route",
    websiteUrl: "https://radiok.org/",
    submissionUrl: "https://radiok.org/contact",
    sourceUrl: "https://radiok.org/contact",
    sourceType: "automation_run_175_public_research",
    country: "United States / Minneapolis-St. Paul independent college-community radio route with online reach",
    language: "en",
    genres: ["college-radio", "independent", "alternative", "electronic", "hip-hop", "local-performance", "off-the-record", "music-director", "manual-review"],
    submissionMethod: "official-radio-k-kuom-music-submissions-off-the-record-route",
    feeRequired: false,
    feeAmount: "No submission fee observed on the public Radio K contact route; exact format requirements from the linked How to Submit Music page require manual review because the details page could not be fetched during this run.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Radio K exposes a linked How to Submit Music route plus Music Director and Off The Record contacts, but package format, attachments/download-link handling and show fit must be reviewed before sending.",
    notes: "Public research verified Radio K official station/contact pages, current new-album/new-single rotation, July 2026 content, Music Submissions navigation and public staff/contact routes. No email, form, upload or package was sent."
  },
  {
    name: "CKUA Alberta Digital Music Committee Airplay Submission Route",
    websiteUrl: "https://ckua.com/",
    submissionUrl: "https://ckua.com/our-story/library/getting-airplay/",
    sourceUrl: "https://ckua.com/our-story/library/getting-airplay/",
    sourceType: "automation_run_175_public_research",
    country: "Canada / Alberta radio network with Canadian and global digital airplay review",
    language: "en",
    genres: ["radio-airplay", "adult-alternative", "roots", "folk", "experimental-pop", "traditional-country", "soca", "newgrass", "canadian-artists", "manual-review"],
    submissionMethod: "official-ckua-digital-music-committee-airplay-submission-route",
    feeRequired: false,
    feeAmount: "No submission fee observed; CKUA asks for digital submissions with streaming/download links and also lists a Music Committee postal route.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because CKUA requests a one-sheet, backgrounder, bio, website, clean/radio edits, streaming and download links, 320 kbps MP3 preference and Music Committee review; owner must approve metadata, links and rights before sending.",
    notes: "Public research verified CKUA official contact and Getting Airplay pages, digital-only preference, clean/obscenity guidance, 320 kbps MP3/download-link recommendations, Music Committee review queue and July 2026 site activity. No email, form, upload, link or package was sent."
  },
  {
    name: "KGNU Boulder Denver Music Department Contact Form Route",
    websiteUrl: "https://kgnu.org/",
    submissionUrl: "https://kgnu.org/contact-us/",
    sourceUrl: "https://kgnu.org/contact-us/",
    sourceType: "automation_run_175_public_research",
    country: "United States / Boulder and Denver independent community radio music department contact route",
    language: "en",
    genres: ["community-radio", "independent", "local-music", "bluegrass", "jazz", "electronic", "world", "folk", "music-department", "recaptcha", "manual-review"],
    submissionMethod: "official-kgnu-music-department-contact-form-route",
    feeRequired: false,
    feeAmount: "No music-contact fee observed; KGNU contact page exposes radio staff/DJ contact routing with Music and DJ department options.",
    loginRequired: false,
    captchaDetected: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because the official KGNU staff/DJ contact path is a public form with Music/DJ department routing and reCAPTCHA v3; anti-bot controls must not be bypassed and artist pitch/material must be owner-approved.",
    notes: "Public research verified KGNU official site activity with July 2026 music/news posts, live stream, music menus, contact form department options including Music and DJ, and reCAPTCHA v3. No form was submitted and CAPTCHA was not handled."
  },
  {
    name: "WFMU Freeform Physical Music Director Review Submission Route",
    websiteUrl: "https://www.wfmu.org/",
    submissionUrl: "https://www.wfmu.org/sendmusic.html",
    sourceUrl: "https://www.wfmu.org/sendmusic.html",
    sourceType: "automation_run_175_public_research",
    country: "United States / New York New Jersey Hudson Valley and global online freeform radio physical-review route",
    language: "en",
    genres: ["freeform-radio", "experimental", "independent", "electronic", "vinyl", "cd", "cassette", "physical-review", "music-director", "manual-review"],
    submissionMethod: "official-wfmu-freeform-physical-music-director-review-submission-route",
    feeRequired: false,
    feeAmount: "No submission fee observed; WFMU asks music-review materials to be mailed physically.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WFMU requests physical review materials such as vinyl, CD, CD-R or cassette; package preparation, postage, format choice and Music Director contact require owner control.",
    notes: "Public research verified WFMU official Send Us Music page, physical review format list, Music Director postal/UPS/FedEx routes and current 2026 playlists/archives. No package was prepared or mailed and no contact was sent."
  },
  {
    name: "PBS 106.7FM Melbourne Digital Submit Your Music Form Route",
    websiteUrl: "https://www.pbsfm.org.au/",
    submissionUrl: "https://www.pbsfm.org.au/submitmusic",
    sourceUrl: "https://www.pbsfm.org.au/submitmusic",
    sourceType: "automation_run_175_public_research",
    country: "Australia / Melbourne community radio route accepting local and international music",
    language: "en",
    genres: ["community-radio", "under-represented-music", "electronic", "roots", "world", "hip-hop", "international", "download-link", "physical-side-route", "captcha", "manual-review"],
    submissionMethod: "official-pbs-1067fm-digital-submit-your-music-form-route",
    feeRequired: false,
    feeAmount: "No submission fee observed; PBS prefers digital submission through the public form and also accepts posted CDs/vinyl or in-person delivery.",
    loginRequired: false,
    captchaDetected: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because the PBS public form includes required contact/location fields, social/gig metadata, music stream and high-quality download links, a non-Spotify/Deezer rule, physical-copy guidance and CAPTCHA; no anti-bot control may be bypassed.",
    notes: "Public research verified PBS official Submit Your Music page, local and international acceptance, digital form, 320 kbps AAC/MP3/WAV-equivalent download requirement, physical CD/vinyl side route, current July 2026 site activity and CAPTCHA boundary. No form was submitted, no download link was provided and CAPTCHA was not handled."
  }
];
