import type { PlatformInput } from '../models/types.js';

export const run115SeedPlatforms: PlatformInput[] = [
  {
    name: "RouteNote Free and Premium Digital Music Distribution Route",
    websiteUrl: "https://www.routenote.com/",
    submissionUrl: "https://www.routenote.com/",
    sourceUrl: "https://www.routenote.com/",
    sourceType: "automation_run_115_public_research",
    country: "United Kingdom / Global independent music distribution route",
    language: "en",
    genres: ["routenote", "digital-distribution", "free-distribution", "premium-distribution", "spotify", "apple-music", "independent-artists", "electronic", "reggae", "dub", "world", "free-first", "account-boundary", "manual-review"],
    submissionMethod: "official-routenote-free-premium-digital-music-distribution-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because RouteNote is an account-based distribution workflow with Free and Premium choices, release metadata, store selection, rights ownership and royalty-model decisions before delivery.",
    notes: "Official public research confirmed RouteNote offers Free or Premium distribution and sends music worldwide to Spotify, Apple Music and other platforms. No account, submission, upload, store delivery or payment action was performed."
  },
  {
    name: "Audiomack Creator Upload and Free Limitless Music Discovery Route",
    websiteUrl: "https://audiomack.com/",
    submissionUrl: "https://creators.audiomack.com/",
    sourceUrl: "https://creators.audiomack.com/",
    sourceType: "automation_run_115_public_research",
    country: "United States / Global creator streaming and discovery platform",
    language: "en",
    genres: ["audiomack", "creator-route", "music-sharing", "music-discovery", "free-hosting", "unlimited-storage", "private-links", "advanced-stats", "electronic", "reggae", "dub", "world", "afrobeats", "free-first", "account-boundary", "manual-review"],
    submissionMethod: "official-audiomack-creator-free-limitless-music-discovery-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Audiomack is an account-based creator route requiring owner review of rights, metadata, privacy settings, monetization choices and profile decisions.",
    notes: "Official public research confirmed Audiomack has creator account and music sharing routes and describes itself as a free, limitless platform for artists and creators. No account, submission, upload or payment action was performed."
  },
  {
    name: "CD Baby Worldwide Music Distribution Paid Release Submission Route",
    websiteUrl: "https://cdbaby.com/",
    submissionUrl: "https://members.cdbaby.com/",
    sourceUrl: "https://cdbaby.com/",
    sourceType: "automation_run_115_public_research",
    country: "United States / Global independent music distribution and promotion route",
    language: "en",
    genres: ["cd-baby", "digital-distribution", "spotify", "apple-music", "tiktok", "amazon", "pandora", "youtube", "deezer", "promotion", "independent-artists", "electronic", "reggae", "dub", "world", "paid-route", "account-boundary", "payment-required", "manual-review"],
    submissionMethod: "official-cd-baby-paid-release-distribution-submission-route",
    feeRequired: true,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because CD Baby is a paid account-based release workflow requiring payment approval, release type selection, metadata, rights confirmation and delivery timing before submission.",
    notes: "Official public research confirmed CD Baby distributes music worldwide to 150+ services and lists one-time setup pricing starting at $9.99 per release. No account, submission, upload or payment action was performed."
  },
  {
    name: "TuneCore Unlimited Digital Music Distribution Account Submission Route",
    websiteUrl: "https://www.tunecore.com/",
    submissionUrl: "https://web.tunecore.com/",
    sourceUrl: "https://www.tunecore.com/",
    sourceType: "automation_run_115_public_research",
    country: "United States / Global independent digital music distribution route",
    language: "en",
    genres: ["tunecore", "digital-distribution", "spotify", "apple-music", "tiktok", "youtube", "tidal", "tencent", "beatport", "electronic", "reggae", "dub", "world", "paid-route", "account-boundary", "payment-required", "manual-review"],
    submissionMethod: "official-tunecore-unlimited-digital-music-distribution-account-submission-route",
    feeRequired: true,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because TuneCore is a paid account-based distribution route requiring subscription approval, release setup, platform selection, ownership checks, metadata and splits decisions.",
    notes: "Official public research confirmed TuneCore offers distribution to Spotify, Apple Music, TikTok, YouTube, Tidal, Tencent and more, with unlimited releases starting at $24.99/year. No account, submission, upload or payment action was performed."
  },
  {
    name: "LANDR Distribution Release Wizard and Playlist Pitching Route",
    websiteUrl: "https://www.landr.com/",
    submissionUrl: "https://www.landr.com/music-distribution/",
    sourceUrl: "https://www.landr.com/music-distribution/",
    sourceType: "automation_run_115_public_research",
    country: "Canada / Global music distribution and promotion route",
    language: "en",
    genres: ["landr", "music-distribution", "release-wizard", "spotify-preferred-partner", "playlist-pitching", "pre-save", "royalty-splits", "youtube-content-id", "electronic", "reggae", "dub", "world", "paid-route", "account-boundary", "app-boundary", "manual-review"],
    submissionMethod: "official-landr-distribution-release-wizard-playlist-pitching-route",
    feeRequired: true,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because LANDR is an account/app-based paid distribution route with release setup, subscription selection, store delivery, royalty splits, Content ID and promotion decisions.",
    notes: "Official public research confirmed LANDR distributes globally to 150+ stores and streaming platforms and uses a paid app-based release route starting from $2/month. No account, submission, upload or payment action was performed."
  }
];
