import type { PlatformInput } from '../models/types.js';
import { run155SeedPlatforms } from './run155PlatformSeeds.js';

export const run154SeedPlatforms: PlatformInput[] = [
  ...run155SeedPlatforms,
  {
    name: "KFAI Music Department and Music Library Public Email Route",
    websiteUrl: "https://kfai.org/",
    submissionUrl: "https://kfai.org/about/contact/",
    sourceUrl: "https://kfai.org/about/contact/",
    sourceType: "automation_run_154_public_research",
    country: "United States / Minneapolis and Saint Paul community radio station with Music Department and Music Library route",
    language: "en",
    genres: ["community-radio", "airplay", "music-library", "multicultural", "electronic", "reggae", "world", "independent", "verified-email-route", "manual-review"],
    submissionMethod: "official-kfai-music-department-music-library-public-email-route",
    feeRequired: false,
    feeAmount: "No music-submission fee observed for the public Music Department and Music Library route.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KFAI asks artists to share music with its Music Department / Music Library route, and the pitch package, stream/download links, FCC-clean context, bio and release metadata must remain owner-controlled.",
    notes: "Public research verified KFAI's official contact page, Music Department & Music Library section, public music-contact route and current 2026 station/blog activity. No contact was sent, no link was delivered and no audio file was transferred."
  },
  {
    name: "KRCL Physical CD and Utah Digital Music Department Submission Route",
    websiteUrl: "https://krcl.org/",
    submissionUrl: "https://krcl.org/about/how-to-submit-music/",
    sourceUrl: "https://krcl.org/about/how-to-submit-music/",
    sourceType: "automation_run_154_public_research",
    country: "United States / Salt Lake City, Utah community radio station with physical and local digital music routes",
    language: "en",
    genres: ["community-radio", "airplay", "physical-submission", "local-music", "utah-music", "independent", "electronic", "world", "google-form-boundary", "manual-review"],
    submissionMethod: "official-krcl-physical-cd-utah-digital-music-department-submission-route",
    feeRequired: false,
    feeAmount: "No music-submission fee observed; physical CD submission and Utah-based digital upload route are public, while package and mailing choices remain manual.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KRCL accepts physical CDs with no demo/CD-R guidance, treats received music as station property, uses an external Google Form for Utah-based digital submissions, and gives no reply or airplay guarantee.",
    notes: "Public research verified KRCL's official How to Submit Music page, physical Music Department address, Utah digital upload handoff and active 2026 events/programming context. No Google Form was opened/submitted and no physical package was prepared or mailed."
  },
  {
    name: "KGNU Music Department Contact Form reCAPTCHA Submission Route",
    websiteUrl: "https://kgnu.org/",
    submissionUrl: "https://kgnu.org/contact-us/",
    sourceUrl: "https://kgnu.org/contact-us/",
    sourceType: "automation_run_154_public_research",
    country: "United States / Boulder and Denver, Colorado community radio station with Music department contact route",
    language: "en",
    genres: ["community-radio", "airplay", "music-department", "contact-form", "electronic", "world", "reggae", "independent", "captcha-boundary", "manual-review"],
    submissionMethod: "official-kgnu-music-department-contact-form-recaptcha-route",
    feeRequired: false,
    feeAmount: "No music-submission fee observed for the public Music department contact route.",
    loginRequired: false,
    captchaDetected: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KGNU routes Music inquiries through a public contact form with department selection, message field and reCAPTCHA v3 boundary; no automated form entry or challenge handling is allowed.",
    notes: "Public research verified KGNU's official contact page, Music department option, public staff/DJ contact workflow and current 2026 music programming, playlists and studio-session activity. No form was submitted, no reCAPTCHA/session control was handled and no contact was guessed."
  },
  {
    name: "WUOG 90.5FM Physical Album and Music Director Email Airplay Route",
    websiteUrl: "https://wuog.org/",
    submissionUrl: "https://wuog.org/contact/",
    sourceUrl: "https://wuog.org/contact/",
    sourceType: "automation_run_154_public_research",
    country: "United States / Athens, Georgia student-run college radio station with album airplay consideration route",
    language: "en",
    genres: ["college-radio", "airplay", "album-submission", "physical-submission", "local-music", "independent", "alternative", "verified-email-route", "manual-review"],
    submissionMethod: "official-wuog-physical-album-music-director-email-airplay-route",
    feeRequired: false,
    feeAmount: "No music-submission fee observed; route is album consideration by mail with public Music Director and Local Music Director email context.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WUOG asks artists to mail albums in the appropriate format for music-director review, routes local music separately, and lists public director contacts that should only be used with a curated release package.",
    notes: "Public research verified WUOG's official contact page, Submit Music section, physical album mailing route, public Music Director / Local Music Director email context and current 2026 music blog activity. No email was sent and no package was prepared or mailed."
  },
  {
    name: "KCR College Radio Digital MP3 FCC Clean Email Submission Route",
    websiteUrl: "https://kcr.sdsu.edu/",
    submissionUrl: "https://kcr.sdsu.edu/contact/music-submissions/",
    sourceUrl: "https://kcr.sdsu.edu/contact/music-submissions/",
    sourceType: "automation_run_154_public_research",
    country: "United States / San Diego, California student-run college radio station with digital playlist and DJ library route",
    language: "en",
    genres: ["college-radio", "digital-submission", "airplay", "automated-playlist", "dj-library", "local-music", "electronic", "independent", "verified-email-route", "manual-review"],
    submissionMethod: "official-kcr-college-radio-digital-mp3-fcc-clean-email-route",
    feeRequired: false,
    feeAmount: "No music-submission fee observed for the public digital email route.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KCR requires FCC-clean MP3 files with exact artist-title file naming, discourages status calls, and places accepted tracks into curated automation and the music department for DJ use.",
    notes: "Public research verified KCR's official Music Submissions page, digital-only email route, MP3/FCC-clean/file-naming requirements and active 2026 blog/radio context. No email was sent and no MP3 file was attached or transferred."
  }
];
