import type { PlatformInput } from '../models/types.js';

export const run102SeedPlatforms: PlatformInput[] = [
  {
    name: "WPRK 91.5FM Music Submissions Email Route",
    websiteUrl: "https://wprk.org/",
    submissionUrl: "https://wprk.org/music-submissions/",
    sourceUrl: "https://wprk.org/music-submissions/",
    sourceType: "automation_run_102_public_research",
    country: "United States / Winter Park Orlando Florida college and community radio",
    language: "en",
    genres: ["wprk", "winter-park", "orlando", "college-radio", "community-radio", "basement-radio", "electronic", "edm", "reggae", "world", "hip-hop", "local-global-music", "public-email", "free-first", "manual-review"],
    submissionMethod: "official-wprk-music-submissions-public-email-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WPRK exposes an official music-submissions email route, but outreach still requires station-fit validation, track-link permissions, metadata, clean/radio-edit review, no-attachment handling and human-approved pitch copy.",
    notes: "Public research confirmed WPRK is active with current schedule pages and an official Music Submissions page that asks artists to send music submissions to a public Rollins email address. Relevant show schedule signals include electronic, reggae, world and local/global music programs. No email was sent, no files or links were delivered, no account was used and no SMTP/MX probing was performed."
  },
  {
    name: "KSPC 88.7FM Album and EP Airplay Submission Route",
    websiteUrl: "https://kspc.org/",
    submissionUrl: "https://kspc.org/contact/music-submissions/",
    sourceUrl: "https://kspc.org/contact/music-submissions/",
    sourceType: "automation_run_102_public_research",
    country: "United States / Claremont Los Angeles California college and community radio",
    language: "en",
    genres: ["kspc", "claremont", "los-angeles", "college-radio", "community-radio", "album", "ep", "electronic", "hip-hop", "reggae", "world", "local-independent", "digital-download", "physical-mail", "public-email-redacted", "free-first", "manual-review"],
    submissionMethod: "official-kspc-album-ep-digital-email-and-physical-mail-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KSPC accepts albums and EPs for airplay, rejects singles, demos, cassettes, Spotify/iTunes-only links, non-downloadable streaming routes and substantially AI-generated work, and states it does not accept payment for airplay. Digital package prep, protected/redacted email handling, physical mailing, album/EP eligibility, AI-origin checks, metadata and follow-up timing must remain manual.",
    notes: "Public research confirmed KSPC's official Music Submissions page welcomes all genres, accepts CDs/records by mail and digital music by email with downloadable attachments or cloud links, rejects singles and demos, and explicitly rejects pay-for-play. The fetch layer displayed the email as protected/redacted; it was not decoded or guessed. No email, upload, cloud-link delivery, physical mail, payment or SMTP/MX probing was performed."
  },
  {
    name: "WTJU 91.1FM Genre Music Director Submission Route",
    websiteUrl: "https://www.wtju.net/",
    submissionUrl: "https://www.wtju.net/submit-music/",
    sourceUrl: "https://www.wtju.net/submit-music/",
    sourceType: "automation_run_102_public_research",
    country: "United States / Charlottesville Virginia UVA eclectic community radio",
    language: "en",
    genres: ["wtju", "charlottesville", "uva", "community-radio", "eclectic-radio", "music-directors", "rock", "r-and-b", "hip-hop", "world", "folk", "jazz", "digital-files", "physical-mail", "free-first", "manual-review"],
    submissionMethod: "official-wtju-genre-music-director-digital-and-physical-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WTJU routes music by genre and format, accepts CD, LP, 45 rpm and digital MP3/WAV/FLAC files, but says streaming links are review-only and cannot be added to the broadcast library. Correct genre director selection, file/link permissions, physical address choice, metadata, follow-up timing and volunteer-review expectations require manual handling.",
    notes: "Public research confirmed WTJU's official Submit Music page gives U.S. mail and private-carrier addresses, lists digital file guidance, names genre contacts for Classical, Jazz & Blues, Rock/R&B/Hip-Hop, Folk, World and Other, and shows current July 2026 articles/events on the main site. No email was sent, no files or links were delivered, no physical mail was sent and no SMTP/MX probing was performed."
  },
  {
    name: "WMNF 88.5FM Music Department Upload Form and Email Route",
    websiteUrl: "https://www.wmnf.org/",
    submissionUrl: "https://www.wmnf.org/submit-your-music-to-wmnf/",
    sourceUrl: "https://www.wmnf.org/submit-your-music-to-wmnf/",
    sourceType: "automation_run_102_public_research",
    country: "United States / Tampa Bay Florida listener-supported community radio",
    language: "en",
    genres: ["wmnf", "tampa", "community-radio", "music-department", "upload-form", "public-email", "song-of-the-day", "reggae", "soul", "world", "electronic", "indie", "local-music", "free-first", "manual-review"],
    submissionMethod: "official-wmnf-music-department-upload-form-and-email-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WMNF exposes an official upload form with required artist, contact and music-file fields plus an official Music Department email route. File selection, format/size constraints, local/Tampa context, metadata, release notes, rights, clean/radio edits, consent and pitch copy must be reviewed manually before any submission.",
    notes: "Public research confirmed WMNF's official Submit Your Music page invites artists and representatives to submit for Music Department review, lists musicrelations@wmnf.org, and exposes an upload form accepting mp3, wav, flac, aac, aiff, wma and m4a files up to 50 MB and 5 files. The site also showed current July 2026 activity. No form was submitted, no files were uploaded, no email was sent, no account was used and no SMTP/MX probing was performed."
  },
  {
    name: "KZSU Stanford Music Director Email, Mail and Protected Submission Route",
    websiteUrl: "https://kzsu.stanford.edu/",
    submissionUrl: "https://kzsu.stanford.edu/contact/",
    sourceUrl: "https://kzsu.stanford.edu/contact/",
    sourceType: "automation_run_102_public_research",
    country: "United States / Stanford California freeform college radio",
    language: "en",
    genres: ["kzsu", "stanford", "college-radio", "freeform-radio", "music-director", "music-library", "electronic", "experimental", "world", "reggae", "hip-hop", "physical-mail", "public-email", "turnstile-cookie-boundary", "free-first", "manual-review"],
    submissionMethod: "official-kzsu-music-director-email-mail-and-protected-send-us-music-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KZSU exposes official Music Director email and physical-mail routes, plus a 'send us music' route that resolves to a cookie/session verification boundary. Route choice, anti-bot/session boundary, email copy, physical package prep, genre fit, metadata and library eligibility require manual review.",
    notes: "Public research confirmed KZSU's official contact page lists Music Directors with music@kzsu.stanford.edu, a KZSU Music postal address, a UPS/FedEx address and a 'send us music' link. Opening the music route led to a cookie/session verification page, so no session control was interacted with and no protected route was bypassed. No email was sent, no form was submitted, no files or links were delivered, no physical mail was sent and no SMTP/MX probing was performed."
  }
];
