import type { PlatformInput } from '../models/types.js';

export const run158SeedPlatforms: PlatformInput[] = [
  {
    name: "STMPD RCRDS SoundCloud Original Demo Drop Route",
    websiteUrl: "https://stmpdrcrds.com/",
    submissionUrl: "https://demo.stmpdrcrds.com/",
    sourceUrl: "https://demo.stmpdrcrds.com/",
    sourceType: "automation_run_158_public_research",
    country: "Global / Netherlands-based electronic dance music label and demo-review route",
    language: "en",
    genres: ["electronic", "dance", "edm", "future-bass", "house", "demo-drop", "label-submission", "soundcloud-required", "manual-review", "login-required", "session-boundary"],
    submissionMethod: "official-stmpd-rcrds-soundcloud-original-demo-drop-route",
    feeRequired: false,
    feeAmount: "No submission fee observed on the public demo-drop page; route requires SoundCloud connection/login and original-demo eligibility review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because the route requires SoundCloud login/connection, acceptance of platform terms, original-track eligibility, no-remix/no-bootleg compliance, rights ownership, metadata and label-fit decisions.",
    notes: "Public research verified STMPD RCRDS' official site with current 2026 release activity and the official demo.stmpdrcrds.com Demo Drop route. The page asks for original demo tracks only and uses SoundCloud to listen/review tracks. No login was used, no SoundCloud connection authorized, no upload submitted and no terms/session controls were handled."
  },
  {
    name: "Future House Music Discord Demo Drop Community Route",
    websiteUrl: "https://futurehousemusic.com/",
    submissionUrl: "https://discord.gg/",
    sourceUrl: "https://futurehousemusic.com/",
    sourceType: "automation_run_158_public_research",
    country: "Global / Netherlands-based future house label and house-music community",
    language: "en",
    genres: ["future-house", "house", "tech-house", "bass-house", "electronic", "discord-demo-drop", "remix-competition", "live-feedback", "community-submission", "manual-review", "app-boundary", "login-required"],
    submissionMethod: "official-future-house-music-discord-demo-drop-route",
    feeRequired: false,
    feeAmount: "No direct demo fee observed on the public homepage; route points to Discord/community participation and may require Discord account/session review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because demo submission is routed through a Discord/community session with possible server rules, account identity, channel access and monthly demo-drop/remix/live-feedback conditions.",
    notes: "Public research verified Future House Music's official site, current release/homepage activity, explicit SUBMIT DEMO links to Discord, and community language covering monthly events, remix competitions, demo drops, live feedback sessions and Q&As. No Discord invite/session was joined, no message sent and no demo/file/link was submitted."
  },
  {
    name: "Armada Music Official Demo Drop and A&R Listening Route",
    websiteUrl: "https://www.armadamusic.com/",
    submissionUrl: "https://www.armadamusic.com/",
    sourceUrl: "https://www.armadamusic.com/",
    sourceType: "automation_run_158_public_research",
    country: "Global / Netherlands-based independent dance label and artist-services group",
    language: "en",
    genres: ["dance", "edm", "trance", "progressive-house", "tech-house", "demo-drop", "label-submission", "a-and-r", "publishing", "sync", "manual-review", "session-boundary"],
    submissionMethod: "official-armada-music-demo-drop-a-and-r-route",
    feeRequired: false,
    feeAmount: "No demo fee observed from the public homepage; official Demo drop navigation was observed, but the full submission workflow was not entered.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because the Demo drop route is an A&R/label workflow with track rights, exclusive/non-exclusive status, genre fit, release strategy, publishing/sync implications and any session-gated form steps requiring owner control.",
    notes: "Public research verified Armada Music's official homepage with Demo drop navigation, active featured-release listings, publishing/sync/business sections, and 2025 news about new creative/A&R facilities. The demo route was not submitted or entered beyond public discovery; no files, tracks, links or private data were transferred."
  },
  {
    name: "Radiooooo Global Map Curated Song Upload Route",
    websiteUrl: "https://app.radiooooo.com/",
    submissionUrl: "https://app.radiooooo.com/",
    sourceUrl: "https://app.radiooooo.com/",
    sourceType: "automation_run_158_public_research",
    country: "Global / France-based music discovery map and curated upload community",
    language: "en",
    genres: ["global-music", "music-discovery", "curated-upload", "dj-curation", "producer-curation", "historical-map", "community-upload", "manual-review", "login-required", "payment-side-route", "app-boundary"],
    submissionMethod: "official-radiooooo-app-curated-song-upload-route",
    feeRequired: false,
    feeAmount: "Free/trial access context and subscription side route observed from public sources; exact upload eligibility, account and subscription state require owner review inside the app.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Radiooooo is app/session-based, uses curation, may involve subscription or trial boundaries, and requires correct country/decade metadata, rights ownership and track-selection fit.",
    notes: "Public research verified the official app route and public indexing describing user song/track uploads curated by a community of DJs/producers. The app presented a JavaScript boundary, so no account, app workflow, upload or subscription/trial action was entered."
  },
  {
    name: "Audiotool Free Produce Publish and Community Music Route",
    websiteUrl: "https://www.audiotool.com/",
    submissionUrl: "https://www.audiotool.com/",
    sourceUrl: "https://www.audiotool.com/",
    sourceType: "automation_run_158_public_research",
    country: "Global / Germany-based browser DAW, publishing and creator-community platform",
    language: "en",
    genres: ["browser-daw", "produce-and-publish", "creator-community", "remix", "collaboration", "music-sharing", "electronic", "free-first", "manual-review", "login-required", "app-boundary"],
    submissionMethod: "official-audiotool-free-produce-publish-community-route",
    feeRequired: false,
    feeAmount: "Official public page describes free/no-ads access; account/session is required for studio and publishing functions.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because publishing through Audiotool depends on account/session access, project setup, track rights, remix/collaboration settings, visibility, profile use and community-sharing choices.",
    notes: "Public research verified Audiotool's official site showing Sign in/Get Started/Open Studio routes, Join for free, Produce & Publish Music, Remix & Collaborate, community sharing and current 2026 press/activity statements. No account was created, no studio/app workflow entered and no music/project was published."
  }
];
