import type { PlatformInput } from '../models/types.js';

export const run143SeedPlatforms: PlatformInput[] = [
  {
    name: "KEXP Digital WAV Music Director Airplay Submission Route",
    websiteUrl: "https://www.kexp.org/",
    submissionUrl: "https://www.kexp.org/about/submission-guidelines/",
    sourceUrl: "https://www.kexp.org/about/submission-guidelines/",
    sourceType: "automation_run_143_public_research",
    country: "United States / Seattle and Bay Area listener-powered non-commercial global music-discovery airplay route",
    language: "en",
    genres: ["non-commercial-radio", "eclectic-radio", "independent-music", "electronic", "reggae", "world-music", "digital-wav", "music-director-email", "manual-review"],
    submissionMethod: "official-kexp-music-director-email-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KEXP asks for streaming and WAV download links, focus tracks, clean-edit/FCC notes, lyrics, credits, one-sheet context and optional Pacific Northwest/Bay Area show context; the pitch and file-link package must remain owner-controlled.",
    notes: "Official KEXP Submission Guidelines page, authored by the Music Director, says to digitally submit releases to md@kexp.org with streaming and WAV download links, metadata, clean edits, lyric sheet, credits and bio/one-sheet context. No email was sent, no files or links were delivered and no follow-up was attempted."
  },
  {
    name: "DropTrack Artist Label Targeted Submission Campaign Route",
    websiteUrl: "https://www.droptrack.com/",
    submissionUrl: "https://www.droptrack.com/",
    sourceUrl: "https://www.droptrack.com/",
    sourceType: "automation_run_143_public_research",
    country: "United States / global artist, label, DJ, playlist, blog and radio promotion platform",
    language: "en",
    genres: ["music-promotion", "targeted-submissions", "dj-promo", "playlist-curators", "radio", "blogs", "labels", "email-campaigns", "login-boundary", "payment-boundary", "manual-review"],
    submissionMethod: "official-droptrack-artist-signup-and-campaign-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because DropTrack campaigns involve account/session access, track upload or SoundCloud integration, target-contact selection, campaign copy, analytics permissions, optional playlist placement or advertising spend and pricing-plan choices.",
    notes: "Official DropTrack page describes targeted submissions to labels, DJs, playlist curators, bloggers and radio contacts, email campaigns, analytics, artist signup and pricing routes. No account was created, no campaign was configured, no contacts were selected and no paid option was initiated."
  },
  {
    name: "EmuBands One-Time Premium Digital Release Upload Route",
    websiteUrl: "https://www.emubands.com/",
    submissionUrl: "https://www.emubands.com/",
    sourceUrl: "https://www.emubands.com/",
    sourceType: "automation_run_143_public_research",
    country: "United Kingdom / global digital music distribution route for artists and labels",
    language: "en",
    genres: ["digital-distribution", "spotify", "apple-music", "amazon-music", "release-upload", "royalties", "pricing-boundary", "login-boundary", "manual-review"],
    submissionMethod: "official-emubands-dashboard-signup-release-upload-route",
    feeRequired: true,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because EmuBands distribution requires account access, release metadata, audio/artwork upload, DSP selection, one-time fee versus Premium plan choice, royalty/payment settings and copyright control decisions.",
    notes: "Official EmuBands page describes digital music distribution to leading retailers, sign-up/login routes, one-time setup fees per release or Premium unlimited distribution, 100% royalties and recent 2026 activity. No signup/login was used, no release was configured and no payment was initiated."
  },
  {
    name: "Record Union Global Distribution Release Upload and A&R Network Route",
    websiteUrl: "https://www.recordunion.com/",
    submissionUrl: "https://www.recordunion.com/",
    sourceUrl: "https://www.recordunion.com/",
    sourceType: "automation_run_143_public_research",
    country: "Sweden / global digital distribution and artist-services route",
    language: "en",
    genres: ["digital-distribution", "spotify", "apple-music", "tiktok", "amazon-music", "pandora", "beatport", "release-upload", "a-r-network", "pricing-boundary", "manual-review"],
    submissionMethod: "official-record-union-start-releasing-music-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Record Union distribution involves account/session access, music upload, release date, custom label name, royalty splits, platform delivery, annual pricing tier and optional upgrade decisions such as Pitch Priority or YouTube Content ID.",
    notes: "Official Record Union page says artists can join free and pay when ready to release, upload music to 20+ global music services, choose release dates, keep ownership and use optional professional upgrades. No account was created, no release was uploaded and no paid route was selected."
  },
  {
    name: "Too Lost Delivery Suite Create Release and Priority Pitch Route",
    websiteUrl: "https://toolost.com/",
    submissionUrl: "https://toolost.com/",
    sourceUrl: "https://toolost.com/",
    sourceType: "automation_run_143_public_research",
    country: "United States / global music distribution, marketing, analytics and catalog-management route",
    language: "en",
    genres: ["digital-distribution", "450-plus-platforms", "create-release", "priority-pitch", "publishing", "content-id", "smart-links", "physical-distribution", "login-boundary", "payment-boundary", "manual-review"],
    submissionMethod: "official-too-lost-get-started-create-release-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Too Lost exposes account, dashboard and create-release routes plus distribution, publishing, Content ID, priority pitch, copyright, physical distribution and financing features; rights, metadata, stores, paid options and eligibility must remain owner-controlled.",
    notes: "Official Too Lost page describes delivery to 450+ digital platforms, login/get-started/create-release routes, pricing link, Priority Pitch, publishing, Content ID, physical distribution and catalog tools. No app workflow was entered, no release was created and no paid feature was activated."
  }
];
