import type { PlatformInput } from '../models/types.js';

export const run174SeedPlatforms: PlatformInput[] = [
  {
    name: "Obscure Sound SubmitHub MusoSoup Indie Electronic Blog Submission Route",
    websiteUrl: "https://www.obscuresound.com/",
    submissionUrl: "https://www.obscuresound.com/contact-submissions/",
    sourceUrl: "https://www.obscuresound.com/",
    sourceType: "automation_run_174_public_research",
    country: "United States / global indie music blog route with SubmitHub and MusoSoup submission paths",
    language: "en",
    genres: ["music-blog", "indie", "electronic", "hip-hop", "pop", "rock", "album-features", "track-features", "submithub", "musosoup", "manual-review"],
    submissionMethod: "official-obscure-sound-submithub-musosoup-indie-electronic-blog-submission-route",
    feeRequired: true,
    feeAmount: "Official Obscure Sound page routes submissions through SubmitHub or MusoSoup; external platform credits, campaign fees, free options and exact costs require manual review before use.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because the authorized route leaves Obscure Sound and enters SubmitHub or MusoSoup, where account/session, credits or campaign fees, genre targeting, pitch copy, release links and curator fit must be reviewed before submission.",
    notes: "Public research verified Obscure Sound's active 2026 publishing cadence, genre navigation including electronic and hip-hop, and official Send us your music links to SubmitHub and MusoSoup. No external platform workflow was entered, no credits were purchased and no pitch was submitted."
  },
  {
    name: "TAXI Independent A&R Daily Industry Listings Submission Route",
    websiteUrl: "https://www.taxi.com/",
    submissionUrl: "https://www.taxi.com/submit-music/",
    sourceUrl: "https://www.taxi.com/",
    sourceType: "automation_run_174_public_research",
    country: "United States / global independent A&R membership route for labels, publishers, sync, libraries, advertising and game opportunities",
    language: "en",
    genres: ["a-and-r", "sync-licensing", "film-tv", "music-publishing", "production-libraries", "labels", "ad-agencies", "video-games", "membership", "paid-route", "manual-review"],
    submissionMethod: "official-taxi-independent-ar-daily-industry-listings-submission-route",
    feeRequired: true,
    feeAmount: "TAXI exposes Join/Renew/Member Login and a Submit Music route; membership, submission economics and opportunity-specific requirements require manual owner review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because TAXI is a membership/login route with opportunity-specific industry listings, possible membership/payment decisions, submission-format rules, rights questions and genre/sync targeting choices.",
    notes: "Public research verified TAXI's official independent A&R route, Submit Music navigation, Join/Member Login boundary, record-label/publisher/music-supervisor/library/ad/game routing, free daily music request messaging and March 2026 featured-artist activity. No account was created, no listing was opened behind login and no music was submitted."
  },
  {
    name: "Pond5 Free Contributor Music Upload Licensing Marketplace Route",
    websiteUrl: "https://www.pond5.com/",
    submissionUrl: "https://www.pond5.com/sell-stock-footage",
    sourceUrl: "https://www.pond5.com/sell-stock-footage",
    sourceType: "automation_run_174_public_research",
    country: "United States / global royalty-free stock music contributor and licensing marketplace route",
    language: "en",
    genres: ["stock-music", "sync-licensing", "royalty-free", "music-briefs", "sound-effects", "contributor-marketplace", "free-upload", "identity-verification", "metadata-pricing", "manual-review"],
    submissionMethod: "official-pond5-free-contributor-music-upload-licensing-marketplace-route",
    feeRequired: false,
    feeAmount: "Official Pond5 contributor page states there is no cost to upload work and start selling; account, identity verification, royalty share and payout setup require manual review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Pond5 requires contributor account creation, valid-ID identity verification, file preparation, music metadata, tagging, pricing, legal guidelines, payout method and licensing/royalty review before upload.",
    notes: "Public research verified Pond5's official Sell Your Media and Contributor Portal routes, music and sound-effects media types, create/upload/get-paid workflow, 30% royalty share for music and no-cost upload FAQ. No contributor account was created, no ID verification was attempted and no files were uploaded."
  },
  {
    name: "Musicbed Artist Licensing Roster Contact and JavaScript App Boundary Route",
    websiteUrl: "https://www.musicbed.com/",
    submissionUrl: "https://www.musicbed.com/artists",
    sourceUrl: "https://www.musicbed.com/artists",
    sourceType: "automation_run_174_public_research",
    country: "United States / global curated music licensing artist-roster and support-contact route",
    language: "en",
    genres: ["music-licensing", "sync-licensing", "artist-roster", "cinematic", "electronic", "indie", "ambient", "folk", "contact-route", "javascript-boundary", "manual-review"],
    submissionMethod: "official-musicbed-artist-licensing-roster-contact-js-app-boundary-route",
    feeRequired: false,
    feeAmount: "No artist-submission fee was observed on the public artist roster/contact route; any roster onboarding, licensing or account terms require manual review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Musicbed exposes a curated artist roster, support-contact route, Login/Create Free Account boundary and JavaScript app boundary rather than a plain public upload form; roster fit and permission terms must be checked manually.",
    notes: "Public research verified Musicbed's official artist roster, contact support and phone route, Login/Create Free Account boundary, music licensing context and visible artist catalog signals. No JavaScript app workflow, login, account creation, contact request or file upload was performed."
  },
  {
    name: "AudioJungle Envato Market Start Selling Music Author Upload Route",
    websiteUrl: "https://audiojungle.net/",
    submissionUrl: "https://author.envato.com/",
    sourceUrl: "https://audiojungle.net/",
    sourceType: "automation_run_174_public_research",
    country: "Australia / global Envato Market stock music author route with AudioJungle marketplace review",
    language: "en",
    genres: ["stock-music", "royalty-free", "audiojungle", "envato-market", "music-packs", "music-kits", "sound-effects", "author-upload", "quality-review", "manual-review"],
    submissionMethod: "official-audiojungle-envato-market-start-selling-music-author-upload-route",
    feeRequired: false,
    feeAmount: "No author-submission fee was observed on the public AudioJungle/Envato Author Support pages; account, author terms, tax, quality and upload rules require manual review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because AudioJungle routes potential sellers through Envato Start Selling/Author Hub with sign-in/account, author support, upload methods, tax/account requirements, quality review and marketplace licensing terms.",
    notes: "Public research verified AudioJungle's official marketplace with music, music packs, music kits and sound effects, Start Selling and Sign In links, quality-reviewed creator/item language, and Envato Author Support categories for becoming an author and uploading items. The author hub returned an access boundary; no account, upload, support ticket or sale listing was created."
  }
];