import type { PlatformInput } from '../models/types.js';

export const run100SeedPlatforms: PlatformInput[] = [
  {
    name: "WUOG 90.5FM Music Directors Physical Album Submission Route",
    websiteUrl: "https://wuog.org/",
    submissionUrl: "https://wuog.org/contact/",
    sourceUrl: "https://wuog.org/contact/",
    sourceType: "automation_run_100_public_research",
    country: "United States / Athens Georgia student-run college radio",
    language: "en",
    genres: ["wuog", "athens", "college-radio", "alternative", "small-artists", "music-director", "local-music", "physical-mail", "public-email", "contact-form", "free-first", "manual-review"],
    submissionMethod: "official-wuog-music-director-physical-album-and-public-email-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WUOG requests physical album mailing for airplay consideration and lists Music Director and Local Music Director email routes plus a general contact form. Physical package preparation, local-vs-general routing, album-format choice, contact-form handling, metadata, release context, smaller-artist eligibility and station fit must remain manual.",
    notes: "Public research confirmed WUOG is a student-run 24-hour alternative media outlet that uplifts smaller artists. Its contact page says albums can be mailed to WUOG Music Directors for review and distribution to staff, and lists public Music Director and Local Music Director email routes. No form was submitted, no email was sent, no album or link was delivered, no physical mail was sent and no SMTP/MX probing was performed."
  },
  {
    name: "WRAS Album 88 Current Rotation Music Department Submission Route",
    websiteUrl: "https://www.wrasfm.org/",
    submissionUrl: "https://www.wrasfm.org/contact",
    sourceUrl: "https://www.wrasfm.org/contact",
    sourceType: "automation_run_100_public_research",
    country: "United States / Atlanta Georgia college radio and underground music rotation",
    language: "en",
    genres: ["wras", "album-88", "atlanta", "college-radio", "underground", "local-music", "electronic", "rpm", "urban", "music-director", "public-email", "current-rotation", "free-first", "manual-review"],
    submissionMethod: "official-wras-regular-rotation-music-department-public-email-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WRAS routes regular-rotation music to several public Music Department emails and asks for local Atlanta or generally underground music released in the past four months. The correct music director route, release-age proof, local/underground fit, specialty-show targeting, pitch copy, metadata and clean/radio edits require manual review.",
    notes: "Public research confirmed WRAS/Album 88 is student-operated and active, with specialty shows and current rotation pages. Its contact page lists public Program, Promotions and Regular Rotation music department emails and invites local Atlanta or underground releases from the past four months. No email was sent, no files or links were delivered, no playlist/rotation action was attempted and no SMTP/MX probing was performed."
  },
  {
    name: "Amazing Radio Artist Upload and New Music Airplay Route",
    websiteUrl: "https://amazingradio.com/",
    submissionUrl: "https://amazingradio.com/",
    sourceUrl: "https://amazingradio.com/",
    sourceType: "automation_run_100_public_research",
    country: "United Kingdom / United States / worldwide new and emerging artist radio platform",
    language: "en",
    genres: ["amazing-radio", "new-artists", "emerging-artists", "unsigned", "radio-airplay", "artist-upload", "electronic", "reggae", "world", "independent", "javascript-app", "login-required", "free-first", "manual-review"],
    submissionMethod: "official-amazing-radio-artist-upload-web-app-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Amazing Radio's public site is a JavaScript application and artist uploading/submission is handled inside the app boundary. Account/session handling, upload permissions, artist profile, rights verification, metadata, track choice and platform fit require manual review.",
    notes: "Public research confirmed Amazing Radio is an international station focused on new and emerging artists, and historical reference material describes its website as the current route for artist music submission. The official site loaded only a JavaScript-required application shell in this fetch, so no app interaction, account creation, login, upload, file transfer or form submission was attempted."
  },
  {
    name: "TIDAL Upload Direct Artist Upload Route",
    websiteUrl: "https://artists.tidal.com/",
    submissionUrl: "https://artists.tidal.com/",
    sourceUrl: "https://artists.tidal.com/",
    sourceType: "automation_run_100_public_research",
    country: "United States / global high-fidelity streaming and direct artist upload platform",
    language: "en",
    genres: ["tidal", "tidal-upload", "artist-home", "direct-upload", "independent-artists", "electronic", "reggae", "dub", "world", "private-sharing", "rights-check", "login-required", "free-first", "manual-review"],
    submissionMethod: "official-tidal-artist-home-direct-upload-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because TIDAL Artist Home requires sign-up/login before creator-profile management, and TIDAL Upload requires rights ownership, metadata, track/public-private settings, territory or eligibility checks, AI-origin labeling/royalty implications and copyright-compliance review. Account/session and upload handling must remain manual.",
    notes: "Public research confirmed TIDAL Artist Home presents an official creator-profile login/sign-up route, and recent reporting describes TIDAL Upload as a free direct-upload feature for independent artists with rights, metadata and no-streaming-royalty caveats. No account was created, no login was used, no track was uploaded, no profile was changed, no payment was made and no SMTP/MX probing was performed."
  },
  {
    name: "SoundOn TikTok Music Distribution Artist Upload Route",
    websiteUrl: "https://www.soundon.global/",
    submissionUrl: "https://www.soundon.global/",
    sourceUrl: "https://www.soundon.global/",
    sourceType: "automation_run_100_public_research",
    country: "Global / TikTok-owned music marketing and distribution platform",
    language: "en",
    genres: ["soundon", "tiktok", "music-distribution", "artist-upload", "independent-artists", "electronic", "dance", "reggae", "world", "social-music", "royalties", "login-required", "free-first", "manual-review"],
    submissionMethod: "official-soundon-artist-upload-and-music-distribution-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because SoundOn is a music distribution and artist-services platform with account, upload, copyright, distribution-scope, royalty-share, territory and TikTok/third-party platform choices. Account creation, login/session handling, release metadata, rights checks, distribution settings and payout/tax implications must remain manual.",
    notes: "Public research confirmed SoundOn is a TikTok-owned music marketing and distribution platform for artist uploads and distribution, with copyright-retention and royalty mechanics described in public reference material. The official homepage was observed but did not expose a safe complete static auto-submit endpoint in this fetch. No account was created, no login was used, no release was uploaded, no distribution route was activated and no SMTP/MX probing was performed."
  }
];
