import type { PlatformInput } from '../models/types.js';

export const run130SeedPlatforms: PlatformInput[] = [
  {
    name: "KDVS Davis Physical-Only Music Department Airplay Submission Route",
    websiteUrl: "https://kdvs.org/",
    submissionUrl: "mailto:musicdept@kdvs.org",
    sourceUrl: "https://kdvs.org/contact",
    sourceType: "automation_run_130_public_research",
    country: "US / Davis freeform college and community radio physical-only music department airplay route",
    language: "en",
    genres: ["kdvs", "uc-davis", "college-radio", "community-radio", "freeform", "music-department", "physical-submission", "record-label-contact", "new-music", "manual-review"],
    submissionMethod: "official-kdvs-davis-physical-only-music-department-airplay-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KDVS publishes an official Music Department contact and states new music should be sent to its mailing address as physical submissions only. Media choice, package preparation, mailing, metadata, label context, follow-up timing and any email contact must remain owner-controlled.",
    notes: "Official public research confirmed KDVS is active, publishes current staff and department contacts, lists musicdept@kdvs.org for music review/library/mail-sorting/record-label contact, and says to send all new music to the mailing address as physical submissions only. No email was sent, no package was prepared and no physical mail was sent."
  },
  {
    name: "KZSC Santa Cruz Music Submission Contact Form and Package Route",
    websiteUrl: "https://kzsc.org/",
    submissionUrl: "https://kzsc.org/send-us-a-message/",
    sourceUrl: "https://kzsc.org/send-us-a-message/",
    sourceType: "automation_run_130_public_research",
    country: "US / Santa Cruz college radio music submission contact-form and package route",
    language: "en",
    genres: ["kzsc", "santa-cruz", "college-radio", "music-director", "music-submission-form", "contact-form", "physical-package", "mailing-route", "manual-review"],
    submissionMethod: "official-kzsc-santa-cruz-music-submission-contact-form-package-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KZSC exposes a public contact form with a Music Submission option and separate package mailing instructions for Music Directors. Form text, package contents, mailing method, release metadata and music-fit decisions must remain owner-reviewed.",
    notes: "Official public research confirmed KZSC is active in 2026, publishes recent music/news posts, exposes a Send Us a Message form with a Music Submission option, and lists package addresses for Music Directors. No form was submitted, no message was sent, no package was prepared and no physical mail was sent."
  },
  {
    name: "KSPC Claremont Album EP Digital Physical Music Submission Route",
    websiteUrl: "https://kspc.org/",
    submissionUrl: "https://kspc.org/contact/music-submissions/",
    sourceUrl: "https://kspc.org/contact/music-submissions/",
    sourceType: "automation_run_130_public_research",
    country: "US / Claremont college radio album and EP digital or physical airplay route",
    language: "en",
    genres: ["kspc", "claremont", "college-radio", "airplay", "music-submissions", "album", "ep", "digital-submission", "physical-submission", "no-singles", "no-ai-music", "no-pay-for-play", "manual-review"],
    submissionMethod: "official-kspc-claremont-album-ep-digital-physical-music-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KSPC accepts albums and EPs for airplay by mailed CD/record or downloadable digital submission, explicitly excludes singles, demos, cassettes, Spotify/iTunes-only links and substantially AI-generated work, and states there is no payment for airplay. Release format, AI-origin review, downloadability, metadata and follow-up should remain manual.",
    notes: "Official public research confirmed KSPC publishes a Music Submissions page welcoming all genres for airplay consideration, accepts CDs/records by mail and digital music by email/cloud download, rejects non-downloadable streams, singles, demos, cassette tapes and AI music, and states it is noncommercial and does not accept payment for airplay. No protected email was decoded, no email was sent, no file or link was delivered and no package was prepared."
  },
  {
    name: "WMFO Tufts Music Director Digital Physical Library Submission Route",
    websiteUrl: "https://www.wmfo.org/",
    submissionUrl: "mailto:md@wmfo.org",
    sourceUrl: "https://www.wmfo.org/contact/",
    sourceType: "automation_run_130_public_research",
    country: "US / Medford freeform college radio Music Director and music-library route",
    language: "en",
    genres: ["wmfo", "tufts", "freeform-radio", "music-director", "music-department", "digital-media", "cd", "vinyl", "cassette", "library-curation", "manual-review"],
    submissionMethod: "official-wmfo-tufts-music-director-digital-physical-library-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WMFO exposes a public Music Director contact and describes a Music Department that receives CDs, vinyl and cassettes while adding digital media to its database. Pitch copy, media format, package choice, link/file delivery and follow-up must remain owner-controlled.",
    notes: "Official public research confirmed WMFO is active in 2026, publishes a current 2025-2026 staff contact page with Music Director md@wmfo.org, and describes a Music Department handling CDs, vinyl, cassette and digital media. No email was sent, no file or link was delivered and no package was prepared."
  },
  {
    name: "WZBC Boston College Programming Promotion Contact Submission Route",
    websiteUrl: "https://www.wzbc.org/",
    submissionUrl: "mailto:wzbcpd@gmail.com",
    sourceUrl: "https://www.wzbc.org/",
    sourceType: "automation_run_130_public_research",
    country: "US / Newton Boston College radio programming and promotion contact route",
    language: "en",
    genres: ["wzbc", "boston-college", "college-radio", "alternative", "experimental", "no-commercial-potential", "programming", "promotion", "contact-form", "manual-review"],
    submissionMethod: "official-wzbc-boston-college-programming-promotion-contact-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WZBC exposes public programming, promotions and station contact routes rather than a safe dedicated auto-submit form. Program fit, department choice, message copy, download/stream-link delivery and follow-up must remain owner-reviewed.",
    notes: "Official public research confirmed WZBC is active, identifies itself as Boston College's student-run radio station, publishes a contact form for programming/promotions/concert questions and lists public station contacts including a programming email. No form was submitted, no email was sent, no link or file was delivered and no package was prepared."
  }
];
