import type { PlatformInput } from '../models/types.js';

export const run101SeedPlatforms: PlatformInput[] = [
  {
    name: "KFAI Music Department and Music Library Submission Email Route",
    websiteUrl: "https://www.kfai.org/",
    submissionUrl: "https://kfai.org/about/contact/",
    sourceUrl: "https://kfai.org/about/contact/",
    sourceType: "automation_run_101_public_research",
    country: "United States / Minneapolis-Saint Paul volunteer-based community radio",
    language: "en",
    genres: ["kfai", "minneapolis", "saint-paul", "community-radio", "fresh-air-radio", "music-library", "music-department", "world", "reggae", "electronic", "community-music", "public-email", "free-first", "manual-review"],
    submissionMethod: "official-kfai-music-department-and-music-library-public-email-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KFAI exposes an official public Music Department and Music Library email route, but outreach still requires track-link permission checks, metadata, clean/radio-edit review, genre/show fit, release context, non-attachment handling and human-approved pitch copy.",
    notes: "Public research confirmed KFAI is an active volunteer-based community radio station with current programming and 2026 site signals. Its official contact page invites artists to share music with the KFAI Music Department and Music Library through a public email route. No email was sent, no files or links were delivered, no account was used and no SMTP/MX probing was performed."
  },
  {
    name: "WNCW Programming Department CD and Digital Music Submission Route",
    websiteUrl: "https://www.wncw.org/",
    submissionUrl: "https://www.wncw.org/submit-music/",
    sourceUrl: "https://www.wncw.org/submit-music/",
    sourceType: "automation_run_101_public_research",
    country: "United States / North Carolina public radio and roots/eclectic music station",
    language: "en",
    genres: ["wncw", "north-carolina", "public-radio", "roots", "world", "reggae", "soul", "electronic-adjacent", "programming-department", "digital-download", "physical-cd", "public-email", "free-first", "manual-review"],
    submissionMethod: "official-wncw-programming-department-cd-and-digital-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WNCW accepts physical CDs and digital WAV/MP3 download links through its Programming Department, but package format, one-sheet content, download permissions, clean/radio edits, release type, metadata and no-airplay-guarantee acknowledgement must be checked manually.",
    notes: "Public research confirmed WNCW's official Submit Music page describes authorized CD and digital routes, asks digital submitters to use Dropbox or Google Drive links for WAV/MP3 files, and says DJs review daily but airplay is not guaranteed. No email was sent, no links were delivered, no physical package was sent, no account was used and no SMTP/MX probing was performed."
  },
  {
    name: "Radio Boise Submit Your Music Public Form Route",
    websiteUrl: "https://radioboise.org/",
    submissionUrl: "https://radioboise.org/submit-music/",
    sourceUrl: "https://radioboise.org/submit-music/",
    sourceType: "automation_run_101_public_research",
    country: "United States / Boise Idaho community radio and global streaming station",
    language: "en",
    genres: ["radio-boise", "boise", "community-radio", "independent", "local-music", "world", "reggae", "electronic", "dj", "submit-your-music", "public-form", "javascript-form", "free-first", "manual-review"],
    submissionMethod: "official-radio-boise-submit-your-music-public-form-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Radio Boise exposes an official Submit Your Music page, but the static fetch only showed a loading boundary instead of safe complete form fields. Any embedded form, validation, file/link fields, consent controls, metadata, local/global fit and session behavior must be handled manually.",
    notes: "Public research confirmed Radio Boise's official navigation links to Submit Your Music and its site shows current 2026 activity, playlists and global streaming language. The submission page loaded only a public route shell in this fetch, so no form interaction, upload, email, file transfer, account action or SMTP/MX probing was performed."
  },
  {
    name: "KGNU Community Radio Music Department Contact Form Route",
    websiteUrl: "https://kgnu.org/",
    submissionUrl: "https://kgnu.org/contact-us/",
    sourceUrl: "https://kgnu.org/contact-us/",
    sourceType: "automation_run_101_public_research",
    country: "United States / Boulder-Denver Colorado independent noncommercial community radio",
    language: "en",
    genres: ["kgnu", "boulder", "denver", "community-radio", "independent-radio", "music-department", "contact-form", "recaptcha-v3", "protected-email", "world", "reggae", "electronic", "free-first", "manual-review"],
    submissionMethod: "official-kgnu-music-department-contact-form-and-protected-email-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KGNU's official contact page includes a department selector with Music plus reCaptcha v3, and the page exposes protected/redacted department email routes that must not be decoded or guessed. Form use, CAPTCHA handling, routing, metadata and pitch copy require manual review.",
    notes: "Public research confirmed KGNU is active with current 2026 site signals, live programming, recent playlists and public contact routes. Its official contact page exposes a Music department option in the contact form and reCaptcha v3 protection. No form was submitted, no CAPTCHA was interacted with, no protected contacts were decoded, no email was sent and no SMTP/MX probing was performed."
  },
  {
    name: "KBCS Music Director and Music Librarian Public Music Contact Route",
    websiteUrl: "https://www.kbcs.fm/",
    submissionUrl: "https://www.kbcs.fm/about/staff/",
    sourceUrl: "https://www.kbcs.fm/about/staff/",
    sourceType: "automation_run_101_public_research",
    country: "United States / Bellevue-Seattle Washington community radio",
    language: "en",
    genres: ["kbcs", "bellevue", "seattle", "community-radio", "music-director", "music-librarian", "music-requests", "world", "reggae", "electronic", "local-music", "public-email", "free-first", "manual-review"],
    submissionMethod: "official-kbcs-music-director-and-music-librarian-public-contact-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KBCS exposes public Music Director, Music Librarian and music-request routes, but the pages do not provide a complete static auto-submit policy. Correct routing, whether unsolicited submissions are appropriate, track-link permissions, metadata, local/show fit and pitch copy require manual verification before outreach.",
    notes: "Public research confirmed KBCS has current 2026 activity and public music-related staff/contact routes, including Music Director, Music Librarian and music-request contacts. Because the observed pages are contact routes rather than a full automated submission form, no email was sent, no files or links were delivered, no account was used and no SMTP/MX probing was performed."
  }
];
