import type { PlatformInput } from '../models/types.js';

export const run124SeedPlatforms: PlatformInput[] = [
  {
    name: "Sonicbids Rebooted EPK Live Booking and Venue Submission Route",
    websiteUrl: "https://sonicbids.com/",
    submissionUrl: "https://app.sonicbids.com/signup",
    sourceUrl: "https://sonicbids.com/",
    sourceType: "automation_run_124_public_research",
    country: "Global / live booking EPK venue submission and artist opportunity route",
    language: "en",
    genres: ["sonicbids", "epk", "live-booking", "venues", "festival-opportunities", "artist-profile", "booking-submissions", "login", "unknown-pricing", "manual-review"],
    submissionMethod: "official-sonicbids-rebooted-epk-live-booking-venue-submission-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Sonicbids routes artists through account sign-up, EPK claiming/building, profile data, live-performance history, venue or slot applications and booking workflow choices. The current public site states submissions and partner tools are rolling out next, so account/session access, opportunity fit, profile claims and any future pricing boundaries need owner review.",
    notes: "Official public research confirmed Sonicbids is active in 2026, lists artist sign-up/sign-in routes, says artists can claim a new EPK, and describes future booking submissions by slot, night or general interest. No account was created, no EPK was claimed, no opportunity was selected and no application was sent."
  },
  {
    name: "Syncr Music Brand Brief Upload Submit and Sync Opportunity Route",
    websiteUrl: "https://www.syncrmusic.com/",
    submissionUrl: "https://www.syncrmusic.com/",
    sourceUrl: "https://www.syncrmusic.com/",
    sourceType: "automation_run_124_public_research",
    country: "Global / brand brief sync playlist gig radio interview and publishing opportunity route",
    language: "en",
    genres: ["syncr", "sync-briefs", "brand-briefs", "upload-tracks", "submit-to-briefs", "playlisting", "radio-play", "publishing", "free-first", "login", "manual-review"],
    submissionMethod: "official-syncr-music-brand-brief-upload-submit-sync-opportunity-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Syncr requires account sign-up/login, track upload, brief selection, brand-fit review, rights clearance and progress tracking. Brief eligibility, sync rights, metadata, publisher/master ownership and any follow-up licensing terms must remain owner-reviewed.",
    notes: "Official public research confirmed Syncr is active in 2026, offers free signup, collects brand briefs, lets artists upload tracks and submit to briefs, and reports outcomes including playlisting, gigs, radio play, interviews, signings and publishing deals. No account was opened, no track was uploaded and no brief was submitted."
  },
  {
    name: "Feature.fm Artist Smart Link Pre-Save Fan Activation and Campaign Route",
    websiteUrl: "https://feature.fm/",
    submissionUrl: "https://feature.fm/",
    sourceUrl: "https://feature.fm/",
    sourceType: "automation_run_124_public_research",
    country: "Global / independent artist smart-link pre-save fan activation and music marketing route",
    language: "en",
    genres: ["feature-fm", "music-marketing", "smart-links", "pre-save", "release-links", "artist-bio-links", "fan-data", "analytics", "free-first", "login", "manual-review"],
    submissionMethod: "official-feature-fm-artist-smart-link-presave-fan-activation-campaign-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Feature.fm involves login/account setup, artist bio links, release links, pre-save links, contest/unlock pages, fan-data capture, analytics and campaign publishing. Fan consent, data collection, release timing, link destinations, ad/retargeting choices and any plan upgrades need owner review.",
    notes: "Official public research confirmed Feature.fm is active, markets itself as a music marketing platform for independent artists, exposes Start for free routes, and lists artist bio links, release links, pre-save links, contest/unlock pages, fan-base management and analytics. No login was used, no link was created and no campaign was published."
  },
  {
    name: "DISCO Artist Catalog Share Receive Track and Supervisor Pitch Route",
    websiteUrl: "https://www.disco.ac/",
    submissionUrl: "https://www.disco.ac/",
    sourceUrl: "https://www.disco.ac/",
    sourceType: "automation_run_124_public_research",
    country: "Global / artist catalog sharing pitching music supervisor and promotion workflow route",
    language: "en",
    genres: ["disco", "catalog-management", "music-supervisors", "rights-holders", "artists-creators", "marketing-promotions", "share-receive-track", "sync-pitching", "free-trial", "login", "manual-review"],
    submissionMethod: "official-disco-artist-catalog-share-receive-track-supervisor-pitch-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because DISCO requires account/free-trial access, catalog upload or import, rights-holder metadata, pitch/share links, listening analytics and possible pricing/trial decisions. Music-supervisor targeting, permission controls, downloadable assets and catalog rights must remain owner-reviewed.",
    notes: "Official public research confirmed DISCO is active in 2026, offers a no-credit-card free trial, supports artists and creators, rights holders, music supervisors, A&R and marketing/promotions, and describes sending/receiving/tracking music plus pitching tracks. No trial was started, no catalog was uploaded and no pitch/share link was sent."
  },
  {
    name: "TopHit Radio TV Music Distribution Airplay Testing and Chart Route",
    websiteUrl: "https://tophit.com/",
    submissionUrl: "https://tophit.com/",
    sourceUrl: "https://tophit.com/",
    sourceType: "automation_run_124_public_research",
    country: "Global / radio television digital music distribution airplay testing and chart-monitoring route",
    language: "en",
    genres: ["tophit", "radio-distribution", "tv-channels", "airplay-testing", "charts", "music-arrivals", "rights-holders", "labels", "djs", "upload", "login", "manual-review"],
    submissionMethod: "official-tophit-radio-tv-music-distribution-airplay-testing-chart-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because TopHit routes rights holders through registration/login, music or video upload, radio/TV distribution, test ratings, rights-holder statistics and regional airplay/market fit. Territory suitability, metadata, release rights, language/clean edits and any platform terms require owner review.",
    notes: "Public research confirmed TopHit is an active worldwide-oriented platform where artists, songwriters, DJs, labels and publishers upload music for radio/TV review and distribution; sources report 9,000+ rightsholders and 2,500+ radio stations/90 TV channels across 45 countries. No registration was attempted, no track or video was uploaded and no radio/TV delivery was made."
  }
];
