import type { PlatformInput } from '../models/types.js';
import { run162SeedPlatforms } from './run162PlatformSeeds.js';

export const run161SeedPlatforms: PlatformInput[] = [
  {
    name: "WFUV New York Music Department Snail Mail Airplay Submission Route",
    websiteUrl: "https://wfuv.org/",
    submissionUrl: "https://wfuv.org/contactus",
    sourceUrl: "https://wfuv.org/contactus",
    sourceType: "automation_run_161_public_research",
    country: "United States / New York public radio music-discovery station with global streaming reach",
    language: "en",
    genres: ["public-radio", "new-york", "aaa", "indie", "folk", "roots", "world", "latin", "celtic", "physical-submission", "music-department", "manual-review"],
    submissionMethod: "official-wfuv-music-department-snail-mail-airplay-submission-route",
    feeRequired: false,
    feeAmount: "No submission fee observed; official WFUV Contact & Staff guidance says to send music by snail mail to the Music Department at the public station address and provides a follow-up call window.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WFUV's safe public route is physical/snail-mail music servicing, while staff email links are protected; owner must verify format, release fit, clean/explicit notes, one-sheet, rights, follow-up timing and whether a physical package is worthwhile.",
    notes: "Public research verified the official WFUV site, active on-air/listen-live context, current live-session/editorial activity, Contact & Staff page, station address and Send Music guidance. Protected staff email links were not decoded. No email was sent, no links/files were delivered and no physical package was prepared or mailed."
  },
  {
    name: "KVRX Austin Physical Digital Music Department Submission Route",
    websiteUrl: "https://www.kvrx.org/app/",
    submissionUrl: "https://www.kvrx.org/app/contact/",
    sourceUrl: "https://www.kvrx.org/app/contact/",
    sourceType: "automation_run_161_public_research",
    country: "United States / Austin student-run underground music station with 91.7 FM and online reach",
    language: "en",
    genres: ["college-radio", "austin", "underground", "local-discovery", "electronic", "hip-hop", "reggae", "world", "physical-submission", "digital-submission", "music-department-email", "manual-review"],
    submissionMethod: "official-kvrx-physical-digital-music-department-submission-route",
    feeRequired: false,
    feeAmount: "No submission fee observed; official contact page says KVRX is currently taking both physical and digital submissions and routes all music submissions to music@kvrx.org.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KVRX explicitly excludes AI-assisted or AI-generated music from music submissions, and the owner must verify rights, authorship, format, clean/explicit notes, underground fit, metadata, one-sheet and physical-vs-digital route before contact.",
    notes: "Public research verified KVRX's official site, 91.7 FM Austin/student-run underground identity, active live/on-air context, contact page, music@kvrx.org submission email and physical/digital acceptance language. No email was sent, no files or links were delivered and no package was prepared."
  },
  {
    name: "WCBN Ann Arbor Hard Copy Music Director Library Submission Route",
    websiteUrl: "https://wcbn.org/",
    submissionUrl: "https://wcbn.org/c/",
    sourceUrl: "https://wcbn.org/c/",
    sourceType: "automation_run_161_public_research",
    country: "United States / Ann Arbor freeform University of Michigan student-run radio station",
    language: "en",
    genres: ["college-radio", "freeform", "ann-arbor", "experimental", "electronic", "hip-hop", "jazz", "world", "hard-copy", "music-director", "genre-routed", "manual-review"],
    submissionMethod: "official-wcbn-hard-copy-music-director-library-submission-route",
    feeRequired: false,
    feeAmount: "No submission fee observed; official contact guidance says WCBN accepts music from any/all musicians willing to send a hard copy album, preferably CD or vinyl, with genre-specific care-of routing when appropriate.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WCBN's public safe route is hard-copy library servicing with optional genre care-of routing, while director email links are protected; owner must verify album format, CD/vinyl availability, genre routing, clean/explicit notes, one-sheet and mailing choice.",
    notes: "Public research verified WCBN's official site, 24/7 broadcast and freeform University of Michigan station identity, recent/current content activity, public contact page, mailing address and hard-copy album submission guidance. Protected email links were not decoded. No email was sent, no links/files were delivered and no physical package was prepared or mailed."
  },
  {
    name: "Amazing Radio Emerging Artist Website Upload App Boundary Route",
    websiteUrl: "https://amazingradio.com/",
    submissionUrl: "https://amazingradio.com/",
    sourceUrl: "https://amazingradio.com/",
    sourceType: "automation_run_161_public_research",
    country: "Global / UK and US emerging-artist internet radio and discovery platform",
    language: "en",
    genres: ["internet-radio", "emerging-artists", "unsigned", "independent", "pop", "electronic", "indie", "global", "website-upload", "app-boundary", "manual-review"],
    submissionMethod: "official-amazing-radio-emerging-artist-website-upload-app-boundary-route",
    feeRequired: false,
    feeAmount: "No submission fee confirmed during this run; public indexing describes artist submission via the Amazing Radio website, but the official site was JavaScript-gated during safe discovery.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because the official Amazing Radio site is JavaScript/app-gated, and the artist upload process likely requires account/session handling, rights metadata, profile setup and track selection. No app workflow was entered.",
    notes: "Public research verified the official Amazing Radio domain, international emerging-artist positioning and historical/current artist-upload model. The official page returned a JavaScript application boundary, so no login, upload, form submission or session workflow was attempted."
  },
  {
    name: "TopHit Global Radio TV Music Upload Platform Review Route",
    websiteUrl: "https://tophit.com/",
    submissionUrl: "https://tophit.com/",
    sourceUrl: "https://tophit.com/",
    sourceType: "automation_run_161_public_research",
    country: "Global / radio, television and label-facing music distribution and airplay-monitoring platform",
    language: "en",
    genres: ["radio-servicing", "tv-servicing", "music-distribution", "airplay-monitoring", "charts", "pop", "dance", "electronic", "latin", "global", "registration-boundary", "manual-review"],
    submissionMethod: "official-tophit-global-radio-tv-music-upload-platform-review-route",
    feeRequired: false,
    feeAmount: "No submission fee was safely confirmed during this run; public platform descriptions state rights holders register/upload works for radio and TV channel review, while the official site returned a 403 boundary during safe discovery.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because TopHit is a registration/upload platform for rights holders and media review, the official site returned an access boundary, and terms, geography, pricing, rights, metadata and suitability must be checked by the owner before any account or upload action.",
    notes: "Public research verified TopHit as an active global radio/TV music delivery and monitoring platform through public indexed material, but the official site returned a 403 boundary. No boundary was bypassed, no account was created, no form was submitted, no audio/video was uploaded and no payment route was entered."
  },
  ...run162SeedPlatforms
];
