import type { PlatformInput } from '../models/types.js';
import { run154SeedPlatforms } from './run154PlatformSeeds.js';

export const run153SeedPlatforms: PlatformInput[] = [
  {
    name: "Radio K KUOM Lossless Digital and Physical Airplay Submission Route",
    websiteUrl: "https://radiok.org/",
    submissionUrl: "https://radiok.org/submitting-music",
    sourceUrl: "https://radiok.org/submitting-music",
    sourceType: "automation_run_153_public_research",
    country: "United States / Minneapolis, Minnesota college radio station with independent music airplay route",
    language: "en",
    genres: ["college-radio", "airplay", "independent", "electronic", "reggae", "world", "lossless-audio", "physical-submission", "verified-email-route", "manual-review"],
    submissionMethod: "official-radio-k-kuom-lossless-digital-physical-airplay-submission-route",
    feeRequired: false,
    feeAmount: "No submission fee observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Manual review is required for station fit, release package, lossless audio preference and optional physical package decisions.",
    notes: "Run 153 verified the official public route and queued it for owner review."
  },
  {
    name: "KCSB Artist Inquiry Library Airplay Live Session Premiere Form Route",
    websiteUrl: "https://www.kcsb.org/",
    submissionUrl: "https://www.kcsb.org/contact/artist-inquiry/",
    sourceUrl: "https://www.kcsb.org/contact/artist-inquiry/",
    sourceType: "automation_run_153_public_research",
    country: "United States / Santa Barbara, California college and community radio station with artist inquiry and library-add route",
    language: "en",
    genres: ["college-radio", "community-radio", "airplay", "artist-inquiry", "live-session", "premiere", "dj", "independent", "external-form-boundary", "manual-review"],
    submissionMethod: "official-kcsb-artist-inquiry-library-airplay-live-session-premiere-form-route",
    feeRequired: false,
    feeAmount: "No submission fee observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Manual review is required for artist inquiry use case, public form boundary, release data and availability decisions.",
    notes: "Run 153 verified the official public route and queued it for owner review."
  },
  {
    name: "KXCI Tucson Music Department Global Digital Physical Airplay Submission Route",
    websiteUrl: "https://kxci.org/",
    submissionUrl: "https://kxci.org/about/music-department/",
    sourceUrl: "https://kxci.org/about/music-department/",
    sourceType: "automation_run_153_public_research",
    country: "United States / Tucson, Arizona community radio station accepting local, regional and worldwide music submissions",
    language: "en",
    genres: ["community-radio", "airplay", "electronic", "world", "reggae", "roots", "local-music", "global-submission", "physical-submission", "verified-email-route", "manual-review"],
    submissionMethod: "official-kxci-music-department-global-digital-physical-airplay-submission-route",
    feeRequired: false,
    feeAmount: "No music-submission fee observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Manual review is required for metadata, explicit-language notes, release links and optional physical package decisions.",
    notes: "Run 153 verified the official public route and queued it for owner review."
  },
  {
    name: "WXPN EPK Digital Download Airplay and Local Show Submission Route",
    websiteUrl: "https://xpn.org/",
    submissionUrl: "https://xpn.org/contact/",
    sourceUrl: "https://xpn.org/contact/",
    sourceType: "automation_run_153_public_research",
    country: "United States / Philadelphia, Pennsylvania public radio station with airplay and Local Show submission contacts",
    language: "en",
    genres: ["public-radio", "airplay", "local-show", "epk", "release-link", "independent", "alternative", "world-cafe", "verified-email-route", "manual-review"],
    submissionMethod: "official-wxpn-epk-digital-download-airplay-local-show-submission-route",
    feeRequired: false,
    feeAmount: "No music-submission fee observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Manual review is required for EPK details, release link choice, local-show context and audio-quality decisions.",
    notes: "Run 153 verified the official public route and queued it for owner review."
  },
  {
    name: "KBOO Portland Genre-Routed Physical Music Submission Route",
    websiteUrl: "https://www.kboo.fm/",
    submissionUrl: "https://www.kboo.fm/submit-your-music",
    sourceUrl: "https://www.kboo.fm/submit-your-music",
    sourceType: "automation_run_153_public_research",
    country: "United States / Portland, Oregon volunteer-driven community radio station with genre-routed physical music submission route",
    language: "en",
    genres: ["community-radio", "airplay", "physical-submission", "electronic", "rock", "punk", "jazz", "hip-hop", "world", "reggae", "manual-review"],
    submissionMethod: "official-kboo-portland-genre-routed-physical-music-submission-route",
    feeRequired: false,
    feeAmount: "No music-submission fee observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Manual review is required for physical-only package choice, genre routing and station-fit decisions.",
    notes: "Run 153 verified the official public route and queued it for owner review."
  },
  ...run154SeedPlatforms
];
