import type { PlatformInput } from '../models/types.js';

export const run171SeedPlatforms: PlatformInput[] = [
  {
    name: "KBOO Portland Physical Genre Routed Emerging Music Submission Route",
    websiteUrl: "https://www.kboo.fm/",
    submissionUrl: "https://www.kboo.fm/submit-music",
    sourceUrl: "https://www.kboo.fm/submit-music",
    sourceType: "automation_run_171_public_research",
    country: "United States / Portland community radio physical music submission route with genre-routed music staff attention lines",
    language: "en",
    genres: ["community-radio", "freeform-radio", "emerging-artists", "electronic", "reggae", "world-music", "hip-hop", "jazz", "folk", "rock", "physical-package", "manual-review"],
    submissionMethod: "official-kboo-physical-genre-routed-emerging-music-submission-route",
    feeRequired: false,
    feeAmount: "No submission fee or payment requirement was observed on the official KBOO Submit Your Music route.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KBOO states it has no digital library capacity, prefers physical mailed submissions, uses genre-specific attention routing and provides no airplay guarantee.",
    notes: "Public research verified KBOO's official active station site, Submit Your Music page, postal route, emerging-music framing and genre attention lines for electronic, folk, rock/punk, jazz, hip-hop, world music and reggae. No package was prepared or mailed and no staff contact was messaged."
  },
  {
    name: "WXPN Music Director EPK Digital Download Local Show Submission Route",
    websiteUrl: "https://xpn.org/",
    submissionUrl: "https://xpn.org/contact/",
    sourceUrl: "https://xpn.org/contact/",
    sourceType: "automation_run_171_public_research",
    country: "United States / Philadelphia AAA public radio and local-show digital music submission route",
    language: "en",
    genres: ["public-radio", "aaa-radio", "independent-artists", "new-music", "local-show", "epk", "wav-download", "high-quality-mp3", "email-route", "manual-review"],
    submissionMethod: "official-wxpn-music-director-epk-digital-download-local-show-submission-route",
    feeRequired: false,
    feeAmount: "No submission fee or payment requirement was observed on the official WXPN contact/submission route.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WXPN asks for an EPK or high-quality local-show download link, and route selection between general airplay and The Local Show must be reviewed before emailing.",
    notes: "Public research verified WXPN's official active site, music-submission contact page, EPK/digital download instructions, Local Show WAV or high-quality MP3 guidance and no-response expectation. The rendered page exposed official email actions but no plain address was copied into the database, and no email was sent."
  },
  {
    name: "SomaFM Channel Music Director Digital Bandcamp YUM High Bitrate Route",
    websiteUrl: "https://somafm.com/",
    submissionUrl: "https://somafm.com/submitmusic/",
    sourceUrl: "https://somafm.com/submitmusic/",
    sourceType: "automation_run_171_public_research",
    country: "United States / global internet radio channel-specific digital music director route",
    language: "en",
    genres: ["internet-radio", "electronic", "downtempo", "ambient", "dub", "groove", "world-fusion", "independent-artists", "bandcamp-yum", "high-bitrate-mp3", "email-route", "manual-review"],
    submissionMethod: "official-somafm-channel-music-director-digital-bandcamp-yum-high-bitrate-route",
    feeRequired: false,
    feeAmount: "No submission fee or payment requirement was observed on the official SomaFM Submit Music route.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because SomaFM only accepts selected channel submissions, forbids sending the same release to multiple directors, rejects low-quality links and excludes AI-generated music.",
    notes: "Public research verified SomaFM's official active multi-channel site, Submit Music policy, digital-only requirement, Bandcamp/YUM guidance, WeTransfer/Dropbox guidance, high-bitrate MP3 requirements, public channel/director email routes and no-bulk-mail policy. No email was sent and no download code or file was transferred."
  },
  {
    name: "WWOZ New Orleans CD WAV Music Director Airplay Submission Route",
    websiteUrl: "https://www.wwoz.org/",
    submissionUrl: "https://www.wwoz.org/getting-airplay-your-cd-wwoz",
    sourceUrl: "https://www.wwoz.org/getting-airplay-your-cd-wwoz",
    sourceType: "automation_run_171_public_research",
    country: "United States / New Orleans community radio CD and high-quality WAV airplay route",
    language: "en",
    genres: ["community-radio", "new-orleans", "louisiana-music", "jazz", "r-and-b", "funk", "world-music", "reggae", "cd-submission", "wav-file", "physical-package", "manual-review"],
    submissionMethod: "official-wwoz-cd-wav-music-director-airplay-submission-route",
    feeRequired: false,
    feeAmount: "No submission fee or payment requirement was observed on the official WWOZ airplay guidance page.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WWOZ strongly prefers finished CD projects, may require multiple physical copies, expects cover-letter/context, needs clean/profanity marking and has a specific Louisiana/New Orleans music-fit consideration.",
    notes: "Public research verified WWOZ's official active site, musician resources path, Getting Airplay guidance, CD preference, WAV fallback requirement, Music Director mailing address and library/show-host copy advice. No physical package was prepared or mailed and no audio file was transferred."
  },
  {
    name: "KUTX Austin Music Director WAV Download and Specialty Show Route",
    websiteUrl: "https://kutx.org/",
    submissionUrl: "https://kutx.org/submit-your-music/",
    sourceUrl: "https://kutx.org/submit-your-music/",
    sourceType: "automation_run_171_public_research",
    country: "United States / Austin Texas public radio music-director and specialty-show submission route",
    language: "en",
    genres: ["public-radio", "new-music", "austin-music", "texas-music", "electronic", "experimental", "hip-hop", "r-and-b", "latin", "jazz", "wav-download", "email-route", "manual-review"],
    submissionMethod: "official-kutx-music-director-wav-download-specialty-show-route",
    feeRequired: false,
    feeAmount: "No submission fee or payment requirement was observed on the official KUTX Submit Your Music route.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KUTX requires a specific subject format, streaming link, WAV download link, mastered clean radio edits and routing between on-air rotation and specialty shows.",
    notes: "Public research verified KUTX's official active station site, Submit Your Music page, public music@kutx.org route, WAV-download requirement, no-MP3-attachment instruction, FCC-clean guidance and specialty shows including electronic/experimental Soundfounder, hip-hop/R&B The Breaks and Latin Horizontes. No email was sent and no file link was delivered."
  }
];
