import type { PlatformInput } from '../models/types.js';

export const run192SeedPlatforms: PlatformInput[] = [
  {
    name: "KEXP Digital WAV Music Director Rotation Consideration Route",
    websiteUrl: "https://www.kexp.org/",
    submissionUrl: "https://www.kexp.org/about/contact/",
    sourceUrl: "https://www.kexp.org/read/2018/9/24/getting-radio-airplay-everything-youve-ever-wanted-know-about-getting-your-music-played-kexp/",
    sourceType: "automation_run_192_public_research",
    country: "United States / Seattle non-commercial public radio digital music-director submission route",
    language: "en",
    genres: ["public-radio", "non-commercial-radio", "electronic", "world", "reggae", "dub", "independent", "airplay", "manual-review"],
    submissionMethod: "official-kexp-music-director-digital-wav-download-link-route",
    feeRequired: false,
    feeAmount: "Free-first/manual route; official KEXP guidance states music cannot be paid into rotation and asks artists to send digital stream or download links instead of attachments or physical media.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KEXP asks for curated email submission materials, non-attachment WAV/stream/download links, clean edits for FCC violations, release metadata, credits, pronouns, show dates and patience/no-tracking expectations. Owner must approve the specific track, private/public link, pitch wording, explicit-content notes, AI/authorship disclosure and no-bulk handling before outreach.",
    notes: "Official public KEXP contact and submission-guideline pages list md@kexp.org as the digital submission route, request WAV-quality links rather than attachments, state that physical submissions should not be sent and confirm that airplay cannot be bought. No email, upload, account, payment or tracking request was sent."
  },
  {
    name: "KALX Berkeley Physical CD LP Music Director Airplay Route",
    websiteUrl: "https://kalx.berkeley.edu/",
    submissionUrl: "https://kalx.berkeley.edu/contact/",
    sourceUrl: "https://kalx.berkeley.edu/contact/",
    sourceType: "automation_run_192_public_research",
    country: "United States / Berkeley college radio physical-only music-director route",
    language: "en",
    genres: ["college-radio", "freeform-radio", "physical-submission", "electronic", "world", "reggae", "independent", "airplay", "manual-review"],
    submissionMethod: "official-kalx-physical-cd-lp-music-director-submission-route",
    feeRequired: false,
    feeAmount: "Free-first/manual physical route; official KALX instructions say the station accepts only professionally pressed CDs or LPs and does not accept downloads, file transfers, Bandcamp, Spotify, YouTube, CD-Rs or digital forms.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KALX is physical-only, prefers plain-text contact with no attachments, and rejects digital delivery. Owner must approve whether a professionally pressed CD/LP package exists, package contents, FCC-clean notes, one-sheet, shipping costs and no-digital/no-bulk handling before any mail or email action.",
    notes: "Official KALX pages show current 2026 station activity and list music@kalx.berkeley.edu plus a physical Music Director address, but the public rules explicitly require professional physical releases and reject digital submissions. No email was sent and no package was prepared."
  },
  {
    name: "WXPN EPK Download Link Music Director Local Show Route",
    websiteUrl: "https://xpn.org/",
    submissionUrl: "https://xpn.org/contact/",
    sourceUrl: "https://xpn.org/contact/",
    sourceType: "automation_run_192_public_research",
    country: "United States / Philadelphia public radio EPK and local-show download-link route",
    language: "en",
    genres: ["public-radio", "aaa-radio", "local-show", "epk", "electronic", "world", "reggae", "independent", "manual-review"],
    submissionMethod: "official-wxpn-epk-download-link-music-director-local-show-route",
    feeRequired: false,
    feeAmount: "Free-first/manual route; official WXPN contact guidance requests an EPK with a digital download link for airplay consideration and high-quality WAV/MP3 links for local-show consideration.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WXPN uses email-link routes whose actual addresses were exposed as public link labels rather than decoded in the retrieved page, and because track fit, Philadelphia/local eligibility, EPK completeness, download-link permissions, bio/show details and no-response expectations must be checked before contact.",
    notes: "Official WXPN pages show active July 2026 music coverage and provide public instructions to send an EPK plus digital download link for airplay consideration; Local Show guidance requests WAV/high-quality MP3 download links, bio and upcoming shows. Link-only/protected email routes were not decoded and no message was sent."
  },
  {
    name: "WFMU Physical Materials Music Director Review Route",
    websiteUrl: "https://wfmu.org/",
    submissionUrl: "https://wfmu.org/sendmusic",
    sourceUrl: "https://wfmu.org/sendmusic",
    sourceType: "automation_run_192_public_research",
    country: "United States / New Jersey freeform radio physical-materials review route",
    language: "en",
    genres: ["freeform-radio", "physical-submission", "experimental", "electronic", "world", "reggae", "independent", "manual-review"],
    submissionMethod: "official-wfmu-physical-materials-music-director-review-route",
    feeRequired: false,
    feeAmount: "Free-first/manual physical route; official WFMU Send Us Music page welcomes vinyl, CD, CD-R and cassette materials for review and provides postal and courier addresses.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WFMU is a physical-materials review route with postal/courier handling, format choice, package contents, explicit/FCC notes, artist contact details, shipping cost and no-return/no-tracking considerations. Owner must approve any physical package before mailing.",
    notes: "Official WFMU pages show active station/program context and a public Send Us Music route addressed to the Music Director for physical materials. The site chrome displayed login/register links, but no authenticated route was used. No contact email was decoded, no form was submitted and no package was prepared."
  },
  {
    name: "Radio K KUOM Physical Digital Music Department Submission Route",
    websiteUrl: "https://radiok.org/",
    submissionUrl: "https://radiok.org/submitting-music",
    sourceUrl: "https://radiok.org/submitting-music",
    sourceType: "automation_run_192_public_research",
    country: "United States / Minneapolis college radio physical and digital music-department route",
    language: "en",
    genres: ["college-radio", "nacc", "independent", "electronic", "world", "reggae", "local-music", "airplay", "manual-review"],
    submissionMethod: "official-radio-k-kuom-physical-digital-music-department-submission-route",
    feeRequired: false,
    feeAmount: "Free-first/manual route; official Radio K instructions accept physical releases by mail and digital releases by email using a cloud .zip link with high-quality WAV or FLAC files, plus Bandcamp code/free-release options.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Radio K asks artists to confirm playlist/genre fit, provide physical or high-quality digital files, include FCC warnings, a short bio, contact information and 2-3 radio-suitable songs, and not request tracking. The music department address was protected/obfuscated in public output and was not decoded.",
    notes: "Official Radio K pages show current July 2026 playlist/new-addition activity and a public Submitting Music page with physical and digital submission instructions. The public page displayed a protected music-department contact label; no contact was decoded, guessed or probed, and no email/package/upload was sent."
  }
];
