import type { PlatformInput } from '../models/types.js';

export const run149SeedPlatforms: PlatformInput[] = [
  {
    name: "KFJC Physical Media Music Director Airplay Submission Route",
    websiteUrl: "https://kfjc.org/",
    submissionUrl: "https://kfjc.org/about/for-musicians",
    sourceUrl: "https://kfjc.org/about/for-musicians",
    sourceType: "automation_run_149_public_research",
    country: "United States / San Francisco Bay Area college-community freeform station with global online listening and broad experimental music fit",
    language: "en",
    genres: ["college-radio", "freeform", "experimental", "electronic", "world", "reggae", "physical-media", "music-director", "manual-review"],
    submissionMethod: "official-kfjc-physical-media-music-director-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KFJC accepts only physical media for library consideration, asks senders to address the Music Director, and package preparation, format choice, genre fit and rights notes must remain owner-controlled.",
    notes: "Public research verified KFJC's official For Musicians page as a submission route for bands and labels. KFJC states it listens to everything sent, accepts physical CD/vinyl/cassette only, routes material through the Music Director, and does not accept digital-only media. No package was prepared, no mail was sent and no contact was used."
  },
  {
    name: "WMBR MIT Physical CD Music Director Freeform Airplay Route",
    websiteUrl: "https://wmbr.org/",
    submissionUrl: "https://wmbr.org/www/md",
    sourceUrl: "https://wmbr.org/www/md",
    sourceType: "automation_run_149_public_research",
    country: "United States / MIT Cambridge freeform college-community station with global stream and genre-director routing",
    language: "en",
    genres: ["college-radio", "freeform", "physical-cd", "rpm-techno", "world", "experimental", "unsigned-bands", "music-director", "manual-review"],
    submissionMethod: "official-wmbr-physical-cd-music-director-airplay-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WMBR prefers tangible physical music, publishes mailing and genre-director guidance, and warns against unsolicited list/self-promotion behavior; the right show, physical package and one-sheet must be reviewed manually.",
    notes: "Public research verified WMBR's official Your Music page as a route explaining how to get music played, with physical mailing to the Music Director, unsigned-band eligibility, no pay-for-play influence, and genre contacts for RPM/Techno and World. No CD was prepared, no email/image contact was decoded, and no message was sent."
  },
  {
    name: "KSPC Album EP Digital and Physical Airplay Submission Route",
    websiteUrl: "https://kspc.org/",
    submissionUrl: "https://kspc.org/contact/music-submissions/",
    sourceUrl: "https://kspc.org/contact/music-submissions/",
    sourceType: "automation_run_149_public_research",
    country: "United States / Claremont college-community station supporting new, local and underrepresented voices with online stream",
    language: "en",
    genres: ["college-radio", "all-genres", "album-ep", "digital-download", "physical-cd-vinyl", "no-singles", "no-ai-music", "manual-review"],
    submissionMethod: "official-kspc-album-ep-digital-physical-airplay-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KSPC accepts albums/EPs only, rejects singles, demos, Spotify/iTunes links and substantially AI-generated work, and requires downloadable music or mailed physical media with owner-approved metadata.",
    notes: "Public research verified KSPC's official Music Submissions page. KSPC welcomes artists from all genres, accepts CDs/records mailed to the Music Director and digital submissions through an official public email link with files or downloadable cloud links, and states it does not accept pay-for-play. No file, link, email or physical package was sent."
  },
  {
    name: "KZSC RPM Electronic International Music Director Contact Route",
    websiteUrl: "https://kzsc.org/",
    submissionUrl: "https://kzsc.org/contact/",
    sourceUrl: "https://kzsc.org/contact/",
    sourceType: "automation_run_149_public_research",
    country: "United States / Santa Cruz college-community station with RPM/electronic and international music director contacts plus global online listening",
    language: "en",
    genres: ["college-radio", "rpm", "electronic", "international", "world", "reggae", "hip-hop", "music-director-contact", "manual-review"],
    submissionMethod: "official-kzsc-rpm-electronic-international-music-director-contact-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KZSC exposes public music-director contacts but does not provide a safe auto-submit form; selecting RPM/Electronic or International routing, pitch copy, metadata and rights context must remain manual.",
    notes: "Public research verified KZSC's active 2026 site, music news, music charts and official staff/contact page listing station music directors including RPM & Electronic and International roles with public email links. No email address was decoded beyond the public page, no message was sent and no contact was guessed."
  },
  {
    name: "WMSE How To Submit Music Request Verification Boundary Route",
    websiteUrl: "https://www.wmse.org/",
    submissionUrl: "https://wmse.org/about-wmse-radio/music-department/",
    sourceUrl: "https://www.wmse.org/",
    sourceType: "automation_run_149_public_research",
    country: "United States / Milwaukee freeform and eclectic non-commercial station with world, jazz, blues, new age and alternative fit",
    language: "en",
    genres: ["non-commercial-radio", "freeform", "alternative", "world", "jazz", "blues", "new-age", "request-verification-boundary", "manual-review"],
    submissionMethod: "official-wmse-how-to-submit-music-boundary-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because the official WMSE homepage exposes a How To Submit Music link, but the submission detail route returned a request-verification boundary that must not be bypassed or handled automatically.",
    notes: "Public research verified WMSE's active official site, How To Submit Music navigation and eclectic station positioning. The linked music-department submission route reached a verification/loader boundary; no anti-bot step was handled, no form was entered, no contact was guessed and no message was sent."
  }
];
