import type { PlatformInput } from '../models/types.js';

export const run170SeedPlatforms: PlatformInput[] = [
  {
    name: "Playlist Push Spotify TikTok Paid Curator Campaign Route",
    websiteUrl: "https://playlistpush.com/",
    submissionUrl: "https://app.playlistpush.com/",
    sourceUrl: "https://playlistpush.com/",
    sourceType: "automation_run_170_public_research",
    country: "United States / global Spotify playlist and TikTok creator promotion route for independent and label artists",
    language: "en",
    genres: ["music-promotion", "spotify-playlists", "tiktok-creators", "playlist-curators", "independent-artists", "electronic", "dance", "world-music", "paid-campaign", "login-boundary", "manual-review"],
    submissionMethod: "official-playlist-push-paid-spotify-tiktok-curator-campaign-route",
    feeRequired: true,
    feeAmount: "Playlist Push public pricing states Spotify campaigns typically start at $280 and that actual pricing depends on campaign goals, genres and curator reach.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Playlist Push requires app/account access, paid campaign setup, Spotify or TikTok route selection, song/link selection, genre targeting, budget approval, release timing and campaign terms review.",
    notes: "Public research verified the official Playlist Push site, Spotify playlist submission route, TikTok creator route, app sign-up/sign-in boundary, vetted curator network, live reporting dashboard language and pricing page. No account was created, no campaign was configured and no payment was initiated."
  },
  {
    name: "SoundCampaign Spotify TikTok A&R Reviewed Promotion Campaign Route",
    websiteUrl: "https://soundcamps.com/",
    submissionUrl: "https://app.soundcamps.com/",
    sourceUrl: "https://soundcamps.com/",
    sourceType: "automation_run_170_public_research",
    country: "Estonia / global Spotify playlist, TikTok creator and music-promotion campaign platform",
    language: "en",
    genres: ["music-promotion", "spotify-playlists", "tiktok-creators", "playlist-consideration", "curator-feedback", "campaign-budget", "artist-development", "login-boundary", "payment-boundary", "manual-review"],
    submissionMethod: "official-soundcampaign-paid-spotify-tiktok-ar-reviewed-campaign-route",
    feeRequired: true,
    feeAmount: "SoundCampaign pricing says campaign pricing is dynamic, depends on targeted genres and available playlists, and that the average campaign cost is around $100.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because SoundCampaign requires campaign creation, A&R review, genre and language targeting, budget/reach setup, playlist or TikTok creator routing, payment approval and platform terms review.",
    notes: "Public research verified SoundCampaign's official site, Spotify and TikTok promotion routes, Get Started app boundary, pricing page, A&R review step, dynamic budget setup and real-curator/creator review language. No account was created, no campaign was submitted and no payment was started."
  },
  {
    name: "One Submit Multi Channel Curator Review Dashboard Route",
    websiteUrl: "https://www.one-submit.com/",
    submissionUrl: "https://app.one-submit.com/auth/artistSignup",
    sourceUrl: "https://www.one-submit.com/",
    sourceType: "automation_run_170_public_research",
    country: "Israel / global multi-channel curator platform for Spotify, YouTube, TikTok, blogs, radio, magazines and labels",
    language: "en",
    genres: ["music-promotion", "spotify-playlists", "youtube-channels", "tiktok-influencers", "music-blogs", "online-radio", "record-labels", "electronic", "afrobeats", "paid-review", "login-boundary", "manual-review"],
    submissionMethod: "official-one-submit-paid-multi-channel-curator-review-dashboard-route",
    feeRequired: true,
    feeAmount: "One Submit pricing lists paid review routes including radio submissions from $4, Spotify/blog submissions from $6, label submissions from $5, YouTube submissions from $20 and payment by PayPal or credit card.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because One Submit requires artist sign-up, channel selection, track lookup/upload or Spotify link handling, genre targeting, curator/channel choices, paid-review approval, payment method selection and campaign terms review.",
    notes: "Public research verified One Submit's official homepage, artist sign-up app boundary, multi-channel submission scope, contact form, pricing page, curator review/refund language and electronic-artist suitability note. No account was created, no form was submitted and no payment was initiated."
  },
  {
    name: "Stereofox SubmitHub Groover Curated Music Blog Playlist Route",
    websiteUrl: "https://www.stereofox.com/",
    submissionUrl: "https://www.submithub.com/blog/stereofox?c=fox10",
    sourceUrl: "https://www.stereofox.com/contact/",
    sourceType: "automation_run_170_public_research",
    country: "Germany / Bulgaria / global curated music blog, playlists and label ecosystem with SubmitHub and Groover submission routes",
    language: "en",
    genres: ["music-blog", "curated-playlists", "electronic", "electronica", "progressive-house", "melodic-house", "uk-garage", "lofi", "independent-artists", "submithub", "groover", "manual-review"],
    submissionMethod: "official-stereofox-submithub-groover-curated-music-blog-playlist-route",
    feeRequired: false,
    feeAmount: "Stereofox points artists to SubmitHub or Groover and rejects email/Discord submissions; exact free/paid credit route must be checked manually inside the authorized submission platform before use.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Stereofox only accepts music through external SubmitHub/Groover routes, where account/session, curator profile, song link, pitch copy, credit/payment options and genre fit must be reviewed.",
    notes: "Public research verified Stereofox's official active site, contact/submission page, Submit Music navigation, human-curated tracks/playlists, electronic and chill-electronica playlists, SubmitHub/Groover submission instructions and explicit no-email/no-Discord policy. No SubmitHub/Groover login was used and no music was submitted."
  },
  {
    name: "EARMILK SubmitHub Pillargram Music Submission and Premiere Route",
    websiteUrl: "https://earmilk.com/",
    submissionUrl: "https://earmilk.com/submit-music/",
    sourceUrl: "https://earmilk.com/submit-music/",
    sourceType: "automation_run_170_public_research",
    country: "United States / global online music publication with SubmitHub and Pillargram submission routes for music and premieres",
    language: "en",
    genres: ["music-blog", "premieres", "electronic", "dance", "experimental", "hip-hop", "indie", "pop", "submithub", "pillargram", "business-contact-observed", "manual-review"],
    submissionMethod: "official-earmilk-submithub-pillargram-music-submission-premiere-route",
    feeRequired: false,
    feeAmount: "EARMILK's official submission page routes music and premieres to SubmitHub or Pillargram; direct fee requirement was not established from the publication page and must be checked manually in the external submission app.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because EARMILK only accepts new music through SubmitHub or Pillargram, not its contact form, and the external app route requires account/session, song link, premiere status, pitch copy, media assets and possible platform terms review.",
    notes: "Public research verified EARMILK's official active site, July 2026 publishing activity, Submit Music page, SubmitHub/Pillargram-only submission policy, contact page warning against music submissions through the general form and a public business partnership email. No external account was created, no form was submitted and no email was sent."
  }
];
