import type { PlatformInput } from '../models/types.js';

export const run188BaseSeedPlatforms: PlatformInput[] = [
  {
    name: "CKCU Ottawa Music Library CD Mail Program Director Review Route",
    websiteUrl: "https://www.ckcufm.com/",
    submissionUrl: "https://www.ckcufm.com/contact/",
    sourceUrl: "https://www.ckcufm.com/contact/",
    sourceType: "automation_run_188_public_research",
    country: "Canada / Ottawa Ontario community-radio music-library physical CD and program-director review route",
    language: "en",
    genres: ["community-radio", "campus-radio", "freeform-radio", "electronic", "reggae", "world", "caribbean", "indie", "cd-mail", "program-director", "manual-review"],
    submissionMethod: "official-ckcu-music-library-cd-mail-program-director-review-route",
    feeRequired: false,
    feeAmount: "Free-first CKCU route; official pages expose a staff directory, mailing address, playlist/library system and a public 'mail your CD to us' library route, but exact package and targeting require manual review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because CKCU's public pages expose staff/program contacts, a mailing address and playlist/library context, while the COD library/search area includes login/session links. CD/package availability, program/director targeting, clean edits, metadata, and whether to contact programs@ckcufm.com before mailing must be approved.",
    notes: "Official CKCU Contact page lists Station Director, Production Manager, Program Director programs@ckcufm.com, phone, office hours and a studio/mailing address. The CKCU playlist/library search page exposes a 'mail your CD to us' path and COD login/library boundaries. No login, email, file, CD or package action was taken."
  },
  {
    name: "CFUV Victoria 320kbps Digital Download Music Director Submission Route",
    websiteUrl: "https://cfuv.uvic.ca/",
    submissionUrl: "https://cfuv.uvic.ca/music-submissions/",
    sourceUrl: "https://cfuv.uvic.ca/music-submissions/",
    sourceType: "automation_run_188_public_research",
    country: "Canada / Victoria British Columbia campus-community radio digital album EP submission route",
    language: "en",
    genres: ["campus-radio", "community-radio", "freeform-radio", "electronic", "hip-hop", "reggae", "world", "jazz", "independent-music", "digital-download", "manual-review"],
    submissionMethod: "official-cfuv-320kbps-digital-download-music-director-submission-route",
    feeRequired: false,
    feeAmount: "Free-first CFUV Music Department route; official page requires digital submissions to music@cfuv.ca with at least three unique tracks and 320 kbps MP3 download-link handling.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because CFUV requires at least three unique tracks, prefers 320 kbps MP3 digital download links, asks for a one-page bio and track listing, excludes most physical submissions unless local, and can decline releases for format, lyrical, recording-quality or programming-fit reasons.",
    notes: "Official CFUV Music Submissions page lists Music Director Troy Lemberg, music@cfuv.ca, tracking guidance, 320 kbps MP3 requirements, acceptable digital-download services and review timeline. No email, file, link or physical item was sent."
  },
  {
    name: "KUPS Tacoma Staff Music Submission Form Genre Director Route",
    websiteUrl: "https://kupsfm.com/",
    submissionUrl: "https://kupsfm.com/contact/",
    sourceUrl: "https://kupsfm.com/contact/",
    sourceType: "automation_run_188_public_research",
    country: "United States / Tacoma Washington college-radio public form and genre music-director route",
    language: "en",
    genres: ["college-radio", "student-radio", "alternative", "electronic", "hip-hop", "specialty", "independent-music", "public-form", "music-director-email", "manual-review"],
    submissionMethod: "official-kups-public-form-genre-director-music-submission-route",
    feeRequired: false,
    feeAmount: "Free-first KUPS public contact-form route; official contact page invites music submission through a public form and staff page lists genre director email routes.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KUPS exposes a public music submission form plus multiple staff genre-director email routes. The owner must approve whether to use the form or a genre director route, choose electronic/alternative/hip-hop/specialty targeting, and prepare concise wording, metadata, clean edits and download-link handling.",
    notes: "Official KUPS Contact page says 'Looking to submit music to the staff? Submit below' and includes first name, last name, email and message fields plus a mailing address. Official staff page lists Alternative, Hip-Hop, Specialty and Electronic Music Director email routes. No form, email, file, link or package was submitted."
  },
  {
    name: "KSPC Claremont Album EP Digital Cloud Music Submission Route",
    websiteUrl: "https://kspc.org/",
    submissionUrl: "https://kspc.org/contact/music-submissions/",
    sourceUrl: "https://kspc.org/contact/music-submissions/",
    sourceType: "automation_run_188_public_research",
    country: "United States / Claremont California college-radio album EP digital and physical music route",
    language: "en",
    genres: ["college-radio", "freeform-radio", "independent-music", "electronic", "reggae", "world", "hip-hop", "album-ep-only", "digital-download", "physical-media", "manual-review"],
    submissionMethod: "official-kspc-album-ep-digital-cloud-music-submission-route",
    feeRequired: false,
    feeAmount: "Free-first KSPC route; official page accepts albums or EPs for airplay consideration via mailed CDs/records or digital files/cloud-download links, but rejects singles, demos and AI music.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KSPC accepts albums/EPs only, rejects singles, demos, cassette tapes, streaming-only links, iTunes/Spotify links and substantially AI-generated work, and states no pay-for-play or guaranteed programming. Format, rights/authorship, cloud-download access, clean edits and follow-up wording must be approved.",
    notes: "Official KSPC Music Submissions page welcomes all genres for airplay, accepts mailed CDs/records except singles and digital files or cloud-download links, rejects streaming-only links and AI music, and states no payment is accepted for airplay. The visible email on the fetched page was protected/obfuscated and was not decoded. No email, files, links or package were sent."
  },
  {
    name: "KXUA Fayetteville Non Local Local Music Director Email Submission Route",
    websiteUrl: "https://kxua.com/",
    submissionUrl: "https://kxua.com/",
    sourceUrl: "https://kxua.com/",
    sourceType: "automation_run_188_public_research",
    country: "United States / Fayetteville Arkansas University of Arkansas student-radio non-local local music submission route",
    language: "en",
    genres: ["college-radio", "student-radio", "eclectic", "electronic", "indie", "hip-hop", "local-music", "album-review", "music-director-email", "manual-review"],
    submissionMethod: "official-kxua-nonlocal-local-music-director-email-submission-route",
    feeRequired: false,
    feeAmount: "Free-first KXUA music submission route; official homepage footer lists Submit Music with non-local and local music-director email routes.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KXUA separates non-local and local submission routes, is an eclectic student radio outlet with album-review and newest-arrival context, and does not define file format, attachment policy, download-link rules, clean/radio edits or follow-up expectations on the observed page.",
    notes: "Official KXUA homepage showed 2026 album-review activity and a Submit Music footer with non-local charts@uark.edu and local localmd@uark.edu routes plus studio address. No email, file, link, form or package action was taken."
  }
];