import type { PlatformInput } from '../models/types.js';

export const run195SeedPlatforms: PlatformInput[] = [
  {
    name: "Groover Global Curator Credit Music Promotion Submission Route",
    websiteUrl: "https://groover.co/",
    submissionUrl: "https://groover.co/en/",
    sourceUrl: "https://groover.co/en/",
    sourceType: "automation_run_195_public_research",
    country: "Global / France-US music promotion curator, playlist, radio, label and pro campaign route",
    language: "en",
    genres: ["music-promotion", "curator-feedback", "spotify-playlists", "radio", "blogs", "labels", "electronic", "world", "reggae", "dj", "manual-review"],
    submissionMethod: "official-groover-paid-curator-pro-credit-campaign-route",
    feeRequired: true,
    feeAmount: "Paid/manual route; official Groover page says artists choose 3,000+ curators/pros, add a song or demo and pitch, with contacts starting at $2 / 2 Grooviz and Grooviz purchase required.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because the route needs account/session handling, paid Grooviz credits, curator/pro targeting, genre/country filters, private-link selection, pitch copy, rights/metadata review and payment approval. No account, upload, pitch or payment may be automated.",
    notes: "Official Groover pages say the platform connects artists with curators, radios, playlists, labels and music pros, supports all genres, accepts YouTube/SoundCloud/Audiomack links, and refunds credits if contacts do not respond within 7 days. Contact support is chat/FAQ based; no public music-submission email route was selected and no deliverability probing was performed."
  },
  {
    name: "SoundCampaign Spotify TikTok Curator Campaign Submission Route",
    websiteUrl: "https://soundcamps.com/",
    submissionUrl: "https://app.soundcamps.com/",
    sourceUrl: "https://soundcamps.com/",
    sourceType: "automation_run_195_public_research",
    country: "Global / Spotify playlist and TikTok creator paid campaign platform",
    language: "en",
    genres: ["music-promotion", "spotify-playlists", "tiktok", "playlist-curators", "creator-campaigns", "electronic", "pop", "hip-hop", "dance", "manual-review"],
    submissionMethod: "official-soundcampaign-paid-spotify-tiktok-curator-campaign-route",
    feeRequired: true,
    feeAmount: "Paid/manual route; official SoundCampaign page says campaigns promote tracks to Spotify playlist curators and TikTok creators, with campaign budgets/payment and credit-back/refund language if reviews are not delivered.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because campaign setup uses a logged-in app, payment/budget controls, curator/creator matching, track upload/link handling, Spotify-policy review, possible cookie/session choices and campaign targeting. No login, upload, campaign, payment or creator outreach may be automated.",
    notes: "Official SoundCampaign pages describe Spotify playlist promotion, TikTok music promotion, creator/curator reviews, analytics and a separate artist/curator account requirement. No account was created, no campaign was started, no payment was initiated and no deliverability probing was performed."
  },
  {
    name: "Soundplate Free Spotify Deezer Playlist Submission Grid Route",
    websiteUrl: "https://play.soundplate.com/",
    submissionUrl: "https://play.soundplate.com/",
    sourceUrl: "https://play.soundplate.com/",
    sourceType: "automation_run_195_public_research",
    country: "Global / free independent Spotify and Deezer playlist submission grid",
    language: "en",
    genres: ["spotify-playlists", "deezer-playlists", "electronic", "house", "garage", "bass", "festival", "disco", "chill", "independent-curators", "manual-review"],
    submissionMethod: "official-soundplate-free-playlist-grid-submission-route",
    feeRequired: false,
    feeAmount: "Free-first/manual route; official Soundplate Play page says artists can discover and submit music to Spotify and Deezer playlists for free by selecting relevant playlists from the grid.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because playlist-by-playlist relevance, platform link quality, genre fit, anti-spam behavior, privacy/consent fields and any downstream external form or authentication boundary must be checked before submission. No playlist form may be auto-submitted.",
    notes: "Official Soundplate Play page lists active playlist categories such as Deep House, Fresh Beats, Garage & Bass, House/Techno/Deep and Festival Anthems, and asks submitters not to spam. No playlist was selected, no form was entered and no contact guessing or deliverability probing was performed."
  },
  {
    name: "Indiemono Free Spotify Playlist Submission Consent Form Route",
    websiteUrl: "https://indiemono.com/",
    submissionUrl: "https://indiemono.com/submit-music-chill-playlists/",
    sourceUrl: "https://indiemono.com/submit-music-chill-playlists/",
    sourceType: "automation_run_195_public_research",
    country: "Global / free Spotify playlist submission and optional PR-service interest form",
    language: "en",
    genres: ["spotify-playlists", "chill", "edm", "indie-alternative", "pop", "urban", "rnb", "latino", "happy", "sadlove", "manual-review"],
    submissionMethod: "official-indiemono-free-spotify-playlist-consent-form-route",
    feeRequired: false,
    feeAmount: "Free-first/manual route; official Indiemono page says the playlisting system is free, accepts Spotify track URLs through forms and does not charge for playlisting.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because the form collects name/email, Spotify track URL, closest genre, optional agency/label/service interest, territory preferences and consent/newsletter permissions. Cookie and consent choices must remain manual, and email submissions are explicitly rejected.",
    notes: "Official Indiemono submission/contact pages say they listen through submission forms, need valid Spotify track URLs, do not reply to email/Facebook submissions, and do not charge for playlisting. No form, cookie consent, outbound email or deliverability probe was performed."
  },
  {
    name: "Radio Airplay Jango Artist Upload Paid Airplay Review Route",
    websiteUrl: "https://www.radioairplay.com/",
    submissionUrl: "https://www.radioairplay.com/music+promotion/guaranteed_airplay",
    sourceUrl: "https://www.radioairplay.com/",
    sourceType: "automation_run_195_public_research",
    country: "Global / internet-radio artist upload, review and paid airplay package route",
    language: "en",
    genres: ["internet-radio", "artist-upload", "song-reviews", "airplay", "playlist-opportunities", "sync-partner-offers", "electronic", "independent-artists", "manual-review"],
    submissionMethod: "official-radio-airplay-jango-upload-airplay-package-route",
    feeRequired: false,
    feeAmount: "Freemium/manual route; official Radio Airplay page lists free sign-up, track upload, song reviews, contests and Airplay Plus package options from $0 to $250, with premium@radioairplay.com for larger packages.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because the route uses account creation/login, track upload, profile setup, package selection, potential payments, fan messaging, contest participation and rights/metadata review. No account, upload, package selection, payment or fan messaging may be automated.",
    notes: "Official Radio Airplay page lists Free Sign Up, Upload Your Tracks, song reviews, free contests, Jango artist profiles, package tiers and the public business contact premium@radioairplay.com for larger packages. No account was created, no music was uploaded, no package was selected and no deliverability probing was performed."
  }
];