import type { PlatformInput } from '../models/types.js';

export const run103SeedPlatforms: PlatformInput[] = [
  {
    name: "WMFO 91.5FM Music Director and Music Department Submission Route",
    websiteUrl: "https://www.wmfo.org/",
    submissionUrl: "https://www.wmfo.org/contact/",
    sourceUrl: "https://www.wmfo.org/contact/",
    sourceType: "automation_run_103_public_research",
    country: "United States / Medford Massachusetts Tufts freeform college radio",
    language: "en",
    genres: ["wmfo", "tufts", "medford", "boston-area", "college-radio", "freeform-radio", "music-director", "music-department", "electronic", "reggae", "hip-hop", "world", "jazz", "alternative", "cd", "vinyl", "digital-library", "public-email", "free-first", "manual-review"],
    submissionMethod: "official-wmfo-music-director-and-music-department-public-contact-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WMFO exposes an official Music Director and Music Department route, but submission packaging still requires station-fit validation, link/file permissions, clean/radio-edit checks, metadata, release context and human-approved pitch copy.",
    notes: "Public research confirmed WMFO is active with a 2026 copyright footer, describes round-the-clock freeform broadcasting, lists a 2025-2026 Music Director contact and says the Music Department receives CDs, vinyl and cassettes while adding new digital media to its Rivendell database. No email was sent, no files or links were delivered, no account was used and no SMTP/MX probing was performed."
  },
  {
    name: "Dandelion Radio Demo Link and DJ Contact Submission Route",
    websiteUrl: "https://www.dandelionradio.com/",
    submissionUrl: "https://www.dandelionradio.com/contact.htm",
    sourceUrl: "https://www.dandelionradio.com/contact.htm",
    sourceType: "automation_run_103_public_research",
    country: "United Kingdom / global online independent radio",
    language: "en",
    genres: ["dandelion-radio", "john-peel-inspired", "internet-radio", "independent-radio", "electronic", "dub", "jungle", "bassline", "reggae", "world", "experimental", "indie", "dj-contact", "demo-link", "physical-delivery-side-route", "free-first", "manual-review"],
    submissionMethod: "official-dandelion-radio-demo-link-and-dj-contact-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Dandelion Radio asks artists to send links or contact individual DJs for postal routing. DJ fit, non-duplicative targeting, link permissions, metadata, release context and any physical-delivery request must be checked manually.",
    notes: "Public research confirmed Dandelion Radio is licensed with PRS/PPL, actively publishes current monthly shows, invites users to email the station and post demos, and advises sending links or contacting DJs for a direct postal address if needed. Public contact labels were observed, but no protected/blank email values were decoded or guessed, no messages were sent and no SMTP/MX probing was performed."
  },
  {
    name: "Radio Free Brooklyn Music Submission Form and Download-Link Route",
    websiteUrl: "https://www.radiofreebrooklyn.org/",
    submissionUrl: "https://submissions.radiofreebrooklyn.org/music-submission-form/",
    sourceUrl: "https://submissions.radiofreebrooklyn.org/music-submission-form/",
    sourceType: "automation_run_103_public_research",
    country: "United States / Brooklyn New York freeform internet radio",
    language: "en",
    genres: ["radio-free-brooklyn", "brooklyn", "freeform-radio", "internet-radio", "community-radio", "music-submission-form", "download-link", "bandcamp", "soundcloud-download", "dropbox", "google-drive", "local-artists", "electronic", "reggae", "world", "hip-hop", "manual-review"],
    submissionMethod: "official-radio-free-brooklyn-music-submission-form-download-link-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Radio Free Brooklyn exposes a public music submission form with reCAPTCHA/visual-code validation, downloadable-link requirements, optional physical CD/vinyl routing and artist/guest-intent fields. Anti-bot controls, link permissions, file availability, image size, metadata, NYC relevance and pitch copy require manual handling.",
    notes: "Public research confirmed the official Radio Free Brooklyn site is active with 2026 content and exposes a public Submit Music route. The form requires freely downloadable track or ZIP links, asks for artist/contact details, summary, image and URL fields, and includes reCAPTCHA validation. No form was submitted, no CAPTCHA was interacted with, no files or links were delivered and no physical mail was sent."
  },
  {
    name: "Obscure Sound Contact, SubmitHub and MusoSoup Submission Route",
    websiteUrl: "https://www.obscuresound.com/",
    submissionUrl: "https://www.obscuresound.com/about/contact/",
    sourceUrl: "https://www.obscuresound.com/about/contact/",
    sourceType: "automation_run_103_public_research",
    country: "United States / global independent music blog and playlist outlet",
    language: "en",
    genres: ["obscure-sound", "music-blog", "indie-blog", "electronic", "ambient", "alt-r-and-b", "hip-hop", "indie-pop", "dream-pop", "world-adjacent", "submithub", "musosoup", "direct-email", "freemium-manual", "payment-side-route", "manual-review"],
    submissionMethod: "official-obscure-sound-contact-submithub-musosoup-and-direct-email-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Obscure Sound offers multiple official routes: SubmitHub, SubmitHub Marketplace, MusoSoup and direct email. Route choice can involve external account/session handling, feedback/marketplace/payment options, editorial fit, pitch quality, image rights and whether to avoid paid PR campaign side-routes.",
    notes: "Public research confirmed Obscure Sound is active with July 2026 posts and its Contact/Submissions page accepts electronic, hip-hop, ambient, alt-R&B and other independent music. It routes singles through SubmitHub, albums/EPs through SubmitHub Marketplace, singles/albums through MusoSoup, and also permits direct email with streaming link, press photo and short release background. No external submission platform was opened for account handling, no payment or PR campaign was selected, no email was sent and no SMTP/MX probing was performed."
  },
  {
    name: "The Line of Best Fit New and Unsigned Artist Submission Route",
    websiteUrl: "https://www.thelineofbestfit.com/",
    submissionUrl: "https://www.thelineofbestfit.com/contact",
    sourceUrl: "https://www.thelineofbestfit.com/contact",
    sourceType: "automation_run_103_public_research",
    country: "United Kingdom / global independent online music publication",
    language: "en",
    genres: ["line-of-best-fit", "online-music-publication", "new-music", "unsigned-artists", "indie", "electronic", "pop", "alternative", "tracks", "albums", "google-form", "public-email", "press-release", "free-first", "manual-review"],
    submissionMethod: "official-line-of-best-fit-new-unsigned-artist-google-form-and-news-email-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because The Line of Best Fit welcomes music from new and unsigned artists through an external Google form route and also lists public editorial email routes for news and press releases. Form ownership, submission fit, release timing, pitch copy, assets and any Google session/privacy boundary must be checked manually.",
    notes: "Public research confirmed The Line of Best Fit contact page has a 2026 footer, welcomes music from new and unsigned artists through a linked form, and lists public routes for news/press releases and general contact. No Google form was opened beyond the public link, no account was used, no message was sent and no SMTP/MX probing was performed."
  }
];
