import type { PlatformInput } from '../models/types.js';

export const run186BaseSeedPlatforms: PlatformInput[] = [
  {
    name: "WZBC Boston College Music Director Email Postal Submission Route",
    websiteUrl: "https://www.wzbc.org/",
    submissionUrl: "https://www.wzbc.org/contact",
    sourceUrl: "https://www.wzbc.org/contact",
    sourceType: "automation_run_186_public_research",
    country: "United States / Newton Boston College alternative freeform college-radio route",
    language: "en",
    genres: ["college-radio", "freeform-radio", "alternative", "experimental", "electronic", "reggae", "world", "independent-music", "music-director-email", "postal", "manual-review"],
    submissionMethod: "official-wzbc-music-director-email-postal-submission-route",
    feeRequired: false,
    feeAmount: "Free-first WZBC Music Director route; public music director emails and postal station address are listed, but package format, genre routing and clean/radio-edit fit require manual review.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WZBC publishes multiple music-director email routes plus a postal address. Rock, NCP and specialty routing, clean edit status, metadata, link/download permissions, physical-copy choice and no-bulk outreach wording must be approved before contact.",
    notes: "Official WZBC contact page lists station postal address, Rock Music Directors, NCP Music Director, Specialty Music Director and public music-director email routes. No email, file, link or package was sent."
  },
  {
    name: "KZSC Santa Cruz RPM International Music Director Form Package Route",
    websiteUrl: "https://kzsc.org/",
    submissionUrl: "https://kzsc.org/send-us-a-message/",
    sourceUrl: "https://kzsc.org/contact/",
    sourceType: "automation_run_186_public_research",
    country: "United States / Santa Cruz UCSC college-community radio music director and form route",
    language: "en",
    genres: ["college-radio", "community-radio", "rpm", "electronic", "international", "world", "hip-hop", "jazz", "blues", "folk", "package", "contact-form", "manual-review"],
    submissionMethod: "official-kzsc-rpm-international-music-director-form-package-route",
    feeRequired: false,
    feeAmount: "Free-first KZSC Music Director route; public form includes Music Submission option and station lists music-director contacts and package addresses, but protected contacts and form/package choice require owner review.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KZSC exposes named music-director routes, protected email links, a public form with a Music Submission option, and package addresses. RPM/electronic versus international routing, form use, package handling, link permissions, metadata and clean edits must be approved before any submission.",
    notes: "Official KZSC pages show active 2026 music/news posts, RPM & Electronic and International music directors, package addresses for Music Directors, and a message form with Music Submission as a selectable topic. Protected contact links were observed but not decoded. No form was submitted and no package was prepared."
  },
  {
    name: "WRIR Richmond Music Department Public Email Submission Route",
    websiteUrl: "https://www.wrir.org/",
    submissionUrl: "https://www.wrir.org/station/contact/",
    sourceUrl: "https://www.wrir.org/station/contact/",
    sourceType: "automation_run_186_public_research",
    country: "United States / Richmond Virginia independent community-radio music-department route",
    language: "en",
    genres: ["community-radio", "independent-radio", "electronic", "house", "hip-hop", "world", "jazz", "folk", "punk", "local-music", "music-department-email", "cookie-boundary", "manual-review"],
    submissionMethod: "official-wrir-music-department-public-email-submission-route",
    feeRequired: false,
    feeAmount: "Free-first WRIR Music Department email route; public contact page says to write to the music department, but protected email display and cookie/session notices require manual review.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WRIR gives a public instruction to submit music to the music department, while the fetched page exposes protected email display and cookie-consent/session elements. Richmond/community-radio fit, clean edit status, metadata, link access and personalized wording must be approved before outreach.",
    notes: "Official WRIR homepage shows current station/social activity and the official contact page says to submit music by writing to the music department. Protected contact was observed but not decoded; cookie consent was observed and not bypassed. No message was sent."
  },
  {
    name: "WCBN Michigan Freeform Hard Copy Music Director Submission Route",
    websiteUrl: "https://wcbn.org/",
    submissionUrl: "https://wcbn.org/c/",
    sourceUrl: "https://wcbn.org/c/",
    sourceType: "automation_run_186_public_research",
    country: "United States / Ann Arbor University of Michigan freeform college-radio physical music route",
    language: "en",
    genres: ["college-radio", "freeform-radio", "electronic", "reggae", "world", "hip-hop", "jazz", "experimental", "cd", "vinyl", "music-director", "hard-copy", "manual-review"],
    submissionMethod: "official-wcbn-hard-copy-music-director-submission-route",
    feeRequired: false,
    feeAmount: "Free-first WCBN Music Director route; station says it accepts hard-copy albums, preferably CD or vinyl, from any musicians willing to send them, requiring manual package review.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WCBN explicitly prioritizes hard-copy albums and genre care-of routing. CD/vinyl availability, package destination, genre-director targeting, metadata, clean edits, return expectations and no-bulk outreach must be approved before any mailing or contact.",
    notes: "Official WCBN contact page lists Music Directors and states WCBN accepts music from any and all musicians willing to send a hard copy of their album, preferably CD or vinyl. Protected music-director contact link was observed but not decoded. No package was prepared or mailed."
  },
  {
    name: "WNYU NYU Physical Digital Music Director Submission Route",
    websiteUrl: "https://wnyu.org/",
    submissionUrl: "https://wnyu.org/about",
    sourceUrl: "https://wnyu.org/about",
    sourceType: "automation_run_186_public_research",
    country: "United States / New York NYU freeform college-radio physical and digital music route",
    language: "en",
    genres: ["college-radio", "freeform-radio", "electronic", "dance", "world", "reggae", "hip-hop", "independent-music", "digital-submission", "physical-media", "music-director-email", "manual-review"],
    submissionMethod: "official-wnyu-physical-digital-music-director-submission-route",
    feeRequired: false,
    feeAmount: "Free-first WNYU route; official About page accepts CDs, CD-Rs, LPs, 12-inch, 10-inch and 7-inch records and digital submissions to the Music Director, with physical submissions prioritized.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WNYU accepts both physical and digital submissions, while physical submissions are prioritized. Format choice, Music Director email usage, metadata, clean/radio edit status, rights, and link/download access must be approved before contact or mailing.",
    notes: "Official WNYU About page says to send music, lists physical-media formats and says digital submissions can be sent to the Music Director. No message, file, link or physical package was sent."
  }
];
