import type { PlatformInput } from '../models/types.js';

export const run190BaseSeedPlatforms: PlatformInput[] = [
  {
    name: "Dancing Astronaut Track Promo Music Submission Email Route",
    websiteUrl: "https://dancingastronaut.com/",
    submissionUrl: "https://dancingastronaut.com/contact/",
    sourceUrl: "https://dancingastronaut.com/contact/",
    sourceType: "automation_run_190_public_research",
    country: "Global / electronic dance music media track-promo submission route",
    language: "en",
    genres: ["music-blog", "electronic", "edm", "trap", "techno", "deep-house", "dubstep", "uk-bass", "track-promo", "new-music-friday", "manual-review"],
    submissionMethod: "official-dancing-astronaut-track-promo-submission-email-route",
    feeRequired: false,
    feeAmount: "Free-first/manual editorial email route; the official contact page lists a dedicated Track Promos & Submission address and says submissions sent elsewhere are not accepted.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because the owner must approve track selection, promo copy, one-link/download-link handling, EDM/UK bass/dubstep fit, release timing, rights/authorship, clean/radio edit availability and no-bulk wording before any editorial email is sent.",
    notes: "Official Dancing Astronaut contact page lists a Track Promos & Submission route and a dedicated music-submission email. The homepage showed July 2026 New Music Friday and recent music/news activity. No email, contact form, comment, login or submission action was taken."
  },
  {
    name: "EDM.com Editorial Music Releases Protected Contact Route",
    websiteUrl: "https://edm.com/",
    submissionUrl: "https://edm.com/contact-us/",
    sourceUrl: "https://edm.com/contact-us/",
    sourceType: "automation_run_190_public_research",
    country: "Global / electronic dance music editorial music-release contact route",
    language: "en",
    genres: ["music-blog", "electronic", "edm", "dance", "music-releases", "industry-news", "features", "protected-contact", "manual-review"],
    submissionMethod: "official-edm-com-editorial-contact-music-releases-route",
    feeRequired: false,
    feeAmount: "Free-first/manual editorial route; official contact page lists Editorial Staff contact, but the address is protected/obfuscated and was not decoded or used.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because the route is an editorial contact rather than a structured submission form, the contact is protected, and owner approval is needed for editorial fit, pitch copy, release angle, music-link handling, rights/authorship, AI-content disclosure and no-bulk language before any contact attempt.",
    notes: "Official EDM.com contact page lists Editorial Staff and Marketing & Advertising contacts with protected/obfuscated addresses. The homepage showed active electronic music release/news coverage in 2026. No protected address was decoded, no email was sent and no contact form was used."
  },
  {
    name: "OFFstep ONErpm DIY Digital Music Distribution Upload Route",
    websiteUrl: "https://offstep.com/",
    submissionUrl: "https://offstep.com/",
    sourceUrl: "https://offstep.com/",
    sourceType: "automation_run_190_public_research",
    country: "Global / DIY digital music distribution upload route powered by ONErpm",
    language: "en",
    genres: ["digital-distribution", "spotify", "apple-music", "tiktok", "instagram", "music-video", "royalties", "smart-links", "electronic", "reggae", "world", "manual-review"],
    submissionMethod: "official-offstep-onerpm-diy-digital-distribution-upload-route",
    feeRequired: true,
    feeAmount: "Paid/manual route; the public site says unlimited music upload starts as low as $1.50 per month and exposes login/sign-up/pricing boundaries.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because OFFstep is a paid account-based distribution workflow with upload, metadata, artwork, royalty, collaborator-split, takedown/update, video-delivery, smart-link and marketing-tool implications. Owner must approve account use, plan choice, pricing, rights, release metadata, territories and content-policy fit before any upload or payment action.",
    notes: "Official OFFstep site says artists can upload unlimited music, release to Spotify/Apple Music/Instagram/TikTok and more, keep rights and royalties, and use a human-supervised approval process. No login, signup, plan selection, file upload, metadata entry, delivery, payment or chat/session action was taken."
  },
  {
    name: "Labelcaster Indie Label DSP Distribution Apply Route",
    websiteUrl: "https://labelcaster.com/",
    submissionUrl: "https://labelcaster.com/",
    sourceUrl: "https://labelcaster.com/",
    sourceType: "automation_run_190_public_research",
    country: "Global / indie label digital distribution and payout platform application route",
    language: "en",
    genres: ["digital-distribution", "indie-labels", "artists", "dsp-delivery", "royalty-splits", "contracts", "payments", "spotify", "apple-music", "youtube", "tiktok", "manual-review"],
    submissionMethod: "official-labelcaster-indie-label-account-application-distribution-route",
    feeRequired: false,
    feeAmount: "Free-first/manual application route; official site states DSP distribution with no upfront cost, but account approval, contracts, splits and payout terms need owner/legal review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Labelcaster is an account/application workflow focused on indie-label operations, DSP delivery, contracts, collaborator splits and royalty payouts. Owner must confirm whether MarcsMusic should apply as label/rightsholder, approve account terms, rights metadata, payout setup, split contracts and distribution scope before any form or login action.",
    notes: "Official Labelcaster page exposes Apply/Login routes and says it distributes label music to major DSPs worldwide with no upfront costs, while handling contracts, reporting and payouts. A public contact form with distribution-support topics was observed. No application, contact form, login, contract, payout or distribution action was taken."
  },
  {
    name: "StreetVoice Independent Music Upload Packer Opportunity Route",
    websiteUrl: "https://streetvoice.com/",
    submissionUrl: "https://streetvoice.com/",
    sourceUrl: "https://streetvoice.com/",
    sourceType: "automation_run_190_public_research",
    country: "Taiwan / Global independent music social upload and opportunity route",
    language: "zh-Hant/en",
    genres: ["independent-music", "ugc-platform", "electronic", "hip-hop", "dance", "indie", "mandarin", "creative-commons", "opportunities", "music-upload", "manual-review"],
    submissionMethod: "official-streetvoice-independent-music-member-upload-opportunity-route",
    feeRequired: false,
    feeAmount: "Free-first/freemium member-content route; official site exposes music charts, opportunities, song dispatch/packer navigation and cookie/session boundaries, while member upload/account terms require owner review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because StreetVoice is a UGC/member upload and opportunity platform with cookie/session requirements, multilingual interface, territorial/community fit, member-content terms, metadata, language/genre tagging and rights/licensing implications. Owner must approve account use and upload/submission fit before any app action.",
    notes: "Official StreetVoice site showed active charts, 2026 opportunity listings, music events, song-dispatch navigation and a cookie/session boundary. Public background information confirms registered members can upload music/audio as member content. No cookies were handled, no account was used, no music was uploaded and no opportunity form was submitted."
  }
];