import type { PlatformInput } from '../models/types.js';

export const run116SeedPlatforms: PlatformInput[] = [
  {
    name: "DistroKid Digital Distribution and DistroVid Submission Route",
    websiteUrl: "https://distrokid.com/",
    submissionUrl: "https://distrokid.com/",
    sourceUrl: "https://distrokid.com/",
    sourceType: "automation_run_116_public_research",
    country: "United States / Global independent music and video distribution route",
    language: "en",
    genres: ["distrokid", "digital-distribution", "spotify", "apple-music", "youtube-music", "tidal", "deezer", "distrovid", "music-video-distribution", "independent-artists", "electronic", "reggae", "dub", "world", "paid-route", "account-boundary", "payment-required", "manual-review"],
    submissionMethod: "official-distrokid-digital-distribution-distrovid-submission-route",
    feeRequired: true,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because DistroKid is a paid account-based distribution workflow requiring subscription/payment approval, release metadata, rights verification, store delivery, collaborator splits, Content ID/video-distribution decisions and anti-fraud checks before any upload or delivery.",
    notes: "Public research confirmed DistroKid is an active independent digital music distributor used to deliver music to streaming platforms while letting artists retain rights and royalties; current reporting also references DistroKid video-distribution activity. No account was created, no login was used, no music/video was uploaded, no store delivery was started and no payment was initiated."
  },
  {
    name: "SoundCloud for Artists Upload Promotion and Monetization Route",
    websiteUrl: "https://soundcloud.com/",
    submissionUrl: "https://artists.soundcloud.com/",
    sourceUrl: "https://artists.soundcloud.com/",
    sourceType: "automation_run_116_public_research",
    country: "Germany / United States / Global creator upload and discovery route",
    language: "en",
    genres: ["soundcloud", "soundcloud-for-artists", "creator-upload", "music-sharing", "fan-discovery", "private-links", "promotion", "monetization", "electronic", "reggae", "dub", "world", "afrobeats", "free-first", "freemium", "account-boundary", "app-boundary", "manual-review"],
    submissionMethod: "official-soundcloud-for-artists-upload-promotion-monetization-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because SoundCloud is an account/app-based creator upload route requiring owner review of track rights, metadata, privacy/public settings, private-link strategy, monetization eligibility, promotional tools and current AI/terms controls.",
    notes: "Public research confirmed SoundCloud remains an artist-first music-sharing platform where users upload audio and creators use account-based artist tools; current reporting also highlights active SoundCloud policy handling around uploaded music and AI. No account was created, no login was used, no track was uploaded, no private link was delivered and no paid feature was activated."
  },
  {
    name: "ReverbNation Artist Opportunities and Profile Submission Route",
    websiteUrl: "https://www.reverbnation.com/",
    submissionUrl: "https://www.reverbnation.com/main/opportunities",
    sourceUrl: "https://www.reverbnation.com/main/opportunities",
    sourceType: "automation_run_116_public_research",
    country: "United States / Global independent artist opportunities route",
    language: "en",
    genres: ["reverbnation", "artist-profile", "opportunities", "song-submission", "industry-opportunities", "artist-services", "promotion", "electronic", "reggae", "dub", "world", "hip-hop", "freemium", "account-boundary", "payment-option", "manual-review"],
    submissionMethod: "official-reverbnation-artist-opportunities-profile-submission-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because ReverbNation is an account/profile-based artist-services and opportunities platform; each opportunity must be selected for relevance, eligibility, pricing, rights, song fit and promotional value before any submission can occur.",
    notes: "Public research confirmed ReverbNation is an active independent music-industry platform focused on musicians, producers and venues, with optional registration and artist tools. No account was created, no login was used, no opportunity was selected, no song/profile was submitted and no paid promotion was activated."
  },
  {
    name: "UnitedMasters Independent Artist Release and Brand Opportunity Route",
    websiteUrl: "https://www.unitedmasters.com/",
    submissionUrl: "https://www.unitedmasters.com/",
    sourceUrl: "https://www.unitedmasters.com/",
    sourceType: "automation_run_116_public_research",
    country: "United States / Global independent music distribution and brand-opportunity route",
    language: "en",
    genres: ["unitedmasters", "music-distribution", "independent-artists", "brand-partnerships", "apple-music", "spotify", "tiktok", "instagram", "youtube", "artist-ownership", "electronic", "reggae", "dub", "world", "freemium", "account-boundary", "payment-option", "manual-review"],
    submissionMethod: "official-unitedmasters-independent-artist-release-brand-opportunity-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because UnitedMasters is an account-based distribution and opportunity workflow involving release setup, platform selection, rights/master ownership confirmation, pricing/plan choice, brand-opportunity fit and payout details.",
    notes: "Public research confirmed UnitedMasters lets independent artists upload and distribute music across major platforms and keeps current public visibility through major distribution partnerships and artist-services coverage. No account was created, no login was used, no release was configured, no opportunity was selected and no payment or subscription was initiated."
  },
  {
    name: "Amuse Self-Service Distribution and Artist Services Submission Route",
    websiteUrl: "https://www.amuse.io/",
    submissionUrl: "https://www.amuse.io/en/distribution/",
    sourceUrl: "https://www.amuse.io/en/distribution/",
    sourceType: "automation_run_116_public_research",
    country: "Sweden / Global self-service distribution and artist-services route",
    language: "en",
    genres: ["amuse", "digital-distribution", "self-service-distribution", "spotify", "apple-music", "artist-services", "royalty-advances", "music-insights", "independent-artists", "electronic", "reggae", "dub", "world", "paid-route", "account-boundary", "app-boundary", "manual-review"],
    submissionMethod: "official-amuse-self-service-distribution-artist-services-submission-route",
    feeRequired: true,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Amuse is an account/app-based distribution and artist-services route requiring plan/payment review, metadata, rights, release assets, royalty/advance implications, analytics settings and optional licensing/service choices.",
    notes: "Public research confirmed Amuse is a global music company with self-service distribution, funding and artist services, including subscription tiers and streaming-platform delivery. No account was created, no login was used, no release was configured, no file was uploaded and no payment was initiated."
  }
];
