import type { PlatformInput } from '../models/types.js';

export const run164SeedPlatforms: PlatformInput[] = [
  {
    name: "KDVS 90.3FM Physical Music Department Submission Route",
    websiteUrl: "https://kdvs.org/",
    submissionUrl: "https://kdvs.org/contact/",
    sourceUrl: "https://kdvs.org/contact/",
    sourceType: "automation_run_164_public_research",
    country: "United States / UC Davis freeform college-community radio station with FM and online reach",
    language: "en",
    genres: ["college-radio", "freeform", "uc-davis", "independent", "electronic", "hip-hop", "world", "reggae", "music-director-email", "physical-submission", "manual-review"],
    submissionMethod: "official-kdvs-physical-music-department-submission-route",
    feeRequired: false,
    feeAmount: "No submission fee observed; official contact page lists musicdept@kdvs.org and states all new music should be sent to the mailing address as physical submissions only.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KDVS is a physical-submission-only route; owner must verify format, clean/explicit status, one-sheet, metadata, rights, package contents and mailing decision before any outreach or shipment.",
    notes: "Public research verified KDVS official site activity, listen-live/programming context, official Contact page, Music Directors route, musicdept@kdvs.org, station mailing address and physical-submissions-only instruction. No email was sent, no package was prepared and no SMTP/MX probing was performed."
  },
  {
    name: "KTRU Rice Radio Physical CD LP 7-inch Music Department Submission Route",
    websiteUrl: "https://ktru.org/",
    submissionUrl: "https://ktru.org/contact/",
    sourceUrl: "https://ktru.org/contact/",
    sourceType: "automation_run_164_public_research",
    country: "United States / Rice University non-commercial student radio with FM and online reach",
    language: "en",
    genres: ["college-radio", "rice-university", "non-commercial", "independent", "alternative", "electronic", "experimental", "hip-hop", "world", "physical-submission", "contact-form", "manual-review"],
    submissionMethod: "official-ktru-physical-cd-lp-7inch-music-department-submission-route",
    feeRequired: false,
    feeAmount: "No submission fee observed; official contact page says music submissions are accepted only in physical formats: CD, LP or 7-inch.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KTRU only accepts physical music submissions and also exposes a public contact-form route; owner must verify release format, clean/explicit status, package contents, metadata, station fit and whether any form note is appropriate before action.",
    notes: "Public research verified KTRU official site activity, recent 2026 posts, official Contact page, USPS/UPS physical addresses and physical-format-only submission rule for CD, LP and 7-inch. No form was submitted, no email/message was sent and no package was prepared."
  },
  {
    name: "WUSB Stony Brook Music Director Email Physical Airplay Submission Route",
    websiteUrl: "https://wusb.fm/",
    submissionUrl: "https://wusb.fm/contact",
    sourceUrl: "https://wusb.fm/contact",
    sourceType: "automation_run_164_public_research",
    country: "United States / Stony Brook University non-commercial radio station with FM and online reach",
    language: "en",
    genres: ["college-radio", "stony-brook", "freeform", "independent", "electronic", "hip-hop", "world", "reggae", "music-director-email", "physical-submission", "manual-review"],
    submissionMethod: "official-wusb-music-director-email-physical-airplay-submission-route",
    feeRequired: false,
    feeAmount: "No submission fee observed; official contact page lists md.wusbradio@gmail.com for music email submissions and a station address for physical submissions.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WUSB supports email and physical submission paths; owner must verify audio/link policy, clean/explicit status, release metadata, rights, pitch copy and whether to use email or package route before any contact.",
    notes: "Public research verified WUSB official site activity, 2026 programming/event posts, official Contact page, Music Director email route, Program Director email route and physical mailing address. No email was sent, no links/files were delivered and no package was prepared."
  },
  {
    name: "WXYC UNC Music Director Email and Postal Music Submission Route",
    websiteUrl: "https://wxyc.org/",
    submissionUrl: "https://wxyc.org/contact",
    sourceUrl: "https://wxyc.org/contact",
    sourceType: "automation_run_164_public_research",
    country: "United States / UNC-Chapel Hill student-run freeform radio station with FM and online reach",
    language: "en",
    genres: ["college-radio", "unc-chapel-hill", "freeform", "independent", "electronic", "experimental", "hip-hop", "world", "reggae", "music-director-email", "postal-submission", "manual-review"],
    submissionMethod: "official-wxyc-music-director-email-postal-music-submission-route",
    feeRequired: false,
    feeAmount: "No submission fee observed; official contact page lists md@wxyc.org for music submissions/distribution concerns and a WXYC Music Department postal route.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WXYC offers both email and postal music-submission routes; owner must verify release fit, clean/explicit status, rights, one-sheet, metadata, file/link/package choice and pitch copy before any outreach.",
    notes: "Public research verified WXYC official site activity with Spring 2026 programming/posts, official Contact page, md@wxyc.org for music submissions, outreach@wxyc.org for artist contacts and the WXYC Music Department postal address. No email was sent, no files/links were delivered and no package was prepared."
  },
  {
    name: "WREK Atlanta Music Director Email Snail Mail Airplay Submission Route",
    websiteUrl: "https://wrek.org/",
    submissionUrl: "https://old.wrek.org/submissions/",
    sourceUrl: "https://old.wrek.org/submissions/",
    sourceType: "automation_run_164_public_research",
    country: "United States / Georgia Tech student-managed college radio station with FM and online reach",
    language: "en",
    genres: ["college-radio", "georgia-tech", "freeform", "quality-diverse-music", "electronic", "hip-hop", "world", "reggae", "music-director-email", "snail-mail", "manual-review"],
    submissionMethod: "official-wrek-music-director-email-snail-mail-airplay-submission-route",
    feeRequired: false,
    feeAmount: "No submission fee observed; official WREK music page links to its submission page, which lists snail-mail and music.director@wrek.org email routes.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WREK accepts snail-mail and email submissions but prioritizes CDs/LPs and does not acknowledge receipt; owner must verify format, clean/explicit status, metadata, rights, pitch copy, package contents and follow-up policy before action.",
    notes: "Public research verified WREK official site activity, current music programming, Submit Songs link, official submission page, music.director@wrek.org, snail-mail route, common-media-format policy, CD/LP priority and contact/follow-up guidance. No email was sent, no files/links were delivered and no package was prepared."
  }
];
