import type { PlatformInput } from '../models/types.js';
import { run158SeedPlatforms } from './run158PlatformSeeds.js';

export const run157SeedPlatforms: PlatformInput[] = [
  ...(run158SeedPlatforms as PlatformInput[]),
  {
    name: "UnitedMasters Digital Distribution Brand Sync Pitching Route",
    websiteUrl: "https://unitedmasters.com/",
    submissionUrl: "https://unitedmasters.com/",
    sourceUrl: "https://unitedmasters.com/",
    sourceType: "automation_run_157_public_research",
    country: "Global / United States-based independent music distribution and artist-services platform",
    language: "en",
    genres: ["digital-distribution", "release-upload", "spotify", "apple-music", "tidal", "sync-licensing", "playlist-pitching", "radio-pitching", "artist-marketing", "manual-review", "payment-side-route", "login-required"],
    submissionMethod: "official-unitedmasters-digital-distribution-brand-sync-pitching-route",
    feeRequired: true,
    feeAmount: "Free social-distribution side route and paid DEBUT+/SELECT distribution plans observed; paid plans shown from $19.99/year and $59.99/year, with exact plan, artist profile and release choices requiring owner review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because UnitedMasters requires account/profile creation, plan selection, music-file upload, metadata, artwork, collaborators, royalty-split details, approval submission, payout setup and optional brand/sync, playlist, editorial and radio pitching decisions.",
    notes: "Public research verified UnitedMasters' official artist/distribution page, Sign Up/Login/Get Started routes, release-to-150+ services language, plan pricing, social-distribution side route, platform FAQ and approval/release workflow. No account was created, no login used, no payment initiated, no app workflow entered and no audio/artwork/metadata was uploaded."
  },
  {
    name: "Mixcloud Creator Free Upload Pro Monetization Route",
    websiteUrl: "https://www.mixcloud.com/",
    submissionUrl: "https://www.mixcloud.com/upload/",
    sourceUrl: "https://www.mixcloud.com/",
    sourceType: "automation_run_157_public_research",
    country: "Global / United Kingdom-based audio platform for DJs, curators, producers, stations and music shows",
    language: "en",
    genres: ["audio-platform", "dj-mixes", "radio-shows", "curator-platform", "upload-for-free", "creator-tools", "hq-audio", "live-streaming", "monetization", "manual-review", "freemium", "login-required"],
    submissionMethod: "official-mixcloud-creator-free-upload-pro-monetization-route",
    feeRequired: false,
    feeAmount: "Upload-for-free route observed; Pro creator tools and Premium listener plan are paid side routes, with Pro shown from $11.25/month when paid annually.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Mixcloud upload requires a user account/session, correct show/track metadata, rights-safe audio, DJ/radio-show fit, optional host tagging, HQ audio, monetization and Pro/Premium choices.",
    notes: "Public research verified Mixcloud's official homepage with Sign up, Login, Upload for free, creator tools, unlimited uploads, live streaming, HQ audio, monetization, stats, support and current 2026 live/trending activity. No account was created, no login used, no upload workflow entered and no audio file was transferred."
  },
  {
    name: "BandLab Free Social Publishing and Distribution Route",
    websiteUrl: "https://www.bandlab.com/",
    submissionUrl: "https://www.bandlab.com/",
    sourceUrl: "https://www.bandlab.com/",
    sourceType: "automation_run_157_public_research",
    country: "Global / Singapore-based cloud DAW, creator community and music publishing platform",
    language: "en",
    genres: ["cloud-daw", "music-publishing", "social-music", "creator-platform", "distribution", "music-sharing", "collaboration", "mobile-app", "freemium", "manual-review", "login-required", "app-boundary"],
    submissionMethod: "official-bandlab-free-social-publishing-and-distribution-route",
    feeRequired: false,
    feeAmount: "Freemium creator route observed through public documentation; premium/advanced tools are side routes and any distribution or publishing choices require owner review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because BandLab publishing/distribution depends on account/session access, artist profile, music ownership, metadata, file format, visibility, collaboration settings, social sharing and any premium or distribution options.",
    notes: "Public research verified the official BandLab domain and public activity/documentation describing BandLab as an active freemium music creation, sharing and distribution platform. The official site did not expose a safely parsable static upload form during discovery. No account was created, no login used, no app workflow entered and no audio/project file was uploaded."
  },
  {
    name: "TIDAL Upload Independent Artist Free Self Publish Route",
    websiteUrl: "https://tidal.com/",
    submissionUrl: "https://tidal.com/",
    sourceUrl: "https://tidal.com/",
    sourceType: "automation_run_157_public_research",
    country: "United States eligibility observed / global expansion potential for TIDAL independent artist self-publishing route",
    language: "en",
    genres: ["streaming-platform", "direct-upload", "independent-artist", "self-publishing", "copyright-compliance", "artist-discovery", "spotlight-program", "ai-policy-sensitive", "manual-review", "app-boundary", "login-required"],
    submissionMethod: "public-tidal-upload-independent-artist-free-self-publish-route",
    feeRequired: false,
    feeAmount: "Free TIDAL Upload route reported; no standard streaming royalties for uploaded files were observed in public reporting, with eligibility and incentive terms requiring owner review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because TIDAL Upload is eligibility-bound, rights-sensitive and app/session-based, with ownership, copyright, artist identity, age/location eligibility, no-royalty terms, Spotlight incentives and AI/content-policy implications needing review before use.",
    notes: "Public research verified recent public reporting on TIDAL Upload as a free independent-artist self-publishing route plus current 2026 TIDAL AI/content policy coverage. The safe official static upload surface was not exposed in this run. No account was created, no login used, no app workflow entered and no music was uploaded or transferred."
  },
  {
    name: "NTS Radio PU$$YRAP Mixtape Apply Submission Route",
    websiteUrl: "https://www.nts.live/",
    submissionUrl: "https://www.nts.live/",
    sourceUrl: "https://www.nts.live/",
    sourceType: "automation_run_157_public_research",
    country: "Global / United Kingdom-based online radio platform with public show-specific mixtape application route",
    language: "en",
    genres: ["online-radio", "mixtape-submission", "show-specific-submission", "hip-hop", "rap", "global-radio", "curator-platform", "manual-review", "public-apply-route"],
    submissionMethod: "official-nts-radio-pussyrap-mixtape-apply-submission-route",
    feeRequired: false,
    feeAmount: "No submission fee observed for the public apply route; show fit, theme, rights and mixtape package choices require owner review.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because this is a show-specific public application route, not a generic auto-submit inbox; MarcsMusic fit, mixtape concept, clean/explicit status, rights, links/files and the application/session flow must be reviewed before use.",
    notes: "Public research observed NTS public site context and a homepage show card indicating a mixtape submission/application route for PU$$YRAP. NTS activity and global platform context were verified from public sources. No apply workflow was entered, no form was submitted, no music link was delivered and no account/session boundary was handled."
  }
];
