import type { PlatformInput } from '../models/types.js';

export const run199BaseSeedPlatforms: PlatformInput[] = [
  {
    name: "Stereofox SubmitHub Groover No Email Music Submission Route",
    websiteUrl: "https://www.stereofox.com/",
    submissionUrl: "https://www.stereofox.com/contact/",
    sourceUrl: "https://www.stereofox.com/contact/",
    sourceType: "automation_run_199_public_research",
    country: "Global / curated music blog SubmitHub and Groover submission route",
    language: "en",
    genres: ["music-blog", "curated-playlists", "submithub", "groover", "no-email-submissions", "independent-artists", "electronic", "chill", "hip-hop", "manual-review"],
    submissionMethod: "official-stereofox-submithub-groover-no-email-route",
    feeRequired: false,
    feeAmount: "Free-first/freemium manual route; official Stereofox contact page directs music submissions to SubmitHub or Groover and explicitly says email/Discord submissions are not processed. Third-party platform pricing and credit choices must be checked manually.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Stereofox routes submissions through third-party platforms, has a no-email/no-Discord policy, and may expose login/session, platform-credit, queue and payment choices. The owner must review fit, rights, streaming link, genre tags, pitch text and any paid option. No platform submission, login, message or payment step may be automated.",
    notes: "Official Stereofox contact page says music submissions should use SubmitHub or Groover, says email/Discord submissions are not processed, references high submission volume, and shows 2026 site/cookie context. No email, platform account, upload, payment or anti-abuse control was used."
  },
  {
    name: "The Line of Best Fit New Unsigned Artist Google Form Email Route",
    websiteUrl: "https://www.thelineofbestfit.com/",
    submissionUrl: "https://www.thelineofbestfit.com/contact",
    sourceUrl: "https://www.thelineofbestfit.com/contact",
    sourceType: "automation_run_199_public_research",
    country: "United Kingdom / global new and unsigned artist editorial form and press email route",
    language: "en",
    genres: ["music-magazine", "new-artists", "unsigned-artists", "google-form", "editorial", "press-email", "indie", "pop", "electronic", "manual-review"],
    submissionMethod: "official-line-of-best-fit-new-unsigned-artist-google-form-email-route",
    feeRequired: false,
    feeAmount: "Free-first/manual editorial route; official contact page welcomes music from new and unsigned artists through a linked Google document/form route and lists public press/contact email patterns with no submission fee observed.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because the artist route is an external Google document/form path and the contact emails are written in human-readable anti-scrape format. Owner review is needed for editorial fit, rights, concise pitch, release status, form fields, login/session prompts and anti-abuse boundaries. No form, email, login or document interaction may be automated.",
    notes: "Official The Line of Best Fit contact page says it welcomes music from new and unsigned artists and links to a Google document/form route, while the homepage shows active July 2026 music coverage. Contacts were only observed from the public page and no decoding, email, form submission or login was performed."
  },
  {
    name: "musicOMH Album Download URL Limited Review Pitch Route",
    websiteUrl: "https://www.musicomh.com/",
    submissionUrl: "https://www.musicomh.com/contact-us",
    sourceUrl: "https://www.musicomh.com/contact-us",
    sourceType: "automation_run_199_public_research",
    country: "United Kingdom / global album review download URL and CD enquiry route",
    language: "en",
    genres: ["music-magazine", "album-review", "download-url", "cd-postal-on-request", "uk-release-date", "no-singles", "no-eps", "electronic", "world", "manual-review"],
    submissionMethod: "official-musicomh-album-download-url-limited-review-pitch-route",
    feeRequired: false,
    feeAmount: "Free-first/manual editorial route; official musicOMH contact page lists public email contact and album-review guidance with no submission fee observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because musicOMH says direct submissions are usually not considered, focuses on albums ahead of UK release dates, does not currently cover tracks, EPs, videos or singles, and asks for album download URL context or CD address enquiry. No email, download transfer or physical package may be automated.",
    notes: "Official musicOMH contact page lists hello@musicomh.com, album review guidance, download URL requirements and CD-address enquiry guidance; the homepage/contact context shows active 2026 editorial coverage and cookie/consent boundaries. No email, link transfer, cookie handling or deliverability probe was performed."
  },
  {
    name: "KCSB Santa Barbara Music Director All Formats Email Postal Form Route",
    websiteUrl: "https://www.kcsb.org/",
    submissionUrl: "https://www.kcsb.org/contact/",
    sourceUrl: "https://www.kcsb.org/contact/",
    sourceType: "automation_run_199_public_research",
    country: "United States / Santa Barbara college radio all-format music director email postal form route",
    language: "en",
    genres: ["college-radio", "santa-barbara", "music-director", "email-submission", "postal-submission", "public-form", "all-formats", "independent-artists", "electronic", "manual-review"],
    submissionMethod: "official-kcsb-music-director-all-formats-email-postal-form-route",
    feeRequired: false,
    feeAmount: "Free-first/manual college-radio route; official contact page lists a Music Director email, physical mailing routes and a public message form with Music submission topic, with no submission fee observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KCSB accepts new releases/demos in all formats through music-director email, postal attention-line routes and a public contact form. Owner review is needed for format choice, clean edits, metadata, package/link preparation, no-attachment policy and form-topic fit. No email, form or physical package may be automated.",
    notes: "Official KCSB contact page lists int.md@kcsb.org for the Music Director, says all formats are welcome for music submissions, gives postal shipping addresses and exposes a contact form with Music submission as a topic. No form, email, upload, package or probe was performed."
  },
  {
    name: "WTSR 91.3FM TCNJ Music Director Student Board Submission Route",
    websiteUrl: "https://wtsr.org/",
    submissionUrl: "https://wtsr.org/contacts/",
    sourceUrl: "https://wtsr.org/contacts/",
    sourceType: "automation_run_199_public_research",
    country: "United States / New Jersey college radio music director email submission route",
    language: "en",
    genres: ["college-radio", "new-jersey", "music-director", "email-submission", "student-board", "independent-artists", "alternative", "electronic", "underground", "manual-review"],
    submissionMethod: "official-wtsr-music-director-student-board-email-submission-route",
    feeRequired: false,
    feeAmount: "Free-first/manual college-radio email route; official WTSR contacts page says artists can submit music and lists public Music Director and Assistant Music Director email routes with no submission fee observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WTSR is a volunteer-run student station with direct board-member email routes. Owner review is needed for concise routing, rights, clean radio edit status, genre fit, link-only pitch preparation and avoiding unsolicited attachments. No email, private link delivery or repeated contact may be automated.",
    notes: "Official WTSR contacts page says listeners/artists can submit music and lists Music Director music@wtsr.org plus Assistant Music Director asstmusic@wtsr.org; site schedule and copyright context show active 2026 station activity. No email, login, upload, message or deliverability probe was performed."
  }
];
