import type { PlatformInput } from '../models/types.js';

export const run107SeedPlatforms: PlatformInput[] = [
  {
    name: "FBi Radio Music Submissions Email Route",
    websiteUrl: "https://www.fbi.radio/",
    submissionUrl: "https://www.fbi.radio/contact",
    sourceUrl: "https://www.fbi.radio/contact",
    sourceType: "automation_run_107_public_research",
    country: "Australia / Sydney independent community radio",
    language: "en",
    genres: ["fbi-radio", "sydney", "australia", "community-radio", "independent-radio", "electronic", "dance", "hip-hop", "soul", "rnb", "indie", "emerging-artists", "radio-airplay", "public-email", "free-first", "manual-review"],
    submissionMethod: "official-fbi-radio-music-submissions-email-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because FBi Radio exposes an official Music Submissions email route, but the pitch, metadata, stream or download links, local/Sydney fit and clean asset permissions must be checked before any outreach.",
    notes: "Public research confirmed fbi.radio is active in 2026 and positions itself as championing emerging Sydney music and culture. Its official Contact page lists a public Music Submissions route plus station contact details. No email was sent, no files or download links were delivered and no SMTP/MX probing was performed."
  },
  {
    name: "PBS 106.7FM Submit Your Music Form and Music Department Route",
    websiteUrl: "https://www.pbsfm.org.au/",
    submissionUrl: "https://www.pbsfm.org.au/submitmusic",
    sourceUrl: "https://www.pbsfm.org.au/submitmusic",
    sourceType: "automation_run_107_public_research",
    country: "Australia / Melbourne community radio",
    language: "en",
    genres: ["pbs-fm", "melbourne", "australia", "community-radio", "under-represented-music", "local-music", "electronic", "roots", "dub", "reggae", "world", "dance", "radio-airplay", "public-form", "physical-mail", "captcha", "free-first", "manual-review"],
    submissionMethod: "official-pbs-submit-your-music-form-and-music-department-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because PBS uses a public music-submission form with CAPTCHA, requests specific stream and high-quality download fields, rejects Spotify/Deezer links, and also supports physical package handling.",
    notes: "Public research confirmed PBS FM is active in 2026 with current feature albums, interviews and events. The official Submit Your Music page says PBS accepts local and international music, prefers the digital form, identifies CD/vinyl postal handling, requests 4-5 copies for physical releases, requires a high-quality download link and includes CAPTCHA. No form was submitted, no CAPTCHA was interacted with, no files were uploaded and no physical package was sent."
  },
  {
    name: "4ZZZ Music Department Airplay and Album of the Week Form Route",
    websiteUrl: "https://4zzz.org.au/",
    submissionUrl: "https://4zzz.org.au/music-submissions",
    sourceUrl: "https://4zzz.org.au/music-submissions",
    sourceType: "automation_run_107_public_research",
    country: "Australia / Brisbane community radio",
    language: "en",
    genres: ["4zzz", "brisbane", "australia", "community-radio", "independent-radio", "local-music", "electronic", "dub", "reggae", "hip-hop", "punk", "world", "radio-airplay", "external-form", "album-of-the-week", "free-first", "manual-review"],
    submissionMethod: "official-4zzz-music-department-airplay-and-album-of-the-week-form-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because 4ZZZ routes submissions through an external station form, requires downloadable music rather than non-downloadable streams, and has a separate Album of the Week consideration route.",
    notes: "Public research confirmed the official 4ZZZ Music Submissions page invites artists to submit to the Music Department for airplay consideration, states that 4ZZZ is not playlisted, requires music that can be downloaded, and links to external forms for general music submission and Album of the Week consideration. No external form was opened or submitted, no session controls were touched and no files were uploaded."
  },
  {
    name: "Triple R 102.7FM Submit Music Email and Physical Route",
    websiteUrl: "https://www.rrr.org.au/",
    submissionUrl: "https://www.rrr.org.au/get-involved/submit-music",
    sourceUrl: "https://www.rrr.org.au/get-involved/submit-music",
    sourceType: "automation_run_107_public_research",
    country: "Australia / Melbourne independent radio",
    language: "en",
    genres: ["triple-r", "3rrr", "melbourne", "australia", "independent-radio", "community-radio", "electronic", "hip-hop", "metal", "indie", "world", "experimental", "radio-airplay", "public-email", "physical-mail", "free-first", "manual-review"],
    submissionMethod: "official-triple-r-submit-music-email-and-physical-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Triple R is not playlisted, allows direct presenter servicing or station servicing, and requires a no-login stream, high-quality non-expiring download link, file naming, short bio and optional physical package routing.",
    notes: "Public research confirmed Triple R is active on 4 July 2026 with current programming, events, latest episodes, videos and live-at-station content. The official Submit Music page says presenters choose tracks, artists can service specific programs or the station, and station submissions need a clear subject line, no-login stream, 320kbps MP3 or WAV download link, clear file names, bio and gig details. It also lists physical release instructions. No email was sent, no files or download links were delivered and no physical package was sent."
  },
  {
    name: "2SER Submit Your Music Airplay Consideration Form Route",
    websiteUrl: "https://www.2ser.com/",
    submissionUrl: "https://www.2ser.com/how-to-submit-music",
    sourceUrl: "https://www.2ser.com/how-to-submit-music",
    sourceType: "automation_run_107_public_research",
    country: "Australia / Sydney community radio",
    language: "en",
    genres: ["2ser", "sydney", "australia", "community-radio", "independent-radio", "alternative", "electronic", "live-at-2ser", "radio-airplay", "public-form", "javascript-form", "free-first", "manual-review"],
    submissionMethod: "official-2ser-submit-your-music-airplay-consideration-form-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because 2SER exposes a public airplay-consideration form but the page includes a form-loading boundary and requires artist, release, location, bio and social details that must be prepared manually.",
    notes: "Public research confirmed 2SER is active in 2026 with recent music stories and its official How to Submit Music page exposes a Submit Your Music form for airplay consideration with fields for name, email, music, location, release date, artist or band name, release title, artist bio and social links. The form was not submitted and no login, CAPTCHA or session boundary was bypassed."
  }
];
