import type { PlatformInput } from '../models/types.js';

export const run147SeedPlatforms: PlatformInput[] = [
  {
    name: "Groover Paid Credit Tastemaker and Media Submission Route",
    websiteUrl: "https://groover.co/",
    submissionUrl: "https://groover.co/en/",
    sourceUrl: "https://groover.co/",
    sourceType: "automation_run_147_public_research",
    country: "Global / music promotion platform connecting artists with media, radios, labels, playlist curators and industry professionals",
    language: "en",
    genres: ["music-promotion", "blogs", "radio", "playlist-curators", "labels", "sync", "industry-professionals", "paid-credit", "account-boundary", "manual-review"],
    submissionMethod: "official-groover-artist-to-curator-credit-submission-route",
    feeRequired: true,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Groover submissions involve account access, paid credits, curator/media selection, track/package metadata, rights-sensitive pitch copy and editorial-independence terms.",
    notes: "Public research verified Groover as a worldwide music promotion platform connecting artists with media outlets and music professionals via a micro-payment model. No account was created, no curator was selected, no track/link was submitted and no payment was initiated."
  },
  {
    name: "SubmitHub Free Premium Curator Blog Label Submission Route",
    websiteUrl: "https://www.submithub.com/",
    submissionUrl: "https://www.submithub.com/submit",
    sourceUrl: "https://www.submithub.com/",
    sourceType: "automation_run_147_public_research",
    country: "Global / curator, blog, playlist, label and influencer submission marketplace",
    language: "en",
    genres: ["music-promotion", "blogs", "playlists", "labels", "influencers", "free-submission", "premium-credits", "account-boundary", "payment-boundary", "manual-review"],
    submissionMethod: "official-submithub-artist-to-curator-free-premium-submission-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because SubmitHub submissions can use free or premium credits and require owner-controlled account access, track selection, pitch context, curator targeting and response/approval expectations.",
    notes: "Public research verified SubmitHub as an artist-to-curator submission service with free and paid submission options referenced in music-promotion guidance. No login was used, no curator was selected, no pitch was sent and no credits/payment were used."
  },
  {
    name: "Playlist Push Paid Spotify TikTok Curator Campaign Route",
    websiteUrl: "https://playlistpush.com/",
    submissionUrl: "https://playlistpush.com/artists",
    sourceUrl: "https://playlistpush.com/",
    sourceType: "automation_run_147_public_research",
    country: "Global / Spotify playlist curator and TikTok creator campaign submission route",
    language: "en",
    genres: ["spotify-playlists", "tiktok-creators", "playlist-promotion", "creator-marketing", "paid-campaign", "account-boundary", "payment-boundary", "manual-review"],
    submissionMethod: "official-playlist-push-artist-campaign-submission-route",
    feeRequired: true,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Playlist Push campaign setup involves account/session access, track eligibility, genre targeting, creator/playlist campaign selection, budget/payment and platform-policy checks.",
    notes: "Public research verified Playlist Push as a paid submission option for reaching playlist creators and social media influencers. No account was created, no campaign was configured, no targeting was selected and no payment was initiated."
  },
  {
    name: "Soundplate Free Spotify Deezer Playlist Submission System Route",
    websiteUrl: "https://soundplate.com/",
    submissionUrl: "https://play.soundplate.com/",
    sourceUrl: "https://play.soundplate.com/",
    sourceType: "automation_run_147_public_research",
    country: "Global / free Spotify and Deezer playlist submission system for artists",
    language: "en",
    genres: ["spotify-playlists", "deezer-playlists", "playlist-submission", "electronic-music", "free-first", "cloudflare-or-verification-boundary", "manual-review"],
    submissionMethod: "official-soundplate-free-playlist-submission-system-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because the Soundplate playlist submission system reached a request-verification/session boundary and playlist/track targeting should remain owner-controlled.",
    notes: "Public research verified Soundplate as a music technology company with Play.Soundplate described as a free playlist submission system for Spotify and Deezer. Opening the live Play.Soundplate route exposed a request-verification boundary; no challenge was handled and no track was submitted."
  },
  {
    name: "KCRW Local Regional Touring Artist Airplay Recording Submission Route",
    websiteUrl: "https://www.kcrw.com/",
    submissionUrl: "https://www.kcrw.com/music",
    sourceUrl: "https://www.kcrw.com/",
    sourceType: "automation_run_147_public_research",
    country: "United States / Southern California public-radio airplay consideration route with global eclectic programming context",
    language: "en",
    genres: ["public-radio", "eclectic", "electronic", "world", "reggae", "latin", "indie", "airplay", "local-regional-fit", "manual-review"],
    submissionMethod: "official-kcrw-local-regional-airplay-recording-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KCRW airplay consideration is local/regional touring-artist dependent and requires selecting the right recording, metadata, clean context, tour angle and pitch route.",
    notes: "Public research verified KCRW's eclectic music programming, electronic/dance/world/reggae-related show context and guidance that local and regional touring artists can send recordings for airplay consideration. No recording was sent, no contact was used and no pitch was submitted."
  }
];
