import type { PlatformInput } from '../models/types.js';
import { run149SeedPlatforms } from './run149PlatformSeeds.js';

export const run148SeedPlatforms: PlatformInput[] = [
  {
    name: "BBC Music Introducing Uploader Local Show Airplay Route",
    websiteUrl: "https://www.bbc.co.uk/introducing",
    submissionUrl: "https://www.bbc.co.uk/introducing/uploader",
    sourceUrl: "https://www.bbc.co.uk/introducing",
    sourceType: "automation_run_148_public_research",
    country: "United Kingdom / BBC local and national Introducing network for unsigned and under-the-radar music talent",
    language: "en",
    genres: ["bbc-introducing", "unsigned-artists", "local-radio", "national-radio-forwarding", "festival-stages", "uploader", "account-boundary", "ugc-terms", "manual-review"],
    submissionMethod: "official-bbc-music-introducing-uploader-local-show-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because BBC Introducing upload routing depends on owner-controlled account access, UK/postcode eligibility, UGC terms, track metadata, clean/context notes and rights confirmation.",
    notes: "Public research verified BBC Music Introducing as an active BBC music upload platform supporting unsigned, undiscovered and under-the-radar UK talent, with an uploader that routes material to local Introducing producers and presenters. No account was created, no upload was attempted and no UGC workflow was entered."
  },
  {
    name: "triple j Unearthed Australian Artist Upload and Radio Route",
    websiteUrl: "https://www.triplejunearthed.com/",
    submissionUrl: "https://www.triplejunearthed.com/",
    sourceUrl: "https://www.triplejunearthed.com/",
    sourceType: "automation_run_148_public_research",
    country: "Australia / ABC-owned online music discovery and digital radio platform for Australian independent artists",
    language: "en",
    genres: ["triple-j-unearthed", "australian-music", "independent-artists", "digital-radio", "artist-upload", "account-boundary", "eligibility-review", "manual-review"],
    submissionMethod: "official-triple-j-unearthed-australian-artist-upload-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Unearthed is limited to Australian music uploaded to the site and requires account access, artist eligibility, track metadata, rights confirmation and profile/release choices.",
    notes: "Public research verified triple j Unearthed as an ABC-owned Australian online music discovery and digital radio platform where local artists can upload music for station staff and listeners. No account was created, no artist profile was changed and no track was uploaded."
  },
  {
    name: "Spinnin Records Talent Pool Dashboard Submission Route",
    websiteUrl: "https://spinninrecords.com/",
    submissionUrl: "https://spinninrecords.com/releases/?label=spinnin-talent-pool",
    sourceUrl: "https://spinninrecords.com/releases/?label=spinnin-talent-pool",
    sourceType: "automation_run_148_public_research",
    country: "Global / Netherlands-linked dance label community route for electronic and festival music producers",
    language: "en",
    genres: ["dance-label", "edm", "electronic", "house", "talent-pool", "contests", "dashboard", "login-boundary", "manual-review"],
    submissionMethod: "official-spinnin-records-talent-pool-dashboard-submission-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because the Talent Pool route exposes a login/dashboard workflow and requires owner-controlled account access, track selection, rights metadata, contest or pool choice and label-fit review.",
    notes: "Public research verified Spinnin Records exposes an official Talent Pool area with dashboard, FAQ and Terms links plus a login boundary. No login was used, no dashboard workflow was entered, no contest was selected and no track was submitted."
  },
  {
    name: "Revealed Recordings Official Demo Login and Pro Side Route",
    websiteUrl: "https://www.revealedrecordings.com/",
    submissionUrl: "https://www.revealedrecordings.com/demo",
    sourceUrl: "https://www.revealedrecordings.com/demo",
    sourceType: "automation_run_148_public_research",
    country: "Global / Netherlands-linked Revealed Recordings electronic label demo route",
    language: "en",
    genres: ["electronic-label", "big-room", "mainstage", "trance", "demo", "login-boundary", "pro-subscription-side-route", "payment-boundary", "manual-review"],
    submissionMethod: "official-revealed-recordings-demo-login-submission-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because the official Demo route redirects to sign-in, and Revealed also exposes Pro/subscription and paid-download side routes that must not be entered or selected automatically.",
    notes: "Public research verified the official Revealed website has a Demo navigation route, active releases and Sign in/Create account options; opening the Demo route redirected to a login page. No login was used, no Pro/subscription flow was entered and no demo was submitted."
  },
  {
    name: "Protocol Recordings Protocol Radio New Producer Platform Route",
    websiteUrl: "https://protocolrecordings.com/",
    submissionUrl: "https://protocolrecordings.com/",
    sourceUrl: "https://protocolrecordings.com/",
    sourceType: "automation_run_148_public_research",
    country: "Global / Netherlands electronic label and Protocol Radio route for producer discovery",
    language: "en",
    genres: ["electronic-label", "progressive-house", "electro-house", "protocol-radio", "new-producers", "platform-submission-context", "manual-review"],
    submissionMethod: "official-protocol-recordings-platform-and-radio-new-producer-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because the public source verifies a producer/platform submission context but the current safe public auto-submit surface was not fully exposed; label fit, rights, metadata and route selection require review.",
    notes: "Public research verified Protocol Recordings as Nicky Romero's Dutch electronic label and Protocol Radio as a weekly route featuring tracks from label artists and new artists whose works can be sent through the platform. The official site was not safely entered beyond public discovery; no form, upload, message or login workflow was used."
  },
  ...run149SeedPlatforms
];
