import type { PlatformInput } from '../models/types.js';

export const run198BaseSeedPlatforms: PlatformInput[] = [
  {
    name: "XRAY.fm Portland Public Music Submissions Email Guidelines Route",
    websiteUrl: "https://xray.fm/",
    submissionUrl: "https://xray.fm/contact",
    sourceUrl: "https://xray.fm/contact",
    sourceType: "automation_run_198_public_research",
    country: "United States / Portland community radio public music-submission email route",
    language: "en",
    genres: ["community-radio", "portland", "independent-artists", "email-submission", "submission-guidelines", "electronic", "world", "reggae", "manual-review"],
    submissionMethod: "official-xrayfm-public-music-submissions-email-guidelines-route",
    feeRequired: false,
    feeAmount: "Free-first/manual route; official XRAY.fm contact page lists a public Music Submissions email and public music submission guidelines, with no submission fee observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required for guideline compliance, concise pitch wording, rights, clean metadata, release fit and link/file preparation.",
    notes: "Official XRAY.fm contact page lists Music Submissions and points submitters to music submission guidelines."
  },
  {
    name: "WYEP Pittsburgh Local Music Link Airplay Submission Route",
    websiteUrl: "https://www.wyep.org/",
    submissionUrl: "https://www.wyep.org/wyep-pittsburgh-area-music-submissions",
    sourceUrl: "https://www.wyep.org/wyep-pittsburgh-area-music-submissions",
    sourceType: "automation_run_198_public_research",
    country: "United States / Pittsburgh-area public radio local music link and hard-copy airplay route",
    language: "en",
    genres: ["public-radio", "pittsburgh", "local-music", "link-submission", "physical-submission", "fcc-clean", "electronic", "world", "manual-review"],
    submissionMethod: "official-wyep-pittsburgh-localmusic-link-airplay-submission-route",
    feeRequired: false,
    feeAmount: "Free-first/manual local route; official WYEP page asks Pittsburgh-area artists to email a music link or mail a hard copy, with no submission fee observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required for local eligibility, FCC-clean suitability, album-track guidance, background context and link or package choice.",
    notes: "Official WYEP page asks artists to email SoundCloud/Spotify/YouTube/Dropbox-style links or mail hard copies."
  },
  {
    name: "Radio Wigwam Basic Artist Upload Grassroots Submission Route",
    websiteUrl: "https://radiowigwam.co.uk/",
    submissionUrl: "https://radiowigwam.co.uk/_useradmin/?uploadtrack=true",
    sourceUrl: "https://radiowigwam.co.uk/",
    sourceType: "automation_run_198_public_research",
    country: "United Kingdom / global grassroots radio artist account upload route",
    language: "en",
    genres: ["grassroots-radio", "uk", "artist-upload", "free-first", "freemium", "independent-artists", "rock", "electronic", "world", "manual-review"],
    submissionMethod: "official-radio-wigwam-artist-account-upload-track-route",
    feeRequired: false,
    feeAmount: "Free-first/freemium manual route; homepage/pricing show a Basic Artist tier with 1 free submission/upload per month, plus paid Premiere/Agency tiers with higher upload allowances.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Radio Wigwam uses account/login and upload boundaries with free and paid artist tiers.",
    notes: "Official Radio Wigwam homepage exposes Submit Music and Log In routes and shows current 2026 site activity."
  },
  {
    name: "Obscure Sound SubmitHub MusoSoup Direct Email Editorial Route",
    websiteUrl: "https://www.obscuresound.com/",
    submissionUrl: "https://www.obscuresound.com/about/contact/",
    sourceUrl: "https://www.obscuresound.com/about/contact/",
    sourceType: "automation_run_198_public_research",
    country: "United States / global independent music blog SubmitHub MusoSoup and direct email route",
    language: "en",
    genres: ["music-blog", "editorial", "submithub", "musosoup", "direct-email", "electronic", "ambient", "hip-hop", "indie", "manual-review"],
    submissionMethod: "official-obscure-sound-submithub-musosoup-direct-email-route",
    feeRequired: false,
    feeAmount: "Free-first/freemium manual route; official page allows direct email and platform routes, with SubmitHub/MusoSoup prioritized and optional paid PR services starting at $530.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because the route offers multiple submission paths, including third-party platforms, direct email and paid PR side services.",
    notes: "Official Obscure Sound contact/submissions page lists SubmitHub, SubmitHub Marketplace, MusoSoup and direct email options."
  },
  {
    name: "A&R Factory Electronic Music Free Paid Form Submission Route",
    websiteUrl: "https://www.anrfactory.com/",
    submissionUrl: "https://www.anrfactory.com/submit-demo/electronic-music/",
    sourceUrl: "https://www.anrfactory.com/submit-demo/electronic-music/",
    sourceType: "automation_run_198_public_research",
    country: "United Kingdom / global electronic music blog editorial form route",
    language: "en",
    genres: ["music-blog", "a-and-r", "electronic", "edm", "dance", "drum-and-bass", "reggae", "world", "form-submission", "manual-review"],
    submissionMethod: "official-anr-factory-electronic-music-form-free-paid-route",
    feeRequired: false,
    feeAmount: "Free-first/freemium manual route; official form exposes Free Submission plus Standard Submission £20 and Premium Donation Submission £30 payment options.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because the route is a multi-step form with release, social, EPK, package and payment choices.",
    notes: "Official A&R Factory electronic submission page includes a form, one-track review link requirement, free option and paid options."
  }
];
