import type { PlatformInput } from '../models/types.js';

export const run104SeedPlatforms: PlatformInput[] = [
  {
    name: "EARMILK SubmitHub and Pillargram Music Submission Route",
    websiteUrl: "https://earmilk.com/",
    submissionUrl: "https://earmilk.com/submit-music/",
    sourceUrl: "https://earmilk.com/submit-music/",
    sourceType: "automation_run_104_public_research",
    country: "United States / North American global online music publication",
    language: "en",
    genres: ["earmilk", "music-blog", "online-publication", "dance", "electronic", "experimental", "hip-hop", "indie", "pop", "rock", "submithub", "pillargram", "external-platform", "freemium-manual", "account-boundary", "payment-side-route", "manual-review"],
    submissionMethod: "official-earmilk-submithub-and-pillargram-music-submission-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because EARMILK says music is accepted exclusively through SubmitHub or Pillargram. External platform account/session handling, paid-option avoidance, premiere fit, metadata, rights, track-link permissions and pitch copy require manual handling.",
    notes: "Public research confirmed EARMILK is active with July 2026 music posts, covers dance, electronic, experimental, hip-hop, indie, pop and rock, and states that submissions are accepted exclusively through SubmitHub or Pillargram. No SubmitHub or Pillargram account was opened, no login was used, no payment option was selected, no music or links were submitted and no SMTP/MX probing was performed."
  },
  {
    name: "Stereofox SubmitHub and Groover Music Submission Route",
    websiteUrl: "https://www.stereofox.com/",
    submissionUrl: "https://www.stereofox.com/contact/",
    sourceUrl: "https://www.stereofox.com/contact/",
    sourceType: "automation_run_104_public_research",
    country: "Bulgaria / global independent music blog playlist and label ecosystem",
    language: "en",
    genres: ["stereofox", "music-blog", "playlist", "independent-music", "electronic", "electronica", "progressive-house", "house", "melodic-house", "uk-garage", "lofi", "jazzhop", "submithub", "groover", "external-platform", "freemium-manual", "account-boundary", "payment-side-route", "manual-review"],
    submissionMethod: "official-stereofox-submithub-and-groover-music-submission-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Stereofox explicitly routes music submissions to SubmitHub or Groover and says email or Discord submissions are not processed. External account/session handling, curator fit, paid-option avoidance, metadata, link permissions and pitch copy require manual review.",
    notes: "Public research confirmed Stereofox is active with a 2026 footer, recent editorial activity, curated playlists for electronic and adjacent genres, and an official contact page that routes music submissions to SubmitHub or Groover instead of email or Discord. No external platform session was used, no payment was selected, no Discord route was joined, no message was sent and no SMTP/MX probing was performed."
  },
  {
    name: "A&R Factory Free and Paid Editorial Submission Form Route",
    websiteUrl: "https://www.anrfactory.com/",
    submissionUrl: "https://www.anrfactory.com/submit-demo/",
    sourceUrl: "https://www.anrfactory.com/submit-demo/",
    sourceType: "automation_run_104_public_research",
    country: "United Kingdom / global independent A&R and music blog",
    language: "en",
    genres: ["a-and-r-factory", "music-blog", "a-and-r", "independent-artists", "unsigned-artists", "edm", "electronic", "drum-and-bass", "dancehall", "hip-hop", "house", "reggae", "world", "synthwave", "techno", "trap", "public-form", "free-first", "payment-side-route", "manual-review"],
    submissionMethod: "official-ar-factory-free-and-paid-editorial-submission-form-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because A&R Factory exposes a multi-step submission form with a free submission option alongside paid Standard and Premium Donation options and payment fields. Package choice, free-first handling, metadata, release status, one-track selection, artwork/EPK links, marketing-budget questions and payment avoidance require manual review.",
    notes: "Public research confirmed A&R Factory is active with July 2026 posts, says artists can submit through its website regardless of genre or location, supports EDM, electronic, drum and bass, dancehall, reggae, world and other genres, and exposes form fields for artist name, genre, one track, release status, date, links, artwork/photo, EPK/bio, email and package selection. No form was submitted, no payment was selected and no SMTP/MX probing was performed."
  },
  {
    name: "EDM Identity Track Submission Email Route",
    websiteUrl: "https://edmidentity.com/",
    submissionUrl: "https://edmidentity.com/contact/",
    sourceUrl: "https://edmidentity.com/contact/",
    sourceType: "automation_run_104_public_research",
    country: "United States / global electronic music news and festival culture publication",
    language: "en",
    genres: ["edm-identity", "electronic-music", "edm-news", "festival-culture", "track-submission", "editorial-email", "links-only", "house", "techno", "dubstep", "bass", "trance", "drum-and-bass", "public-email", "free-first", "redacted-contact", "manual-review"],
    submissionMethod: "official-edm-identity-track-submission-email-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because EDM Identity lists an official track-submission email route and asks for links only. The fetched page redacts email values, so no contact may be decoded or guessed; pitch copy, link permissions, metadata, clean/radio-friendly edits and editorial fit require manual handling.",
    notes: "Public research confirmed EDM Identity is active with July 2026 electronic music coverage and its official contact page lists separate editorial, track-submission, team, advertising and general routes. The displayed email values were protected/redacted by the fetch layer. No redacted contact was decoded or guessed, no email was sent, no track link was delivered and no SMTP/MX probing was performed."
  },
  {
    name: "House Nest Media and Promotion Submissions Form Route",
    websiteUrl: "https://housenest.net/",
    submissionUrl: "https://housenest.net/media-promotion/",
    sourceUrl: "https://housenest.net/media-promotion/",
    sourceType: "automation_run_104_public_research",
    country: "Global / electronic music media and culture platform",
    language: "en",
    genres: ["house-nest", "electronic-music", "house", "techno", "edm", "music-media", "artist-interview", "feature", "single-review", "ep-review", "album-review", "premiere", "in-the-mix", "public-form", "promotion", "unknown-manual", "manual-review"],
    submissionMethod: "official-house-nest-media-and-promotion-submissions-form-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because House Nest exposes a public submissions form inside a media/promotion page with multiple enquiry types including news, interview, feature, single/EP review, album review, premiere and in-the-mix. Editorial/promotional intent, pricing ambiguity, fit, metadata, track links, pitch copy and form-handling boundaries require manual review.",
    notes: "Public research confirmed House Nest is an electronic-music media platform with 2026 activity and a Media & Promotion page describing global electronic music coverage and a public submissions form with enquiry types for news, interviews, features, reviews, premieres and collaborations. No form was submitted, no files or links were delivered, no payment was initiated and no SMTP/MX probing was performed."
  }
];
