import type { PlatformInput } from '../models/types.js';

export const run169SeedPlatforms: PlatformInput[] = [
  {
    name: "AWAL Selective Submit Your Music Distribution Application Route",
    websiteUrl: "https://www.awal.com/",
    submissionUrl: "https://apply.awal.com/submit-form/",
    sourceUrl: "https://apply.awal.com/submit-form/",
    sourceType: "automation_run_169_public_research",
    country: "United Kingdom / global selective independent-artist distribution, playlisting, radio promotion, sync and licensing route",
    language: "en",
    genres: ["music-distribution", "selective-application", "independent-artists", "global-release-planning", "worldwide-playlisting", "radio-promotion", "sync-licensing", "digital-distribution", "application-form", "terms-boundary", "manual-review"],
    submissionMethod: "official-awal-selective-submit-your-music-distribution-application-route",
    feeRequired: false,
    feeAmount: "No upfront submission fee was observed; AWAL application and distribution terms include a selective acceptance process, revenue-share/accounting terms and legal obligations that require owner review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because AWAL's official Submit Your Music workflow requires accepting distribution terms, application data, rights warranties, metadata, commercial-quality recordings, AI/content declarations, payment/accounting terms and selective acceptance before any upload or product-uploader use.",
    notes: "Public research verified AWAL's official site, Submit Your Music link, global artist services, active 2026 artist-news context, application terms, Product Uploader language, worldwide digital distribution scope, 85% distribution-share clause and rights/warranty obligations. No application was accepted, no form was submitted, no account was created and no protected contact was decoded."
  },
  {
    name: "Symphonic Starter Paid Distribution and Release Campaign Builder Route",
    websiteUrl: "https://symphonic.com/",
    submissionUrl: "https://symphonic.com/starter/",
    sourceUrl: "https://symphonic.com/starter/",
    sourceType: "automation_run_169_public_research",
    country: "United States / global independent music distribution and promotion platform with Starter sign-up route",
    language: "en",
    genres: ["music-distribution", "paid-distribution", "independent-artists", "spotify", "apple-music", "tiktok", "beatport", "youtube", "release-campaign-builder", "identity-verification", "login-boundary", "manual-review"],
    submissionMethod: "official-symphonic-starter-paid-distribution-release-campaign-builder-route",
    feeRequired: true,
    feeAmount: "Symphonic Starter public page lists $29.99 per year for emerging artists, with identity verification, age and partner-approval conditions requiring manual review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Symphonic Starter involves paid sign-up, identity verification, age confirmation, one-primary-artist limits, release metadata, platform delivery, partner approvals, rights ownership, collaborator splits and campaign-builder choices.",
    notes: "Public research verified Symphonic's official distribution site, Starter plan, 200+ service-provider delivery, Spotify/Apple/TikTok/Beatport context, human support, royalty-split/payment tooling, release-campaign builder and 2026 active site context. No account was created, no identity verification was initiated, no payment was started and no release was uploaded."
  },
  {
    name: "EmuBands One-Time Fee Premium Dashboard Distribution Route",
    websiteUrl: "https://www.emubands.com/",
    submissionUrl: "https://dashboard.emubands.com/",
    sourceUrl: "https://www.emubands.com/",
    sourceType: "automation_run_169_public_research",
    country: "United Kingdom / global digital music distribution service with dashboard sign-up, one-time release fees and Premium option",
    language: "en",
    genres: ["music-distribution", "paid-distribution", "dashboard-upload", "spotify", "apple-music", "amazon-music", "premium-plan", "one-time-release-fee", "royalty-access", "login-boundary", "manual-review"],
    submissionMethod: "official-emubands-one-time-fee-premium-dashboard-distribution-route",
    feeRequired: true,
    feeAmount: "EmuBands states low-cost distribution with either a one-time setup fee per release or Premium unlimited distribution; pricing and release choices require manual owner review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because EmuBands uses dashboard sign-up/login and paid release or Premium plan choices, plus DSP selection, metadata, copyright ownership, release permanence, payout settings and optional add-on decisions.",
    notes: "Public research verified EmuBands' official homepage, dashboard sign-up/login, low-cost distribution, one-time-fee/Premium model, 100% royalties language, major DSP coverage, 2005 operating history and April 2026 latest-news activity. No dashboard session was entered, no account was created, no payment was started and no release was uploaded."
  },
  {
    name: "Record Union Paid Dashboard Distribution and Pitch Priority Route",
    websiteUrl: "https://www.recordunion.com/",
    submissionUrl: "https://www.recordunion.com/pricing/",
    sourceUrl: "https://www.recordunion.com/",
    sourceType: "automation_run_169_public_research",
    country: "Sweden / global dashboard-based digital distribution service with smart links, EPK, royalty splits and optional pitch priority",
    language: "en",
    genres: ["music-distribution", "paid-distribution", "spotify", "apple-music", "tiktok", "beatport", "soundcloud", "electronic-press-kit", "pitch-priority", "royalty-splits", "login-boundary", "manual-review"],
    submissionMethod: "official-record-union-paid-dashboard-distribution-pitch-priority-route",
    feeRequired: true,
    feeAmount: "Record Union public pricing lists annual release pricing, optional UPC fee and professional upgrades such as Pitch Priority; exact release plan requires manual selection.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Record Union requires dashboard release setup, paid plan selection, UPC/upgrade decisions, platform targeting, label/copyright line choices, royalty splits, smart links, EPK setup and playlist-pitch upgrade review.",
    notes: "Public research verified Record Union's official site, upload-to-global-services route, 20+ global service coverage, Spotify/Apple/TikTok/Beatport/SoundCloud context, pay-nothing-until-release language, pricing tiers, optional UPC and Pitch Priority upgrade. No account was created, no release dashboard was entered and no payment or upgrade was initiated."
  },
  {
    name: "iMusician Paid Distribution Editorial Playlist and Curated Playlist Submission Route",
    websiteUrl: "https://imusician.pro/",
    submissionUrl: "https://imusician.pro/en/resources/playlists",
    sourceUrl: "https://imusician.pro/",
    sourceType: "automation_run_169_public_research",
    country: "Switzerland / global digital distribution, artist tools, editorial playlist pitching and curated playlist submission platform",
    language: "en",
    genres: ["music-distribution", "paid-distribution", "editorial-playlist-pitching", "spotify-playlists", "electronic", "drum-and-bass", "breakbeat", "bass", "techno", "artist-hub", "login-boundary", "manual-review"],
    submissionMethod: "official-imusician-paid-distribution-editorial-curated-playlist-submission-route",
    feeRequired: true,
    feeAmount: "iMusician lists pay-per-release and subscription plans, including Starter/Rockstar/Amplify options; playlist and release submission choices require manual owner review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because iMusician requires auth/session handling for release starts, paid plan selection, playlist-pitch eligibility, metadata, ownership, commission/subscription choices, genre targeting and curated playlist fit for MarcsMusic tracks.",
    notes: "Public research verified iMusician's official site, sign-up/login boundary, 200+ platform reach, forever-online distribution, ownership language, pay-per-release/subscription pricing, editorial playlist pitching and curated playlist pages including electronic, drum & bass, breakbeat, bass and techno routes. No account was created, no login was used, no track was submitted and no payment was started."
  }
];
