import type { PlatformInput } from '../models/types.js';

export const run108SeedPlatforms: PlatformInput[] = [
  {
    name: "Music Connection New Music Critiques Free Review Form Route",
    websiteUrl: "https://www.musicconnection.com/",
    submissionUrl: "https://www.musicconnection.com/reviews/new-music-critiques/",
    sourceUrl: "https://www.musicconnection.com/reviews/new-music-critiques/",
    sourceType: "automation_run_108_public_research",
    country: "United States / global artist critique and music-industry magazine",
    language: "en",
    genres: ["music-connection", "new-music-critiques", "artist-review", "music-magazine", "industry-press", "electronic", "dance", "world", "reggae", "dub", "independent-artists", "public-form", "javascript-form", "free-first", "manual-review"],
    submissionMethod: "official-music-connection-new-music-critiques-free-review-form-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Music Connection exposes a free New Music Critiques submission form that requires JavaScript, artist contact details, style, seeking category, website and at least three streamable songs before any submission can be considered.",
    notes: "Public research confirmed Music Connection is active in July 2026 with current posts and a New Music Critiques page. The page says artists can sign up for a chance to be reviewed, says the route is always free, shows a JavaScript form boundary and lists required fields. No form was submitted, no email was sent and no JavaScript/session control was bypassed."
  },
  {
    name: "SoundClick Artist and Beat Producer Upload Route",
    websiteUrl: "https://www.soundclick.com/",
    submissionUrl: "https://www.soundclick.com/",
    sourceUrl: "https://www.soundclick.com/",
    sourceType: "automation_run_108_public_research",
    country: "United States / global independent music community and beat marketplace",
    language: "en",
    genres: ["soundclick", "independent-music", "artist-upload", "beat-producers", "electronic", "world", "reggae", "latin", "hip-hop", "rnb", "dance", "charts", "artist-page", "login-required", "freemium-manual", "manual-review"],
    submissionMethod: "official-soundclick-artist-upload-and-community-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because SoundClick requires account handling for artist upload, profile configuration, rights and licensing choices, download or sale settings, page branding and optional promotional tools.",
    notes: "Public research confirmed SoundClick is active in 2026. Its official site invites artists to join free, says artists and beat producers can upload unlimited songs or beats with no storage limits, sell beats and songs, use charts and artist pages, and sign in or sign up. No account was created, no upload was attempted, no licensing or sales settings were changed and no payment flow was opened."
  },
  {
    name: "BandLab Creator Publishing and Distribution Route",
    websiteUrl: "https://www.bandlab.com/",
    submissionUrl: "https://www.bandlab.com/distribution",
    sourceUrl: "https://www.bandlab.com/distribution",
    sourceType: "automation_run_108_public_research",
    country: "Singapore / global creator platform and distribution workflow",
    language: "en",
    genres: ["bandlab", "creator-platform", "social-music", "music-hosting", "distribution", "artist-upload", "electronic", "pop", "world", "reggae", "collaboration", "account-required", "freemium-manual", "manual-review"],
    submissionMethod: "official-bandlab-creator-publishing-and-distribution-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because BandLab involves account/session handling, creative-rights review, publishing or distribution settings, release metadata, store or DSP choices and a paid-membership distribution boundary that must not be crossed automatically.",
    notes: "Public research confirmed BandLab is active in 2026 as a music creation, sharing and distribution platform. The route is freemium: free creator and social publishing features exist, while secondary trade coverage states BandLab Distribution is available through paid Membership and the public site is a JavaScript application. No account was created, no release was configured, no files were uploaded, no distribution route was activated and no paid membership path was opened."
  },
  {
    name: "Radiooooo Curated Music Upload and Global Map Submission Route",
    websiteUrl: "https://app.radiooooo.com/",
    submissionUrl: "https://app.radiooooo.com/",
    sourceUrl: "https://app.radiooooo.com/",
    sourceType: "automation_run_108_public_research",
    country: "France / global curated music discovery map",
    language: "en/fr",
    genres: ["radiooooo", "music-discovery", "curated-upload", "global-map", "world-music", "electronic", "dub", "reggae", "afrobeat", "disco", "historical-music", "account-required", "paid-manual-only", "manual-review"],
    submissionMethod: "official-radiooooo-curated-upload-and-review-route",
    feeRequired: true,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Radiooooo uploads are curated, app/session based and connected to a free-trial/subscription boundary; rights, country/decade metadata and suitability for the map must be reviewed manually.",
    notes: "Public research confirmed Radiooooo is a Paris-based music discovery app where users can upload songs or music tracks that are curated by DJs and producers before appearing on an interactive global map. The same source notes a free trial followed by subscription. No account was created, no upload was attempted, no curator workflow was triggered and no subscription or payment path was opened."
  },
  {
    name: "Audius Artist Upload and Open Audio Streaming Route",
    websiteUrl: "https://audius.co/",
    submissionUrl: "https://audius.co/",
    sourceUrl: "https://audius.co/",
    sourceType: "automation_run_108_public_research",
    country: "United States / global decentralized music streaming platform",
    language: "en",
    genres: ["audius", "open-audio", "decentralized-streaming", "artist-upload", "electronic", "dance", "bass-music", "world", "reggae", "fan-discovery", "account-required", "javascript-app", "free-first", "manual-review"],
    submissionMethod: "official-audius-artist-upload-and-open-audio-streaming-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Audius is an app/session-based artist upload route involving account handling, rights and metadata review, token/monetization context and JavaScript boundaries.",
    notes: "Public research confirmed Audius is active in 2026 through the Open Audio Foundation/Audius site and a JavaScript Audius Music app. Independent reporting describes Audius as a platform with artists posting content and earning AUDIO tokens, with a large artist and track base. No account was created, no upload was attempted, no wallet/token action was taken and no JavaScript/session boundary was bypassed."
  }
];