import type { PlatformInput } from '../models/types.js';

export const run193BaseSeedPlatforms: PlatformInput[] = [
  {
    name: "DistroKid Unlimited DSP Upload Distribution Route",
    websiteUrl: "https://distrokid.com/",
    submissionUrl: "https://distrokid.com/",
    sourceUrl: "https://distrokid.com/",
    sourceType: "automation_run_193_public_research",
    country: "United States / global independent artist DSP distribution upload route",
    language: "en",
    genres: ["digital-distribution", "dsp-upload", "spotify", "apple-music", "youtube-music", "electronic", "world", "reggae", "independent", "manual-review"],
    submissionMethod: "official-distrokid-paid-account-dsp-upload-distribution-route",
    feeRequired: true,
    feeAmount: "Paid/manual route; public source review confirms DistroKid is an active independent digital distribution service using annual subscription access for unlimited uploads, rights/royalty tools and DSP delivery.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because release setup would involve account access, subscription/payment, audio/artwork upload, songwriter/rights metadata, explicit-content flags, cover-song handling, royalty splits, AI/authorship disclosure and platform terms. No account, payment or upload action may be automated.",
    notes: "DistroKid is a global independent artist distribution route to DSPs and related music-video/label-discovery tools. It is queued only as a manual release/distribution option for MarcsMusic, not as an outreach email route. No login, payment, upload, release configuration, deliverability probe or anti-bot handling was performed."
  },
  {
    name: "TuneCore Worldwide DSP Beatport Publishing Distribution Route",
    websiteUrl: "https://www.tunecore.com/",
    submissionUrl: "https://www.tunecore.com/",
    sourceUrl: "https://www.tunecore.com/",
    sourceType: "automation_run_193_public_research",
    country: "United States / Believe-owned global DSP, Beatport and publishing administration distribution route",
    language: "en",
    genres: ["digital-distribution", "publishing-administration", "beatport", "electronic", "dance", "spotify", "apple-music", "tidal", "independent", "manual-review"],
    submissionMethod: "official-tunecore-account-dsp-beatport-publishing-distribution-route",
    feeRequired: true,
    feeAmount: "Paid/manual route; public source review confirms TuneCore distributes to DSPs including Spotify, Apple Music, Tidal and Beatport and offers music publishing administration, with account/payment boundaries requiring manual review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because TuneCore release setup would involve account access, pricing/subscription/product selection, DSP store choices, Beatport/dance metadata fit, publishing administration decisions, rights/ownership, explicit lyrics, royalty splits and AI/authorship disclosure. No upload or payment may be automated.",
    notes: "TuneCore is queued as a legitimate global distribution and publishing-administration route, especially relevant for electronic releases because Beatport distribution is part of the public platform context. No account, payment, release setup, file transfer, contact form or deliverability check was performed."
  },
  {
    name: "CD Baby Digital Distribution Publishing Administration Route",
    websiteUrl: "https://cdbaby.com/",
    submissionUrl: "https://cdbaby.com/",
    sourceUrl: "https://cdbaby.com/",
    sourceType: "automation_run_193_public_research",
    country: "United States / global independent digital distribution and publishing-administration route",
    language: "en",
    genres: ["digital-distribution", "publishing-administration", "independent", "spotify", "apple-music", "amazon-music", "youtube", "global", "manual-review"],
    submissionMethod: "official-cd-baby-account-digital-distribution-publishing-route",
    feeRequired: true,
    feeAmount: "Paid/manual route; public source review confirms CD Baby is a worldwide independent digital distributor and music publisher, with physical distribution discontinued in favor of digital distribution since June 2023.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because CD Baby setup would involve account access, release/product fee selection, digital distribution choices, publishing administration decisions, songwriter and master-rights confirmation, metadata, cover art, explicit/AI disclosure and royalty/payment setup. No account, payment or upload may be automated.",
    notes: "CD Baby is queued as a legitimate independent digital distribution and publishing administration route, not as an email outreach route. Public sources indicate the historical physical-service side has ended, so route handling should be digital-only unless CD Baby publishes contrary current guidance. No account, upload, payment, form submission or deliverability probe was performed."
  },
  {
    name: "RouteNote Free Premium DSP Distribution Publishing Route",
    websiteUrl: "https://www.routenote.com/",
    submissionUrl: "https://www.routenote.com/",
    sourceUrl: "https://www.routenote.com/",
    sourceType: "automation_run_193_public_research",
    country: "United Kingdom / worldwide free and premium DSP distribution route",
    language: "en",
    genres: ["digital-distribution", "free-distribution", "premium-distribution", "publishing", "licensing", "spotify", "itunes", "amazon-music", "independent", "manual-review"],
    submissionMethod: "official-routenote-free-premium-account-dsp-distribution-route",
    feeRequired: false,
    feeAmount: "Free-first/freemium manual route; public source review confirms RouteNote offers free distribution with 85% royalty share and paid distribution with 100% royalty share across many digital stores and streaming platforms.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because RouteNote release setup would involve account access, free-vs-premium royalty model selection, DSP delivery choices, rights/licensing, publishing options, metadata, explicit-content notes, AI/authorship disclosure and payout configuration. No account, upload or payment may be automated.",
    notes: "RouteNote is queued as a free-first global distribution option for MarcsMusic because public sources describe both free and paid distribution models. Manual review must confirm the current plan terms before release. No login, upload, payment, form submission, protected contact decoding or deliverability probe was performed."
  },
  {
    name: "Amuse Independent Artist Self Release Licensing Upload Route",
    websiteUrl: "https://www.amuse.io/",
    submissionUrl: "https://www.amuse.io/",
    sourceUrl: "https://www.amuse.io/",
    sourceType: "automation_run_193_public_research",
    country: "Sweden / global independent artist self-release distribution and licensing route",
    language: "en",
    genres: ["digital-distribution", "self-release", "licensing", "artist-services", "spotify", "apple-music", "electronic", "independent", "royalty-insights", "manual-review"],
    submissionMethod: "official-amuse-account-self-release-distribution-licensing-route",
    feeRequired: true,
    feeAmount: "Freemium/subscription manual route; public source review confirms Amuse has self-service distribution tiers, artist services, licensing and DSP delivery, with current pricing/plan terms requiring manual confirmation before use.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Amuse release setup would involve account access, subscription/plan selection, DSP distribution, potential licensing or artist-services terms, rights ownership, metadata, cover art, explicit and AI/authorship disclosure, royalty/payout configuration and release timing. No account, payment or upload may be automated.",
    notes: "Amuse is queued as a legitimate global independent artist distribution and licensing route. Fresh July 6, 2026 public coverage describes Amuse as an independent artist/label partner where artists can self-release and upload songs, while public background sources describe subscription distribution tiers. No login, upload, payment, application, message or deliverability probe was performed."
  }
];
