import type { PlatformInput } from '../models/types.js';
import { run126SeedPlatforms } from './run126PlatformSeeds.js';

export const run125SeedPlatforms: PlatformInput[] = [
  {
    name: "Horus Music Distribution Playlist Radio Promotion and Send Us Your Music Route",
    websiteUrl: "https://www.horusmusic.global/",
    submissionUrl: "https://www.horusmusic.global/",
    sourceUrl: "https://www.horusmusic.global/",
    sourceType: "automation_run_125_public_research",
    country: "Global / UK-based independent artist distribution publishing playlist radio promotion and marketing route",
    language: "en",
    genres: ["horus-music", "music-distribution", "playlist-pitching", "global-radio-promotion", "digital-pr", "sync-licensing", "smartlinks", "free-signup", "payment", "login", "manual-review"],
    submissionMethod: "official-horus-music-distribution-playlist-radio-promotion-send-us-your-music-route",
    feeRequired: true,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Horus Music uses sign-up/login, release setup, subscription or plan choices, Send Us Your Music intake, playlist/radio/PR service choices, publishing and sync options, rights metadata and optional regional services. Release ownership, UPC/ISRC use, campaign selection, budget and any Microsoft Forms or account-session fields must remain owner-reviewed.",
    notes: "Official public research confirmed Horus Music is active in 2026, exposes Sign Up, Login, Get Started, Sign Up For Free and Send Us Your Music routes, lists unlimited distribution from £20/year, publishing from £3/month, playlist pitching, UK radio plugging, global radio promotion, digital PR, ad campaigns, EPK creation and recent 2026 blog activity. No account was created, no Microsoft form was submitted, no release was configured and no payment was initiated."
  },
  {
    name: "Symphonic Distribution Starter Partner Marketing Sync and Playlist Pitching Route",
    websiteUrl: "https://symphonic.com/",
    submissionUrl: "https://symphonic.com/",
    sourceUrl: "https://symphonic.com/",
    sourceType: "automation_run_125_public_research",
    country: "Global / independent artist label distribution marketing sync playlist pitching and rights management route",
    language: "en",
    genres: ["symphonic", "digital-distribution", "music-promotion", "rights-management", "sync-licensing", "playlist-pitching", "release-campaign-builder", "paid", "login", "manual-review"],
    submissionMethod: "official-symphonic-distribution-starter-partner-marketing-sync-playlist-pitching-route",
    feeRequired: true,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Symphonic routes creators through Join/Login, Starter or Partner plan selection, release setup, DSP and playlist pitching, royalty splits, rights management, marketing, sync and possible custom approval workflows. Plan selection, payment approval, release metadata, collaborator splits and pitch eligibility must remain owner-reviewed.",
    notes: "Official public research confirmed Symphonic is active in 2026, offers digital music distribution, video distribution, royalty collection, music promotion, support, Release Campaign Builder, DSP playlist pitching, pricing, Login and Join routes. No account was opened, no plan was selected, no release was uploaded, no collaborator split was configured and no payment was made."
  },
  {
    name: "AWAL Selective Submit Your Music Distribution Radio Playlist Sync Route",
    websiteUrl: "https://www.awal.com/",
    submissionUrl: "https://apply.awal.com/",
    sourceUrl: "https://www.awal.com/",
    sourceType: "automation_run_125_public_research",
    country: "Global / selective independent artist distribution playlisting radio promotion sync and label-services application route",
    language: "en",
    genres: ["awal", "submit-your-music", "selective-distribution", "radio-promotion", "worldwide-playlisting", "sync-licensing", "artist-marketing", "funding", "application", "login", "manual-review"],
    submissionMethod: "official-awal-selective-submit-your-music-distribution-radio-playlist-sync-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because AWAL is a selective application route with Submit Your Music and login boundaries, artist qualification review, ownership/control terms, distribution, playlisting, radio promotion, sync, funding and marketing implications. The application package, streaming links, artist metrics, rights status and commercial terms must remain owner-reviewed.",
    notes: "Official public research confirmed AWAL is active in 2026, exposes Submit Your Music, Join Us and Login routes, says it supports independent artists globally, and lists global release planning, digital strategy, worldwide playlisting, artist marketing, funding, creative support, radio promotion, sync and licensing, and digital/physical distribution. No application was opened beyond public discovery, no account was used and no music was submitted."
  },
  {
    name: "Too Lost Distribution Priority Pitch Publishing Smart Link and Catalog Protection Route",
    websiteUrl: "https://toolost.com/",
    submissionUrl: "https://toolost.com/",
    sourceUrl: "https://toolost.com/",
    sourceType: "automation_run_125_public_research",
    country: "Global / artist label distribution publishing playlist pitch smart link and catalog protection route",
    language: "en",
    genres: ["too-lost", "music-distribution", "priority-pitch", "publishing-administration", "smart-release-links", "content-id", "audio-recognition", "profile-defender", "catalog-management", "pricing", "login", "manual-review"],
    submissionMethod: "official-too-lost-distribution-priority-pitch-publishing-smart-link-catalog-protection-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Too Lost exposes Get Started/Login/Dashboard/Create Release routes, pricing, release creation, priority pitch, publishing, smart links, Content ID, copyright registration, fan email and catalog protection features. Rights, territory, store delivery, publisher data, profile access, campaign targets, pricing and support/session boundaries require owner review.",
    notes: "Official public research confirmed Too Lost is active in 2026, presents product suites for delivery, analytics, marketing, compliance, financing and catalog management, lists distribution to 450+ platforms, Priority Pitch, smart release links, publishing administration, Content ID, physical distribution and contact/support routes. No login was used, no release was created, no priority pitch was submitted and no pricing route was accepted."
  },
  {
    name: "Record Union Distribution Smart Link EPK Pitch Priority and Release Upload Route",
    websiteUrl: "https://www.recordunion.com/",
    submissionUrl: "https://www.recordunion.com/",
    sourceUrl: "https://www.recordunion.com/",
    sourceType: "automation_run_125_public_research",
    country: "Global / independent artist distribution smart-link EPK release upload and playlist pitch priority route",
    language: "en",
    genres: ["record-union", "music-distribution", "spotify", "apple-music", "tiktok", "smart-links", "epk", "pitch-priority", "youtube-content-id", "paid-release", "login", "manual-review"],
    submissionMethod: "official-record-union-distribution-smart-link-epk-pitch-priority-release-upload-route",
    feeRequired: true,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Record Union uses Get Started/Start Releasing routes, release upload, release-date selection, service-tier choice, paid yearly release plans, UPC decisions, Pitch Priority, Spotify pre-save, YouTube Content ID, EPK publishing and collaborator splits. Release assets, metadata, payment, ownership, copyright and upgrade choices require owner review.",
    notes: "Official public research confirmed Record Union is active in 2026, lets artists join free before release, upload music to Spotify and 20+ global music services, publish an EPK, use smart links, select release dates, access Spotify for Artists and choose paid Top Dog or World Domination yearly plans. No account was created, no release was uploaded, no EPK was published and no payment was made."
  },
  ...run126SeedPlatforms
];
