import type { PlatformInput } from '../models/types.js';
import { run132SeedPlatforms } from './run132PlatformSeeds.js';

export const run131SeedPlatforms: PlatformInput[] = [
  {
    name: "Groover Paid Curator Radio Label DJ Music Promotion Submission Route",
    websiteUrl: "https://groover.co/en/",
    submissionUrl: "https://groover.co/en/",
    sourceUrl: "https://groover.co/en/lp/pricing/",
    sourceType: "automation_run_131_public_research",
    country: "Global / France-US music promotion marketplace for curators, playlists, radio, labels, managers, DJs and sync-adjacent pros",
    language: "en",
    genres: ["groover", "music-promotion", "playlist-curators", "radio", "labels", "djs", "press", "all-genres", "paid-credits", "login-required", "manual-review"],
    submissionMethod: "official-groover-paid-curator-radio-label-dj-music-promotion-submission-route",
    feeRequired: true,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Groover requires account/session control, track or link selection, curator/pro targeting, paid Grooviz credit purchase, pitch text, genre filters and owner decisions about radio, playlist, label, DJ or manager targeting.",
    notes: "Official public research confirmed Groover is active in 2026, supports all genres, lets artists send music to 3,000+ curators and pros, includes radio, playlists, press, labels and DJs, and prices submissions through Grooviz credits. No account was created, no login was used, no track was uploaded, no curator was selected, no pitch was sent and no payment was initiated."
  },
  {
    name: "Playlist Push Spotify Playlist and TikTok Paid Campaign Submission Route",
    websiteUrl: "https://playlistpush.com/",
    submissionUrl: "https://app.playlistpush.com/",
    sourceUrl: "https://playlistpush.com/pricing",
    sourceType: "automation_run_131_public_research",
    country: "Global / US music promotion platform for Spotify playlist and TikTok creator campaigns",
    language: "en",
    genres: ["playlist-push", "spotify-playlists", "tiktok-creators", "music-promotion", "playlist-curators", "paid-campaign", "app-session-boundary", "login-required", "manual-review"],
    submissionMethod: "official-playlist-push-spotify-playlist-tiktok-paid-campaign-submission-route",
    feeRequired: true,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Playlist Push routes artist submissions through app account creation/sign-in, campaign budgeting, Spotify or TikTok campaign choice, genre targeting, curator/creator network selection, payment and no-guarantee terms.",
    notes: "Official public research confirmed Playlist Push is active, offers artist services for Spotify playlist and TikTok promotion, exposes app sign-up/sign-in routes, describes vetted independent playlist curators and a minimum Spotify campaign budget. No account was created, no login was used, no campaign was configured, no curator or creator was selected, no song was submitted and no payment was initiated."
  },
  {
    name: "TAXI Independent A&R Listings Sync Label Publisher Submission Route",
    websiteUrl: "https://www.taxi.com/",
    submissionUrl: "https://www.taxi.com/industry",
    sourceUrl: "https://www.taxi.com/industry",
    sourceType: "automation_run_131_public_research",
    country: "Global / US independent A&R listings route for labels, publishers, supervisors, music libraries, ads and games",
    language: "en",
    genres: ["taxi", "independent-a-r", "sync-licensing", "record-labels", "publishers", "music-supervisors", "production-music", "industry-listings", "membership-required", "manual-review"],
    submissionMethod: "official-taxi-independent-ar-listings-sync-label-publisher-submission-route",
    feeRequired: true,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because TAXI submissions require membership/login, opportunity-by-opportunity eligibility review, genre and deadline fit, master/copyright ownership checks, PRO affiliation where required, AI-use restrictions, lyrics/bio/photo package choices and deal-term review.",
    notes: "Official public research confirmed TAXI is active with 2026 industry listings, public Join/Renew/Member Login routes, Submit Music links and opportunities across labels, publishers, supervisors, music libraries, ads and video games. No membership was purchased, no login was used, no listing was selected, no music was submitted and no payment was initiated."
  },
  {
    name: "Soundplate Free Spotify Deezer Playlist Submission Route",
    websiteUrl: "https://www.soundplate.com/",
    submissionUrl: "https://play.soundplate.com/",
    sourceUrl: "https://play.soundplate.com/",
    sourceType: "automation_run_131_public_research",
    country: "Global / UK free playlist-submission system for Spotify and Deezer independent curator routes",
    language: "en",
    genres: ["soundplate", "spotify-playlists", "deezer-playlists", "playlist-submission", "free-service", "independent-curators", "house", "electronic", "reggae", "dancehall", "manual-review"],
    submissionMethod: "official-soundplate-free-spotify-deezer-playlist-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Soundplate requires playlist-by-playlist relevance selection, track/link entry, curator-specific form handling, anti-spam compliance and release-fit review before any submission is made.",
    notes: "Official public research confirmed Soundplate operates a public Submit Music route for Spotify and Deezer playlists, describes the service as free, lists multiple live playlist categories relevant to electronic, dance, reggae/dancehall and adjacent MarcsMusic styles, and warns artists not to spam irrelevant playlists. No playlist was selected, no form was submitted, no track link was delivered and no account/payment action was taken."
  },
  {
    name: "Songtradr Sync Licensing Marketplace Upload and Rights Submission Route",
    websiteUrl: "https://www.songtradr.com/",
    submissionUrl: "https://www.songtradr.com/",
    sourceUrl: "https://www.songtradr.com/",
    sourceType: "automation_run_131_public_research",
    country: "Global / US B2B music licensing marketplace and app upload route for artists, labels and rights holders",
    language: "en",
    genres: ["songtradr", "sync-licensing", "music-licensing", "marketplace", "artist-upload", "rights-metadata", "set-licensing-fees", "javascript-app-boundary", "login-required", "manual-review"],
    submissionMethod: "official-songtradr-sync-licensing-marketplace-upload-rights-submission-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Songtradr is an app-based music licensing marketplace requiring JavaScript/session control, account access, rights ownership verification, upload decisions, territory/licensing-fee settings and catalog metadata review.",
    notes: "Official public research confirmed the public Songtradr route renders behind a JavaScript app boundary, while public reference research describes Songtradr as a B2B music licensing platform where artists can upload music and set licensing fees. No JavaScript app workflow was handled, no account was created, no login was used, no music was uploaded and no licensing terms were set."
  },
  ...run132SeedPlatforms
];
