import type { PlatformInput } from '../models/types.js';

export const run142SeedPlatforms: PlatformInput[] = [
  {
    name: "XRAY FM Music Submission Guidelines Email Route",
    websiteUrl: "https://xray.fm/",
    submissionUrl: "https://xray.fm/contact",
    sourceUrl: "https://xray.fm/contact",
    sourceType: "automation_run_142_public_research",
    country: "United States / Portland community radio, KXRY FM and online music-submission contact route",
    language: "en",
    genres: ["community-radio", "freeform-radio", "independent-music", "music-submissions", "email-route", "radio-airplay", "manual-review"],
    submissionMethod: "official-public-music-submissions-email-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because XRAY directs music submissions to a public email route plus guidelines; pitch copy, release metadata, clean/explicit notes and link or package selection must remain owner-controlled.",
    notes: "Official XRAY Contact Us page lists Music Submissions and directs senders to submissions@xray.fm with music submission guidelines. No email was sent, no contact was guessed and no deliverability probing was performed."
  },
  {
    name: "Radio Milwaukee 88Nine WAV Radio Edit Music Submission Route",
    websiteUrl: "https://radiomilwaukee.org/",
    submissionUrl: "https://radiomilwaukee.org/music-submission",
    sourceUrl: "https://radiomilwaukee.org/music-submission",
    sourceType: "automation_run_142_public_research",
    country: "United States / Milwaukee public radio, 88Nine, HYFIN and 414Music.fm music discovery route",
    language: "en",
    genres: ["public-radio", "adult-album-alternative", "local-music", "new-music", "wav-required", "radio-edits", "no-physical-media", "manual-review"],
    submissionMethod: "official-radio-milwaukee-music-submission-page",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Radio Milwaukee asks for WAV-quality mixed/mastered radio edits and a contextual information document; track choice, lyrics, show context and contact package require owner review.",
    notes: "Official Radio Milwaukee Music Submission page states WAV is preferred, tracks should be mixed/mastered, radio edits are required, physical media are not accepted, and an informational document should include bio, lyrics, album/live-show information and links. No form was submitted and no file or link was delivered."
  },
  {
    name: "WMNF Music Department Upload Form and Music Relations Email Route",
    websiteUrl: "https://www.wmnf.org/",
    submissionUrl: "https://www.wmnf.org/submit-your-music-to-wmnf/",
    sourceUrl: "https://www.wmnf.org/submit-your-music-to-wmnf/",
    sourceType: "automation_run_142_public_research",
    country: "United States / Tampa community radio, Music Department form-upload and email route",
    language: "en",
    genres: ["community-radio", "eclectic-music", "music-department", "upload-form", "mp3", "wav", "flac", "aiff", "musicrelations-email", "manual-review"],
    submissionMethod: "official-wmnf-submit-music-upload-form-and-email-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WMNF exposes an upload form with artist/contact/location fields and audio file uploads; file choice, form copy, local/context answers and optional email follow-up require owner control.",
    notes: "Official WMNF Submit Your Music page states music emails go to musicrelations@wmnf.org and exposes a form with artist/band, social/website, location, Tampa Bay roots/show context, required file upload and contact email fields. No form was submitted and no audio file was uploaded."
  },
  {
    name: "WYEP Pittsburgh Area Email and Hard-Copy Airplay Submission Route",
    websiteUrl: "https://www.wyep.org/",
    submissionUrl: "https://www.wyep.org/wyep-pittsburgh-area-music-submissions",
    sourceUrl: "https://www.wyep.org/wyep-pittsburgh-area-music-submissions",
    sourceType: "automation_run_142_public_research",
    country: "United States / Pittsburgh and Western Pennsylvania public-radio local music airplay route",
    language: "en",
    genres: ["public-radio", "adult-album-alternative", "local-music", "pittsburgh", "western-pennsylvania", "email-route", "physical-mail-route", "fcc-clean", "manual-review"],
    submissionMethod: "official-wyep-local-music-email-and-hard-copy-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WYEP is local/regional-fit dependent and allows email links or hard-copy mail; eligibility, FCC-clean edits, best-track selection, bio and physical-mail choice require review.",
    notes: "Official WYEP Pittsburgh Area Music Submissions page accepts music links by email to localmusic@wyep.org or hard copy by mail, asks for contact information, hometown, bio and suggested tracks, and notes local/FCC-clean constraints. No email was sent and no physical package was prepared."
  },
  {
    name: "STMPD RCRDS Official Demo Submission Route",
    websiteUrl: "https://stmpdrcrds.com/",
    submissionUrl: "https://demo.stmpdrcrds.com/",
    sourceUrl: "https://stmpdrcrds.com/",
    sourceType: "automation_run_142_public_research",
    country: "Netherlands / Amsterdam global electronic label demo-submission route",
    language: "en",
    genres: ["electronic-music", "edm", "demo-submission", "record-label", "future-bass", "tech-house", "progressive-house", "app-session-boundary", "manual-review"],
    submissionMethod: "official-stmpd-rcrds-demo-submit-link",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because STMPD routes demos through an external demo app boundary; label fit, rights, demo version, metadata, terms and any session prompts require owner control.",
    notes: "Official STMPD RCRDS public page shows current 2026 release activity and links to demo.stmpdrcrds.com for demo submission. No demo app workflow was executed, no login was used and no file or link was delivered."
  }
];
