import type { PlatformInput } from '../models/types.js';

export const run106SeedPlatforms: PlatformInput[] = [
  {
    name: "EQ Music Blog New Music Tip and Promo Submission Route",
    websiteUrl: "https://eqmusicblog.com/",
    submissionUrl: "https://eqmusicblog.com/contact/",
    sourceUrl: "https://eqmusicblog.com/contact/",
    sourceType: "automation_run_106_public_research",
    country: "United Kingdom / global pop and electronic music blog",
    language: "en",
    genres: ["eq-music", "music-blog", "pop", "electronic-pop", "synthpop", "dance-pop", "new-music-tip", "editorial-consideration", "public-email", "physical-promo", "redacted-contact", "free-first", "manual-review"],
    submissionMethod: "official-eq-music-new-music-tip-and-promo-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because EQ Music asks for a streaming link, a compelling photo and a clear reason the music deserves coverage, while the fetched public email was redacted and physical promo handling must not be automated.",
    notes: "Public research confirmed EQ Music is active in 2026 with recent posts and a copyright footer, and its official Contact page invites hot new music tips for editorial consideration. The page asks for a streaming link, compelling photo and fit rationale, and also lists a physical music-promos address. The fetched email was redacted, so no protected contact was decoded or guessed. No email was sent, no physical promo was mailed and no SMTP/MX probing was performed."
  },
  {
    name: "Nialler9 Music Promo and Premiere Submission Route",
    websiteUrl: "https://nialler9.com/",
    submissionUrl: "https://nialler9.com/contact/",
    sourceUrl: "https://nialler9.com/contact/",
    sourceType: "automation_run_106_public_research",
    country: "Ireland / independent music publication and newsletter",
    language: "en",
    genres: ["nialler9", "irish-music-blog", "independent-music", "electronic", "alt-pop", "premiere", "track-stream", "album-link", "release-pitch", "public-email", "redacted-contact", "free-first", "manual-review"],
    submissionMethod: "official-nialler9-music-promo-and-premiere-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Nialler9 separates general, promo/premiere, Irish-artist and gig-listing routes, asks for advance timing and clean release assets, and the fetched email values were redacted rather than safely exposed.",
    notes: "Public research confirmed Nialler9 is active in 2026 with recent music posts and an official Contact page for sending music and gig listings. The page says to use music-specific emails for promos, track streams, premiere offers, album links and releases; it asks for a short, direct pitch, release date, links, bio, social links, hi-res photo/download assets and streaming links with download options, and discourages attachments and chase emails. The fetched email values were redacted, so no protected contact was decoded or guessed. No email was sent, no files or links were delivered and no SMTP/MX probing was performed."
  },
  {
    name: "LOUD WOMEN Reviews Editor and Radio Form Submission Route",
    websiteUrl: "https://loudwomen.org/",
    submissionUrl: "https://loudwomen.org/contact/",
    sourceUrl: "https://loudwomen.org/contact/",
    sourceType: "automation_run_106_public_research",
    country: "United Kingdom / international women-led DIY music zine, radio and promoter",
    language: "en",
    genres: ["loud-women", "women-led", "non-binary", "diy", "indie", "punk", "riot-grrrl", "electro", "radio-show", "review-route", "google-form", "public-email", "free-first", "manual-review"],
    submissionMethod: "official-loud-women-review-email-and-radio-form-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because LOUD WOMEN has separate review, radio-play, live-review and festival-application routes, including an external Google Form for radio consideration and public editor emails that require fit and eligibility review.",
    notes: "Public research confirmed LOUD WOMEN is active in 2026 with recent reviews, radio and festival posts. Its official Contact page tells musicians or PR representatives to send new music for site consideration to the Reviews Editor, use a specific external form for radio play, contact a Live Editor for live review coverage and use festival application links separately. No Google Form was opened or submitted, no email was sent, no files were uploaded and no SMTP/MX probing was performed."
  },
  {
    name: "Get In Her Ears Website and Soho Radio Pitch Submission Route",
    websiteUrl: "https://getinherears.com/",
    submissionUrl: "https://getinherears.com/contact-info-about-us/",
    sourceUrl: "https://getinherears.com/contact-info-about-us/",
    sourceType: "automation_run_106_public_research",
    country: "United Kingdom / women, non-binary and LGBTQIA+ new music platform",
    language: "en",
    genres: ["get-in-her-ears", "women", "non-binary", "lgbtqia", "new-music", "soho-radio", "website-reviews", "features", "indie", "alt-pop", "electronic", "experimental", "public-email", "free-first", "manual-review"],
    submissionMethod: "official-get-in-her-ears-website-and-soho-radio-pitch-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Get In Her Ears applies eligibility around women and marginalised genders, separates website review/feature and Soho Radio contacts, and requests a short bio, music link, promo image and socials.",
    notes: "Public research confirmed Get In Her Ears is active in 2026 with recent playlist, feature and Soho Radio posts. Its official Contact Info & About Us page says coverage is for women and marginalised genders in new music, including trans women, and asks pitches to include a short bio, a music link, a promo pic and social links, with individual editors listed for live queries, website reviews/features and Soho Radio submissions. No email was sent, no files or links were delivered and no SMTP/MX probing was performed."
  },
  {
    name: "musicOMH Album Feature and Review Pitch Submission Route",
    websiteUrl: "https://www.musicomh.com/",
    submissionUrl: "https://www.musicomh.com/contact-us",
    sourceUrl: "https://www.musicomh.com/contact-us",
    sourceType: "automation_run_106_public_research",
    country: "United Kingdom / global online music magazine",
    language: "en",
    genres: ["musicomh", "online-music-magazine", "album-review", "feature-pitch", "interview-pitch", "introducing", "spotlight", "downloads", "cd-on-request", "public-email", "free-first", "manual-review"],
    submissionMethod: "official-musicomh-album-feature-and-review-pitch-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because musicOMH does not currently cover tracks, EPs, videos or singles, mainly considers albums with a UK release date and prefers album-download URLs or CDs only after contacting for a postal address.",
    notes: "Public research confirmed musicOMH is active in 2026 with current reviews and features, and its official Contact Us page provides routes for features/interviews, album review alerts and live event coverage. The page says albums are reviewed ahead of UK release date, direct submissions are not usually considered, album download URLs should be included, CDs require contacting for a postal address, and tracks, EPs, videos and singles are not currently covered. No email was sent, no postal address was requested, no CD/package was sent and no SMTP/MX probing was performed."
  }
];
