import type { PlatformInput } from '../models/types.js';

export const run176BaseSeedPlatforms: PlatformInput[] = [
  {
    name: "KEXP Seattle Music Director Rotation Consideration Email Route",
    websiteUrl: "https://www.kexp.org/",
    submissionUrl: "https://www.kexp.org/contact/",
    sourceUrl: "https://www.kexp.org/contact/",
    sourceType: "automation_run_176_public_research",
    country: "United States / Seattle global online independent radio rotation-consideration route",
    language: "en",
    genres: ["independent-radio", "electronic", "global", "reggae", "hip-hop", "latin", "new-music", "music-director", "email-route", "manual-review"],
    submissionMethod: "official-kexp-music-director-rotation-consideration-email-route",
    feeRequired: false,
    feeAmount: "No submission fee observed; KEXP routes music for rotation consideration through its public Music Director and Music Department email route.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KEXP asks artists to email the Music Director and Music Department for rotation consideration; owner-approved pitch copy, release links, clean/radio edit status, rights and attachments/download-link policy must be reviewed before sending.",
    notes: "Public research verified KEXP official contact page, public Music Director/Music Department route, general contact routes, Getting Radio Airplay guidance and current July 2026 homepage activity with live sessions, events and podcast/content updates. No email was sent and no files or links were delivered."
  },
  {
    name: "KALX Berkeley Physical CD LP Music Director Airplay Submission Route",
    websiteUrl: "https://www.kalx.berkeley.edu/",
    submissionUrl: "https://www.kalx.berkeley.edu/about/contact/",
    sourceUrl: "https://www.kalx.berkeley.edu/about/contact/",
    sourceType: "automation_run_176_public_research",
    country: "United States / Berkeley freeform college radio physical-airplay route",
    language: "en",
    genres: ["college-radio", "freeform", "independent", "electronic", "experimental", "hip-hop", "world", "physical-review", "music-director", "manual-review"],
    submissionMethod: "official-kalx-physical-cd-lp-music-director-airplay-submission-route",
    feeRequired: false,
    feeAmount: "No submission fee observed; KALX currently accepts only physical professionally pressed CDs or LPs for airplay submission.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KALX explicitly rejects digital downloads, file transfers, Bandcamp/Spotify links, YouTube videos, CD-Rs and other digital music forms; physical package format, postage, one-sheet and routing require owner control.",
    notes: "Public research verified KALX official contact page, Music Directors contact, physical-only CD/LP submission policy, no-attachment email policy, mailing address and current July 2026 activity on the homepage. No email was sent and no physical package was prepared or mailed."
  },
  {
    name: "4ZZZ Brisbane Music Department Downloadable Library Submission Form Route",
    websiteUrl: "https://4zzz.org.au/",
    submissionUrl: "https://4zzz.org.au/music-submissions",
    sourceUrl: "https://4zzz.org.au/music-submissions",
    sourceType: "automation_run_176_public_research",
    country: "Australia / Brisbane community radio digital-library music department route",
    language: "en",
    genres: ["community-radio", "independent", "electronic", "bass", "world", "reggae", "hip-hop", "downloadable-music", "form-boundary", "manual-review"],
    submissionMethod: "official-4zzz-music-department-downloadable-library-submission-form-route",
    feeRequired: false,
    feeAmount: "No submission fee observed; 4ZZZ routes music through a public Music Submissions page and external submit-music form.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because 4ZZZ requires downloadable music and routes submission through an external form/app boundary; owner-approved download links, release metadata, rights and potential Album of the Week route selection must be reviewed before use.",
    notes: "Public research verified the official 4ZZZ Music Submissions page, Music Department review/library inclusion language, non-downloadable-stream rejection, Submit Your Music form link and Album of the Week side route. No external form workflow was entered and no music/download link was submitted."
  },
  {
    name: "WPRB Princeton Physical Priority Music Submissions Email Route",
    websiteUrl: "https://wprb.com/",
    submissionUrl: "https://wprb.com/music-submissions/",
    sourceUrl: "https://wprb.com/music-submissions/",
    sourceType: "automation_run_176_public_research",
    country: "United States / Princeton New Jersey freeform independent radio physical-priority route",
    language: "en",
    genres: ["freeform-radio", "independent", "electronic", "reggae", "world", "hip-hop", "experimental", "physical-priority", "music-director", "manual-review"],
    submissionMethod: "official-wprb-physical-priority-music-submissions-email-route",
    feeRequired: false,
    feeAmount: "No submission fee observed; WPRB accepts music submissions by physical formats and also provides a public music submissions email, while prioritizing physical submissions.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WPRB prioritizes CDs, CD-Rs, LPs, 12-inches, 10-inches and 7-inches; physical package selection, one-sheet, postage and optional email copy require owner approval.",
    notes: "Public research verified WPRB official Music Submissions page, music@wprb.com contact, Music Director postal route, physical format list, current playlist activity and 2026 site footer. No email was sent and no package was prepared or mailed."
  },
  {
    name: "RTRFM Perth Digital Download Link Music Team Form Route",
    websiteUrl: "https://rtrfm.com.au/",
    submissionUrl: "https://rtrfm.com.au/submit-your-music/",
    sourceUrl: "https://rtrfm.com.au/submit-your-music/",
    sourceType: "automation_run_176_public_research",
    country: "Australia / Perth alternative community radio digital and physical-side submission route",
    language: "en",
    genres: ["community-radio", "alternative", "electronic", "beats", "dance", "ambient", "independent", "download-link", "form-route", "manual-review"],
    submissionMethod: "official-rtrfm-digital-download-link-music-team-form-route",
    feeRequired: false,
    feeAmount: "No submission fee observed; RTRFM asks artists to use the public form or email details and requires downloadable WAV or high-quality MP3 links rather than email attachments.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because RTRFM's form asks for personal, artist, bio, social, gig, stream and free-download-link fields; owner-approved links, release timing, metadata, file permissions and physical side-route decisions must be reviewed before submitting.",
    notes: "Public research verified RTRFM official Submit Your Music page, Music Team consideration language, two-week advance release guidance, WAV/high-quality MP3 download-link recommendation, no-email-attachment rule, form fields, physical-copy side route and current July 2026 site activity. No form was submitted, no email was sent and no files or links were transferred."
  }
];
