import type { PlatformInput } from '../models/types.js';

export const run145SeedPlatforms: PlatformInput[] = [
  {
    name: "KUCI 88.9 FM Physical and Google Form New Release Airplay Submission Route",
    websiteUrl: "https://kuci.org/",
    submissionUrl: "https://kuci.org/submitting-music/",
    sourceUrl: "https://kuci.org/submitting-music/",
    sourceType: "automation_run_145_public_research",
    country: "United States / Irvine college radio physical and digital new-release airplay route",
    language: "en",
    genres: ["college-radio", "independent-radio", "new-release-form", "physical-submission", "cd", "vinyl", "wax-cylinder", "google-form-boundary", "manual-review"],
    submissionMethod: "official-kuci-physical-mail-and-new-release-google-form-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KUCI accepts physical CD/vinyl/wax-cylinder packages and an external Google Form digital route; the form/session boundary, track listing, artist information, genre targeting and package choice must remain owner-controlled.",
    notes: "Official KUCI Submitting Music page gives a Music Director mailing address, a New Release Submission Form link and programming-fit guidance, including not contacting non-music directors about airplay. No Google Form was opened for submission, no file/link was delivered and no physical package was prepared or mailed."
  },
  {
    name: "WCBN Ann Arbor Hard-Copy Album Music Director Submission Route",
    websiteUrl: "https://wcbn.org/",
    submissionUrl: "https://wcbn.org/c/",
    sourceUrl: "https://wcbn.org/c/",
    sourceType: "automation_run_145_public_research",
    country: "United States / Ann Arbor student-run freeform radio hard-copy airplay review route",
    language: "en",
    genres: ["college-radio", "freeform-radio", "hard-copy-submission", "cd", "vinyl", "genre-director-routing", "obfuscated-email", "manual-review"],
    submissionMethod: "official-wcbn-hard-copy-music-director-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WCBN asks musicians to send a hard copy, preferably CD or vinyl, to WCBN MUSIC or a genre director; the music-director contact is public but obfuscated in parsed text and must not be decoded or guessed automatically.",
    notes: "Official WCBN Contact Us page lists the station mailing address, Music Directors, genre-director routing and states WCBN accepts music from any and all musicians willing to send a hard copy of an album. No protected/obfuscated contact was decoded, no email was sent and no package was prepared or mailed."
  },
  {
    name: "KVRX Austin Physical Digital Music Department Airplay Submission Route",
    websiteUrl: "https://kvrx.org/",
    submissionUrl: "https://kvrx.org/app/contact/",
    sourceUrl: "https://kvrx.org/app/contact/",
    sourceType: "automation_run_145_public_research",
    country: "United States / Austin student radio physical and digital airplay consideration route",
    language: "en",
    genres: ["college-radio", "independent-radio", "physical-submission", "digital-submission", "music-department-email", "no-ai-submissions", "manual-review"],
    submissionMethod: "official-kvrx-music-department-physical-digital-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KVRX accepts physical and digital submissions for airplay consideration but excludes AI-assisted/generated music; format, rights, metadata, clean notes and email/package choices require owner review.",
    notes: "Official KVRX Contact page lists the mailing address, says all music submissions for airplay consideration should go to music@kvrx.org, gives operations@kvrx.org for submission questions, states both physical and digital submissions are accepted, and excludes AI-assisted/generated music. No email was sent and no file/package was delivered."
  },
  {
    name: "WYSO Novaphonic WAV CD Music Department Airplay Submission Route",
    websiteUrl: "https://www.wyso.org/",
    submissionUrl: "https://www.wyso.org/music-submission",
    sourceUrl: "https://www.wyso.org/music-submission",
    sourceType: "automation_run_145_public_research",
    country: "United States / Ohio public radio and Novaphonic eclectic airplay submission route",
    language: "en",
    genres: ["public-radio", "novaphonic", "eclectic-radio", "wav-preferred", "cd", "bandcamp-download", "clean-radio-edits", "music-department-email", "manual-review"],
    submissionMethod: "official-wyso-novaphonic-music-department-digital-physical-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WYSO/Novaphonic requests high-quality downloadable files, clean radio edits, metadata, bios/one-sheets and optional physical releases; package quality, FCC-clean status and Ohio/local context need review.",
    notes: "Official WYSO Music Submission page invites singles and albums/EPs, asks for releases by email to musicdepartment@wyso.org with WAV-preferred download files, artist/release metadata, clean edits and bio/press context, also allowing physical releases by mail. No email was sent, no files were delivered and no package was prepared or mailed."
  },
  {
    name: "WREK Atlanta Snail Mail Email Music Director Library Submission Route",
    websiteUrl: "https://wrek.org/",
    submissionUrl: "https://old.wrek.org/submissions/",
    sourceUrl: "https://old.wrek.org/submissions/",
    sourceType: "automation_run_145_public_research",
    country: "United States / Atlanta student-run radio music library and airplay review route",
    language: "en",
    genres: ["college-radio", "student-radio", "quality-diverse-music", "snail-mail", "music-director-email", "cd", "lp", "electronic", "reggae", "world", "manual-review"],
    submissionMethod: "official-wrek-snail-mail-email-music-director-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WREK accepts snail-mail and email music director submissions, but CDs and LPs have better airplay odds; media format, genre fit, metadata, contact details and follow-up timing require owner control.",
    notes: "Official WREK Music page links to Submit Songs, and the official submission page lists the snail-mail address plus music.director@wrek.org, common media-format handling, CD/LP preference and add-list follow-up guidance. No email was sent and no physical package was prepared or mailed."
  }
];
