import type { PlatformInput } from '../models/types.js';

export const run114SeedPlatforms: PlatformInput[] = [
  {
    name: "Bandcamp Direct-to-Fan Artist Store and Music Upload Route",
    websiteUrl: "https://bandcamp.com/",
    submissionUrl: "https://bandcamp.com/artists",
    sourceUrl: "https://bandcamp.com/artists",
    sourceType: "automation_run_114_public_research",
    country: "United States / Global direct-to-fan artist store and discovery marketplace",
    language: "en",
    genres: ["bandcamp", "direct-to-fan", "artist-store", "digital-albums", "digital-tracks", "merch", "music-community", "electronic", "dub", "reggae", "world", "bass-music", "free-account", "optional-pro", "account-boundary", "upload-boundary", "manual-review"],
    submissionMethod: "official-bandcamp-direct-to-fan-artist-store-music-upload-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Bandcamp is an account-based artist-store and upload route involving profile/store setup, track or album metadata, pricing, PayPal/payment configuration, merch choices, rights confirmation, release timing and optional Bandcamp Pro decisions before publication.",
    notes: "Official public research confirmed Bandcamp for Artists is a direct-to-fan record store and music community, artist accounts are free, Bandcamp takes a revenue share on sales, optional Bandcamp Pro exists, and desktop sign-up is required. No account was created, no login was used, no tracks were uploaded, no store settings were changed and no payment configuration was touched."
  },
  {
    name: "Jamendo Artists Music Licensing In-Store Promotion and Content ID Route",
    websiteUrl: "https://artists.jamendo.com/",
    submissionUrl: "https://artists.jamendo.com/",
    sourceUrl: "https://artists.jamendo.com/",
    sourceType: "automation_run_114_public_research",
    country: "Luxembourg / Global independent-artist streaming, licensing and commercial-placement route",
    language: "en",
    genres: ["jamendo", "artist-services", "licensing", "sync", "in-store", "content-id", "promotion", "independent-artists", "electronic", "reggae", "dub", "world", "free-first", "account-boundary", "rights-review", "manual-review"],
    submissionMethod: "official-jamendo-artists-licensing-in-store-promotion-content-id-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Jamendo Artists is an account-based artist services route involving music upload, licensing opt-ins, in-store placement, Content ID, promotion, rights ownership, collecting-society compatibility and revenue-share terms.",
    notes: "Official public research confirmed Jamendo Artists offers a one-stop space for DIY musicians, Jamendo Music discovery, licensing placements, in-store placement, Content ID and promotion. No account was created, no sign-in was used, no music was uploaded, no licensing setting was selected and no Content ID tracking was activated."
  },
  {
    name: "Mixcloud Creator Upload DJ Mix Radio Show and Live Stream Route",
    websiteUrl: "https://www.mixcloud.com/",
    submissionUrl: "https://www.mixcloud.com/",
    sourceUrl: "https://www.mixcloud.com/",
    sourceType: "automation_run_114_public_research",
    country: "United Kingdom / Global DJ mix, radio show, podcast and creator-audio platform",
    language: "en",
    genres: ["mixcloud", "creator-upload", "dj-mixes", "radio-shows", "podcasts", "live-streaming", "electronic", "house", "progressive-house", "bass", "drum-and-bass", "reggae", "dub", "world", "free-upload", "optional-pro", "account-boundary", "manual-review"],
    submissionMethod: "official-mixcloud-creator-upload-dj-mix-radio-show-live-stream-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Mixcloud is an account-based creator upload route for shows, mixes and live streams, requiring tracklist/rights review, audio-format readiness, metadata, profile setup and optional Pro/monetization decisions before publication.",
    notes: "Official public research confirmed Mixcloud exposes Sign up for free and Upload for free routes, creator tools, Pro for creators, unlimited uploads, live streaming, monetization and current active genre pages including electronic, house, reggae, hip hop and radio shows. No account was created, no login was used, no upload was started and no Pro subscription was initiated."
  },
  {
    name: "Songtradr Sync Licensing Marketplace and Artist Upload Route",
    websiteUrl: "https://www.songtradr.com/",
    submissionUrl: "https://www.songtradr.com/",
    sourceUrl: "https://www.songtradr.com/",
    sourceType: "automation_run_114_public_research",
    country: "United States / Global sync licensing and music-rights marketplace",
    language: "en",
    genres: ["songtradr", "sync-licensing", "music-licensing", "marketplace", "artist-upload", "brands", "film-tv", "advertising", "games", "electronic", "reggae", "dub", "world", "javascript-app", "account-boundary", "rights-review", "manual-review"],
    submissionMethod: "official-songtradr-sync-licensing-marketplace-artist-upload-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Songtradr is a JavaScript app and sync-licensing marketplace route involving account/session handling, master and publishing rights, PRO/ownership metadata, licensing fee strategy, usage permissions and possible distribution or monetization choices.",
    notes: "Public research confirmed Songtradr's official site is active but JavaScript-gated, and secondary public references describe Songtradr as a B2B music licensing platform where artists can upload music and set licensing fees. No JavaScript app session was initiated, no account was created, no login was used, no track was uploaded and no licensing terms were configured."
  },
  {
    name: "LabelRadar Demo Contest and Label Submission Platform Route",
    websiteUrl: "https://www.labelradar.com/",
    submissionUrl: "https://www.labelradar.com/artists",
    sourceUrl: "https://www.labelradar.com/artists",
    sourceType: "automation_run_114_public_research",
    country: "Global electronic-music demo, remix contest and label-discovery route",
    language: "en",
    genres: ["labelradar", "demo-submission", "record-labels", "remix-contests", "beatport", "electronic", "edm", "dance", "house", "bass", "dubstep", "producer", "account-boundary", "javascript-app", "payment-option", "manual-review"],
    submissionMethod: "official-labelradar-demo-contest-label-submission-platform-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because LabelRadar is a JavaScript-gated artist/label submission route requiring account/session handling, demo or contest selection, label fit, rights and remix-stem rules, track metadata, upload/link handling and any credit/payment-option review.",
    notes: "Public research confirmed LabelRadar's artist page is live but JavaScript-gated, and current industry coverage identifies LabelRadar as Beatport's online platform for artists to connect with labels and submit remix-contest entries. No account was created, no login was used, no contest was entered, no demo was uploaded and no payment or credits were used."
  }
];
