import type { PlatformInput } from '../models/types.js';

export const run196BaseSeedPlatforms: PlatformInput[] = [
  {
    name: "CJSW Calgary Digital Album ZIP Jotform Music Submission Route",
    websiteUrl: "https://cjsw.com/",
    submissionUrl: "https://cjsw.com/music/submit/",
    sourceUrl: "https://cjsw.com/music/submit/",
    sourceType: "automation_run_196_public_research",
    country: "Canada / Calgary campus-community radio digital album submission and Canadian mailout side route",
    language: "en",
    genres: ["campus-community-radio", "freeform", "independent-artists", "albums", "mp3", "canadian-radio", "electronic", "experimental", "multicultural", "manual-review"],
    submissionMethod: "official-cjsw-digital-album-zip-jotform-upload-route",
    feeRequired: false,
    feeAmount: "Free-first/manual route for direct CJSW digital submission; related CJSW campus-radio mailout side route has separate paid physical-mailout options and therefore needs separate owner review if used.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because the route uses a public Jotform upload/form boundary, requires full recent album/EP qualification, MP3 ZIP preparation, no-single policy checks, release date validation, metadata/rights review, optional tracking-list signup and separate paid/physical mailout choices. No form, upload, email or payment may be automated.",
    notes: "Official CJSW pages say only digital submissions are accepted for the direct route, new albums must be within three months, releases must include three or more unique tracks, MP3 format is required, ZIP delivery is required and upload is through a public form link. A protected/obfuscated music contact was observed but not decoded; no deliverability probing was performed."
  },
  {
    name: "CKUT Montreal Physical 320 MP3 Music Department Submission Route",
    websiteUrl: "https://ckut.ca/",
    submissionUrl: "https://ckut.ca/submit-music-to-ckut/",
    sourceUrl: "https://ckut.ca/submit-music-to-ckut/",
    sourceType: "automation_run_196_public_research",
    country: "Canada / Montreal campus-community radio physical and 320 MP3 submission route",
    language: "en",
    genres: ["campus-community-radio", "freeform", "physical-submission", "digital-mp3", "albums", "independent-artists", "world", "electronic", "reggae", "manual-review"],
    submissionMethod: "official-ckut-physical-320-mp3-music-department-route",
    feeRequired: false,
    feeAmount: "Free-first/manual route; official CKUT guidance accepts physical releases by mail/drop-off and 320 MP3 digital submissions to the public music department email, with no submission fee observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because CKUT rejects singles, requires at least three distinct tracks for most formats, evaluates digital submissions under the same library criteria as physical releases, warns that email volume is high and needs clean metadata, format, rights and pitch review. No email, file transfer or physical package may be automated.",
    notes: "Official CKUT guidance says DJs choose from recordings sent by artists and record companies around the world, accepts CDs/cassettes/vinyl plus 320 MP3 digital submissions, and lists music@ckut.ca as the digital submission route. The email was treated only as a public official route; no message or deliverability probe was sent."
  },
  {
    name: "!earshot Distro Canadian Campus Radio Paid Upload Distribution Route",
    websiteUrl: "https://earshot-distro.ca/",
    submissionUrl: "https://earshot-distro.ca/",
    sourceUrl: "https://earshot-distro.ca/",
    sourceType: "automation_run_196_public_research",
    country: "Canada / national campus and community radio digital distribution system",
    language: "en",
    genres: ["canadian-radio", "campus-community-radio", "digital-distribution", "albums", "independent-artists", "labels", "promoters", "electronic", "world", "manual-review"],
    submissionMethod: "official-earshot-distro-paid-campus-radio-upload-route",
    feeRequired: true,
    feeAmount: "Paid/manual route; official !earshot Distro page says uploads start at $7/song or $50/album (8-20 songs) Canadian plus tax.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because the route uses sign-up/login, paid upload fees, Canadian campus/community radio distribution targeting, rights-to-distribute confirmation, release metadata, audio file preparation and terms/payment approval. No account, upload, payment or distribution workflow may be automated.",
    notes: "Official !earshot Distro copy says NCRA/ANREC, Canadian stations and the music industry created the platform so rights holders can upload recordings for campus/community stations to search, review, download and broadcast across Canada. It is available to labels, distributors, publishers, promoters and independent artists with distribution rights."
  },
  {
    name: "Radio Free Brooklyn Download Link reCAPTCHA Music Submission Form Route",
    websiteUrl: "https://www.radiofreebrooklyn.org/",
    submissionUrl: "https://submissions.radiofreebrooklyn.org/music-submission-form/",
    sourceUrl: "https://submissions.radiofreebrooklyn.org/music-submission-form/",
    sourceType: "automation_run_196_public_research",
    country: "United States / Brooklyn internet radio downloadable-link submission and optional physical route",
    language: "en",
    genres: ["internet-radio", "brooklyn", "independent-artists", "download-link", "freeform", "electronic", "world", "reggae", "manual-review"],
    submissionMethod: "official-radio-free-brooklyn-download-link-recaptcha-form-route",
    feeRequired: false,
    feeAmount: "Free-first/manual route; official form asks for a freely downloadable track or ZIP link and no submission fee was observed.",
    loginRequired: false,
    captchaDetected: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because the public form collects artist/contact details, phone, music description, NYC-area and guest-interest fields, an image/graphic upload with a small-size limit, a listen/download URL and reCAPTCHA validation. No CAPTCHA, form, upload, email or physical package may be automated.",
    notes: "Official Radio Free Brooklyn form says tracks must be freely listenable/downloadable through links such as Bandcamp download code, SoundCloud download, Dropbox or Google Drive; non-downloadable tracks are not considered. The page also offers an optional vinyl/CD route addressed to the Music Director. No form was submitted and no challenge control was handled."
  },
  {
    name: "KUTX Austin Music Director WAV Link Airplay Submission Route",
    websiteUrl: "https://kutx.org/",
    submissionUrl: "https://kutx.org/submit-your-music/",
    sourceUrl: "https://kutx.org/submit-your-music/",
    sourceType: "automation_run_196_public_research",
    country: "United States / Austin-Texas public radio music director email and specialty-show route",
    language: "en",
    genres: ["public-radio", "austin", "texas", "music-director", "wav-download-link", "specialty-shows", "electronic", "experimental", "hip-hop", "latin", "manual-review"],
    submissionMethod: "official-kutx-music-director-email-wav-link-route",
    feeRequired: false,
    feeAmount: "Free-first/manual route; official KUTX guidance lists a public music director email for rotation submissions and no submission fee was observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KUTX requires subject-line formatting, streaming and WAV download links, mastered clean radio edits only, new/upcoming-release checks, Austin/Texas flagging, specialty-show fit review and no attachment behavior. No email, file transfer, event form or sponsorship route may be automated.",
    notes: "Official KUTX guidance says artists should email music@kutx.org with streaming links, a WAV download link, bio/release/tour/collab notes and a highlighted top pick. The page lists genre-specific specialty shows including electronic/experimental Soundfounder, hip-hop/R&B The Breaks and Latin Horizontes. The email was treated only as a public official route; no message or deliverability probe was sent."
  }
];
