import type { PlatformInput } from '../models/types.js';
import { run160SeedPlatforms } from './run160PlatformSeeds.js';

export const run159SeedPlatforms: PlatformInput[] = [
  {
    name: "KEXP Digital WAV Music Director Rotation Submission Route",
    websiteUrl: "https://kexp.org/",
    submissionUrl: "https://www.kexp.org/about/submission-guidelines/",
    sourceUrl: "https://www.kexp.org/about/submission-guidelines/",
    sourceType: "automation_run_159_public_research",
    country: "Global / United States-based listener-powered eclectic public radio station with Seattle and Bay Area reach",
    language: "en",
    genres: ["eclectic", "indie", "electronic", "world", "reggae", "hip-hop", "latin", "afrobeat", "radio-airplay", "music-director-email", "manual-review", "fcc-clean"],
    submissionMethod: "official-kexp-digital-wav-music-director-rotation-submission-route",
    feeRequired: false,
    feeAmount: "No pay-for-play or submission fee; KEXP explicitly says paying for play is not available and asks for digital submissions to md@kexp.org with streaming/download WAV links and release context.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KEXP asks for a curated digital release package with WAV download links, focus tracks, release dates, clean/FCC-safe edits, lyric sheet, credits, bio/one-sheet and Pacific Northwest or Bay Area show context.",
    notes: "Public research verified the official KEXP contact and submission-guidelines pages, current 2026 site activity, the md@kexp.org Music Department route, digital-only preference, no-attachments guidance, no physical submissions and no-pay-for-play rule. No email was sent, no private links were delivered and no audio files were transferred."
  },
  {
    name: "Triple R 3RRR Digital Physical Presenter Station Music Submission Route",
    websiteUrl: "https://www.rrr.org.au/",
    submissionUrl: "https://www.rrr.org.au/get-involved/submit-music",
    sourceUrl: "https://www.rrr.org.au/get-involved/submit-music",
    sourceType: "automation_run_159_public_research",
    country: "Australia / Melbourne independent community radio with worldwide streaming",
    language: "en",
    genres: ["community-radio", "independent-radio", "electronic", "hip-hop", "reggae", "world", "jazz", "station-email", "presenter-routing", "physical-side-route", "manual-review"],
    submissionMethod: "official-triple-r-3rrr-digital-physical-presenter-station-music-submission-route",
    feeRequired: false,
    feeAmount: "No submission fee observed; official route accepts station servicing by email to music@rrr.org.au or direct presenter/program servicing, with optional physical CD/LP/cassette package route.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Triple R is not playlisted, presenters select tracks independently, and the package must include non-login stream links, high-quality MP3/WAV download links, clear file names, bio and gig/launch details without large email attachments.",
    notes: "Public research verified Triple R's official Submit Music page, current 2026 homepage activity, music@rrr.org.au station route, direct presenter servicing option and physical mail side route. No email was sent, no presenter was targeted, no files or links were delivered and no physical package was prepared."
  },
  {
    name: "CKUT 90.3FM Physical Digital Music Department Library Submission Route",
    websiteUrl: "https://ckut.ca/",
    submissionUrl: "https://ckut.ca/submit-music-to-ckut/",
    sourceUrl: "https://ckut.ca/submit-music-to-ckut/",
    sourceType: "automation_run_159_public_research",
    country: "Canada / Montreal campus-community radio with global and underground programming",
    language: "en",
    genres: ["campus-community-radio", "global", "reggae", "soca", "dancehall", "electronic", "house", "hip-hop", "experimental", "physical-side-route", "music-department-email", "manual-review"],
    submissionMethod: "official-ckut-physical-digital-music-department-library-submission-route",
    feeRequired: false,
    feeAmount: "No submission fee observed; official route accepts physical releases and 320 MP3 digital submissions to music@ckut.ca, subject to library criteria.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because CKUT does not accept singles, requires at least three distinct tracks except vinyl 7-inch releases, evaluates digital submissions against physical-library criteria, and notes physical releases may receive more attention.",
    notes: "Public research verified CKUT's official Submit Music page, current 2026 site activity, music@ckut.ca digital route, physical Music Department mailing route, library criteria, no-singles policy and relevant genre programming tags including Caribbean, reggae, soca/dancehall, electronic, house, hip-hop and global. No email was sent and no audio or package was delivered."
  },
  {
    name: "WFMU Freeform Physical Music Director Review and JavaScript Contact Route",
    websiteUrl: "https://wfmu.org/",
    submissionUrl: "https://wfmu.org/sendmusic.html",
    sourceUrl: "https://wfmu.org/sendmusic.html",
    sourceType: "automation_run_159_public_research",
    country: "United States / New Jersey-New York freeform independent radio with global online audience",
    language: "en",
    genres: ["freeform-radio", "experimental", "eclectic", "marginal-music", "physical-submission", "music-director", "contact-form", "javascript-boundary", "manual-review"],
    submissionMethod: "official-wfmu-freeform-physical-music-director-review-contact-route",
    feeRequired: false,
    feeAmount: "No submission fee observed; official route asks artists/labels to ship vinyl, CD, CD-R or cassette materials for review and provides a JavaScript-based Music Department contact page.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WFMU's primary route is physical media sent to the Music Director, the online Music Department page requires JavaScript, and package format, release fit, one-sheet content and mailing choice must be owner-controlled.",
    notes: "Public research verified WFMU's official homepage, Send Us Music navigation, active July 2026 archive activity, physical review address for Jessica Romoff/Music Director and the public Music Department contact form's JavaScript boundary. No JavaScript form was executed, no contact form was submitted, no package was prepared or mailed and no audio was transferred."
  },
  {
    name: "Worldwide FM Global Music Collaboration Contact and New Voices Pitch Route",
    websiteUrl: "https://www.worldwidefm.net/",
    submissionUrl: "https://www.worldwidefm.net/contact",
    sourceUrl: "https://www.worldwidefm.net/contact",
    sourceType: "automation_run_159_public_research",
    country: "Global / United Kingdom-based independent global radio platform founded by Gilles Peterson",
    language: "en",
    genres: ["global-radio", "worldwide-music", "electronic", "dub", "jazz", "latin", "afro-fusion", "caribbean", "curator-pitch", "contact-form", "discord-side-route", "payment-side-route", "manual-review"],
    submissionMethod: "official-worldwide-fm-global-music-collaboration-contact-new-voices-pitch-route",
    feeRequired: false,
    feeAmount: "No submission fee observed for the public contact route; a £6/month member-support side route and Discord/community route were observed but were not used.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because this is a general contact/collaboration and editorial pitch route rather than a generic upload inbox; show/curator fit, global music angle, link package, rights, clean/explicit notes and whether Discord/member side routes are appropriate must be reviewed.",
    notes: "Public research verified the official Worldwide FM site, current 2026 programming/activity, Contact page, info@worldwidefm.net email, public Send a Message fields, Discord/community link, member-support side route and New Voices/Friday Curates context for innovative music from around the globe. No form was submitted, no Discord joined, no login used, no payment started and no music links were delivered."
  },
  ...run160SeedPlatforms
];
