import type { PlatformInput } from '../models/types.js';

export const run194BaseSeedPlatforms: PlatformInput[] = [
  {
    name: "FBi Radio Sydney Music Submissions Email Route",
    websiteUrl: "https://www.fbi.radio/",
    submissionUrl: "https://www.fbi.radio/contact",
    sourceUrl: "https://www.fbi.radio/contact",
    sourceType: "automation_run_194_public_research",
    country: "Australia / Sydney emerging music community-radio submission route",
    language: "en",
    genres: ["community-radio", "emerging-music", "sydney", "electronic", "indie", "hip-hop", "dance", "dj", "manual-review"],
    submissionMethod: "official-fbi-radio-public-music-submissions-email-route",
    feeRequired: false,
    feeAmount: "Free-first/manual route; official FBi contact page lists a public Music Submissions email and public station contacts, with active July 2026 station/music activity observed on the official site.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because FBi positions itself around emerging Sydney music and culture; fit, release geography, clean/radio edit, download/stream link choice, EPK copy, sender identity and consent must be confirmed before any email is sent. No message or deliverability probe may be automated.",
    notes: "Official contact page lists Music Submissions at music@fbiradio.com and station contacts. Queued as a manual public-email route only; no email was sent, no contact guessed, no MX/SMTP probing was performed and no anti-bot controls were handled."
  },
  {
    name: "RTRFM Perth Form Download Link Music Director Route",
    websiteUrl: "https://rtrfm.com.au/",
    submissionUrl: "https://rtrfm.com.au/submit-your-music/",
    sourceUrl: "https://rtrfm.com.au/submit-your-music/",
    sourceType: "automation_run_194_public_research",
    country: "Australia / Perth community-radio digital form and Music Director review route",
    language: "en",
    genres: ["community-radio", "perth", "electronic", "beats", "dance", "local-feature", "radio-airplay", "music-director", "manual-review"],
    submissionMethod: "official-rtrfm-public-form-download-link-music-director-route",
    feeRequired: false,
    feeAmount: "Free-first/manual route; official RTRFM page invites artists to submit latest/upcoming releases using a form, stream link and free download link, with WAV/high-quality MP3 guidance and a physical-copy side route.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because the route includes a public form, file/link preparation, free-download requirement, city/state/overseas fields, biography upload, local-feature fit and protected email display. No form, upload, protected contact decoding or email may be automated.",
    notes: "Official RTRFM submission page says the Music Team will consider submitted releases and asks for downloadable WAV or high-quality MP3 links without email attachments. Protected/obfuscated email displays were observed but not decoded. No form entry, file upload, email send, physical package or deliverability check was performed."
  },
  {
    name: "PBS 106.7FM International Digital Form CAPTCHA Music Submission Route",
    websiteUrl: "https://www.pbsfm.org.au/",
    submissionUrl: "https://www.pbsfm.org.au/submitmusic",
    sourceUrl: "https://www.pbsfm.org.au/submitmusic",
    sourceType: "automation_run_194_public_research",
    country: "Australia / Melbourne local and international community-radio digital-form route",
    language: "en",
    genres: ["community-radio", "melbourne", "international", "under-represented-music", "electronic", "world", "reggae", "radio-airplay", "manual-review"],
    submissionMethod: "official-pbs-fm-digital-submission-form-captcha-route",
    feeRequired: false,
    feeAmount: "Free-first/manual route; official PBS page says it accepts new music from local and international acts and prefers digital submissions through the form, with optional CD/vinyl side route.",
    loginRequired: false,
    captchaDetected: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because the official form includes a CAPTCHA/human-visitor test and asks for country/location, stream link, high-quality download link, bio and consent/newsletter choices. CAPTCHA and form controls must not be automated or bypassed.",
    notes: "Official PBS form accepts stream links, rejects Spotify/Deezer as stream sources, requests 320kbps AAC/MP3/WAV-equivalent downloads, and lists physical-copy guidance. No CAPTCHA was solved, no form was submitted, no files were uploaded and no physical package was prepared."
  },
  {
    name: "4ZZZ Brisbane Music Department Digital Library Form Route",
    websiteUrl: "https://4zzz.org.au/",
    submissionUrl: "https://4zzz.org.au/music-submissions",
    sourceUrl: "https://4zzz.org.au/music-submissions",
    sourceType: "automation_run_194_public_research",
    country: "Australia / Brisbane community-radio music department digital-library form route",
    language: "en",
    genres: ["community-radio", "brisbane", "alternative", "electronic", "reggae", "ska", "punk", "independent", "manual-review"],
    submissionMethod: "official-4zzz-music-department-digital-library-form-route",
    feeRequired: false,
    feeAmount: "Free-first/manual route; official 4ZZZ page invites artists to submit music to the Music Department for airplay and digital-library processing, with a linked external submission form.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because the official route uses an external form boundary, requires downloadable music rather than non-downloadable streams, and is focused on Music Department processing and announcer access. No external form interaction may be automated.",
    notes: "Official 4ZZZ page says submitted music may be considered for processing and inclusion in its digital library for announcers, and links to a separate submit-your-music form. No linked form was entered, no files were uploaded, no direct announcer servicing was attempted and no anti-bot controls were handled."
  },
  {
    name: "Triple J Unearthed Australian Artist Upload Discovery Route",
    websiteUrl: "https://www.abc.net.au/triplejunearthed",
    submissionUrl: "https://www.abc.net.au/triplejunearthed",
    sourceUrl: "https://www.abc.net.au/triplejunearthed",
    sourceType: "automation_run_194_public_research",
    country: "Australia / ABC unsigned Australian artist upload and discovery route",
    language: "en",
    genres: ["artist-upload", "unsigned-australian-artists", "electronic", "pop", "hip-hop", "beats", "radio-discovery", "manual-review"],
    submissionMethod: "official-triple-j-unearthed-artist-upload-discovery-route",
    feeRequired: false,
    feeAmount: "Free-first/manual route; official ABC/triple j Unearthed site shows active 2026 tracks, reviews and discovery activity, and public context confirms Unearthed is an upload/discovery platform for Australian artists.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Unearthed is an artist-profile/upload platform with likely account/login handling and Australian-artist eligibility constraints. Account creation, login, upload, profile setup and eligibility claims must remain manual.",
    notes: "Official ABC Unearthed page shows active July 2026 staff reviews, tracks, artist profiles and discovery sections. Queued only as a manual eligibility/account route for Australian-artist scenarios; no account, login, profile creation, upload or message action was performed."
  }
];