import type { PlatformInput } from '../models/types.js';

export const run189BaseSeedPlatforms: PlatformInput[] = [
  {
    name: "EARMILK SubmitHub Pillargram Electronic Blog Submission Route",
    websiteUrl: "https://earmilk.com/",
    submissionUrl: "https://earmilk.com/submit-music/",
    sourceUrl: "https://earmilk.com/submit-music/",
    sourceType: "automation_run_189_public_research",
    country: "Global / electronic hip-hop indie pop reggae music blog submission route through authorized third-party platforms",
    language: "en",
    genres: ["music-blog", "electronic", "dance", "experimental", "hip-hop", "indie", "pop", "rock", "reggae", "premiere", "submithub", "pillargram", "manual-review"],
    submissionMethod: "official-earmilk-submithub-pillargram-music-submission-route",
    feeRequired: false,
    feeAmount: "Free-first/manual EARMILK route through authorized SubmitHub or Pillargram submission platforms; third-party login, credit/pricing and pitch requirements require owner review before any submission.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because EARMILK explicitly rejects music sent through its contact form and exclusively accepts new music/premieres through SubmitHub or Pillargram. Owner must approve third-party account use, possible credit/pricing choices, pitch copy, premiere status, genre targeting, rights/authorship, clean edits and link handling before any app submission.",
    notes: "Official EARMILK Submit Music page says submissions are accepted only through SubmitHub or Pillargram and shows July 2026 music activity. Official Contact page says music submissions through the contact form are automatically filtered and lists david@earmilk.com only for brand partnerships/events, not music submissions. No contact form, email, app submission, login, upload or payment action was taken."
  },
  {
    name: "DropTrack Artist Label DJ Radio Blog Playlist Campaign Route",
    websiteUrl: "https://www.droptrack.com/",
    submissionUrl: "https://www.droptrack.com/",
    sourceUrl: "https://www.droptrack.com/",
    sourceType: "automation_run_189_public_research",
    country: "Global / artist label music promotion and industry-contact submission campaign platform",
    language: "en",
    genres: ["music-promotion", "djs", "radio", "blogs", "playlist-curators", "labels", "electronic", "reggae", "world", "hip-hop", "campaign-platform", "manual-review"],
    submissionMethod: "official-droptrack-artist-label-targeted-submission-campaign-route",
    feeRequired: false,
    feeAmount: "Freemium/manual DropTrack route; public page exposes free account/analyzer paths plus artist/label pricing, supplied contacts, email campaigns, playlist placement and Pro features.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because DropTrack is a campaign/app platform with signup/login, pricing, contact-list use, email campaign tooling, playlist placement options, track upload/analytics and AI-generated press-material features. Owner must approve account access, plan/credit spend, contact targeting, opt-in compliance, pitch content, upload assets and release metadata before any campaign or delivery action.",
    notes: "Official DropTrack page states artists and labels can pitch DJs, labels, playlist curators, bloggers and radio contacts, create email campaigns, upload tracks and use analytics. Pricing and cloud app links were observed. No login, signup, upload, email campaign, playlist placement, contact export, payment or submission action was taken."
  },
  {
    name: "Playlist Push Spotify TikTok Curator Paid Campaign Route",
    websiteUrl: "https://playlistpush.com/",
    submissionUrl: "https://playlistpush.com/spotify-playlists-promotion",
    sourceUrl: "https://playlistpush.com/spotify-playlists-promotion",
    sourceType: "automation_run_189_public_research",
    country: "Global / paid Spotify playlist and TikTok creator music promotion campaign route",
    language: "en",
    genres: ["spotify-playlists", "playlist-curators", "tiktok", "paid-campaign", "electronic", "edm", "reggae", "world", "pop", "hip-hop", "manual-review"],
    submissionMethod: "official-playlist-push-spotify-tiktok-curator-paid-campaign-route",
    feeRequired: true,
    feeAmount: "Paid/manual Playlist Push route; official pricing page states Spotify campaign minimum budget starts at $280 and calculator examples show higher spend tiers, while playlist adds are not guaranteed.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Playlist Push is a paid campaign/app route where music is submitted to Spotify playlist curators or TikTok creators via account workflow. Owner must approve budget, track selection, Spotify link or MP3 upload, genre/mood/language targeting, curator review terms, no-guarantee language, release timing, rights and campaign reporting before any app action.",
    notes: "Official Playlist Push pages show Spotify/TikTok artist services, Create Account/Sign In app boundaries, Spotify playlist submission workflow, MP3/Spotify-link handling, curator targeting, campaign analytics and a $280 minimum Spotify campaign budget. No account, login, MP3 upload, campaign setup, payment or curator submission was initiated."
  },
  {
    name: "RepostExchange SoundCloud Creator Credit Repost Feedback Route",
    websiteUrl: "https://repostexchange.com/",
    submissionUrl: "https://repostexchange.com/welcome",
    sourceUrl: "https://repostexchange.com/welcome",
    sourceType: "automation_run_189_public_research",
    country: "Global / SoundCloud creator repost feedback and campaign network route",
    language: "en",
    genres: ["soundcloud", "repost-network", "feedback", "electronic", "edm", "deep-house", "trap", "techno", "ambient", "hip-hop", "free-first", "manual-review"],
    submissionMethod: "official-repostexchange-soundcloud-credit-repost-feedback-route",
    feeRequired: false,
    feeAmount: "Free-first/freemium RepostExchange route; official page says free to use/no credit card required, while pricing page shows optional credit packs and Pro plans starting at $15.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because RepostExchange requires connecting a SoundCloud account and uses credits, repost requests, campaigns, feedback and optional paid credit packs/plans. Owner must approve SoundCloud connection, track eligibility, campaign ethics, manual repost behavior, credit spend, genre fit and platform-compliance review before any connection or campaign action.",
    notes: "Official RepostExchange page says it is an official SoundCloud partner, free to use, creator/community based, and requires connecting with SoundCloud. It describes credit-based repost requests, campaigns and feedback; pricing page explains free, credit packs and Pro plans. No SoundCloud connection, login, repost, follow, like, comment, credit purchase or campaign was initiated."
  },
  {
    name: "Hypeddit Music Promotion Download Gate New Releases Route",
    websiteUrl: "https://hypeddit.com/",
    submissionUrl: "https://hypeddit.com/",
    sourceUrl: "https://hypeddit.com/",
    sourceType: "automation_run_189_public_research",
    country: "Global / artist music promotion smart-link download-gate new-releases and fan-growth route",
    language: "en",
    genres: ["music-promotion", "download-gates", "smart-links", "pre-saves", "new-releases", "spotify", "soundcloud", "youtube", "tiktok", "electronic", "reggae", "world", "manual-review"],
    submissionMethod: "official-hypeddit-download-gate-new-releases-music-promotion-route",
    feeRequired: false,
    feeAmount: "Free-first/freemium Hypeddit route; official pricing shows Rookie free after Pro trial, Basic $10/month, Pro $20/month and Elite $100/month plus in-app fan-promotion/ad-spend considerations.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Hypeddit is an account/app music-promotion platform with cookies, login, free trial/pricing, download gates, smart links, pre-saves, new releases/top charts eligibility and ad/fan-promotion features. Owner must approve account access, pricing/trial, cookie/session handling, asset upload, platform links, gate mechanics, privacy and ad-spend before any use.",
    notes: "Official Hypeddit pages show Try for Free/Login, music-promotion tools, download gates, smart links, pre-saves, Top 100/New Releases areas, cookie controls and pricing tiers. No cookie preferences were handled, no login/signup was used, no files or links were uploaded, no gate/pre-save/ad campaign was created and no payment was initiated."
  }
];
