import type { PlatformInput } from '../models/types.js';
import { run153SeedPlatforms } from './run153PlatformSeeds.js';

export const run152SeedPlatforms: PlatformInput[] = [
  {
    name: "Fresh On The Net Weekly Listening Post New Track Submission Route",
    websiteUrl: "https://freshonthenet.co.uk/",
    submissionUrl: "https://freshonthenet.co.uk/submit/",
    sourceUrl: "https://freshonthenet.co.uk/submit/",
    sourceType: "automation_run_152_public_research",
    country: "Global / United Kingdom-based independent music blog and Listening Post discovery route",
    language: "en",
    genres: ["independent-music", "blog-discovery", "listening-post", "electronic", "world", "reggae", "pop", "new-music", "timing-boundary", "manual-review"],
    submissionMethod: "official-fresh-on-the-net-weekly-listening-post-track-submission-route",
    feeRequired: false,
    feeAmount: "No submission fee observed; route opens weekly and closes at 200 tracks or Wednesday evening, whichever comes first.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because the inbox was closed at discovery time and submission depends on weekly timing, one-track-per-week limits, public worldwide track availability, no-repeat/no-remix rules, AI-content exclusion and radio-clean package decisions.",
    notes: "Public research verified Fresh On The Net's official Send Us A Track route, weekly Listening Post workflow and current 2026 site activity. The page stated the inbox was closed during this run. No form was opened or submitted, no track link was delivered and no staff radio contact was used."
  },
  {
    name: "KUTX Music Director WAV Airplay and Electronic Specialty Show Submission Route",
    websiteUrl: "https://kutx.org/",
    submissionUrl: "https://kutx.org/submit-your-music/",
    sourceUrl: "https://kutx.org/submit-your-music/",
    sourceType: "automation_run_152_public_research",
    country: "United States / Austin, Texas public radio music station with specialty electronic, world, Latin and new-music programming",
    language: "en",
    genres: ["public-radio", "airplay", "electronic", "experimental", "world", "latin", "independent", "clean-radio-edit", "verified-email-route", "manual-review"],
    submissionMethod: "official-kutx-music-director-wav-airplay-specialty-show-email-route",
    feeRequired: false,
    feeAmount: "No music-submission fee observed for the Music Director route; separate event sponsorship/underwriting side routes are outside the free music-submission workflow.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KUTX asks for streaming links, downloadable WAV links, final mastered clean radio edits, artist/release context, highlighted focus track and Austin/Texas fit notes before any contact is sent.",
    notes: "Public research verified the official KUTX Submit Your Music page and public Music Director contact route. KUTX showed 2026 homepage activity and the Soundfounder specialty show for electronic/experimental music. No contact was sent, no WAV/download link was delivered and no event/sponsorship route was entered."
  },
  {
    name: "FBi Radio Digital Music Servicing Premiere and Interview Submission Route",
    websiteUrl: "https://www.fbi.radio/",
    submissionUrl: "https://www.fbi.radio/pages/music-submissions",
    sourceUrl: "https://www.fbi.radio/pages/music-submissions",
    sourceType: "automation_run_152_public_research",
    country: "Australia / Sydney independent community radio station focused on emerging music and culture",
    language: "en",
    genres: ["community-radio", "airplay", "premiere", "interview", "electronic", "dj", "producer", "independent", "verified-email-route", "manual-review"],
    submissionMethod: "official-fbi-radio-digital-music-servicing-premiere-email-route",
    feeRequired: false,
    feeAmount: "No general music-servicing fee observed; promotional campaign and partnership side routes exist and require manual review before any paid promotion decision.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because FBi asks for a curated package with subject line, bio, press image, gig details, streaming link, high-quality download link, premiere/interview timing and show fit; paid promotional side routes must remain owner-controlled.",
    notes: "Public research verified the official FBi Radio Music Submissions page, public music-submission contact route, premiere guidance and interview route. The homepage showed current 2026 episodes/articles and active programming. No contact was sent, no stream/download link was delivered and no paid campaign or partnership workflow was entered."
  },
  {
    name: "PBS 106.7FM Digital Form and Physical Airplay Submission Route",
    websiteUrl: "https://www.pbsfm.org.au/",
    submissionUrl: "https://www.pbsfm.org.au/submitmusic",
    sourceUrl: "https://www.pbsfm.org.au/submitmusic",
    sourceType: "automation_run_152_public_research",
    country: "Australia / Melbourne community radio station accepting local and international music for presenter-led airplay consideration",
    language: "en",
    genres: ["community-radio", "airplay", "digital-form", "physical-submission", "electronic", "world", "under-represented-music", "international", "captcha-boundary", "manual-review"],
    submissionMethod: "official-pbs-106-7fm-digital-form-physical-airplay-submission-route",
    feeRequired: false,
    feeAmount: "No submission fee observed; digital form and optional CD/vinyl physical package route are public, while mailing/package costs require manual handling.",
    loginRequired: false,
    captchaDetected: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because PBS uses a public digital submission form with CAPTCHA, asks for artist identity, location/country, bio, social links, stream link and high-quality download, and also supports physical CD/vinyl package routing.",
    notes: "Public research verified the official PBS Submit Your Music route, local/international acceptance, digital form fields, high-quality download requirement, CAPTCHA boundary and optional CD/vinyl postal delivery. No form was submitted, no CAPTCHA was handled, no track/download link was delivered and no physical package was prepared or mailed."
  },
  {
    name: "2SER Airplay Consideration Public Form Submission Route",
    websiteUrl: "https://www.2ser.com/",
    submissionUrl: "https://www.2ser.com/how-to-submit-music",
    sourceUrl: "https://www.2ser.com/how-to-submit-music",
    sourceType: "automation_run_152_public_research",
    country: "Australia / Sydney community radio station with public airplay-consideration form",
    language: "en",
    genres: ["community-radio", "airplay", "public-form", "independent", "electronic", "alternative", "world", "artist-bio", "manual-review"],
    submissionMethod: "official-2ser-airplay-consideration-public-form-route",
    feeRequired: false,
    feeAmount: "No submission fee observed for the public airplay-consideration form.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because the 2SER form asks for personal/contact fields, location, release date, artist/band name, release title, artist bio and social links; the form must be completed only by the owner with correct release context.",
    notes: "Public research verified 2SER's official How to Submit Music page and public airplay-consideration form. The site showed 2026 music content and active on-demand programming. No form was submitted, no contact data was entered and no track/release package was delivered."
  },
  ...run153SeedPlatforms
];
