import type { PlatformInput } from '../models/types.js';

export const run172BaseSeedPlatforms: PlatformInput[] = [
  {
    name: "RouteNote Free Premium Global Music Distribution Upload Route",
    websiteUrl: "https://routenote.com/",
    submissionUrl: "https://routenote.com/",
    sourceUrl: "https://routenote.com/",
    sourceType: "automation_run_172_public_research",
    country: "United Kingdom / global digital music distribution route with free and premium release models",
    language: "en",
    genres: ["digital-distribution", "independent-artists", "spotify", "apple-music", "global-stores", "free-plan", "premium-plan", "release-upload", "dashboard-boundary", "manual-review"],
    submissionMethod: "official-routenote-free-premium-global-music-distribution-upload-route",
    feeRequired: false,
    feeAmount: "Official RouteNote page advertises a FREE service and a Premium service; payment-model selection must be reviewed before use.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because release upload, account creation, store selection, free-versus-premium revenue model, rights ownership, metadata, artwork and takedown/account terms must be reviewed before submitting.",
    notes: "Public research verified RouteNote's official active site, global distribution to Spotify/Apple Music and more, FREE/Premium model language, partner-platform reach and Get Started route. No account was created, no dashboard workflow was entered, no files were uploaded and no release was configured."
  },
  {
    name: "Amuse Paid Web Mobile Distribution Artist Services Route",
    websiteUrl: "https://www.amuse.io/",
    submissionUrl: "https://artist.amuse.io/",
    sourceUrl: "https://www.amuse.io/",
    sourceType: "automation_run_172_public_research",
    country: "Sweden / global self-service music distribution and selective artist-label-services route",
    language: "en",
    genres: ["digital-distribution", "independent-artists", "mobile-app", "web-dashboard", "major-streaming-services", "artist-services", "paid-plan", "royalties", "dashboard-boundary", "manual-review"],
    submissionMethod: "official-amuse-paid-web-mobile-distribution-artist-services-route",
    feeRequired: true,
    feeAmount: "Official Amuse page states distribution starts from $23.99/year / $1.99 per month; plan and terms require manual review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Amuse requires account/app access, paid plan selection, release metadata, rights confirmation, royalty/payout settings and possible artist-label-services consideration.",
    notes: "Public research verified Amuse's official active site, Sign In/Get Started app boundary, distribution navigation, major streaming/social network distribution, keep-100%-royalties claim, pricing language and 2026 newsroom activity. No sign-in or app workflow was used."
  },
  {
    name: "TuneCore Paid Unlimited Global Distribution Accelerator Route",
    websiteUrl: "https://www.tunecore.com/",
    submissionUrl: "https://web.tunecore.com/",
    sourceUrl: "https://www.tunecore.com/",
    sourceType: "automation_run_172_public_research",
    country: "United States / global paid independent music distribution, publishing and artist-growth dashboard route",
    language: "en",
    genres: ["digital-distribution", "independent-artists", "spotify", "apple-music", "tiktok", "youtube", "beatport", "publishing", "accelerator", "paid-plan", "dashboard-boundary", "manual-review"],
    submissionMethod: "official-tunecore-paid-unlimited-global-distribution-accelerator-route",
    feeRequired: true,
    feeAmount: "Official TuneCore page states unlimited releases starting at $24.99/year; pricing and plan scope require manual review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because TuneCore requires sign-up/dashboard use, paid plan selection, release upload, store selection, publishing/accelerator choices, cover-art/metadata, rights and payment review.",
    notes: "Public research verified TuneCore's official active site, digital distribution service, 150+ stores, Spotify/Apple/TikTok/YouTube/Tidal/Tencent/Beatport reach, Sign Up/Login/Dashboard routes, ownership language and annual pricing. No account, payment or upload was initiated."
  },
  {
    name: "Ditto Music Paid Unlimited Distribution Playlist Sync Pitching Route",
    websiteUrl: "https://dittomusic.com/",
    submissionUrl: "https://login.dittomusic.com/",
    sourceUrl: "https://dittomusic.com/",
    sourceType: "automation_run_172_public_research",
    country: "United Kingdom / global paid music distribution, playlist pitching, publishing and sync route",
    language: "en",
    genres: ["digital-distribution", "independent-artists", "spotify", "apple-music", "tiktok", "beatport", "playlist-pitching", "sync-licensing", "publishing", "paid-plan", "dashboard-boundary", "manual-review"],
    submissionMethod: "official-ditto-music-paid-unlimited-distribution-playlist-sync-pitching-route",
    feeRequired: true,
    feeAmount: "Official Ditto page lists Starter pricing at $19/year, Pro at $59/year and Label pricing at $109/year; plan selection requires manual review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Ditto requires sign-up/login, plan choice, release upload, artist/store setup, playlist/sync/publishing options, royalties, rights and any trial/payment terms review.",
    notes: "Public research verified Ditto's official active site, free sign-up form boundary, distribution to 150+ platforms, unlimited release claims, playlist pitching, publishing/sync routes, Trustpilot/date activity on the page and pricing tiers. No form was submitted and no account was created."
  },
  {
    name: "Soundrop Free Account Per Track Distribution Cover Licensing Route",
    websiteUrl: "https://soundrop.com/",
    submissionUrl: "https://app.soundrop.com/",
    sourceUrl: "https://soundrop.com/",
    sourceType: "automation_run_172_public_research",
    country: "United States / global creator distribution, collaborator splits and cover-song licensing route",
    language: "en",
    genres: ["digital-distribution", "creator-platform", "spotify", "apple-music", "youtube-music", "deezer", "pandora", "tiktok", "cover-song-licensing", "collaborator-splits", "per-track-fee", "dashboard-boundary", "manual-review"],
    submissionMethod: "official-soundrop-free-account-per-track-distribution-cover-licensing-route",
    feeRequired: true,
    feeAmount: "Official Soundrop page says free account sign-up is available, but distribution costs $4.99 per song plus 15% of revenue; payment/royalty terms require review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Soundrop requires app sign-up/login, per-track distribution payment, 15% revenue-share review, cover-song licensing decisions, collaborator split configuration, metadata and rights validation.",
    notes: "Public research verified Soundrop's official active site, Sign Up Free/Login app boundary, distribution to Spotify/Apple/YouTube Music/Deezer/Pandora/Instagram/TikTok, collaborator splits, cover-song licensing, monthly reporting and per-track pricing. No app workflow or upload was entered."
  }
];
