import type { PlatformInput } from '../models/types.js';
import { run129SeedPlatforms } from './run129PlatformSeeds.js';

export const run128SeedPlatforms: PlatformInput[] = [
  {
    name: "KALX Berkeley Physical CD LP Music Director Airplay Submission Route",
    websiteUrl: "https://kalx.berkeley.edu/",
    submissionUrl: "mailto:music@kalx.berkeley.edu",
    sourceUrl: "https://kalx.berkeley.edu/about/contact/",
    sourceType: "automation_run_128_public_research",
    country: "US / Berkeley college and community radio physical-only airplay submission route",
    language: "en",
    genres: ["kalx", "college-radio", "community-radio", "airplay", "music-director", "physical-submission", "professionally-pressed-cd", "lp", "no-digital-submissions", "manual-review"],
    submissionMethod: "official-kalx-berkeley-physical-cd-lp-music-director-airplay-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KALX only accepts physical professionally pressed CDs or LPs for airplay consideration and explicitly rejects downloads, file transfers, Bandcamp, Spotify, YouTube, CD-R and other digital-only routes. Physical packaging, format choice, mailing, metadata and follow-up contact must remain owner-controlled.",
    notes: "Official public research confirmed KALX publishes Music Director contact details and music-submission instructions, including physical-only CD/LP routing and no digital submissions. No email was sent, no package was prepared and no physical mail was sent."
  },
  {
    name: "Radio K KUOM Physical Digital Music Department Airplay Submission Route",
    websiteUrl: "https://radiok.org/",
    submissionUrl: "https://radiok.org/submitting-music",
    sourceUrl: "https://radiok.org/submitting-music",
    sourceType: "automation_run_128_public_research",
    country: "US / Minnesota college radio physical and digital airplay submission route",
    language: "en",
    genres: ["radio-k", "kuom", "college-radio", "independent-music", "airplay", "music-department", "physical-submission", "digital-download-link", "wav", "flac", "manual-review"],
    submissionMethod: "official-radio-k-kuom-physical-digital-music-department-airplay-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Radio K supports physical and digital submissions but requires a music-department-directed package with download links, preferred lossless files, one-sheet context, FCC-friendly track guidance and release-fit review. Email/link delivery and any physical mail must remain owner-reviewed.",
    notes: "Official public research confirmed Radio K is active in 2026, publishes a Submitting Music route, accepts physical submissions and digital links through its music department, prefers lossless WAV or FLAC files, accepts Bandcamp download codes or free download links, and asks for simple one-sheet and FCC-friendly guidance. No contact was decoded, no email was sent and no link or file was delivered."
  },
  {
    name: "WXYC UNC Freeform Music Department Contact and Mailing Route",
    websiteUrl: "https://wxyc.org/",
    submissionUrl: "mailto:info@wxyc.org",
    sourceUrl: "https://wxyc.org/",
    sourceType: "automation_run_128_public_research",
    country: "US / North Carolina student-run freeform radio music department contact route",
    language: "en",
    genres: ["wxyc", "unc", "college-radio", "freeform-radio", "music-department", "mailing-route", "local-artists", "experimental", "world", "manual-review"],
    submissionMethod: "official-wxyc-unc-freeform-music-department-contact-and-mailing-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WXYC exposes a public station contact email and Music Department mailing address, but no complete safe auto-submit form was observed. Contact purpose, package format, pitch copy, music fit and any mailing or link delivery must remain owner-reviewed.",
    notes: "Official public research confirmed WXYC is an active UNC-Chapel Hill student-run freeform station with current 2026 programming/news, a public station contact route and a Music Department mailing address. No email was sent, no link or file was delivered and no physical package was prepared or mailed."
  },
  {
    name: "WREK Atlanta Snail Mail Email Music Director Submission Route",
    websiteUrl: "https://www.wrek.org/",
    submissionUrl: "mailto:music.director@wrek.org",
    sourceUrl: "https://old.wrek.org/submissions/",
    sourceType: "automation_run_128_public_research",
    country: "US / Atlanta Georgia Tech college radio snail-mail and email music submission route",
    language: "en",
    genres: ["wrek", "college-radio", "georgia-tech", "freeform", "music-director", "snail-mail", "email-route", "cd", "lp", "cassette", "experimental", "electronic", "reggae", "world", "manual-review"],
    submissionMethod: "official-wrek-atlanta-snail-mail-email-music-director-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WREK supports snail-mail and email submissions, gives CDs and LPs better airplay odds, does not acknowledge receipt due to volume and reviews music through Music Director workflows. Format choice, package prep, email/link delivery, label metadata and follow-up timing must remain manual.",
    notes: "Official public research confirmed WREK is active in 2026 and links to a public How To Submit Music page stating music may be submitted by snail mail or to the Music Director email route, with CDs and LPs having better chances of airplay. No email was sent, no package was prepared and no physical mail was sent."
  },
  {
    name: "WRAS Album 88 Regular Rotation Local Underground Music Submission Route",
    websiteUrl: "https://www.wrasfm.org/",
    submissionUrl: "mailto:WRASMD@gmail.com",
    sourceUrl: "https://www.wrasfm.org/contact",
    sourceType: "automation_run_128_public_research",
    country: "US / Atlanta student-run radio regular-rotation local and underground music submission route",
    language: "en",
    genres: ["wras", "album-88", "college-radio", "student-radio", "regular-rotation", "local-atlanta", "underground-music", "rpm", "urban", "specialty-programming", "manual-review"],
    submissionMethod: "official-wras-album-88-regular-rotation-local-underground-music-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WRAS exposes Regular Rotation and specialty-programming contact routes and asks for local Atlanta or generally underground music released in the past four months. Release date, format, fit, department choice, pitch copy and any email/link delivery must remain owner-reviewed.",
    notes: "Official public research confirmed WRAS Album 88 is active, publishes current rotation and schedule routes, lists Regular Rotation music contacts and asks for local Atlanta or generally underground music released in the past four months. No email was sent, no link or file was delivered and no form was submitted."
  },
  ...run129SeedPlatforms
];
