import type { PlatformInput } from '../models/types.js';

export const run185BaseSeedPlatforms: PlatformInput[] = [
  {
    name: "WXDU Duke Bandcamp YUM Code Airplay Submission Route",
    websiteUrl: "https://www.wxdu.org/",
    submissionUrl: "https://www.wxdu.org/contact.html",
    sourceUrl: "https://www.wxdu.org/contact.html",
    sourceType: "automation_run_185_public_research",
    country: "United States / Durham Duke noncommercial college-radio airplay route",
    language: "en",
    genres: ["college-radio", "progressive-alternative", "electronic", "rpm", "world", "reggae", "latin", "independent-music", "bandcamp-yum", "music-director-email", "manual-review"],
    submissionMethod: "official-wxdu-bandcamp-yum-code-airplay-submission-route",
    feeRequired: false,
    feeAmount: "Free-first WXDU airplay route; Bandcamp YUM codes are preferred over other downloads, and public music email/genre-director routing requires manual review.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WXDU asks senders to use Bandcamp YUM codes or other download routes through a public music email. Approved link permissions, clean/radio-edit status, metadata, genre/RPM/world fit and sender identity must be checked before outreach.",
    notes: "Official WXDU contact page says Bandcamp YUM codes are preferred for airplay submissions and lists a public music submission email. No message, download code or file transfer was sent."
  },
  {
    name: "WESU Middletown Music Directors Link Submission Route",
    websiteUrl: "https://www.wesufm.org/",
    submissionUrl: "https://www.wesufm.org/contact-us/",
    sourceUrl: "https://www.wesufm.org/contact-us/",
    sourceType: "automation_run_185_public_research",
    country: "United States / Middletown Wesleyan college-community radio link-submission route",
    language: "en",
    genres: ["college-radio", "community-radio", "freeform-radio", "electronic", "reggae", "world", "hip-hop", "streaming-link", "cloud-link", "music-director-email", "manual-review"],
    submissionMethod: "official-wesu-music-directors-link-submission-route",
    feeRequired: false,
    feeAmount: "Free-first WESU Music Directors email route; links are requested and direct files are discouraged, requiring manual review of share permissions and metadata.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WESU explicitly asks music submitters to contact Music Directors and send links rather than files. Link access, appropriate streaming/download route, clean edit status, metadata, rights, and personalized wording need approval before contact.",
    notes: "Official WESU contact page lists a public Music Directors email and says music submitters should send links such as Dropbox, Google Drive, Spotify, Apple Music or other streaming platforms. No message or link was sent."
  },
  {
    name: "WNCW Programming Department CD WAV MP3 Airplay Submission Route",
    websiteUrl: "https://www.wncw.org/",
    submissionUrl: "https://www.wncw.org/submit-music",
    sourceUrl: "https://www.wncw.org/submit-music",
    sourceType: "automation_run_185_public_research",
    country: "United States / Western North Carolina AAA public-radio programming route",
    language: "en",
    genres: ["public-radio", "aaa", "americana", "folk", "blues", "jazz", "reggae", "world", "rock", "independent-music", "cd", "wav", "mp3", "manual-review"],
    submissionMethod: "official-wncw-programming-department-cd-wav-mp3-airplay-submission-route",
    feeRequired: false,
    feeAmount: "Free-first WNCW Programming Department route accepting mailed CDs and wav/mp3 digital files by download service; album-oriented fit and one-sheet context require manual review.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WNCW prefers CDs but permits wav/mp3 digital submissions through common download services. CD versus digital route, Music Director email usage, one-sheet information, area-show relevance, album/single fit, clean edits and no-request-campaign guidance must be reviewed before outreach or transfer.",
    notes: "Official WNCW Submit Music page says CDs can be mailed to the Programming Department and digital wav/mp3 files can be delivered through common download services to the listed public contact. No message, transfer or physical package was prepared."
  },
  {
    name: "WPRK Rollins Community Radio Music Submissions Email Route",
    websiteUrl: "https://wprk.org/",
    submissionUrl: "https://wprk.org/music-submissions/",
    sourceUrl: "https://wprk.org/music-submissions/",
    sourceType: "automation_run_185_public_research",
    country: "United States / Winter Park Orlando college-community radio music submission route",
    language: "en",
    genres: ["college-radio", "community-radio", "local-music", "electronic", "edm", "reggae", "world", "hip-hop", "indie", "music-submission-email", "manual-review"],
    submissionMethod: "official-wprk-rollins-community-radio-music-submissions-email-route",
    feeRequired: false,
    feeAmount: "Free-first WPRK music-submissions email route; format, attachment/link preference and Orlando/college-radio fit require manual review.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WPRK publishes a public music-submissions email but does not expose a full technical spec for files, links or one-sheet metadata. Submission package, clean edit, genre/show fit, link permissions and wording must be approved before contact.",
    notes: "Official WPRK Music Submissions page asks artists to send submissions to the listed public music-submissions address. No message, file or link was sent."
  },
  {
    name: "WXYC UNC Music Department Postal Contact Route",
    websiteUrl: "https://www.wxyc.org/",
    submissionUrl: "https://www.wxyc.org/",
    sourceUrl: "https://www.wxyc.org/",
    sourceType: "automation_run_185_public_research",
    country: "United States / Chapel Hill UNC freeform college-radio music-department route",
    language: "en",
    genres: ["college-radio", "freeform-radio", "electronic", "reggae", "world", "hip-hop", "local-music", "experimental", "music-department-postal", "manual-review"],
    submissionMethod: "official-wxyc-music-department-postal-contact-route",
    feeRequired: false,
    feeAmount: "Free-first WXYC Music Department contact route; official site lists a music department postal address and general contact email, but exact submission package requirements require manual review.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WXYC exposes a Music Department postal route and general contact email but does not provide complete public digital submission rules on the fetched page. Physical package choice, general email appropriateness, local/freeform fit, metadata, clean edits and no-bulk outreach must be reviewed before any contact or mailing.",
    notes: "Official WXYC homepage lists a general contact email and a WXYC Music Department postal address at UNC-Chapel Hill, with active artist-interview/blog and playlist context. No message or physical package was prepared."
  }
];
