import type { PlatformInput } from '../models/types.js';

export const run105SeedPlatforms: PlatformInput[] = [
  {
    name: "Radio Milwaukee 88Nine Music Submission Route",
    websiteUrl: "https://radiomilwaukee.org/",
    submissionUrl: "https://radiomilwaukee.org/music-submission",
    sourceUrl: "https://radiomilwaukee.org/music-submission",
    sourceType: "automation_run_105_public_research",
    country: "United States / Milwaukee public independent music radio",
    language: "en",
    genres: ["radio-milwaukee", "88nine", "public-radio", "independent-radio", "local-music", "new-music", "studio-sessions", "aaa", "electronic-adjacent", "world", "hip-hop", "r-and-b", "public-submission-page", "free-first", "no-physical-media", "manual-review"],
    submissionMethod: "official-radio-milwaukee-88nine-music-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Radio Milwaukee asks for uncompressed mixed/mastered audio, radio edits, full lyrics, bio, song notes, upcoming album/live-show details and helpful links, while the fetched page exposes a public instruction route rather than a safe complete auto-submit endpoint.",
    notes: "Public research confirmed Radio Milwaukee's official 88Nine site is active in 2026 and includes a Music Submission route. The submission page asks for uncompressed audio with WAV preferred, radio edits, no physical media, an informational document, lyrics, bio, comments, upcoming album/live-show details and artist links, and says the station listens to received music but cannot guarantee airplay or feedback. No form was submitted, no files or links were delivered, no email was sent and no SMTP/MX probing was performed."
  },
  {
    name: "WFUV Music Department Snail Mail Submission Route",
    websiteUrl: "https://wfuv.org/",
    submissionUrl: "https://wfuv.org/contactus",
    sourceUrl: "https://wfuv.org/contactus",
    sourceType: "automation_run_105_public_research",
    country: "United States / New York public music discovery radio",
    language: "en",
    genres: ["wfuv", "public-radio", "music-discovery", "aaa", "independent-music", "new-york", "snail-mail", "music-department", "physical-package", "free-first", "manual-review"],
    submissionMethod: "official-wfuv-music-department-snail-mail-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WFUV routes music through snail mail to its Music Department. Physical package preparation, correct addressing, release metadata, clean/radio-fit checks and follow-up timing must be handled manually.",
    notes: "Public research confirmed WFUV presents itself as New York's Music Discovery and its official Contact & Staff page lists the Fordham University address plus a Send Music instruction to snail mail the Music Department at that address, with follow-up calls only during a specified Wednesday window. No email links were decoded, no physical mail was sent, no follow-up call was placed and no SMTP/MX probing was performed."
  },
  {
    name: "WNRN Music Submissions Email and Commonwealth Artist Route",
    websiteUrl: "https://wnrn.org/",
    submissionUrl: "https://wnrn.org/about/contact/",
    sourceUrl: "https://wnrn.org/about/contact/",
    sourceType: "automation_run_105_public_research",
    country: "United States / Virginia listener-supported independent music radio",
    language: "en",
    genres: ["wnrn", "independent-music-radio", "public-radio", "aaa", "world-cafe", "alt-latino", "fresh-roots", "local-music", "commonwealth-artist", "public-email", "public-form-side-route", "free-first", "manual-review"],
    submissionMethod: "official-wnrn-music-submissions-email-and-commonwealth-artist-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WNRN asks artists to email an album for airplay consideration and provides a separate Commonwealth artist submission route. Album fit, local/Commonwealth eligibility, metadata, clean edits, link permissions and pitch copy need manual review.",
    notes: "Public research confirmed WNRN is an active listener-supported independent music radio network with 2026 site activity and a Contact page listing Music Submissions instructions. The page states artists can submit an album for airplay consideration by emailing music@wnrn.org and points Commonwealth artists to a separate submission route. No email was sent, no form was opened or submitted, no files or links were delivered and no SMTP/MX probing was performed."
  },
  {
    name: "WERS Wicked Local Wednesday Music Submission Form Route",
    websiteUrl: "https://wers.org/",
    submissionUrl: "https://wers.org/wicked-local-wednesday/",
    sourceUrl: "https://wers.org/wicked-local-wednesday/",
    sourceType: "automation_run_105_public_research",
    country: "United States / Boston noncommercial college and public music radio",
    language: "en",
    genres: ["wers", "boston", "college-radio", "noncommercial-radio", "local-music", "wicked-local-wednesday", "music-discovery", "live-performance", "mp3-upload", "public-form", "recaptcha-site-boundary", "free-first", "manual-review"],
    submissionMethod: "official-wers-wicked-local-wednesday-music-submission-form-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WERS exposes a public local-artist music form with required artist/contact/location fields and MP3 file upload, and the site declares reCAPTCHA protection. Local eligibility, upload handling, rights, metadata and CAPTCHA/session boundaries require manual review.",
    notes: "Public research confirmed WERS is active in 2026, identifies a Submit Music route under its Music navigation and hosts the Wicked Local Wednesday page for Boston-area artists. The page asks local bands to fill out a form and exposes fields for local artist/band name, artist information, website, location, contact name, email, phone and MP3 file upload with a 39 MB max size, while the site declares reCAPTCHA protection. No form was submitted, no CAPTCHA was interacted with, no files were uploaded and no SMTP/MX probing was performed."
  },
  {
    name: "WYEP Pittsburgh Area Music Submissions Email and Mail Route",
    websiteUrl: "https://www.wyep.org/",
    submissionUrl: "https://www.wyep.org/wyep-pittsburgh-area-music-submissions",
    sourceUrl: "https://www.wyep.org/wyep-pittsburgh-area-music-submissions",
    sourceType: "automation_run_105_public_research",
    country: "United States / Pittsburgh independent public music station",
    language: "en",
    genres: ["wyep", "pittsburgh", "public-radio", "independent-music", "local-913", "pittsburgh-music-hour", "aaa", "local-music", "public-email", "physical-mail", "specialty-show-routing", "fcc-clean", "free-first", "manual-review"],
    submissionMethod: "official-wyep-pittsburgh-area-music-submissions-email-and-mail-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WYEP focuses this route on Pittsburgh-area musicians, asks for links or hard-copy mail, requires contact/location context, suggests album track picks and requires FCC-clean suitability. Regional fit, specialty-show routing, metadata, link permissions and clean-edit checks need manual handling.",
    notes: "Public research confirmed WYEP is active in 2026 and its Pittsburgh Area Music Submissions page states WYEP supports local musicians through Local 913, Pittsburgh Music Hour and station events. It instructs artists to email a music link or mail a hard copy, include contact information and origin details, suggest 2-3 tracks for albums, review specialty-show fit, and keep submissions FCC-clean. No email was sent, no physical package was mailed, no host contacts were used and no SMTP/MX probing was performed."
  }
];
