import type { PlatformInput } from '../models/types.js';
import { run125SeedPlatforms } from './run125PlatformSeeds.js';

export const run124SeedPlatforms: PlatformInput[] = [
  {
    name: "Sonicbids Rebooted EPK Live Booking and Venue Submission Route",
    websiteUrl: "https://sonicbids.com/",
    submissionUrl: "https://app.sonicbids.com/signup",
    sourceUrl: "https://sonicbids.com/",
    sourceType: "automation_run_124_public_research",
    country: "Global / live booking EPK venue submission and artist opportunity route",
    language: "en",
    genres: ["sonicbids", "epk", "live-booking", "venues", "festival-opportunities", "artist-profile", "booking-submissions", "login", "unknown-pricing", "manual-review"],
    submissionMethod: "official-sonicbids-rebooted-epk-live-booking-venue-submission-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Account sign-up, EPK setup, profile data and booking workflow choices require owner review.",
    notes: "Run 124 official public route retained and aggregated. No account, upload, application or payment action was performed."
  },
  {
    name: "Syncr Music Brand Brief Upload Submit and Sync Opportunity Route",
    websiteUrl: "https://www.syncrmusic.com/",
    submissionUrl: "https://www.syncrmusic.com/",
    sourceUrl: "https://www.syncrmusic.com/",
    sourceType: "automation_run_124_public_research",
    country: "Global / brand brief sync playlist gig radio interview and publishing opportunity route",
    language: "en",
    genres: ["syncr", "sync-briefs", "brand-briefs", "upload-tracks", "submit-to-briefs", "playlisting", "radio-play", "publishing", "free-first", "login", "manual-review"],
    submissionMethod: "official-syncr-music-brand-brief-upload-submit-sync-opportunity-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Account access, track upload, brief fit, rights data and licensing terms require owner review.",
    notes: "Run 124 official public route retained and aggregated. No account, upload, brief submission or payment action was performed."
  },
  {
    name: "Feature.fm Artist Smart Link Pre-Save Fan Activation and Campaign Route",
    websiteUrl: "https://feature.fm/",
    submissionUrl: "https://feature.fm/",
    sourceUrl: "https://feature.fm/",
    sourceType: "automation_run_124_public_research",
    country: "Global / independent artist smart-link pre-save fan activation and music marketing route",
    language: "en",
    genres: ["feature-fm", "music-marketing", "smart-links", "pre-save", "release-links", "artist-bio-links", "analytics", "free-first", "login", "manual-review"],
    submissionMethod: "official-feature-fm-artist-smart-link-presave-fan-activation-campaign-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Account access, link setup, pre-save choices, analytics and campaign publication require owner review.",
    notes: "Run 124 official public route retained and aggregated. No account, link or campaign action was performed."
  },
  {
    name: "DISCO Artist Catalog Share Receive Track and Supervisor Pitch Route",
    websiteUrl: "https://www.disco.ac/",
    submissionUrl: "https://www.disco.ac/",
    sourceUrl: "https://www.disco.ac/",
    sourceType: "automation_run_124_public_research",
    country: "Global / artist catalog sharing pitching music supervisor and promotion workflow route",
    language: "en",
    genres: ["disco", "catalog-management", "music-supervisors", "rights-holders", "artists-creators", "marketing-promotions", "share-receive-track", "sync-pitching", "free-trial", "login", "manual-review"],
    submissionMethod: "official-disco-artist-catalog-share-receive-track-supervisor-pitch-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Account access, catalog upload, permissions, pitch links and recipient targeting require owner review.",
    notes: "Run 124 official public route retained and aggregated. No trial, catalog upload or pitch action was performed."
  },
  {
    name: "TopHit Radio TV Music Distribution Airplay Testing and Chart Route",
    websiteUrl: "https://tophit.com/",
    submissionUrl: "https://tophit.com/",
    sourceUrl: "https://tophit.com/",
    sourceType: "automation_run_124_public_research",
    country: "Global / radio television digital music distribution airplay testing and chart-monitoring route",
    language: "en",
    genres: ["tophit", "radio-distribution", "tv-channels", "airplay-testing", "charts", "music-arrivals", "rights-holders", "labels", "djs", "upload", "login", "manual-review"],
    submissionMethod: "official-tophit-radio-tv-music-distribution-airplay-testing-chart-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Registration, media upload, territory fit, clean edits and platform terms require owner review.",
    notes: "Run 124 official public route retained and aggregated. No registration, media upload or delivery action was performed."
  },
  ...run125SeedPlatforms
];
