import type { PlatformInput } from '../models/types.js';

export const run160SeedPlatforms: PlatformInput[] = [
  {
    name: "KALX Berkeley Physical CD LP Music Director Airplay Submission Route",
    websiteUrl: "https://kalx.berkeley.edu/",
    submissionUrl: "https://kalx.berkeley.edu/about/contact/",
    sourceUrl: "https://kalx.berkeley.edu/about/contact/",
    sourceType: "automation_run_160_public_research",
    country: "United States / Berkeley college-community radio with San Francisco Bay Area and online reach",
    language: "en",
    genres: ["college-radio", "community-radio", "bay-area", "eclectic", "electronic", "world", "reggae", "hip-hop", "physical-submission", "music-director-email", "manual-review"],
    submissionMethod: "official-kalx-physical-cd-lp-music-director-airplay-submission-route",
    feeRequired: false,
    feeAmount: "No submission fee observed; official KALX guidance accepts only physical professionally pressed CDs or LPs for airplay and explicitly excludes downloads, file transfers, Bandcamp, Spotify, YouTube, CD-Rs and digital submissions.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KALX is physical-media-only for airplay consideration; owner must verify format, professional pressing, no digital-link use, release fit, clean/FCC notes, one-sheet and mailing choice before any contact or package action.",
    notes: "Public research verified the official KALX site, current July 2026 programming and coming-attractions activity, Music Directors contact, music@kalx.berkeley.edu route, physical-only submission requirements and digital/attachment exclusions. No email was sent, no attachments or links were delivered and no physical package was prepared or mailed."
  },
  {
    name: "WPRB Princeton Physical Priority Music Director Submission Route",
    websiteUrl: "https://wprb.com/",
    submissionUrl: "https://wprb.com/music-submissions/",
    sourceUrl: "https://wprb.com/music-submissions/",
    sourceType: "automation_run_160_public_research",
    country: "United States / Princeton freeform independent college radio with online streaming",
    language: "en",
    genres: ["freeform-radio", "college-radio", "independent", "electronic", "hip-hop", "reggae", "world", "experimental", "physical-priority", "music-director-email", "manual-review"],
    submissionMethod: "official-wprb-physical-priority-music-director-submission-route",
    feeRequired: false,
    feeAmount: "No submission fee observed; official route accepts CDs, CD-Rs, LPs, 12-inch, 10-inch and 7-inch releases to the Music Director, with an email side route to music@wprb.com but physical submissions prioritized.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WPRB prioritizes physical submissions, uses an email side route, and the owner must choose physical vs email servicing, verify file/link policy, genre fit, one-sheet, clean/explicit notes and release metadata before any outreach.",
    notes: "Public research verified WPRB's official homepage activity, Music Submissions page, Music Director postal route, music@wprb.com route and 2026 footer context. No email was sent, no links/files were delivered and no physical package was prepared or mailed."
  },
  {
    name: "WNYU 89.1FM Physical Priority Digital Music Director Submission Route",
    websiteUrl: "https://wnyu.org/",
    submissionUrl: "https://wnyu.org/about/",
    sourceUrl: "https://wnyu.org/about/",
    sourceType: "automation_run_160_public_research",
    country: "United States / New York University student-run radio broadcasting on 89.1 FM and 24/7 online",
    language: "en",
    genres: ["college-radio", "new-york", "independent", "electronic", "world", "reggae", "hip-hop", "experimental", "physical-priority", "digital-side-route", "manual-review"],
    submissionMethod: "official-wnyu-physical-priority-digital-music-director-submission-route",
    feeRequired: false,
    feeAmount: "No submission fee observed; official WNYU guidance asks artists to send physical CDs, CD-Rs, LPs, 12-inch, 10-inch and 7-inch releases, with digital submissions to music@wnyu.org but physical submissions prioritized.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WNYU prioritizes physical mail while permitting digital submissions, and the owner must verify release format, digital package, clean/explicit notes, show fit, one-sheet and whether a physical package is worthwhile.",
    notes: "Public research verified WNYU's official site, station identity, 89.1 FM weekday and 24/7 internet broadcast context, Send Us Music route, physical-format requirements and public Music Director email. No email was sent, no links/files were delivered and no physical package was prepared or mailed."
  },
  {
    name: "WZBC Boston College Rock NCP Specialty Music Director Contact Route",
    websiteUrl: "https://www.wzbc.org/",
    submissionUrl: "https://www.wzbc.org/contact.html",
    sourceUrl: "https://www.wzbc.org/contact.html",
    sourceType: "automation_run_160_public_research",
    country: "United States / Boston College student-run radio station serving Newton and online listeners",
    language: "en",
    genres: ["college-radio", "boston", "rock", "ncp", "specialty", "electronic", "experimental", "hip-hop", "music-director-email", "manual-review"],
    submissionMethod: "official-wzbc-rock-ncp-specialty-music-director-contact-route",
    feeRequired: false,
    feeAmount: "No submission fee observed; official contact route lists Rock Music Directors, NCP Music Director and Specialty Music Director email contacts for public music-director routing.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WZBC exposes multiple department-specific music-director contacts rather than a single upload form; the owner must choose Rock, NCP or Specialty routing, verify genre fit, clean/explicit notes, release metadata and pitch copy before contact.",
    notes: "Public research verified WZBC's official site, current playlist/schedule context, Boston College student-run station identity, public contact page and department music-director emails including rock, NCP and specialty routes. No email was sent, no links/files were delivered and no account or form workflow was used."
  },
  {
    name: "WRAS Album 88 Regular Rotation Underground Music Department Submission Route",
    websiteUrl: "https://wras.org/",
    submissionUrl: "https://wras.org/contact/",
    sourceUrl: "https://wras.org/contact/",
    sourceType: "automation_run_160_public_research",
    country: "United States / Atlanta student-run Georgia State University radio station",
    language: "en",
    genres: ["college-radio", "atlanta", "underground", "rpm", "urban", "electronic", "hip-hop", "local-music", "music-director-email", "manual-review"],
    submissionMethod: "official-wras-album-88-regular-rotation-underground-music-department-submission-route",
    feeRequired: false,
    feeAmount: "No submission fee observed; official contact guidance routes regular-rotation submissions to WRAS music department emails for general, RPM and Urban consideration, especially local Atlanta or generally underground music released in the past four months.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WRAS asks for routing by format/department, emphasizes local Atlanta or underground fit and recent releases, and requires the owner to verify release date, department fit, clean/explicit notes, metadata and pitch copy before outreach.",
    notes: "Public research verified WRAS Album 88 official site activity, schedule/rotation context, Georgia State student-run station identity, contact page and regular-rotation music department routes including WRASMD, WRASRPMMD and WRASUrbanMD. No email was sent, no links/files were delivered and no payment or account workflow was used."
  }
];
