import type { PlatformInput } from '../models/types.js';

export const run173BaseSeedPlatforms: PlatformInput[] = [
  {
    name: "KCSB Santa Barbara Music Director All Formats Artist Inquiry Route",
    websiteUrl: "https://www.kcsb.org/",
    submissionUrl: "https://www.kcsb.org/contact/",
    sourceUrl: "https://www.kcsb.org/contact/",
    sourceType: "automation_run_173_public_research",
    country: "United States / Santa Barbara college-community radio music director route with all-formats acceptance and artist inquiry path",
    language: "en",
    genres: ["college-radio", "community-radio", "freeform-radio", "all-genres", "demos", "new-releases", "artist-inquiry", "physical-package", "email-route", "manual-review"],
    submissionMethod: "official-kcsb-santa-barbara-music-director-all-formats-artist-inquiry-route",
    feeRequired: false,
    feeAmount: "No submission fee observed on the official KCSB public music-submission route.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KCSB accepts new releases and demos in all formats, but the correct package format, clean/explicit notes, artist inquiry fit, one-sheet, download links and physical routing must be prepared before contact.",
    notes: "Public research verified KCSB's official contact page, Music Director route, public music-submission email, message form with Music submission option, physical mailing addresses and 2026 site footer. No message was sent, no form was submitted and no package was prepared."
  },
  {
    name: "CD Baby Paid Digital Distribution Human Review Dashboard Route",
    websiteUrl: "https://cdbaby.com/",
    submissionUrl: "https://cdbaby.com/music-distribution/",
    sourceUrl: "https://cdbaby.com/music-distribution/",
    sourceType: "automation_run_173_public_research",
    country: "United States / global independent digital distribution route for major DSPs and promotion tools",
    language: "en",
    genres: ["digital-distribution", "independent-artists", "spotify", "apple-music", "tiktok", "youtube-music", "cover-song-licensing", "release-dashboard", "paid-per-release", "manual-review"],
    submissionMethod: "official-cd-baby-paid-digital-distribution-human-review-dashboard-route",
    feeRequired: true,
    feeAmount: "Official CD Baby page lists one-time per-release pricing starting at $9.99 for singles and $14.99 for albums; plan, rights and optional services require manual review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because CD Baby requires sign-up/dashboard use, paid per-release choice, audio/artwork upload, metadata, release date, barcode/store choices, cover-song licensing and rights validation before submission.",
    notes: "Public research verified CD Baby's official music distribution page, Get Started/Login dashboard boundary, distribution to 150+ partners, human inspection before delivery, pricing language, dashboard tools and rights-preparation guidance. No account, payment, upload or release setup was initiated."
  },
  {
    name: "LANDR Paid Unlimited Distribution Release Wizard Route",
    websiteUrl: "https://www.landr.com/",
    submissionUrl: "https://www.landr.com/digital-distribution",
    sourceUrl: "https://www.landr.com/digital-distribution",
    sourceType: "automation_run_173_public_research",
    country: "Canada / global paid distribution, mastering, promotion and release-wizard route",
    language: "en",
    genres: ["digital-distribution", "independent-artists", "spotify", "apple-music", "tiktok", "youtube", "release-wizard", "royalty-splits", "cover-song-licensing", "paid-plan", "dashboard-boundary", "manual-review"],
    submissionMethod: "official-landr-paid-unlimited-distribution-release-wizard-route",
    feeRequired: true,
    feeAmount: "Official LANDR distribution page states unlimited releases from as low as $24/year; subscription, rights and distribution terms require manual review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because LANDR requires app sign-up/login, subscription review, release-wizard setup, audio/artwork upload, metadata, royalty splits, cover-song licensing and store/platform decisions.",
    notes: "Public research verified LANDR's official distribution page, Release your music app boundary, 150+ stores/platforms, paid annual pricing, release wizard, royalty splits, metrics, Spotify for Artists access and cover-song licensing. No app workflow, payment or upload was entered."
  },
  {
    name: "UnitedMasters Debut Select Distribution Brand Sync Pitching Route",
    websiteUrl: "https://www.unitedmasters.com/",
    submissionUrl: "https://www.unitedmasters.com/",
    sourceUrl: "https://www.unitedmasters.com/",
    sourceType: "automation_run_173_public_research",
    country: "United States / global independent artist distribution, brand, sync and playlist-pitching route",
    language: "en",
    genres: ["digital-distribution", "independent-artists", "spotify", "apple-music", "tidal", "brand-deals", "sync-licensing", "playlist-pitching", "paid-plan", "freemium-social-route", "dashboard-boundary", "manual-review"],
    submissionMethod: "official-unitedmasters-debut-select-distribution-brand-sync-pitching-route",
    feeRequired: true,
    feeAmount: "Official UnitedMasters page lists Debut+ and Select yearly pricing and a social-only free option; plan scope, rights and pitching terms require manual review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because UnitedMasters requires sign-up/login, plan selection, release setup, master-rights confirmation, royalty/payout settings, brand/sync eligibility and playlist/editorial/radio pitching decisions.",
    notes: "Public research verified UnitedMasters' official active site, Sign Up/Login boundaries, Spotify/Apple Music/TIDAL distribution, 150+ music services, Debut+/Select/Partner tiers, brand/sync opportunities and playlist/editorial/radio pitching context. No account, payment or upload was initiated."
  },
  {
    name: "Horus Music Unlimited Artist Label Distribution Dashboard Route",
    websiteUrl: "https://www.horusmusic.global/",
    submissionUrl: "https://www.horusmusic.global/music-distribution/",
    sourceUrl: "https://www.horusmusic.global/music-distribution/",
    sourceType: "automation_run_173_public_research",
    country: "United Kingdom / global artist and label distribution dashboard route with marketing, radio and playlist side services",
    language: "en",
    genres: ["digital-distribution", "independent-artists", "labels", "spotify", "apple-music", "tiktok", "youtube-music", "royalty-splits", "playlist-pitching", "radio-promotion", "paid-plan", "dashboard-boundary", "manual-review"],
    submissionMethod: "official-horus-music-unlimited-artist-label-distribution-dashboard-route",
    feeRequired: true,
    feeAmount: "Official Horus Music page lists artist distribution at £20/year and label distribution from £30/year; subscription/payment terms require manual review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Horus Music requires account/dashboard use, paid artist or label plan choice, audio/artwork/metadata upload, platform selection, royalty splits, release-date planning and optional marketing/radio/playlist services review.",
    notes: "Public research verified Horus Music's official distribution page, Sign Up/Login dashboard boundary, artist and label annual pricing, unlimited releases, Spotify/Apple/TikTok/Instagram platform selection, quality-control review, royalty splits and side services. No account, payment, form submission or upload was initiated."
  }
];