import type { PlatformInput } from '../models/types.js';

export const run136SeedPlatforms: PlatformInput[] = [
  {
    name: "CJSW Digital Album Jotform and Campus Radio Mailout Submission Route",
    websiteUrl: "https://cjsw.com/",
    submissionUrl: "https://cjsw.com/music/submit/",
    sourceUrl: "https://cjsw.com/music/submit/",
    sourceType: "automation_run_136_public_research",
    country: "Canada / Calgary campus-community freeform station with digital album submission and Canadian campus-radio mailout side route",
    language: "en",
    genres: ["cjsw", "campus-radio", "community-radio", "digital-submission", "jotform", "mp3-zip", "recent-release", "no-singles", "reggae", "afrobeat", "electronic", "world", "hip-hop", "manual-review"],
    submissionMethod: "official-cjsw-digital-album-jotform-campus-radio-mailout-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because CJSW uses an external Jotform upload route, only accepts digital album releases from the last three months with three or more unique tracks, rejects singles, requires MP3 files in a ZIP, and has a separate paid/physical campus-radio mailout side route.",
    notes: "Official CJSW pages identify an active Music Submissions route, public upload guidance and a Music and Performance Director contact link. No Jotform was submitted, no mailing-list signup was made, no file/link was uploaded, no payment was initiated and no protected contact was decoded."
  },
  {
    name: "CKUT 90.3FM Physical and 320 MP3 Music Library Submission Route",
    websiteUrl: "https://ckut.ca/",
    submissionUrl: "https://ckut.ca/submit-music-to-ckut/",
    sourceUrl: "https://ckut.ca/submit-music-to-ckut/",
    sourceType: "automation_run_136_public_research",
    country: "Canada / Montreal campus-community radio station accepting global artist and record-company submissions",
    language: "en",
    genres: ["ckut", "campus-radio", "community-radio", "freeform", "physical-submission", "digital-submission", "320-mp3", "reggae", "afrobeat", "soca-dancehall", "electronic", "world", "hip-hop", "manual-review"],
    submissionMethod: "official-ckut-physical-320-mp3-music-library-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because CKUT accepts both physical and digital routes, rejects singles, requires at least three distinct tracks for most formats, and notes that many programmers prefer physical releases even though 320 MP3 digital submissions are accepted.",
    notes: "Official CKUT pages show active 2025 programming, a Submit Music route, physical mail guidance and an official public digital music submission address. No email was sent, no file/link was delivered, no package was prepared and no follow-up was initiated."
  },
  {
    name: "Monstercat LabelRadar Uncaged Instinct Silk Demo Submission Route",
    websiteUrl: "https://www.monstercat.com/",
    submissionUrl: "https://www.monstercat.com/contact-us",
    sourceUrl: "https://www.monstercat.com/contact-us",
    sourceType: "automation_run_136_public_research",
    country: "Canada / global electronic label with Uncaged, Instinct and Silk demo lanes through LabelRadar",
    language: "en",
    genres: ["monstercat", "label-demo", "labelradar", "electronic", "dubstep", "drum-and-bass", "future-bass", "progressive-house", "bass-music", "account-required", "protected-contact", "manual-review"],
    submissionMethod: "official-monstercat-labelradar-uncaged-instinct-silk-demo-submission-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Monstercat routes demos to external LabelRadar lanes, requires selecting the correct brand lane, submitting only best/original work, and respecting account/session, rights, track-link/upload and possible platform terms.",
    notes: "Official Monstercat pages show active 2026 releases, sign-in/sign-up boundaries, public Uncaged/Instinct/Silk LabelRadar demo links and general contact-form/business routes. No LabelRadar page was entered, no account was created, no login was used, no demo was uploaded and no protected contact was decoded."
  },
  {
    name: "NCS LabelRadar Demo Submission Electronic Creator Music Route",
    websiteUrl: "https://ncs.io/",
    submissionUrl: "https://ncs.io/contact",
    sourceUrl: "https://ncs.io/contact",
    sourceType: "automation_run_136_public_research",
    country: "United Kingdom / global electronic label and creator-music platform with official LabelRadar demo route",
    language: "en",
    genres: ["ncs", "nocopyrightsounds", "label-demo", "labelradar", "electronic", "edm", "dubstep", "drum-and-bass", "trap", "future-bass", "creator-music", "login-boundary", "manual-review"],
    submissionMethod: "official-ncs-labelradar-demo-submission-electronic-creator-music-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because NCS publishes an official LabelRadar demo-submission route, the NCS site exposes account/login boundaries, and demo submission requires owner-controlled rights, track selection, metadata, terms and external platform-session review.",
    notes: "Official NCS pages show an active music library with recent 2026 releases, broad electronic genre coverage, login/sign-up options and a Contact page linking Demo Submissions to LabelRadar. No account was created, no login was used, no LabelRadar workflow was executed and no music/link was delivered."
  },
  {
    name: "Armada Music Official Demo Drop Electronic Label Submission Route",
    websiteUrl: "https://www.armadamusic.com/",
    submissionUrl: "https://www.armadamusic.com/",
    sourceUrl: "https://www.armadamusic.com/",
    sourceType: "automation_run_136_public_research",
    country: "Netherlands / Amsterdam-based global electronic music label group with official Demo Drop entry point",
    language: "en",
    genres: ["armada-music", "label-demo", "demo-drop", "edm", "trance", "progressive-house", "deep-house", "tech-house", "electronic", "netherlands", "app-session-boundary", "manual-review"],
    submissionMethod: "official-armada-music-demo-drop-electronic-label-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because the official Armada site exposes a Demo drop entry point, but the parsed public page did not expose a complete safe auto-submit form; label fit, demo format, rights, metadata and any app/session boundary need owner review.",
    notes: "Official Armada Music pages show active 2026 site content, featured releases, artists, news and a Demo drop navigation route. No demo page beyond the public navigation was opened, no account/session control was handled, no form was submitted, no contact was guessed and no music/link was delivered."
  }
];