import type { PlatformInput } from '../models/types.js';
import { run119SeedPlatforms } from './run119PlatformSeeds.js';

export const run118SeedPlatforms: PlatformInput[] = [
  {
    name: "KUTX On-Air Rotation and Specialty Show Music Submission Route",
    websiteUrl: "https://kutx.org/",
    submissionUrl: "https://kutx.org/submit-your-music/",
    sourceUrl: "https://kutx.org/submit-your-music/",
    sourceType: "automation_run_118_public_research",
    country: "United States / Austin public radio on-air rotation and specialty-show route",
    language: "en",
    genres: ["kutx", "public-radio", "austin-music", "on-air-rotation", "specialty-shows", "electronic", "experimental", "hip-hop", "latin", "world", "radio-edit", "wav-download", "free-first", "manual-review"],
    submissionMethod: "official-kutx-on-air-rotation-specialty-show-music-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KUTX requires a targeted email to the Music Director with streaming and WAV download links, final mastered radio edits, bio/location/release context, a highlighted top track and optional specialty-show routing before any outbound submission is prepared.",
    notes: "Official public research confirmed KUTX is active in July 2026, publishes a Submit Your Music page, lists music@kutx.org for on-air rotation, asks for streaming links and WAV download links rather than MP3 attachments, requires clean radio edits and identifies specialty shows including electronic/experimental, hip-hop, Latin and new-music routes. No email was sent, no file/link was delivered and no external form was submitted."
  },
  {
    name: "KXLU FCC-Clean Music Director Demolisten and Specialty Submission Route",
    websiteUrl: "https://kxlu.com/",
    submissionUrl: "https://kxlu.com/contact/",
    sourceUrl: "https://kxlu.com/contact/",
    sourceType: "automation_run_118_public_research",
    country: "United States / Los Angeles college-community radio physical and Music Director route",
    language: "en",
    genres: ["kxlu", "college-radio", "freeform-radio", "music-director", "demolisten", "physical-mail", "fcc-clean", "specialty-shows", "electronic", "reggae", "latin", "hip-hop", "free-first", "manual-review"],
    submissionMethod: "official-kxlu-fcc-clean-music-director-demolisten-specialty-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KXLU requests FCC-clean submissions and separates general Music Director, Demolisten and specialty physical routes; route fit, clean edits, package prep and contact choice must be reviewed before use.",
    notes: "Official public research confirmed KXLU publishes staff contacts including a Music Director, active 2026 site content, FCC-clean submission guidance and physical addresses for General Submissions, Demolisten and A Fistful of Vinyl. No email was sent, no physical media was prepared and no contact route was used."
  },
  {
    name: "WHUS New Music Committee and Music Director Review Submission Route",
    websiteUrl: "https://whus.org/",
    submissionUrl: "https://whus.org/new-music-committee/",
    sourceUrl: "https://whus.org/new-music-committee/",
    sourceType: "automation_run_118_public_research",
    country: "United States / UConn college radio music-review committee route",
    language: "en",
    genres: ["whus", "college-radio", "new-music-committee", "music-director", "album-review", "promoter-submissions", "independent-music", "electronic", "hip-hop", "world", "free-first", "manual-review"],
    submissionMethod: "official-whus-new-music-committee-music-director-review-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WHUS routes new releases through a New Music Committee and Music Director contact; album/release fit, promoter-style package quality, clean metadata and outreach copy must be reviewed before any contact is made.",
    notes: "Official public research confirmed WHUS is active in June and July 2026, maintains a New Music Committee that reviews albums promoters send to the station, identifies the Music Department as a core station entry point, and lists musicdirector@whus.org for New Music Committee questions. No email was sent and no music package was delivered."
  },
  {
    name: "KUSF College Radio Music Department Email and Physical Submission Route",
    websiteUrl: "https://www.kusf.org/",
    submissionUrl: "https://www.kusf.org/contact",
    sourceUrl: "https://www.kusf.org/contact",
    sourceType: "automation_run_118_public_research",
    country: "United States / San Francisco online college-radio music-department route",
    language: "en",
    genres: ["kusf", "college-radio", "online-radio", "music-department", "physical-mail", "email-route", "rock", "hip-hop", "world", "rnb", "jazz", "soul", "eclectic", "free-first", "manual-review"],
    submissionMethod: "official-kusf-college-radio-music-department-email-physical-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KUSF exposes a public Music Department email and address but no safe auto-submit form; route fit, pitch text, link/package choice and station eligibility must be reviewed before outreach.",
    notes: "Official public research confirmed KUSF is an online 24/7 college-radio station with diverse current programming, publishes a Music Department address and kusfmusic@gmail.com contact, and lists station staff routes. No email was sent, no file/link was delivered and no physical package was prepared."
  },
  {
    name: "KZSU Stanford Music Director Mail Email and Cookie-Protected Guidelines Route",
    websiteUrl: "https://kzsu.stanford.edu/",
    submissionUrl: "https://kzsu.stanford.edu/contact/",
    sourceUrl: "https://kzsu.stanford.edu/contact/",
    sourceType: "automation_run_118_public_research",
    country: "United States / Stanford freeform radio Music Director and mail route",
    language: "en",
    genres: ["kzsu", "stanford-radio", "college-radio", "freeform-radio", "music-director", "snail-mail", "email-route", "cookie-boundary", "independent-new-releases", "electronic", "hip-hop", "world", "free-first", "manual-review"],
    submissionMethod: "official-kzsu-stanford-music-director-mail-email-cookie-protected-guidelines-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KZSU lists Music Director email and physical music-mail routes, but its detailed music guidelines page is protected by a cookie/session boundary; no cookie, session or guideline workflow should be handled automatically.",
    notes: "Official public research confirmed KZSU lists KZSU Music snail-mail and UPS addresses, Music Director contacts, music@kzsu.stanford.edu and a public send-us-music link, while the music-guidelines page redirected to a cookie-required boundary. No cookie/session control was handled, no email was sent and no package was prepared."
  },
  ...run119SeedPlatforms
];
