import type { PlatformInput } from '../models/types.js';
import { run147SeedPlatforms } from './run147PlatformSeeds.js';

export const run146SeedPlatforms: PlatformInput[] = [
  {
    name: "Broadjam Song Opportunity Licensing Review and Radio Submission Route",
    websiteUrl: "https://www.broadjam.com/",
    submissionUrl: "https://www.broadjam.com/delivery/opportunities/opportunities.php",
    sourceUrl: "https://www.broadjam.com/",
    sourceType: "automation_run_146_public_research",
    country: "Global / independent songwriter and artist opportunity, licensing, contest, review and radio-play submission marketplace",
    language: "en",
    genres: ["independent-music", "songwriting", "music-licensing", "sync", "radio-play", "reviews", "contests", "account-boundary", "payment-boundary", "manual-review"],
    submissionMethod: "official-broadjam-account-opportunity-song-submission-route",
    feeRequired: true,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Broadjam opportunities can involve account access, song selection, opportunity fit, usage rights, licensing terms, review/contest context and submission/payment choices.",
    notes: "Public research verified Broadjam as an independent-musician community with radio play, professional reviews, contests and film/TV/advertising/game placement opportunity context. No account was created, no opportunity was selected, no song was uploaded and no payment was initiated."
  },
  {
    name: "ReverbNation Artist Profile Opportunities and Fan Discovery Submission Route",
    websiteUrl: "https://www.reverbnation.com/",
    submissionUrl: "https://www.reverbnation.com/band-promotion/opportunities",
    sourceUrl: "https://www.reverbnation.com/",
    sourceType: "automation_run_146_public_research",
    country: "Global / independent artist profile, promotion and opportunity-discovery route",
    language: "en",
    genres: ["independent-music", "artist-profile", "fan-discovery", "promotion", "opportunities", "licensing", "festivals", "account-boundary", "freemium", "manual-review"],
    submissionMethod: "official-reverbnation-artist-profile-opportunity-submission-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because ReverbNation artist participation requires account/profile access, artist assets, track uploads, opportunity targeting and optional paid promotion or artist-service decisions.",
    notes: "Public research verified ReverbNation as an active independent-music website owned by BandLab Technologies, used for musicians, producers and venues to collaborate and communicate. No login was used, no profile was created, no track was uploaded and no opportunity was entered."
  },
  {
    name: "RadioAirplay Jango Paid Listener Targeting Airplay Campaign Route",
    websiteUrl: "https://www.radioairplay.com/",
    submissionUrl: "https://www.radioairplay.com/",
    sourceUrl: "https://www.jango.com/",
    sourceType: "automation_run_146_public_research",
    country: "Global / Jango listener-targeted internet-radio airplay campaign route",
    language: "en",
    genres: ["internet-radio", "airplay-campaign", "listener-targeting", "jango", "artist-promotion", "paid-campaign", "account-boundary", "payment-boundary", "manual-review"],
    submissionMethod: "official-radioairplay-jango-artist-campaign-submission-route",
    feeRequired: true,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because RadioAirplay/Jango campaign creation involves account access, song upload or catalog selection, listener targeting, budget/subscription selection, campaign copy and paid-play terms.",
    notes: "Public research verified Jango as an online radio service and RadioAirplay as the rebranded Jango Airplay artist promotion path. No account was created, no song was uploaded, no target artist/listener group was selected and no campaign or payment was initiated."
  },
  {
    name: "Music Xray Song to Opportunity A&R Guaranteed Listen Submission Route",
    websiteUrl: "https://www.musicxray.com/",
    submissionUrl: "https://www.musicxray.com/artist/categories",
    sourceUrl: "https://www.musicxray.com/",
    sourceType: "automation_run_146_public_research",
    country: "Global / A&R, label, publisher, supervisor and industry-professional opportunity matching route",
    language: "en",
    genres: ["a-and-r", "song-opportunities", "sync", "publishing", "labels", "music-supervisors", "paid-submission", "account-boundary", "payment-boundary", "manual-review"],
    submissionMethod: "official-music-xray-song-to-opportunity-submission-route",
    feeRequired: true,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Music Xray opportunity submissions involve account access, song/opportunity matching, guaranteed-listen fees, industry-recipient selection, critique/response terms and rights-sensitive pitch metadata.",
    notes: "Public research verified Music Xray as an active platform where artists submit songs to industry professionals, commonly with a fee for guaranteed listen/response. No account was created, no song was analyzed or submitted and no payment was initiated."
  },
  {
    name: "VPAL VP Records Caribbean Independent Distribution Submission Route",
    websiteUrl: "https://www.vprecords.com/",
    submissionUrl: "https://www.vprecords.com/distribution/",
    sourceUrl: "https://www.vprecords.com/",
    sourceType: "automation_run_146_public_research",
    country: "Global / reggae, dancehall, soca, afrobeats and Caribbean independent distribution route",
    language: "en",
    genres: ["reggae", "dancehall", "soca", "afrobeats", "caribbean", "distribution", "label-services", "rights-management", "manual-review"],
    submissionMethod: "official-vpal-vp-records-independent-distribution-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because VPAL/VP Records distribution fit depends on Caribbean genre alignment, release ownership, label/distribution terms, rights metadata, territory strategy and professional package quality.",
    notes: "Public research verified VP Records as a reggae/dancehall/soca label group and VPAL as its distribution branch that gives independent artists access to VP Records' distribution channel. No application was submitted, no music was delivered and no contact or terms negotiation was initiated."
  },
  ...run147SeedPlatforms
];
