import type { PlatformInput } from '../models/types.js';
import { run168SeedPlatforms } from './run168PlatformSeeds.js';

export const run167SeedPlatforms: PlatformInput[] = [
  ...run168SeedPlatforms,
  {
    name: "Audiomack Free Limitless Creator Upload Discovery Route",
    websiteUrl: "https://audiomack.com/",
    submissionUrl: "https://creators.audiomack.com/",
    sourceUrl: "https://creators.audiomack.com/",
    sourceType: "automation_run_167_public_research",
    country: "United States / global on-demand music streaming and audio discovery platform with free creator upload and business inquiry routes",
    language: "en",
    genres: ["music-streaming", "artist-upload", "audio-discovery", "afrosounds", "hip-hop", "caribbean", "electronic", "creator-app", "free-hosting", "login-boundary", "manual-review"],
    submissionMethod: "official-audiomack-free-limitless-creator-upload-discovery-route",
    feeRequired: false,
    feeAmount: "Audiomack states free, limitless hosting/sharing/stats for creators; upload and creator tooling require account/session handling.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Audiomack upload/creator tooling requires account creation or login, track ownership, metadata, cover art, explicit-content settings, territory/monetization choices and private-link/release strategy to remain owner-controlled.",
    notes: "Public research verified the official Audiomack creator route, upload link, free/limitless creator-hosting language, active trending/recently-added catalog, business inquiry route and 2026 footer context. No account was created, no login was used, no upload was attempted and no app/session control was handled."
  },
  {
    name: "Songtradr Licensing Marketplace Artist Catalog Upload Route",
    websiteUrl: "https://www.songtradr.com/",
    submissionUrl: "https://www.songtradr.com/",
    sourceUrl: "https://www.songtradr.com/",
    sourceType: "automation_run_167_public_research",
    country: "United States / global B2B music licensing platform and searchable catalog marketplace for artists and labels",
    language: "en",
    genres: ["sync-licensing", "music-licensing", "b2b", "catalog-upload", "artist-marketplace", "film-tv-advertising", "login-boundary", "app-boundary", "manual-review"],
    submissionMethod: "official-songtradr-licensing-marketplace-artist-catalog-upload-route",
    feeRequired: false,
    feeAmount: "No public upfront submission fee was verified during this run; platform licensing and account/catalog terms require manual review before use.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Songtradr is a JavaScript app/account workflow involving catalog upload, rights ownership, PRO/publishing data, licensing fees, splits, metadata, sync opt-ins and commercial terms.",
    notes: "Public research verified the official Songtradr web app boundary and independent source context describing Songtradr as a B2B music licensing platform where artists can upload music and set licensing fees. No account was created, no login was used, no catalog was uploaded and no licensing settings were selected."
  },
  {
    name: "Broadjam Independent Artist Licensing Contest Radio Submission Route",
    websiteUrl: "https://www.broadjam.com/",
    submissionUrl: "https://www.broadjam.com/",
    sourceUrl: "https://www.broadjam.com/",
    sourceType: "automation_run_167_public_research",
    country: "United States / global independent-musician community with licensing, contest, radio-play and review submission opportunities",
    language: "en",
    genres: ["music-licensing", "songwriting-contests", "radio-play", "artist-community", "song-reviews", "film-tv-ads-games", "independent-artists", "login-boundary", "payment-side-route", "manual-review"],
    submissionMethod: "official-broadjam-independent-artist-licensing-contest-radio-submission-route",
    feeRequired: false,
    feeAmount: "Broadjam public route availability was verified, but contest, membership, hosting or opportunity fees must be reviewed case-by-case before any use.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Broadjam uses member/account workflows and may involve contests, reviews, premium hosting or opportunity fees, plus song ownership, licensing terms, metadata, download settings and sync/radio opportunity targeting.",
    notes: "Public research verified Broadjam independent-musician community context, online song submissions for radio play/professional reviews/film-TV-ad-game placement, song contests and top-chart/review mechanisms. Official site fetching failed during public research, so this is queued as manual review with no automated entry."
  },
  {
    name: "LabelRadar Electronic Demo Label and Remix Competition Submission Route",
    websiteUrl: "https://www.labelradar.com/",
    submissionUrl: "https://www.labelradar.com/artists",
    sourceUrl: "https://www.labelradar.com/artists",
    sourceType: "automation_run_167_public_research",
    country: "Global / Beatport-linked electronic music demo and remix-competition submission platform connecting artists with labels",
    language: "en",
    genres: ["demo-submission", "electronic", "dance", "labels", "remix-competition", "beatport", "producer-platform", "login-boundary", "app-boundary", "manual-review"],
    submissionMethod: "official-labelradar-electronic-demo-label-remix-competition-submission-route",
    feeRequired: false,
    feeAmount: "No public upfront fee was verified on the JavaScript-gated artist route; active contest/demo terms, login and any credits/payment rules require manual review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because LabelRadar exposes a JavaScript/login app boundary and submissions require demo/remix rights, label/competition terms, stems/originality checks, artist profile, metadata and any Beatport/partner rules to remain owner-controlled.",
    notes: "Public research verified the official LabelRadar artist route as an app/loading boundary and independent current reporting that LabelRadar is used for Beatport/Warner remix entries and is designed to help artists connect with labels. No account was created, no login was used, no demo/remix was uploaded and no app workflow was entered."
  },
  {
    name: "BBC Music Introducing UK Artist Upload UGC Route",
    websiteUrl: "https://www.bbc.co.uk/introducing",
    submissionUrl: "https://www.bbc.co.uk/introducing/uploader",
    sourceUrl: "https://www.bbc.co.uk/introducing",
    sourceType: "automation_run_167_public_research",
    country: "United Kingdom / BBC unsigned and under-the-radar UK artist upload route with local and national radio forwarding potential",
    language: "en",
    genres: ["public-broadcaster", "bbc-introducing", "unsigned-artists", "uk-local-radio", "radio-airplay", "festival-discovery", "ugc-upload", "login-boundary", "eligibility-boundary", "manual-review"],
    submissionMethod: "official-bbc-music-introducing-uk-artist-upload-ugc-route",
    feeRequired: false,
    feeAmount: "No submission fee was observed in public source context; route is UK-local/UGC uploader based and requires account/eligibility review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because BBC Introducing is UK/postcode and UGC/uploader based; MarcsMusic eligibility, account access, track rights, BBC terms, location, metadata, explicit status and local-show fit must be reviewed before any upload.",
    notes: "Public research verified BBC Introducing active status, artist uploader context, UK/local radio routing and national forwarding potential through public index sources; direct BBC fetch was blocked by robots, so no uploader workflow was entered and no account/session/CAPTCHA controls were handled."
  }
];
