import type { PlatformInput } from '../models/types.js';

export const run141SeedPlatforms: PlatformInput[] = [
  {
    name: "Spotify for Artists Editorial Playlist Pitch and Release Radar Route",
    websiteUrl: "https://artists.spotify.com/",
    submissionUrl: "https://artists.spotify.com/playlisting",
    sourceUrl: "https://artists.spotify.com/playlisting",
    sourceType: "automation_run_141_public_research",
    country: "Sweden / United States / global Spotify streaming, editorial playlist, Release Radar and artist-dashboard route",
    language: "en",
    genres: ["spotify-for-artists", "editorial-playlist-pitch", "release-radar", "global-streaming", "new-release", "distributor-required", "artist-profile-claim", "account-required", "manual-review"],
    submissionMethod: "official-spotify-for-artists-editorial-playlist-pitch-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Spotify playlist pitching requires distributor-delivered unreleased music, Spotify for Artists access, owner/admin account control, one-song selection, metadata, genre/context, release timing and rights verification.",
    notes: "Official Spotify for Artists guidance states Spotify for Artists is the only way to submit new music for playlisting, that artists can pitch one song from an EP or album, and that new music should be pitched at least seven days before release. No account was created, no login was used, no release was configured and no playlist pitch was submitted."
  },
  {
    name: "Amazon Music for Artists Global Programming Pitch Route",
    websiteUrl: "https://artists.amazonmusic.com/",
    submissionUrl: "https://artists.amazonmusic.com/pitch",
    sourceUrl: "https://artists.amazonmusic.com/pitch",
    sourceType: "automation_run_141_public_research",
    country: "United States / global Amazon Music artist tools, programming and curation pitch route",
    language: "en/fr/de/it/ja/pt/es",
    genres: ["amazon-music-for-artists", "global-curation", "programming-consideration", "new-release-pitch", "artist-profile-claim", "distributor-delivery", "account-required", "app-session-boundary", "manual-review"],
    submissionMethod: "official-amazon-music-for-artists-global-programming-pitch-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Amazon Music pitching requires distributor-delivered eligible new music, owner/admin app access, one-track selection, artist/team verification, rights, genre/context, marketing-plan and release-date validation.",
    notes: "Official Amazon Music for Artists guidance says artists can submit a track for global curation and programming consideration, with eligibility limited to new music delivered to Amazon Music with streaming rights, one track per release and up to 14 days after street date. No Amazon account was used, no app workflow was entered and no pitch was submitted."
  },
  {
    name: "Pandora AMP Independent Artist Distributor Claim and Genome Analysis Route",
    websiteUrl: "https://www.ampplaybook.com/",
    submissionUrl: "https://www.ampplaybook.com/independent-artist-submissions",
    sourceUrl: "https://www.ampplaybook.com/independent-artist-submissions",
    sourceType: "automation_run_141_public_research",
    country: "United States / Pandora AMP artist-claim, distributor-delivery and Music Genome Project analysis route",
    language: "en",
    genres: ["pandora-amp", "independent-artist-submissions", "distributor-delivery", "artist-profile-claim", "music-genome-project", "featured-tracks", "artist-audio-message", "account-required", "manual-review"],
    submissionMethod: "official-pandora-amp-independent-artist-distributor-claim-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Pandora now routes independent artists through supported distributors plus an AMP artist claim; U.S. streaming rights, aggregator choice, artist verification, Genome analysis, Featured Tracks and promotional tools require owner control.",
    notes: "Official AMP Playbook guidance states artists no longer submit directly through the former Artist Submissions portal; instead music must be delivered to Pandora through supported digital aggregators with Pandora selected and U.S. streaming rights granted, then the artist claims a Pandora AMP account. No distributor settings were changed, no AMP account was claimed and no submission or campaign was made."
  },
  {
    name: "BandLab Creator Publish Social Discovery and Distribution Route",
    websiteUrl: "https://www.bandlab.com/",
    submissionUrl: "https://www.bandlab.com/",
    sourceUrl: "https://www.bandlab.com/",
    sourceType: "automation_run_141_public_research",
    country: "Singapore / global creator music publishing, social discovery, collaboration and distribution ecosystem",
    language: "en/fr/hi/ja/ko/pt/ru/es/tr",
    genres: ["bandlab", "creator-upload", "publish-song", "social-music-platform", "collaboration", "music-discovery-feed", "bandlab-albums", "freemium", "account-required", "manual-review"],
    submissionMethod: "official-bandlab-creator-publish-social-discovery-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because BandLab publishing requires owner-controlled account/session access, track/project ownership, file/export choice, visibility, collaboration settings, profile/distribution options and optional premium feature decisions.",
    notes: "Official BandLab public site exposes the creator platform and sign-up/login route, while fresh public research verifies BandLab as an active free music-making app with built-in publishing, sharing, social discovery and premium tiers. No account was created, no login was used, no track was published and no premium feature was activated."
  },
  {
    name: "Audius Artist Upload Decentralized Music Streaming Route",
    websiteUrl: "https://audius.co/",
    submissionUrl: "https://audius.co/",
    sourceUrl: "https://audius.co/",
    sourceType: "automation_run_141_public_research",
    country: "United States / global decentralized artist upload, fan discovery and music-streaming route",
    language: "en",
    genres: ["audius", "artist-upload", "decentralized-streaming", "direct-to-fan", "electronic-dance-music", "web3", "account-required", "javascript-app-boundary", "manual-review"],
    submissionMethod: "official-audius-artist-upload-decentralized-streaming-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Audius resolves as a JavaScript app boundary and upload/use requires account/session control, rights ownership, profile setup, track metadata, fan-discovery choices and web3/token or monetization boundary review.",
    notes: "Official Audius public site was observed as a JavaScript app boundary for a free music streaming service for artists, labels and fans; public sources identify Audius as a decentralized music platform that lets artists upload content and connect directly with fans. No account was created, no login was used, no wallet/token feature was entered and no track was uploaded."
  }
];
