import type { PlatformInput } from '../models/types.js';

export const run162SeedPlatforms: PlatformInput[] = [
  {
    name: "KZSU Stanford Music Department Cookie Session Submission Route",
    websiteUrl: "https://kzsu.stanford.edu/",
    submissionUrl: "https://kzsu.stanford.edu/contact/",
    sourceUrl: "https://kzsu.stanford.edu/contact/",
    sourceType: "automation_run_162_public_research",
    country: "United States / Stanford University freeform college radio station with FM and online reach",
    language: "en",
    genres: ["college-radio", "freeform", "stanford", "independent", "experimental", "electronic", "hip-hop", "world", "music-director-email", "snail-mail", "cookie-session-boundary", "manual-review"],
    submissionMethod: "official-kzsu-music-department-cookie-session-submission-route",
    feeRequired: false,
    feeAmount: "No submission fee observed; official contact page routes Music Director submissions to music@kzsu.stanford.edu and lists a KZSU Music postal route, while the detailed zookeeper music-submission guidelines require a browser cookie/session boundary.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because the official send-music/guidelines route triggered a cookie/session verification boundary and the owner must verify rights, clean/explicit status, release metadata, file/link policy, station fit and whether to use email or postal servicing before contact.",
    notes: "Public research verified KZSU's official site, live/stream context, contact page, Music Directors route, music@kzsu.stanford.edu, KZSU Music snail-mail address and cookie/session requirement on the guidelines route. No cookie/session boundary was handled, no login was used, no email was sent and no package was prepared."
  },
  {
    name: "KXLU 88.9 FM FCC Clean Physical Music Director Demolisten Route",
    websiteUrl: "https://kxlu.com/",
    submissionUrl: "https://kxlu.com/contact/",
    sourceUrl: "https://kxlu.com/contact/",
    sourceType: "automation_run_162_public_research",
    country: "United States / Los Angeles Loyola Marymount University freeform college-community station",
    language: "en",
    genres: ["college-radio", "los-angeles", "freeform", "non-commercial", "eclectic", "electronic", "world", "reggae", "hip-hop", "fcc-clean", "physical-submission", "manual-review"],
    submissionMethod: "official-kxlu-fcc-clean-physical-music-director-demolisten-route",
    feeRequired: false,
    feeAmount: "No submission fee observed; official contact page lists FCC-clean submissions only, general Music Director, Demolisten, and Punk/Folk/Vinyl physical submission addresses, plus a public Music Director contact route.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KXLU requires FCC-clean submissions and uses multiple physical routing choices; owner must verify clean edit status, package format, station fit, route selection, one-sheet, metadata, rights and whether Demolisten or general Music Director routing is appropriate.",
    notes: "Public research verified KXLU's official site, livestream/current-post activity, Loyola Marymount non-commercial freeform identity, Contact page, Music Director route, physical submission addresses and FCC-clean requirement. No email was sent, no links/files were delivered and no physical package was prepared."
  },
  {
    name: "KUPS Tacoma Staff Music Submission Form and Genre Director Email Route",
    websiteUrl: "https://kupsfm.com/",
    submissionUrl: "https://kupsfm.com/contact/",
    sourceUrl: "https://kupsfm.com/contact/",
    sourceType: "automation_run_162_public_research",
    country: "United States / Tacoma University of Puget Sound student-run college radio with FM and online reach",
    language: "en",
    genres: ["college-radio", "tacoma", "alternative", "hip-hop", "electronic", "loud-rock", "specialty", "local-artists", "contact-form", "genre-routed-email", "manual-review"],
    submissionMethod: "official-kups-staff-music-submission-form-genre-director-email-route",
    feeRequired: false,
    feeAmount: "No submission fee observed; official Contact page exposes a staff music-submission form and the Staff page lists genre/department email routes for alternative, hip-hop, specialty, electronic and loud rock directors.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KUPS exposes both a public contact form and multiple genre-director email routes; owner must choose targeting, verify clean/explicit status, release fit, genre routing, metadata, links/files policy and pitch copy before any form or email action.",
    notes: "Public research verified KUPS official site activity for the 2026-27 season/summer streaming, University of Puget Sound student-run nonprofit/noncommercial identity, contact form, mailing address and staff/genre-director email routes. No form was submitted, no email was sent and no files or links were delivered."
  },
  {
    name: "CFUV 101.9 Victoria Digital Music Director Airplay Submission Route",
    websiteUrl: "https://cfuv.uvic.ca/",
    submissionUrl: "https://cfuv.uvic.ca/music-submissions/",
    sourceUrl: "https://cfuv.uvic.ca/music-submissions/",
    sourceType: "automation_run_162_public_research",
    country: "Canada / Victoria campus-community radio station with nonprofit FM and online reach",
    language: "en",
    genres: ["campus-community-radio", "victoria", "canada", "independent", "electronic", "hip-hop", "world", "nonprofit", "digital-download", "music-director-email", "manual-review"],
    submissionMethod: "official-cfuv-digital-music-director-airplay-submission-route",
    feeRequired: false,
    feeAmount: "No submission fee observed; official Music Submissions page instructs artists to email digital download links to music@cfuv.ca, with MP3 minimum 320 kbps and local-only physical exceptions.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because CFUV requires a properly packaged digital download submission with at least three unique tracks, track listing, bio/location details, release context and owner-approved links before any email outreach.",
    notes: "Public research verified CFUV's official University of Victoria Student Radio Society site, nonprofit campus/community identity, Music Submissions page, public Music Director contact, minimum file requirements, no-general-physical policy and independent/underappreciated programming focus. No email was sent and no links/files were delivered."
  },
  {
    name: "CJSF 90.1FM National Music Director Earshot Distro Submission Route",
    websiteUrl: "https://www.cjsf.ca/",
    submissionUrl: "https://www.cjsf.ca/contact-us/departments/music-department",
    sourceUrl: "https://www.cjsf.ca/contact-us/departments/music-department",
    sourceType: "automation_run_162_public_research",
    country: "Canada / Vancouver-Burnaby campus-community radio and national NCRA !earshot Distro pathway",
    language: "en",
    genres: ["campus-community-radio", "vancouver", "burnaby", "canada", "national-distribution", "earshot-distro", "independent", "electronic", "hip-hop", "world", "rights-review", "manual-review"],
    submissionMethod: "official-cjsf-national-music-director-earshot-distro-submission-route",
    feeRequired: false,
    feeAmount: "No submission fee observed on the official CJSF music pages; CJSF routes submissions through its Music Coordinator and national distribution context via NCRA / !earshot Distro, with local physical exceptions.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because CJSF points artists toward an external national distribution form/!earshot Distro registration and requires broadcast-rights authority; owner must verify rights grant, local-vs-national eligibility, metadata, release format, clean/explicit status and form/account boundaries before action.",
    notes: "Public research verified CJSF's official site activity, listen-live context, Music Department pages, Music Coordinator contact, CD-submission guidance, local-physical limitations, broadcast-rights language and !earshot Distro/National Music Director submission context. No external form was submitted, no account/login was used, no email was sent and no package was prepared."
  }
];
