import type { PlatformInput } from '../models/types.js';

export const run155SeedPlatforms: PlatformInput[] = [
  {
    name: "TuneCore Unlimited Digital Distribution Release Upload Route",
    websiteUrl: "https://www.tunecore.com/",
    submissionUrl: "https://www.tunecore.com/",
    sourceUrl: "https://www.tunecore.com/",
    sourceType: "automation_run_155_public_research",
    country: "Global / United States-based independent digital distribution, publishing and artist-services platform with worldwide DSP delivery",
    language: "en",
    genres: ["digital-distribution", "release-upload", "streaming-stores", "music-publishing", "spotify", "apple-music", "tiktok", "youtube", "manual-review", "payment-required", "login-required"],
    submissionMethod: "official-tunecore-unlimited-digital-distribution-release-upload-route",
    feeRequired: true,
    feeAmount: "Paid distribution route observed with unlimited releases starting at $24.99/year; plan, add-on and payout choices require owner review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because TuneCore distribution uses sign-up/login dashboard access, paid plan selection, release metadata, ownership confirmation, cover art and DSP/store choices; no automated account creation, payment or upload is allowed.",
    notes: "Public research verified TuneCore's official distribution page, pricing, sign-up/login/dashboard links, 150+ store context and active artist-service route. No account was created, no payment was initiated and no music/artwork/audio was uploaded or transferred."
  },
  {
    name: "CD Baby One-Time Release Digital Distribution Upload Route",
    websiteUrl: "https://cdbaby.com/",
    submissionUrl: "https://cdbaby.com/",
    sourceUrl: "https://cdbaby.com/",
    sourceType: "automation_run_155_public_research",
    country: "Global / United States-based independent music distribution platform with worldwide digital partner delivery",
    language: "en",
    genres: ["digital-distribution", "one-time-release", "streaming-stores", "download-services", "cover-song-licensing", "artist-promotion", "manual-review", "payment-required", "login-required"],
    submissionMethod: "official-cd-baby-one-time-release-digital-distribution-upload-route",
    feeRequired: true,
    feeAmount: "Paid one-time setup route observed from $9.99 per release and published single/album pricing; exact release and add-on choices require owner review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because CD Baby release distribution uses Get Started/login flow, one-time release payment, DSP partner delivery, release metadata, rights declarations, cover-song/licensing choices and promotion add-ons.",
    notes: "Public research verified CD Baby's official music-distribution page, pricing, Get Started/login links, 150+ streaming/download partner context and current digital-only release route. No account was created, no payment was initiated and no release/audio/artwork was uploaded."
  },
  {
    name: "ONErpm Emerging Self-Service Digital Delivery and Album Review Route",
    websiteUrl: "https://onerpm.com/",
    submissionUrl: "https://onerpm.com/digital-distribution/",
    sourceUrl: "https://onerpm.com/digital-distribution/",
    sourceType: "automation_run_155_public_research",
    country: "Global / independent music and video distribution platform with offices across North America, Caribbean, Europe, Africa, Asia and Oceania",
    language: "en",
    genres: ["digital-distribution", "self-service", "album-review", "video-distribution", "dsp-pitching", "analytics", "royalty-splits", "manual-review", "login-required"],
    submissionMethod: "official-onerpm-emerging-self-service-digital-delivery-album-review-route",
    feeRequired: false,
    feeAmount: "No registration, annual or upload fees observed for the Emerging self-service route; later commercial terms and advanced-service eligibility remain manual.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because ONErpm uses dashboard join/login, self-service delivery tools, album upload review, rights metadata, DSP delivery settings, royalty-split/accounting configuration and optional higher-service terms.",
    notes: "Public research verified ONErpm's official homepage, Join/Login dashboard links, Digital Distribution page, self-service platform, manual album-review language and 2026 global company context. No account was created, no dashboard workflow entered and no music/video/release file was uploaded."
  },
  {
    name: "LANDR Studio Distribution and Release Upload Route",
    websiteUrl: "https://www.landr.com/",
    submissionUrl: "https://www.landr.com/music-distribution/",
    sourceUrl: "https://www.landr.com/music-distribution/",
    sourceType: "automation_run_155_public_research",
    country: "Global / Canada-based music creation, mastering, promotion and distribution platform with worldwide store delivery",
    language: "en",
    genres: ["digital-distribution", "release-upload", "mastering", "playlist-pitching", "pre-save", "youtube-content-id", "royalty-splits", "manual-review", "payment-side-route", "login-required"],
    submissionMethod: "official-landr-studio-distribution-release-upload-route",
    feeRequired: true,
    feeAmount: "Paid/subscription pricing observed from $2 per month with sign-up and pricing links; exact plan, release and add-on choices require owner review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because LANDR distribution uses sign-up/login app workflow, release wizard, pricing/plan choice, release metadata, mastering/artwork tools, cover-song licensing, playlist-pitching, Content ID and royalty-split settings.",
    notes: "Public research verified LANDR's official music-distribution page, 150+ store/platform delivery, app sign-up/login links, release wizard, pricing side route and active 2026 site context. No account was created, no app workflow entered, no payment initiated and no release file was uploaded."
  },
  {
    name: "RouteNote Free Premium Worldwide Distribution Upload Route",
    websiteUrl: "https://routenote.com/",
    submissionUrl: "https://routenote.com/",
    sourceUrl: "https://routenote.com/",
    sourceType: "automation_run_155_public_research",
    country: "Global / Europe-based digital music distribution platform with free and premium worldwide delivery routes",
    language: "en",
    genres: ["digital-distribution", "free-first", "premium-side-route", "streaming-platforms", "spotify", "apple-music", "royalties", "analytics", "independent-artists", "manual-review", "login-required"],
    submissionMethod: "official-routenote-free-premium-worldwide-distribution-upload-route",
    feeRequired: false,
    feeAmount: "Free distribution route observed with optional Premium pricing model; payment model can be changed and must be owner-reviewed before use.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because RouteNote uses a Get Started/account route, free versus Premium payment-model choice, platform selection, release metadata, rights confirmation and earnings/statistics settings.",
    notes: "Public research verified RouteNote's official distribution page, Free/Premium pricing model, Get Started route, worldwide distribution workflow, 50+ platform partner context and active RouteNote Sessions content. No account was created, no pricing model selected and no audio/artwork/release was uploaded."
  }
];
