import type { PlatformInput } from '../models/types.js';

export const run165SeedPlatforms: PlatformInput[] = [
  {
    name: "KSPC 88.7FM Album EP Digital Physical Airplay Submission Route",
    websiteUrl: "https://kspc.org/",
    submissionUrl: "https://kspc.org/music-submissions/",
    sourceUrl: "https://kspc.org/music-submissions/",
    sourceType: "automation_run_165_public_research",
    country: "United States / Claremont Colleges non-commercial college-community radio station with FM and online reach",
    language: "en",
    genres: ["college-radio", "non-commercial", "claremont", "independent", "electronic", "hip-hop", "world", "reggae", "digital-download", "physical-submission", "protected-contact", "manual-review"],
    submissionMethod: "official-kspc-album-ep-digital-physical-airplay-submission-route",
    feeRequired: false,
    feeAmount: "No submission fee observed; official KSPC guidance accepts free-download digital submissions and CD/record mailings while excluding streaming-only links, singles, demos, cassettes and AI music.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KSPC has strict route-fit rules around downloadable albums/EPs, physical formats, no streaming-only links, no singles/demos/cassettes, no AI music and protected-contact boundaries that were not decoded.",
    notes: "Public research verified active KSPC station context, official Music Submissions page, accepted digital download and physical routes, exclusions, non-commercial/no-pay-for-play policy and protected email display. No protected contact was decoded, no email was sent, no links/files were delivered and no SMTP/MX probing was performed."
  },
  {
    name: "WMSE 91.7FM Music Department Physical Digital FCC Clean Submission Route",
    websiteUrl: "https://www.wmse.org/",
    submissionUrl: "https://www.wmse.org/music-department/",
    sourceUrl: "https://www.wmse.org/music-department/",
    sourceType: "automation_run_165_public_research",
    country: "United States / Milwaukee School of Engineering non-commercial community radio station with FM and online reach",
    language: "en",
    genres: ["community-radio", "milwaukee", "independent", "electronic", "experimental", "hip-hop", "world", "reggae", "physical-submission", "digital-download", "fcc-clean", "captcha-boundary", "manual-review"],
    submissionMethod: "official-wmse-music-department-physical-digital-fcc-clean-submission-route",
    feeRequired: false,
    feeAmount: "No submission fee observed; official Music Department page accepts physical walk-up/mail submissions and digital links via WeTransfer or email.",
    loginRequired: false,
    captchaDetected: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WMSE requires route selection, physical/digital package preparation, FCC clean/explicit notes, genre targeting, release metadata, rights, pitch context and contact-form CAPTCHA boundaries must not be handled automatically.",
    notes: "Public research verified WMSE official site activity, Music Department submission guidance, accepted formats, digital WeTransfer/email option, FCC-clean requirements, review timing, public contact emails and public contact form with CAPTCHA. No contact form was submitted, no CAPTCHA was handled, no email was sent and no files/links were delivered."
  },
  {
    name: "Radio Free Brooklyn Downloadable Track and CD Vinyl Music Submission Form Route",
    websiteUrl: "https://www.radiofreebrooklyn.org/",
    submissionUrl: "https://submissions.radiofreebrooklyn.org/music-submission-form/",
    sourceUrl: "https://submissions.radiofreebrooklyn.org/music-submission-form/",
    sourceType: "automation_run_165_public_research",
    country: "United States / Brooklyn independent online community radio station with live stream and local-culture programming",
    language: "en",
    genres: ["community-radio", "brooklyn", "independent", "local-music", "electronic", "hip-hop", "world", "reggae", "download-link", "music-submission-form", "recaptcha", "manual-review"],
    submissionMethod: "official-radio-free-brooklyn-downloadable-track-cd-vinyl-music-submission-form-route",
    feeRequired: false,
    feeAmount: "No submission fee observed; official form requires a freely downloadable track or ZIP link and also permits vinyl/CD route via the contact-page address.",
    loginRequired: false,
    captchaDetected: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because the official RFB form requires artist/contact data, downloadable music URL, optional image asset, airplay/guest intent, NYC-area context and reCAPTCHA validation; the physical CD/vinyl side route also needs owner control.",
    notes: "Public research verified current Radio Free Brooklyn site activity, Submit Music navigation, official Music Submission Form, required freely downloadable track/ZIP rule, CD/vinyl side route and reCAPTCHA boundary. No form was submitted, no reCAPTCHA was handled, no image/audio/link was delivered and no message was sent."
  },
  {
    name: "WXDU 88.7FM Bandcamp YUM Code Airplay Submission Route",
    websiteUrl: "https://www.wxdu.org/",
    submissionUrl: "https://www.wxdu.org/contact.html",
    sourceUrl: "https://www.wxdu.org/contact.html",
    sourceType: "automation_run_165_public_research",
    country: "United States / Duke University progressive alternative non-commercial radio station with FM and online reach",
    language: "en",
    genres: ["college-radio", "duke-university", "progressive-alternative", "independent", "electronic", "hip-hop", "world", "reggae", "bandcamp-yum", "music-director-email", "manual-review"],
    submissionMethod: "official-wxdu-bandcamp-yum-code-airplay-submission-route",
    feeRequired: false,
    feeAmount: "No submission fee observed; official WXDU Contact page says Bandcamp YUM codes are preferred for airplay submissions and lists music@wxdu.org.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WXDU prefers Bandcamp YUM codes and music-director routing; owner must verify Bandcamp/download setup, clean/explicit status, release metadata, rights, pitch copy and station fit before any outreach.",
    notes: "Public research verified WXDU official site activity, current playlist/listen context, mission, contact page, airplay submission note, Bandcamp YUM-code preference and music@wxdu.org route. No email was sent, no download code/link was delivered and no form or request workflow was used."
  },
  {
    name: "WERS Wicked Local Wednesday Local Artist MP3 Upload Form Route",
    websiteUrl: "https://wers.org/",
    submissionUrl: "https://wers.org/wicked-local-wednesday/",
    sourceUrl: "https://wers.org/wicked-local-wednesday/",
    sourceType: "automation_run_165_public_research",
    country: "United States / Boston Emerson College non-commercial radio station with local-artist discovery programming",
    language: "en",
    genres: ["college-radio", "boston", "local-artists", "independent", "electronic", "pop", "hip-hop", "world", "reggae", "mp3-upload-form", "recaptcha", "manual-review"],
    submissionMethod: "official-wers-wicked-local-wednesday-local-artist-mp3-upload-form-route",
    feeRequired: false,
    feeAmount: "No submission fee observed; official WERS Wicked Local Wednesday page exposes a local-artist form with MP3 upload field and 39 MB maximum file size.",
    loginRequired: false,
    captchaDetected: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because this is a local Boston-area WERS route with artist/location eligibility, contact fields, MP3 upload, file-size limits, local-program fit and site reCAPTCHA boundary that must remain owner-controlled.",
    notes: "Public research verified WERS official 2026 site activity, Submit Music navigation, Wicked Local Wednesday discovery page, local artist form fields, MP3 upload limit, recent 2026 posts and reCAPTCHA-protected site context. No form was submitted, no file was uploaded and no CAPTCHA/session control was handled."
  }
];
