import type { PlatformInput } from '../models/types.js';
import { run152SeedPlatforms } from './run152PlatformSeeds.js';

export const run151SeedPlatforms: PlatformInput[] = [
  {
    name: "Songtradr Sync Licensing Marketplace Artist Upload Route",
    websiteUrl: "https://www.songtradr.com/",
    submissionUrl: "https://www.songtradr.com/",
    sourceUrl: "https://www.songtradr.com/",
    sourceType: "automation_run_151_public_research",
    country: "Global / United States-based B2B music licensing marketplace for artists, labels, agencies and brands",
    language: "en",
    genres: ["sync-licensing", "music-marketplace", "artist-upload", "film-tv-advertising", "electronic", "world", "reggae", "account-boundary", "manual-review"],
    submissionMethod: "official-songtradr-sync-licensing-marketplace-artist-upload-route",
    feeRequired: false,
    feeAmount: "Final account, commission, licensing and payout terms require manual review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required for account access, rights clearance, license terms, metadata, territory and payout settings.",
    notes: "Public research verified Songtradr as a global music licensing marketplace. No protected workflow was entered."
  },
  {
    name: "Symphonic Starter Paid Distribution Unlimited Release Upload Route",
    websiteUrl: "https://symphonic.com/",
    submissionUrl: "https://symphonic.com/starter/",
    sourceUrl: "https://symphonic.com/starter/",
    sourceType: "automation_run_151_public_research",
    country: "Global / United States-based music technology and distribution company with DIY artist distribution route",
    language: "en",
    genres: ["digital-distribution", "diy-distribution", "streaming-platforms", "electronic", "latin", "hip-hop", "world", "subscription-boundary", "manual-review"],
    submissionMethod: "official-symphonic-starter-paid-distribution-release-upload-route",
    feeRequired: true,
    feeAmount: "Yearly-fee DIY option observed; exact active pricing and terms require manual review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required for plan selection, release metadata, delivery, rights, royalties, tax and payout settings.",
    notes: "Public research verified Symphonic Starter as a DIY distribution option. No protected workflow was entered."
  },
  {
    name: "GYROstream Australian Global Distribution Artist Release Upload Route",
    websiteUrl: "https://www.gyrostream.com/",
    submissionUrl: "https://www.gyrostream.com/",
    sourceUrl: "https://www.gyrostream.com/",
    sourceType: "automation_run_151_public_research",
    country: "Global / Australia-based digital music distribution and artist-services company with offices across multiple countries",
    language: "en",
    genres: ["digital-distribution", "artist-services", "streaming-platforms", "electronic", "pop", "hip-hop", "world", "paid-route", "manual-review"],
    submissionMethod: "official-gyrostream-global-distribution-artist-release-upload-route",
    feeRequired: true,
    feeAmount: "Distribution and artist-service terms require manual review before release setup.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required for service scope, release metadata, delivery, rights, royalty collection, tax/payout settings and territory strategy.",
    notes: "Public research verified GYROstream as an international digital music distribution platform. No protected workflow was entered."
  },
  {
    name: "Labelcaster Digital Delivery Royalty Splits Artist Label Release Route",
    websiteUrl: "https://labelcaster.com/",
    submissionUrl: "https://labelcaster.com/",
    sourceUrl: "https://labelcaster.com/",
    sourceType: "automation_run_151_public_research",
    country: "Global / online music distribution platform for independent artists and labels",
    language: "en",
    genres: ["digital-distribution", "artist-label-tools", "royalty-splits", "spotify", "apple-music", "tiktok", "deezer", "manual-review"],
    submissionMethod: "official-labelcaster-digital-delivery-artist-label-release-route",
    feeRequired: false,
    feeAmount: "Pricing and split terms were not fully exposed in parsed public research and require manual review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required for account access, roster setup, release metadata, DSP selection, split configuration, rights, payout and tax settings.",
    notes: "Public research verified Labelcaster as a digital delivery and royalty split platform. No protected workflow was entered."
  },
  {
    name: "Subvert Artist Owned Marketplace Founder Member Release Route",
    websiteUrl: "https://subvert.fm/",
    submissionUrl: "https://subvert.fm/",
    sourceUrl: "https://subvert.fm/docs/",
    sourceType: "automation_run_151_public_research",
    country: "Global / United States-based cooperatively owned artist and label marketplace in phased rollout",
    language: "en",
    genres: ["direct-to-fan", "artist-owned-marketplace", "digital-downloads", "cooperative-membership", "independent-labels", "electronic", "experimental", "manual-review"],
    submissionMethod: "official-subvert-artist-owned-marketplace-founder-member-release-route",
    feeRequired: false,
    feeAmount: "Artist/label membership and access status require manual review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required for phased access, cooperative membership, governance, catalog upload, content policy, release, pricing and ownership choices.",
    notes: "Public research verified Subvert as a cooperatively owned marketplace in phased rollout. No protected workflow was entered."
  },
  ...run152SeedPlatforms
];