import type { PlatformInput } from '../models/types.js';

export const run110SeedPlatforms: PlatformInput[] = [
  {
    name: "KEXP Rotation Consideration Digital Music Director Submission Route",
    websiteUrl: "https://www.kexp.org/",
    submissionUrl: "https://www.kexp.org/about/submission-guidelines/",
    sourceUrl: "https://www.kexp.org/about/submission-guidelines/",
    sourceType: "automation_run_110_public_research",
    country: "United States / Seattle listener-powered music-discovery radio digital submission route",
    language: "en",
    genres: ["kexp", "public-radio", "listener-powered-radio", "music-discovery", "independent-music", "electronic", "reggae", "dub", "world", "bass-music", "alternative", "digital-download", "wav-links", "music-director-email", "free-first", "manual-review"],
    submissionMethod: "official-kexp-digital-music-director-rotation-consideration-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KEXP asks for a concise digital submission package with streaming and WAV download links, release metadata, clean/FCC-safe edits, lyrics, credits, bio or one-sheet and no attachments or physical media; pitch wording and asset readiness must be checked manually before any email is sent.",
    notes: "Public research confirmed KEXP's official submission guidelines are live and route airplay consideration to the Music Director/Music Department email path. The page says KEXP cannot guarantee spins or responses, prefers digital submissions and does not use pay-to-play. No email was sent, no download link was delivered, no physical material was prepared and no mailbox probing was performed."
  },
  {
    name: "WFMU Music Director Physical Review Package Submission Route",
    websiteUrl: "https://wfmu.org/",
    submissionUrl: "https://wfmu.org/sendmusic.html",
    sourceUrl: "https://wfmu.org/sendmusic.html",
    sourceType: "automation_run_110_public_research",
    country: "United States / Jersey City independent freeform radio physical music-review route",
    language: "en",
    genres: ["wfmu", "freeform-radio", "independent-radio", "community-radio", "experimental", "electronic", "reggae", "dub", "world", "leftfield", "alternative", "physical-mail", "vinyl", "cd", "cassette", "music-director", "free-first", "manual-review"],
    submissionMethod: "official-wfmu-music-director-physical-review-package-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WFMU's authorized route is a physical review-package workflow for vinyl, CD, CD-R or cassette addressed to the Music Director; media choice, package contents, metadata, clean/edit notes and shipping handling must remain manual.",
    notes: "Public research confirmed WFMU is active in July 2026 with recent archives/playlists and a current Send Us Music page. The official route welcomes physical materials for review and provides postal and courier addresses for the Music Director. No email was sent, no physical package was prepared, no account/login was used and no session or anti-bot boundary was touched."
  },
  {
    name: "NTS Radio Show Proposal and Supporter Mix Submission Route",
    websiteUrl: "https://www.nts.live/",
    submissionUrl: "https://www.nts.live/contact",
    sourceUrl: "https://ntslive.freshdesk.com/support/solutions/articles/77000570099-show-proposals",
    sourceType: "automation_run_110_public_research",
    country: "United Kingdom / global online radio show-proposal and supporter-mix route",
    language: "en",
    genres: ["nts", "online-radio", "global-radio", "radio-show-proposal", "mixtape", "supporter-radio", "electronic", "reggae", "dub", "world", "bass", "ambient", "jungle", "free-and-paid", "public-form", "account-boundary", "manual-review"],
    submissionMethod: "official-nts-radio-show-proposal-and-supporter-mix-submission-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because NTS has a public radio-show proposal form with demo-link fields and a separate Supporter Radio mix route that requires becoming an NTS Supporter; account, subscription, show concept, demo links, genre fit and submission timing require owner approval before use.",
    notes: "Public research confirmed NTS is active in July 2026, shows a current homepage callout inviting mixtape submissions, documents show proposals through its support center and exposes a Radio Show Proposal form accepting up to three SoundCloud, Mixcloud or YouTube demo links. The Supporter Radio mix path is a free and paid/subscriber-side route. No account was created, no supporter subscription was started, no form was submitted and no CAPTCHA/session-control interaction occurred."
  },
  {
    name: "WXPN Airplay and Local Show Digital EPK Submission Route",
    websiteUrl: "https://xpn.org/",
    submissionUrl: "https://xpn.org/contact/",
    sourceUrl: "https://xpn.org/contact/",
    sourceType: "automation_run_110_public_research",
    country: "United States / Philadelphia public radio airplay and local-show digital submission route",
    language: "en",
    genres: ["wxpn", "xpn", "public-radio", "adult-album-alternative", "world-cafe", "independent-music", "electronic", "reggae", "dub", "world", "alternative", "local-show", "digital-epk", "download-link", "free-first", "manual-review"],
    submissionMethod: "official-wxpn-airplay-and-local-show-digital-epk-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WXPN asks for an EPK with a digital download link for airplay consideration and a separate Local Show route requiring WAV or high-quality MP3, bio and upcoming-show information; route choice, local relevance, metadata and pitch copy must be reviewed manually.",
    notes: "Public research confirmed WXPN is active in July 2026 with current music news and its official How to Reach Us page lists music submissions for airplay and The Local Show. The page says unsolicited submissions cannot be confirmed for receipt or airplay. No email was sent, no download link was delivered, no event/calendar route was used and no mailbox probing was performed."
  },
  {
    name: "Atwood Magazine Editorial Pitching Music Submission Route",
    websiteUrl: "https://atwoodmagazine.com/",
    submissionUrl: "https://atwoodmagazine.com/pitching-us/",
    sourceUrl: "https://atwoodmagazine.com/pitching-us/",
    sourceType: "automation_run_110_public_research",
    country: "United States / global online music magazine editorial pitch route",
    language: "en",
    genres: ["atwood-magazine", "music-blog", "online-magazine", "editorial-pitch", "premieres", "today-song", "album-review", "ep-review", "interview", "independent-music", "electronic", "reggae", "dub", "world", "obfuscated-contact", "free-first", "manual-review"],
    submissionMethod: "official-atwood-magazine-editorial-pitching-music-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Atwood Magazine asks for a direct music link, very short context, artist/social links, a clear coverage ask, one-follow-up maximum and at least three weeks of notice for premiere opportunities; the public editorial email is obfuscated and must not be decoded or guessed automatically.",
    notes: "Public research confirmed Atwood Magazine is active in July 2026 with recent music posts and an official Pitching Us page. The page explicitly welcomes music from around the world and gives submission guidance for reviews, premieres, interviews and related coverage. No email was sent, the obfuscated contact was not decoded, no protected contact was guessed and no SMTP/MX probing was performed."
  }
];