import type { PlatformInput } from '../models/types.js';
import { run139SeedPlatforms } from './run139PlatformSeeds.js';

export const run138SeedPlatforms: PlatformInput[] = [
  {
    name: "Musosoup Artist Campaign Curator Playlist Press Submission Route",
    websiteUrl: "https://musosoup.com/",
    submissionUrl: "https://app.musosoup.com/",
    sourceUrl: "https://musosoup.com/",
    sourceType: "automation_run_138_public_research",
    country: "United Kingdom / global independent music promotion marketplace connecting artists with curators, playlists, press, radio and social media opportunities",
    language: "en",
    genres: ["musosoup", "music-promotion", "curator-marketplace", "playlisting", "press", "radio", "electronic", "world-music", "hip-hop", "free-first", "campaign-fee", "account-required", "manual-review"],
    submissionMethod: "official-musosoup-artist-campaign-curator-playlist-press-submission-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Musosoup allows free initial music upload/link submission but requires platform review, account creation after approval, campaign activation, campaign-fee decisions and owner-controlled curator-offer acceptance before any promotion runs.",
    notes: "Official Musosoup pages show a Submit music route, artist sign-in/app boundary, free upload/link start, review before approval, campaign activation with payment after approval, curator offers and free/paid coverage options. No account was created, no app workflow was entered, no music/link was uploaded, no campaign was activated, no curator offer was accepted and no payment was initiated."
  },
  {
    name: "DailyPlaylists Free Spotify Playlist Curator Submission Route",
    websiteUrl: "https://dailyplaylists.com/",
    submissionUrl: "https://dailyplaylists.com/",
    sourceUrl: "https://dailyplaylists.com/",
    sourceType: "automation_run_138_public_research",
    country: "Global / Spotify-focused playlist pitching and curator marketplace with standard free submissions and paid/pro credit options",
    language: "en/es/pt",
    genres: ["dailyplaylists", "spotify-playlists", "playlist-submission", "curator-marketplace", "standard-free", "premium-credits", "artist-pro", "track-explorer", "business-email", "account-required", "manual-review"],
    submissionMethod: "official-dailyplaylists-free-spotify-playlist-curator-submission-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because DailyPlaylists requires sign-in/searching for a track, playlist/curator selection, Spotify/link handling, submission-volume choices and premium/pro credit boundaries that must remain owner-controlled.",
    notes: "Official DailyPlaylists pages show Submit a Song, Sign In, a free Standard tier, access to a playlist/curator marketplace, premium credits, a professional tier and the public business email info@dailyplaylists.com. No login was used, no Spotify authorization was granted, no song was searched/submitted, no curator or playlist was selected and no paid tier or credit purchase was started."
  },
  {
    name: "Obscure Sound Electronic Indie Blog SubmitHub Musosoup Email Submission Route",
    websiteUrl: "https://www.obscuresound.com/",
    submissionUrl: "https://www.obscuresound.com/about/contact/",
    sourceUrl: "https://www.obscuresound.com/about/contact/",
    sourceType: "automation_run_138_public_research",
    country: "United States / independent music blog covering electronic, ambient, hip-hop, alt-R&B, indie pop, dream pop, folk and more",
    language: "en",
    genres: ["obscure-sound", "music-blog", "electronic", "ambient", "alt-rnb", "hip-hop", "indie-pop", "submithub", "musosoup", "direct-email", "redacted-contact", "manual-review"],
    submissionMethod: "official-obscure-sound-submithub-musosoup-direct-email-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Obscure Sound offers multiple authorized routes with different expectations: SubmitHub for singles/feedback, SubmitHub Marketplace for longer releases, MusoSoup for single or album curator distribution, and direct email with streaming link, press photo and release background; route choice and pitch package need owner approval.",
    notes: "Official Obscure Sound pages show active July 2026 coverage, a Contact/Submissions page, accepted genres including Electronic/Ambient/Hip-Hop/Alt-R&B, prioritized SubmitHub/MusoSoup routes and a direct-email route. The page masked email text in the fetched public view, so no protected contact was decoded. No SubmitHub/MusoSoup workflow was entered, no email was sent and no link/photo/EPK was delivered."
  },
  {
    name: "A&R Factory Electronic Music Free Paid Editorial Review Submission Route",
    websiteUrl: "https://www.anrfactory.com/",
    submissionUrl: "https://www.anrfactory.com/submit-demo/electronic-music/",
    sourceUrl: "https://www.anrfactory.com/submit-demo/electronic-music/",
    sourceType: "automation_run_138_public_research",
    country: "United Kingdom / internationally focused A&R blog and independent-artist discovery platform with electronic, EDM, reggae, world and genre-specific submission forms",
    language: "en",
    genres: ["a-r-factory", "music-blog", "electronic", "edm", "drum-and-bass", "dancehall", "reggae", "world", "genre-form", "free-submission", "paid-review-option", "payment-form", "manual-review"],
    submissionMethod: "official-ar-factory-electronic-music-free-paid-editorial-review-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because A&R Factory exposes a multi-step form requiring artist identity, genre, track link, release status/date, socials, image/EPK, email, budget context and package selection, including free and paid payment-card/PayPal routes.",
    notes: "Official A&R Factory pages show active July 2026 posts, Submit Your Music navigation, genre-specific Electronic submission guidance, support for many MarcsMusic-relevant genres, a free editorial submission option and paid Standard/Premium package/payment fields. No form was submitted, no payment fields were touched, no package was selected and no track/social/EPK link was delivered."
  },
  {
    name: "WERS Wicked Local Wednesday Boston Artist MP3 Upload Form Route",
    websiteUrl: "https://wers.org/",
    submissionUrl: "https://wers.org/wicked-local-wednesday/",
    sourceUrl: "https://wers.org/wicked-local-wednesday/",
    sourceType: "automation_run_138_public_research",
    country: "United States / Boston-area public radio local-artist feature route with online form and MP3 upload boundary",
    language: "en",
    genres: ["wers", "public-radio", "local-artist", "boston", "wicked-local-wednesday", "mp3-upload", "online-form", "recaptcha", "manual-review"],
    submissionMethod: "official-wers-wicked-local-wednesday-boston-artist-mp3-upload-form-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WERS is a local Boston-area route, the form requests artist/contact/location details and MP3 file upload, and the site discloses reCAPTCHA protection; this cannot be automated and may not fit MarcsMusic unless there is a Boston/local angle.",
    notes: "Official WERS pages show active July 2026 music content, a Submit Music menu route to Wicked Local Wednesday, local-artist form fields, required contact/location data, MP3 upload with 39 MB max file size and reCAPTCHA protection. No form was filled, no file was uploaded, no reCAPTCHA was touched and no local-fit claim was made."
  },
  ...run139SeedPlatforms
];
