import type { PlatformInput } from '../models/types.js';

export const run150SeedPlatforms: PlatformInput[] = [
  {
    name: "Audiomack Creator Upload Unlimited Music Discovery Route",
    websiteUrl: "https://audiomack.com/",
    submissionUrl: "https://creators.audiomack.com/upload",
    sourceUrl: "https://creators.audiomack.com/upload",
    sourceType: "automation_run_150_public_research",
    country: "Global / United States-based on-demand streaming and audio-discovery platform with creator upload workflow",
    language: "en",
    genres: ["artist-upload", "streaming-discovery", "hip-hop", "afrobeats", "latin", "r-and-b", "electronic", "creator-app", "account-boundary", "manual-review"],
    submissionMethod: "official-audiomack-creator-upload-unlimited-music-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Audiomack exposes login/account and JavaScript upload workflows, supported file constraints, copyright compliance warnings, optional monetization tools and release metadata decisions that must remain owner-controlled.",
    notes: "Public research verified Audiomack's official Upload and Creator App routes. The upload route supports Song and Album/EP choices, states unlimited storage is free, lists supported file types and warns that uploads are for artists/content creators only with infringing accounts banned. No account was created, no JavaScript upload workflow was executed, no audio was uploaded and no business inquiry was sent."
  },
  {
    name: "Bandcamp Artist Direct-to-Fan Store Release Upload Route",
    websiteUrl: "https://bandcamp.com/",
    submissionUrl: "https://bandcamp.com/artists?from=footer",
    sourceUrl: "https://bandcamp.com/artists?from=footer",
    sourceType: "automation_run_150_public_research",
    country: "Global / direct-to-fan online record store and music community for artists, labels and fans",
    language: "en",
    genres: ["artist-store", "direct-to-fan", "digital-albums", "tracks", "merch", "electronic", "ambient", "reggae", "world", "account-boundary", "manual-review"],
    submissionMethod: "official-bandcamp-artist-direct-to-fan-store-release-upload-route",
    feeRequired: false,
    feeAmount: "Free artist account; public page lists 15% digital revenue share, 10% merch revenue share and optional Bandcamp Pro at $10/month.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Bandcamp store/release setup requires account access, artist profile control, pricing, revenue-share awareness, PayPal/payment setup, artwork/audio metadata and optional Bandcamp Pro/private-streaming decisions.",
    notes: "Public research verified Bandcamp for Artists as an official route to create a direct-to-fan store and marketplace presence, with free artist accounts, revenue-share pricing, fan messaging, stats, pricing control, release promotion and optional Pro features. No signup was started, no release/store was configured, no private stream was created and no payment settings were entered."
  },
  {
    name: "SoundCloud Artist Upload and Fan Discovery Route",
    websiteUrl: "https://soundcloud.com/",
    submissionUrl: "https://soundcloud.com/upload",
    sourceUrl: "https://soundcloud.com/upload",
    sourceType: "automation_run_150_public_research",
    country: "Global / creator audio-sharing and music-discovery network with direct fan engagement",
    language: "en",
    genres: ["artist-upload", "audio-sharing", "fan-discovery", "electronic", "dubstep", "reggae", "hip-hop", "creator-tools", "pro-plan-side-route", "manual-review"],
    submissionMethod: "official-soundcloud-artist-upload-and-fan-discovery-route",
    feeRequired: false,
    feeAmount: "Public upload route lists 180 minutes of free uploads and links to Pro plans as an optional side route.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because SoundCloud upload requires a JavaScript/account session, track ownership and rights review, public/private visibility choices, metadata, artwork, engagement settings and optional Pro-plan decisions.",
    notes: "Public research verified SoundCloud's official upload route as a way for creators to share tracks, connect with fans, access stats and use creator tools. The page exposes free upload capacity and a Pro-plan side route. No account was created, no upload button was entered, no track or artwork was uploaded and no paid plan was selected."
  },
  {
    name: "Jamendo Artist Publishing and Licensing Opt-In Route",
    websiteUrl: "https://www.jamendo.com/",
    submissionUrl: "https://www.jamendo.com/",
    sourceUrl: "https://www.jamendo.com/",
    sourceType: "automation_run_150_public_research",
    country: "Global / Luxembourg independent-music community and licensing marketplace for Creative Commons and commercial-use catalog routes",
    language: "en",
    genres: ["artist-publishing", "creative-commons", "music-licensing", "sync-licensing", "background-music", "instrumental", "world", "electronic", "account-boundary", "manual-review"],
    submissionMethod: "official-jamendo-artist-publishing-and-licensing-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Jamendo artist publishing/licensing depends on account access, collecting-society compatibility, license selection, rights clearance, artist profile metadata and optional commercial licensing opt-in choices.",
    notes: "Public research verified Jamendo as an independent-artist music platform and licensing marketplace where artists can publish music and manage artist profiles, with Jamendo Licensing providing commercial-use licensing and an artist opt-in/out revenue-share route. No account was created, no catalog was uploaded, no license was selected and no licensing opt-in was activated."
  },
  {
    name: "BeatStars Marketplace Producer Artist Licensing Upload Route",
    websiteUrl: "https://www.beatstars.com/",
    submissionUrl: "https://www.beatstars.com/",
    sourceUrl: "https://www.beatstars.com/",
    sourceType: "automation_run_150_public_research",
    country: "Global / music licensing marketplace for producers, recording artists and songwriters",
    language: "en",
    genres: ["beat-marketplace", "producer-upload", "music-licensing", "hip-hop", "r-and-b", "dancehall", "afrobeats", "collaborator-splits", "paid-tier-side-route", "manual-review"],
    submissionMethod: "official-beatstars-marketplace-producer-artist-licensing-upload-route",
    feeRequired: false,
    feeAmount: "Free and paid subscription models observed; license terms and seller pricing are configurable and require manual review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because BeatStars marketplace use requires account access, seller/buyer role selection, beat or song ownership review, license type, price, collaborator splits, publishing administration and paid-tier decisions.",
    notes: "Public research verified BeatStars as a global music licensing marketplace where artists and producers collaborate, license and distribute work through non-exclusive and exclusive license types, with free and paid subscription models and configurable licenses. No account was created, no marketplace listing was entered, no license was configured and no payment/subscription was started."
  }
];
