import type { PlatformInput } from '../models/types.js';

export const run123SeedPlatforms: PlatformInput[] = [
  {
    name: "RepostExchange Official SoundCloud Repost Campaign and Feedback Route",
    websiteUrl: "https://repostexchange.com/",
    submissionUrl: "https://repostexchange.com/welcome",
    sourceUrl: "https://repostexchange.com/welcome",
    sourceType: "automation_run_123_public_research",
    country: "Global / SoundCloud creator repost campaign and feedback network",
    language: "en",
    genres: ["repostexchange", "soundcloud", "repost-campaigns", "feedback", "creator-network", "dubstep", "electronic", "edm", "reggae", "free-first", "credits", "login", "manual-review"],
    submissionMethod: "official-repostexchange-soundcloud-repost-campaign-feedback-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because RepostExchange uses SoundCloud account connection, track selection, credit allocation, repost-request or targeted-campaign choices and optional paid credits/plans. Account authorization, track fit, credit spend, manual repost choices and platform-compliance boundaries require owner review.",
    notes: "Official public research confirmed RepostExchange is active in 2026, presents itself as an official SoundCloud partner, lists free usage with starter credits, current campaign/activity sections, and explains that artists choose which repost/follow/like/comment actions happen. No SoundCloud account was connected, no campaign was created and no repost request was sent."
  },
  {
    name: "Hypeddit Music Promotion Download Gate Smart Link and Pre-Save Route",
    websiteUrl: "https://hypeddit.com/",
    submissionUrl: "https://hypeddit.com/",
    sourceUrl: "https://hypeddit.com/",
    sourceType: "automation_run_123_public_research",
    country: "Global / independent artist music promotion smart-link download-gate and ad campaign route",
    language: "en",
    genres: ["hypeddit", "music-promotion", "download-gates", "smart-links", "pre-saves", "ai-ads", "spotify", "soundcloud", "youtube", "edm", "electronic", "freemium", "login", "manual-review"],
    submissionMethod: "official-hypeddit-music-promotion-download-gate-smart-link-presave-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Hypeddit routes artists through login/trial setup, song upload or link handling, goal/campaign selection, download-gate, pre-save, smart-link and paid-ad choices, plus cookie/session controls. Asset upload, ad-budget decisions, fan-data collection and link delivery must remain owner-reviewed.",
    notes: "Official public research confirmed Hypeddit is active in 2026, offers artist music-promotion tools including AI-powered ads, download gates, smart links, pre-saves, fan promotion and promotion exchange, and exposes login/Try for free routes plus paid-plan language. No account was opened, no song was uploaded, no smart link was created and no campaign was started."
  },
  {
    name: "Radio Airplay Jango Internet Radio Upload Review Contest and Airplay Route",
    websiteUrl: "https://www.radioairplay.com/",
    submissionUrl: "https://www.radioairplay.com/music+promotion/guaranteed_airplay",
    sourceUrl: "https://www.radioairplay.com/music+promotion/guaranteed_airplay",
    sourceType: "automation_run_123_public_research",
    country: "Global / Jango internet-radio artist upload airplay review and contest route",
    language: "en",
    genres: ["radio-airplay", "jango", "internet-radio", "song-reviews", "free-contests", "playlist-opportunities", "sync-partner-offers", "upload-tracks", "freemium", "login", "manual-review"],
    submissionMethod: "official-radio-airplay-jango-upload-review-contest-airplay-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Radio Airplay uses account sign-up/login, track upload, target-artist matching, song-review or airplay package choices, free contest eligibility and paid package tiers. Track selection, style targeting, account access, budget approval and public fan-facing profile choices must remain owner-reviewed.",
    notes: "Official public research confirmed Radio Airplay is active through 2026, publishes a Free Sign Up route, asks artists to upload tracks, offers song reviews and contests, lists free and paid airplay packages, and exposes premium@radioairplay.com as a public deal/contact route. No account was created, no file was uploaded and no package was selected."
  },
  {
    name: "Play MPE Caster Radio Curator Supervisor and Media Release Promotion Route",
    websiteUrl: "https://www.plaympe.com/",
    submissionUrl: "https://www.plaympe.com/",
    sourceUrl: "https://www.plaympe.com/",
    sourceType: "automation_run_123_public_research",
    country: "Global / professional release-promotion route to radio programmers media supervisors bloggers and curators",
    language: "en",
    genres: ["play-mpe", "caster", "radio-promotion", "music-supervisors", "media", "bloggers", "curators", "wav", "aiff", "metadata", "isrc", "paid", "login", "manual-review"],
    submissionMethod: "official-play-mpe-caster-radio-curator-supervisor-media-release-promotion-route",
    feeRequired: true,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Play MPE Caster involves account/session access, mastered WAV/AIFF upload, artwork, ISRC and publishing metadata, campaign construction, radio target-market package selection and paid tracking or promotion-plan decisions. Release assets, rights, budget and recipient selection require owner review.",
    notes: "Official public research confirmed Play MPE is active as a platform for labels, managers and artists to promote releases to verified industry contacts, upload mastered music files and artwork, build campaigns and distribute/track radio promotion. No Caster session was entered, no release was uploaded and no campaign or payment route was initiated."
  },
  {
    name: "Promoly DJ Tastemaker Promo Mailout Feedback and Smartlink Route",
    websiteUrl: "https://promoly.com/",
    submissionUrl: "https://promoly.com/",
    sourceUrl: "https://promoly.com/",
    sourceType: "automation_run_123_public_research",
    country: "Global / DJ tastemaker promo mailout feedback smartlink and pre-save route",
    language: "en",
    genres: ["promoly", "dj-promo", "tastemaker-network", "music-publicists", "labels", "artists", "feedback", "smartlinks", "pre-save", "mailout", "free-trial", "login", "manual-review"],
    submissionMethod: "official-promoly-dj-tastemaker-promo-mailout-feedback-smartlink-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Promoly requires app access/free-trial setup, track or UPC upload, artwork/description prep, contact-list import or Tastemaker Network targeting, promo send decisions, smartlink/pre-save options and follow-up automation settings. Uploads, contact targeting, recipient consent, trial/payment boundaries and outbound messages must remain owner-reviewed.",
    notes: "Official public research confirmed Promoly is active in 2026, offers a 7-day free trial with 150 free sends, lets artists upload tracks, pick contacts, send promos and track opens/plays/downloads, and lists a 1,300+ DJ Tastemaker Network. No account was opened, no contacts were imported, no promo was sent and no file/link was delivered."
  }
];