import type { PlatformInput } from '../models/types.js';

export const run191BaseSeedPlatforms: PlatformInput[] = [
  {
    name: "Music Xray Paid A&R Song Opportunity Submission Route",
    websiteUrl: "https://www.musicxray.com/",
    submissionUrl: "https://www.musicxray.com/",
    sourceUrl: "https://www.musicxray.com/",
    sourceType: "automation_run_191_public_research",
    country: "Global / paid A&R song-to-opportunity matching and guaranteed-listen platform",
    language: "en",
    genres: ["a-and-r", "song-opportunities", "professional-feedback", "industry-submission", "sync", "radio", "electronic", "reggae", "world", "manual-review"],
    submissionMethod: "official-music-xray-paid-a-and-r-song-opportunity-platform-route",
    feeRequired: true,
    feeAmount: "Paid/manual opportunity route; public references describe an online platform where artists submit songs to industry professionals, typically paying a fee for a guaranteed listen and response.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Music Xray is a paid account-based A&R/opportunity workflow with professional targeting, fee, upload, metadata, rights/authorship, genre-fit, AI-content disclosure and value-for-money implications. Owner must approve the selected opportunity and payment before any signup or submission.",
    notes: "Public research identified Music Xray as an active A&R/music-tech platform where artists submit songs to industry professionals and pay for guaranteed listen/response workflows. No account was created, no opportunity was opened behind login, no music was uploaded and no payment was initiated."
  },
  {
    name: "Broadjam Artist Upload Licensing Radio Review Route",
    websiteUrl: "https://www.broadjam.com/",
    submissionUrl: "https://www.broadjam.com/",
    sourceUrl: "https://www.broadjam.com/",
    sourceType: "automation_run_191_public_research",
    country: "Global / independent artist song upload, licensing, review and radio-play opportunity platform",
    language: "en",
    genres: ["artist-platform", "song-upload", "licensing", "sync", "radio-play", "song-contests", "professional-review", "electronic", "world", "manual-review"],
    submissionMethod: "official-broadjam-artist-song-upload-licensing-radio-review-route",
    feeRequired: true,
    feeAmount: "Freemium/paid manual route; public references describe memberships, song uploads, radio play, professional reviews, contests and film/TV/commercial placement opportunities, with account/fee details requiring review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Broadjam is an account platform with song uploads, contests, licensing, radio/review options, possible membership fees, public profile/download settings and placement terms. Owner must approve membership tier, target opportunity, rights, splits, metadata and pricing before any upload or submission.",
    notes: "Public research identified Broadjam as an independent musician platform with song upload, review, radio play, contest and licensing/placement routes. No login, profile, upload, contest entry, licensing configuration, email or payment action was performed."
  },
  {
    name: "Free Music Archive Creative Commons Curated Upload Permission Route",
    websiteUrl: "https://freemusicarchive.org/",
    submissionUrl: "https://freemusicarchive.org/",
    sourceUrl: "https://freemusicarchive.org/",
    sourceType: "automation_run_191_public_research",
    country: "Netherlands / Global Creative Commons music archive and curated upload-permission route",
    language: "en",
    genres: ["creative-commons", "free-music-archive", "curated-upload", "open-license", "podcast-safe", "electronic", "dub", "world", "manual-review"],
    submissionMethod: "official-free-music-archive-curated-upload-permission-open-license-route",
    feeRequired: false,
    feeAmount: "Free-first/manual curated route; public references describe FMA as an open music archive where content is curated and upload/edit permission is granted by invitation or permission rather than unrestricted self-service.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because FMA involves curated permission, account/access boundaries, Creative Commons/open-license selection, royalty/PRO implications, downloadability, commercial-use settings and long-term rights exposure. Owner must approve licensing strategy before any account, upload-permission request or track publication.",
    notes: "Public research identified FMA as a Creative Commons/open music archive currently associated with Tribe of Noise, with curated audio content and permission-based upload/edit access. No account, permission request, upload, license selection or contact action was performed."
  },
  {
    name: "Boxout.fm Alternative Community Radio Artist Contribution Route",
    websiteUrl: "https://boxout.fm/",
    submissionUrl: "https://boxout.fm/",
    sourceUrl: "https://boxout.fm/",
    sourceType: "automation_run_191_public_research",
    country: "India / Global alternative community internet radio artist contribution route",
    language: "en",
    genres: ["internet-radio", "community-radio", "alternative", "electronic", "dj-mix", "world", "india", "artist-contribution", "manual-review"],
    submissionMethod: "official-boxout-fm-alternative-community-radio-artist-contribution-route",
    feeRequired: false,
    feeAmount: "Free-first/manual community-radio route; public references state that the station welcomes submissions from artists looking to contribute musically to its programs, while the exact current public submission endpoint needs manual confirmation.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Boxout.fm is a curated community-radio route where the exact current delivery endpoint, genre/show fit, track vs mix format, rights/authorship, explicit-content handling, India/global relevance and no-bulk pitch wording must be confirmed before any outreach.",
    notes: "Public research identified Boxout.fm as an online community radio station based in New Delhi with global streaming/archive context and artist submission/contribution language. No contact form, email, upload, DM or pitch was sent."
  },
  {
    name: "Hype Machine Blog Directory Manual Curator Outreach Route",
    websiteUrl: "https://hypem.com/",
    submissionUrl: "https://hypem.com/blogs",
    sourceUrl: "https://hypem.com/",
    sourceType: "automation_run_191_public_research",
    country: "Global / music-blog aggregator and manual blog-directory curator-outreach route",
    language: "en",
    genres: ["music-blogs", "blog-aggregator", "electronic", "indie", "remixes", "soundcloud", "curator-research", "manual-review"],
    submissionMethod: "official-hype-machine-blog-directory-authorized-blog-outreach-route",
    feeRequired: false,
    feeAmount: "Free-first/manual research route; Hype Machine itself is an aggregator, so submissions should not be sent to Hype Machine unless an official route is present. The queued route is to use the public blog directory to identify individual blogs, then only use each blog's own authorized submission route.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Hype Machine is not a direct submission inbox. Each downstream blog must be verified individually for activity, authorized submission method, contact preferences, anti-spam rules, SoundCloud/private-link requirements, genre fit and no-payment/no-login boundaries before any outreach is queued.",
    notes: "Public research identified Hype Machine as an active music-blog aggregator with a blog directory and historical SoundCloud/blog servicing context. No scraping beyond public discovery, no blog contact extraction, no emails and no submissions were performed."
  }
];
