import type { PlatformInput } from '../models/types.js';

export const run182SeedPlatforms: PlatformInput[] = [
  {
    name: "Bandcamp Artist Direct-to-Fan Upload Store Route",
    websiteUrl: "https://bandcamp.com/",
    submissionUrl: "https://bandcamp.com/",
    sourceUrl: "https://en.wikipedia.org/wiki/Bandcamp",
    sourceType: "automation_run_182_public_research",
    country: "Global / independent artist direct-to-fan upload and sales route",
    language: "en",
    genres: ["independent-artists", "direct-to-fan", "electronic", "world", "reggae", "dub", "downloads", "merch", "wav", "flac", "aiff", "manual-review"],
    submissionMethod: "official-bandcamp-artist-upload-direct-to-fan-store-route",
    feeRequired: false,
    feeAmount: "Artist upload/storefront entry is free-first, but Bandcamp sales commissions, payment processing, download settings, merch options, tax/payment setup and AI/content policy require manual review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Bandcamp uses an artist account/storefront workflow with rights ownership, release metadata, download formats, pricing, revenue share, payout setup, merch settings and current AI-content policy obligations that must be approved by the owner before any upload or sale configuration.",
    notes: "Public research verified Bandcamp as an active direct-to-fan music distribution platform where artists/labels upload music, control pricing and sell music/merch; 2026 public reporting also confirmed a strict AI-generated-content policy. No account, storefront, upload, sale, payout or message action was initiated."
  },
  {
    name: "SoundClick Artist MP3 Upload Store Licensing Route",
    websiteUrl: "https://www.soundclick.com/",
    submissionUrl: "https://www.soundclick.com/",
    sourceUrl: "https://en.wikipedia.org/wiki/SoundClick",
    sourceType: "automation_run_182_public_research",
    country: "Global / artist profile MP3 upload store and licensing route",
    language: "en",
    genres: ["artist-profile", "mp3-upload", "electronic", "dance", "hip-hop", "beats", "licensing", "store", "social-music", "freemium", "manual-review"],
    submissionMethod: "official-soundclick-artist-upload-store-licensing-route",
    feeRequired: false,
    feeAmount: "SoundClick publicly describes free MP3 upload/profile functionality with optional VIP and store/licensing monetization; account, VIP, store, PayPal and licensing terms require manual review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because SoundClick upload/store/licensing workflows require account/session handling, track ownership review, MP3 quality choices, stream/download/sale/license settings, optional VIP services and payout/commercial terms approval.",
    notes: "Public research verified SoundClick as an active music-based social community where artists can upload MP3 songs, stream, offer downloads, sell through a store and license songs. No account, upload, store, license, VIP or payment workflow was entered."
  },
  {
    name: "Jamendo Independent Artist Free Publishing Licensing Route",
    websiteUrl: "https://www.jamendo.com/",
    submissionUrl: "https://www.jamendo.com/",
    sourceUrl: "https://en.wikipedia.org/wiki/Jamendo",
    sourceType: "automation_run_182_public_research",
    country: "Global / Luxembourg independent artist publishing and licensing route",
    language: "en",
    genres: ["independent-artists", "creative-commons", "licensing", "sync", "background-music", "electronic", "world", "instrumental", "free-publishing", "manual-review"],
    submissionMethod: "official-jamendo-independent-artist-publishing-licensing-route",
    feeRequired: false,
    feeAmount: "Jamendo is free-first for independent artist publication, while licensing participation, Creative Commons choices, collecting-society restrictions and commercial rights need manual review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Jamendo publication and licensing affect copyright licensing, Creative Commons or commercial-use permissions, collecting-society compatibility, artist profile metadata, revenue terms and sync/background-music authorization.",
    notes: "Public research verified Jamendo as an active global independent-artist community and music-licensing service where artists can publish music and use artist profile tools. No registration, upload, license grant, collecting-society declaration or message was submitted."
  },
  {
    name: "BandLab Creator Social Music Distribution Route",
    websiteUrl: "https://www.bandlab.com/",
    submissionUrl: "https://www.bandlab.com/",
    sourceUrl: "https://en.wikipedia.org/wiki/BandLab",
    sourceType: "automation_run_182_public_research",
    country: "Global / social music creation sharing and distribution route",
    language: "en",
    genres: ["creator-platform", "social-music", "collaboration", "distribution", "electronic", "pop", "reggae", "world", "mobile", "freemium", "manual-review"],
    submissionMethod: "official-bandlab-creator-social-music-distribution-route",
    feeRequired: false,
    feeAmount: "BandLab is publicly described as freemium with creation, sharing, selling and distribution functions; account, distribution, collaboration and monetization terms require manual review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because BandLab uses account/app workflows for creation, publishing, collaboration and distribution; rights, collaboration splits, uploads, profile settings, monetization, AI/tool usage and platform terms must be owner-approved.",
    notes: "Public research verified BandLab as an active cloud DAW/social music platform with tens of millions of creators and distribution/selling functions. No account, project, upload, collaboration, distribution or monetization action was initiated."
  },
  {
    name: "BeatStars Producer Beat Licensing Marketplace Route",
    websiteUrl: "https://www.beatstars.com/",
    submissionUrl: "https://www.beatstars.com/",
    sourceUrl: "https://en.wikipedia.org/wiki/BeatStars",
    sourceType: "automation_run_182_public_research",
    country: "Global / producer beat licensing marketplace and distribution route",
    language: "en",
    genres: ["beats", "producer-marketplace", "instrumentals", "hip-hop", "electronic", "dancehall", "reggae", "licensing", "collaborator-splits", "freemium", "manual-review"],
    submissionMethod: "official-beatstars-producer-beat-licensing-marketplace-route",
    feeRequired: false,
    feeAmount: "BeatStars is publicly described with both free and paid subscription models, customizable license types, collaborator splits and marketplace/distribution functions; commercial terms require manual review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because BeatStars marketplace participation can create commercial beat/instrumental license offers; ownership, samples, collaborator splits, publishing, non-exclusive/exclusive license templates, payout setup and subscription terms require owner approval.",
    notes: "Public research verified BeatStars as an active global music licensing marketplace where producers and recording artists collaborate, license works and use free or paid subscription models. No account, beat upload, license template, collaborator split, distribution or payment workflow was entered."
  }
];
