import type { PlatformInput } from '../models/types.js';

export const run178SeedPlatforms: PlatformInput[] = [
  {
    name: "WYEP Pittsburgh Area Music Submissions Email and Hard Copy Route",
    websiteUrl: "https://wyep.org/",
    submissionUrl: "https://wyep.org/about/submissions/",
    sourceUrl: "https://wyep.org/about/submissions/",
    sourceType: "automation_run_178_public_research",
    country: "United States / Pittsburgh Western Pennsylvania public radio local-music route",
    language: "en",
    genres: ["public-radio", "aaa-radio", "pittsburgh", "western-pennsylvania", "local-music", "indie", "electronic", "world", "radio-airplay", "manual-review"],
    submissionMethod: "official-wyep-local-music-email-hard-copy-submission-route",
    feeRequired: false,
    feeAmount: "No submission fee observed; WYEP publishes an official local-music email route and hard-copy mailing option.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WYEP asks for a music link or hard copy, contact/origin/bio context, two to three focus tracks for albums, FCC-clean/radio-edit status, Western Pennsylvania relevance, specialty-show fit and no follow-up expectations.",
    notes: "Public research verified WYEP's official Pittsburgh Music Submissions page, local music feature context, Local 913/Pittsburgh Music Hour paths, localmusic@wyep.org route, hard-copy side route and current 2026 site activity. No email was sent and no physical package was prepared."
  },
  {
    name: "KVRX Austin Physical Digital Music Submission Email Route",
    websiteUrl: "https://www.kvrx.org/app/",
    submissionUrl: "https://www.kvrx.org/app/contact/",
    sourceUrl: "https://www.kvrx.org/app/contact/",
    sourceType: "automation_run_178_public_research",
    country: "United States / Austin student-run underground independent radio route",
    language: "en",
    genres: ["college-radio", "student-radio", "austin", "underground-music", "independent", "electronic", "experimental", "local-live", "digital-submission", "physical-submission", "manual-review"],
    submissionMethod: "official-kvrx-physical-digital-music-submission-email-route",
    feeRequired: false,
    feeAmount: "No submission fee observed; KVRX publishes a free music@kvrx.org route for airplay consideration.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KVRX accepts physical and digital music but explicitly excludes AI-assisted/generated submissions, so owner verification of authorship, rights, release assets, genre fit and preferred delivery format is mandatory.",
    notes: "Public research verified KVRX's official contact page, music@kvrx.org submission route, operations@kvrx.org questions route, physical and digital submission statement, underground programming mission and current 2025/2026 site activity. No email was sent and no files were transferred."
  },
  {
    name: "KFAI Minneapolis Music Library Submission Email Route",
    websiteUrl: "https://kfai.org/",
    submissionUrl: "https://kfai.org/about/contact/",
    sourceUrl: "https://kfai.org/about/contact/",
    sourceType: "automation_run_178_public_research",
    country: "United States / Minneapolis Saint Paul eclectic community radio music-library route",
    language: "en",
    genres: ["community-radio", "minneapolis", "saint-paul", "eclectic", "world", "reggae", "soul", "funk", "local-music", "music-library", "manual-review"],
    submissionMethod: "official-kfai-music-library-submission-contact-route",
    feeRequired: false,
    feeAmount: "No submission fee observed; KFAI publishes a Music Department and Music Library contact path for artists sharing music.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KFAI provides a music-library contact path but the crawler rendered the email as a protected link; owner-approved pitch copy, track links, station/program fit and no-response expectation must be reviewed before action.",
    notes: "Public research verified KFAI's official contact page, Music Department and Music Library invitation to share music, active 2026 posts/programming and broad multicultural programming context. Protected email links were observed but not decoded; no message was sent."
  },
  {
    name: "CJSW Calgary Digital Album Jotform Music Submission Route",
    websiteUrl: "https://cjsw.com/",
    submissionUrl: "https://cjsw.com/music/submit/",
    sourceUrl: "https://cjsw.com/music/submit/",
    sourceType: "automation_run_178_public_research",
    country: "Canada / Calgary campus community radio digital album submission form route",
    language: "en",
    genres: ["campus-radio", "community-radio", "calgary", "canadian-independent", "digital-album", "mp3-zip", "electronic", "experimental", "world", "freeform-radio", "manual-review"],
    submissionMethod: "official-cjsw-digital-album-jotform-music-submission-route",
    feeRequired: false,
    feeAmount: "No submission fee observed for CJSW's official digital music submission form; campus mailout is a separate side service.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because CJSW accepts only digital albums released within the last three months, requires three or more unique tracks, rejects singles, requests MP3 files in a ZIP, and routes uploads through a Jotform boundary.",
    notes: "Public research verified CJSW's official Music Submissions page, upload-form link, digital-only policy, no-singles rule, MP3 ZIP requirements, review-rotation explanation, freeform/no-rotation programming model and Music & Performance Director assistance route. No form was opened beyond public discovery and no files were uploaded."
  },
  {
    name: "Sonicbids Rebooted EPK Live Booking Submission Platform Route",
    websiteUrl: "https://sonicbids.com/",
    submissionUrl: "https://app.sonicbids.com/",
    sourceUrl: "https://sonicbids.com/",
    sourceType: "automation_run_178_public_research",
    country: "Global / live booking EPK venue promoter submission platform route",
    language: "en",
    genres: ["artist-opportunities", "live-booking", "epk", "venues", "festivals", "promoters", "independent-artists", "electronic-live", "application-boundary", "manual-review"],
    submissionMethod: "official-sonicbids-epk-live-booking-submission-platform-route",
    feeRequired: false,
    feeAmount: "No mandatory fee was observed on the public homepage; pricing and opportunity terms remain unknown behind the app boundary and must be reviewed manually.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Sonicbids uses Sign Up/Sign In app boundaries, EPK claiming, artist profile data, live booking opportunities, venue/promoter submission workflows and potentially variable opportunity terms that require owner approval.",
    notes: "Public research verified Sonicbids' official 2026 homepage, status update that the platform is back online, brand-new EPK claim route, sign-up/sign-in boundaries, 200,000+ artist and 1,500+ venue positioning, and upcoming submissions/dashboard/partner-tool language. No account was created and no EPK or booking submission was started."
  }
];
