import type { PlatformInput } from '../models/types.js';

export const run137SeedPlatforms: PlatformInput[] = [
  {
    name: "SoundOn TikTok Music Distribution Artist Upload Route",
    websiteUrl: "https://www.soundon.global/",
    submissionUrl: "https://www.soundon.global/",
    sourceUrl: "https://www.soundon.global/",
    sourceType: "automation_run_137_public_research",
    country: "Global / TikTok-owned music marketing and distribution platform with territory eligibility and release-upload workflow",
    language: "en",
    genres: ["soundon", "tiktok", "digital-distribution", "artist-upload", "release-upload", "music-marketing", "royalties", "audience-insights", "account-required", "territory-review", "manual-review"],
    submissionMethod: "official-soundon-tiktok-music-distribution-artist-upload-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because SoundOn is an account/session-bound music distribution route, territory availability and artist eligibility must be checked for MarcsMusic, and release upload requires owner-controlled rights, metadata, artwork, payout and TikTok/DSP delivery decisions.",
    notes: "Public research identifies SoundOn as a TikTok-founded music distribution and artist-services platform where artists can upload music, retain copyright and distribute to additional platforms. No account was created, no login was used, no release was configured, no music or artwork was uploaded, no payout data was entered and no platform session was executed."
  },
  {
    name: "RouteNote Free Premium Digital Distribution Release Upload Route",
    websiteUrl: "https://www.routenote.com/",
    submissionUrl: "https://www.routenote.com/",
    sourceUrl: "https://www.routenote.com/",
    sourceType: "automation_run_137_public_research",
    country: "United Kingdom / worldwide digital music distribution and publishing service with free and premium release routes",
    language: "en",
    genres: ["routenote", "digital-distribution", "free-distribution", "premium-distribution", "spotify", "apple-music", "amazon-music", "youtube-content-id", "publishing", "account-required", "payment-option", "manual-review"],
    submissionMethod: "official-routenote-free-premium-digital-distribution-release-upload-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because RouteNote offers free and premium distribution paths, release upload requires account access, store selection, ownership, metadata, artwork, Content ID and royalty-share choices, and no release should be delivered without owner approval.",
    notes: "Public research identifies RouteNote as a worldwide distribution, publishing and licensing service with free distribution and paid/premium options. No account was created, no login was used, no music or artwork was uploaded, no stores were selected, no Content ID claim was configured and no payment route was entered."
  },
  {
    name: "Amuse Self Service Distribution Artist Subscription Release Upload Route",
    websiteUrl: "https://www.amuse.io/",
    submissionUrl: "https://www.amuse.io/",
    sourceUrl: "https://www.amuse.io/",
    sourceType: "automation_run_137_public_research",
    country: "Sweden / global self-service digital distribution, funding and artist-services platform",
    language: "en",
    genres: ["amuse", "digital-distribution", "self-service-release", "artist-services", "funding", "royalties", "ai-mastering", "subscription-tier", "account-required", "payment-option", "manual-review"],
    submissionMethod: "official-amuse-self-service-distribution-artist-subscription-release-upload-route",
    feeRequired: true,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Amuse is a self-service distribution platform with subscription tiers and connected artist services; release upload, payment plan, rights ownership, metadata, artwork, AI-mastering and funding settings require owner control.",
    notes: "Public research identifies Amuse as a Stockholm-based global music company offering self-service distribution through major streaming services, with subscription tiers and connected artist services. No account was created, no subscription or trial was started, no payment was initiated, no release was configured and no music or artwork was uploaded."
  },
  {
    name: "iMusician Digital Music Distribution Release Upload Route",
    websiteUrl: "https://imusician.pro/",
    submissionUrl: "https://imusician.pro/",
    sourceUrl: "https://imusician.pro/",
    sourceType: "automation_run_137_public_research",
    country: "Switzerland / European independent digital distribution service with multilingual artist release workflows",
    language: "en/fr/de",
    genres: ["imusician", "digital-distribution", "europe", "streaming-platforms", "release-upload", "rights-holder", "account-required", "payment-required", "manual-review"],
    submissionMethod: "official-imusician-digital-music-distribution-release-upload-route",
    feeRequired: true,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because iMusician is an account-bound distribution route where product/pricing, release metadata, artwork, rights-holder information, territory/store choices and payout/tax settings must be confirmed before any submission.",
    notes: "Public research identifies iMusician Digital AG as a Zurich-based independent online music distribution service for musicians and rights holders. No account was created, no login was used, no price plan was selected, no release was configured, no payment was initiated and no upload occurred."
  },
  {
    name: "UnitedMasters Independent Artist Distribution Release Upload Route",
    websiteUrl: "https://www.unitedmasters.com/",
    submissionUrl: "https://www.unitedmasters.com/",
    sourceUrl: "https://www.unitedmasters.com/",
    sourceType: "automation_run_137_public_research",
    country: "United States / worldwide independent artist distribution platform with brand, DSP and social-platform delivery routes",
    language: "en",
    genres: ["unitedmasters", "digital-distribution", "independent-artists", "release-upload", "spotify", "apple-music", "tiktok", "instagram", "brand-opportunities", "account-required", "payment-option", "manual-review"],
    submissionMethod: "official-unitedmasters-independent-artist-distribution-release-upload-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because UnitedMasters is an account/session-bound distribution and artist-services route with plan choices, release upload, platform delivery, brand opportunity, rights, metadata, artwork and payout decisions that need owner approval.",
    notes: "Public research identifies UnitedMasters as a worldwide independent artist distributor whose release workflow lets artists upload music and artwork for distribution across major streaming and social platforms. No account was created, no login was used, no music or artwork was uploaded, no platform delivery was selected and no paid plan or brand-opportunity workflow was entered."
  }
];
