import type { PlatformInput } from '../models/types.js';

export const run111SeedPlatforms: PlatformInput[] = [
  {
    name: "CJSR Edmonton Album EP Digital and Physical Music Department Submission Route",
    websiteUrl: "https://www.cjsr.com/",
    submissionUrl: "https://www.cjsr.com/submit-music/",
    sourceUrl: "https://www.cjsr.com/submit-music/",
    sourceType: "automation_run_111_public_research",
    country: "Canada / Edmonton campus-community radio album and EP submission route",
    language: "en",
    genres: ["cjsr", "campus-radio", "community-radio", "independent-music", "eclectic", "electronic", "reggae", "dub", "world", "hip-hop", "folk", "experimental", "album-ep-only", "physical-mail", "digital-download", "free-first", "manual-review"],
    submissionMethod: "official-cjsr-album-ep-digital-and-physical-music-department-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because CJSR accepts albums and EPs only, asks for files or durable download links rather than paid streaming links, requests track metadata, origin, focus tracks, track lengths, language warnings and tagged MP3s, and also supports physical mail/drop-off package handling.",
    notes: "Public research confirmed CJSR's official Submit Music page is live in 2026 and lists authorized Music Department digital and physical routes. The route exposes a public music email and station mailing address, but no email was sent, no files or download links were delivered, no physical package was prepared and no mailbox probing was performed."
  },
  {
    name: "CJSF 90.1FM NCRA Earshot Distro and Music Coordinator Submission Route",
    websiteUrl: "https://www.cjsf.ca/",
    submissionUrl: "https://www.cjsf.ca/contact-us/departments/music-department",
    sourceUrl: "https://www.cjsf.ca/contact-us/departments/music-department",
    sourceType: "automation_run_111_public_research",
    country: "Canada / Burnaby campus-community radio and national NCRA distribution partner route",
    language: "en",
    genres: ["cjsf", "campus-radio", "community-radio", "ncra", "earshot-distro", "national-music-director-program", "independent-music", "electronic", "world", "reggae", "dub", "jazz", "hip-hop", "broadcast-rights", "external-form", "physical-local-only", "free-first", "manual-review"],
    submissionMethod: "official-cjsf-ncra-earshot-distro-and-music-coordinator-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because CJSF's route involves broadcast-rights authorization, a National Music Director/!earshot Distro form, local-library rules that do not accept singles locally, local-only physical submission limits and email/metadata review by the Music Coordinator.",
    notes: "Public research confirmed CJSF is active in 2026 with current news/programming and an official Music Department page explaining the NCRA National Music Director partnership, release-form handling, broadcast-rights authorization and Music Coordinator contact. No form was opened beyond public static content, no account was created, no email was sent and no protected workflow was bypassed."
  },
  {
    name: "Earshot Distro Canadian Campus Community Radio Upload Route",
    websiteUrl: "https://earshot-distro.ca/",
    submissionUrl: "https://earshot-distro.ca/",
    sourceUrl: "https://earshot-distro.ca/",
    sourceType: "automation_run_111_public_research",
    country: "Canada / national campus and community radio digital distribution platform",
    language: "en",
    genres: ["earshot-distro", "ncra", "campus-radio", "community-radio", "canadian-radio", "digital-distribution", "music-upload", "independent-music", "electronic", "reggae", "dub", "world", "paid-upload", "account-required", "payment-required", "manual-review"],
    submissionMethod: "official-earshot-distro-campus-community-radio-upload-route",
    feeRequired: true,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because !earshot Distro is an account-based paid upload platform with per-song/per-album pricing, Canadian sector eligibility, rights-to-distribute requirements, tax/credit handling and upload metadata decisions that require owner approval before use.",
    notes: "Public research confirmed !earshot Distro is an official NCRA/ANREC-associated platform for uploading recordings to Canadian campus and community radio stations. Its public site lists sign-up/login routes and upload pricing. No account was created, no login was used, no upload was started and no payment or credit purchase was initiated."
  },
  {
    name: "RTRFM Submit Your Music Form Email and Physical Side Route",
    websiteUrl: "https://rtrfm.com.au/",
    submissionUrl: "https://rtrfm.com.au/submit-your-music/",
    sourceUrl: "https://rtrfm.com.au/submit-your-music/",
    sourceType: "automation_run_111_public_research",
    country: "Australia / Perth community radio public form and Music Team route",
    language: "en",
    genres: ["rtrfm", "community-radio", "perth", "australian-radio", "independent-music", "electronic", "global-rhythm", "jazz", "soul", "heavy", "local-feature", "public-form", "download-link", "physical-side-route", "redacted-contact", "free-first", "manual-review"],
    submissionMethod: "official-rtrfm-submit-your-music-form-email-and-physical-side-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because RTRFM's official workflow includes a public form with artist/contact fields, biography file upload, stream and free-download-link fields, a validation field, redacted public email text, physical-copy side handling and premiere/release timing expectations.",
    notes: "Public research confirmed RTRFM is active in July 2026 with current station content and an official Submit Your Music page. The page exposes a public music-submission form, references an email route that was redacted by the fetch layer and gives physical-copy guidance. No form was submitted, no files were uploaded, no redacted contact was decoded and no physical package was prepared."
  },
  {
    name: "Triple J Unearthed Independent Australian Artist Upload Route",
    websiteUrl: "https://www.abc.net.au/triplejunearthed",
    submissionUrl: "https://www.abc.net.au/triplejunearthed",
    sourceUrl: "https://www.abc.net.au/triplejunearthed",
    sourceType: "automation_run_111_public_research",
    country: "Australia / ABC independent Australian artist upload and discovery platform",
    language: "en",
    genres: ["triple-j-unearthed", "abc", "australian-artists", "independent-music", "digital-radio", "artist-upload", "staff-review", "electronic", "hip-hop", "rnb", "indie", "pop", "rock", "account-boundary", "eligibility-review", "free-first", "manual-review"],
    submissionMethod: "official-triple-j-unearthed-independent-australian-artist-upload-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Triple J Unearthed is an artist upload/discovery platform with account/session and Australian-artist eligibility boundaries; rights, metadata, profile setup and release suitability must be reviewed by the owner before any upload path is used.",
    notes: "Public research confirmed the official Triple J Unearthed site is active in July 2026 with featured artists, current staff reviews, ABC station links and a large public artist/track catalogue. No account was created, no login was used, no upload workflow was entered and no session or eligibility boundary was bypassed."
  }
];
