import type { PlatformInput } from '../models/types.js';

export const run135SeedPlatforms: PlatformInput[] = [
  {
    name: "SomaFM High-Bitrate Digital Music Director Submission Route",
    websiteUrl: "https://somafm.com/",
    submissionUrl: "https://somafm.com/contact/submitmusic.html",
    sourceUrl: "https://somafm.com/contact/submitmusic.html",
    sourceType: "automation_run_135_public_research",
    country: "Global / US-based listener-supported internet radio network with electronic, dub, reggae, ambient, indie and specialty channels",
    language: "en",
    genres: ["somafm", "internet-radio", "electronic", "ambient", "downtempo", "dub", "reggae", "indie", "digital-submission", "music-director-email", "no-ai", "metadata-required", "manual-review"],
    submissionMethod: "official-somafm-high-bitrate-digital-music-director-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because SomaFM asks artists to choose the correct channel/music director, avoid mass-mailing, provide acceptable high-bitrate broadcast files or Bandcamp download codes, verify metadata and avoid AI-generated submissions.",
    notes: "Official SomaFM pages show active 2000-2026 operation, list public channel-specific music-director emails, and publish a Submit Music for Airplay route. No email was sent, no download link/file was delivered, no mailing list was used and no protected contact or platform restriction was bypassed."
  },
  {
    name: "KUTX Music Director WAV Link On-Air Rotation Submission Route",
    websiteUrl: "https://kutx.org/",
    submissionUrl: "https://kutx.org/submit-your-music/",
    sourceUrl: "https://kutx.org/submit-your-music/",
    sourceType: "automation_run_135_public_research",
    country: "US / Austin public radio music station with Music Director and specialty-show submission paths",
    language: "en",
    genres: ["kutx", "public-radio", "aaa", "electronic", "hip-hop", "latin", "jazz", "specialty-show", "wav-download", "music-director-email", "fcc-clean", "manual-review"],
    submissionMethod: "official-kutx-music-director-wav-link-on-air-rotation-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because submission requires selecting the correct airplay or specialty-show route, drafting the email subject/body, choosing a streaming link, WAV download link, bio/release notes, clean radio edit and local/genre fit.",
    notes: "Official KUTX pages show active 2026 music programming, a Submit Your Music route, public Music Director email guidance, streaming/WAV/bio requirements, specialty-show routes and no guaranteed feedback. No email was sent, no link or file was delivered and no paid event/promo route was used."
  },
  {
    name: "KXT 91.7 Online Form Streaming Link WAV Airplay Submission Route",
    websiteUrl: "https://kxt.org/",
    submissionUrl: "https://kxt.org/submissions/",
    sourceUrl: "https://kxt.org/submissions/",
    sourceType: "automation_run_135_public_research",
    country: "US / North Texas independent public-radio station accepting online music submissions",
    language: "en",
    genres: ["kxt", "public-radio", "independent", "local-music", "online-form", "wufoo-form", "streaming-link", "wav-download", "rights-authorization", "manual-review"],
    submissionMethod: "official-kxt-online-form-streaming-link-wav-airplay-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KXT uses an external online form, asks for one-song selection, a streaming link, a downloadable WAV and authorization for airplay, and the form must not be auto-submitted.",
    notes: "Official KXT pages show an active public-radio station, a Music Submissions route and an online form route for music considered a good fit. No form was submitted, no streaming/download link was delivered, no file was uploaded and no authorization was given."
  },
  {
    name: "KBOO Genre-Routed Physical Music Library Airplay Submission Route",
    websiteUrl: "https://kboo.fm/",
    submissionUrl: "https://kboo.fm/submit-your-music",
    sourceUrl: "https://kboo.fm/submit-your-music",
    sourceType: "automation_run_135_public_research",
    country: "US / Portland community radio station with world, reggae, electronic, jazz, hip-hop, rock and folk programming",
    language: "en",
    genres: ["kboo", "community-radio", "physical-submission", "world-music", "reggae", "electronic", "jazz", "hip-hop", "program-directory", "manual-review"],
    submissionMethod: "official-kboo-genre-routed-physical-music-library-airplay-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KBOO states it has no digital library capacity and asks for physical submissions routed by genre/show, with non-return/no-guarantee conditions.",
    notes: "Official KBOO pages show active station programming, a Submit Your Music route, physical-mail guidance and genre ATTN routing including Electronic, World Music and Reggae. No package was prepared, no physical mail was sent, no programmer was contacted and no contact was guessed."
  },
  {
    name: "WWOZ Music Director CD WAV New Orleans Airplay Submission Route",
    websiteUrl: "https://www.wwoz.org/",
    submissionUrl: "https://www.wwoz.org/getting-airplay-your-cd-wwoz",
    sourceUrl: "https://www.wwoz.org/getting-airplay-your-cd-wwoz",
    sourceType: "automation_run_135_public_research",
    country: "US / New Orleans community radio station with New Orleans, Louisiana, jazz, blues, brass, funk and world-adjacent programming",
    language: "en",
    genres: ["wwoz", "new-orleans", "jazz", "blues", "brass", "funk", "latin", "world", "physical-cd", "wav-file", "music-director", "manual-review"],
    submissionMethod: "official-wwoz-music-director-cd-wav-new-orleans-airplay-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WWOZ fit depends on New Orleans/Louisiana relevance, finished CD or WAV quality, cover-letter/package decisions, host/show matching, profanity marking and physical or digital delivery choices.",
    notes: "Official WWOZ pages show active programming, musician resources and a Getting Airplay route that prefers finished CDs but accepts WAV files for digital delivery. No CD package was prepared, no WAV/link/file was delivered, no host was contacted and no follow-up was sent."
  }
];
