import type { PlatformInput } from '../models/types.js';
import { run130SeedPlatforms } from './run130PlatformSeeds.js';

export const run129SeedPlatforms: PlatformInput[] = [
  {
    name: "KVRX Austin Music Department Physical Digital Airplay Submission Route",
    websiteUrl: "https://www.kvrx.org/",
    submissionUrl: "mailto:music@kvrx.org",
    sourceUrl: "https://www.kvrx.org/app/contact/",
    sourceType: "automation_run_129_public_research",
    country: "US / Austin student-run underground radio physical and digital airplay submission route",
    language: "en",
    genres: ["kvrx", "college-radio", "student-radio", "underground-music", "music-department", "airplay", "physical-submission", "digital-submission", "no-ai-assisted-music", "manual-review"],
    submissionMethod: "official-kvrx-austin-music-department-physical-digital-airplay-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KVRX accepts music submissions through an official Music Department route, supports both physical and digital submissions, and states AI-assisted or generated music will not be considered. Track eligibility, AI-origin review, package format, metadata, email/link delivery and any physical mailing must remain owner-controlled.",
    notes: "Official public research confirmed KVRX is active, student-run, focused on underground music, publishes music@kvrx.org as the route for airplay consideration, and states it is taking both physical and digital submissions. No email was sent, no file or link was delivered, and no physical package was prepared or mailed."
  },
  {
    name: "FBi Radio Sydney Digital Music Submission Premiere and Interview Route",
    websiteUrl: "https://fbiradio.com/",
    submissionUrl: "mailto:music@fbiradio.com",
    sourceUrl: "https://fbiradio.com/music-submissions/",
    sourceType: "automation_run_129_public_research",
    country: "Australia / Sydney independent radio digital music submission premiere and interview route",
    language: "en",
    genres: ["fbi-radio", "sydney", "independent-radio", "emerging-music", "digital-submission", "320kbps-mp3", "wav", "premiere", "interview", "paid-promo-side-route", "manual-review"],
    submissionMethod: "official-fbi-radio-sydney-digital-music-submission-premiere-interview-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because FBi Radio requires a properly formatted digital music pitch with release context, stream link, high-quality download link, timing rules for playlisting, and optional premiere, interview and paid promotional campaign side routes. Email copy, track links, release timing, interview fit and any paid campaign choice must remain owner-reviewed.",
    notes: "Official public research confirmed FBi Radio champions emerging Sydney music, lists music@fbiradio.com for music submissions, requires digital-only servicing with bio, press/gig context, stream and 320kbps MP3 or WAV download links, and exposes separate premiere, interview and paid promotional routes. No email was sent, no links or files were delivered and no paid route was initiated."
  },
  {
    name: "Triple J Unearthed Artist Upload Staff Review and Competition Route",
    websiteUrl: "https://www.abc.net.au/triplejunearthed",
    submissionUrl: "https://www.abc.net.au/triplejunearthed",
    sourceUrl: "https://www.abc.net.au/triplejunearthed",
    sourceType: "automation_run_129_public_research",
    country: "Australia / ABC Triple J Unearthed artist upload staff-review and competition platform route",
    language: "en",
    genres: ["triple-j-unearthed", "abc", "australian-artists", "artist-upload", "staff-review", "competitions", "unearthed-high", "app-session-boundary", "login-required", "manual-review"],
    submissionMethod: "official-triple-j-unearthed-artist-upload-staff-review-competition-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Triple J Unearthed is an artist-upload and competition platform that requires account/session control, Australian artist eligibility review, track metadata, rights and terms acceptance, and contest or staff-review route selection. No upload or account action is safe to automate.",
    notes: "Official public research confirmed Triple J Unearthed is active in 2026 with artist, review, competition and Unearthed High activity and describes a large Australian artist/track discovery platform. No account was created, no login was used, no artist profile was edited and no track was uploaded."
  },
  {
    name: "PBS 106.7FM Digital Form Physical Music Department Airplay Route",
    websiteUrl: "https://www.pbsfm.org.au/",
    submissionUrl: "https://www.pbsfm.org.au/submitmusic",
    sourceUrl: "https://www.pbsfm.org.au/submitmusic",
    sourceType: "automation_run_129_public_research",
    country: "Australia / Melbourne radio digital form and physical music department airplay route",
    language: "en",
    genres: ["pbs-1067fm", "melbourne", "community-radio", "music-department", "digital-form", "captcha", "physical-submission", "cd", "vinyl", "320kbps", "wav", "manual-review"],
    submissionMethod: "official-pbs-1067fm-digital-form-physical-music-department-airplay-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because PBS uses a public digital submission form with required contact, location, artist, stream and high-quality download fields plus a CAPTCHA, and also supports CD/vinyl package delivery. CAPTCHA, form entry, download-link selection, release metadata, show fit and physical package prep must remain manual.",
    notes: "Official public research confirmed PBS accepts new music from local and international acts, prefers digital submission through its form, asks for stream links and 320kbps AAC/MP3 or WAV-equivalent downloads, rejects Spotify/Deezer links, includes CAPTCHA anti-spam protection and provides physical CD/vinyl postal and in-person routes. No CAPTCHA was handled, no form was submitted, no links or files were delivered and no physical package was prepared."
  },
  {
    name: "4ZZZ Brisbane Music Department Downloadable Stream and AOTW Submission Route",
    websiteUrl: "https://4zzz.org.au/",
    submissionUrl: "https://jeff.4zzz.org.au/form/submit-your-music-to-4zzz",
    sourceUrl: "https://4zzz.org.au/music-submissions",
    sourceType: "automation_run_129_public_research",
    country: "Australia / Brisbane community radio music department downloadable-stream and Album of the Week route",
    language: "en",
    genres: ["4zzz", "brisbane", "community-radio", "music-department", "downloadable-stream", "wav", "320kbps-mp3", "bandcamp-code", "apple-music-code", "album-of-the-week", "javascript-form", "manual-review"],
    submissionMethod: "official-4zzz-brisbane-music-department-downloadable-stream-aotw-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because 4ZZZ routes submissions through a JavaScript-required public form with contact, subscriber status, artist, release, permission, identity/disclosure, warning, downloadable-stream, cover-art and social-link fields. Downloadability, release data, permissions, optional AOTW eligibility and form boundaries must remain owner-controlled.",
    notes: "Official public research confirmed 4ZZZ is active, publishes a Music Submissions page, requires downloadable music rather than non-downloadable streams, links to a JavaScript-required submission form, and separately exposes Album of the Week consideration with Australian-artist criteria. No JavaScript form was submitted, no permissions were granted, no link or file was delivered and no account/payment action was taken."
  },
  ...run130SeedPlatforms
];
