import type { PlatformInput } from '../models/types.js';
import { run118SeedPlatforms } from './run118PlatformSeeds.js';

export const run117SeedPlatforms: PlatformInput[] = [
  {
    name: "KBOO-FM Genre-Routed Physical Music Submission Route",
    websiteUrl: "https://kboo.fm/",
    submissionUrl: "https://kboo.fm/submit-your-music",
    sourceUrl: "https://kboo.fm/submit-your-music",
    sourceType: "automation_run_117_public_research",
    country: "United States / Portland community radio physical-library route",
    language: "en",
    genres: ["kboo", "community-radio", "freeform-radio", "physical-mail", "genre-routing", "electronic", "reggae", "world", "hip-hop", "free-first", "manual-review"],
    submissionMethod: "official-kboo-fm-genre-routed-physical-music-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KBOO requires physical package routing, genre-specific attention lines, ownership and return-risk acceptance, station-fit review and no-airplay-guarantee acknowledgement before any package is prepared.",
    notes: "Official public research confirmed KBOO exposes a Submit Your Music page, does not yet have a digital library, cannot process digital submissions into CDs, and asks submissions to be mailed with genre routing including Electronic, Hip-hop, World Music and Reggae. No physical mail was prepared or sent."
  },
  {
    name: "Radio Boise JavaScript-Loaded Submit Your Music Route",
    websiteUrl: "https://radioboise.org/",
    submissionUrl: "https://radioboise.org/support/submit-your-music/",
    sourceUrl: "https://radioboise.org/support/submit-your-music/",
    sourceType: "automation_run_117_public_research",
    country: "United States / Boise community radio public submission route",
    language: "en",
    genres: ["radio-boise", "community-radio", "submit-your-music", "javascript-boundary", "freeform-radio", "electronic", "reggae", "dub", "world", "hip-hop", "free-first", "manual-review"],
    submissionMethod: "official-radio-boise-javascript-loaded-submit-your-music-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Radio Boise exposes an official Submit Your Music route, but the submission content is JavaScript-loaded in the fetched view and must be reviewed manually.",
    notes: "Official public research confirmed Radio Boise is active with 2026 site updates and a public Submit Your Music navigation route. The submission page rendered as Loading in the fetch layer, so it was treated as a JavaScript/session boundary. No form was submitted."
  },
  {
    name: "CJSW Digital Album Submission and Campus Radio Mailout Route",
    websiteUrl: "https://cjsw.com/",
    submissionUrl: "https://cjsw.com/music/submit/",
    sourceUrl: "https://cjsw.com/music/submit/",
    sourceType: "automation_run_117_public_research",
    country: "Canada / Calgary campus-community radio digital album and mailout route",
    language: "en",
    genres: ["cjsw", "campus-radio", "community-radio", "digital-submission", "album-submission", "campus-mailout", "electronic", "reggae", "dub", "world", "hip-hop", "free-first", "payment-option", "external-form", "manual-review"],
    submissionMethod: "official-cjsw-digital-album-submission-campus-radio-mailout-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because CJSW accepts only recent digital album releases with three or more unique tracks, rejects singles, requires MP3 ZIP preparation, uses an external upload form and has a separate paid/physical campus-mailout side route.",
    notes: "Official public research confirmed CJSW accepts digital music submissions, asks for new albums released within the last three months with at least three unique tracks, requires MP3 ZIPs, and links to an external upload route. Its Campus Radio Mailout page also describes digital and physical mailout workflows, due dates and optional cash package costs. No form was submitted and no payment was initiated."
  },
  {
    name: "CKUW Music Director Digital Link and Physical Media Submission Route",
    websiteUrl: "https://ckuw.ca/",
    submissionUrl: "https://ckuw.ca/contact",
    sourceUrl: "https://ckuw.ca/contact",
    sourceType: "automation_run_117_public_research",
    country: "Canada / Winnipeg campus-community radio music-director route",
    language: "en",
    genres: ["ckuw", "campus-radio", "community-radio", "music-director", "digital-download", "physical-media", "cassette", "cd", "vinyl", "electronic", "reggae", "world", "hip-hop", "free-first", "manual-review"],
    submissionMethod: "official-ckuw-music-director-digital-link-physical-media-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because CKUW rejects unsolicited MP3 email attachments, asks artists to contact the Music Director for digital submissions or send high-quality download links, and also accepts physical media.",
    notes: "Official public research confirmed CKUW is active in 2026, lists a Music Director and station contact routes, and explains that artists should not send unsolicited MP3s but should contact the Music Director for digital submissions or send a high-quality download link. No email was sent, no file or link was delivered and no physical media was prepared."
  },
  {
    name: "WMSE Music Department Physical Digital Download and FCC-Clean Route",
    websiteUrl: "https://wmse.org/",
    submissionUrl: "https://wmse.org/about-wmse-radio/music-department/",
    sourceUrl: "https://wmse.org/about-wmse-radio/music-department/",
    sourceType: "automation_run_117_public_research",
    country: "United States / Milwaukee freeform radio physical and digital route",
    language: "en",
    genres: ["wmse", "college-radio", "freeform-radio", "music-department", "physical-mail", "digital-download", "fcc-clean", "electronic", "reggae", "dub", "world", "hip-hop", "free-first", "manual-review"],
    submissionMethod: "official-wmse-music-department-physical-digital-download-fcc-clean-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WMSE accepts physical and digital-download submissions but requires FCC-clean track guidance, music-department preview, program fit review, contact clarity and careful handling of digital delivery.",
    notes: "Official public research confirmed WMSE encourages new music submissions, accepts CD, vinyl, digital download and cassette, provides a Music Department mailing address and a public Music Director digital-download route, and asks submitters to identify non-airable material. No package or digital delivery was sent."
  },
  ...run118SeedPlatforms
];