import type { PlatformInput } from '../models/types.js';

export const run144SeedPlatforms: PlatformInput[] = [
  {
    name: "KALX Berkeley Physical-Only Music Director Airplay Submission Route",
    websiteUrl: "https://kalx.berkeley.edu/",
    submissionUrl: "https://kalx.berkeley.edu/about/contact/",
    sourceUrl: "https://kalx.berkeley.edu/about/contact/",
    sourceType: "automation_run_144_public_research",
    country: "United States / Berkeley college-community freeform radio physical-airplay review route",
    language: "en",
    genres: ["college-radio", "freeform-radio", "independent-music", "physical-submission", "cd", "lp", "music-director-email", "no-digital-submissions", "manual-review"],
    submissionMethod: "official-kalx-music-director-physical-airplay-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KALX currently accepts only physical professionally pressed CDs or LPs for airplay; format eligibility, package prep, metadata, FCC-clean notes and mailing decisions must remain owner-controlled.",
    notes: "Official KALX Contact page lists Music Directors, music@kalx.berkeley.edu and states submissions are physical only: professionally pressed CDs or LPs, with no downloads, file transfers, Bandcamp/Spotify links, YouTube videos, CD-Rs or other digital forms. No email was sent and no package was prepared or mailed."
  },
  {
    name: "WNRN Album Email and Commonwealth Artist Submission Route",
    websiteUrl: "https://wnrn.org/",
    submissionUrl: "https://wnrn.org/about/contact/",
    sourceUrl: "https://wnrn.org/about/contact/",
    sourceType: "automation_run_144_public_research",
    country: "United States / Virginia listener-supported independent music radio airplay route",
    language: "en",
    genres: ["public-radio", "independent-music-radio", "adult-album-alternative", "album-submission", "commonwealth-music", "email-route", "manual-review"],
    submissionMethod: "official-wnrn-music-email-and-commonwealth-artist-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WNRN accepts albums for airplay consideration by email and separately routes Commonwealth artists and bands through a submission link; album fit, local/regional status, pitch copy, metadata and link/file choices require review.",
    notes: "Official WNRN Contact page lists music@wnrn.org for album airplay consideration and a Commonwealth artist/band submission route, alongside active listener-supported radio context. No email was sent, no form was submitted and no upload or link delivery was attempted."
  },
  {
    name: "WPRB Princeton Physical Priority and Email Music Submission Route",
    websiteUrl: "https://wprb.com/",
    submissionUrl: "https://wprb.com/music-submissions/",
    sourceUrl: "https://wprb.com/music-submissions/",
    sourceType: "automation_run_144_public_research",
    country: "United States / Princeton community-supported independent radio physical and email music review route",
    language: "en",
    genres: ["college-radio", "freeform-radio", "independent-radio", "physical-submission", "vinyl", "cd", "email-route", "monthly-charts", "manual-review"],
    submissionMethod: "official-wprb-physical-priority-and-email-music-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WPRB accepts physical CDs, CD-Rs and vinyl plus an email route, but prioritizes physical media; package format, metadata, FCC-clean notes, best tracks and email-or-mail choice need owner review.",
    notes: "Official WPRB Music Submissions page says artists, labels and promoters can send music to the Music Director by physical mail or email music@wprb.com, with physical submissions prioritized. No email was sent and no physical package was prepared or mailed."
  },
  {
    name: "KZSU Stanford Music Director Email Snail Mail and Secure Music Portal Route",
    websiteUrl: "https://kzsu.stanford.edu/",
    submissionUrl: "https://kzsu.stanford.edu/contact/",
    sourceUrl: "https://kzsu.stanford.edu/contact/",
    sourceType: "automation_run_144_public_research",
    country: "United States / Stanford freeform radio music portal, email and mail submission route",
    language: "en",
    genres: ["college-radio", "freeform-radio", "independent-new-releases", "music-director-email", "snail-mail", "secure-session-boundary", "turnstile-boundary", "manual-review"],
    submissionMethod: "official-kzsu-contact-music-email-and-send-us-music-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KZSU lists music directors and a music@ email plus a send-us-music/guidelines route that resolves to a secure cookie/Turnstile session boundary; the portal/challenge must not be automated and music/package choices need owner review.",
    notes: "Official KZSU Contact page lists the KZSU Music PO Box, guidance links, Music Directors and music@kzsu.stanford.edu, while the Music portal required cookies and a secure browser/session check. No challenge was handled, no form was submitted and no email or physical package was sent."
  },
  {
    name: "KXLU Loyola Marymount FCC Clean Physical Music Director and Demolisten Route",
    websiteUrl: "https://kxlu.com/",
    submissionUrl: "https://kxlu.com/contact/",
    sourceUrl: "https://kxlu.com/contact/",
    sourceType: "automation_run_144_public_research",
    country: "United States / Los Angeles college-community radio FCC-clean physical submission and demo route",
    language: "en",
    genres: ["college-radio", "community-radio", "freeform-radio", "fcc-clean", "physical-submission", "demolisten", "punk", "folk", "vinyl", "manual-review"],
    submissionMethod: "official-kxlu-contact-physical-general-demolisten-specialty-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KXLU's submission routes are FCC-clean and physical-mail oriented, with separate general Music Director, Demolisten and A Fistful of Vinyl specialty destinations; route fit, content cleanliness and package prep need review.",
    notes: "Official KXLU Contact page lists station contacts plus physical submission guidance for General Submissions, Demolisten Submissions and Punk/Folk/Vinyl submissions. No email was sent, no package was prepared and no physical mail was initiated."
  }
];
