import type { PlatformInput } from '../models/types.js';
import { run135SeedPlatforms } from './run135PlatformSeeds.js';

export const run134SeedPlatforms: PlatformInput[] = [
  {
    name: "SoundCloud Artist Upload Direct Fan Discovery Route",
    websiteUrl: "https://soundcloud.com/",
    submissionUrl: "https://soundcloud.com/upload",
    sourceUrl: "https://soundcloud.com/upload",
    sourceType: "automation_run_134_public_research",
    country: "Global / Germany-based audio streaming, artist upload and fan-discovery platform",
    language: "en",
    genres: ["soundcloud", "artist-upload", "electronic", "dubstep", "reggae", "bass-music", "direct-to-fan", "streaming", "account-required", "rights-review", "manual-review"],
    submissionMethod: "official-soundcloud-artist-upload-direct-fan-discovery-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because SoundCloud upload requires an authenticated artist account, original-rights checks, metadata, artwork, public/private visibility, AI/content-policy review and any paid plan or monetization decisions.",
    notes: "Public research confirmed SoundCloud is active globally and allows users to upload, promote and share audio. The official upload route is account/session-bound and was queued only for manual owner review. No account was created, no login was used, no track was uploaded, no link was delivered and no paid plan was selected."
  },
  {
    name: "Audiomack Creator Upload Discovery and Monetization Route",
    websiteUrl: "https://audiomack.com/",
    submissionUrl: "https://audiomack.com/upload",
    sourceUrl: "https://audiomack.com/upload",
    sourceType: "automation_run_134_public_research",
    country: "Global / US-based streaming and discovery platform with strong hip-hop, R&B, Afrobeats, Latin and independent-artist usage",
    language: "en",
    genres: ["audiomack", "creator-upload", "afrobeats", "r-and-b", "hip-hop", "latin", "independent", "streaming", "creator-app", "account-required", "manual-review"],
    submissionMethod: "official-audiomack-creator-upload-discovery-monetization-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Audiomack upload requires an authenticated creator account, rights ownership, metadata, cover art, release formatting, possible monetization eligibility choices and platform-specific profile decisions.",
    notes: "Public research confirmed Audiomack is active, allows artists to upload music through its website/creator app, and does not charge creators for storage; Audiomack also uses fingerprinting, DMCA and manual curation to police unauthorized uploads. No account was created, no login was used, no upload or fan message was made and no monetization or Pro-tier decision was taken."
  },
  {
    name: "Bandcamp Artist Store Track Album Upload and Sales Route",
    websiteUrl: "https://bandcamp.com/",
    submissionUrl: "https://bandcamp.com/artists",
    sourceUrl: "https://bandcamp.com/artists",
    sourceType: "automation_run_134_public_research",
    country: "Global / US-based direct-to-fan artist store, streaming, download and merchandise platform",
    language: "en",
    genres: ["bandcamp", "artist-store", "track-upload", "album-upload", "direct-to-fan", "downloads", "merch", "sales-commission", "account-required", "payment-setup", "manual-review"],
    submissionMethod: "official-bandcamp-artist-store-track-album-upload-sales-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Bandcamp requires artist account/profile setup, track or album upload, pricing, payout/payment settings, metadata, artwork, merch/download choices and current AI/content policy review.",
    notes: "Public research confirmed Bandcamp is active, artists and labels upload music, set prices and sell downloads/merch, and Bandcamp takes a sales commission rather than charging an upfront submission fee. No account was created, no login was used, no artist page was configured, no music was uploaded and no payment/payout settings were entered."
  },
  {
    name: "Jamendo Artist Profile Licensing and Free Streaming Upload Route",
    websiteUrl: "https://www.jamendo.com/",
    submissionUrl: "https://www.jamendo.com/start",
    sourceUrl: "https://www.jamendo.com/start",
    sourceType: "automation_run_134_public_research",
    country: "Global / Luxembourg-based independent music community and licensing marketplace",
    language: "en",
    genres: ["jamendo", "artist-profile", "creative-commons", "licensing", "sync", "background-music", "free-streaming", "download", "account-required", "rights-metadata", "manual-review"],
    submissionMethod: "official-jamendo-artist-profile-licensing-free-streaming-upload-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Jamendo artist publishing and licensing decisions require account setup, rights/collecting-society compatibility, licensing opt-in choices, track metadata, territory/usage decisions and profile management.",
    notes: "Public research confirmed Jamendo is active, lets artists publish music, maintain artist profiles and potentially earn through Jamendo Licensing. No account was created, no login was used, no music was uploaded, no license terms were selected and no business contact was messaged."
  },
  {
    name: "Mixcloud DJ Mix Radio Show Creator Upload Route",
    websiteUrl: "https://www.mixcloud.com/",
    submissionUrl: "https://www.mixcloud.com/upload/",
    sourceUrl: "https://www.mixcloud.com/upload/",
    sourceType: "automation_run_134_public_research",
    country: "Global / UK-based licensed streaming platform for DJ mixes, radio shows and podcasts",
    language: "en",
    genres: ["mixcloud", "dj-mix", "radio-show", "podcast", "electronic", "dub", "bass-music", "creator-upload", "licensed-streaming", "account-required", "metadata-required", "manual-review"],
    submissionMethod: "official-mixcloud-dj-mix-radio-show-creator-upload-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Mixcloud upload requires a registered account, long-form mix/show formatting, tracklist and rights metadata, creator profile choices and any creator-subscription or monetization decisions.",
    notes: "Public research confirmed Mixcloud is active worldwide, registered users can upload radio shows, DJ mixes and podcasts, and correct artist/song metadata is required to preserve IP rights. No account was created, no login was used, no mix/show was uploaded, no metadata was submitted and no subscription/monetization route was activated."
  },
  ...run135SeedPlatforms
];
