import type { PlatformInput } from '../models/types.js';

export const run197SeedPlatforms: PlatformInput[] = [
  {
    name: "KVRX Austin Physical Digital Music Department Airplay Submission Route",
    websiteUrl: "https://kvrx.org/",
    submissionUrl: "https://kvrx.org/app/contact/",
    sourceUrl: "https://kvrx.org/contact/",
    sourceType: "automation_run_197_public_research",
    country: "United States / Austin college radio physical and digital music department submission route",
    language: "en",
    genres: ["college-radio", "austin", "independent-artists", "physical-submission", "digital-submission", "freeform", "electronic", "experimental", "world", "manual-review"],
    submissionMethod: "official-kvrx-music-department-physical-digital-email-route",
    feeRequired: false,
    feeAmount: "Free-first/manual route; official KVRX contact page lists a public music department email and physical mailing address with no submission fee observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KVRX asks that submissions go to the music department, currently accepts both physical and digital submissions, rejects AI-assisted/generated music, and requires owner review for release authenticity, clean metadata, rights, file/link preparation and physical package decisions. No email, upload or package may be automated.",
    notes: "Official KVRX contact guidance says all music submissions for airplay consideration should be sent to music@kvrx.org, that both physical and digital submissions are currently accepted, and that music submissions sent to programming will not be reviewed. Public contact emails were observed only from the official page; no message or deliverability probe was sent."
  },
  {
    name: "WPRB Princeton Physical Priority Music Submission Email Route",
    websiteUrl: "https://wprb.com/",
    submissionUrl: "https://wprb.com/music-submissions/",
    sourceUrl: "https://wprb.com/music-submissions/",
    sourceType: "automation_run_197_public_research",
    country: "United States / Princeton college radio physical-priority and email music submission route",
    language: "en",
    genres: ["college-radio", "princeton", "independent-artists", "physical-submission", "email-submission", "freeform", "electronic", "experimental", "dub", "manual-review"],
    submissionMethod: "official-wprb-physical-priority-music-submission-email-route",
    feeRequired: false,
    feeAmount: "Free-first/manual route; official WPRB music submissions page accepts physical formats and lists a public music email, with no submission fee observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because physical submissions are prioritized, WPRB accepts multiple physical formats, the email route needs careful no-attachment/link/package preparation, and owner review is required for radio-clean edits, rights, metadata and relevance. No email or physical package may be automated.",
    notes: "Official WPRB music submissions guidance asks artists, labels and promoters to send CDs, CD-Rs, LPs, 12-inch, 10-inch or 7-inch records to the Music Director and says submissions can also be emailed to music@wprb.com, while physical submissions are prioritized."
  },
  {
    name: "KXLU Los Angeles FCC Clean Music Director Physical Submission Route",
    websiteUrl: "https://kxlu.com/",
    submissionUrl: "https://kxlu.com/contact/",
    sourceUrl: "https://kxlu.com/contact/",
    sourceType: "automation_run_197_public_research",
    country: "United States / Los Angeles college radio FCC-clean physical music-director route",
    language: "en",
    genres: ["college-radio", "los-angeles", "physical-submission", "fcc-clean", "demolisten", "punk", "folk", "vinyl", "latin", "manual-review"],
    submissionMethod: "official-kxlu-fcc-clean-music-director-physical-route",
    feeRequired: false,
    feeAmount: "Free-first/manual physical route; official KXLU contact page lists music-director/submission mailing routes and no submission fee was observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KXLU explicitly asks for FCC-clean submissions, uses physical attention-line routing for general, Demolisten and genre-specific submissions, and requires clean-edit, format, package, rights and contact-routing review. No email, upload or physical package may be automated.",
    notes: "Official KXLU contact page lists the station address, a Music Director contact, FCC-clean-only submission guidance, general submissions addressed to the Music Director, Demolisten submissions, and punk/folk/vinyl routing. The public Music Director contact was observed only from the official page; no outbound contact or deliverability probe was performed."
  },
  {
    name: "Fresh On The Net Listening Post SoundCloud Dropbox Submission Route",
    websiteUrl: "https://freshonthenet.co.uk/",
    submissionUrl: "https://freshonthenet.co.uk/send/",
    sourceUrl: "https://freshonthenet.co.uk/send/",
    sourceType: "automation_run_197_public_research",
    country: "United Kingdom / global independent-artist Listening Post SoundCloud link submission route",
    language: "en",
    genres: ["music-blog", "listening-post", "independent-artists", "soundcloud", "single-track", "weekly-dropbox", "electronic", "alternative", "world", "manual-review"],
    submissionMethod: "official-fresh-on-the-net-listening-post-soundcloud-dropbox-route",
    feeRequired: false,
    feeAmount: "Free-first/manual route; official Fresh On The Net send page shows a public one-track Dropbox/submit route and no submission fee was observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because the inbox is time/capacity gated, the route asks for one SoundCloud track URL, moderators review a limited weekly batch, and the submission link must not be automated or repeatedly retried. No form, link submission, login/session boundary or anti-abuse control may be automated.",
    notes: "Fresh On The Net's official send page shows a current inbox area with a submit-a-track link, notes that moderators listen to weekly submissions and select a smaller Listening Post, and shows recent 2026 batch activity. The route should be queued only for a human-ready single-track SoundCloud link and timing check."
  },
  {
    name: "KALW Bay Area Music Programming Inquiry Route",
    websiteUrl: "https://www.kalw.org/",
    submissionUrl: "https://www.kalw.org/contact-us",
    sourceUrl: "https://www.kalw.org/contact-us",
    sourceType: "automation_run_197_public_research",
    country: "United States / San Francisco Bay Area public radio music programming inquiry route",
    language: "en",
    genres: ["public-radio", "bay-area", "music-programming", "music-inquiry", "world", "electronic", "roots", "community-radio", "manual-review"],
    submissionMethod: "official-kalw-music-programming-inquiry-email-route",
    feeRequired: false,
    feeAmount: "Free-first/manual inquiry route; official KALW contact page lists a public music inquiries and music programming questions email, with no submission fee observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KALW's public route is framed as music inquiries and programming questions, not an explicit open-submission inbox, so fit, permission-to-send, concise query wording, clean links and genre-program targeting must be owner-reviewed. No email or file transfer may be automated.",
    notes: "Official KALW contact page lists music@kalw.org for music inquiries and music programming questions, and the same site shows active music programming sections. This is queued as a cautious manual inquiry route rather than an auto-submit route."
  }
];
