import type { PlatformInput } from '../models/types.js';
import { run121SeedPlatforms } from './run121PlatformSeeds.js';

export const run120SeedPlatforms: PlatformInput[] = [
  {
    name: "EARMILK SubmitHub Pillargram Music Submission and Premiere Route",
    websiteUrl: "https://earmilk.com/",
    submissionUrl: "https://earmilk.com/submit-music/",
    sourceUrl: "https://earmilk.com/submit-music/",
    sourceType: "automation_run_120_public_research",
    country: "United States / global music blog editorial submission and premiere route",
    language: "en",
    genres: ["earmilk", "music-blog", "new-music", "premieres", "electronic", "hip-hop", "indie", "rnb", "submithub", "pillargram", "freemium", "manual-review"],
    submissionMethod: "official-earmilk-submithub-pillargram-music-submission-premiere-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because EARMILK exclusively routes music submissions through SubmitHub or Pillargram, while its general contact form says music submissions sent there are filtered out. External-platform login, possible credit/payment options, premiere timing, fit and pitch package require owner review.",
    notes: "Official public research confirmed EARMILK is active with July 2026 posts, publishes a Submit Music page, routes music and premiere submissions to SubmitHub/Pillargram, and exposes a separate business contact route that must not be used for music submissions. No account/session was opened and no track link or message was delivered."
  },
  {
    name: "Indie88 Music Director Airplay and Business Contact Submission Route",
    websiteUrl: "https://indie88.com/",
    submissionUrl: "https://indie88.com/contact/",
    sourceUrl: "https://indie88.com/contact/",
    sourceType: "automation_run_120_public_research",
    country: "Canada / Toronto alternative radio music director and business contact route",
    language: "en",
    genres: ["indie88", "radio", "alternative", "indie", "music-director", "airplay", "business-contact", "canada", "recaptcha", "free-first", "manual-review"],
    submissionMethod: "official-indie88-music-director-airplay-business-contact-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Indie88 exposes staff and station contact routes, including a Music/Program Director address, but no safe public auto-submit music form was identified; the site also declares reCAPTCHA protection. Pitch copy, radio-edit assets and contact choice need manual review.",
    notes: "Official public research confirmed Indie88 is active with current station content and publishes contact details for listener/business routes, show hosts and the Music/Program Director. Main contact formatting and site-level reCAPTCHA boundaries were not bypassed, and no message was sent."
  },
  {
    name: "Amazing Radio Unsigned Artist Upload and Airplay Discovery Route",
    websiteUrl: "https://amazingradio.com/",
    submissionUrl: "https://amazingradio.com/",
    sourceUrl: "https://amazingradio.com/",
    sourceType: "automation_run_120_public_research",
    country: "United Kingdom / global unsigned artist upload and radio discovery route",
    language: "en",
    genres: ["amazing-radio", "unsigned-artists", "new-music", "artist-upload", "radio-airplay", "discovery-platform", "javascript-app", "free-first", "manual-review"],
    submissionMethod: "official-amazing-radio-unsigned-artist-upload-airplay-discovery-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Amazing Radio is an app-based unsigned-artist upload and radio-discovery route that requires account/session handling, rights confirmation, artist profile metadata and upload preparation. The public app rendered behind a JavaScript boundary.",
    notes: "Public research confirmed Amazing Radio operates an artist upload/radio discovery model for unsigned artists; the official page responded as a JavaScript application boundary. No account was created, no login was used and no file was uploaded."
  },
  {
    name: "Broadjam Song Placement Licensing Contest and Radio Submission Route",
    websiteUrl: "https://www.broadjam.com/",
    submissionUrl: "https://www.broadjam.com/",
    sourceUrl: "https://en.wikipedia.org/wiki/Broadjam",
    sourceType: "automation_run_120_public_research",
    country: "United States / worldwide independent musician placement licensing contest and radio route",
    language: "en",
    genres: ["broadjam", "independent-musicians", "song-placement", "sync-licensing", "film-tv-advertising-games", "radio-play", "contests", "reviews", "membership", "freemium", "manual-review"],
    submissionMethod: "official-broadjam-song-placement-licensing-contest-radio-submission-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Broadjam uses membership/account-based song submission, contests, reviews, radio and placement opportunities. Opportunity fit, pricing/membership tier, rights, metadata and upload/package details need owner review before use.",
    notes: "Public research confirmed Broadjam is a long-running independent-musician community with song placement, contests, radio play, reviews and licensing opportunities for film, TV, advertising and games; the official site URL was identified but direct fetch was blocked, so only public discovery was recorded. No account/session was opened."
  },
  {
    name: "Ditto Music Distribution Playlist Sync and Artist Growth Submission Route",
    websiteUrl: "https://dittomusic.com/",
    submissionUrl: "https://dittomusic.com/en/sell-your-music",
    sourceUrl: "https://dittomusic.com/en/sell-your-music",
    sourceType: "automation_run_120_public_research",
    country: "United Kingdom / worldwide music distribution playlist sync and artist-growth route",
    language: "en",
    genres: ["ditto-music", "music-distribution", "spotify", "apple-music", "tiktok", "instagram", "150-plus-platforms", "playlist-pitching", "sync-licensing", "artist-growth", "paid", "manual-review"],
    submissionMethod: "official-ditto-music-distribution-playlist-sync-artist-growth-route",
    feeRequired: true,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Ditto routes releases through login/signup, plan/pricing decisions, release metadata, store delivery, royalty splits, sync/publishing options, playlist pitching and potential payment/subscription approval.",
    notes: "Official public research confirmed Ditto offers online music distribution to 150+ platforms, signup/login routes, playlist pitching, sync licensing, publishing and revenue tools. No account was created, no release wizard was started and no payment was initiated."
  },
  ...run121SeedPlatforms
];
