import type { PlatformInput } from '../models/types.js';

export const run121SeedPlatforms: PlatformInput[] = [
  {
    name: "Radio Milwaukee WAV Radio Edit Digital Music Submission Route",
    websiteUrl: "https://radiomilwaukee.org/",
    submissionUrl: "https://radiomilwaukee.org/music-submission",
    sourceUrl: "https://radiomilwaukee.org/music-submission",
    sourceType: "automation_run_121_public_research",
    country: "United States / Milwaukee public-radio digital music submission route",
    language: "en",
    genres: ["radio-milwaukee", "public-radio", "radio-airplay", "new-music", "local-music", "wav", "radio-edits", "lyrics", "no-physical-media", "free-first", "manual-review"],
    submissionMethod: "official-radio-milwaukee-wav-radio-edit-digital-music-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Radio Milwaukee asks for uncompressed audio with WAV preferred, mastered radio edits, lyrics, bio/context, album or show information and helpful links, and explicitly says no physical media. Asset preparation and link delivery must remain owner-reviewed.",
    notes: "Official public research confirmed Radio Milwaukee is active with current July 2026 music content and publishes a Music Submission page describing the authorized digital package. No form was submitted, no file was transferred and no track link was delivered."
  },
  {
    name: "WFUV Music Department Snail Mail and Music Contact Airplay Route",
    websiteUrl: "https://wfuv.org/",
    submissionUrl: "https://wfuv.org/contact-us",
    sourceUrl: "https://wfuv.org/contact-us",
    sourceType: "automation_run_121_public_research",
    country: "United States / New York public-radio music department and airplay route",
    language: "en",
    genres: ["wfuv", "public-radio", "radio-airplay", "music-department", "snail-mail", "physical-package", "adult-alternative", "indie", "americana", "free-first", "manual-review"],
    submissionMethod: "official-wfuv-music-department-snail-mail-music-contact-airplay-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WFUV routes music to the Music Department by snail mail and exposes staff/music contact routes. Physical package preparation, release fit, follow-up timing and contact choice must be reviewed before any outreach.",
    notes: "Official public research confirmed WFUV is active with current July 2026 station content and lists a public Send Music route for the Music Department. No email was sent, no contact link was decoded beyond public page text and no physical mail was prepared."
  },
  {
    name: "WERS Wicked Local Wednesday Local Artist MP3 Upload Form Route",
    websiteUrl: "https://wers.org/",
    submissionUrl: "https://wers.org/wickedlocalwednesday/",
    sourceUrl: "https://wers.org/wickedlocalwednesday/",
    sourceType: "automation_run_121_public_research",
    country: "United States / Boston local-artist radio upload form route",
    language: "en",
    genres: ["wers", "wicked-local-wednesday", "boston", "local-music", "radio-airplay", "mp3-upload", "contact-form", "recaptcha", "validation-fields", "free-first", "manual-review"],
    submissionMethod: "official-wers-wicked-local-wednesday-local-artist-mp3-upload-form-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WERS uses a public Wicked Local Wednesday form for local artists, requires artist/location/contact fields, accepts MP3 music files with a size limit and the site declares reCAPTCHA protection. Local eligibility and form interaction must be owner-reviewed.",
    notes: "Official public research confirmed WERS is active with current 2026 station content and publishes a Submit Your Music form for Wicked Local Wednesday. No reCAPTCHA/session interaction occurred and no file or form data was submitted."
  },
  {
    name: "KCSM Jazz 91 CD Broadcast Consideration Music Director Route",
    websiteUrl: "https://www.kcsm.org/",
    submissionUrl: "https://www.kcsm.org/contact",
    sourceUrl: "https://www.kcsm.org/contact",
    sourceType: "automation_run_121_public_research",
    country: "United States / Bay Area jazz radio CD broadcast consideration route",
    language: "en",
    genres: ["kcsm", "jazz", "jazz-radio", "public-radio", "music-director", "cd-submission", "broadcast-consideration", "physical-package", "free-first", "manual-review"],
    submissionMethod: "official-kcsm-jazz-91-cd-broadcast-consideration-music-director-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KCSM lists an official route to submit a CD for broadcast consideration through its radio contacts and Program/Music Director context. Jazz fit, physical package handling and any contact choice require owner review.",
    notes: "Official public research confirmed KCSM is active as Jazz 91 with current July 2026 station content, publishes department/staff contact pages and identifies a CD broadcast-consideration route. No email was sent, no call was placed and no physical package was prepared."
  },
  {
    name: "KGNU Music Department Contact Form and DJ Route",
    websiteUrl: "https://kgnu.org/",
    submissionUrl: "https://kgnu.org/contact-us/",
    sourceUrl: "https://kgnu.org/contact-us/",
    sourceType: "automation_run_121_public_research",
    country: "United States / Boulder-Denver community-radio music department contact route",
    language: "en",
    genres: ["kgnu", "community-radio", "music-department", "dj-route", "contact-form", "recaptcha-v3", "local-music", "eclectic", "free-first", "manual-review"],
    submissionMethod: "official-kgnu-music-department-contact-form-dj-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KGNU publishes a contact form with Department choices including Music and DJ routes, but the form is protected by reCaptcha v3. Department choice, message text, music fit and any link/package details must be reviewed manually.",
    notes: "Official public research confirmed KGNU is active with current July 2026 music/news programming and exposes a public contact workflow for Music/DJ routing. No reCaptcha/session interaction occurred and no message or music link was submitted."
  }
];
