import type { PlatformInput } from '../models/types.js';

export const run187BaseSeedPlatforms: PlatformInput[] = [
  {
    name: "CJSR Edmonton Digital Album EP Music Department Submission Route",
    websiteUrl: "https://www.cjsr.com/",
    submissionUrl: "https://www.cjsr.com/submit-music/",
    sourceUrl: "https://www.cjsr.com/submit-music/",
    sourceType: "automation_run_187_public_research",
    country: "Canada / Edmonton Alberta independent campus-community radio album EP digital and physical route",
    language: "en",
    genres: ["campus-radio", "community-radio", "eclectic", "electronic", "folktronica", "reggae", "world", "hip-hop", "independent-music", "digital-album", "physical-media", "manual-review"],
    submissionMethod: "official-cjsr-digital-album-ep-music-department-submission-route",
    feeRequired: false,
    feeAmount: "Free-first CJSR Music Department route; official page accepts digital albums/EPs by public music email or physical mail/drop-off, but excludes single tracks and requires file/link/package review.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because CJSR accepts albums or EPs only, asks for actual files rather than paid streaming links, permits Bandcamp codes/cloud storage, discourages expiring transfer links, requires metadata/track lengths/language warnings and has physical customs/package guidance for non-Canadian senders.",
    notes: "Official CJSR Submit Music page says the station wants eclectic music, gives a Music Department postal address, accepts digital album/EP submissions to music@cjsr.com, accepts Bandcamp download codes and cloud-storage links, rejects single tracks, asks for artist/release information, focus tracks, track lengths, language warnings and tagged MP3s. No email, files, links or package were sent."
  },
  {
    name: "KBOO Portland Physical Genre Attention Music Submission Route",
    websiteUrl: "https://www.kboo.fm/",
    submissionUrl: "https://www.kboo.fm/submit-your-music",
    sourceUrl: "https://www.kboo.fm/submit-your-music",
    sourceType: "automation_run_187_public_research",
    country: "United States / Portland Oregon community-radio physical music route",
    language: "en",
    genres: ["community-radio", "freeform-radio", "electronic", "reggae", "world", "hip-hop", "jazz", "folk", "physical-media", "genre-routing", "no-digital-library", "manual-review"],
    submissionMethod: "official-kboo-physical-genre-attention-music-submission-route",
    feeRequired: false,
    feeAmount: "Free-first KBOO physical music route; official page says KBOO does not yet have a digital library and asks submissions to be mailed with genre-specific attention lines.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KBOO currently routes music through physical mail, explicitly says it lacks digital-library capacity, gives multiple genre-specific attention lines including electronic and world music/reggae, and states submissions become station property and are not returned.",
    notes: "Official KBOO Submit Your Music page says general submissions can be mailed to KBOO-FM in Portland, lists attention lines for electronic, world music/reggae, hip-hop, jazz, folk and other genres, states it does not have digital library/download capacity, and notes no guarantee of airplay. No package was prepared or mailed."
  },
  {
    name: "KOOP Austin Music Library Public Email Submission Route",
    websiteUrl: "https://koop.org/",
    submissionUrl: "https://koop.org/about-us/contact/",
    sourceUrl: "https://koop.org/about-us/contact/",
    sourceType: "automation_run_187_public_research",
    country: "United States / Austin Texas community-radio music-library email route",
    language: "en",
    genres: ["community-radio", "independent-radio", "electronic", "reggae", "world", "hip-hop", "latin", "jazz", "blues", "music-library-email", "manual-review"],
    submissionMethod: "official-koop-music-library-public-email-submission-route",
    feeRequired: false,
    feeAmount: "Free-first KOOP Music Library route; official contact page states the music library welcomes music submissions at the listed public music email.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KOOP gives a public music-library submission email but does not define allowed file formats, attachment rules, download-link requirements, clean/radio-edit expectations or genre/show targeting on the fetched page.",
    notes: "Official KOOP contact page lists info@koop.org, mailing address and explicitly states that the Music Library welcomes music submissions at music@koop.org. KOOP homepage also showed active July/August 2026 updates/events and diverse community-radio programming. No message, file or link was sent."
  },
  {
    name: "KDVS Davis Physical Only Music Department Submission Route",
    websiteUrl: "https://kdvs.org/",
    submissionUrl: "https://kdvs.org/contact",
    sourceUrl: "https://kdvs.org/contact",
    sourceType: "automation_run_187_public_research",
    country: "United States / Davis California UC Davis college-radio physical-only music route",
    language: "en",
    genres: ["college-radio", "community-radio", "freeform-radio", "electronic", "reggae", "world", "hip-hop", "experimental", "physical-only", "music-department", "manual-review"],
    submissionMethod: "official-kdvs-physical-only-music-department-submission-route",
    feeRequired: false,
    feeAmount: "Free-first KDVS Music Department route; official contact page lists music directors/musicdept contact and says all new music should be sent to the mailing address as physical submissions only.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KDVS explicitly says new music should be sent to its mailing address and that submissions are physical only. CD/vinyl availability, package address, clean edit status, metadata, rights and whether any pre-contact to musicdept is appropriate must be approved.",
    notes: "Official KDVS contact page lists Music Directors, musicdept@kdvs.org, describes music review/library maintenance/mail sorting/record-label contact, and instructs that all new music should be sent to the mailing address as physical submissions only. No email or package was sent."
  },
  {
    name: "WREK Atlanta Music Director Email Snail Mail Submission Route",
    websiteUrl: "https://www.wrek.org/",
    submissionUrl: "https://old.wrek.org/submissions/",
    sourceUrl: "https://old.wrek.org/submissions/",
    sourceType: "automation_run_187_public_research",
    country: "United States / Atlanta Georgia Tech college-radio email and snail-mail music route",
    language: "en",
    genres: ["college-radio", "independent-radio", "electronic", "reggae", "world", "hip-hop", "ambient", "experimental", "cd", "lp", "music-director-email", "manual-review"],
    submissionMethod: "official-wrek-music-director-email-snail-mail-submission-route",
    feeRequired: false,
    feeAmount: "Free-first WREK Music Director route; official site links to Submit Songs and the official submissions page accepts snail mail or email to the Music Director.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WREK accepts snail-mail and email submissions, handles common music media formats, says CDs and LPs have better airplay odds, does not acknowledge receipts, and uses random Music Director review. Format, link/file packaging, clean edits, metadata and follow-up expectations must be approved.",
    notes: "Official WREK music page links to Submit Songs; the linked submissions page says music can be submitted by snail mail or emailed to music.director@wrek.org, accepts common music media formats and notes CDs/LPs have better airplay odds. WREK homepage also showed active July 2026 playlist/update context across electronic, reggae/world and other shows. No email, file, link or package was sent."
  }
];
