import type { PlatformInput } from '../models/types.js';

export const run19SeedPlatforms: PlatformInput[] = [
  {
    name: 'Liquicity Records Liquid Drum and Bass Demo Route',
    websiteUrl: 'https://liquicity.com/',
    submissionUrl: 'https://liquicity.com/',
    sourceUrl: 'https://liquicity.com/',
    sourceType: 'automation_run_19_public_research',
    country: 'Netherlands / global drum and bass reach',
    language: 'en',
    genres: ['drum-and-bass', 'liquid-drum-and-bass', 'electronic', 'bass-music', 'dance'],
    submissionMethod: 'label-demo-route-requires-current-form-confirmation-and-rights-review',
    feeRequired: false,
    loginRequired: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Strong label and genre fit, but current demo intake fields and any third-party submission widget must be manually confirmed before sharing music, rights metadata or unreleased material.',
    notes: 'Verified as an active Dutch liquid drum and bass label/promoter with global community relevance. No demo upload, form submission, login, contact guessing or protected workflow was attempted.'
  },
  {
    name: 'Armada Music Demo Drop Electronic Label Route',
    websiteUrl: 'https://www.armadamusic.com/',
    submissionUrl: 'https://www.armadamusic.com/',
    sourceUrl: 'https://www.armadamusic.com/',
    sourceType: 'automation_run_19_public_research',
    country: 'Netherlands / global electronic music reach',
    language: 'en',
    genres: ['edm', 'trance', 'progressive-house', 'deep-house', 'tech-house', 'techno', 'electronic'],
    submissionMethod: 'official-electronic-label-route-with-demo-drop-or-contact-flow-needs-manual-form-mapping',
    feeRequired: false,
    loginRequired: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Major independent dance label route requires human label-fit, rights, exclusivity, unreleased status and current demo-drop/form field review before submission.',
    notes: 'Verified active through official site and recent 2026 label activity. No demo drop, protected form interaction, upload, account access or bypass was performed.'
  },
  {
    name: 'Monstercat Electronic Label Contact and A&R Route',
    websiteUrl: 'https://www.monstercat.com/',
    submissionUrl: 'https://www.monstercat.com/',
    sourceUrl: 'https://www.monstercat.com/',
    sourceType: 'automation_run_19_public_research',
    country: 'Canada / global electronic music reach',
    language: 'en',
    genres: ['edm', 'electronic', 'bass-music', 'drum-and-bass', 'dubstep', 'house', 'dance'],
    submissionMethod: 'label-contact-and-artist-discovery-route-not-safe-for-auto-submit',
    feeRequired: false,
    loginRequired: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Active electronic label, but no safe public self-serve demo form was confirmed; any contact or A&R route requires human fit and rights review.',
    notes: 'Verified as an active electronic label/discovery destination. No account, message, demo upload, contact scraping or guessed business email was used.'
  },
  {
    name: 'Future House Music Label and Network Demo Route',
    websiteUrl: 'https://www.futurehousemusic.com/',
    submissionUrl: 'https://www.futurehousemusic.com/',
    sourceUrl: 'https://www.futurehousemusic.com/',
    sourceType: 'automation_run_19_public_research',
    country: 'Netherlands / global house music network',
    language: 'en',
    genres: ['future-house', 'tech-house', 'deep-house', 'bass-house', 'electro-house', 'edm', 'dance'],
    submissionMethod: 'label-network-demo-or-contact-route-needs-current-policy-review',
    feeRequired: false,
    loginRequired: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Label/network has strong genre fit, but current demo policy and any form/widget fields need manual verification before sharing unreleased music.',
    notes: 'Verified as an active Dutch future-house label/network. No contact attempt, hidden-form mapping, upload or platform restriction bypass was performed.'
  },
  {
    name: 'Hospital Records Drum and Bass Label Route',
    websiteUrl: 'https://www.hospitalrecords.com/',
    submissionUrl: 'https://www.hospitalrecords.com/',
    sourceUrl: 'https://www.hospitalrecords.com/',
    sourceType: 'automation_run_19_public_research',
    country: 'United Kingdom / global drum and bass reach',
    language: 'en',
    genres: ['drum-and-bass', 'liquid-funk', 'electronic', 'breakbeat', 'bass-music'],
    submissionMethod: 'curated-label-contact-or-demo-policy-route-needs-manual-review',
    feeRequired: false,
    loginRequired: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Curated DnB label route; current demo policy, sublabel/artist fit, rights, metadata and unreleased-status requirements must be checked manually.',
    notes: 'Verified as an active independent drum and bass label. No form submission, email send, account access, demo upload or scraped contact workflow was used.'
  },
  {
    name: 'NoCopyrightSounds NCS Electronic Label and Creator-Safe Music Route',
    websiteUrl: 'https://ncs.io/',
    submissionUrl: 'https://ncs.io/',
    sourceUrl: 'https://ncs.io/',
    sourceType: 'automation_run_19_public_research',
    country: 'United Kingdom / global creator and electronic music reach',
    language: 'en',
    genres: ['edm', 'house', 'dubstep', 'trap', 'drum-and-bass', 'electropop', 'creator-safe-music'],
    submissionMethod: 'electronic-label-contact-or-demo-policy-route-needs-licensing-review',
    feeRequired: false,
    loginRequired: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'NCS has creator-safe/licensing implications; any submission requires manual review of rights, exclusivity, creator-use terms and current demo policy.',
    notes: 'Verified as an active electronic label and creator-safe music platform. No terms acceptance, upload, licensing action, protected form submission or account access occurred.'
  },
  {
    name: 'Anjunabeats and Anjuna Electronic Label Route',
    websiteUrl: 'https://anjunabeats.com/',
    submissionUrl: 'https://anjunabeats.com/',
    sourceUrl: 'https://anjunabeats.com/',
    sourceType: 'automation_run_19_public_research',
    country: 'United Kingdom / global trance and progressive reach',
    language: 'en',
    genres: ['trance', 'progressive-trance', 'progressive-house', 'deep-house', 'electronic', 'dance'],
    submissionMethod: 'curated-electronic-label-route-needs-current-demo-policy-and-rights-review',
    feeRequired: false,
    loginRequired: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Curated Anjuna label ecosystem; current demo policy, label fit, release status and rights/exclusivity must be manually reviewed before submission.',
    notes: 'Verified as an active electronic/trance/progressive label route. No demo delivery, form submission, email send, login or bypass was performed.'
  },
  {
    name: 'TopHit Radio and TV Music Distribution Platform',
    websiteUrl: 'https://tophit.com/',
    submissionUrl: 'https://tophit.com/',
    sourceUrl: 'https://tophit.com/',
    sourceType: 'automation_run_19_public_research',
    country: 'Global radio/TV distribution with strong Eastern Europe and CIS footprint',
    language: 'en',
    genres: ['radio-ready', 'dance', 'edm', 'pop', 'electronic', 'club', 'music-video'],
    submissionMethod: 'rightsholder-registration-upload-radio-and-tv-distribution-workflow-needs-manual-review',
    feeRequired: false,
    loginRequired: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Requires rightsholder registration, track or video upload, metadata, rights confirmation, territory/radio targeting and possible service terms review.',
    notes: 'Verified as a music distribution, airplay monitoring and chart platform where rights holders upload content for radio/TV review. No registration, upload, data entry or account workflow was attempted.'
  }
];
