import type { PlatformInput } from '../models/types.js';

export const run168BaseSeedPlatforms: PlatformInput[] = [
  {
    name: "WMNF Tampa Submit Music Upload Form and Music Relations Route",
    websiteUrl: "https://www.wmnf.org/",
    submissionUrl: "https://www.wmnf.org/submit-your-music-to-wmnf/",
    sourceUrl: "https://www.wmnf.org/submit-your-music-to-wmnf/",
    sourceType: "automation_run_168_public_research",
    country: "United States / Tampa Bay community radio station with public music upload form and music-relations email route",
    language: "en",
    genres: ["community-radio", "radio-airplay", "album-ep-submission", "file-upload-form", "wav", "flac", "mp3", "aac", "aiff", "m4a", "music-relations", "manual-review"],
    submissionMethod: "official-wmnf-submit-music-upload-form-music-relations-route",
    feeRequired: false,
    feeAmount: "No submission fee was observed on the official WMNF Submit Music page; file upload and music-relations routing require manual owner review.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because the official WMNF submission route includes music-file upload fields, artist identity, contact email, local show context, release package choice, metadata and FCC/explicit-content readiness that must remain owner-controlled.",
    notes: "Public research verified WMNF's official Submit Music page, public music-relations route, required artist/band and contact fields, audio upload requirements and active 2026 station context. No form was submitted and no files were uploaded."
  },
  {
    name: "KZSC Santa Cruz Genre Music Director Contact Submission Route",
    websiteUrl: "https://kzsc.org/",
    submissionUrl: "https://kzsc.org/contact/",
    sourceUrl: "https://kzsc.org/contact/",
    sourceType: "automation_run_168_public_research",
    country: "United States / Santa Cruz college and community radio station with genre-routed Station Music Director contact links",
    language: "en",
    genres: ["college-radio", "community-radio", "genre-director-routing", "rock", "hardcore", "hip-hop", "rpm-electronic", "jazz-blues", "folk", "international", "protected-contact-boundary", "manual-review"],
    submissionMethod: "official-kzsc-genre-station-music-director-contact-route",
    feeRequired: false,
    feeAmount: "No submission fee was observed; route is official staff/genre contact based and requires manual targeting.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KZSC exposes genre-specific Station Music Director routes with protected public contact links; route selection, pitch fit, release metadata, download-link choice and contact handling must remain manual.",
    notes: "Public research verified KZSC's official active station site and Staff & Contact page with Station Music Director routing for rock, hardcore, hip hop, RPM/electronic, jazz & blues, folk and international. Protected contact links were observed but not decoded."
  },
  {
    name: "CJSR Edmonton Album EP Digital Physical Music Department Submission Route",
    websiteUrl: "https://www.cjsr.com/",
    submissionUrl: "https://www.cjsr.com/submit-music/",
    sourceUrl: "https://www.cjsr.com/submit-music/",
    sourceType: "automation_run_168_public_research",
    country: "Canada / Edmonton independent campus-community radio station accepting digital albums or EPs and physical media",
    language: "en",
    genres: ["campus-radio", "community-radio", "radio-airplay", "album-ep-only", "digital-download-links", "bandcamp-codes", "physical-cd-vinyl-cassette", "edmonton", "eclectic", "manual-review"],
    submissionMethod: "official-cjsr-album-ep-digital-physical-music-department-route",
    feeRequired: false,
    feeAmount: "No music submission fee was observed; CJSR lists a separate optional local advertising package unrelated to submission.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because CJSR accepts albums/EPs only, requests files rather than paid-streaming links, asks for track listings, focus tracks, language warnings, MP3 tagging and optional physical package handling.",
    notes: "Public research verified CJSR's official Submit Music page, digital and physical music department routes, Bandcamp code/cloud-download acceptance, album/EP-only requirement, language-warning and metadata guidance. No message was sent and no physical package was prepared."
  },
  {
    name: "CFRU Guelph Digital MP3 Local Form Music Library Submission Route",
    websiteUrl: "https://www.cfru.ca/",
    submissionUrl: "https://www.cfru.ca/music/",
    sourceUrl: "https://www.cfru.ca/music/",
    sourceType: "automation_run_168_public_research",
    country: "Canada / Guelph campus-community radio station with digital music-director email route and local upload form",
    language: "en",
    genres: ["campus-radio", "community-radio", "music-library", "radio-airplay", "high-quality-mp3", "album-ep-only", "local-form", "file-upload-form", "guelph", "manual-review"],
    submissionMethod: "official-cfru-digital-mp3-local-form-music-library-submission-route",
    feeRequired: false,
    feeAmount: "No submission fee was observed; CFRU's route is free-first but contains owner-controlled email/download-link and local upload form choices.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because CFRU asks for EP/album submissions, artist/album/track/contact information, 320 kbps MP3 download links or local-form uploads, cover art, one-sheet/bio and explicit submitter authorization.",
    notes: "Public research verified CFRU's official Music page, public music route, EP/album and 320 kbps MP3 requirements, local music form, upload and download-link fields, cover-art/bio fields and permission checkbox. No form was submitted and no files were uploaded."
  },
  {
    name: "WICB Ithaca Submit Music Navigation and Local Music Airplay Route",
    websiteUrl: "https://wicb.org/",
    submissionUrl: "https://wicb.org/",
    sourceUrl: "https://wicb.org/",
    sourceType: "automation_run_168_public_research",
    country: "United States / Ithaca College radio station with official Submit Music navigation and local music airplay/live-performance context",
    language: "en",
    genres: ["college-radio", "alternative-radio", "radio-airplay", "local-music", "reggae", "hip-hop", "r-and-b", "jazz", "live-performance", "app-content-boundary", "manual-review"],
    submissionMethod: "official-wicb-submit-music-navigation-local-music-route",
    feeRequired: false,
    feeAmount: "No submission fee was observed on the publicly indexed official route; submission surface is navigation/app-content-boundary based and requires manual review.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WICB's official site exposes Submit Music navigation but the fetched route resolves through a dynamic content boundary; local music fit, contact method, recording/live-performance eligibility, metadata and release package should be checked manually.",
    notes: "Public research verified WICB's official site with Submit Music navigation, request/contact support context and independent station-profile context. No dynamic app workflow was entered and no submission was attempted."
  }
];
