import type { PlatformInput } from '../models/types.js';
import { run167SeedPlatforms } from './run167PlatformSeeds.js';

export const run166SeedPlatforms: PlatformInput[] = [
  {
    name: "Spinnin Records Talent Pool Login Demo Upload Route",
    websiteUrl: "https://spinninrecords.com/",
    submissionUrl: "https://spinninrecords.com/talentpool/",
    sourceUrl: "https://spinninrecords.com/talentpool/",
    sourceType: "automation_run_166_public_research",
    country: "Netherlands / global dance label and public producer community with current Talent Pool leaderboard and login-gated demo upload route",
    language: "en",
    genres: ["dance-label", "edm", "electronic", "house", "future-house", "big-room", "producer-community", "demo-upload", "login-boundary", "manual-review"],
    submissionMethod: "official-spinnin-records-talent-pool-login-demo-upload-route",
    feeRequired: false,
    feeAmount: "No submission fee observed on the public Talent Pool page; official route requires account login before demo submission.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Spinnin requires account login, demo ownership/rights confirmation, track fit, metadata, audio readiness, profile choices and any Talent Pool/contest terms to remain owner-controlled.",
    notes: "Public research verified the official Spinnin Talent Pool page, current navigation, login-to-submit copy, most-popular/latest-additions activity and current releases. No account was created, no login was used, no demo was uploaded and no session controls were handled."
  },
  {
    name: "Spotify for Artists Editorial Playlist Pitch Dashboard Route",
    websiteUrl: "https://artists.spotify.com/",
    submissionUrl: "https://artists.spotify.com/en/get-started",
    sourceUrl: "https://artists.spotify.com/en/get-started",
    sourceType: "automation_run_166_public_research",
    country: "Global / Spotify artist dashboard route for release preparation and unreleased-song editorial playlist pitching after distributor delivery",
    language: "en",
    genres: ["streaming", "spotify", "editorial-playlist-pitch", "release-prep", "artist-dashboard", "distributor-required", "login-boundary", "payment-side-route", "manual-review"],
    submissionMethod: "official-spotify-for-artists-editorial-playlist-pitch-dashboard-route",
    feeRequired: false,
    feeAmount: "Spotify for Artists is stated as free to join, but delivery to Spotify requires a distributor that may charge a fee or commission.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Spotify pitching depends on distributor delivery, claimed artist access, unreleased-track timing, playlist pitch copy, metadata, release date, cover art, rights, Canvas/profile choices and possible distributor fee/commission decisions.",
    notes: "Public research verified the official Spotify for Artists get-started page, distributor requirement, release-ready upload guidance, dashboard/profile access and editorial playlist pitch guidance. No Spotify account was accessed, no profile was claimed, no distributor action was taken and no pitch was submitted."
  },
  {
    name: "Bandcamp Free Artist Store Upload Community Discovery Route",
    websiteUrl: "https://bandcamp.com/",
    submissionUrl: "https://bandcamp.com/artists",
    sourceUrl: "https://bandcamp.com/artists",
    sourceType: "automation_run_166_public_research",
    country: "Global / direct-to-fan music store and discovery marketplace for independent artists and labels",
    language: "en",
    genres: ["direct-to-fan", "bandcamp", "digital-release", "merch", "community-discovery", "artist-store", "revenue-share", "freemium", "login-boundary", "manual-review"],
    submissionMethod: "official-bandcamp-free-artist-store-upload-community-discovery-route",
    feeRequired: false,
    feeAmount: "Artist accounts are free; Bandcamp takes a revenue share on digital music and merch sales, with an optional paid Pro tier.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because artist sign-up, store configuration, release upload, pricing, revenue-share/payment setup, merch/physical options, codes, private streaming and optional Pro features require owner decisions.",
    notes: "Public research verified the official Bandcamp for Artists page, active marketplace signals, free artist-account pricing, revenue-share model, optional Pro tier, pricing control, digital/physical product support and community discovery context. No account was created, no music or merch was uploaded, no pricing was set and no payment setup was entered."
  },
  {
    name: "Triple J Unearthed Australian Independent Artist Upload Route",
    websiteUrl: "https://www.abc.net.au/triplejunearthed",
    submissionUrl: "https://www.abc.net.au/triplejunearthed",
    sourceUrl: "https://www.abc.net.au/triplejunearthed",
    sourceType: "automation_run_166_public_research",
    country: "Australia / ABC triple j independent Australian music discovery platform and digital radio route",
    language: "en",
    genres: ["public-broadcaster", "triple-j", "unearthed", "australian-independent", "digital-radio", "staff-reviews", "electronic", "hip-hop", "pop", "login-boundary", "manual-review"],
    submissionMethod: "official-triple-j-unearthed-australian-independent-artist-upload-route",
    feeRequired: false,
    feeAmount: "No submission fee observed on the public Unearthed route; eligibility appears tied to Australian independent artists and account/upload workflow.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because this route appears Australia-focused, requires artist/account/upload eligibility review, rights confirmation, explicit-content handling, profile metadata and competition or broadcast terms before any use.",
    notes: "Public research verified the official ABC triple j Unearthed site, current 2026 staff reviews, active featured artists, tracks played on triple j/Unearthed, Australian discovery positioning and large independent-artist catalog context. No account was created, no login was used and no track/profile upload was attempted."
  },
  {
    name: "Jamendo Artists One Stop Music Licensing Promotion Route",
    websiteUrl: "https://www.jamendo.com/",
    submissionUrl: "https://artists.jamendo.com/",
    sourceUrl: "https://artists.jamendo.com/",
    sourceType: "automation_run_166_public_research",
    country: "Luxembourg / global independent-artist music platform with Jamendo Music, licensing, in-store, Content ID and promotion routes",
    language: "en",
    genres: ["licensing", "sync", "in-store", "content-id", "independent-artists", "jamendo", "worldwide", "artist-services", "login-boundary", "manual-review"],
    submissionMethod: "official-jamendo-artists-one-stop-music-licensing-promotion-route",
    feeRequired: false,
    feeAmount: "No upfront submission fee observed on the public artist-services page; route involves licensing/revenue-share and Content ID monetization decisions.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Jamendo artist services require sign-in, catalog upload, licensing opt-ins, sync/in-store/Content ID choices, revenue-share terms, copyright ownership and collecting-society compatibility review.",
    notes: "Public research verified the official Jamendo Artists page, sign-in/start-now route, Jamendo Music audience reach, sync licensing, in-store placement, Content ID, promotion and compensation language. No sign-in was used, no catalog was uploaded, no licensing or Content ID option was selected and no payment or rights workflow was entered."
  },
  ...run167SeedPlatforms
];
