import type { PlatformInput } from '../models/types.js';
import { run157SeedPlatforms } from './run157PlatformSeeds.js';

export const run156SeedPlatforms: PlatformInput[] = [
  {
    name: "CJSW Digital Album Jotform Music Submission Route",
    websiteUrl: "https://cjsw.com/",
    submissionUrl: "https://cjsw.com/music/submit/",
    sourceUrl: "https://cjsw.com/music/submit/",
    sourceType: "automation_run_156_public_research",
    country: "Canada / Calgary freeform campus-community radio station with digital album submission route",
    language: "en",
    genres: ["campus-radio", "community-radio", "airplay", "digital-album-submission", "independent", "freeform", "electronic", "world", "external-form-boundary", "verified-email-route", "manual-review"],
    submissionMethod: "official-cjsw-digital-album-jotform-music-submission-route",
    feeRequired: false,
    feeAmount: "No music-submission fee observed; digital release upload route and Music & Performance Director assistance email are public, while release package choices remain manual.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because CJSW accepts only digital album submissions released within the last three months, requires a full release with at least three unique tracks, MP3 files in a ZIP package, and uses an external Jotform upload route that must not be auto-submitted.",
    notes: "Public research verified CJSW's official Music Submissions page, digital-only album rules, external upload form link, public Music & Performance Director assistance email and review-rotation/tracking language. No Jotform workflow was opened/submitted, no email was sent and no MP3/ZIP file was uploaded or transferred."
  },
  {
    name: "RTRFM Submit Your Music Form WAV MP3 Airplay Route",
    websiteUrl: "https://rtrfm.com.au/",
    submissionUrl: "https://rtrfm.com.au/submit-your-music/",
    sourceUrl: "https://rtrfm.com.au/submit-your-music/",
    sourceType: "automation_run_156_public_research",
    country: "Australia / Perth independent community radio station with digital form, music email and physical side route",
    language: "en",
    genres: ["community-radio", "airplay", "digital-submission", "music-form", "wav", "high-quality-mp3", "electronic", "indie", "world", "physical-side-route", "verified-email-route", "manual-review"],
    submissionMethod: "official-rtrfm-submit-your-music-form-wav-mp3-airplay-route",
    feeRequired: false,
    feeAmount: "No music-submission fee observed; free digital form/email route is public, with optional physical copies only as a side route.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because RTRFM asks artists to submit a latest or upcoming release through a public form or music email with downloadable WAV/high-quality MP3 links, bio, social links, upcoming gigs and free download links; physical packages must also be accompanied by a free digital submission.",
    notes: "Public research verified RTRFM's official Submit your music page, embedded form fields, public music email route, Music Director contact context, downloadable-link guidance and physical CD side route. No form was submitted, no email was sent, no link was delivered and no physical package was prepared or mailed."
  },
  {
    name: "DistroKid Unlimited Paid Distribution Upload Route",
    websiteUrl: "https://distrokid.com/",
    submissionUrl: "https://distrokid.com/pricing/",
    sourceUrl: "https://distrokid.com/pricing/",
    sourceType: "automation_run_156_public_research",
    country: "Global / United States-based independent music distribution platform with paid annual upload plans",
    language: "en",
    genres: ["digital-distribution", "release-upload", "unlimited-uploads", "spotify", "apple-music", "royalty-splits", "lyrics", "promo-tools", "manual-review", "payment-required", "login-required"],
    submissionMethod: "official-distrokid-unlimited-paid-distribution-upload-route",
    feeRequired: true,
    feeAmount: "Paid annual plans observed from $24.99 billed annually; exact plan, artist count and add-on choices require owner review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because DistroKid uses register/sign-in/account flows, paid annual plan selection, unlimited upload tooling, artist profile settings, royalty splits, lyrics, promo tools and optional advanced features; no automated account creation, payment or upload is allowed.",
    notes: "Public research verified DistroKid's official pricing page, Register/Sign in/Get Started routes, annual paid plans, unlimited song upload language, 100% earnings language and royalty-split/promo-tool context. No account was created, no payment was initiated and no audio/artwork/release metadata was uploaded."
  },
  {
    name: "Amuse Self-Service Distribution App Release Upload Route",
    websiteUrl: "https://www.amuse.io/",
    submissionUrl: "https://www.amuse.io/en/",
    sourceUrl: "https://www.amuse.io/en/",
    sourceType: "automation_run_156_public_research",
    country: "Global / Sweden-based self-service music distribution and artist-label services platform",
    language: "en",
    genres: ["digital-distribution", "release-upload", "self-service", "streaming-services", "social-networks", "artist-label-services", "mastering", "lyrics-verification", "promo-tools", "manual-review", "payment-side-route", "login-required"],
    submissionMethod: "official-amuse-self-service-distribution-app-release-upload-route",
    feeRequired: true,
    feeAmount: "Paid distribution plans observed from $23.99/year or $1.99/month; exact app plan and release choices require owner review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Amuse uses Sign In/Get Started artist-app routes, distribution plan selection, release metadata, streaming/social network delivery, payout controls, mastering, lyrics verification and promo tools.",
    notes: "Public research verified Amuse's official homepage, Distribution/Pricing/Sign In/Get Started links, major streaming/social distribution language, app/web access, 100% royalty language, artist-label services and current 2026 newsroom activity. No account was created, no app workflow entered, no payment initiated and no music file was uploaded."
  },
  {
    name: "Ditto Music Unlimited Distribution Playlist Pitching Route",
    websiteUrl: "https://dittomusic.com/",
    submissionUrl: "https://dittomusic.com/en",
    sourceUrl: "https://dittomusic.com/en",
    sourceType: "automation_run_156_public_research",
    country: "Global / United Kingdom-based music distribution, monetization and promotion platform",
    language: "en",
    genres: ["digital-distribution", "release-upload", "unlimited-releases", "playlist-pitching", "sync-licensing", "music-publishing", "youtube-content-id", "pre-save", "analytics", "manual-review", "payment-side-route", "login-required"],
    submissionMethod: "official-ditto-music-unlimited-distribution-playlist-pitching-route",
    feeRequired: true,
    feeAmount: "Free sign-up and paid subscription/pricing side route observed; distribution, pitching and add-on choices require owner review before use.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Ditto Music uses login/sign-up account creation, release upload, store/platform delivery, playlist pitching, publishing/sync/Content ID options, promo/ad tools and terms acceptance.",
    notes: "Public research verified Ditto's official distribution page, login/try-free/sign-up form, 150+ platform delivery, unlimited releases, playlist-pitching route, sync licensing, publishing, YouTube Content ID and active 2026 site context. No sign-up form was submitted, no payment was initiated and no release/audio/artwork was uploaded."
  },
  ...run157SeedPlatforms,
];
