import type { PlatformInput } from '../models/types.js';
import { run120SeedPlatforms } from './run120PlatformSeeds.js';

export const run119SeedPlatforms: PlatformInput[] = [
  {
    name: "Fresh On The Net Listening Post Weekly Track Submission Route",
    websiteUrl: "https://freshonthenet.co.uk/",
    submissionUrl: "https://freshonthenet.co.uk/submit/",
    sourceUrl: "https://freshonthenet.co.uk/submit/",
    sourceType: "automation_run_119_public_research",
    country: "United Kingdom / global weekly independent-music Listening Post route",
    language: "en",
    genres: ["fresh-on-the-net", "listening-post", "independent-music", "new-music", "one-track", "weekly-window", "soundcloud-profile", "radio-clean", "no-ai-generated-tracks", "free-first", "manual-review"],
    submissionMethod: "official-fresh-on-the-net-listening-post-weekly-track-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Fresh On The Net only opens its inbox during a weekly submission window, limits artists to one track per week, requires public worldwide availability, rejects repeat/remix and AI-generated tracks, and currently shows the inbox as closed.",
    notes: "Official public research confirmed Fresh On The Net publishes a Send Us A Track page, listens to one track per artist per week when the inbox is open, caps or closes the weekly inbox, and shows recent July 2026 Listening Post activity. No form was submitted and no track link was delivered."
  },
  {
    name: "Obscure Sound SubmitHub MusoSoup Email and PR Submission Route",
    websiteUrl: "https://www.obscuresound.com/",
    submissionUrl: "https://www.obscuresound.com/about/contact/",
    sourceUrl: "https://www.obscuresound.com/about/contact/",
    sourceType: "automation_run_119_public_research",
    country: "United States / global independent music blog editorial and PR route",
    language: "en",
    genres: ["obscure-sound", "music-blog", "indie-rock", "indie-pop", "dream-pop", "folk", "electronic", "alt-rnb", "hip-hop", "ambient", "submithub", "musosoup", "email-route", "music-pr", "freemium", "manual-review"],
    submissionMethod: "official-obscure-sound-submithub-musosoup-email-pr-submission-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Obscure Sound offers multiple routes with different obligations: SubmitHub feedback, SubmitHub Marketplace for albums and EPs, MusoSoup, direct email and paid PR services. Route choice, account/payment boundaries, pitch package and contact handling must be reviewed.",
    notes: "Official public research confirmed Obscure Sound has current July 2026 posts, covers electronic and hip-hop alongside indie genres, and publishes Contact/Submissions guidance for SubmitHub, MusoSoup and direct email. The fetched email value was redacted and was not decoded or guessed; no platform session was opened and no message was sent."
  },
  {
    name: "The Other Side Reviews MusoSoup and Editorial Contact Submission Route",
    websiteUrl: "https://www.theothersidereviews.com/",
    submissionUrl: "https://www.theothersidereviews.com/contact/",
    sourceUrl: "https://www.theothersidereviews.com/contact/",
    sourceType: "automation_run_119_public_research",
    country: "United Kingdom / international music reviews interviews and track-of-the-day route",
    language: "en",
    genres: ["the-other-side-reviews", "music-blog", "single-reviews", "album-reviews", "video-reviews", "interviews", "track-of-the-day", "musosoup", "editorial-contact", "global-artists", "freemium", "manual-review"],
    submissionMethod: "official-the-other-side-reviews-musosoup-editorial-contact-submission-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because The Other Side Reviews recommends MusoSoup to guarantee a listen, also exposes a direct contact route, and currently receives high submission volume. MusoSoup account/payment boundaries and editorial fit must be reviewed before use.",
    notes: "Official public research confirmed The Other Side Reviews is active with July 2026 reviews and interviews, publishes a contact page, recommends MusoSoup to guarantee a listen and provides a direct contact route. The fetched contact was redacted and was not decoded or guessed; no MusoSoup session or email was used."
  },
  {
    name: "Under the Radar Magazine JavaScript-Protected Submissions Contact Route",
    websiteUrl: "https://www.undertheradarmag.com/",
    submissionUrl: "https://www.undertheradarmag.com/contact",
    sourceUrl: "https://www.undertheradarmag.com/contact",
    sourceType: "automation_run_119_public_research",
    country: "United States / global indie music magazine submissions contact route",
    language: "en",
    genres: ["under-the-radar", "music-magazine", "indie-music", "album-reviews", "premieres", "pleased-to-meet-you", "news", "reviews", "submissions-contact", "javascript-obfuscated-contact", "free-first", "manual-review"],
    submissionMethod: "official-under-the-radar-magazine-javascript-protected-submissions-contact-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Under the Radar lists a public Submissions department route but the contact is JavaScript-protected; no protected contact should be decoded automatically, and pitch fit must be reviewed before any outreach.",
    notes: "Official public research confirmed Under the Radar is active in July 2026, publishes reviews, news and interviews, and lists a Submissions department on its Contact page, while email addresses are protected behind JavaScript. No obfuscated contact was decoded and no email was sent."
  },
  {
    name: "The Line of Best Fit New Unsigned Artist Google Form Submission Route",
    websiteUrl: "https://www.thelineofbestfit.com/",
    submissionUrl: "https://docs.google.com/forms/d/e/1FAIpQLSdnvDWw7n5iLoVqzjS_DlnOCgkyETJ7Es1a7YL0bgmkdbuawQ/viewform",
    sourceUrl: "https://www.thelineofbestfit.com/contact",
    sourceType: "automation_run_119_public_research",
    country: "United Kingdom / global new and unsigned artist editorial form route",
    language: "en",
    genres: ["the-line-of-best-fit", "new-music", "unsigned-artists", "google-form", "rap-rnb-hip-hop", "indie-guitar", "jazz-world", "pop", "dance-club", "one-track", "newsletter-option", "free-first", "manual-review"],
    submissionMethod: "official-line-of-best-fit-new-unsigned-artist-google-form-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because The Line of Best Fit routes new and unsigned artists to a public Google Form with required email, role, artist, genre, one-sentence bio and one-track fields; the form shows a JavaScript/session warning and optional Google sign-in to save progress.",
    notes: "Official public research confirmed The Line of Best Fit is active in July 2026, welcomes music from new and unsigned artists on its contact page, and links to a Google Form asking for one best song aligned with coverage plus required artist and track fields. No form was filled or submitted."
  },
  ...run120SeedPlatforms
];
