import type { PlatformInput } from '../models/types.js';

export const run177SeedPlatforms: PlatformInput[] = [
  {
    name: "FBi Radio Sydney Music Submissions Email Route",
    websiteUrl: "https://www.fbi.radio/",
    submissionUrl: "https://www.fbi.radio/contact",
    sourceUrl: "https://www.fbi.radio/contact",
    sourceType: "automation_run_177_public_research",
    country: "Australia / Sydney independent emerging-music radio email submission route",
    language: "en",
    genres: ["independent-radio", "emerging-music", "sydney", "australian", "electronic", "bass", "hip-hop", "dance", "music-submissions-email", "manual-review"],
    submissionMethod: "official-fbi-radio-music-submissions-email-route",
    feeRequired: false,
    feeAmount: "No submission fee observed; FBi publishes a Music Submissions email route on its official contact page.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because FBi uses a public music-submission email route; owner-approved pitch copy, release links, clean/radio-edit status, Australian/Sydney relevance, rights and attachment/download-link policy must be checked before sending.",
    notes: "Public research verified the official FBi contact page, Music Submissions route, general station contacts, postal address, current July 2026 featured episodes/articles and emerging Sydney music positioning. No email was sent and no files or links were delivered."
  },
  {
    name: "Triple R Melbourne Streaming Download Music Department Submission Route",
    websiteUrl: "https://www.rrr.org.au/",
    submissionUrl: "https://www.rrr.org.au/get-involved/submit-music",
    sourceUrl: "https://www.rrr.org.au/get-involved/submit-music",
    sourceType: "automation_run_177_public_research",
    country: "Australia / Melbourne independent radio presenter-discretion route",
    language: "en",
    genres: ["independent-radio", "melbourne", "electronic", "hip-hop", "first-nations", "world", "experimental", "download-link", "music-department", "manual-review"],
    submissionMethod: "official-triple-r-streaming-download-music-department-submission-route",
    feeRequired: false,
    feeAmount: "No submission fee observed; Triple R publishes free service-the-station and direct-presenter routes with streaming/download links and optional physical media.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Triple R is not playlisted, each presenter chooses tracks, and the route requires a clear subject line, public stream link, non-expiring high-quality MP3/WAV download link, bio, gig details and no large email attachments.",
    notes: "Public research verified the official Triple R Submit Music page, music@rrr.org.au route, presenter-direct service option, non-playlisted presenter-discretion policy, high-quality download requirements, physical postal route and current July 2026 homepage/program activity. No email was sent and no package was prepared."
  },
  {
    name: "Edge Radio Hobart Digital Download Physical Music Department Route",
    websiteUrl: "https://www.edgeradio.org.au/",
    submissionUrl: "https://www.edgeradio.org.au/submit-your-music/",
    sourceUrl: "https://www.edgeradio.org.au/submit-your-music/",
    sourceType: "automation_run_177_public_research",
    country: "Australia / Hobart youth community radio global emerging-artist route",
    language: "en",
    genres: ["community-radio", "youth-radio", "tasmanian", "australian", "emerging-artists", "electronic", "indie", "digital-download", "physical-cd", "manual-review"],
    submissionMethod: "official-edge-radio-digital-download-physical-music-department-route",
    feeRequired: false,
    feeAmount: "No submission fee observed for airplay submission; paid promotional-campaign side route exists separately and was marked manual-only.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Edge requests bio/gig details, stream link, high-quality download link, optional multiple physical CDs, Tasmanian-submission subject handling and separate paid promotional-campaign boundaries.",
    notes: "Public research verified Edge Radio's official Submit Your Music page, Music Department physical route, digital requirements for stream and high-quality download links, current Edge Recommended/music-news activity and paid promotional side-route language. Protected email links were observed but not decoded; no email was sent and no paid campaign was initiated."
  },
  {
    name: "Three D Radio Adelaide MP3 Form and Physical Library Submission Route",
    websiteUrl: "https://threedradio.com/",
    submissionUrl: "https://threedradio.com/get-involved-page/submit-your-music/",
    sourceUrl: "https://threedradio.com/get-involved-page/submit-your-music/",
    sourceType: "automation_run_177_public_research",
    country: "Australia / Adelaide progressive alternative community radio form route",
    language: "en",
    genres: ["community-radio", "adelaide", "south-australia", "progressive", "alternative", "local-music", "electronic", "mp3-upload", "form-boundary", "manual-review"],
    submissionMethod: "official-three-d-radio-mp3-form-physical-library-submission-route",
    feeRequired: false,
    feeAmount: "No submission fee observed; Three D uses a digital music submission form and accepts physical CDs/vinyl for its music library.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Three D requires careful form reading, .mp3-only files for digital submissions, cloud or Bandcamp download-code access, full-album/EP preference, no email/DM submissions and physical-library metadata if mailed or dropped off.",
    notes: "Public research verified Three D's official Submit Your Music page, Music Committee route, volunteer-run/manual-library context, .mp3-only rule, no email/DM submission policy, mail@threedradio.com support route for form issues, physical CD/vinyl route and current 2026 site activity. No form was submitted and no files were uploaded."
  },
  {
    name: "Fresh On The Net Weekly Listening Post SoundCloud Submission Route",
    websiteUrl: "https://freshonthenet.co.uk/",
    submissionUrl: "https://freshonthenet.co.uk/submit/",
    sourceUrl: "https://freshonthenet.co.uk/submit/",
    sourceType: "automation_run_177_public_research",
    country: "United Kingdom / global independent artist blog listening-post route",
    language: "en",
    genres: ["music-blog", "independent-artists", "listening-post", "soundcloud", "electronic", "pop", "indie", "weekly-form", "public-track", "manual-review"],
    submissionMethod: "official-fresh-on-the-net-weekly-listening-post-soundcloud-submission-route",
    feeRequired: false,
    feeAmount: "No submission fee observed; Fresh On The Net allows one public SoundCloud track per artist per week while the inbox window is open.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Fresh On The Net restricts submissions to one public, worldwide-available, embeddable SoundCloud track per week; repeat/remix/private/restricted tracks and AI-generated/composition disclosures require owner verification before use.",
    notes: "Public research verified the official Fresh On The Net homepage, active 2026 batches, Send Us A Track page, one-track weekly inbox, Listening Post/Fresh Faves process, public SoundCloud URL requirement, anti-vote-manipulation terms and radio-side clean-edit guidance. No form was submitted and no SoundCloud URL was delivered."
  }
];
