import type { PlatformInput } from '../models/types.js';

export const run183BaseSeedPlatforms: PlatformInput[] = [
  {
    name: "Audiomack Creator App Limitless Upload Discovery Route",
    websiteUrl: "https://audiomack.com/",
    submissionUrl: "https://creators.audiomack.com/upload",
    sourceUrl: "https://audiomack.com/world/post/audiomack-creator-app",
    sourceType: "automation_run_183_public_research",
    country: "Global / creator upload, discovery, fan connection and analytics route",
    language: "en",
    genres: ["creator-platform", "music-upload", "afrobeats", "hip-hop", "latin", "electronic", "reggae", "dance", "analytics", "fan-connect", "manual-review"],
    submissionMethod: "official-audiomack-creator-app-upload-discovery-route",
    feeRequired: false,
    feeAmount: "Audiomack publicly exposes a creator upload route and says artists/creators can upload limitless music and podcasts; account, rights, creator-app permissions, monetization/supporter eligibility and promotional tools require manual review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Audiomack uses Sign Up/Sign In and creator upload boundaries. Release ownership, explicit/clean metadata, artwork/audio assets, monetization eligibility, fan messaging, promotional assets and terms must be approved before any upload or profile action.",
    notes: "Official Audiomack pages show Sign Up/Sign In and an Upload route, and state that Audiomack allows artists and creators to upload limitless music and podcasts through its mobile apps and website. No signup, upload, fan-message, monetization or promo action was initiated."
  },
  {
    name: "BBC Music Introducing UK UGC Upload Producer Route",
    websiteUrl: "https://www.bbc.co.uk/introducing",
    submissionUrl: "https://www.bbc.co.uk/introducing/uploader",
    sourceUrl: "https://en.wikipedia.org/wiki/BBC_Music_Introducing",
    sourceType: "automation_run_183_public_research",
    country: "United Kingdom / BBC unsigned artist uploader and local-to-national radio route",
    language: "en",
    genres: ["unsigned-artists", "radio", "bbc", "electronic", "dance", "urban", "pop", "local-radio", "festival-stages", "ugc", "manual-review"],
    submissionMethod: "official-bbc-music-introducing-ugc-upload-producer-route",
    feeRequired: false,
    feeAmount: "Free-first BBC Introducing upload route, but UK/local routing, BBC account/session requirements, postcode eligibility, UGC terms and rights declarations require manual review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because the BBC Introducing uploader routes tracks by postcode/local show and classifies submitted material as UGC. UK eligibility, account/session access, song ownership, explicit content, artist location and BBC Terms of Use must be verified before any upload.",
    notes: "Public research verified BBC Music Introducing as an active BBC upload platform for unsigned and under-the-radar UK artists, with direct music upload to Introducing producers/presenters and possible forwarding to BBC radio networks. No BBC account, upload or UGC submission was created."
  },
  {
    name: "Radiooooo Curated Global Map Song Contribution Route",
    websiteUrl: "https://radiooooo.com/",
    submissionUrl: "https://app.radiooooo.com/",
    sourceUrl: "https://www.newyorker.com/culture/culture-desk/radiooooo-the-hit-tune-time-machine",
    sourceType: "automation_run_183_public_research",
    country: "Global / France curated world-map music discovery contribution route",
    language: "en/fr",
    genres: ["global-music", "world", "reggae", "afrobeat", "electronic", "curated-radio", "time-map", "community-curation", "freemium", "manual-review"],
    submissionMethod: "official-radiooooo-community-song-contribution-curation-route",
    feeRequired: false,
    feeAmount: "Radiooooo is described as freemium/subscription for listeners and accepts user song uploads/contributions for curation; account/app access, curation fit, country/decade tagging and rights require manual review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Radiooooo uses an app/account contribution path and editorial curation. Territory/decade tagging, sound quality, copyright ownership, cultural metadata, app/session boundaries and fit with its curated aesthetic need owner approval before any upload.",
    notes: "Public research verified Radiooooo as an active music discovery app where users can upload songs or tracks that are curated by DJs/producers and placed on an interactive global map if selected. No account, contribution, upload or subscription action was initiated."
  },
  {
    name: "Mixcloud Registered Creator DJ Mix Upload Streaming Route",
    websiteUrl: "https://www.mixcloud.com/",
    submissionUrl: "https://www.mixcloud.com/upload/",
    sourceUrl: "https://en.wikipedia.org/wiki/Mixcloud",
    sourceType: "automation_run_183_public_research",
    country: "Worldwide / licensed DJ mix, radio show and podcast upload route",
    language: "en",
    genres: ["dj-mixes", "radio-shows", "podcasts", "electronic", "dance", "reggae", "dub", "licensed-streaming", "creator-subscriptions", "manual-review"],
    submissionMethod: "official-mixcloud-registered-creator-upload-streaming-route",
    feeRequired: false,
    feeAmount: "Mixcloud upload is free-first for registered users, with optional creator monetization/subscription context; account, licensing, metadata, tracklists and creator monetization terms require manual review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Mixcloud requires registration to upload and is designed for radio shows, DJ mixes and podcasts rather than arbitrary single-track pitching. Tracklist accuracy, licensing, creator subscription settings, metadata and non-download streaming restrictions must be reviewed.",
    notes: "Public research verified Mixcloud as an active worldwide streaming community where registered users upload radio shows, DJ mixes and podcasts, with licensing and metadata requirements. No registration, upload, mix/show creation or subscription configuration was initiated."
  },
  {
    name: "Songtradr Artist Upload Sync Licensing Marketplace Route",
    websiteUrl: "https://www.songtradr.com/",
    submissionUrl: "https://www.songtradr.com/",
    sourceUrl: "https://en.wikipedia.org/wiki/Songtradr",
    sourceType: "automation_run_183_public_research",
    country: "Global / sync licensing marketplace and artist upload route",
    language: "en",
    genres: ["sync-licensing", "music-supervision", "advertising", "film-tv", "games", "electronic", "instrumental", "world", "licensing-fees", "manual-review"],
    submissionMethod: "official-songtradr-artist-upload-sync-licensing-marketplace-route",
    feeRequired: false,
    feeAmount: "Songtradr artist upload/licensing route appears free-first to enter, but sync licensing, pricing, rights splits, PRO/publishing details and marketplace terms require manual review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Songtradr licensing can expose tracks to commercial sync opportunities. Master/publishing ownership, co-writer splits, PRO data, pricing, exclusivity, territory, payout/tax setup and licensing permissions must be approved before upload or listing.",
    notes: "Public research verified Songtradr as an automated music licensing marketplace where artists can upload music, set licensing fees and make recordings searchable for ads, film and TV use. No account, upload, listing, price, pitch, license or payment action was initiated."
  }
];
