import type { PlatformInput } from '../models/types.js';

export const run181BaseSeedPlatforms: PlatformInput[] = [
  {
    name: "Volumo Artist Label Electronic Download Store Submission Route",
    websiteUrl: "https://volumo.com/",
    submissionUrl: "https://volumo.com/about",
    sourceUrl: "https://volumo.com/about",
    sourceType: "automation_run_181_public_research",
    country: "Global / electronic music download store artist-label route",
    language: "en",
    genres: ["electronic", "dance", "edm", "download-store", "artist-label", "curated-catalog", "wav", "flac", "aiff", "mp3", "manual-review"],
    submissionMethod: "official-volumo-artist-label-electronic-download-store-route",
    feeRequired: false,
    feeAmount: "No public submission fee observed during research; Volumo exposes an artist/label route and public support contact, while label/distribution-partner terms require manual review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Volumo is a curated electronic download store working with artists, labels and distribution partners; rights, catalog ownership, audio formats, revenue-share terms, support contact use and account/label onboarding need owner approval.",
    notes: "Public research verified Volumo's official artist/label positioning, electronic-store activity, daily release model, 75% rightsholder share language, AFEM-approved download-site status and public support@volumo.com contact. No account was created and no file or message was sent."
  },
  {
    name: "TopHit Rights Holder Radio TV Upload Testing Route",
    websiteUrl: "https://tophit.com/",
    submissionUrl: "https://tophit.com/",
    sourceUrl: "https://en.wikipedia.org/wiki/TopHit",
    sourceType: "automation_run_181_public_research",
    country: "Global / radio TV broadcaster music testing and download platform route",
    language: "en",
    genres: ["radio-promotion", "tv-promotion", "airplay", "music-testing", "rights-holder-upload", "electronic", "dance", "pop", "global", "manual-review"],
    submissionMethod: "public-tophit-rights-holder-upload-radio-tv-testing-route",
    feeRequired: false,
    feeAmount: "No public submission fee confirmed during research; registration, upload, testing and broadcaster-download terms require manual review before use.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because TopHit routes producers, rightsholders and labels through platform upload/testing workflows for radio/TV users; rights-holder authority, metadata, territory, registration/session boundaries and broadcaster-use terms must be approved.",
    notes: "Public research verified TopHit platform activity, artist/label upload context, radio/TV user base and cross-country airplay/chart functionality. The official site presented an access boundary during research; no account, upload, test or message was initiated."
  },
  {
    name: "ReverbNation Independent Artist Profile Opportunities Route",
    websiteUrl: "https://www.reverbnation.com/",
    submissionUrl: "https://www.reverbnation.com/",
    sourceUrl: "https://en.wikipedia.org/wiki/ReverbNation",
    sourceType: "automation_run_181_public_research",
    country: "Global / independent artist profile discovery and opportunity platform route",
    language: "en",
    genres: ["independent-artists", "artist-profile", "music-opportunities", "fan-discovery", "electronic", "pop", "world", "reggae", "freemium", "manual-review"],
    submissionMethod: "public-reverbnation-independent-artist-profile-opportunities-route",
    feeRequired: false,
    feeAmount: "Registration is publicly described as optional/free at platform level, but opportunity, promotion and subscription terms require manual review before any action.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because ReverbNation uses artist-profile/account workflows, possible opportunity listings, promotion/subscription options, profile assets, music links, rights and platform terms that must be owner-approved.",
    notes: "Public research verified ReverbNation as an active independent-music social/discovery platform owned by BandLab with profile and fan-discovery tooling. No login, profile creation, upload, opportunity application or payment action was performed."
  },
  {
    name: "KCRW Local Regional Recording Airplay Consideration Route",
    websiteUrl: "https://www.kcrw.com/",
    submissionUrl: "https://www.kcrw.com/",
    sourceUrl: "https://www.kcrw.com/",
    sourceType: "automation_run_181_public_research",
    country: "United States / Los Angeles public radio local-regional airplay consideration route",
    language: "en",
    genres: ["public-radio", "npr", "aaa", "local-music", "regional-artists", "touring-artists", "electronic", "world", "alternative", "manual-review"],
    submissionMethod: "public-kcrw-local-regional-recording-airplay-consideration-route",
    feeRequired: false,
    feeAmount: "No public submission fee observed in research; exact recording-delivery route and local/regional/touring fit require manual review.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KCRW consideration appears focused on local/regional/touring artist recordings, while exact package format, contact route, regional fit, clean/radio-edit readiness and outreach copy need owner approval.",
    notes: "Public research verified KCRW station activity and public reporting that local/regional touring artists can send recordings for consideration. No email, package, upload or contact form submission was made."
  },
  {
    name: "Beatport Label Distributor Electronic Music Store Route",
    websiteUrl: "https://www.beatport.com/",
    submissionUrl: "https://www.beatport.com/",
    sourceUrl: "https://en.wikipedia.org/wiki/Beatport",
    sourceType: "automation_run_181_public_research",
    country: "Global / electronic music store label-distributor ingestion route",
    language: "en",
    genres: ["electronic", "dance", "dj-store", "label-distribution", "download-store", "streaming", "rightsholder", "mp3", "lossless", "manual-review"],
    submissionMethod: "public-beatport-label-distributor-electronic-music-store-route",
    feeRequired: false,
    feeAmount: "No direct public self-serve submission fee confirmed during research; Beatport access normally depends on authorized label/distributor/rightsholder routes and commercial terms requiring review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because no direct public self-serve artist form was confirmed; Beatport is a curated electronic-music store, so label/distributor eligibility, catalog ownership, royalty terms, metadata, territories and approved ingestion path must be reviewed first.",
    notes: "Public research verified Beatport as a global electronic-music store with label catalog and rightsholder-payment context. This is queued only for authorized distributor/label-route review; no account, upload, distributor action, store listing or payment was initiated."
  }
];
