import type { PlatformInput } from '../models/types.js';
import { run127SeedPlatforms } from './run127PlatformSeeds.js';

export const run126SeedPlatforms: PlatformInput[] = [
  {
    name: "KEXP Global Music Director Digital Airplay Submission Route",
    websiteUrl: "https://www.kexp.org/",
    submissionUrl: "mailto:md@kexp.org",
    sourceUrl: "https://www.kexp.org/about/getting-airplay/submission-guidelines/",
    sourceType: "automation_run_126_public_research",
    country: "Global / US public radio digital airplay submission route",
    language: "en",
    genres: ["kexp", "public-radio", "airplay", "music-director", "digital-submission", "streaming-link", "wav-download", "clean-radio-edit", "no-payola", "manual-review"],
    submissionMethod: "official-kexp-global-music-director-digital-airplay-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KEXP asks for streaming or download links, WAV downloads, artist and release metadata, pronunciation guidance, focus tracks, release timing, clean radio edits, lyric sheets, credits, bio or one-sheet context and show information. No outbound email, link delivery or audio-file transfer should be automated.",
    notes: "Official public research confirmed KEXP submission guidelines are active, direct digital music submissions to the Music Director email route, reject physical submissions, describe playlist/archive verification paths and state there is no pay-to-play. No email was sent, no streaming/download links were delivered and no audio files were transferred."
  },
  {
    name: "WXPN Music Director and Local Show Digital Airplay Submission Route",
    websiteUrl: "https://xpn.org/",
    submissionUrl: "https://xpn.org/contact/",
    sourceUrl: "https://xpn.org/contact/",
    sourceType: "automation_run_126_public_research",
    country: "US / Philadelphia public radio digital airplay and local-show submission route",
    language: "en",
    genres: ["wxpn", "public-radio", "music-director", "airplay", "local-show", "epk", "download-link", "wav", "mp3", "manual-review"],
    submissionMethod: "official-wxpn-music-director-and-local-show-digital-airplay-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WXPN requests an EPK, digital download link, Local Show package choices, WAV or high-quality MP3 links, artist bio and upcoming show context. Submission fit, regional relevance, message copy and any file or link delivery must remain owner-reviewed.",
    notes: "Official public research confirmed WXPN exposes Music Director and Local Show music submission routes through its contact page and states no confirmation of receipt or airplay can be guaranteed. No email was sent, no download link was delivered and no media file was transferred."
  },
  {
    name: "WFMU Music Director Physical Library Submission and Contact Route",
    websiteUrl: "https://wfmu.org/",
    submissionUrl: "https://www.wfmu.org/sendmusic.html",
    sourceUrl: "https://www.wfmu.org/sendmusic.html",
    sourceType: "automation_run_126_public_research",
    country: "US / New Jersey independent freeform radio physical music submission route",
    language: "en",
    genres: ["wfmu", "independent-radio", "freeform-radio", "music-director", "physical-submission", "vinyl", "cd", "cassette", "mail-route", "manual-review"],
    submissionMethod: "official-wfmu-music-director-physical-library-submission-and-contact-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WFMU's public Send Us Music route is physical/package-first, with vinyl, CD, CD-R or cassette mailing instructions and a Music Director contact route. Package preparation, physical mail handling, label copy, format choice and follow-up contact must remain manual.",
    notes: "Official public research confirmed WFMU is active in 2026, publishes current playlists/archives, and provides Send Us Music instructions for physical media to the Music Director route. No physical package was prepared or sent and no contact form or staff message was submitted."
  },
  {
    name: "KCRW Active Music Programming Contact and Airplay Research Route",
    websiteUrl: "https://www.kcrw.com/",
    submissionUrl: "https://www.kcrw.com/contact",
    sourceUrl: "https://www.kcrw.com/contact",
    sourceType: "automation_run_126_public_research",
    country: "US / Los Angeles public radio music programming contact route",
    language: "en",
    genres: ["kcrw", "public-radio", "music-programming", "morning-becomes-eclectic", "airplay-research", "contact-route", "manual-review"],
    submissionMethod: "official-kcrw-active-music-programming-contact-and-airplay-research-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KCRW's official public site and contact page confirm an active music-programming environment but the fetched public contact page did not expose a complete direct music-submission form or business email. Route legitimacy, correct department/contact path, pitch copy and link delivery require manual verification before outreach.",
    notes: "Official public research confirmed KCRW is active in 2026 with current music playlists, Morning Becomes Eclectic programming, live event listings and a public Contact page. A secondary public reference describes KCRW airplay consideration for local and regional artists. No form was submitted, no contact was guessed and no protected contact was decoded."
  },
  {
    name: "BBC Music Introducing Unsigned Artist Upload and Local Show Route",
    websiteUrl: "https://www.bbc.co.uk/introducing/",
    submissionUrl: "https://www.bbc.co.uk/introducing/uploader",
    sourceUrl: "https://www.bbc.co.uk/introducing/",
    sourceType: "automation_run_126_public_research",
    country: "UK / unsigned and emerging artist upload route with local-show routing",
    language: "en",
    genres: ["bbc-introducing", "unsigned-artist", "upload-tool", "local-radio", "artist-registration", "postcode-routing", "login", "manual-review"],
    submissionMethod: "official-bbc-music-introducing-unsigned-artist-upload-and-local-show-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because BBC Music Introducing uses an account/upload tool, local-show routing, artist registration and eligibility boundaries. Login, UK/postcode routing, UGC terms, rights status, track selection and any upload must remain owner-controlled. The official public page was not bypassed when fetch access was restricted.",
    notes: "Public research identified BBC Music Introducing as an upload route for unsigned artists, routed to local Introducing shows after registration. The official BBC page was not bypassed where automated fetch access was restricted. No login was used, no account was created and no track was uploaded."
  },
  ...run127SeedPlatforms
];
