import type { PlatformInput } from '../models/types.js';
import { run114SeedPlatforms } from './run114PlatformSeeds.js';

export const run113SeedPlatforms: PlatformInput[] = [
  {
    name: "Groover Curator Playlist Radio Label and DJ Submission Platform Route",
    websiteUrl: "https://groover.co/",
    submissionUrl: "https://groover.co/",
    sourceUrl: "https://groover.co/",
    sourceType: "automation_run_113_public_research",
    country: "France / Global paid music-promotion and curator submission platform",
    language: "en",
    genres: ["groover", "music-promotion", "curators", "playlists", "radio", "labels", "djs", "blogs", "independent-artists", "electronic", "reggae", "dub", "world", "hip-hop", "paid-credits", "account-boundary", "upload-boundary", "manual-review"],
    submissionMethod: "official-groover-curator-playlist-radio-label-dj-submission-platform-route",
    feeRequired: true,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Groover is an official paid credit-based route requiring account/session handling, curator targeting, track upload or private-link handling, pitch copy, genre filters and payment approval before any submission can occur.",
    notes: "Official public research confirmed Groover lets artists send music to curators, playlists, radio, labels and DJs, supports many genres including electronic and world music, and uses paid Grooviz credits with refund rules for non-response. No account was created, no login was used, no track was uploaded, no curators were selected and no payment was initiated."
  },
  {
    name: "Soundplate Free Spotify and Deezer Playlist Submission Route",
    websiteUrl: "https://soundplate.com/",
    submissionUrl: "https://play.soundplate.com/",
    sourceUrl: "https://play.soundplate.com/",
    sourceType: "automation_run_113_public_research",
    country: "United Kingdom / Global free playlist submission system",
    language: "en",
    genres: ["soundplate", "playlist-submission", "spotify", "deezer", "electronic", "dance", "house", "garage", "bass", "festival", "independent-curators", "free-first", "public-form", "manual-review"],
    submissionMethod: "official-soundplate-free-spotify-deezer-playlist-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Soundplate exposes a public free playlist submission workflow, but each playlist must be selected manually and the track/playlist fit, link format, release status, rights, anti-spam guidance and curator relevance must be reviewed before use.",
    notes: "Official public research confirmed Soundplate Play invites artists to select a playlist, submit music to Spotify and Deezer playlists, says the service is free, and warns users to submit only to relevant playlists and not spam. No playlist was selected, no form was submitted, no track link was delivered and no account/session controls were handled."
  },
  {
    name: "Playlist Push Spotify Playlist and TikTok Creator Campaign Submission Route",
    websiteUrl: "https://playlistpush.com/",
    submissionUrl: "https://playlistpush.com/",
    sourceUrl: "https://playlistpush.com/",
    sourceType: "automation_run_113_public_research",
    country: "United States / Global paid Spotify playlist and TikTok creator promotion platform",
    language: "en",
    genres: ["playlist-push", "spotify-playlists", "tiktok-creators", "organic-curators", "music-promotion", "independent-artists", "electronic", "reggae", "dub", "world", "hip-hop", "paid-campaign", "account-boundary", "manual-review"],
    submissionMethod: "official-playlist-push-spotify-playlist-tiktok-campaign-submission-route",
    feeRequired: true,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Playlist Push is a paid campaign platform requiring account/session handling, campaign setup, budget approval, Spotify or TikTok route choice, song matching, creative brief review and payment approval before any outreach occurs.",
    notes: "Official public research confirmed Playlist Push offers artist services for Spotify playlist and TikTok promotion, has vetted curator and creator networks, uses artist dashboards and campaign reporting, and lists paid campaign pricing. No account was created, no campaign was configured, no creator/curator was contacted and no payment was initiated."
  },
  {
    name: "One Submit Curator Blog Radio Label Playlist and TikTok Submission Platform Route",
    websiteUrl: "https://www.one-submit.com/",
    submissionUrl: "https://www.one-submit.com/",
    sourceUrl: "https://www.one-submit.com/",
    sourceType: "automation_run_113_public_research",
    country: "Global paid music-promotion and curator submission platform",
    language: "en",
    genres: ["one-submit", "music-promotion", "spotify-playlists", "youtube-channels", "tiktok-influencers", "music-blogs", "radio-stations", "record-labels", "independent-artists", "electronic", "paid-campaign", "account-boundary", "upload-boundary", "manual-review"],
    submissionMethod: "official-one-submit-curator-blog-radio-label-playlist-tiktok-submission-platform-route",
    feeRequired: true,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because One Submit is a paid campaign/upload route requiring account/session handling, song upload or link entry, campaign-type choice, genre targeting, budget/payment approval and review of claims before any submission can be queued externally.",
    notes: "Official public research confirmed One Submit routes music to Spotify playlists, TikTok influencers, YouTube channels, music blogs, online radio stations and record labels, says artists upload music and receive curator reviews, and discloses that its services are not free and do not guarantee placement. No account was created, no upload happened, no campaign was started and no payment was initiated."
  },
  {
    name: "TAXI Independent A&R Record Label Publishing and Sync Licensing Submission Route",
    websiteUrl: "https://www.taxi.com/",
    submissionUrl: "https://www.taxi.com/",
    sourceUrl: "https://www.taxi.com/",
    sourceType: "automation_run_113_public_research",
    country: "United States / Global paid independent A&R and music licensing opportunity route",
    language: "en",
    genres: ["taxi", "independent-ar", "record-labels", "publishing", "sync-licensing", "film-tv", "production-music", "music-supervisors", "songwriters", "composers", "artists", "paid-membership", "member-login", "manual-review"],
    submissionMethod: "official-taxi-independent-ar-record-label-publishing-sync-licensing-submission-route",
    feeRequired: true,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because TAXI is a member/login-based independent A&R opportunity route involving paid membership, opportunity-listing selection, song/instrumental suitability, metadata, rights, pitch fit and licensing strategy review before any submission.",
    notes: "Official public research confirmed TAXI is an independent A&R company with Submit Music and member-login routes, offering opportunities for major/indie labels, publishers, film/TV supervisors, production libraries, ad agencies and game companies. The site also shows current 2026 activity. No membership was started, no login was used, no music was submitted and no payment was initiated."
  },
  ...run114SeedPlatforms
];
