import type { PlatformInput } from '../models/types.js';

export const run184BaseSeedPlatforms: PlatformInput[] = [
  {
    name: "WERS Wicked Local Wednesday Boston MP3 Upload Form Route",
    websiteUrl: "https://wers.org/",
    submissionUrl: "https://wers.org/wicked-local-wednesday/",
    sourceUrl: "https://wers.org/wicked-local-wednesday/",
    sourceType: "automation_run_184_public_research",
    country: "United States / Boston and New England local artist radio feature route",
    language: "en",
    genres: ["college-radio", "public-radio", "local-music", "electronic", "reggae", "afrobeat", "pop", "hip-hop", "mp3-upload", "manual-review"],
    submissionMethod: "official-wers-wicked-local-wednesday-mp3-upload-form-route",
    feeRequired: false,
    feeAmount: "Free-first WERS local artist feature route; public form accepts MP3 music files but Boston-area eligibility, upload size, metadata, privacy and reCAPTCHA/form boundaries require manual review.",
    loginRequired: false,
    captchaDetected: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WERS uses a public form with music-file upload and site reCAPTCHA protection. Boston-area/local fit, MP3 size, radio edit, artist/contact consent, metadata and follow-up routing must be approved before any form submission or file transfer.",
    notes: "Official WERS pages expose Music > Submit Music and the Wicked Local Wednesday form route. The form asks for artist/band name, contact information and MP3 music files. No form was submitted and no file was uploaded."
  },
  {
    name: "WMSE Milwaukee Physical Digital Music Director Submission Route",
    websiteUrl: "https://www.wmse.org/",
    submissionUrl: "https://www.wmse.org/submit-music/",
    sourceUrl: "https://www.wmse.org/submit-music/",
    sourceType: "automation_run_184_public_research",
    country: "United States / Milwaukee freeform radio music director route",
    language: "en",
    genres: ["freeform-radio", "college-radio", "electronic", "reggae", "dub", "world", "hip-hop", "alternative", "cd", "vinyl", "digital-transfer", "manual-review"],
    submissionMethod: "official-wmse-physical-digital-music-director-submission-route",
    feeRequired: false,
    feeAmount: "Free-first WMSE route accepting CD, vinyl, digital WeTransfer/email and cassette paths; format choice, explicit-content marking and follow-up expectations require manual review.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WMSE accepts multiple delivery modes and gives explicit review instructions. Package format, Music Director email usage, WeTransfer link handling, explicit-content notices, release timing and interview/live-performance fit must be checked before contact or transfer.",
    notes: "Official WMSE submission page lists physical drop/mail guidance and digital submission via WeTransfer or email to Music Director Sid McCain at mccain@msoe.edu. No email, transfer or package was sent."
  },
  {
    name: "WMBR MIT Physical Freeform Music Director Submission Route",
    websiteUrl: "https://wmbr.org/",
    submissionUrl: "https://wmbr.org/music.html",
    sourceUrl: "https://wmbr.org/music.html",
    sourceType: "automation_run_184_public_research",
    country: "United States / Cambridge MIT freeform radio physical music-review route",
    language: "en",
    genres: ["freeform-radio", "college-radio", "physical-submission", "electronic", "reggae", "dub", "world", "hip-hop", "experimental", "manual-review"],
    submissionMethod: "official-wmbr-mit-physical-freeform-music-director-submission-route",
    feeRequired: false,
    feeAmount: "Free-first WMBR physical review-material route; tangible media, postal delivery, genre-program fit and hidden/protected contact routes require manual review.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WMBR asks artists to send tangible physical material rather than MP3 review and says DJs select music independently. Physical package preparation, show targeting, local/interview expectations and protected contact images must be reviewed without decoding protected contacts.",
    notes: "Official WMBR guidance says to mail music to the Music Director and prefers tangible physical forms for unsigned bands; chart and genre-contact emails were presented as images and were not decoded. No package or message was prepared."
  },
  {
    name: "KXCI Tucson Global Digital Physical Music Department Submission Route",
    websiteUrl: "https://kxci.org/",
    submissionUrl: "https://kxci.org/music-department/",
    sourceUrl: "https://kxci.org/music-department/",
    sourceType: "automation_run_184_public_research",
    country: "United States / Tucson community radio global digital and physical route",
    language: "en",
    genres: ["community-radio", "global-music", "electronic", "reggae", "world", "afrobeat", "hip-hop", "local-priority", "digital-download", "physical-copy", "manual-review"],
    submissionMethod: "official-kxci-global-digital-physical-music-department-submission-route",
    feeRequired: false,
    feeAmount: "Free-first KXCI route accepting music from all over the world, while prioritizing Tucson/Arizona/regional artists; digital links, physical copies, explicit-content details and protected email display require manual review.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KXCI accepts worldwide submissions but prioritizes local and regional artists. Required metadata, explicit-content notices, Tucson/regional performance context, digital download links, physical-copy routing and protected contact handling must be approved before outreach.",
    notes: "Official KXCI Music Department page states it accepts and broadcasts music from all over the world and accepts CDs, vinyl with digital download, and MP3/WAV download links. The displayed email was protected/obfuscated and not decoded."
  },
  {
    name: "KZSU Stanford Music Director Email Postal Submission Guidelines Route",
    websiteUrl: "https://kzsu.stanford.edu/",
    submissionUrl: "https://kzsu.stanford.edu/contact/",
    sourceUrl: "https://kzsu.stanford.edu/contact/",
    sourceType: "automation_run_184_public_research",
    country: "United States / Stanford freeform college radio music-director route",
    language: "en",
    genres: ["college-radio", "freeform-radio", "independent-music", "electronic", "reggae", "world", "hip-hop", "mail", "music-director-email", "cookie-session-boundary", "manual-review"],
    submissionMethod: "official-kzsu-music-director-email-postal-submission-guidelines-route",
    feeRequired: false,
    feeAmount: "Free-first KZSU Music Director contact and postal route; public contact page lists music@kzsu.stanford.edu and physical mail, but linked music guidelines expose a cookie/session boundary requiring manual review.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KZSU explicitly asks senders to choose appropriate email routes and the linked music-submission guidelines are behind a cookie/session boundary. Music Director email usage, postal option, genre fit, spam-avoidance guidance and acceptable-use policy need review before contact.",
    notes: "Official KZSU contact page lists a Music Directors section with a send-us-music link, music@kzsu.stanford.edu, and KZSU Music postal addresses. The music page redirected to a cookie-required boundary; it was not bypassed. No email or package was sent."
  }
];