import type { PlatformInput } from '../models/types.js';

export const run163SeedPlatforms: PlatformInput[] = [
  {
    name: "Groover Paid Curator Radio Label Playlist Pitch Route",
    websiteUrl: "https://groover.co/en/",
    submissionUrl: "https://groover.co/en/",
    sourceUrl: "https://groover.co/en/",
    sourceType: "automation_run_163_public_research",
    country: "Global / France-founded music-promotion platform with international curator, radio, playlist, label, DJ and media routes",
    language: "en",
    genres: ["music-promotion", "playlist-pitching", "radio", "labels", "djs", "media", "electronic", "hip-hop", "world", "reggae", "paid-credits", "login-required", "manual-review"],
    submissionMethod: "official-groover-paid-curator-radio-label-playlist-pitch-route",
    feeRequired: true,
    feeAmount: "Paid credit model observed; official page states curator/pro contact starts at 2 Grooviz = 2€ and credits must be purchased to send tracks to chosen curators/pros.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Groover requires account/session flow, paid credit purchase, track/demo upload or link, curator targeting, pitch copy, rights review and budget decisions before any campaign can be launched.",
    notes: "Public research verified Groover's official active 2026 site, 3,000+ curator/pro positioning, supported genre coverage, contact/chat route, pricing/credit model and login/sign-up routes. No account was created, no payment was initiated, no curator was selected and no music was uploaded."
  },
  {
    name: "Musosoup Campaign Review Music Promotion Marketplace Route",
    websiteUrl: "https://musosoup.com/",
    submissionUrl: "https://app.musosoup.com/",
    sourceUrl: "https://musosoup.com/",
    sourceType: "automation_run_163_public_research",
    country: "Global / music-promotion marketplace for independent artists and curators",
    language: "en",
    genres: ["music-promotion", "blogs", "reviews", "playlisting", "curator-marketplace", "independent-artists", "mp3-upload", "campaign-fee", "login-required", "manual-review"],
    submissionMethod: "official-musosoup-campaign-review-music-promotion-marketplace-route",
    feeRequired: true,
    feeAmount: "Submission/start can begin without upfront cost, but official workflow states approved artists create an account and pay the campaign fee; page also references campaigns starting from £42 plus free/paid curator offers.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Musosoup includes upload/link choices, internal submission review, account creation after approval, campaign fee, optional paid/free offers, release timing and curator-offer selection that must remain owner-controlled.",
    notes: "Public research verified Musosoup's official active 2026 site, Submit music route, app.musosoup.com boundary, campaign review language, campaign-fee/payment language, curator marketplace, contact form and recent July 2026 blog activity. No app workflow was entered, no form was submitted, no account was created and no campaign was paid or activated."
  },
  {
    name: "DailyPlaylists Free Standard Spotify Playlist Submission Route",
    websiteUrl: "https://dailyplaylists.com/",
    submissionUrl: "https://dailyplaylists.com/",
    sourceUrl: "https://dailyplaylists.com/",
    sourceType: "automation_run_163_public_research",
    country: "Global / Spotify playlist submission marketplace for artists and playlist curators",
    language: "en",
    genres: ["spotify-playlists", "playlist-pitching", "free-standard-tier", "premium-credits", "artist-pro", "curator-marketplace", "electronic", "pop", "hip-hop", "login-required", "manual-review"],
    submissionMethod: "official-dailyplaylists-free-standard-spotify-playlist-submission-route",
    feeRequired: false,
    feeAmount: "Standard submission route advertises free music submission to playlist curators; premium credits and professional tier are payment side routes.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because DailyPlaylists requires sign-in and Spotify track lookup/linking, playlist selection, curator targeting, tier choice, rights and profile authorization decisions before any submission.",
    notes: "Public research verified DailyPlaylists official 2026 site, free Standard Tier, 18,000+ playlist marketplace, Premium Credits/Professional side routes, Submit a Song route and official public info@dailyplaylists.com contact. No login was used, no Spotify account was connected, no playlist was selected and no submission was sent."
  },
  {
    name: "Soundplate Free Spotify Playlist Submission Directory Route",
    websiteUrl: "https://soundplate.com/",
    submissionUrl: "https://soundplate.com/",
    sourceUrl: "https://soundplate.com/",
    sourceType: "automation_run_163_public_research",
    country: "Global / UK-based independent music marketing and playlist submission platform",
    language: "en",
    genres: ["spotify-playlists", "free-playlist-submissions", "independent-artists", "record-label", "music-marketing-tools", "afrobeats", "drum-and-bass", "electronic", "reggae-dancehall", "world-music", "manual-review"],
    submissionMethod: "official-soundplate-free-spotify-playlist-submission-directory-route",
    feeRequired: false,
    feeAmount: "No submission fee observed for the free playlist submission directory; advertising, smart-link and other promotion tools exist as separate side routes.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Soundplate exposes many playlist-specific submit routes and genre filters; owner must choose playlist fit, review per-playlist requirements, Spotify link/auth expectations, rights, metadata and anti-spam constraints before any action.",
    notes: "Public research verified Soundplate's official active 2026 site, independent-artist positioning, Submit Music to Playlists route, Free Playlist Submissions link, genre taxonomy including Afrobeats/Afropop, Drum & Bass, House/Electronic/Dance, Reggae/Dancehall and World Music, and a 403 boundary on the contact route. No playlist page form was submitted, no account was used and no contact route boundary was handled."
  },
  {
    name: "RepostExchange SoundCloud Partner Feedback Campaign Route",
    websiteUrl: "https://repostexchange.com/welcome",
    submissionUrl: "https://repostexchange.com/welcome",
    sourceUrl: "https://repostexchange.com/welcome",
    sourceType: "automation_run_163_public_research",
    country: "Global / SoundCloud-connected creator promotion and feedback network",
    language: "en",
    genres: ["soundcloud", "creator-community", "feedback", "credits", "electronic", "edm", "deep-house", "techno", "trap", "hip-hop", "soundcloud-login", "manual-review"],
    submissionMethod: "official-repostexchange-soundcloud-partner-feedback-campaign-route",
    feeRequired: false,
    feeAmount: "Free-to-use model observed with optional credit/plan purchase side route; official page states free forever and no credit card required while buying credits/plans can accelerate reach.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because RepostExchange requires SoundCloud account connection, track selection, credit/campaign decisions, permission review and platform-compliance review before any campaign action.",
    notes: "Public research verified RepostExchange's official active 2026 site, official SoundCloud Partner positioning, 500,000+ creator community, free-to-use claim, credit model, SoundCloud connection requirement and login/pricing boundary. No SoundCloud account was connected and no campaign was created."
  }
];
