import type { PlatformInput } from '../models/types.js';

export const run297SeedPlatforms: PlatformInput[] = [
  {
    "name": "IndieXL Official New Single 320kbps MP3 Upload Form Route",
    "websiteUrl": "https://www.indiexl.nl/",
    "submissionUrl": "https://www.indiexl.nl/submit/",
    "sourceUrl": "https://www.indiexl.nl/submit/",
    "sourceType": "automation_run_297_public_research",
    "country": "Netherlands / global online indie and alternative radio with a public new-single MP3 upload form",
    "language": "nl/en",
    "genres": ["indiexl", "online-radio", "indie", "alternative", "new-music", "single", "mp3-upload", "320kbps", "genre-restricted", "manual-review"],
    "submissionMethod": "official-indiexl-new-current-single-320kbps-mp3-upload-form-route",
    "feeRequired": false,
    "feeAmount": "No submission fee or payment requirement is stated on IndieXL's official music-upload page.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "IndieXL accepts only new/current singles that fit its indie and alternative format, explicitly excludes Hip Hop, Rap, House, EDM, Pop, R&B and Urban, and requires an actual tagged 320-kbps MP3 named Artist – Title.mp3 with a maximum size of 12 MB. A human must confirm that the selected MarcsMusic track genuinely fits the station format, verify metadata and file size, approve the upload fields and submit the file manually.",
    "notes": "Verified on 2026-07-12 from IndieXL's official submission page and active 2026 homepage, charts and new-music sections. The form requests name, email, social profiles, message and audio upload. Spotify, YouTube, Bandcamp and SoundCloud links are explicitly rejected. The displayed general contact uses an obfuscated (at) format and was not decoded or used as an alternate submission route."
  },
  {
    "name": "KANM Student Radio Official Artist Submission Google Form Route",
    "websiteUrl": "https://kanm.org/",
    "submissionUrl": "https://kanm.org/contact",
    "sourceUrl": "https://kanm.org/contact",
    "sourceType": "automation_run_297_public_research",
    "country": "United States / Texas A&M student radio with an official external artist-submission form",
    "language": "en",
    "genres": ["kanm", "student-radio", "college-radio", "independent", "experimental", "alternative", "electronic", "hip-hop", "world", "artist-submission", "google-form", "manual-review"],
    "submissionMethod": "official-kanm-artist-submission-external-google-form-route",
    "feeRequired": false,
    "feeAmount": "No submission fee or payment requirement is stated on KANM's official artist-submission route.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "KANM explicitly directs artists to an external Google Form for music review. The form target could not be safely inspected through the crawler, so its live fields, session state, upload or link requirements, consent language and any runtime verification controls remain unknown. A human must open the authorized form normally, review every requirement and submit manually without using the public Music Director email as a workaround.",
    "notes": "Verified on 2026-07-12 from KANM's official contact and station pages. The site separately publishes md@kanm.org for the Music Directors and a different form for live studio sessions, but the dedicated Artist Submissions form is the primary music-review route. KANM shows an active stream, schedule, releases and live-session activity, with a 2026 site footer. No form, email or session was used."
  },
  {
    "name": "KZUU 90.7 FM Official Music-by-Mail and Band Contact Route",
    "websiteUrl": "https://kzuu.org/",
    "submissionUrl": "https://kzuu.org/contact-us/",
    "sourceUrl": "https://kzuu.org/contact-us/",
    "sourceType": "automation_run_297_public_research",
    "country": "United States / Washington State University student radio with physical music servicing and a public band-contact route",
    "language": "en",
    "genres": ["kzuu", "college-radio", "student-radio", "independent", "underground", "alternative", "electronic", "hip-hop", "world", "physical-media", "band-contact", "manual-review"],
    "submissionMethod": "official-kzuu-music-by-mail-and-band-information-contact-route",
    "feeRequired": false,
    "feeAmount": "No submission fee is stated; media-production and postage costs apply only if the physical route is used.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "KZUU says sending music by mail is generally the fastest way to reach the station and publishes a public General Manager address for telling the station about an artist or managed band. It does not publish complete accepted-media, file, metadata, clean-edit, return or release-window rules. A human must choose either a concise information inquiry or the physical route, confirm the current package requirements and avoid duplicate delivery.",
    "notes": "Verified on 2026-07-12 from KZUU's official contact and active station pages. The site publishes Bridget.a.murphy@wsu.edu for band information and a station P.O. box, and shows 2026 interviews plus current streaming and scheduling. No email, form, file, link or physical package was sent."
  },
  {
    "name": "KWVA 88.1 FM Official Demo and Music Donation Physical Route",
    "websiteUrl": "https://kwva.uoregon.edu/",
    "submissionUrl": "https://kwva.uoregon.edu/send-us-your-music",
    "sourceUrl": "https://kwva.uoregon.edu/send-us-your-music",
    "sourceType": "automation_run_297_public_research",
    "country": "United States / University of Oregon student radio with a physical demo and music-donation route",
    "language": "en",
    "genres": ["kwva", "college-radio", "student-radio", "independent", "freeform", "electronic", "alternative", "hip-hop", "world", "physical-demo", "music-donation", "manual-review"],
    "submissionMethod": "official-kwva-band-demo-and-music-donation-physical-route",
    "feeRequired": false,
    "feeAmount": "No submission fee is stated; physical-media production and shipping costs apply.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "KWVA directs band demos and music donations to its Music Director mailing address. Its public music@kwvaradio.org address is specifically presented for discussing an interview, not as permission to deliver digital music. A human must confirm the accepted physical format, prepare the demo or donation package, review metadata and clean/explicit notes, and mail it manually; any interview inquiry must remain separate and asset-free unless requested.",
    "notes": "Verified on 2026-07-12 from the official University of Oregon KWVA Send Us Your Music page and active station homepage. KWVA broadcasts live 24/7 and published music and chart items in May and June 2026. No email, interview request, digital submission or physical package was sent."
  },
  {
    "name": "KCOU 88.1 FM Official New-Submitter Music Director and Physical Review Route",
    "websiteUrl": "https://kcou.fm/",
    "submissionUrl": "https://kcou.fm/contact/",
    "sourceUrl": "https://kcou.fm/contact/",
    "sourceType": "automation_run_297_public_research",
    "country": "United States / University of Missouri student-owned radio with a new-submitter Music Director inquiry and physical review policy",
    "language": "en",
    "genres": ["kcou", "college-radio", "student-radio", "independent", "alternative", "electronic", "hip-hop", "world", "radio-friendly", "physical-media", "music-director", "manual-review"],
    "submissionMethod": "official-kcou-new-submitter-music-director-inquiry-and-physical-review-route",
    "feeRequired": false,
    "feeAmount": "No submission fee or payment requirement is stated; physical-media production and shipping costs may apply.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "KCOU tells labels, promoters and independent artists with no prior station relationship to call or email the Music Director for instructions before beginning record service or providing submissions. Its policy then asks for radio-friendly, airable-quality recordings with band contact information and recommends a media kit, while giving no airplay guarantee. A human must make an asset-free routing inquiry first, confirm the accepted delivery format, review profanity or clean-edit status and prepare any physical package manually.",
    "notes": "Verified on 2026-07-12 from KCOU's official contact and Music Submission Policy page and active station homepage, which contains music and interview posts through May 2026. The official Music Director contact is exposed as a protected/non-plaintext link in the crawler and was not decoded or guessed. No call, email, submission or package was made."
  }
];
