import type { PlatformInput } from '../models/types.js';

export const run287SeedPlatforms: PlatformInput[] = [
  {
    "name": "HEXAGON HQ Trackstack House and Bass House Demo Route",
    "websiteUrl": "https://www.hexagonhq.com/",
    "submissionUrl": "https://www.hexagonhq.com/",
    "sourceUrl": "https://www.hexagonhq.com/",
    "sourceType": "automation_run_287_public_research",
    "country": "Netherlands / Amsterdam-based global electronic label with embedded Trackstack demo intake",
    "language": "en",
    "genres": ["hexagon", "house", "bass-house", "club-bangers", "electronic", "trackstack", "embedded-demo", "dynamic-upload", "manual-review"],
    "submissionMethod": "official-hexagon-hq-embedded-trackstack-demo-intake",
    "feeRequired": false,
    "feeAmount": "No demo-submission fee or payment requirement is stated on the official HEXAGON HQ demo section.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "HEXAGON HQ explicitly opens demos through an embedded Trackstack workflow and is looking for House, Bass House and Club Bangers. The complete runtime fields, file limits, declarations, session state and any challenge controls are not exposed in the static page. A human must confirm track fit, final-master status, originality, rights, metadata and the live Trackstack form before upload.",
    "notes": "Verified on 2026-07-11 from the official HEXAGON HQ website. The site says demos are open, Don Diablo opens every file himself, identifies the Main label and states that the workflow is powered by Trackstack. The site carries a 2026 copyright notice and an active label catalogue. No form, file, account, cookie control, email or payment route was used."
  },
  {
    "name": "Future House Cloud SubmitHub Playlist Submission Route",
    "websiteUrl": "https://futurehousecloud.com/",
    "submissionUrl": "https://www.submithub.com/playlister/future-house-cloud",
    "sourceUrl": "https://futurehousecloud.com/contact/",
    "sourceType": "automation_run_287_public_research",
    "country": "Germany / global future, deep-house and electronic promotion channel",
    "language": "en",
    "genres": ["future-house-cloud", "future-house", "deep-house", "electronic", "playlist-submission", "submithub", "account-session-boundary", "freemium", "manual-review"],
    "submissionMethod": "official-future-house-cloud-submithub-playlist-submission-route",
    "feeRequired": false,
    "feeAmount": "The official site routes submissions to SubmitHub; free and optional premium-credit conditions must be reviewed in the live account workflow.",
    "loginRequired": true,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "Future House Cloud explicitly forbids track submissions through its contact form and routes them to its official SubmitHub playlister page. A human must use an owner-controlled SubmitHub account, review free versus premium-credit options, confirm curator fit, track rights, metadata and release status, and complete any session or platform controls. Do not use the general contact form or copyright address for music submissions.",
    "notes": "Verified on 2026-07-11 from the official Future House Cloud homepage and contact page. The site identifies itself as an independent label and YouTube channel for future and deep house, links the SubmitHub route in primary navigation, carries a 2026 copyright notice and shows an active upload catalogue. copyright@futurehousecloud.com is publicly listed only for rights/removal matters and was not treated as a submission email. No account, login, credits, form, email or track link was used."
  },
  {
    "name": "Dharma Worldwide Basic and Pro Demo Drop Route",
    "websiteUrl": "https://www.dharmaworldwide.com/",
    "submissionUrl": "https://demos.dharmaworldwide.com/",
    "sourceUrl": "https://www.dharmaworldwide.com/",
    "sourceType": "automation_run_287_public_research",
    "country": "United States / global electronic label and producer community with account-controlled demo drop",
    "language": "en",
    "genres": ["dharma-worldwide", "electronic", "edm", "world-fusion", "festival", "house", "mp3-upload", "account-login", "freemium", "manual-review"],
    "submissionMethod": "official-dharma-worldwide-account-controlled-mp3-demo-drop",
    "feeRequired": false,
    "feeAmount": "Basic members can submit for listening without guaranteed feedback; optional Pro membership is advertised at USD 9.99 monthly or USD 95.88 yearly for guaranteed feedback and other benefits.",
    "loginRequired": true,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "The official Dharma demo portal requires sign-in and an MP3 upload. Basic submissions are listened to without guaranteed feedback, while paid Pro membership offers guaranteed feedback. A human must review account ownership, free-versus-Pro choice, master and rights status, metadata, label fit, terms and any live session controls before upload or subscription.",
    "notes": "Verified on 2026-07-11 from the official Dharma Studio site and its linked demo portal. The portal says new community music is central to Dharma, distinguishes Basic and Pro feedback treatment and provides an MP3 drag-and-drop intake. The main site carries a 2026 copyright notice and current tutorials, products and label releases. No account, sign-in, subscription, payment, file, form or consent action was used."
  },
  {
    "name": "Kannibalen Records Public Label Intake Routing Inquiry",
    "websiteUrl": "https://www.kannibalenrecords.com/",
    "submissionUrl": "mailto:label@kannibalenrecords.com",
    "sourceUrl": "https://www.kannibalenrecords.com/contact",
    "sourceType": "automation_run_287_public_research",
    "country": "Canada / Montreal bass-music label with public general-inquiry routing",
    "language": "en",
    "genres": ["kannibalen-records", "bass-music", "dubstep", "drum-and-bass", "electro", "future-bass", "trap", "public-business-email", "pre-submission-inquiry", "manual-review"],
    "submissionMethod": "official-public-label-email-for-asset-free-demo-routing-inquiry",
    "feeRequired": false,
    "feeAmount": "No fee applies to a short routing inquiry; no direct demo-delivery policy is published on the official contact page.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "Kannibalen publishes label@kannibalenrecords.com for General Inquiries but does not publish complete unsolicited-demo delivery rules. Queue only a short asset-free inquiry asking whether demos are open and which authorized route and format to use. A human must approve the inquiry copy and must not attach audio, send track links or repurpose the separate press or sync addresses.",
    "notes": "Verified on 2026-07-11 from the official contact, artists and releases pages. Public business contacts are label@kannibalenrecords.com for general inquiries, tyler@kannibalenrecords.com for press and baokhanh@kannibalenrecords.com for sync. The site displays an extensive release catalogue and active artist roster. Only the general label address is suitable for a routing question; no deliverability probing, email, attachment or link delivery occurred."
  },
  {
    "name": "Mixmash Records Human-Verification Demo Routing Inquiry Form",
    "websiteUrl": "https://www.mixmashrecords.com/",
    "submissionUrl": "https://www.mixmashrecords.com/contact",
    "sourceUrl": "https://www.mixmashrecords.com/contact",
    "sourceType": "automation_run_287_public_research",
    "country": "Netherlands / Amsterdam house label with public contact form and human-verification boundary",
    "language": "en",
    "genres": ["mixmash-records", "house", "electro-house", "future-house", "progressive-house", "electronic", "contact-form", "human-verification", "pre-submission-inquiry", "manual-review"],
    "submissionMethod": "official-mixmash-contact-form-for-asset-free-demo-routing-inquiry",
    "feeRequired": false,
    "feeAmount": "No fee is stated for the official contact form; it is not represented as a direct demo uploader.",
    "loginRequired": false,
    "captchaDetected": true,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "Mixmash publishes an official contact form but no complete current unsolicited-demo policy on the public page. The form includes a visual code that must be copied, so it is a human-verification boundary. Queue only an asset-free routing inquiry asking whether demos are open and which authorized route to use. A human must inspect the live fields, complete verification and approve the message; no music file or track link should be supplied through this inquiry unless Mixmash explicitly instructs it.",
    "notes": "Verified on 2026-07-11 from the official Mixmash homepage and contact page. The site shows current releases, playlists, artists, events and a weekly Mixmash Radio series, and lists its Amsterdam headquarters. The contact form displays a human-entered visual code. No public demo email was exposed or guessed, and no form, verification code, file, link, email or payment route was used."
  }
];
