import type { PlatformInput } from '../models/types.js';

export const run21SeedPlatforms: PlatformInput[] = [
  {
    name: 'Groover Global Curator Playlist Radio and Label Pitching Route',
    websiteUrl: 'https://groover.co/',
    submissionUrl: 'https://groover.co/',
    sourceUrl: 'https://groover.co/',
    sourceType: 'automation_run_21_public_research',
    country: 'France / United States / global curator and industry-pro reach',
    language: 'en',
    genres: ['electronic', 'reggae', 'world', 'pop', 'hip-hop', 'indie', 'dance'],
    submissionMethod: 'paid-credit-curator-campaign-route-needs-login-payment-targeting-and-rights-review',
    feeRequired: true,
    feeAmount: 'Credits required; public page indicates paid credits for curator/pro contact.',
    loginRequired: true,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: 'Requires account access, credit purchase, curator targeting, track/demo link or upload, pitch text, rights ownership and campaign-review decisions.',
    notes: 'Official public page shows thousands of curators/pros, broad genre support, guaranteed feedback and paid credits. No account, upload, payment or campaign launch was attempted.'
  },
  {
    name: 'MusoSoup Global Music PR Curator Campaign Route',
    websiteUrl: 'https://musosoup.com/',
    submissionUrl: 'https://app.musosoup.com/',
    sourceUrl: 'https://musosoup.com/',
    sourceType: 'automation_run_21_public_research',
    country: 'United Kingdom / global curator network',
    language: 'en',
    genres: ['independent', 'electronic', 'reggae', 'world', 'pop', 'rock', 'hip-hop', 'afrobeats'],
    submissionMethod: 'curator-marketplace-campaign-route-needs-review-account-and-payment-check',
    feeRequired: true,
    feeAmount: 'Public page indicates campaign pricing while some coverage options may be free.',
    loginRequired: true,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: 'Requires submission review, account creation, campaign fee/payment decision, upload or link submission, rights confirmation and paid/free offer triage.',
    notes: 'Official public page lists a submit-music app route, global curator partners and manual submission review. No account, upload, payment or offer acceptance was attempted.'
  },
  {
    name: 'DailyPlaylists Spotify Playlist Submission Marketplace Route',
    websiteUrl: 'https://dailyplaylists.com/',
    submissionUrl: 'https://dailyplaylists.com/',
    sourceUrl: 'https://dailyplaylists.com/',
    sourceType: 'automation_run_21_public_research',
    country: 'Global playlist marketplace',
    language: 'en',
    genres: ['electronic', 'dance', 'reggae', 'world', 'pop', 'hip-hop', 'independent'],
    submissionMethod: 'spotify-track-link-playlist-marketplace-route-needs-login-track-link-and-curator-matching-review',
    feeRequired: false,
    loginRequired: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Requires sign-in, Spotify track/link selection, playlist relevance matching, curator selection and platform terms review before submission.',
    notes: 'Official public page exposes Submit a Song, many playlists, a standard free tier and a public business contact. No sign-in or submit action was attempted.'
  },
  {
    name: 'Soundplate Free Spotify and Deezer Playlist Submission Route',
    websiteUrl: 'https://play.soundplate.com/',
    submissionUrl: 'https://play.soundplate.com/',
    sourceUrl: 'https://play.soundplate.com/',
    sourceType: 'automation_run_21_public_research',
    country: 'United Kingdom / global independent playlist reach',
    language: 'en',
    genres: ['house', 'techno', 'deep-house', 'garage', 'bass', 'disco', 'festival', 'electronic'],
    submissionMethod: 'free-playlist-grid-select-and-submit-route-needs-playlist-relevance-and-form-review',
    feeRequired: false,
    loginRequired: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Requires manual playlist relevance review and form inspection per selected playlist; automation must avoid irrelevant bulk submissions.',
    notes: 'Official public page says artists can submit music to Spotify and Deezer playlists for free by selecting relevant playlists. No form submission or playlist selection was attempted.'
  },
  {
    name: 'Jamendo Artists Licensing In-Store and Promotion Route',
    websiteUrl: 'https://artists.jamendo.com/',
    submissionUrl: 'https://artists.jamendo.com/',
    sourceUrl: 'https://artists.jamendo.com/',
    sourceType: 'automation_run_21_public_research',
    country: 'Luxembourg / global licensing and in-store reach',
    language: 'en',
    genres: ['independent', 'electronic', 'world', 'reggae', 'cinematic', 'instrumental', 'ambient'],
    submissionMethod: 'artist-service-sign-in-route-for-licensing-instore-content-id-and-promotion-needs-rights-review',
    feeRequired: false,
    loginRequired: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Requires sign-in, catalog upload, rights and collecting-society compatibility review, licensing opt-in, Content ID and promotion choices.',
    notes: 'Official artist page lists audience reach, licensing, in-store placement, Content ID and promotion. No sign-in, upload, license opt-in or rights declaration was attempted.'
  },
  {
    name: 'TAXI Independent A&R Music Licensing and Label Opportunity Route',
    websiteUrl: 'https://www.taxi.com/',
    submissionUrl: 'https://www.taxi.com/submit-music/',
    sourceUrl: 'https://www.taxi.com/',
    sourceType: 'automation_run_21_public_research',
    country: 'United States / global A&R and sync opportunity reach',
    language: 'en',
    genres: ['songwriter', 'electronic', 'reggae', 'world', 'cinematic', 'instrumental', 'pop', 'production-music'],
    submissionMethod: 'membership-ar-listings-route-needs-membership-payment-listing-fit-and-rights-review',
    feeRequired: true,
    loginRequired: true,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: 'Requires membership/login, listing-fit review, possible fees, rights ownership, metadata and sync/label opportunity suitability assessment.',
    notes: 'Official page lists Submit Music and industry listings for labels, publishers, supervisors, libraries, ad agencies and game companies. No membership, payment, listing access or submission was attempted.'
  },
  {
    name: 'Audiosocket Artist Music Licensing Submission Route',
    websiteUrl: 'https://www.audiosocket.com/artists',
    submissionUrl: 'https://www.audiosocket.com/artists',
    sourceUrl: 'https://www.audiosocket.com/artists',
    sourceType: 'automation_run_21_public_research',
    country: 'United States / global music licensing reach',
    language: 'en',
    genres: ['independent', 'electronic', 'world', 'reggae', 'cinematic', 'ambient', 'instrumental'],
    submissionMethod: 'public-submit-music-contribution-route-needs-catalog-rights-and-contract-review',
    feeRequired: false,
    loginRequired: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Requires submit-music flow review, catalog fit, rights ownership, publishing/master control, licensing terms and possible account access.',
    notes: 'Official artist page exposes a Contribute > Submit Music link. No form entry, account creation, catalog upload or licensing agreement acceptance was attempted.'
  },
  {
    name: 'Radio Airplay Jango Independent Artist Upload and Airplay Route',
    websiteUrl: 'https://www.radioairplay.com/',
    submissionUrl: 'https://www.radioairplay.com/',
    sourceUrl: 'https://www.radioairplay.com/',
    sourceType: 'automation_run_21_public_research',
    country: 'United States / global internet-radio reach',
    language: 'en',
    genres: ['independent', 'electronic', 'dance', 'reggae', 'world', 'pop', 'hip-hop'],
    submissionMethod: 'artist-account-track-upload-and-airplay-campaign-route-needs-login-plan-and-rights-review',
    feeRequired: false,
    feeAmount: 'Public page lists a free package and paid packages.',
    loginRequired: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Requires account creation, song upload, plan selection, rights confirmation, style targeting and review of paid options before campaign use.',
    notes: 'Official page shows free sign-up, track upload, song reviews, contests and internet-radio targeting. No sign-up, upload, plan selection or messaging was attempted.'
  }
];
