import type { PlatformInput } from '../models/types.js';

export const run286SeedPlatforms: PlatformInput[] = [
  {
    "name": "Dirty Workz Native Hard Dance Demo Upload Route",
    "websiteUrl": "https://dirtyworkz.com/",
    "submissionUrl": "https://dirtyworkz.com/demos/",
    "sourceUrl": "https://dirtyworkz.com/demos/",
    "sourceType": "automation_run_286_public_research",
    "country": "Belgium / global hard dance label and native demo-upload route",
    "language": "en",
    "genres": ["dirty-workz", "hardstyle", "hard-dance", "rawstyle", "euphoric-hardstyle", "dw-x-copyright-free", "native-upload", "audio-file", "cookie-consent-boundary", "manual-review"],
    "submissionMethod": "official-native-dirty-workz-demo-upload-form",
    "feeRequired": false,
    "feeAmount": "No demo-submission fee or payment requirement is stated on the official Dirty Workz demo page.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "The native form requires a final audio file, track title, email, artist name, genre and an originality/rights confirmation. Dirty Workz limits delivery to one track at a time and three per day, strongly discourages unofficial remixes or bootlegs, requires cleared samples and asks that the track remain exclusive for at least 30 days. A human must approve the master, rights, exclusivity window, metadata and cookie boundary before upload. Do not send demos to licensing@dirtyworkz.com or social channels.",
    "notes": "Verified on 2026-07-11 from the official demo and contact pages. Accepted formats are MP3, WAV, FLAC, AAC and OGG up to 50 MB. The official site says every submission receives an answer and current activity includes 2026 news, playlists and releases. licensing@dirtyworkz.com is publicly listed only for licensing requests and was not treated as a demo address. No form, cookie control, file, email or social route was used."
  },
  {
    "name": "Scantraxx Hard Dance Tstack Demo Upload Route",
    "websiteUrl": "https://www.scantraxx.com/",
    "submissionUrl": "https://www.scantraxx.com/demos",
    "sourceUrl": "https://www.scantraxx.com/demos",
    "sourceType": "automation_run_286_public_research",
    "country": "Netherlands / global hard dance label group and official external demo uploader",
    "language": "en",
    "genres": ["scantraxx", "hardstyle", "hard-dance", "raw-hardstyle", "hard-techno-adjacent", "mp3", "wav", "tstack", "external-upload", "manual-review"],
    "submissionMethod": "official-scantraxx-demo-page-with-tstack-upload-form",
    "feeRequired": false,
    "feeAmount": "No mandatory demo-submission fee is stated on the official Scantraxx demo page.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "Scantraxx accepts only finished Hard Dance productions in MP3 or WAV and rejects fully AI-generated tracks, works in progress and snippets. The official page embeds or links to an external Tstack uploader whose complete live fields, file limits, declarations, privacy terms and runtime challenge state require manual inspection. A human must confirm genre fit, final-master status, AI-use status, rights, metadata and the external form before upload.",
    "notes": "Verified on 2026-07-11 from the official Scantraxx demo, company and homepage pages. The site names its A&R reviewers, says suitable demos are contacted within 30 days and lists releases dated through 2026-07-10. No public demo email was exposed or guessed. The Tstack form was not submitted and no account, file, cookie action or payment flow was used."
  },
  {
    "name": "Dirtybird LabelWorx DemoBox Bass House Demo Route",
    "websiteUrl": "https://dirtybirdrecords.com/",
    "submissionUrl": "https://www.label-worx.com/demo/dirtybird",
    "sourceUrl": "https://dirtybirdrecords.com/",
    "sourceType": "automation_run_286_public_research",
    "country": "United States / global house and bass label with official LabelWorx DemoBox",
    "language": "en",
    "genres": ["dirtybird", "house", "tech-house", "bass-house", "electronic", "label-worx", "demobox", "mp3", "wav", "javascript-required", "rights-grant", "manual-review"],
    "submissionMethod": "official-dirtybird-labelworx-demobox-file-upload-route",
    "feeRequired": false,
    "feeAmount": "No demo-submission fee or payment requirement is stated on the official Dirtybird or LabelWorx demo pages.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "The official LabelWorx DemoBox requires JavaScript, artist and track data, contact details, country, prior-label history, exclusivity status and an MP3 or WAV file. Submission includes rights, data-storage and gratis social/live-stream playback permissions. A human must review the unreleased/exclusive status, master, rights, optional marketing consent, privacy terms and permission language before any upload.",
    "notes": "Verified on 2026-07-11 from Dirtybird's official site and the linked LabelWorx DemoBox. Dirtybird states that every submitted track is heard and the official site links current music, radio and a 2026 Campout event. No direct demo email was exposed or guessed. JavaScript was not enabled for submission, and no form, file, personal data, consent choice, account or payment was supplied."
  },
  {
    "name": "Critical Music 320kbps reCAPTCHA Demo Submission Form",
    "websiteUrl": "https://criticalmusic.com/",
    "submissionUrl": "https://criticalmusic.com/contact/",
    "sourceUrl": "https://criticalmusic.com/contact/",
    "sourceType": "automation_run_286_public_research",
    "country": "United Kingdom / global drum and bass label with native demo contact form",
    "language": "en",
    "genres": ["critical-music", "drum-and-bass", "jungle", "bass-music", "electronic", "320kbps", "native-contact-form", "recaptcha", "manual-review"],
    "submissionMethod": "official-contact-form-demo-submission-dropdown",
    "feeRequired": false,
    "feeAmount": "No demo-submission fee or payment requirement is stated on the official Critical Music contact page.",
    "loginRequired": false,
    "captchaDetected": true,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "Critical Music welcomes demos through the Demo Submission option in its contact form, prefers 320 kbps audio and protects the form with reCAPTCHA. A human must inspect the live fields, prepare the correct audio/link package, confirm rights and label fit, and complete any human verification. The public press and label-management emails must not be used to bypass the authorized demo form.",
    "notes": "Verified on 2026-07-11 from the official contact and homepage pages. The site publicly lists info@criticalmusic.com for press enquiries and badger@criticalmusic.com for label management/operations, while separately directing demos to the reCAPTCHA-protected form. The homepage displays an active release catalogue and event listing. No form, CAPTCHA, email, file or message was used."
  },
  {
    "name": "Shogun Audio LabelRadar Drum and Bass Demo Route",
    "websiteUrl": "https://www.shogunaudio.co.uk/",
    "submissionUrl": "https://www.labelradar.com/labels/shogunaudio/portal",
    "sourceUrl": "https://www.shogunaudio.co.uk/pages/contact",
    "sourceType": "automation_run_286_public_research",
    "country": "United Kingdom / global drum and bass label group and official account-controlled demo portal",
    "language": "en",
    "genres": ["shogun-audio", "drum-and-bass", "liquid-drum-and-bass", "jungle", "bass-music", "labelradar", "label-engine", "account-session-boundary", "manual-review"],
    "submissionMethod": "official-shogun-audio-demo-navigation-to-labelradar-with-legacy-label-engine-reference",
    "feeRequired": false,
    "feeAmount": "Shogun Audio states no mandatory demo fee; current LabelRadar account, credit or plan conditions require manual inspection.",
    "loginRequired": true,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "Shogun Audio's current Demos navigation points to LabelRadar, while its official contact page also publishes a Label Engine demo URL. A human must confirm the current destination, use an owner-controlled account/session, choose the correct label or imprint, review current credit or plan limits, supply rights-cleared metadata and approve the track before submission. General, shop and licensing emails are not substitute demo routes.",
    "notes": "Verified on 2026-07-11 from the official Shogun Audio homepage, contact page and linked LabelRadar portal. The contact page publicly lists info@shogunaudio.co.uk, shop@shogunaudio.co.uk and licensing@shogunaudio.co.uk for their stated business purposes. The site carries a 2026 copyright notice and current release, event and merchandise activity. No account, login, portal action, email, file, cookie choice or payment was used."
  }
];
