import type { PlatformInput } from '../models/types.js';

export const run220BaseSeedPlatforms: PlatformInput[] = [
  {
    name: "WERS Boston Wicked Local Wednesday MP3 Local Artist Form Route",
    websiteUrl: "https://wers.org/",
    submissionUrl: "https://wers.org/wicked-local-wednesday/",
    sourceUrl: "https://wers.org/wicked-local-wednesday/",
    sourceType: "automation_run_220_public_research",
    country: "United States / Boston college radio and local artist feature route",
    language: "en",
    genres: ["college-radio", "local-radio", "boston", "mp3-upload", "form-route", "live-session", "manual-review", "captcha-boundary"],
    submissionMethod: "wers-boston-wicked-local-wednesday-mp3-local-artist-form-route",
    feeRequired: false,
    feeAmount: "Free/manual local-airplay and feature route. Official WERS page exposes a public Wicked Local Wednesday submission form and no payment path was observed.",
    loginRequired: false,
    captchaDetected: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for Boston/local eligibility, public embeddable audio/file choice, MP3 upload, contact details, bio text, phone field and reCAPTCHA/human-verification boundary. No form was submitted and no file was uploaded.",
    notes: "Official WERS page describes Wicked Local Wednesday, asks local bands to fill out the form, exposes artist/band/about/website/location/contact/email/phone/Music Files fields, accepts MP3 up to 39 MB, and the site footer shows 2026 plus reCAPTCHA language."
  },
  {
    name: "WYEP Pittsburgh Link Email Hard Copy Local Airplay Submission Route",
    websiteUrl: "https://www.wyep.org/",
    submissionUrl: "https://www.wyep.org/wyep-pittsburgh-area-music-submissions",
    sourceUrl: "https://www.wyep.org/wyep-pittsburgh-area-music-submissions",
    sourceType: "automation_run_220_public_research",
    country: "United States / Pittsburgh independent public radio local music route",
    language: "en",
    genres: ["public-radio", "local-radio", "pittsburgh", "email-link", "hard-copy", "fcc-clean", "manual-review", "free-first"],
    submissionMethod: "wyep-pittsburgh-link-email-hard-copy-local-airplay-submission-route",
    feeRequired: false,
    feeAmount: "Free/manual local-airplay route. Official WYEP page exposes link/email and hard-copy submission instructions and no payment path was observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for Western Pennsylvania/local fit, public track link or hard-copy package choice, FCC-clean edit, artist bio, suggested album tracks, contact details and editorial airplay expectations. No email was sent and no package was prepared.",
    notes: "Official WYEP page asks artists to email a music link such as SoundCloud, Spotify, YouTube or Dropbox to localmusic@wyep.org or mail hard copy, explains staff voting and 2-4 month programming timelines, and states airplay is not guaranteed."
  },
  {
    name: "Radio Milwaukee WAV Digital Music Submission Route",
    websiteUrl: "https://radiomilwaukee.org/",
    submissionUrl: "https://radiomilwaukee.org/music-submission",
    sourceUrl: "https://radiomilwaukee.org/music-submission",
    sourceType: "automation_run_220_public_research",
    country: "United States / Milwaukee public radio local and new music route",
    language: "en",
    genres: ["public-radio", "local-music", "new-music", "wav", "digital-only", "radio-edit", "manual-review", "free-first"],
    submissionMethod: "radio-milwaukee-wav-digital-music-submission-route",
    feeRequired: false,
    feeAmount: "Free/manual digital music submission route. Official Radio Milwaukee page exposes Submit Music navigation and no payment path was observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for WAV/radio-edit preparation, no-physical-media rule, bio/lyrics/song comments, upcoming album/live show details, helpful links and editorial no-guarantee boundary. No file transfer or message was sent.",
    notes: "Official Radio Milwaukee page says to send uncompressed mixed/mastered audio with WAV preferred, requires radio edits, says no physical media, asks for an informational document with bio, lyrics and links, and confirms the team listens but cannot guarantee airplay or feedback."
  },
  {
    name: "BBC Music Introducing UK UGC Artist Upload Review Route",
    websiteUrl: "https://www.bbc.co.uk/introducing",
    submissionUrl: "https://www.bbc.co.uk/introducing/uploader",
    sourceUrl: "https://www.bbc.co.uk/introducing",
    sourceType: "automation_run_220_public_research",
    country: "United Kingdom / BBC new-music upload platform",
    language: "en",
    genres: ["bbc-introducing", "ugc-upload", "unsigned-artists", "uk-local-radio", "festival-opportunities", "app-boundary", "terms-boundary", "manual-review"],
    submissionMethod: "bbc-music-introducing-uk-ugc-artist-upload-review-route",
    feeRequired: false,
    feeAmount: "Free/manual public broadcaster upload route. Public source material identifies BBC Music Introducing as an active UGC music upload platform; no payment path was observed.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for BBC account/session, UK/local eligibility, postcode routing, UGC terms, original-rights confirmation, audio upload, profile metadata and producer/presenter editorial review. Official BBC pages were not accessed beyond robots boundaries and no login or upload was attempted.",
    notes: "Public source material describes BBC Music Introducing as active, with an upload tool allowing users to upload music directly to Introducing producers/presenters, postcode-based local show routing, national BBC forwarding opportunities and UGC terms."
  },
  {
    name: "NPR Tiny Desk Contest Original Song Video Submission Route",
    websiteUrl: "https://www.npr.org/series/tiny-desk-concerts/",
    submissionUrl: "https://tinydeskcontest.npr.org/",
    sourceUrl: "https://www.npr.org/series/tiny-desk-concerts/",
    sourceType: "automation_run_220_public_research",
    country: "United States / NPR Music national contest and discovery route",
    language: "en",
    genres: ["npr-music", "tiny-desk", "contest", "original-song", "video-submission", "youtube", "timing-window", "manual-review"],
    submissionMethod: "npr-tiny-desk-contest-original-song-video-submission-route",
    feeRequired: false,
    feeAmount: "Free/manual contest route. Public source material says the annual Tiny Desk Contest invites musicians to submit a video of one of their songs; no payment path was observed.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for contest timing/open-window status, original-song eligibility, YouTube/video account/session, desk-performance format, rights, release strategy, application answers and NPR rules. The 2026 winner had already been announced in public coverage, so this remains queued for future manual timing review.",
    notes: "Public source material describes the Tiny Desk Contest as annual, with musicians submitting a video of one of their songs, a jury selecting a winner for a Tiny Desk Concert, continued 2026 activity, and more than 6,000 entries reported for the 2026 cycle."
  }
];
