import type { PlatformInput } from '../models/types.js';

export const run284SeedPlatforms: PlatformInput[] = [
  {
    "name": "High Tea Music Drum and Bass Official Fillout Demo Form",
    "websiteUrl": "https://highteamusic.nl/",
    "submissionUrl": "https://highteamusic.fillout.com/demo-form",
    "sourceUrl": "https://highteamusic.nl/contact/",
    "sourceType": "automation_run_284_public_research",
    "country": "Netherlands / European drum-and-bass label official external demo-form route",
    "language": "en",
    "genres": ["high-tea-music", "drum-and-bass", "liquid-dnb", "dancefloor-dnb", "electronic", "bass-music", "fillout-form", "cookie-consent-boundary", "manual-review"],
    "submissionMethod": "official-public-label-demo-form-linked-from-official-contact-page",
    "feeRequired": false,
    "feeAmount": "No mandatory demo-submission fee is stated on the official High Tea Music contact page.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "High Tea Music directs all label demos to a third-party Fillout form. A human must inspect the live form fields, file or link requirements, rights declarations, privacy terms, cookie choices and any runtime verification before entering artist data or music. Do not send demos to the public label or general email addresses as a substitute for the authorized form.",
    "notes": "The official contact page was verified on 2026-07-11 and links the dedicated demo form. It publicly lists releases@highteamusic.nl for label business and contact@highteamusic.nl for other enquiries, but explicitly routes demos through the form. The releases page lists multiple 2026 releases. No form, file, email, cookie choice or payment action was completed."
  },
  {
    "name": "Liquicity Records Drum and Bass Label Engine Demo Upload Route",
    "websiteUrl": "https://liquicity.com/",
    "submissionUrl": "https://liquicityrecords.label-engine.com/demos?embed=1",
    "sourceUrl": "https://liquicity.com/demo/",
    "sourceType": "automation_run_284_public_research",
    "country": "Netherlands / global drum-and-bass label official Label Engine demo-upload route",
    "language": "en",
    "genres": ["liquicity", "drum-and-bass", "liquid-dnb", "electronic", "bass-music", "label-engine", "mp3-upload", "manual-review"],
    "submissionMethod": "official-public-label-engine-demo-form-with-up-to-five-mp3-track-uploads",
    "feeRequired": false,
    "feeAmount": "No demo-submission fee is stated on the official Liquicity demo page or the rendered Label Engine form.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "Liquicity directs all music submissions to a Label Engine form that requests artist and real names, email confirmation, up to five MP3 tracks, track titles, optional social profiles and a message. A human must select the final tracks, confirm metadata, rights, file quality, privacy implications and any runtime challenge before upload. Do not use Liquicity's general contact form for demos.",
    "notes": "The official Liquicity demo page and embedded Label Engine workflow were verified on 2026-07-11. Liquicity states that every submitted track is listened to but a response is not guaranteed. The official site lists current 2026 events and active releases. No files, form fields, social identifiers or messages were submitted."
  },
  {
    "name": "Circus Records and Circus Electric LabelRadar Bass Music Demo Route",
    "websiteUrl": "https://www.circus-records.co.uk/",
    "submissionUrl": "https://www.labelradar.com/labels/circusrecords/profile",
    "sourceUrl": "https://www.circus-records.co.uk/about/",
    "sourceType": "automation_run_284_public_research",
    "country": "United Kingdom / global bass-music label official LabelRadar demo route",
    "language": "en",
    "genres": ["circus-records", "circus-electric", "dubstep", "bass-music", "melodic-bass", "electronic", "labelradar", "account-session-boundary", "manual-review"],
    "submissionMethod": "official-public-labelradar-demo-route-for-circus-records-and-circus-electric",
    "feeRequired": false,
    "feeAmount": "Circus Records states that demos are accepted only through LabelRadar and does not state a mandatory label submission fee; any LabelRadar account or credit conditions require manual inspection.",
    "loginRequired": true,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "Circus Records accepts demos only through its external LabelRadar route. The portal is dynamically rendered and requires an owner-controlled LabelRadar account or session before submission. A human must select the correct Circus label, review any credit or plan boundary, verify rights and metadata, and approve the track upload. Do not email demos to info@circus-records.co.uk.",
    "notes": "The official Circus Records site was verified on 2026-07-11. Its about page publishes info@circus-records.co.uk for questions, explicitly says demos are accepted via LabelRadar only, and describes Circus Records, Circus Electric and DPMO as active bass-music imprints. The homepage displays current latest releases. No login, portal action, file upload, email or payment was performed."
  },
  {
    "name": "Monstercat Uncaged Instinct and Silk Official LabelRadar Demo Portals",
    "websiteUrl": "https://www.monstercat.com/",
    "submissionUrl": "https://www.labelradar.com/labels/monstercat/portal",
    "sourceUrl": "https://www.monstercat.com/contact-us",
    "sourceType": "automation_run_284_public_research",
    "country": "Canada and United States / global electronic label official multi-imprint LabelRadar demo route",
    "language": "en",
    "genres": ["monstercat", "uncaged", "instinct", "silk", "dubstep", "bass-music", "future-bass", "house", "progressive", "electronic", "labelradar", "account-session-boundary", "cookie-consent-boundary", "manual-review"],
    "submissionMethod": "official-public-labelradar-demo-portals-for-uncaged-instinct-and-silk",
    "feeRequired": false,
    "feeAmount": "Monstercat does not state a mandatory label fee for its demo portals; any LabelRadar account, credit or plan conditions require manual inspection.",
    "loginRequired": true,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "Monstercat links separate LabelRadar demo portals for Uncaged, Instinct and Silk. The artist must manually choose the correct imprint and use an owner-controlled LabelRadar account or session. A human must inspect any credits, terms, rights declarations, cookies, runtime controls and upload requirements. Do not repurpose Monstercat's support, press, event or general contact form for demos.",
    "notes": "The official Monstercat contact page was verified on 2026-07-11 and states that every submitted demo is listened to, linking the three imprint portals. Public support, press and event contacts are displayed in protected form and were not decoded. The homepage lists releases dated July 3 and July 10, 2026. No cookie choice, account, login, portal submission, upload or payment was completed."
  },
  {
    "name": "NCS NoCopyrightSounds Official LabelRadar Electronic Demo Submission Route",
    "websiteUrl": "https://ncs.io/",
    "submissionUrl": "https://www.labelradar.com/labels/ncs/portal",
    "sourceUrl": "https://ncs.io/contact",
    "sourceType": "automation_run_284_public_research",
    "country": "United Kingdom / global electronic-music label official LabelRadar demo route",
    "language": "en",
    "genres": ["ncs", "nocopyrightsounds", "electronic", "dubstep", "drum-and-bass", "future-bass", "house", "melodic-dubstep", "labelradar", "account-session-boundary", "manual-review"],
    "submissionMethod": "official-public-labelradar-demo-submission-route-linked-from-ncs-contact-page",
    "feeRequired": false,
    "feeAmount": "NCS does not state a mandatory label submission fee on its official contact page; any LabelRadar account, credit or plan conditions require manual inspection.",
    "loginRequired": true,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "NCS routes demo submissions to a dynamic LabelRadar portal. Submission requires an owner-controlled account or session and human review of the platform's current credits, terms, rights declarations, metadata and upload controls. Do not use the separate claims, licensing or general-enquiry routes for music demos.",
    "notes": "The official NCS contact page was verified on 2026-07-11 and links LabelRadar specifically for demo submissions. The public music library shows active recent releases across electronic genres, including drum and bass and melodic dubstep. No account, login, form, file upload, licence request, payment or general enquiry was initiated."
  }
];
