import type { PlatformInput } from '../models/types.js';

export const run289SeedPlatforms: PlatformInput[] = [
  {
    "name": "STMPD RCRDS Official SoundCloud Login Demo Drop Route",
    "websiteUrl": "https://stmpdrcrds.com/",
    "submissionUrl": "https://demo.stmpdrcrds.com/",
    "sourceUrl": "https://demo.stmpdrcrds.com/",
    "sourceType": "automation_run_289_public_research",
    "country": "Netherlands / Amsterdam global electronic label",
    "language": "en",
    "genres": ["stmpd-rcrds", "electronic", "progressive-house", "bass-house", "future-bass", "trap", "downtempo", "soundcloud-oauth", "login-required", "manual-review"],
    "submissionMethod": "official-stmpd-rcrds-soundcloud-connected-demo-drop",
    "feeRequired": false,
    "feeAmount": "No demo-submission fee is stated on the official STMPD RCRDS demo portal.",
    "loginRequired": true,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "STMPD RCRDS links its official Demo Drop from the label homepage. The portal accepts original demo tracks only, explicitly excludes remixes and bootlegs, and requires connecting and logging in with SoundCloud under the portal terms and privacy policy. A human must approve account authorization, track ownership, original-work status, private-link permissions, metadata and all live declarations before submission.",
    "notes": "Verified on 2026-07-11 from the official STMPD RCRDS homepage and linked demo portal. The homepage lists releases dated 2026-07-03 and other current catalogue entries. No SoundCloud login or authorization was used, no track was connected or submitted, no cookie choice was made and no payment or anti-bot control was handled. No demo email was guessed or substituted for the authorized portal."
  },
  {
    "name": "Selected Base Native Unreleased Streamable-Link Demo Drop Route",
    "websiteUrl": "https://selectedbase.com/",
    "submissionUrl": "https://selectedbase.com/submit",
    "sourceUrl": "https://selectedbase.com/submit",
    "sourceType": "automation_run_289_public_research",
    "country": "Germany / Berlin and Munich global house label, blog and event brand",
    "language": "en",
    "genres": ["selected-base", "house", "deep-house", "dance", "electronic", "unreleased-music", "streamable-links", "native-form", "public-demo-email", "manual-review"],
    "submissionMethod": "official-selected-base-native-demo-form-with-streamable-unreleased-link",
    "feeRequired": false,
    "feeAmount": "No submission fee or payment requirement is stated on Selected Base's official Demo Drop page.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "Selected Base states that it is constantly looking for new music to sign and accepts only streamable links to unreleased tracks, preferably via SoundCloud, YouTube, Dropbox or Google Drive. Its official imprint also publishes inbox@selectedbase.com specifically for demos. A human must choose the authorized form or published demo mailbox, verify unreleased and rights status, review link accessibility and privacy, complete all live fields and avoid follow-up chasing after submission.",
    "notes": "Verified on 2026-07-11 from Selected Base's official homepage, Demo Drop and legal imprint. The site describes Selected as a house-focused music blog, record label and event brand and displays current releases. The imprint identifies Selected Base GmbH and publicly lists inbox@selectedbase.com for demos, licensing@selectedbase.com for business inquiries, booking@selectedbase.com for events and info@selectedbase.com for other matters. These addresses were verified only as published on the official domain; no SMTP/MX probing or email was performed. No form was submitted, no link supplied and no cookie preference was accepted."
  },
  {
    "name": "Future House Music Official Discord Demo Drop Route",
    "websiteUrl": "https://futurehousemusic.com/",
    "submissionUrl": "https://discord.gg/futurehousemusic",
    "sourceUrl": "https://futurehousemusic.com/contact/",
    "sourceType": "automation_run_289_public_research",
    "country": "Netherlands / global future-house and electronic label community",
    "language": "en",
    "genres": ["future-house-music", "future-house", "house", "electronic", "discord", "community-demo-drop", "login-required", "cookie-boundary", "manual-review"],
    "submissionMethod": "official-future-house-music-discord-demo-drop",
    "feeRequired": false,
    "feeAmount": "No mandatory demo-submission fee is stated on Future House Music's official website for the linked Discord demodrop.",
    "loginRequired": true,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "Future House Music explicitly directs artists from its official site and contact page to a Discord demodrop and describes recurring demo drops and feedback events in its community. Discord membership, login, channel rules, posting permissions, rights, track format and any live moderation requirements must be reviewed by a person. The adjacent general contact form is not a substitute for the designated demo route.",
    "notes": "Verified on 2026-07-11 from the official Future House Music homepage and contact page. The site presents a current release, active community events and a dedicated Submit Demo link to Discord. No Discord account, invite acceptance or channel access was used, no contact form was sent, no cookie choice was accepted and no track or link was posted. No business email was guessed from staff or domain patterns."
  },
  {
    "name": "Spinnin Records Account-Gated Talent Pool Demo Upload Route",
    "websiteUrl": "https://spinninrecords.com/",
    "submissionUrl": "https://spinninrecords.com/talentpool/",
    "sourceUrl": "https://spinninrecords.com/contact",
    "sourceType": "automation_run_289_public_research",
    "country": "Netherlands / Amsterdam global dance and electronic label",
    "language": "en",
    "genres": ["spinnin-records", "dance", "house", "electronic", "edm", "talent-pool", "account-required", "public-ranking", "manual-review"],
    "submissionMethod": "official-spinnin-records-account-gated-talent-pool-upload",
    "feeRequired": false,
    "feeAmount": "No mandatory upload fee is stated on the public Talent Pool landing page; account registration is required before upload.",
    "loginRequired": true,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "Spinnin' Records explicitly directs new talent to upload tracks through its Talent Pool and requires creating or logging into an account before a demo can be submitted. The public pool displays ranked and newly added tracks. A human must review account terms, public-visibility implications, upload format, rights, master and metadata, any contest or voting conditions and all live consent fields before using the service.",
    "notes": "Verified on 2026-07-11 from the official Talent Pool and contact pages. The contact page states that artists should upload tracks to the Talent Pool, and the platform carries a 2026 copyright notice with current releases and active pool additions. No account was created or accessed, no upload or vote occurred, no cookie setting was changed and no payment or CAPTCHA workflow was handled. No email was inferred as an alternative demo route."
  },
  {
    "name": "Dim Mak Official Dynamic Demo Submission Page Route",
    "websiteUrl": "https://www.dimmak.com/",
    "submissionUrl": "https://www.dimmak.com/demos",
    "sourceUrl": "https://www.dimmak.com/demos",
    "sourceType": "automation_run_289_public_research",
    "country": "United States / Los Angeles global electronic label",
    "language": "en",
    "genres": ["dim-mak", "electronic", "dance", "bass", "house", "new-noise", "official-demo-page", "dynamic-form", "manual-review"],
    "submissionMethod": "official-dim-mak-dynamic-demo-submission-page",
    "feeRequired": false,
    "feeAmount": "No demo fee or payment requirement is stated on the public Dim Mak demo page.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "Dim Mak exposes a dedicated Send Demos destination from its official navigation, but the statically accessible page does not expose the complete live form, upload or link requirements, declarations, consent language, limits or runtime verification state. A human must inspect the rendered demo workflow, confirm label fit, ownership, master status, metadata and all terms before entering data or delivering audio.",
    "notes": "Verified on 2026-07-11 from the official Dim Mak homepage, demos page and contact page. The site identifies Dim Mak as an independent Los Angeles label founded in 1996, displays current music and carries a 2026 copyright notice. General, licensing, sync and publicity contact categories are kept separate from the designated demo route. No form was rendered or submitted, no file or link was supplied, no account or cookie action was used and no CAPTCHA, payment or contact-guessing occurred."
  }
];
