import type { PlatformInput } from '../models/types.js';

export const run222SeedPlatforms: PlatformInput[] = [
  {
    name: "UnitedMasters Debut Select Distribution Brand Sync Route",
    websiteUrl: "https://www.unitedmasters.com/",
    submissionUrl: "https://www.unitedmasters.com/",
    sourceUrl: "https://www.unitedmasters.com/",
    sourceType: "automation_run_222_public_research",
    country: "United States / global independent artist distribution",
    language: "en",
    genres: ["digital-distribution", "artist-upload", "brand-sync", "playlist-pitching", "radio-pitching", "login-boundary", "pricing-boundary", "freemium"],
    submissionMethod: "unitedmasters-debut-select-distribution-brand-sync-route",
    feeRequired: true,
    feeAmount: "Freemium/paid manual route. Official page shows free social distribution language plus DEBUT+ at $19.99/year, SELECT at $59.99/year and PARTNER by invitation; release approval, royalty wallet and plan boundaries are owner-controlled.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for UnitedMasters account creation, artist profile, plan selection, release upload, metadata, artwork, collaborators/splits, brand/sync eligibility, playlist/radio pitching, wallet/payout setup, copyright notices and approval timing. No form was submitted, no account was created and no audio/artwork/file was uploaded.",
    notes: "Official UnitedMasters page exposes Log In, Sign Up and Start Your Journey routes; it says artists can release to 150+ music services, upload music files/metadata/artwork, review and submit for approval, access brand/sync deals, playlist/editorial/radio pitching, and current 2026 plan pricing."
  },
  {
    name: "LANDR Studio Distribution Mastering Promotion Artist Upload Route",
    websiteUrl: "https://www.landr.com/",
    submissionUrl: "https://www.landr.com/",
    sourceUrl: "https://www.landr.com/",
    sourceType: "automation_run_222_public_research",
    country: "Canada / global music creation and distribution platform",
    language: "en",
    genres: ["digital-distribution", "artist-upload", "mastering", "music-promotion", "collaboration", "login-boundary", "pricing-boundary", "freemium"],
    submissionMethod: "landr-studio-distribution-mastering-promotion-artist-upload-route",
    feeRequired: true,
    feeAmount: "Freemium/paid manual route. Official page exposes Sign up free and Log in, with LANDR Studio starting at USD $8.25/month and unlimited distribution to 150+ platforms.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for sign-up/session, plan/subscription choice, distribution setup, mastering/export decisions, audio upload, metadata, store selection, royalty retention, promotion services, collaboration/network data and legal terms. No form was submitted, no account was created and no audio/artwork/file was uploaded.",
    notes: "Official LANDR page shows Distribution, Pricing, Log in and Sign up free routes; it advertises unlimited AI mastering, unlimited distribution to 150+ streaming platforms, 100% royalties, promotion/collaboration tooling and 2026 copyright footer."
  },
  {
    name: "Symphonic Starter Partner Distribution Playlist Pitching Route",
    websiteUrl: "https://symphonic.com/",
    submissionUrl: "https://symphonic.com/",
    sourceUrl: "https://symphonic.com/",
    sourceType: "automation_run_222_public_research",
    country: "United States / global independent artist and label distribution",
    language: "en",
    genres: ["digital-distribution", "artist-upload", "playlist-pitching", "music-promotion", "rights-management", "sync-licensing", "login-boundary", "pricing-boundary"],
    submissionMethod: "symphonic-starter-partner-distribution-playlist-pitching-route",
    feeRequired: true,
    feeAmount: "Paid/manual route. Official page lists Starter at $29.99/year and Partner as a custom royalty percentage / by-approval path for established artists, labels and managers.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for Start Now/Join route, account/session, Starter versus Partner eligibility, payment or royalty-percentage terms, release upload, metadata, royalties/splits, DSP delivery, playlist pitching, marketing, rights management and sync/licensing boundaries. No form was submitted, no account was created and no audio/artwork/file was uploaded.",
    notes: "Official Symphonic page exposes Login, Join, Starter, Partner and Pricing routes; it says creators can distribute to 200+ DSPs, monetize Spotify/TikTok/YouTube, use SplitShare, access marketing/promotion, and get DSP playlist pitching on Partner."
  },
  {
    name: "EmuBands One Time Premium Distribution Playlist Pitching Route",
    websiteUrl: "https://www.emubands.com/",
    submissionUrl: "https://www.emubands.com/",
    sourceUrl: "https://www.emubands.com/",
    sourceType: "automation_run_222_public_research",
    country: "United Kingdom / global digital distribution",
    language: "en",
    genres: ["digital-distribution", "artist-upload", "playlist-pitching", "pre-save", "royalty-splits", "login-boundary", "pricing-boundary", "paid-manual"],
    submissionMethod: "emubands-one-time-premium-distribution-playlist-pitching-route",
    feeRequired: true,
    feeAmount: "Paid/manual route. Official page says artists can use one-time fees per release or Premium for unlimited distribution; exact plan choice is owner-controlled.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for Login/Sign Up, one-time release fee versus Premium subscription, release setup, platform selection, rights and copyright control, playlist pitching, pre-save links, royalty splitting, payout settings and support terms. No form was submitted, no account was created and no audio/artwork/file was uploaded.",
    notes: "Official EmuBands page exposes Login / Sign Up, Get Started and Pricing routes; it says artists and labels can distribute to Spotify, Apple Music, Amazon Music and other retailers, keep 100% royalties, use one-time fees or Premium, and shows January/March/April 2026 news activity."
  },
  {
    name: "Ditto Music Unlimited Distribution Playlist Sync Pitching Route",
    websiteUrl: "https://dittomusic.com/",
    submissionUrl: "https://dittomusic.com/en",
    sourceUrl: "https://dittomusic.com/en",
    sourceType: "automation_run_222_public_research",
    country: "United Kingdom / global independent artist distribution",
    language: "en",
    genres: ["digital-distribution", "artist-upload", "playlist-pitching", "sync-licensing", "publishing", "music-promotion", "login-boundary", "pricing-boundary", "freemium"],
    submissionMethod: "ditto-music-unlimited-distribution-playlist-sync-pitching-route",
    feeRequired: true,
    feeAmount: "Freemium/paid manual route. Official page exposes free account creation / try for free plus paid plans, including Starter at $19/year, Pro at $59/year and Labels from $109/year.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for sign-up/login, paid plan selection, unlimited release setup, audio/video upload, metadata, platform choice, playlist submission, sync and publishing opt-ins, YouTube Content ID, royalty splits, app access and terms. No form was submitted, no account was created and no audio/artwork/file was uploaded.",
    notes: "Official Ditto page exposes Login, Try For Free, sign-up form and Start releasing routes; it advertises unlimited releases to 150+ platforms, 100% royalties, playlist pitching, sync licensing, publishing, YouTube Content ID, 2026 artist reviews and 2026 updates."
  }
];
