import type { PlatformInput } from '../models/types.js';

export const run204SeedPlatforms: PlatformInput[] = [
  {
    name: "Audiomack Creator App Free Unlimited Upload Route",
    websiteUrl: "https://audiomack.com/",
    submissionUrl: "https://creators.audiomack.com/upload",
    sourceUrl: "https://creators.audiomack.com/creator-app",
    sourceType: "automation_run_204_public_research",
    country: "Global / United States-based music streaming and creator upload platform",
    language: "en",
    genres: ["music-platform", "artist-upload", "audiomack", "hip-hop", "afrobeats", "r-and-b", "reggae", "electronic", "creator-app", "manual-review"],
    submissionMethod: "official-audiomack-creator-app-free-unlimited-upload-route",
    feeRequired: false,
    feeAmount: "Free-first/manual creator-upload route. Official Audiomack pages state artists and creators can upload limitless music through the website/mobile apps and that Creator App uploads are free; no upload fee was observed.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for account/login boundary, JavaScript upload boundary, rights ownership, release metadata, artwork/audio preparation, monetization terms and platform policy fit. No account was created and no upload was attempted.",
    notes: "Audiomack was verified through official 2026 pages showing Sign Up/Sign In, Upload, Creator App, unlimited uploads, statistics, fan interaction and business-inquiry/support links."
  },
  {
    name: "Bandcamp Artist Direct To Fan Store Upload Route",
    websiteUrl: "https://bandcamp.com/",
    submissionUrl: "https://bandcamp.com/artists?from=footer",
    sourceUrl: "https://bandcamp.com/artists?from=footer",
    sourceType: "automation_run_204_public_research",
    country: "Global / direct-to-fan artist store and music marketplace route",
    language: "en",
    genres: ["music-platform", "direct-to-fan", "artist-store", "digital-albums", "merch", "electronic", "reggae", "world", "dub", "manual-review"],
    submissionMethod: "official-bandcamp-artist-direct-to-fan-store-upload-route",
    feeRequired: false,
    feeAmount: "Free-first/freemium/manual artist-account route. Official Bandcamp for Artists page says artist accounts are free, with revenue share on digital/merch sales and optional Bandcamp Pro.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for desktop sign-up boundary, pricing/revenue-share terms, payout setup, rights and AI-content policy, release/artwork/metadata preparation, storefront positioning and optional Pro/private-streaming decisions. No account, upload, sale setup or payment workflow was started.",
    notes: "Bandcamp was verified through official 2026 homepage and Bandcamp for Artists page showing artist accounts, direct-to-fan store, free account pricing, revenue-share terms, direct fan communication, editorial/discovery surfaces and sign-up boundary."
  },
  {
    name: "Hearthis.at Free Weekly Upload Artist Profile Route",
    websiteUrl: "https://hearthis.at/",
    submissionUrl: "https://hearthis.at/",
    sourceUrl: "https://hearthis.at/",
    sourceType: "automation_run_204_public_research",
    country: "Global / Germany-based audio sharing, DJ set and artist upload platform",
    language: "en",
    genres: ["music-platform", "artist-upload", "hearthis", "dj-sets", "electronic", "dubstep", "reggae", "dancehall", "world", "manual-review"],
    submissionMethod: "official-hearthis-free-weekly-upload-artist-profile-route",
    feeRequired: false,
    feeAmount: "Free-first/freemium/manual route. Official hearthis.at page says users can create an account for free and upload up to 400 MB of music each week, with optional paid/unlimited features observed.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for account creation, login/session boundary, upload quota, file-format and quality choices, genre tagging, rights/copyright compliance, optional paid features and public profile positioning. No login, upload or subscription action was taken.",
    notes: "hearthis.at was verified through the official 2026 homepage showing Upload, account creation, weekly free upload allowance, genre taxonomy including dubstep, reggae, hip-hop, world and electronic, and optional unlimited/fan subscription features."
  },
  {
    name: "SoundCloud Artist Upload Next Pro Discovery Route",
    websiteUrl: "https://soundcloud.com/",
    submissionUrl: "https://soundcloud.com/upload",
    sourceUrl: "https://soundcloud.com/",
    sourceType: "automation_run_204_public_research",
    country: "Global / Germany-based audio sharing, artist upload and discovery platform",
    language: "en",
    genres: ["music-platform", "soundcloud", "artist-upload", "audio-sharing", "electronic", "dubstep", "reggae", "hip-hop", "social-discovery", "manual-review"],
    submissionMethod: "official-soundcloud-artist-upload-next-pro-discovery-route",
    feeRequired: false,
    feeAmount: "Free-first/freemium/manual route. Public platform information identifies SoundCloud as an upload/promote/share audio platform with free and paid creator tiers; Next Pro paid features and JavaScript/login boundaries were observed.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for JavaScript browser boundary, account/login requirement, track rights, profile setup, upload limits or paid Next Pro choices, metadata/artwork, AI/no-scraping policy review and public/private release positioning. No account or upload action was taken.",
    notes: "SoundCloud was verified through the official site boundary plus public source validation showing global availability, upload/promote/share audio use, optional paid creator services and recent AI/artist-control policy context."
  },
  {
    name: "BandLab Creator Social Upload Collaboration Distribution Route",
    websiteUrl: "https://www.bandlab.com/",
    submissionUrl: "https://www.bandlab.com/",
    sourceUrl: "https://www.bandlab.com/",
    sourceType: "automation_run_204_public_research",
    country: "Global / Singapore-based music creation, social upload and distribution ecosystem",
    language: "en",
    genres: ["music-platform", "bandlab", "creator-upload", "collaboration", "distribution", "electronic", "pop", "hip-hop", "independent-artists", "manual-review"],
    submissionMethod: "official-bandlab-creator-social-upload-collaboration-distribution-route",
    feeRequired: false,
    feeAmount: "Free-first/freemium/manual creator route. Public source validation identifies BandLab as a freemium cloud DAW/social music platform with sharing and distribution functions; premium tiers and platform restrictions require owner review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for account/login boundary, upload/share/distribution eligibility, rights ownership, collaborator permissions, AI/tool usage disclosures, metadata, platform terms and optional premium features. No account, upload or distribution action was taken.",
    notes: "BandLab was verified through official site discovery and public source validation describing an active global creator platform with music creation, sharing, social functions and distribution-related features."
  }
];
