import type { PlatformInput } from '../models/types.js';

export const run285SeedPlatforms: PlatformInput[] = [
  {
    "name": "Enhanced Music Official Demmo Electronic Demo Upload Route",
    "websiteUrl": "https://www.enhancedmusic.com/",
    "submissionUrl": "https://labels.demmo.link/enhanced-music/demos",
    "sourceUrl": "https://www.enhancedmusic.com/",
    "sourceType": "automation_run_285_public_research",
    "country": "United Kingdom / global electronic label group and official Demmo demo-upload route",
    "language": "en",
    "genres": ["enhanced-music", "progressive-house", "trance", "melodic-house", "edm", "electronic", "demmo", "dynamic-upload", "manual-review"],
    "submissionMethod": "official-public-demmo-demo-upload-link-published-by-enhanced-music",
    "feeRequired": false,
    "feeAmount": "No mandatory demo-submission fee is stated on the official Enhanced Music page.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "Enhanced Music links to a dynamically rendered third-party Demmo upload workflow. A human must inspect the live fields, supported audio or link format, file limits, metadata, rights declarations, privacy terms and any runtime login, CAPTCHA or payment boundary before supplying artist data or music. Do not send demos to info@enhancedmusic.com as a substitute for the authorized portal.",
    "notes": "Verified on 2026-07-11 from the official Enhanced Music site, which publishes info@enhancedmusic.com as a business contact and separately directs demos to Demmo. The site posted label news on 2026-07-03 and lists an Enhanced Sessions event dated 2026-05-15. No portal fields, files, email, cookie choice or payment workflow were used."
  },
  {
    "name": "Heldeep Records OH2 and HILOMATIK LabelRadar MP3 Demo Route",
    "websiteUrl": "https://heldeeprecords.com/",
    "submissionUrl": "https://www.labelradar.com/labels/heldeeprecords/portal",
    "sourceUrl": "https://heldeeprecords.com/",
    "sourceType": "automation_run_285_public_research",
    "country": "Netherlands / global electronic label family and official LabelRadar demo route",
    "language": "en",
    "genres": ["heldeep-records", "oh2-records", "hilomatik", "house", "future-house", "tech-house", "electronic", "labelradar", "mp3-upload", "account-session-boundary", "manual-review"],
    "submissionMethod": "official-public-labelradar-mp3-demo-route-for-heldeep-oh2-and-hilomatik",
    "feeRequired": false,
    "feeAmount": "Heldeep states that its labels use LabelRadar and does not state a mandatory label fee; current LabelRadar account, credit or plan conditions require manual inspection.",
    "loginRequired": true,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "The official Heldeep page routes Heldeep Records, OH2 Records and HILOMATIK demos to LabelRadar for MP3 delivery. An owner-controlled account or session, correct imprint choice, track ownership, metadata, current credits or plan limits, terms and any runtime challenge require human approval. Do not email demos to the public label-management address unless the label explicitly instructs this.",
    "notes": "Verified on 2026-07-11. The official site publishes team@heldeeprecords.com for label management, not as the demo route, and lists releases dated 2026-07-06, 2026-06-22, 2026-06-15 and 2026-06-01. No LabelRadar account, login, upload, email, cookie action or payment was used."
  },
  {
    "name": "Bassrush Records Official Insomniac Music Group Demo Form",
    "websiteUrl": "https://www.bassrush.com/",
    "submissionUrl": "https://www.insomniacmusicgroup.com/label/bassrush-records/",
    "sourceUrl": "https://www.insomniacmusicgroup.com/label/bassrush-records/",
    "sourceType": "automation_run_285_public_research",
    "country": "United States / global bass-music label and official Insomniac Music Group demo form",
    "language": "en",
    "genres": ["bassrush-records", "dubstep", "drum-and-bass", "riddim", "bass-music", "electronic", "native-demo-form", "dynamic-form", "manual-review"],
    "submissionMethod": "official-label-specific-demo-tab-and-contact-form-on-insomniac-music-group",
    "feeRequired": false,
    "feeAmount": "No mandatory demo fee or payment requirement is stated on the public Bassrush Records label page.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "The official Bassrush Records page exposes a label-specific demos tab in a dynamically rendered contact workflow. A human must verify the live demo tab, required fields, whether a private streaming or download link is expected, label fit, rights, metadata, privacy terms and any runtime challenge before sending. The separate Bassrush general contact form uses reCAPTCHA and is not an authorized substitute music route.",
    "notes": "Verified on 2026-07-11 through Bassrush's official Records link and the Insomniac Music Group label page. The label page exposes demos alongside separate General and Licensing tabs and carries a 2026 copyright notice; Bassrush's public site displays a current bass-music track roster. No form, reCAPTCHA, cookie setting, email, file or link was submitted."
  },
  {
    "name": "Insomniac Records Official Music Group Demo Form",
    "websiteUrl": "https://www.insomniacmusicgroup.com/",
    "submissionUrl": "https://www.insomniacmusicgroup.com/label/insomniac-records/",
    "sourceUrl": "https://www.insomniacmusicgroup.com/label/insomniac-records/",
    "sourceType": "automation_run_285_public_research",
    "country": "United States / global electronic label and official Insomniac Music Group demo form",
    "language": "en",
    "genres": ["insomniac-records", "house", "bass-music", "edm", "electronic", "dance", "native-demo-form", "dynamic-form", "manual-review"],
    "submissionMethod": "official-label-specific-demo-tab-and-contact-form-on-insomniac-music-group",
    "feeRequired": false,
    "feeAmount": "No mandatory demo fee or payment requirement is stated on the public Insomniac Records label page.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "The official Insomniac Records page includes a dynamically rendered demos tab with contact fields, but the static page does not expose complete delivery, attachment, link or rights instructions. A human must select the demos context, inspect all live fields and terms, confirm label fit and approve the final private link and metadata before sending.",
    "notes": "Verified on 2026-07-11 on the official Insomniac Music Group label page. The page presents a live release catalogue, separate General, Licensing and demos contexts, privacy and terms links, and a 2026 copyright notice. No public business email was exposed or guessed, and no form, cookie setting, file, track link or message was submitted."
  },
  {
    "name": "Defected Records Official WAV Streamable-Link Demo Email Route",
    "websiteUrl": "https://defected.com/",
    "submissionUrl": "https://defected.com/demos",
    "sourceUrl": "https://defected.com/demos",
    "sourceType": "automation_run_285_public_research",
    "country": "United Kingdom / global house label and official demo-email instructions",
    "language": "en",
    "genres": ["defected-records", "house", "deep-house", "tech-house", "dance", "electronic", "wav", "streamable-link", "protected-email-link", "cookie-consent-boundary", "manual-review"],
    "submissionMethod": "official-protected-demo-email-link-with-streamable-wav-link-guidelines",
    "feeRequired": false,
    "feeAmount": "No demo-submission fee is stated on Defected's official demo-guidelines page.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "Defected authorizes demo delivery through the protected email link on its official page and requires a streamable SoundCloud, Dropbox or WeTransfer link to WAV audio only, with no artwork or extra promotional materials. A human must open the official link, verify the destination without decoding or guessing it, choose the correct WAV and access settings, confirm rights and comply exactly with the minimal package rules. The page also presents a cookie-consent boundary.",
    "notes": "Verified on 2026-07-11. The official demo page warns that non-compliant submissions are automatically deleted. The protected demo address was not decoded or copied from non-official sources. Current activity includes Defected releases dated 2026-07-10, news dated 2026-07-07 and scheduled 2026 events. No cookie choice, email, file, transfer link or message was sent."
  }
];
