import type { PlatformInput } from '../models/types.js';

export const run229BaseSeedPlatforms: PlatformInput[] = [
  {
    name: "KVRX Austin Physical Digital Music Director Airplay Route",
    websiteUrl: "https://www.kvrx.org/",
    submissionUrl: "https://www.kvrx.org/app/contact/",
    sourceUrl: "https://www.kvrx.org/app/contact/",
    sourceType: "automation_run_229_public_research",
    country: "United States / Austin, Texas student-run college radio",
    language: "en",
    genres: ["college-radio", "student-radio", "radio-airplay", "music-director-email", "physical-submission", "digital-submission", "free-first", "ai-music-exclusion", "manual-review"],
    submissionMethod: "kvrx-austin-physical-digital-music-director-airplay-route",
    feeRequired: false,
    feeAmount: "Free manual physical/digital route. Official KVRX contact guidance lists music@kvrx.org for music submissions and does not list a submission payment requirement.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for outbound email or physical delivery, track/package selection, FCC-clean suitability, AI-assisted/generated exclusion, download/attachment handling and station fit. No email was sent and no files or packages were transferred.",
    notes: "Official KVRX Contact page says to send all music submissions for airplay consideration to music@kvrx.org, notes AI-assisted/generated submissions will not be considered, and states the station is currently taking both physical and digital submissions. The active homepage shows KVRX as student-run radio broadcasting underground music, live shows and local discoveries around the clock."
  },
  {
    name: "KCSB Santa Barbara New Releases Music Director All Formats Route",
    websiteUrl: "https://www.kcsb.org/",
    submissionUrl: "https://www.kcsb.org/contact/",
    sourceUrl: "https://www.kcsb.org/contact/",
    sourceType: "automation_run_229_public_research",
    country: "United States / Santa Barbara, California independent community-college radio",
    language: "en",
    genres: ["college-radio", "community-radio", "radio-airplay", "music-director-email", "new-releases", "demos", "all-formats", "physical-submission", "free-first", "manual-review"],
    submissionMethod: "kcsb-santa-barbara-new-releases-music-director-all-formats-route",
    feeRequired: false,
    feeAmount: "Free manual music-director route. Official KCSB contact guidance asks for new releases and demos and does not list a submission payment requirement.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for contacting the music director, release/demo selection, all-format delivery choice, physical package preparation, metadata and college-radio fit. No email was sent and no package was prepared.",
    notes: "Official KCSB Contact page identifies the music director, says the music director reviews music sent to the station and corresponds with music industry representatives, labels and artists, and asks submitters to send new releases and demos in all formats to the attention of the music director. The site shows 2026 blog/review activity and current live-programming information."
  },
  {
    name: "WKDU Philadelphia Music Submission Public Contact Form Route",
    websiteUrl: "https://wkdu.org/",
    submissionUrl: "https://wkdu.org/contact",
    sourceUrl: "https://wkdu.org/contact",
    sourceType: "automation_run_229_public_research",
    country: "United States / Philadelphia, Pennsylvania free-format college radio",
    language: "en",
    genres: ["college-radio", "free-format-radio", "public-contact-form", "music-submission-topic", "radio-airplay", "free-first", "manual-review"],
    submissionMethod: "wkdu-philadelphia-music-submission-public-contact-form-route",
    feeRequired: false,
    feeAmount: "Free public contact-form route. Official WKDU contact form includes a Music Submission topic and no payment field was observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for form content, contact data, music-link choice, privacy/session handling, editorial fit and avoiding unsolicited upload or outbound-message automation. No form was submitted.",
    notes: "Official WKDU Contact page exposes a public form with required name, email, subject, topic and body fields; Music Submission is one of the available topics. The active homepage shows current July 2026 playlists, on-air scheduling and local-event activity."
  },
  {
    name: "KSPC Claremont Album EP CD Record Digital Download Route",
    websiteUrl: "https://kspc.org/",
    submissionUrl: "https://kspc.org/contact/music-submissions/",
    sourceUrl: "https://kspc.org/contact/music-submissions/",
    sourceType: "automation_run_229_public_research",
    country: "United States / Claremont, California college and community radio",
    language: "en",
    genres: ["college-radio", "community-radio", "album-ep", "cd-record", "digital-download", "music-director-email-link", "no-singles", "no-ai-music", "free-first", "manual-review"],
    submissionMethod: "kspc-claremont-album-ep-cd-record-digital-download-route",
    feeRequired: false,
    feeAmount: "Free manual physical/digital route. Official KSPC music-submission guidance states the station is noncommercial and does not accept payment in exchange for airplay.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for album/EP eligibility, no-singles/no-demos/no-cassettes restrictions, AI-music exclusion, download-link or file-attachment choice, physical mailing and review-process expectations. No protected email was decoded and no files or packages were transferred.",
    notes: "Official KSPC Music Submissions page welcomes airplay submissions from artists from all genres, accepts mailed CDs/records but no singles, accepts digital music by email attachment or cloud-download link, rejects Spotify/iTunes links, demos, cassettes and substantially AI-generated work, states there is no guarantee of programming, and notes post-programming review before airplay."
  },
  {
    name: "KXLU Los Angeles FCC Clean Physical Music Submission Route",
    websiteUrl: "https://kxlu.com/",
    submissionUrl: "https://kxlu.com/contact/",
    sourceUrl: "https://kxlu.com/contact/",
    sourceType: "automation_run_229_public_research",
    country: "United States / Los Angeles, California free-form college and community radio",
    language: "en",
    genres: ["college-radio", "free-form-radio", "physical-submission", "fcc-clean", "music-director", "demolisten", "punk-folk-vinyl", "free-first", "manual-review"],
    submissionMethod: "kxlu-los-angeles-fcc-clean-physical-music-submission-route",
    feeRequired: false,
    feeAmount: "Free manual physical-mail route. Official KXLU contact/submissions guidance lists FCC-clean submissions and station mailing routes without a submission payment requirement.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for FCC-clean material, choosing General Submissions versus Demolisten versus Punk/Folk/Vinyl attention routing, physical package preparation, local/unsigned/demo fit and no-contact automation. No email was sent and no package was prepared.",
    notes: "Official KXLU Contact page lists staff contacts and a Submissions section requiring FCC-clean submissions only, with physical mailing attention routes for the Music Director, Demolisten and A Fistful of Vinyl. The homepage shows current playlists, DJ schedule and 2026 blog/fundraiser activity."
  }
];