import type { PlatformInput } from '../models/types.js';

export const run200BaseSeedPlatforms: PlatformInput[] = [
  {
    name: "WERS 88.9FM Wicked Local Wednesday MP3 Upload Local Boston Route",
    websiteUrl: "https://wers.org/",
    submissionUrl: "https://wers.org/wicked-local-wednesday/",
    sourceUrl: "https://wers.org/wicked-local-wednesday/",
    sourceType: "automation_run_200_public_research",
    country: "United States / Boston local artist radio-upload form route",
    language: "en",
    genres: ["college-radio", "boston", "local-artists", "wicked-local-wednesday", "mp3-upload-form", "live-session", "independent-artists", "electronic", "reggae", "manual-review"],
    submissionMethod: "official-wers-wicked-local-wednesday-mp3-upload-form-route",
    feeRequired: false,
    feeAmount: "Free-first/manual local-radio form route; official WERS Wicked Local Wednesday page invites local bands to fill out the form and accepts MP3 files up to 39 MB. No submission fee was observed.",
    loginRequired: false,
    captchaDetected: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because this is a local Boston-area route with an upload form, artist-location fields, contact fields, MP3 file upload and a site-level reCAPTCHA boundary. Owner review is needed for local eligibility, rights, radio-clean status, file choice, contact details and anti-abuse boundaries. No form, upload, CAPTCHA or message step may be automated.",
    notes: "Official WERS pages show active July 2026 music coverage, a Submit Music navigation route, Wicked Local Wednesday programming for Boston-area artists, a public MP3 upload form and reCAPTCHA protection. No file was uploaded, no form was submitted and no CAPTCHA/session control was handled."
  },
  {
    name: "WMBR MIT Physical CD Music Director Freeform Airplay Route",
    websiteUrl: "https://wmbr.org/",
    submissionUrl: "https://wmbr.org/www/md",
    sourceUrl: "https://wmbr.org/www/md",
    sourceType: "automation_run_200_public_research",
    country: "United States / Cambridge MIT freeform radio physical music director route",
    language: "en",
    genres: ["college-radio", "freeform", "mit", "physical-submission", "music-director", "unsigned-artists", "experimental", "rpm-techno", "world", "manual-review"],
    submissionMethod: "official-wmbr-music-director-physical-cd-route",
    feeRequired: false,
    feeAmount: "Free-first/manual college-radio route; official WMBR Your Music page gives a Music Director postal address, treats unsigned bands like major-label bands, and urges artists and labels to send tangible physical music. No submission fee was observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WMBR strongly prefers tangible physical submissions, discourages MP3 review requests, and relies on individual freeform DJs. Owner review is needed for physical package choice, one-sheet, FCC-clean content, genre-show targeting and avoiding unsolicited updates or attachments. No package, email, protected contact or delivery action may be automated.",
    notes: "Official WMBR pages show active current-air information, a Your Music route, Music Director mailing instructions, unsigned-band eligibility, physical-only preference and protected image-based contact routes for specific genres. No protected contacts were decoded and no package or message was prepared."
  },
  {
    name: "WMFO Tufts Music Director CD Digital Library Route",
    websiteUrl: "https://www.wmfo.org/",
    submissionUrl: "https://www.wmfo.org/contact/",
    sourceUrl: "https://www.wmfo.org/contact/",
    sourceType: "automation_run_200_public_research",
    country: "United States / Medford Tufts college-radio Music Director route",
    language: "en",
    genres: ["college-radio", "freeform", "tufts", "music-director", "cd-submission", "digital-library", "vinyl", "independent-artists", "electronic", "manual-review"],
    submissionMethod: "official-wmfo-music-director-contact-and-library-route",
    feeRequired: false,
    feeAmount: "Free-first/manual college-radio route; official WMFO contact and get-involved pages list the current Music Director email, describe constant CD intake and digital database/library curation, and show no submission fee.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WMFO exposes a Music Director contact and music-library context rather than an automated submission endpoint. Owner review is needed for deciding whether to use email, physical CD/vinyl, digital link or local relationship route, plus metadata, rights, clean edit status and one-sheet preparation. No email, file transfer or package may be automated.",
    notes: "Official WMFO pages show active 2026 station context, the 2025-2026 Music Director listing, a public md@wmfo.org address, ongoing CD intake, occasional vinyl/cassette intake and a digital Rivendell library. No email, upload, package or deliverability probe was performed."
  },
  {
    name: "KXCI Tucson MP3 WAV Download Link Music Department Route",
    websiteUrl: "https://kxci.org/",
    submissionUrl: "https://kxci.org/about/music-department/",
    sourceUrl: "https://kxci.org/about/music-department/",
    sourceType: "automation_run_200_public_research",
    country: "United States / Tucson community-radio global digital and physical music department route",
    language: "en",
    genres: ["community-radio", "tucson", "music-department", "mp3", "wav", "download-link", "physical-submission", "local-priority", "world", "reggae", "manual-review"],
    submissionMethod: "official-kxci-music-department-download-link-physical-route",
    feeRequired: false,
    feeAmount: "Free-first/manual community-radio route; official KXCI Music Department page accepts music from all over the world, prioritizes local/regional/Arizona artists, and accepts MP3/WAV download links plus CDs/vinyl. No submission fee was observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KXCI asks for reviewed music submissions with release metadata, explicit-language notes, tracklist, artwork, bio, links and contact details, and exposes protected contact routes. Owner review is needed for download-link selection, local/regional fit, clean edits, metadata completeness and whether to mail physical copies. No protected contacts were decoded and no email/package action may be automated.",
    notes: "Official KXCI pages show active June 2026 programming/news, Music Department submission recommendations, global acceptance language, MP3/WAV digital-link route, physical CD/vinyl mailing guidance and protected email contact display. No protected contact decoding, email, file transfer or package preparation was performed."
  },
  {
    name: "KFAI Fresh Air Music Library Email Submission Route",
    websiteUrl: "https://kfai.org/",
    submissionUrl: "https://kfai.org/about/contact/",
    sourceUrl: "https://kfai.org/about/contact/",
    sourceType: "automation_run_200_public_research",
    country: "United States / Minneapolis Saint Paul community-radio music library route",
    language: "en",
    genres: ["community-radio", "minneapolis", "saint-paul", "music-library", "fresh-air-radio", "new-music", "diverse-programming", "independent-artists", "world", "reggae", "manual-review"],
    submissionMethod: "official-kfai-music-library-email-submission-route",
    feeRequired: false,
    feeAmount: "Free-first/manual community-radio route; official KFAI contact page invites artists to share music with the KFAI Music Department and Music Library by email, with no submission fee observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KFAI uses a public/protected email route for music sharing, warns that receipt may not be confirmed due to request volume, and operates a diverse volunteer programming model. Owner review is needed for release fit, concise pitch, rights, link-only delivery, clean edit status, metadata and avoiding repeated follow-up. No protected contact was decoded and no email or file link was sent.",
    notes: "Official KFAI pages show active July 2026 posts, First Tracks new-music newsletter/library context, staff directory, and Music Department/Music Library invitation to share music through a protected email route. No login, email, form, contact decoding or deliverability probe was performed."
  }
];
