import type { PlatformInput } from '../models/types.js';

export const run294SeedPlatforms: PlatformInput[] = [
  {
    "name": "4ZZZ 102.1FM Official Digital Music Submission Form",
    "websiteUrl": "https://4zzz.org.au/",
    "submissionUrl": "https://jeff.4zzz.org.au/form/submit-your-music-to-4zzz",
    "sourceUrl": "https://4zzz.org.au/music-submissions",
    "sourceType": "automation_run_294_public_research",
    "country": "Australia / Brisbane independent community radio with open digital music-department intake",
    "language": "en",
    "genres": ["4zzz", "community-radio", "freeform", "independent", "electronic", "dance", "reggae", "world", "alternative", "digital-form", "download-link", "javascript", "permission", "manual-review"],
    "submissionMethod": "official-4zzz-javascript-digital-music-submission-form",
    "feeRequired": false,
    "feeAmount": "No submission fee or payment requirement is stated on 4ZZZ's official music-submission page or live form.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "4ZZZ uses an official JavaScript-dependent form that requests artist and release metadata, identity and optional demographic information, biography or press-pack context, content warnings, social links, cover art and a downloadable WAV or 320-kbps MP3 link. Spotify links are not accepted, while Bandcamp or Apple Music submissions require a download code. The form also asks for permission to play the release before its release date and requires acknowledgement that 4ZZZ may broadcast it. A human must inspect the live controls, approve all permissions and identity disclosures, verify link access and rights and submit manually.",
    "notes": "Verified on 2026-07-12 from 4ZZZ's official submission page, live form and active homepage. The station displayed current July 2026 programming, playlists, events and an Album of the Week. The separate Album of the Week form is restricted to Australian artists and was not used as the primary MarcsMusic route. No form was submitted, no permission was granted and no assets were delivered."
  },
  {
    "name": "2SER 107.3FM Official Airplay Consideration Form",
    "websiteUrl": "https://www.2ser.com/",
    "submissionUrl": "https://www.2ser.com/how-to-submit-music",
    "sourceUrl": "https://www.2ser.com/how-to-submit-music",
    "sourceType": "automation_run_294_public_research",
    "country": "Australia / Sydney educational community radio with a public music-intake form",
    "language": "en",
    "genres": ["2ser", "community-radio", "educational-radio", "alternative", "underground", "electronic", "independent", "digital-form", "artist-bio", "social-links", "dynamic-form", "manual-review"],
    "submissionMethod": "official-2ser-public-airplay-consideration-form",
    "feeRequired": false,
    "feeAmount": "No submission fee or payment requirement is stated on 2SER's official music-submission page.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "2SER's official page provides a public form for airplay consideration and requests first and last name, email, location, release date, artist or band name, release title, artist biography and social-media links. The form is dynamically loaded, and the static page does not expose all live validation, music-link requirements, declarations or possible anti-spam controls. A human must inspect the current form, confirm international eligibility and required track-delivery fields, approve all submitted data and complete the workflow manually.",
    "notes": "Verified on 2026-07-12 from 2SER's official submission page and station website. The site presents current 2026 operations and alternative and underground music programming. 2SER says it cannot respond to every submission. No form was submitted, no fields were completed and no track or private link was supplied."
  },
  {
    "name": "Triple R 102.7FM Official Station Email and Physical Music Submission Route",
    "websiteUrl": "https://www.rrr.org.au/",
    "submissionUrl": "mailto:music@rrr.org.au",
    "sourceUrl": "https://www.rrr.org.au/get-involved/submit-music",
    "sourceType": "automation_run_294_public_research",
    "country": "Australia / Melbourne independent community radio with digital and physical servicing",
    "language": "en",
    "genres": ["triple-r", "community-radio", "independent-radio", "freeform", "electronic", "world", "hip-hop", "alternative", "digital-email", "stream-link", "download-link", "physical-media", "manual-review"],
    "submissionMethod": "official-triple-r-music-department-email-or-physical-route",
    "feeRequired": false,
    "feeAmount": "No submission fee or payment requirement is stated in Triple R's official music-submission guidance.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "Triple R publicly authorizes station-wide servicing through music@rrr.org.au. A compliant email needs a clear subject, a no-login streaming link, a non-expiring high-quality 320-kbps MP3 or WAV download link, clearly named files, a short biography and relevant gig details; large audio attachments are prohibited. Artists may alternatively service suitable public program contacts or mail physical CDs, LPs or cassettes to the Music Department. A human must choose the correct route, prepare compliant links and metadata, verify rights and expiry settings and address any physical package exactly.",
    "notes": "Verified on 2026-07-12 from Triple R's official submission page and active homepage, which showed current 11-12 July 2026 episodes, electronic releases, live sessions and events. The music@rrr.org.au address is purpose-specific and publicly displayed. No email was sent, no program was contacted and no physical package was prepared."
  },
  {
    "name": "SYN Media Official Music Directors Email Submission Route",
    "websiteUrl": "https://www.syn.org.au/",
    "submissionUrl": "mailto:music@syn.org.au",
    "sourceUrl": "https://www.syn.org.au/contact",
    "sourceType": "automation_run_294_public_research",
    "country": "Australia / Melbourne youth-run community radio with rolling music-director review",
    "language": "en",
    "genres": ["syn-media", "youth-radio", "community-radio", "independent", "electronic", "pop", "hip-hop", "alternative", "digital-email", "download-link", "rolling-review", "manual-review"],
    "submissionMethod": "official-syn-music-directors-email-route",
    "feeRequired": false,
    "feeAmount": "No submission fee or payment requirement is stated on SYN Media's official contact page.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "SYN Media publicly directs music servicing to music@syn.org.au. The email must include a downloadable 320-kbps MP3 or WAV link rather than direct attachments, a press release or artist biography, track or release title, release date and relevant website, social, gig and previous-release links. Music Directors review submissions on a rolling basis and may not reply. A human must prepare the release package, ensure download permissions and metadata are correct, keep music and interview requests separated and send the email manually.",
    "notes": "Verified on 2026-07-12 from SYN Media's official contact page and active 2026 website. The page identifies the purpose-specific music submission and music interview addresses separately and lists current staff. No email was sent, no attachment or download link was delivered and no interview request was made."
  },
  {
    "name": "95bFM Official Lossless Music Submission Email Route",
    "websiteUrl": "https://95bfm.com/",
    "submissionUrl": "https://95bfm.com/news/how-do-you-do-submitting-music",
    "sourceUrl": "https://95bfm.com/news/how-do-you-do-submitting-music",
    "sourceType": "automation_run_294_public_research",
    "country": "New Zealand / Auckland independent university radio accepting direct music servicing",
    "language": "en",
    "genres": ["95bfm", "student-radio", "independent-radio", "alternative", "electronic", "dance", "world", "digital-email", "lossless-audio", "stream-link", "download-link", "protected-email", "manual-review"],
    "submissionMethod": "official-95bfm-protected-music-email-with-stream-and-lossless-download",
    "feeRequired": false,
    "feeAmount": "No submission fee or payment requirement is stated in 95bFM's official music-submission guidance.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "95bFM's official guidance directs artists to a protected email contact and requires both an immediately accessible streaming link and a download link to a lossless master such as WAV or FLAC. Links must not require the station to create an account or enter a password; Spotify is unsuitable. The message should include artist and song names, release date, origin and only brief context. Tracks older than one month are no longer eligible for high-rotation A/B playlisting. A human must confirm the protected address in the browser, prepare compliant no-login links, verify release timing and rights and send manually.",
    "notes": "Verified on 2026-07-12 from 95bFM's official submission guidance and active homepage, which displayed current July 2026 shows, albums of the week and events. The protected email address was not decoded or copied from an unofficial source. No email was sent, no link was shared and no account-gated service was used."
  }
];
