import type { PlatformInput } from '../models/types.js';

export const run224SeedPlatforms: PlatformInput[] = [
  {
    name: "DailyPlaylists Free Premium Spotify Playlist Submission Route",
    websiteUrl: "https://dailyplaylists.com/",
    submissionUrl: "https://dailyplaylists.com/submit-song/add-song/",
    sourceUrl: "https://dailyplaylists.com/",
    sourceType: "automation_run_224_public_research",
    country: "United Kingdom / global Spotify playlist submission marketplace",
    language: "en",
    genres: ["spotify-playlist", "playlist-submission", "curator-marketplace", "free-first", "premium-credits", "login-boundary", "pricing-boundary"],
    submissionMethod: "dailyplaylists-free-premium-spotify-playlist-submission-route",
    feeRequired: false,
    feeAmount: "Free-first/freemium manual route. Official pricing page lists a Free tier with 10 weekly Standard Submissions, paid add-on submissions at $7.99/10, Premium Credits at $19.99/10, and Professional at $19.99/month.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for sign-in/session, Spotify track lookup, playlist targeting, free-vs-premium submission choice, curator relevance, campaign limits, add-on credit purchase and contact/consent boundaries. No account was created and no track was submitted.",
    notes: "Official DailyPlaylists pages expose Submit a Song, Sign In, a marketplace of 18,000+ playlists, free standard submissions, premium curator credits, professional tier features and public contact email info@dailyplaylists.com."
  },
  {
    name: "Indiemono Free Spotify Playlist Public Form Submission Route",
    websiteUrl: "https://indiemono.com/",
    submissionUrl: "https://indiemono.com/submit-music-chill-playlists/",
    sourceUrl: "https://indiemono.com/submit-music-chill-playlists/",
    sourceType: "automation_run_224_public_research",
    country: "Spain / global Spotify playlist network",
    language: "en",
    genres: ["spotify-playlist", "free-submission-form", "chill", "edm", "indie-alternative", "urban", "folk", "latino", "consent-boundary", "cookie-boundary"],
    submissionMethod: "indiemono-free-spotify-playlist-public-form-submission-route",
    feeRequired: false,
    feeAmount: "Free manual route. Official Indiemono form states the system is free and accepts any amount of music, while optional PR/label/radio/blog/YouTube/TikTok/sync interest fields are separate owner-controlled outreach boundaries.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for public Spotify-track URL, released-track availability, genre fit, consent/newsletter terms, optional third-party service-interest fields, cookie banner and privacy boundary. No form was submitted and no consent/cookie choice was accepted.",
    notes: "Official Indiemono page provides a public form with name, email, track name/artist, Spotify track URL, genre selection, consent terms and Submit button; the page says email/Facebook submissions are not processed."
  },
  {
    name: "Musosoup Free Intake Paid Coverage Campaign Route",
    websiteUrl: "https://musosoup.com/",
    submissionUrl: "https://app.musosoup.com/submit-music",
    sourceUrl: "https://musosoup.com/",
    sourceType: "automation_run_224_public_research",
    country: "United Kingdom / global music promotion marketplace",
    language: "en",
    genres: ["music-promotion", "playlisting", "press", "radio", "blog-review", "curator-marketplace", "free-intake", "paid-campaign", "login-boundary", "pricing-boundary"],
    submissionMethod: "musosoup-free-intake-paid-coverage-campaign-route",
    feeRequired: false,
    feeAmount: "Free intake / paid campaign manual route. Official pages say artists can submit/upload or share a link for free; if accepted, campaign activation costs £42 and additional curator offers may be paid or free.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for app/session, single/EP/album upload or link, release timing, approval outcome, £42 campaign activation, free-vs-paid curator offers, marketplace budget and refund/coverage terms. No account was created, no upload was made and no campaign fee was paid.",
    notes: "Official Musosoup pages expose Submit music / Sign in routes, 2026 blog activity, free submission intake, curator review, playlist/radio/blog/social coverage, campaign reports, £42 activation and hundreds of vetted curator opportunities."
  },
  {
    name: "Hypeddit Free Trial Music Promotion Download Gate Route",
    websiteUrl: "https://hypeddit.com/",
    submissionUrl: "https://hypeddit.com/",
    sourceUrl: "https://hypeddit.com/",
    sourceType: "automation_run_224_public_research",
    country: "Germany / global music promotion and fan-gate platform",
    language: "en",
    genres: ["music-promotion", "download-gate", "smart-link", "pre-save", "ai-ads", "promotion-exchange", "soundcloud", "spotify", "youtube", "tiktok", "login-boundary", "pricing-boundary", "cookie-boundary"],
    submissionMethod: "hypeddit-free-trial-music-promotion-download-gate-route",
    feeRequired: false,
    feeAmount: "Free-trial/freemium manual route. Official page exposes Try for free plus paid music promotion plans starting at $10/month; ad/campaign spend and fan-gate configuration remain manual owner-controlled choices.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for login/session, cookie preferences, upload/song selection, download-gate/smart-link/pre-save setup, fan permissions, Spotify/SoundCloud/YouTube connections, paid-plan choice, AI ad targeting and campaign spend. No account was created, no fans were gated and no campaign was launched.",
    notes: "Official Hypeddit page advertises music promotion tools, Try for free, AI-powered music ads, download gates, smart links, pre-saves, promotion exchange, charts/new releases and paid plans."
  },
  {
    name: "Richer Unsigned Free UK Emerging Artist Playlist Upload Route",
    websiteUrl: "https://richerunsigned.com/",
    submissionUrl: "https://richerunsigned.com/submit/",
    sourceUrl: "https://richerunsigned.com/submit/",
    sourceType: "automation_run_224_public_research",
    country: "United Kingdom / emerging artist playlist and store-play platform",
    language: "en",
    genres: ["emerging-artist", "spotify-track-form", "playlist-consideration", "store-play", "artist-of-the-week", "free-first", "file-upload-boundary", "javascript-form-boundary"],
    submissionMethod: "richer-unsigned-free-uk-emerging-artist-playlist-upload-route",
    feeRequired: false,
    feeAmount: "Free manual route. Official Richer Unsigned page says the not-for-profit platform is completely free to take part in and the submit page exposes no payment requirement.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for UK/emerging-artist fit, JavaScript form, contact data, third-person bio, Spotify artist URL, band image upload, Spotify track URL, owner-of-music confirmation and Terms & Conditions consent. No form was submitted and no image/audio/link was uploaded.",
    notes: "Official Richer Unsigned pages show current 2026 Artist of the Week updates, public Submit navigation, playlist exposure in Richer Sounds stores, free participation, a JavaScript public form and public general enquiry email enquiries@richerunsigned.com."
  }
];
