import type { PlatformInput } from '../models/types.js';

export const run235SeedPlatforms: PlatformInput[] = [
  {
    name: "EARMILK SubmitHub Pillargram Editorial Music Submission Route",
    websiteUrl: "https://earmilk.com/",
    submissionUrl: "https://earmilk.com/submit-music/",
    sourceUrl: "https://earmilk.com/submit-music/",
    sourceType: "automation_run_235_public_research",
    country: "United States / North America / global electronic, hip-hop, indie and pop music publication",
    language: "en",
    genres: ["music-blog", "editorial-coverage", "electronic", "dance", "experimental", "hip-hop", "indie", "pop", "rock", "submit-hub", "pillargram", "premiere-submission", "playlist-blog-coverage", "payment-pricing-boundary", "login-session-app-boundary", "manual-review"],
    submissionMethod: "earmilk-submithub-pillargram-editorial-music-submission-route",
    feeRequired: true,
    feeAmount: "Manual paid/freemium boundary. Official EARMILK submission page says it currently accepts submissions exclusively through SubmitHub or Pillargram, so credits, platform account, curator selection and any paid/freemium options must be owner-reviewed before use.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for third-party SubmitHub/Pillargram account/session, possible credits/payment, track/premiere selection, genre targeting, release timing and editorial pitch copy. No account was created, no third-party submission route was opened beyond public pages and no track was submitted.",
    notes: "Official EARMILK page exposes dance, electronic, experimental, hip-hop, indie, pop and rock editorial sections and states music/premiere submissions must go through SubmitHub or Pillargram. The same page showed July 2026 popular/recent music posts, validating activity. Suitable for MarcsMusic electronic, bass, reggae-fusion and hip-hop-adjacent releases with manual review."
  },
  {
    name: "Pillargram Curator Influencer Music Promotion Submission Route",
    websiteUrl: "https://pillargram.com/",
    submissionUrl: "https://pillargram.com/",
    sourceUrl: "https://pillargram.com/",
    sourceType: "automation_run_235_public_research",
    country: "Worldwide music-promotion and curator/influencer submission platform",
    language: "en",
    genres: ["music-promotion", "curator-submission", "influencer-promotion", "playlist-placement", "social-media-promotion", "blog-placement", "artist-profile", "campaign-dashboard", "direct-industry-connections", "login-session-app-boundary", "payment-pricing-boundary", "manual-review"],
    submissionMethod: "pillargram-curator-influencer-music-promotion-submission-route",
    feeRequired: true,
    feeAmount: "Paid/manual route. Official page advertises guaranteed music promotion as low as $1, campaign creation, curator selection and dashboard tracking; exact spend requires owner approval.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for artist profile creation, sign-up/login, track upload, campaign setup, curator/influencer choice, budget/tip/payment controls, campaign claims and analytics access. No account was created, no campaign was started and no payment was made.",
    notes: "Official Pillargram page says musicians can submit tracks for promotion and feedback, connect with curators, influencers and industry professionals, upload music, start a campaign and track status/feedback in a dashboard. EARMILK also lists Pillargram as an accepted route for EARMILK submissions."
  },
  {
    name: "Fresh On The Net Listening Post Weekly Track Submission Route",
    websiteUrl: "https://freshonthenet.co.uk/",
    submissionUrl: "https://freshonthenet.co.uk/submit/",
    sourceUrl: "https://freshonthenet.co.uk/submit/",
    sourceType: "automation_run_235_public_research",
    country: "United Kingdom / worldwide unsigned and emerging artist listening-post platform",
    language: "en",
    genres: ["unsigned-artists", "emerging-artists", "listening-post", "weekly-track-submission", "soundcloud-link", "public-worldwide-track", "fresh-faves", "radio-consideration-boundary", "manual-review"],
    submissionMethod: "fresh-on-the-net-listening-post-weekly-track-submission-route",
    feeRequired: false,
    feeAmount: "Free public/manual route. Official page welcomes any artist to send one track per week, with the inbox capped by time/window and track volume.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required because the inbox was closed at verification time, submission windows are time-limited, only one public worldwide track is allowed, AI-generated tracks are rejected, repeated/remix submissions are restricted and social/voting rules require artist compliance. No track was submitted and no email was sent.",
    notes: "Official Fresh On The Net page says any artist may send one track weekly, the team listens, moderators may feature tracks on Listening Post/Fresh Faves, tracks must be publicly available worldwide, only one track is allowed and AI-generated tracks are not accepted. Page shows July 2026 blog/archive activity and an upcoming inbox opening date."
  },
  {
    name: "Radio Airplay Jango Guaranteed Internet Radio Upload Route",
    websiteUrl: "https://www.radioairplay.com/",
    submissionUrl: "https://www.radioairplay.com/",
    sourceUrl: "https://www.radioairplay.com/",
    sourceType: "automation_run_235_public_research",
    country: "United States / worldwide internet-radio airplay and song-review platform",
    language: "en",
    genres: ["internet-radio", "jango", "guaranteed-airplay", "song-reviews", "fan-insights", "free-contests", "playlist-opportunities", "sync-partner-offers", "artist-upload", "login-session-app-boundary", "payment-pricing-boundary", "manual-review"],
    submissionMethod: "radio-airplay-jango-guaranteed-internet-radio-upload-route",
    feeRequired: false,
    feeAmount: "Free-first/freemium manual route. Official page shows Free Sign Up, a Free package with 100 one-time signup bonus plays, and paid Intro/Gold/Platinum/Multi-Platinum packages from $12 to $250.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for sign-up/login, track upload, artist-station targeting, package selection, paid plays, song-review requests, contests, sync/partner offers, fan messaging and profile/publicity claims. No account was created, no track was uploaded and no package was selected.",
    notes: "Official Radio Airplay page exposes free sign-up, music upload, matched artist-station airplay, reports/fan insights, expert song reviews, free contests, playlist opportunities, sync/partner offers and package pricing. The public page lists premium@radioairplay.com for larger deals, treated as a business-contact route rather than an automatic submission path."
  },
  {
    name: "mau5trap WAF 13 Tally Demo Submission Route",
    websiteUrl: "https://mau5trap.com/",
    submissionUrl: "https://tally.so/r/J9Lg5Y",
    sourceUrl: "https://edm.com/features/mau5trap-we-are-friends-series-history/",
    sourceType: "automation_run_235_public_research",
    country: "United States / worldwide electronic music label demo open-call route",
    language: "en",
    genres: ["electronic", "progressive-house", "bass-music", "techno", "label-demo", "compilation-open-call", "soundcloud-downloadable-demo", "final-version-only", "sample-license-proof", "ai-disclosure", "tally-form-boundary", "manual-review"],
    submissionMethod: "mau5trap-waf-13-tally-demo-submission-route",
    feeRequired: false,
    feeAmount: "No public upfront submission fee observed on the Tally form. Manual review required because the form redirects to a Patreon page after submission and asks for release-readiness, SoundCloud downloadability and rights/sample/AI disclosures.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for label fit, final-master readiness, downloadable SoundCloud link, location/contact/Instagram data, genre confidence, AI-tool disclosure, vocal-sample license proof upload, prior-label submission declarations, Patreon-community question and final submit confirmation. No form was submitted and no file/license proof was uploaded.",
    notes: "EDM.com published the mau5trap WAF 13 open-call coverage on July 3, 2026 and linked the official Tally demo form. The form says mau5trap listens to every submission, requires best/final downloadable SoundCloud-only demos, asks AI/sample-license/prior-submission questions and includes upload fields for license proof when relevant. Strong fit for MarcsMusic electronic/bass-focused tracks, subject to manual label-fit review."
  }
];
