import type { PlatformInput } from '../models/types.js';

export const run226BaseSeedPlatforms: PlatformInput[] = [
  {
    name: "KBOO Portland Physical Genre Attention Community Radio Submission Route",
    websiteUrl: "https://www.kboo.fm/",
    submissionUrl: "https://www.kboo.fm/submit-your-music",
    sourceUrl: "https://www.kboo.fm/submit-your-music",
    sourceType: "automation_run_226_public_research",
    country: "United States / Portland, Oregon community freeform radio",
    language: "en",
    genres: ["community-radio", "freeform", "physical-package", "genre-routing", "cd", "vinyl", "free-first", "manual-review"],
    submissionMethod: "kboo-portland-physical-genre-attention-community-radio-submission-route",
    feeRequired: false,
    feeAmount: "Free manual physical route. Official KBOO Submit Your Music page asks artists to mail submissions to KBOO-FM and does not list a payment requirement for airplay consideration.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for physical package preparation, genre-attention routing, CD/vinyl availability, metadata, airplay expectations, risk that mailed submissions become station property, and postal delivery. No package was prepared or mailed.",
    notes: "Official KBOO guidance says the station does not yet have a digital library, cannot download and burn digital submissions, and asks submitters to mail material to KBOO-FM with genre-specific attention lines for electronic/other, folk, rock/punk/electronic, jazz, hip-hop, world music and reggae."
  },
  {
    name: "BFF.fm Bay Area Bands Google Form Digital Airplay Submission Route",
    websiteUrl: "https://bff.fm/",
    submissionUrl: "https://bff.fm/bands",
    sourceUrl: "https://bff.fm/bands",
    sourceType: "automation_run_226_public_research",
    country: "United States / San Francisco Bay Area community internet radio",
    language: "en",
    genres: ["community-radio", "bay-area", "local-artists", "digital-form", "google-form", "blog-feature", "automation-playlist", "free-first", "manual-review"],
    submissionMethod: "bff-fm-bay-area-bands-google-form-digital-airplay-submission-route",
    feeRequired: false,
    feeAmount: "Free manual form route. Official BFF.fm Bay Area Bands page invites Bay Area artists to submit music for airplay, Locals Only automation playlist consideration and blog features; no payment requirement was observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for Bay Area eligibility, Google Forms data-entry boundary, artist location, music link/file metadata, rights confirmation and editorial fit. No form was opened or submitted.",
    notes: "Official BFF.fm contact page says not to mail unsolicited music and routes digital submissions from Bay Area bands to BFF.fm/bands; the bands page defines eligible counties and links to a public Google Forms submission route."
  },
  {
    name: "XRAY Portland Submissions Email Guidelines Music Director Route",
    websiteUrl: "https://xray.fm/",
    submissionUrl: "https://xray.fm/contact",
    sourceUrl: "https://xray.fm/contact",
    sourceType: "automation_run_226_public_research",
    country: "United States / Portland, Oregon independent radio",
    language: "en",
    genres: ["independent-radio", "community-radio", "music-submissions-email", "guidelines-link", "free-first", "manual-review"],
    submissionMethod: "xray-portland-submissions-email-guidelines-music-director-route",
    feeRequired: false,
    feeAmount: "Free manual email route. Official XRAY contact page lists submissions@xray.fm for Music Submissions and links to music submission guidelines; no payment requirement was observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for guideline review, pitch copy, clean/radio-ready files or links, metadata, show fit and email sending. No outbound email was sent and no guideline form/file transfer was performed.",
    notes: "Official XRAY contact page lists general station, DJ/host, underwriting, events and music submission routes; Music Submissions are directed to submissions@xray.fm with a separate public guideline link."
  },
  {
    name: "SomaFM Digital High Bitrate MP3 Channel Music Director Submission Route",
    websiteUrl: "https://somafm.com/",
    submissionUrl: "https://somafm.com/contact/submitmusic.html",
    sourceUrl: "https://somafm.com/contact/submitmusic.html",
    sourceType: "automation_run_226_public_research",
    country: "United States / global commercial-free underground internet radio",
    language: "en",
    genres: ["internet-radio", "electronic", "ambient", "downtempo", "reggae", "indie", "channel-email", "digital-link", "free-first", "manual-review"],
    submissionMethod: "somafm-digital-high-bitrate-mp3-channel-music-director-submission-route",
    feeRequired: false,
    feeAmount: "Free manual digital route. Official SomaFM Submit Music page requires digital submissions and lists channel-specific music-director emails; optional listener donations are unrelated to submission eligibility.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for no-AI policy, channel selection, Bandcamp/YUM or WeTransfer/Dropbox link preparation, MP3 bitrate/metadata compliance, one-recipient anti-spam rule and editorial fit. No files were uploaded or transferred and no email was sent.",
    notes: "Official SomaFM guidance says it supports commercial, independent, emerging and unsigned artists, requires digital submissions rather than CDs, rejects low-bitrate and streaming-only sources for broadcast, and lists currently accepting channel email routes including promosubmissions@somafm.com and several channel-specific addresses."
  },
  {
    name: "idobi Radio Howl Anthm Public Form Dropbox Upload Music Submission Route",
    websiteUrl: "https://idobi.com/",
    submissionUrl: "https://idobi.com/submit/",
    sourceUrl: "https://idobi.com/submit/",
    sourceType: "automation_run_226_public_research",
    country: "United States / global alternative pop-punk metal indie internet radio",
    language: "en",
    genres: ["internet-radio", "alternative", "pop-punk", "metal", "indie", "public-form", "dropbox-upload", "terms-boundary", "cookie-boundary", "free-first", "manual-review"],
    submissionMethod: "idobi-radio-howl-anthm-public-form-dropbox-upload-music-submission-route",
    feeRequired: false,
    feeAmount: "Free manual public form/upload route. Official idobi Submit Music page exposes artist, track, contact, airplay-readiness verification and Terms of Use fields plus an Upload Music button; no payment requirement was observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for public-form entry, Dropbox upload boundary, contact/phone/address fields, airplay-readiness verification, Terms of Use consent, cookie notice and station-specific fit. No form was submitted and no Dropbox upload was started.",
    notes: "Official idobi Submit Music page covers idobi Radio, idobi Howl and idobi Anthm, asks for artist and track details, authorized-agent signature, airplay-readiness verification, Terms of Use acceptance, preferred MP3 files, and a Dropbox Upload Music route."
  }
];