import type { PlatformInput } from '../models/types.js';

export const run225BaseSeedPlatforms: PlatformInput[] = [
  {
    name: "KZSU Stanford Physical Digital Music Director Submission Route",
    websiteUrl: "https://kzsu.stanford.edu/",
    submissionUrl: "https://kzsu.stanford.edu/contact/",
    sourceUrl: "https://kzsu.stanford.edu/contact/",
    sourceType: "automation_run_225_public_research",
    country: "United States / Stanford, California college freeform radio",
    language: "en",
    genres: ["college-radio", "freeform", "music-director", "physical-package", "digital-email", "free-first", "cookie-boundary", "manual-review"],
    submissionMethod: "kzsu-stanford-physical-digital-music-director-submission-route",
    feeRequired: false,
    feeAmount: "Free manual route. Official KZSU contact page lists KZSU Music postal delivery plus Music Directors / send-us-music routing and a public music@kzsu.stanford.edu address; no payment requirement was observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for physical package versus music-director email selection, promo copy, FCC-clean/radio-fit review, anti-spam guidance, guideline page cookie/session boundary and release metadata. No email was sent and no package was prepared or mailed.",
    notes: "Official KZSU contact page lists KZSU Music postal address, a Music Directors section marked 'send us music!' and the public business-domain route music@kzsu.stanford.edu. The linked music-submission-guidelines route presented a temporary-cookie requirement, so it remains manual."
  },
  {
    name: "WPRB Princeton Physical Priority Music Submission Email Route",
    websiteUrl: "https://wprb.com/",
    submissionUrl: "https://wprb.com/music-submissions/",
    sourceUrl: "https://wprb.com/music-submissions/",
    sourceType: "automation_run_225_public_research",
    country: "United States / Princeton, New Jersey college freeform radio",
    language: "en",
    genres: ["college-radio", "freeform", "physical-priority", "music-director", "email-route", "vinyl", "cd", "free-first", "manual-review"],
    submissionMethod: "wprb-princeton-physical-priority-music-submission-email-route",
    feeRequired: false,
    feeAmount: "Free manual route. Official WPRB music-submissions page asks artists, labels and promoters to send physical CDs, CD-Rs, LPs, 12-inch, 10-inch or 7-inch releases and also lists music@wprb.com; no payment requirement was observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for physical-priority servicing, email versus mail decision, radio edit/FCC cleanliness, package contents, metadata and editorial fit. No email was sent and no package was prepared or mailed.",
    notes: "Official WPRB page states artists, labels or promoters can submit new music for airplay by mailing CDs, CD-Rs, LPs, 12-inch, 10-inch or 7-inch releases to the WPRB Music Director, and can also email music@wprb.com while physical submissions are prioritized."
  },
  {
    name: "WHUS UConn New Music Committee Album Review Music Director Route",
    websiteUrl: "https://whus.org/",
    submissionUrl: "https://whus.org/new-music-committee/",
    sourceUrl: "https://whus.org/new-music-committee/",
    sourceType: "automation_run_225_public_research",
    country: "United States / Storrs, Connecticut college variety radio",
    language: "en",
    genres: ["college-radio", "variety", "new-music-committee", "album-review", "music-director", "free-first", "manual-review"],
    submissionMethod: "whus-uconn-new-music-committee-album-review-music-director-route",
    feeRequired: false,
    feeAmount: "Free manual route. Official WHUS New Music Committee page says the committee reviews brand-new releases that promoters send to WHUS and lists musicdirector@whus.org for questions; no payment requirement was observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for album/EP suitability, promoter-style servicing, release metadata, music-director contact, weekly committee timing and station-format fit. No email was sent and no files or packages were transferred.",
    notes: "Official WHUS pages show active June 2026 posts and a New Music Committee that reviews albums sent by promoters, discusses them with peers, shapes station sound and lists musicdirector@whus.org."
  },
  {
    name: "WNYU New York Physical Digital Music Director Submission Route",
    websiteUrl: "https://wnyu.org/",
    submissionUrl: "https://wnyu.org/about",
    sourceUrl: "https://wnyu.org/about",
    sourceType: "automation_run_225_public_research",
    country: "United States / New York, New York student-run radio",
    language: "en",
    genres: ["college-radio", "student-radio", "music-director", "physical-priority", "digital-email", "free-first", "manual-review"],
    submissionMethod: "wnyu-new-york-physical-digital-music-director-submission-route",
    feeRequired: false,
    feeAmount: "Free manual route. Official WNYU About page says to send CDs, CD-Rs, LPs, 12-inch, 10-inch or 7-inch releases by mail or send digital submissions to music@wnyu.org; no payment requirement was observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for digital versus physical submission choice, physical-priority expectation, clean/radio-safe file or package preparation, metadata and station fit. No email was sent and no package was prepared or mailed.",
    notes: "Official WNYU About page identifies WNYU as NYU's student-run station, broadcasts on FM weekdays and online 24/7, lists its mailing address, invites artists to send music and names music@wnyu.org as the Music Director route."
  },
  {
    name: "WCBN Ann Arbor Hard Copy Album Music Director Route",
    websiteUrl: "https://wcbn.org/",
    submissionUrl: "https://wcbn.org/c/",
    sourceUrl: "https://wcbn.org/c/",
    sourceType: "automation_run_225_public_research",
    country: "United States / Ann Arbor, Michigan freeform college radio",
    language: "en",
    genres: ["college-radio", "freeform", "hard-copy", "cd", "vinyl", "music-director", "physical-package", "protected-email-observed", "free-first", "manual-review"],
    submissionMethod: "wcbn-ann-arbor-hard-copy-album-music-director-route",
    feeRequired: false,
    feeAmount: "Free manual physical route. Official WCBN contact page says it accepts music from any and all musicians willing to send a hard copy of their album, preferably CD or vinyl; no payment requirement was observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for hard-copy album preparation, CD/vinyl availability, genre care-of routing, physical package contents, postal delivery and protected/non-plaintext contact handling. No protected contact was decoded and no package was prepared or mailed.",
    notes: "Official WCBN contact page lists its mailing address, Music Directors section and says WCBN accepts music from any and all musicians who send a hard copy of their album, preferably CD or vinyl, and listens to everything sent. The public email link appeared protected/non-plaintext in the tool and was not decoded."
  }
];
