import type { PlatformInput } from '../models/types.js';

export const run227SeedPlatforms: PlatformInput[] = [
  {
    name: "KALX Berkeley Pressed CD LP Music Director Airplay Route",
    websiteUrl: "https://kalx.berkeley.edu/",
    submissionUrl: "https://kalx.berkeley.edu/about/contact/",
    sourceUrl: "https://kalx.berkeley.edu/about/contact/",
    sourceType: "automation_run_227_public_research",
    country: "United States / Berkeley, California college and community radio",
    language: "en",
    genres: ["college-radio", "community-radio", "freeform", "music-director-email", "physical-package", "pressed-cd", "lp", "free-first", "manual-review"],
    submissionMethod: "kalx-berkeley-pressed-cd-lp-music-director-airplay-route",
    feeRequired: false,
    feeAmount: "Free manual physical route. Official KALX contact page lists a Music Director route for airplay and does not list any submission payment requirement.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for physical professionally pressed CD or LP preparation, postal delivery, no-attachment/no-digital rule compliance, radio edit/FCC readiness, metadata, interview/live-session expectations and editorial fit. No package was prepared or mailed and no email was sent.",
    notes: "Official KALX Contact page lists music@kalx.berkeley.edu and says KALX only accepts physical, professionally pressed CDs or LPs for airplay; it explicitly rejects downloads, file transfers, Bandcamp/Spotify links, YouTube videos, burned CDs and other digital forms. The official homepage showed July 2026 schedules, recently played tracks and coming attractions."
  },
  {
    name: "SoundOn TikTok Artist Distribution Upload Royalty Route",
    websiteUrl: "https://www.soundon.global/",
    submissionUrl: "https://www.soundon.global/",
    sourceUrl: "https://www.soundon.global/",
    sourceType: "automation_run_227_public_research",
    country: "Global / TikTok artist distribution platform",
    language: "en",
    genres: ["distribution", "tiktok", "artist-upload", "royalties", "marketing", "publishing-administration", "free-first", "freemium", "login-boundary", "manual-review"],
    submissionMethod: "soundon-tiktok-artist-distribution-upload-royalty-route",
    feeRequired: false,
    feeAmount: "Free-first/freemium manual route. Public source material identifies SoundOn as a TikTok-owned music marketing and distribution platform where artists upload music, retain copyright and receive royalty shares. No up-front submission fee was verified in public source material.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for SoundOn account/session, territory eligibility, rights ownership, upload terms, royalty/revenue-share terms, payout/tax data, TikTok distribution choices and any app-side consent controls. No account was created and no music was uploaded.",
    notes: "Public source material identifies SoundOn as a worldwide TikTok/ByteDance music distribution and artist-services platform that lets users upload music directly to TikTok, retain copyright, earn royalties and distribute to other platforms; the official SoundOn site is a public app route."
  },
  {
    name: "BeatStars Marketplace Beat Licensing Upload Route",
    websiteUrl: "https://www.beatstars.com/",
    submissionUrl: "https://www.beatstars.com/",
    sourceUrl: "https://www.beatstars.com/",
    sourceType: "automation_run_227_public_research",
    country: "Global / producer and artist beat licensing marketplace",
    language: "en",
    genres: ["beat-marketplace", "music-licensing", "producer-upload", "collaboration", "non-exclusive-licenses", "exclusive-licenses", "freemium", "paid-plans", "login-boundary", "manual-review"],
    submissionMethod: "beatstars-marketplace-beat-licensing-upload-route",
    feeRequired: true,
    feeAmount: "Freemium/paid-plan manual route. Public source material says BeatStars operates free and paid subscription models with Marketplace and Pro Page plans; licensing transactions may also involve paid non-exclusive or exclusive license terms.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for account/session, producer/artist role choice, beat or song upload, license templates, publishing/split settings, paid subscription or marketplace transaction choices, rights ownership and tax/payout configuration. No account was created, no listing was created and no payment workflow was initiated.",
    notes: "Public source material identifies BeatStars as a global subscription-based music licensing platform where recording artists and producers collaborate, lease, license and distribute work through non-exclusive and exclusive licenses, with free and paid subscription models."
  },
  {
    name: "Audius Decentralized Artist Upload Token Monetization Route",
    websiteUrl: "https://audius.co/",
    submissionUrl: "https://audius.co/",
    sourceUrl: "https://audius.co/",
    sourceType: "automation_run_227_public_research",
    country: "Global / decentralized artist streaming and fan platform",
    language: "en",
    genres: ["streaming", "creator-upload", "decentralized", "web3", "token-monetization", "fan-community", "free-first", "login-boundary", "wallet-boundary", "manual-review"],
    submissionMethod: "audius-decentralized-artist-upload-token-monetization-route",
    feeRequired: false,
    feeAmount: "Free-first manual route. Public source material describes Audius as a music platform where artists can post content and earn AUDIO tokens; no up-front music submission fee was verified in public source material.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for creator account/session, possible wallet/token exposure, rights ownership, upload metadata, content policy, payout/token choices, genre/community fit and platform terms. No account was created and no content was uploaded.",
    notes: "Public source material describes Audius as a music platform with millions of monthly listeners, hundreds of thousands of artists and over one million tracks as of 2022, where artists can post content and earn AUDIO tokens; the official Audius site exposes a JavaScript app boundary."
  },
  {
    name: "Marmoset Independent Artist Sync Licensing Representation Route",
    websiteUrl: "https://www.marmosetmusic.com/",
    submissionUrl: "https://www.marmosetmusic.com/contact",
    sourceUrl: "https://www.marmosetmusic.com/",
    sourceType: "automation_run_227_public_research",
    country: "United States / global sync licensing agency",
    language: "en",
    genres: ["sync-licensing", "music-licensing", "artist-representation", "independent-artists", "bands", "labels", "contact-route", "manual-review", "paid-commercial-licensing"],
    submissionMethod: "marmoset-independent-artist-sync-licensing-representation-route",
    feeRequired: false,
    feeAmount: "Manual commercial-licensing/contact route. Official/public pages expose a licensing agency and contact/login routes, but no public artist auto-submit fee or open self-serve submission form was verified.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required because public sources identify Marmoset as a licensing agency representing emerging and independent artists, but the observed official pages expose licensing/contact/login surfaces rather than a self-serve artist submission form. Manual outreach/roster-fit review is required; no contact form or outbound message was sent.",
    notes: "Public source material says Marmoset represents vintage, emerging and independent artists, bands and labels for licensing; the official site exposes Browse/Login, music licensing resources, a contact route, a physical HQ, phone and licensing/download interfaces for catalog users."
  }
];