import type { PlatformInput } from '../models/types.js';

export const run215SeedPlatforms: PlatformInput[] = [
  {
    name: "WXPN Philadelphia EPK Download Link Airplay Local Show Route",
    websiteUrl: "https://xpn.org/",
    submissionUrl: "https://xpn.org/contact/",
    sourceUrl: "https://xpn.org/contact/",
    sourceType: "automation_run_215_public_research",
    country: "United States / Philadelphia public AAA and local music radio",
    language: "en",
    genres: ["public-radio", "aaa-radio", "local-music", "independent", "electronic", "dub", "reggae", "world", "digital-download", "epk", "manual-review"],
    submissionMethod: "wxpn-philadelphia-epk-download-link-airplay-local-show-route",
    feeRequired: false,
    feeAmount: "Free-first/manual airplay consideration route. Official WXPN contact guidance asks artists to email an EPK with a digital download link for airplay consideration and gives a Local Show route for WAV/high-quality MP3 links; no payment requirement was observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for EPK completeness, download-link access, WAV/high-quality MP3 selection, local-show versus general rotation routing, clean-edit status, bio/show info and no-confirmation/no-guarantee expectations. No email was sent and no file was transferred.",
    notes: "Official WXPN homepage shows 2026 music-news activity; official contact page exposes music submission routes for airplay and The Local Show using email links and downloadable music assets. Queued manual because assets and editorial fit must be approved by the artist owner."
  },
  {
    name: "FBi Radio Sydney Digital Stream Download Music Submission Route",
    websiteUrl: "https://www.fbi.radio/",
    submissionUrl: "https://www.fbi.radio/pages/music-submissions",
    sourceUrl: "https://www.fbi.radio/pages/music-submissions",
    sourceType: "automation_run_215_public_research",
    country: "Australia / Sydney independent youth and community radio",
    language: "en",
    genres: ["community-radio", "independent-radio", "australian-music", "sydney-music", "electronic", "dance", "hip-hop", "world", "digital-submission", "manual-review"],
    submissionMethod: "fbi-radio-sydney-digital-stream-download-music-submission-route",
    feeRequired: false,
    feeAmount: "Free-first/manual digital submission route. Official FBi guidance accepts music by public music-submission email with stream and high-quality download links; optional paid promotional campaign/partnership routes were observed separately and were not initiated.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for Australian/Sydney relevance, clear subject line, stream link, 320kbps MP3/WAV download link, non-expiring file access, bio/press photo/gig details, direct-show versus general servicing choice and premiere/interview/gig-guide boundaries. No email was sent and no files were transferred.",
    notes: "Official FBi pages show July 2026 station/articles activity and a dedicated music@fbiradio.com route with digital-only requirements, Wednesday audition timing and no-CD policy. Logged as public source-verified business/music email, not SMTP-verified."
  },
  {
    name: "PBS 106.7FM Melbourne Digital CAPTCHA Form Physical Music Submission Route",
    websiteUrl: "https://www.pbsfm.org.au/",
    submissionUrl: "https://www.pbsfm.org.au/submitmusic",
    sourceUrl: "https://www.pbsfm.org.au/submitmusic",
    sourceType: "automation_run_215_public_research",
    country: "Australia / Melbourne specialist community music radio",
    language: "en",
    genres: ["community-radio", "specialist-radio", "underrepresented-music", "local-music", "international", "electronic", "dub", "reggae", "world", "digital-form", "physical-submission", "captcha", "manual-review"],
    submissionMethod: "pbs-1067fm-melbourne-digital-captcha-form-physical-music-submission-route",
    feeRequired: false,
    feeAmount: "Free-first/manual public form and physical submission route. Official PBS guidance prefers the digital form but also accepts CDs/vinyl at postal/in-person addresses; no payment requirement was observed.",
    loginRequired: false,
    captchaDetected: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required because the public music form includes a CAPTCHA/human-spam test and requires personal/contact fields, country/location, stream link, high-quality download, bio/social/gig details and optional newsletter choice. Physical delivery also requires copies/press-bio decisions. No form was submitted, no CAPTCHA was handled and no files or packages were transferred.",
    notes: "Official PBS homepage shows current July 2026 feature/interview/event activity; official Submit Your Music page welcomes local and international acts, captures digital form fields and provides CD/vinyl mailing and in-person delivery instructions. Marked needs_manual_review due CAPTCHA and asset handling."
  },
  {
    name: "Triple R Melbourne Stream Download Physical Music Submission Route",
    websiteUrl: "https://www.rrr.org.au/",
    submissionUrl: "https://www.rrr.org.au/get-involved/submit-music",
    sourceUrl: "https://www.rrr.org.au/get-involved/submit-music",
    sourceType: "automation_run_215_public_research",
    country: "Australia / Melbourne independent community radio",
    language: "en",
    genres: ["community-radio", "independent-radio", "non-playlisted", "specialist-radio", "electronic", "dub", "reggae", "world", "hip-hop", "digital-download", "physical-submission", "manual-review"],
    submissionMethod: "triple-r-melbourne-stream-download-physical-music-submission-route",
    feeRequired: false,
    feeAmount: "Free-first/manual station-service route. Official Triple R guidance accepts station-service email with stream and high-quality download links, direct presenter servicing and physical CD/LP/cassette delivery; no payment requirement was observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for presenter-versus-station routing, no-login stream link, 320kbps MP3/WAV download link, file naming, bio/gig details, no-large-attachment boundary, physical package preparation and presenter-discretion expectations. No email was sent and no physical package was prepared.",
    notes: "Official Triple R pages show current July 2026 live/event/audio activity and a Submit Music route listing music@rrr.org.au plus direct-program and physical postal alternatives. Logged as public source-verified music submission email, not SMTP-verified."
  },
  {
    name: "KUTX Austin WAV Download Link Music Director Airplay Route",
    websiteUrl: "https://kutx.org/",
    submissionUrl: "https://kutx.org/submit-your-music/",
    sourceUrl: "https://kutx.org/submit-your-music/",
    sourceType: "automation_run_215_public_research",
    country: "United States / Austin public music radio",
    language: "en",
    genres: ["public-radio", "aaa-radio", "austin-music", "texas-music", "electronic", "hip-hop", "latin", "jazz", "indie", "wav-download", "manual-review"],
    submissionMethod: "kutx-austin-wav-download-link-music-director-airplay-route",
    feeRequired: false,
    feeAmount: "Free-first/manual music-director route. Official KUTX guidance asks artists to email the Music Director with a stream link, WAV download link and release context; optional event/promotion/sponsorship paths include form and paid sponsorship boundaries but were not initiated.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for final-mastered/new-release eligibility, radio-edit/FCC-clean status, stream link, WAV download link, Austin/Texas subject flag, bio/release/tour/collab notes, top-pick selection and optional specialty-show/event route decisions. No email, Qualtrics form, paid sponsorship or file transfer was initiated.",
    notes: "Official KUTX homepage shows July 2026 current programming and music coverage; official Submit Your Music page exposes music@kutx.org and specialty-show/event routes. Logged as source-verified public music submission email and manual because event/promo routes include forms or paid sponsorship boundaries."
  }
];