import type { PlatformInput } from '../models/types.js';

export const run246SeedPlatforms: PlatformInput[] = [
  {
    "name": "Musosoup Free Intake Paid Coverage Campaign Submission Route",
    "websiteUrl": "https://musosoup.com/",
    "submissionUrl": "https://app.musosoup.com/",
    "sourceUrl": "https://musosoup.com/",
    "sourceType": "automation_run_246_public_research",
    "country": "Global / UK-based independent artist music promotion and curator marketplace route",
    "language": "en",
    "genres": [
      "musosoup",
      "music-promotion",
      "spotify-playlisting",
      "blogs",
      "press",
      "radio",
      "reviews",
      "interviews",
      "curator-marketplace",
      "free-first",
      "paid-campaign",
      "login-required",
      "payment-boundary",
      "manual-review"
    ],
    "submissionMethod": "musosoup-free-intake-paid-coverage-campaign-submission-route",
    "feeRequired": true,
    "feeAmount": "Official page says artists can upload or link music for free and pay only to activate a campaign, with pricing starting at £42 and free coverage options available.",
    "loginRequired": true,
    "captchaDetected": false,
    "paymentRequired": true,
    "manualReviewRequired": true,
    "manualReviewReason": "Owner review required for artist account creation, campaign activation fee, audio/link upload, release timing, curator offers, paid/free coverage choices, marketplace add-ons, rights, metadata and campaign reporting. No account was created, no campaign was activated and no music was uploaded.",
    "notes": "Official Musosoup page exposes Submit Music / app.musosoup.com route, states artists can submit unreleased or released music, upload/link a single EP or album, receive review/interview/playlist/radio offers, and shows 2026 blog activity plus 85k artists, 3k curators and 120 countries. Public business contact route is a Contact us page; no usable public plain music-submission email was observed."
  },
  {
    "name": "DailyPlaylists Free Spotify Playlist Submission Marketplace Route",
    "websiteUrl": "https://dailyplaylists.com/",
    "submissionUrl": "https://dailyplaylists.com/",
    "sourceUrl": "https://dailyplaylists.com/",
    "sourceType": "automation_run_246_public_research",
    "country": "Global / Spotify playlist submission marketplace for independent artists and curators",
    "language": "en",
    "genres": [
      "dailyplaylists",
      "spotify-playlist-submission",
      "playlist-marketplace",
      "artist-pitching",
      "curator-network",
      "track-explorer",
      "premium-credits",
      "free-first",
      "freemium",
      "business-email-observed",
      "login-required",
      "payment-boundary",
      "manual-review"
    ],
    "submissionMethod": "dailyplaylists-free-spotify-playlist-submission-marketplace-route",
    "feeRequired": false,
    "feeAmount": "Official page states the Standard Tier lets artists get started and submit music for free; Premium Credits and Professional tools are paid or plan-boundary items requiring owner approval.",
    "loginRequired": true,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "Owner review required for sign-in, Spotify track lookup/link paste, curator targeting, standard submission limits, premium credit use, Professional tier tools, community feedback, playlist matching and rights/metadata checks. No sign-in was used and no song was submitted.",
    "notes": "Official DailyPlaylists page exposes Submit a Song, Submit a Playlist, pricing, Standard Tier free submissions, a marketplace of 18,000+ playlists, +75M total submissions, +500k artists, +100K premium placements and public business email info@dailyplaylists.com. Email was observed but not used as a direct music-submission address; no deliverability probing was performed."
  },
  {
    "name": "SoundCampaign Paid Spotify TikTok Curator Review Campaign Route",
    "websiteUrl": "https://soundcamps.com/",
    "submissionUrl": "https://app.soundcamps.com/",
    "sourceUrl": "https://soundcamps.com/",
    "sourceType": "automation_run_246_public_research",
    "country": "Global / paid Spotify playlist and TikTok creator music promotion campaign route",
    "language": "en",
    "genres": [
      "soundcampaign",
      "spotify-promotion",
      "playlist-consideration",
      "tiktok-music-promotion",
      "creator-campaigns",
      "curator-feedback",
      "paid-campaign",
      "pricing-boundary",
      "login-required",
      "cookie-boundary",
      "manual-review"
    ],
    "submissionMethod": "soundcampaign-paid-spotify-tiktok-curator-review-campaign-route",
    "feeRequired": true,
    "feeAmount": "Official page describes paid campaigns where artists set a budget and pay when playlist curators review the track or when TikTok creator output is accepted; pricing details sit behind campaign/pricing flows.",
    "loginRequired": true,
    "captchaDetected": false,
    "paymentRequired": true,
    "manualReviewRequired": true,
    "manualReviewReason": "Owner review required for sign-in, campaign budget, Spotify/TikTok targeting, track submission, curator/creator review workflow, acceptance/rejection of creator videos, campaign analytics, no-placement guarantee language and payment authorization. No account was created and no campaign was started.",
    "notes": "Official SoundCampaign page exposes Get Started / app.soundcamps.com, Spotify Promotion, TikTok Music Promotion, Meta Ads for Spotify, pricing/help links, Trustpilot review count, policy language that curators are compensated for reviews not placements, and cookie management. Public music-submission email was not observed."
  },
  {
    "name": "Jamendo Artist Services Licensing In Store Promotion Upload Route",
    "websiteUrl": "https://artists.jamendo.com/",
    "submissionUrl": "https://artists.jamendo.com/",
    "sourceUrl": "https://artists.jamendo.com/",
    "sourceType": "automation_run_246_public_research",
    "country": "Global / Luxembourg-based independent artist services, music discovery and licensing route",
    "language": "en",
    "genres": [
      "jamendo",
      "artist-services",
      "music-upload",
      "licensing",
      "sync-licensing",
      "in-store-placement",
      "content-id",
      "promotion",
      "independent-artists",
      "free-first",
      "login-required",
      "rights-boundary",
      "manual-review"
    ],
    "submissionMethod": "jamendo-artist-services-licensing-in-store-promotion-upload-route",
    "feeRequired": false,
    "feeAmount": "Official artist-services page frames Jamendo as a one-stop space for DIY musicians; licensing, in-store placement, Content ID revenue share and rights/commercial terms require owner review before use.",
    "loginRequired": true,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "Owner review required for sign-in, artist-service terms, music upload, rights ownership, collecting-society/royalty constraints, licensing opt-in, in-store placement, Content ID monetization, release promotion and payout setup. No account was created and no tracks were uploaded.",
    "notes": "Official Jamendo Artists page exposes Sign In / Start Now, Jamendo Music audience reach, Licensing for movies/video games/TV/radio/online commercials, In-Store placement in 20,000+ commercial spaces, Content ID monetization and release-promotion language. Public music-submission email was not observed."
  },
  {
    "name": "Bandcamp Direct To Fan Artist Release Upload Route",
    "websiteUrl": "https://bandcamp.com/artists",
    "submissionUrl": "https://bandcamp.com/artists",
    "sourceUrl": "https://bandcamp.com/artists",
    "sourceType": "automation_run_246_public_research",
    "country": "Global / US-based direct-to-fan artist storefront, release upload and discovery route",
    "language": "en",
    "genres": [
      "bandcamp",
      "direct-to-fan",
      "artist-storefront",
      "digital-music",
      "merch",
      "release-upload",
      "bandcamp-daily",
      "fan-community",
      "free-artist-account",
      "revenue-share",
      "login-required",
      "manual-review"
    ],
    "submissionMethod": "bandcamp-direct-to-fan-artist-release-upload-route",
    "feeRequired": false,
    "feeAmount": "Official Bandcamp for Artists page says artist accounts are free; platform revenue share applies to digital music and merch sales, and Bandcamp Pro is a paid optional tier.",
    "loginRequired": true,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "Owner review required for desktop sign-up, artist profile/storefront, release upload, pricing, merch settings, PayPal payout setup, revenue share, Bandcamp Pro option, AI-content policy alignment, fan communication and editorial/discovery expectations. No account was created and no release or merch was uploaded.",
    "notes": "Official Bandcamp for Artists page exposes Sign up / Log in, artist accounts, direct-to-fan store, release notifications, fan messaging, Bandcamp Daily coverage, pricing controls, free artist accounts, revenue-share terms, paid Pro tier and desktop signup boundary. Public music-submission email was not observed."
  }
];
