import type { PlatformInput } from '../models/types.js';

export const run217BaseSeedPlatforms: PlatformInput[] = [
  {
    name: "Fresh On The Net Weekly Listening Post SoundCloud Form Route",
    websiteUrl: "https://freshonthenet.co.uk/",
    submissionUrl: "https://freshonthenet.co.uk/submit/",
    sourceUrl: "https://freshonthenet.co.uk/submit/",
    sourceType: "automation_run_217_public_research",
    country: "United Kingdom / global independent music blog and Listening Post route",
    language: "en",
    genres: ["music-blog", "listening-post", "independent", "electronic", "hip-hop", "reggae", "pop", "soundcloud-link", "public-form", "manual-review"],
    submissionMethod: "fresh-on-the-net-weekly-listening-post-soundcloud-form-route",
    feeRequired: false,
    feeAmount: "Free-first/manual editorial route; public SoundCloud dropbox, no payment observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Weekly dropbox timing, 200-track cap, SoundCloud availability, repeat/remix rules, AI-content exclusion and optional clean-radio-edit route require owner approval.",
    notes: "Official Fresh On The Net submit page showed public form fields, one-track-per-week rules and July 2026 activity."
  },
  {
    name: "Stereofox SubmitHub Groover Human-Curated Playlist Blog Route",
    websiteUrl: "https://www.stereofox.com/",
    submissionUrl: "https://www.stereofox.com/contact/",
    sourceUrl: "https://www.stereofox.com/contact/",
    sourceType: "automation_run_217_public_research",
    country: "Global / online human-curated music blog and playlist outlet",
    language: "en",
    genres: ["music-blog", "playlist", "submithub", "groover", "electronic", "chill-beats", "indie", "rnb", "hip-hop", "manual-review"],
    submissionMethod: "stereofox-submithub-groover-human-curated-playlist-blog-route",
    feeRequired: false,
    feeAmount: "Freemium/manual third-party route through SubmitHub or Groover; credits/payment may apply.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "SubmitHub/Groover choice, account/session, possible credits/payment, track link, playlist/blog fit and metadata require owner approval.",
    notes: "Official Stereofox contact page routes music submissions to SubmitHub or Groover and rejects email/Discord submissions."
  },
  {
    name: "A&R Factory Free Paid Blog Review Public Form Route",
    websiteUrl: "https://www.anrfactory.com/",
    submissionUrl: "https://www.anrfactory.com/submit-demo/",
    sourceUrl: "https://www.anrfactory.com/submit-demo/",
    sourceType: "automation_run_217_public_research",
    country: "United Kingdom / global independent A&R music blog",
    language: "en",
    genres: ["music-blog", "a-and-r", "public-form", "electronic", "dance-edm", "drum-and-bass", "hip-hop", "reggae", "world", "manual-review"],
    submissionMethod: "anr-factory-free-paid-blog-review-public-form-route",
    feeRequired: false,
    feeAmount: "Free-first/manual public form with paid Standard and Premium options visible.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Free versus paid package, track link, release date/status, socials, artwork, EPK/bio and payment boundary require owner approval.",
    notes: "Official A&R Factory pages showed July 2026 posts and a public submit-demo form with free and paid options."
  },
  {
    name: "CKUA Alberta Digital Link Music Committee Airplay Route",
    websiteUrl: "https://ckua.com/",
    submissionUrl: "https://ckua.com/our-story/library/getting-airplay/",
    sourceUrl: "https://ckua.com/our-story/library/getting-airplay/",
    sourceType: "automation_run_217_public_research",
    country: "Canada / Alberta donor-powered radio network",
    language: "en",
    genres: ["radio-airplay", "music-committee", "canadian-radio", "alberta", "streaming-link", "download-link", "mp3-320", "manual-review"],
    submissionMethod: "ckua-alberta-digital-link-music-committee-airplay-route",
    feeRequired: false,
    feeAmount: "Free-first/manual digital-link radio route; no payment observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Canadian/Alberta fit, clean edits, one-sheet, stream/download links, no-zip handling and Music Committee review require owner approval.",
    notes: "Official CKUA pages showed 2026 activity, Submit Your Music and Getting Airplay guidance."
  },
  {
    name: "triple j Unearthed Australian Artist Account Upload Route",
    websiteUrl: "https://www.abc.net.au/triplejunearthed",
    submissionUrl: "https://www.abc.net.au/triplejunearthed",
    sourceUrl: "https://help.abc.net.au/hc/en-us/articles/360001154256-How-do-I-upload-my-music-to-triple-j-Unearthed",
    sourceType: "automation_run_217_public_research",
    country: "Australia / ABC triple j Unearthed independent artist discovery platform",
    language: "en",
    genres: ["artist-upload", "digital-radio", "independent", "australian-music", "electronic", "hip-hop", "rnb", "pop", "manual-review"],
    submissionMethod: "triple-j-unearthed-australian-artist-account-upload-route",
    feeRequired: false,
    feeAmount: "Free/manual account-upload route; no payment observed.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Australian citizen/resident eligibility, ABC account/session, original rights, no covers/remixes, audio upload and approval require owner review.",
    notes: "Official triple j Unearthed/ABC Help guidance requires ABC account, Unearthed profile and team approval before publication."
  }
];
