import type { PlatformInput } from '../models/types.js';

export const run216BaseSeedPlatforms: PlatformInput[] = [
  {
    name: "CISM 89.3 FM Montreal Digital Album EP Music Committee Route",
    websiteUrl: "https://cism893.ca/",
    submissionUrl: "https://cism893.ca/soumettre-un-album",
    sourceUrl: "https://cism893.ca/soumettre-un-album",
    sourceType: "automation_run_216_public_research",
    country: "Canada / Montreal francophone campus and community radio",
    language: "fr",
    genres: ["campus-radio", "community-radio", "francophone", "local-music", "independent", "electro", "hip-hop", "global-music", "album-ep", "digital-transfer", "manual-review"],
    submissionMethod: "cism-893-fm-montreal-digital-album-ep-music-committee-route",
    feeRequired: false,
    feeAmount: "Free-first/manual radio-submission route. Official CISM guidance accepts digital submissions by transfer/cloud link in 320kbps MP3 with metadata and no payment requirement was observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for album/EP versus single eligibility, francophone/local fit, weekly music-committee expectations, transfer-link access, 320kbps MP3 metadata, clean/radio-ready status and whether to avoid the discouraged physical-copy route. No email was sent and no files were transferred.",
    notes: "Official CISM pages show current 2026 activity and a public Soumettre un album route. The route prioritizes local/francophone music, accepts EPs/albums in French or English, considers singles only in French, and routes digital submissions to musique@cism893.ca."
  },
  {
    name: "Obscure Sound SubmitHub MusoSoup Direct Email Indie Blog Route",
    websiteUrl: "https://www.obscuresound.com/",
    submissionUrl: "https://www.obscuresound.com/about/contact/",
    sourceUrl: "https://www.obscuresound.com/about/contact/",
    sourceType: "automation_run_216_public_research",
    country: "United States / global independent music blog and playlist outlet",
    language: "en",
    genres: ["music-blog", "indie", "electronic", "ambient", "alt-rb", "hip-hop", "dream-pop", "folk", "submithub", "musosoup", "direct-email", "manual-review"],
    submissionMethod: "obscure-sound-submithub-musosoup-direct-email-indie-blog-route",
    feeRequired: false,
    feeAmount: "Free-first/manual direct-email route observed. SubmitHub, SubmitHub Marketplace, MusoSoup and optional PR-campaign services create app/login/credit/payment boundaries; no payment or campaign workflow was initiated.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for choosing SubmitHub, SubmitHub Marketplace, MusoSoup or direct email, possible third-party account/credit/payment use, streaming link, press photo, concise bio, release context, genre fit and optional PR-campaign spend boundary. No email, third-party submission or payment was initiated.",
    notes: "Official Obscure Sound pages show July 2026 music coverage and public submission guidance. The direct submission email is rendered as a protected/non-plaintext link in the tool output and was not decoded or guessed."
  },
  {
    name: "Playlist Push Spotify TikTok Paid Playlist Promotion Route",
    websiteUrl: "https://playlistpush.com/",
    submissionUrl: "https://playlistpush.com/",
    sourceUrl: "https://playlistpush.com/",
    sourceType: "automation_run_216_public_research",
    country: "Global / Spotify playlist and TikTok creator promotion platform",
    language: "en",
    genres: ["spotify-promotion", "playlist-curators", "tiktok-promotion", "paid-campaign", "independent", "electronic", "dance", "hip-hop", "reggae", "manual-review"],
    submissionMethod: "playlist-push-spotify-tiktok-paid-playlist-promotion-route",
    feeRequired: true,
    feeAmount: "Paid/manual campaign route. Official Playlist Push pages expose artist account, sign-in, pricing, playlist-submission and TikTok promotion routes; budget/payment and campaign settings require owner approval.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for account/session use, campaign budget, Spotify-versus-TikTok goal, track eligibility, curator/creator targeting, written-feedback expectations, creator brief, spend authorization and policy fit. No account was created, no login was used and no campaign was started.",
    notes: "Official Playlist Push pages describe pitching songs to independent Spotify playlist curators, verified curator review, artist dashboards, TikTok creator campaigns and pricing/app boundaries. Marked manual because all campaign and spend controls are owner-controlled."
  },
  {
    name: "SoundCampaign Spotify TikTok Curator Review Paid Promotion Route",
    websiteUrl: "https://soundcamps.com/",
    submissionUrl: "https://soundcamps.com/",
    sourceUrl: "https://soundcamps.com/",
    sourceType: "automation_run_216_public_research",
    country: "Global / Spotify playlist and TikTok music promotion platform",
    language: "en",
    genres: ["spotify-promotion", "playlist-curators", "tiktok-creators", "paid-campaign", "curator-feedback", "electronic", "dance", "hip-hop", "world", "manual-review"],
    submissionMethod: "soundcampaign-spotify-tiktok-curator-review-paid-promotion-route",
    feeRequired: true,
    feeAmount: "Paid/manual campaign route. Official SoundCampaign pages expose Get Started/Start Now app routes and budget/pricing language where curators are compensated for reviews; no payment was initiated.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for artist account/session, campaign type, track selection, playlist/TikTok fit, campaign budget, no-guaranteed-placement policy acknowledgement, curator-feedback expectations and spend authorization. No account, login, submission or payment workflow was initiated.",
    notes: "Official SoundCampaign pages describe Spotify playlist promotion, TikTok music promotion, automatic track-to-playlist matching, feedback from curators, budget return rules and Spotify-policy alignment. Marked manual because it is an app/payment-bound promotion route."
  },
  {
    name: "Feature.fm Free Music Marketing Release Link PreSave Route",
    websiteUrl: "https://feature.fm/",
    submissionUrl: "https://feature.fm/",
    sourceUrl: "https://feature.fm/",
    sourceType: "automation_run_216_public_research",
    country: "Global / music marketing and release-link platform",
    language: "en",
    genres: ["music-marketing", "release-link", "pre-save", "bio-link", "fan-management", "analytics", "artist-tools", "freemium", "manual-review"],
    submissionMethod: "featurefm-free-music-marketing-release-link-presave-route",
    feeRequired: false,
    feeAmount: "Free-first/manual artist-marketing route. Official Feature.fm pages expose Start for free, login/app access, release links, pre-save links, future-save links, contest/unlock pages and business-scale marketing tools; paid plan status was not activated.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for account/session use, release-link or pre-save campaign choice, DSP links, fan-data collection, cookie/privacy settings, artwork/metadata, contest/unlock conditions and marketing-goal fit. No account was created, no login was used and no fan-data or campaign workflow was started.",
    notes: "Official Feature.fm pages show a free-start route, artist bio links, release links, pre-save links, future-save tools, contest/unlock pages, fan-base management and business marketing features. Queued as manual because it controls artist-facing campaign assets and fan-data collection."
  }
];
