import type { PlatformInput } from '../models/types.js';

export const run265BaseSeedPlatforms: PlatformInput[] = [
  {"name":"WFUV Public Radio Music Submission Contact Route","websiteUrl":"https://wfuv.org/","submissionUrl":"https://wfuv.org/contact","sourceUrl":"https://wfuv.org/contact","sourceType":"automation_run_265_public_research","country":"United States / New York public radio and music discovery contact route","language":"en","genres":["wfuv","public-radio","radio-submission","aaa-radio","indie","roots","new-york","manual-review"],"submissionMethod":"wfuv-public-radio-music-submission-contact-route","feeRequired":false,"feeAmount":"No public submission fee confirmed; station contact/editorial review required.","loginRequired":false,"captchaDetected":false,"paymentRequired":false,"manualReviewRequired":true,"manualReviewReason":"Owner review required before using station contact forms, sending track links, metadata, artist bio, release notes or contact details. No email or form was sent.","notes":"Public WFUV contact route queued for manual radio submission review. No business email was used or probed."},
  {"name":"WXPN Public Radio Submit Music Contact Route","websiteUrl":"https://xpn.org/","submissionUrl":"https://xpn.org/contact/","sourceUrl":"https://xpn.org/contact/","sourceType":"automation_run_265_public_research","country":"United States / Philadelphia public radio and music discovery contact route","language":"en","genres":["wxpn","xpn","public-radio","radio-submission","indie","americana","philadelphia","manual-review"],"submissionMethod":"wxpn-public-radio-submit-music-contact-route","feeRequired":false,"feeAmount":"No public submission fee confirmed; station contact/editorial review required.","loginRequired":false,"captchaDetected":false,"paymentRequired":false,"manualReviewRequired":true,"manualReviewReason":"Owner review required before contacting station staff, using forms, sending track links, EPK, metadata or release notes. No contact action was taken.","notes":"Public WXPN contact route queued for manual review only."},
  {"name":"KDHX Community Radio Music Submission Contact Route","websiteUrl":"https://kdhx.org/","submissionUrl":"https://kdhx.org/contact/","sourceUrl":"https://kdhx.org/contact/","sourceType":"automation_run_265_public_research","country":"United States / St. Louis community radio contact and music discovery route","language":"en","genres":["kdhx","community-radio","radio-submission","roots","indie","americana","st-louis","manual-review"],"submissionMethod":"kdhx-community-radio-music-submission-contact-route","feeRequired":false,"feeAmount":"No public submission fee confirmed; station contact and programming review required.","loginRequired":false,"captchaDetected":false,"paymentRequired":false,"manualReviewRequired":true,"manualReviewReason":"Owner review required before using contact forms, sending music links, release metadata, EPK, images or press copy. No message was sent.","notes":"Public KDHX contact route queued for manual review."},
  {"name":"KBOO Community Radio Music Submission Contact Route","websiteUrl":"https://kboo.fm/","submissionUrl":"https://kboo.fm/contact","sourceUrl":"https://kboo.fm/contact","sourceType":"automation_run_265_public_research","country":"United States / Portland community radio contact route","language":"en","genres":["kboo","community-radio","radio-submission","independent-music","world-music","portland","manual-review"],"submissionMethod":"kboo-community-radio-music-submission-contact-route","feeRequired":false,"feeAmount":"No public submission fee confirmed; station contact/programming review required.","loginRequired":false,"captchaDetected":false,"paymentRequired":false,"manualReviewRequired":true,"manualReviewReason":"Owner review required before using contact forms, sending track links, metadata, EPK, physical/digital delivery details or press copy. No form or email was sent.","notes":"Public KBOO contact route queued for manual radio review."},
  {"name":"WERS 88.9 Public Radio Music Submission Contact Route","websiteUrl":"https://wers.org/","submissionUrl":"https://wers.org/contact/","sourceUrl":"https://wers.org/contact/","sourceType":"automation_run_265_public_research","country":"United States / Boston college/public radio music contact route","language":"en","genres":["wers","college-radio","public-radio","radio-submission","indie","alternative","boston","manual-review"],"submissionMethod":"wers-public-radio-music-submission-contact-route","feeRequired":false,"feeAmount":"No public submission fee confirmed; station contact/editorial review required.","loginRequired":false,"captchaDetected":false,"paymentRequired":false,"manualReviewRequired":true,"manualReviewReason":"Owner review required before contacting music/programming staff, using forms, sending track links, EPK, artist identity or release metadata. No contact action was taken.","notes":"Public WERS contact route queued for manual review."}
];
