import type { PlatformInput } from '../models/types.js';

export const run212BaseSeedPlatforms: PlatformInput[] = [
  {
    name: "Groover Global Curator Radio Playlist Paid Campaign Route",
    websiteUrl: "https://groover.co/",
    submissionUrl: "https://groover.co/en/",
    sourceUrl: "https://groover.co/en/",
    sourceType: "automation_run_212_public_research",
    country: "Global / France-based music promotion marketplace",
    language: "en",
    genres: ["music-promotion", "playlist-pitching", "radio", "labels", "blogs", "electronic", "reggae", "world", "hip-hop", "independent", "paid-campaign", "manual-review"],
    submissionMethod: "groover-global-curator-radio-playlist-paid-campaign-route",
    feeRequired: true,
    feeAmount: "Paid/manual campaign route. Official Groover guidance says artists choose curators/pros and spend Grooviz credits; pricing is shown as 2 Grooviz = 2 EUR and campaigns depend on selected pros.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for account creation, track link choice, release status, pitch text, curator/radio/label filtering, Grooviz credit purchase, campaign spend cap, rights/metadata and style-fit review. No account was created, no campaign was validated, no credits were purchased and no track link was submitted.",
    notes: "Official Groover pages validate an authorized submission workflow for artists to send music to active curators, radios, labels, playlists and other music pros with guaranteed feedback windows; queued manual because it is an authenticated paid campaign workflow."
  },
  {
    name: "Music Xray Song To Opportunity Industry Pro Paid Submission Route",
    websiteUrl: "https://www.musicxray.com/",
    submissionUrl: "https://www.musicxray.com/S2O",
    sourceUrl: "https://www.musicxray.com/S2O",
    sourceType: "automation_run_212_public_research",
    country: "Global / United States music-tech A&R platform",
    language: "en",
    genres: ["a-and-r", "song-to-opportunity", "industry-pros", "labels", "publishers", "songwriting", "electronic", "reggae", "world", "hip-hop", "independent", "paid-submission", "manual-review"],
    submissionMethod: "music-xray-song-to-opportunity-industry-pro-paid-submission-route",
    feeRequired: true,
    feeAmount: "Paid/manual song-to-opportunity route. Publicly indexed source material describes Music Xray as an active A&R platform where musicians pay submission fees to send songs to industry professionals in exchange for a guaranteed listen and response.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for account/app access, opportunity selection, paid submission fee, track ownership, release/unreleased status, genre targeting, pitch copy, rights and metadata. No login was used, no fee was paid and no song was uploaded or submitted.",
    notes: "Music Xray official pages were reachable only as a JavaScript/empty-content boundary in the tool, so route details were validated from public indexed source material plus the official domain. Queued manual because payment and opportunity-specific submission rules must be reviewed by the artist."
  },
  {
    name: "Radiooooo Global Map Curated Upload Music Discovery Route",
    websiteUrl: "https://app.radiooooo.com/",
    submissionUrl: "https://app.radiooooo.com/",
    sourceUrl: "https://app.radiooooo.com/",
    sourceType: "automation_run_212_public_research",
    country: "Global / France-based music discovery app",
    language: "en/fr",
    genres: ["music-discovery", "curated-map", "global-music", "world", "reggae", "electronic", "archive", "playlist", "freemium", "manual-review"],
    submissionMethod: "radiooooo-global-map-curated-upload-music-discovery-route",
    feeRequired: true,
    feeAmount: "Freemium/manual app route. Public source material says users can upload songs or tracks for curation, and the service has a free trial followed by subscription access.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for JavaScript app/account boundary, upload eligibility, country/decade tagging, curation suitability, rights, subscription/trial terms and metadata. No account was created, no trial/subscription was started and no music was uploaded.",
    notes: "Official Radiooooo app exposed a JavaScript boundary to the tool; public source material confirms user uploads are curated by DJs/producers and selected tracks appear on a global map. Queued manual for authorized app-only upload review."
  },
  {
    name: "TAXI Independent A&R Industry Listings Paid Member Submission Route",
    websiteUrl: "https://www.taxi.com/",
    submissionUrl: "https://www.taxi.com/industry",
    sourceUrl: "https://www.taxi.com/industry",
    sourceType: "automation_run_212_public_research",
    country: "Global / United States independent A&R and licensing listings",
    language: "en",
    genres: ["a-and-r", "sync-licensing", "film-tv", "music-library", "publishers", "labels", "electronic", "hip-hop", "world", "reggae", "paid-membership", "manual-review"],
    submissionMethod: "taxi-independent-ar-industry-listings-paid-member-submission-route",
    feeRequired: true,
    feeAmount: "Paid/manual member route. Official TAXI terms list a 299.95 USD first-year membership fee, 199.95 USD renewal and 5 USD per-song submission fee; active listings show Join to submit / Members submit here boundaries.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for membership purchase, member login, opportunity-fit selection, song originality, no unauthorized samples, AI/release-status constraints, PRO/publishing status, lyric sheets, broadcast-quality files and per-song fee. No membership was purchased, no login was used and no material was submitted.",
    notes: "Official TAXI listings page shows dated 2026 opportunity listings across Electronic, Rap/Hip-Hop, World Music and many other categories; queued manual because it is a paid member submission workflow with legal/rightsholder declarations."
  },
  {
    name: "Soundplate Play Free Spotify Deezer Playlist Submission Route",
    websiteUrl: "https://play.soundplate.com/",
    submissionUrl: "https://play.soundplate.com/",
    sourceUrl: "https://play.soundplate.com/",
    sourceType: "automation_run_212_public_research",
    country: "Global / United Kingdom music technology and playlist-submission tool",
    language: "en",
    genres: ["spotify-playlists", "deezer-playlists", "independent-curators", "electronic", "house", "garage", "festival", "dance", "music-promotion", "free-first", "manual-review"],
    submissionMethod: "soundplate-play-free-spotify-deezer-playlist-submission-route",
    feeRequired: false,
    feeAmount: "Free-first/manual playlist route. Official Soundplate Play page says the service is free and lets artists submit music to Spotify and Deezer playlists by selecting relevant playlists.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for playlist relevance, Spotify/Deezer track link, anti-spam compliance, curator-specific form fields, genre matching, release timing and follow-up discipline. No playlist was selected, no form was submitted and no track link was delivered.",
    notes: "Official Soundplate Play page exposes playlist navigation and a free submission route to independent curators; queued manual because the platform explicitly warns to submit only relevant music and avoid spam."
  }
];
