import type { PlatformInput } from '../models/types.js';

export const run232SeedPlatforms: PlatformInput[] = [
  {
    name: "Amuse Self Service Distribution Artist Upload Licensing Route",
    websiteUrl: "https://www.amuse.io/",
    submissionUrl: "https://www.amuse.io/",
    sourceUrl: "https://www.amuse.io/",
    sourceType: "automation_run_232_public_research",
    country: "Sweden / global digital music distribution",
    language: "en",
    genres: ["digital-distribution", "artist-upload", "self-release", "major-dsp-delivery", "licensing", "artist-services", "subscription-tier-boundary", "royalty-advance-boundary", "ai-mastering-boundary", "login-session-app-boundary", "manual-review"],
    submissionMethod: "amuse-self-service-distribution-artist-upload-licensing-route",
    feeRequired: false,
    feeAmount: "Freemium/subscription-tier manual distribution route. Public source material describes Amuse self-service distribution with Artist, Artist Plus and Professional subscription tiers plus connected services.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for account/login, subscription plan selection, master rights, territory/store delivery, release metadata, artwork/audio upload, royalty-advance/AI-mastering options, licensing terms and payment boundaries. No account was created and no file was uploaded.",
    notes: "Amuse is described as a global music company for digital distribution, funding and artist services. Its self-service distribution lets independent artists release and monetize music through major streaming services, with subscription tiers and connected services such as royalty advances, AI mastering and performance insights. Recent July 2026 coverage also identifies Amuse as an independent-artist platform focused on transparent distribution and licensing/catalog support."
  },
  {
    name: "Labelcaster Independent Label Artist Royalty Split Distribution Route",
    websiteUrl: "https://labelcaster.com/",
    submissionUrl: "https://labelcaster.com/",
    sourceUrl: "https://labelcaster.com/",
    sourceType: "automation_run_232_public_research",
    country: "Sweden / worldwide music distribution platform",
    language: "en",
    genres: ["digital-distribution", "independent-labels", "artist-upload", "spotify-delivery", "apple-music-delivery", "youtube-music-delivery", "tiktok-delivery", "deezer-delivery", "roster-management", "royalty-splits", "login-session-app-boundary", "manual-review"],
    submissionMethod: "labelcaster-independent-label-artist-royalty-split-distribution-route",
    feeRequired: false,
    feeAmount: "Manual commercial distribution route. Public source material identifies Labelcaster as a worldwide online music distribution platform with royalty-split tooling; pricing/contract terms require owner review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for label/artist account setup, roster ownership, splits, DSP delivery terms, metadata/audio/artwork upload, contract/pricing/royalty accounting and app/session boundary. No account was created and no release was delivered.",
    notes: "Public source material describes Labelcaster as an online music distribution platform for independent labels and artists, with delivery to Spotify, Apple Music, YouTube Music, TikTok and Deezer plus artist-roster management and royalty-split tracking."
  },
  {
    name: "GYROstream Independent Artist Distribution Radio Playlisting Services Route",
    websiteUrl: "https://www.gyrostream.com/",
    submissionUrl: "https://www.gyrostream.com/",
    sourceUrl: "https://www.gyrostream.com/",
    sourceType: "automation_run_232_public_research",
    country: "Australia / global independent music distribution and artist services",
    language: "en",
    genres: ["digital-distribution", "independent-artists", "spotify-delivery", "apple-music-delivery", "royalty-collection", "radio-playlisting", "publicity", "digital-marketing", "social-media-marketing", "artist-services", "login-session-app-boundary", "payment-pricing-boundary", "manual-review"],
    submissionMethod: "gyrostream-independent-artist-distribution-radio-playlisting-services-route",
    feeRequired: true,
    feeAmount: "Paid/manual artist-services and distribution route. Public source material describes distribution plus publicity, radio playlisting, digital marketing and social-media support; exact pricing/workflow requires owner review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for account/session, artist eligibility, release ownership, DSP delivery, publicity/radio playlisting scope, marketing-service costs, royalty collection/payment setup and upload metadata. No account was created and no campaign/release was started.",
    notes: "GYROstream is described as an Australian digital music distribution platform founded in 2018, distributing to DSPs such as Spotify, Apple Music, Amazon Music, YouTube Music, Deezer, TIDAL, Meta and TikTok. Current public reporting says it helps independent artists with distribution, publicity, radio playlisting, digital marketing and social strategy, with international teams."
  },
  {
    name: "ONErpm OFFstep Emerging Artist Fixed Fee Distribution Upload Route",
    websiteUrl: "https://onerpm.com/",
    submissionUrl: "https://offstep.com/",
    sourceUrl: "https://onerpm.com/",
    sourceType: "automation_run_232_public_research",
    country: "United States / global music distribution and emerging artist upload route",
    language: "en",
    genres: ["digital-distribution", "emerging-artists", "offstep", "fixed-fee-distribution", "video-upload", "onerpm", "publishing", "label-services", "distribution-services", "login-session-app-boundary", "payment-pricing-boundary", "manual-review"],
    submissionMethod: "onerpm-offstep-emerging-artist-fixed-fee-distribution-upload-route",
    feeRequired: true,
    feeAmount: "Paid fixed-fee/manual distribution route. Public source material says ONErpm launched OFFstep for emerging artists where artists can release music and upload videos for a fixed fee.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for OFFstep/ONErpm account flow, fixed-fee payment, artist/release eligibility, DSP/video delivery, publishing/label-service boundaries, master rights, upload files and metadata. No account was created and no payment or upload was initiated.",
    notes: "Public source material describes ONErpm as a music distribution, publishing and label-services company with global offices. It launched OFFstep for emerging artists in 2023; for a fixed fee, artists can release music and upload videos through OFFstep."
  },
  {
    name: "Chartwin Royalty Free Artist Upload Contest Discovery Route",
    websiteUrl: "https://chartwin.io/",
    submissionUrl: "https://chartwin.io/",
    sourceUrl: "https://chartwin.io/",
    sourceType: "automation_run_232_public_research",
    country: "France / worldwide royalty-free music discovery and upload platform",
    language: "fr",
    genres: ["royalty-free-music", "artist-upload", "music-contests", "streaming-platform", "freemium", "free-plan", "ai-music-boundary", "pro-rights-boundary", "collecting-society-boundary", "login-session-app-boundary", "payment-pricing-boundary", "manual-review"],
    submissionMethod: "chartwin-royalty-free-artist-upload-contest-discovery-route",
    feeRequired: false,
    feeAmount: "Freemium manual upload/discovery route. Public source material describes a free plan with 3 music uploads per month and paid Premium/VIP tiers with higher upload limits and visibility features.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for account/login, royalty-free licensing implications, PRO/collecting-society restrictions, AI-generated/traditional-work disclosure, contest terms, upload limits, paid-tier boundaries and whether MarcsMusic catalogue can legally be submitted there. No account was created and no track was uploaded.",
    notes: "Public source material describes Chartwin as a worldwide royalty-free music streaming/distribution platform launched in 2026. It includes independent-artist uploads, contests and a freemium model: the free plan lists 3 uploads per month, while paid Premium/VIP tiers increase uploads and visibility. Because it operates outside collecting-society circuits and allows AI-generated or traditional uploads only under strict royalty-free conditions, this route is queued for manual legal/rights review."
  }
];
