import type { PlatformInput } from '../models/types.js';

export const run236SeedPlatforms: PlatformInput[] = [
  {
    name: "BBC Music Introducing Peel Upload Tool UK Artist Route",
    websiteUrl: "https://www.bbc.co.uk/introducing",
    submissionUrl: "https://www.bbc.co.uk/introducing",
    sourceUrl: "https://www.bbc.co.uk/introducing",
    sourceType: "automation_run_236_public_research",
    country: "United Kingdom / BBC local and national unsigned-artist radio discovery platform",
    language: "en",
    genres: ["bbc-radio", "bbc-introducing", "uk-unsigned", "under-the-radar", "artist-upload", "radio-airplay", "festival-stage-consideration", "postcode-boundary", "ugc-terms", "login-session-app-boundary", "manual-review"],
    submissionMethod: "bbc-music-introducing-peel-upload-tool-uk-artist-route",
    feeRequired: false,
    feeAmount: "Free public/manual route. Public source material describes the BBC Introducing Peel upload tool for unsigned UK artists and bands; no public upfront submission fee was observed.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for BBC account/login, UK postcode/territory eligibility, UGC/upload terms, track ownership, clean/radio-ready metadata, local-station routing, editorial review and possible AI/copyright policy implications. No account was created, no login was used and no track was uploaded.",
    notes: "Public source material identifies BBC Music Introducing as an active BBC Music upload platform for unsigned/under-the-radar UK talent, with local and national shows, many registered artists/tracks and an upload tool that routes submissions by postcode to producers and presenters. The official route was treated as an account/upload boundary and not bypassed. Strong option for UK-eligible MarcsMusic releases only after manual owner review."
  },
  {
    name: "Triple J Unearthed Australian Independent Artist Upload Route",
    websiteUrl: "https://triplejunearthed.com/",
    submissionUrl: "https://triplejunearthed.com/",
    sourceUrl: "https://triplejunearthed.com/",
    sourceType: "automation_run_236_public_research",
    country: "Australia / ABC Triple J independent Australian music discovery platform",
    language: "en",
    genres: ["triple-j", "unearthed", "independent-australian-music", "artist-profile", "track-upload", "radio-discovery", "unearthed-high-boundary", "abc-radio", "login-session-app-boundary", "manual-review"],
    submissionMethod: "triple-j-unearthed-australian-independent-artist-upload-route",
    feeRequired: false,
    feeAmount: "Free public/manual route. Public source material describes Triple J Unearthed as an independent Australian music discovery/upload platform; no public upfront submission fee was observed.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for Australia eligibility, artist-profile creation, account/login, public upload, competition or Unearthed High boundaries, ratings/comment features, rights/copyright terms and human editorial/radio review. No account was created, no login was used and no track was uploaded.",
    notes: "Public source material identifies Triple J Unearthed as an ABC online music discovery platform for unsigned Australian artists, where musicians upload music and can be discovered for radio/competition opportunities. June 2026 coverage of Unearthed High finalists validates current platform activity. Suitable only if the artist/release meets Australian eligibility criteria."
  },
  {
    name: "Amazing Radio New Emerging Artist Upload Airplay Route",
    websiteUrl: "https://amazingradio.com/",
    submissionUrl: "https://amazingradio.com/",
    sourceUrl: "https://amazingradio.com/",
    sourceType: "automation_run_236_public_research",
    country: "United Kingdom / United States / worldwide new and emerging artist radio-upload platform",
    language: "en",
    genres: ["amazing-radio", "new-music-radio", "emerging-artists", "artist-upload", "radio-airplay", "listener-ratings", "online-radio", "javascript-app-boundary", "login-session-app-boundary", "manual-review"],
    submissionMethod: "amazing-radio-new-emerging-artist-upload-airplay-route",
    feeRequired: false,
    feeAmount: "Free public/manual route. Public source material describes artist uploads for radio consideration; no public upfront submission fee was observed during this run.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required because the official site returned a JavaScript app boundary, and any upload requires account/session, artist identity, rights metadata, track selection, radio suitability and public profile review. No JavaScript app flow was bypassed, no account was created and no music was uploaded.",
    notes: "Public source material identifies Amazing Radio as an international new/emerging-artist radio platform where unsigned artists can submit/upload for radio and online discovery. The official site displayed a JavaScript application boundary and was not bypassed. Relevant for MarcsMusic electronic/world-fusion releases if the owner approves the account and upload workflow."
  },
  {
    name: "International Songwriting Competition Unsigned Only Category Entry Route",
    websiteUrl: "https://www.songwritingcompetition.com/",
    submissionUrl: "https://www.songwritingcompetition.com/enter",
    sourceUrl: "https://www.songwritingcompetition.com/",
    sourceType: "automation_run_236_public_research",
    country: "International / worldwide songwriting and unsigned-artist competition route",
    language: "en",
    genres: ["songwriting-competition", "unsigned-only", "edm", "hip-hop-rap", "instrumental", "lyrics", "performance", "pop", "r-and-b-soul", "rock", "world-music", "industry-judges", "payment-pricing-boundary", "login-session-app-boundary", "manual-review"],
    submissionMethod: "international-songwriting-competition-unsigned-only-category-entry-route",
    feeRequired: true,
    feeAmount: "Paid/manual competition route. Public source material identifies ISC/Unsigned Only as annual international entry competitions with prizes; entry categories, fees, rules and payment flow must be owner-reviewed before use.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for contest eligibility, entry fees/payment, category selection, songwriting/recording ownership, lyric/performance material, prize/rights terms, account/session and final entry confirmation. No account was created, no form was submitted and no payment was made.",
    notes: "Public source material describes the International Songwriting Competition as an annual online contest open to entrants worldwide with multiple relevant categories including EDM, Hip-Hop/Rap, Instrumental, Lyrics, Performance, Pop, R&B/Soul, Rock, Unsigned and World Music; it also describes Unsigned Only as an international competition for artists not signed to major labels. Useful for finished MarcsMusic songs after legal/fee/category review."
  },
  {
    name: "Thomann 2026 Beatmaking Contest Social Hashtag Submission Route",
    websiteUrl: "https://www.thomann.de/",
    submissionUrl: "https://www.thomann.de/blog/en/beatmaking-contest-2026/",
    sourceUrl: "https://www.thomann.de/blog/en/beatmaking-contest-2026/",
    sourceType: "automation_run_236_public_research",
    country: "Europe / worldwide beatmaking contest with public social-platform submission route",
    language: "en",
    genres: ["beatmaking-contest", "producer-contest", "electronic", "hip-hop", "house", "trap", "lo-fi", "drill", "experimental", "sample-pack-requirement", "instagram", "tiktok", "youtube", "facebook", "hashtag-submission", "login-session-app-boundary", "manual-review"],
    submissionMethod: "thomann-2026-beatmaking-contest-social-hashtag-submission-route",
    feeRequired: false,
    feeAmount: "Free public/manual contest route. Public 2026 coverage states entries are submitted through public social posts using the contest hashtag; no upfront entry fee was observed.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required because the route is time-sensitive, requires use of specific sample material, a 30-60 second original beat, public upload to a social platform, hashtag compliance, social-account login, contest terms, rights review and deadline confirmation. No social post was created and no media was uploaded.",
    notes: "Public 2026 coverage reports the Thomann Beatmaking Contest deadline as July 12, 2026, with accepted styles including boom bap, trap, house, lo-fi, drill and experimental. Entries must use required samples, be original, run 30-60 seconds and be posted via Instagram, Facebook, YouTube or TikTok with the specified hashtag. Strong urgent manual-review candidate for MarcsMusic producer content."
  }
];