import type { PlatformInput } from '../models/types.js';

export const run210SeedPlatforms: PlatformInput[] = [
  {
    name: "CFUV Victoria Digital Download Link Music Submission Route",
    websiteUrl: "https://cfuv.uvic.ca/",
    submissionUrl: "https://cfuv.uvic.ca/music-submissions/",
    sourceUrl: "https://cfuv.uvic.ca/music-submissions/",
    sourceType: "automation_run_210_public_research",
    country: "Canada / Victoria, British Columbia campus-community radio",
    language: "en",
    genres: ["campus-radio", "community-radio", "electronic", "reggae", "world", "hip-hop", "independent", "digital-download", "manual-review"],
    submissionMethod: "cfuv-victoria-digital-download-link-music-submission-route",
    feeRequired: false,
    feeAmount: "Free-first/manual campus-community radio route. Official guidance asks for at least three tracks, 320 kbps MP3 quality, digital download links, artist bio and release metadata for Music Director / Music Team review.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for track count, 320 kbps MP3 or better prep, download-link permissions, artist bio, release metadata, clean/FCC-style suitability, local-versus-nonlocal routing and follow-up timing. No outbound email was sent, no files were uploaded, no links were delivered and no physical package was prepared.",
    notes: "Official music-submission page lists a public Music Director route and review constraints. Queued for manual pitch preparation because CFUV explicitly reviews submissions and does not guarantee airplay."
  },
  {
    name: "KBOO Portland Physical Music Library Mail Submission Route",
    websiteUrl: "https://www.kboo.fm/",
    submissionUrl: "https://www.kboo.fm/submit-your-music",
    sourceUrl: "https://www.kboo.fm/submit-your-music",
    sourceType: "automation_run_210_public_research",
    country: "United States / Portland, Oregon community radio",
    language: "en",
    genres: ["community-radio", "freeform", "reggae", "world", "electronic", "hip-hop", "roots", "independent", "physical-package", "manual-review"],
    submissionMethod: "kboo-portland-physical-music-library-mail-submission-route",
    feeRequired: false,
    feeAmount: "Free/manual physical music-library route. Official guidance says KBOO is volunteer-driven, welcomes emerging music, has no digital library, cannot download/burn CDs and asks for mailed physical music submissions.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for physical CD/media decision, one-sheet and genre-attention routing, no-digital-library constraint, clean/radio-fit status, packaging cost and postal dispatch. No files were transferred, no email/contact form was sent and no physical package was prepared or mailed.",
    notes: "Official KBOO submission page is a clear authorized public route, but it is physical/manual only and explicitly disallows relying on downloaded or burned digital submissions."
  },
  {
    name: "KAOS Olympia Physical Digital Link Music Director Submission Route",
    websiteUrl: "https://www.kaosradio.org/",
    submissionUrl: "https://www.kaosradio.org/submitmusic",
    sourceUrl: "https://www.kaosradio.org/submitmusic",
    sourceType: "automation_run_210_public_research",
    country: "United States / Olympia, Washington independent campus-community radio",
    language: "en",
    genres: ["campus-radio", "community-radio", "freeform", "electronic", "reggae", "experimental", "world", "independent", "physical-package", "digital-link", "manual-review"],
    submissionMethod: "kaos-olympia-physical-digital-link-music-director-submission-route",
    feeRequired: false,
    feeAmount: "Free-first/manual music-submission route. Official guidance prioritizes physical submissions but also accepts digital submissions by email with streaming/download links and no direct attached files.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for physical-versus-digital route choice, no-single constraint, one-sheet metadata, FCC note, local/show information, streaming/download link quality and independent-music fit. No email was sent, no links/files were delivered and no package was prepared or mailed.",
    notes: "Official KAOS route is relevant for independent and eclectic MarcsMusic releases; queued manual because the station prioritizes physical processing and applies editorial/library review."
  },
  {
    name: "KEXP Seattle Music Director Rotation Consideration Email Route",
    websiteUrl: "https://kexp.org/",
    submissionUrl: "https://kexp.org/contact/",
    sourceUrl: "https://kexp.org/contact/",
    sourceType: "automation_run_210_public_research",
    country: "United States / Seattle and Bay Area independent public radio",
    language: "en",
    genres: ["public-radio", "indie", "electronic", "afrobeat", "reggae", "hip-hop", "latin", "world", "rotation-consideration", "manual-review"],
    submissionMethod: "kexp-seattle-music-director-rotation-consideration-email-route",
    feeRequired: false,
    feeAmount: "Free-first/manual radio rotation consideration route. Official contact page lists a dedicated Music Director / Music Department email for KEXP rotation consideration and links KEXP's own radio-airplay guidelines.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for high-fit pitch, release timing, clean/radio edit status, download/streaming link selection, one-sheet, regional versus global positioning and KEXP editorial fit. No outbound email was sent, no files were transferred and no contact form was used.",
    notes: "Official KEXP page exposes an authorized Music Director route for rotation consideration. Logged as public source-verified, not SMTP-verified, and queued as a manual pitch."
  },
  {
    name: "WICB Ithaca Submit Music Navigation Local Alternative Route",
    websiteUrl: "https://wicb.org/",
    submissionUrl: "https://wicb.org/",
    sourceUrl: "https://wicb.org/",
    sourceType: "automation_run_210_public_research",
    country: "United States / Ithaca, New York college radio",
    language: "en",
    genres: ["college-radio", "alternative", "reggae", "hip-hop", "jazz", "local-music", "independent", "submit-music-navigation", "manual-review"],
    submissionMethod: "wicb-ithaca-submit-music-navigation-local-alternative-route",
    feeRequired: false,
    feeAmount: "Free-first/manual college-radio route. Official WICB navigation exposes Submit Music, while public station context confirms alternative programming, local-music support, specialty shows and active broadcast operations.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required because the public Submit Music navigation is visible but the tool did not expose the full form/body details. Manual browser review is needed for fields, possible contact form, attachment/link rules, local-music fit, clean/radio edit status and metadata. No form was opened beyond public navigation, no message was sent and no files were uploaded.",
    notes: "Queued cautiously as an official WICB submit-music navigation route; marked needs_manual_review until a human verifies the form fields and any anti-bot/session behavior in-browser."
  }
];
