import type { PlatformInput } from '../models/types.js';

export const run219SeedPlatforms: PlatformInput[] = [
  {
    name: "RouteNote Free Premium Worldwide Music Distribution Upload Route",
    websiteUrl: "https://www.routenote.com/",
    submissionUrl: "https://www.routenote.com/",
    sourceUrl: "https://www.routenote.com/",
    sourceType: "automation_run_219_public_research",
    country: "United Kingdom / worldwide digital music distribution platform",
    language: "en",
    genres: ["digital-distribution", "free-distribution", "premium-distribution", "spotify", "apple-music", "global-stores", "artist-upload", "manual-review"],
    submissionMethod: "routenote-free-premium-worldwide-music-distribution-upload-route",
    feeRequired: false,
    feeAmount: "Free-first/manual distribution route. Official RouteNote page offers FREE and Premium services, worldwide distribution to Spotify, Apple Music and more, and a pricing boundary.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for account/session, free versus Premium plan choice, rights/ownership, audio/artwork upload, metadata, store selection, royalty model and payout setup. No account was created, no upload was started and no plan was selected.",
    notes: "Official RouteNote page says artists can stream and sell music around the world on Spotify, Apple Music and more, choose FREE or Premium service, distribute worldwide to popular platforms and check pricing."
  },
  {
    name: "TuneCore Unlimited DSP Distribution Artist Upload Route",
    websiteUrl: "https://www.tunecore.com/",
    submissionUrl: "https://web.tunecore.com/",
    sourceUrl: "https://www.tunecore.com/",
    sourceType: "automation_run_219_public_research",
    country: "United States / global digital music distribution platform",
    language: "en",
    genres: ["digital-distribution", "spotify", "apple-music", "tiktok", "youtube", "tidal", "beatport", "artist-upload", "manual-review"],
    submissionMethod: "tunecore-unlimited-dsp-distribution-artist-upload-route",
    feeRequired: true,
    feeAmount: "Paid/manual distribution route. Official TuneCore page shows unlimited releases starting at $24.99/year, sign-up/login/dashboard routes and distribution to 150+ stores.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for paid plan, account/session, release upload, rights, cover art, metadata, store selection, publishing/accelerator options and payout/tax setup. No account was created, no upload was started and no payment workflow was initiated.",
    notes: "Official TuneCore page says artists can get music on Spotify, Apple Music, TikTok, YouTube, Tidal, Tencent and more, keep ownership, use unlimited distribution starting at $24.99/year, and upload music through TuneCore."
  },
  {
    name: "CD Baby One-Time Fee Digital Distribution Upload Route",
    websiteUrl: "https://cdbaby.com/",
    submissionUrl: "https://members.cdbaby.com/",
    sourceUrl: "https://cdbaby.com/",
    sourceType: "automation_run_219_public_research",
    country: "United States / worldwide independent music distribution platform",
    language: "en",
    genres: ["digital-distribution", "spotify", "apple-music", "tiktok", "youtube", "pandora", "deezer", "one-time-fee", "manual-review"],
    submissionMethod: "cd-baby-one-time-fee-digital-distribution-upload-route",
    feeRequired: true,
    feeAmount: "Paid/manual distribution route. Official CD Baby page says distribution starts at $9.99 per release, with $9.99 per single and $14.99 per album pricing shown.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for account/session, release setup fee, audio/artwork upload, metadata, partner selection, rights, cover-song licensing if applicable, revenue split and payout/tax setup. No account was created, no release was uploaded and no payment was initiated.",
    notes: "Official CD Baby page exposes Get Started/Login routes, says artists can make music available on 150+ services worldwide including Spotify, Apple Music, TikTok, Amazon, Pandora, YouTube and Deezer, and lists one-time pricing."
  },
  {
    name: "Horus Music Unlimited Distribution Playlist Radio Promotion Route",
    websiteUrl: "https://www.horusmusic.global/",
    submissionUrl: "https://mmaz.myclientzone.com/",
    sourceUrl: "https://www.horusmusic.global/",
    sourceType: "automation_run_219_public_research",
    country: "United Kingdom / global distribution, playlist pitching and radio promotion service",
    language: "en",
    genres: ["digital-distribution", "playlist-pitching", "radio-promotion", "sync-licensing", "global-radio", "artist-upload", "manual-review"],
    submissionMethod: "horus-music-unlimited-distribution-playlist-radio-promotion-route",
    feeRequired: false,
    feeAmount: "Free-start/manual paid-service route. Official Horus Music page exposes Sign Up For Free and Send Us Your Music routes, while unlimited distribution is advertised from £20/year and additional publishing/promotion services have pricing boundaries.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for signup/session, distribution plan, audio/artwork upload, rights, metadata, playlist/radio promotion choices, publishing/sync terms, yearly pricing and support/contact handling. No account was created, no Microsoft/third-party form was submitted and no payment was initiated.",
    notes: "Official Horus Music page shows Sign Up/Login/Get Started routes, unlimited distribution from £20/year, release to 100+ platforms worldwide, 100% royalties, free UPCs/ISRCs, Spotify For Artists access, playlist pitching, UK/global radio promotion, Digital PR, and June/May/March 2026 blog activity."
  },
  {
    name: "iMusician Global Distribution Playlist Pitching Artist Hub Route",
    websiteUrl: "https://imusician.pro/",
    submissionUrl: "https://auth.imusician.pro/",
    sourceUrl: "https://imusician.pro/",
    sourceType: "automation_run_219_public_research",
    country: "Switzerland / global digital music distribution and playlist pitching platform",
    language: "en",
    genres: ["digital-distribution", "playlist-pitching", "artist-hub", "spotify-playlists", "music-analytics", "youtube-monetization", "manual-review"],
    submissionMethod: "imusician-global-distribution-playlist-pitching-artist-hub-route",
    feeRequired: true,
    feeAmount: "Paid/manual distribution and promotion route. Official iMusician page exposes Sign Up/Login/Get Started, Pricing, digital distribution, editorial playlist pitching, Artist Hub and music promotion routes.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for account/session, pricing plan, release upload, ownership/rights, metadata, playlist-pitching eligibility, Artist Hub/promotion tools, analytics and payout setup. No account was created, no upload was started and no pricing flow was opened.",
    notes: "Official iMusician page says artists can reach global audiences on 200+ platforms, retain ownership, use unlimited releases/artists depending on plan, submit music for editorial playlist pitching and submit to hand-picked Spotify playlists."
  }
];
