import type { PlatformInput } from '../models/types.js';

export const run239SeedPlatforms: PlatformInput[] = [
  {
    name: "CJSW Calgary Digital New Album Jotform Airplay Route",
    websiteUrl: "https://cjsw.com/",
    submissionUrl: "https://cjsw.com/music/submit/",
    sourceUrl: "https://cjsw.com/music/submit/",
    sourceType: "automation_run_239_public_research",
    country: "Canada / Calgary campus and community freeform radio",
    language: "en",
    genres: ["cjsw", "campus-radio", "community-radio", "freeform", "digital-music-submissions", "new-albums", "mp3", "zip-upload", "jotform-route", "independent-artists", "no-singles", "protected-email-observed", "manual-review"],
    submissionMethod: "cjsw-calgary-digital-new-album-jotform-airplay-route",
    feeRequired: false,
    feeAmount: "Free public digital album submission route. Official page states CJSW only accepts digital submissions and accepts new albums released within the last three months with three or more unique tracks.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for Jotform upload fields, album recency, three-plus-track rule, MP3 and .zip requirements, no-singles restriction, local/independent fit, weekly tracking signup and protected contact handling. No form was opened beyond the public page and no release was uploaded.",
    notes: "Official CJSW page exposes an upload route, accepts digital music submissions only, requires MP3 albums in .zip format, excludes singles and routes accepted material into volunteer/staff review for freeform airplay fit. The rendered contact email is protected/non-plaintext and was not decoded."
  },
  {
    name: "CFUV Victoria 320kbps Download Link Music Director Airplay Route",
    websiteUrl: "https://cfuv.uvic.ca/",
    submissionUrl: "https://cfuv.uvic.ca/music-submissions/",
    sourceUrl: "https://cfuv.uvic.ca/music-submissions/",
    sourceType: "automation_run_239_public_research",
    country: "Canada / Victoria campus and community radio",
    language: "en",
    genres: ["cfuv", "campus-radio", "community-radio", "freeform", "electronic", "hip-hop", "world", "jazz", "rock", "folk-roots", "320kbps-mp3", "download-link", "music-director-email", "physical-local-boundary", "manual-review"],
    submissionMethod: "cfuv-victoria-320kbps-download-link-music-director-airplay-route",
    feeRequired: false,
    feeAmount: "Free public music director route. Official page asks artists to send digital submissions by email with a download link and says physical submissions are generally no longer accepted except for local artists.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for email wording, download-link privacy, at least three unique tracks, 320 kbps MP3 requirement, one-page bio, album title and track listing, independent/underappreciated fit, lyrical/quality concerns and local-only physical exception. No outbound email was sent and no files were transferred.",
    notes: "Official CFUV route lists music@cfuv.ca, identifies the Music Director, accepts digital download links via services such as earshotDistro, Dropbox, Google Drive, WeTransfer, Box and Disco, and explains that accepted releases are library/chart releases for freeform hosts."
  },
  {
    name: "WMSE Milwaukee FCC Clean Physical Digital Music Department Route",
    websiteUrl: "https://wmse.org/",
    submissionUrl: "https://wmse.org/about-wmse-radio/music-department/",
    sourceUrl: "https://wmse.org/about-wmse-radio/music-department/",
    sourceType: "automation_run_239_public_research",
    country: "United States / Milwaukee noncommercial freeform radio",
    language: "en",
    genres: ["wmse", "college-radio", "noncommercial-radio", "freeform", "alternative", "blues", "jazz", "new-age", "world", "cd", "vinyl", "cassette", "digital-download", "fcc-clean", "music-director-email", "physical-package-route", "manual-review"],
    submissionMethod: "wmse-milwaukee-fcc-clean-physical-digital-music-department-route",
    feeRequired: false,
    feeAmount: "Free public music department route. Shipping or preparation costs may exist for physical media, but no platform fee is stated.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for FCC-clean track labeling, one-copy physical package choice, digital download link/email wording, tracklist, contact details, genre/DJ fit, interview/live-performance expectations and no-guaranteed-airplay policy. No email was sent and no package was prepared or mailed.",
    notes: "Official WMSE music department guidance accepts CD with at least four FCC-clean tracks, vinyl, cassette and digital downloads via WeTransfer or email to the Music Director. It states music is previewed by the Music Department and selected by volunteer DJs rather than a traditional rotation."
  },
  {
    name: "KALX Berkeley Professionally Pressed CD LP Music Director Route",
    websiteUrl: "https://kalx.berkeley.edu/",
    submissionUrl: "https://kalx.berkeley.edu/about/contact/",
    sourceUrl: "https://kalx.berkeley.edu/about/contact/",
    sourceType: "automation_run_239_public_research",
    country: "United States / Berkeley college and community radio",
    language: "en",
    genres: ["kalx", "college-radio", "community-radio", "freeform", "physical-submission", "professionally-pressed-cd", "lp", "no-downloads", "no-file-transfers", "music-director-email", "physical-package-route", "manual-review"],
    submissionMethod: "kalx-berkeley-professionally-pressed-cd-lp-music-director-route",
    feeRequired: false,
    feeAmount: "Free public physical airplay consideration route. Shipping/production costs may exist for artists, but no platform submission fee is stated.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required because KALX currently accepts only physical, professionally pressed CDs or LPs and explicitly rejects downloads, file transfers, Bandcamp/Spotify links, YouTube videos, CD-Rs and other digital forms. No email was sent and no package was prepared or mailed.",
    notes: "Official KALX contact page lists music@kalx.berkeley.edu, names the music directors, provides the mailing address for Attn: Music Director and states physical-only submission requirements for airplay consideration."
  },
  {
    name: "Radio Milwaukee WAV Radio Edit Music Submission Route",
    websiteUrl: "https://www.radiomilwaukee.org/",
    submissionUrl: "https://radiomilwaukee.org/music-submission",
    sourceUrl: "https://radiomilwaukee.org/music-submission",
    sourceType: "automation_run_239_public_research",
    country: "United States / Milwaukee public radio and local music platform",
    language: "en",
    genres: ["radio-milwaukee", "88nine", "public-radio", "adult-album-alternative", "local-music", "new-music", "wav-preferred", "radio-edits", "no-physical-media", "music-submission-page", "manual-review"],
    submissionMethod: "radio-milwaukee-wav-radio-edit-music-submission-route",
    feeRequired: false,
    feeAmount: "Free public music submission guidance route. No platform payment requirement was observed on the official submission page.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for unclear rendered delivery mechanism, uncompressed WAV preference, mixed/mastered radio edits, no-physical-media rule, lyric/bio/documentation requirements, local/editorial fit and no-guaranteed-airplay policy. No form was submitted, no files were uploaded and no message was sent.",
    notes: "Official Radio Milwaukee page exposes a Submit Music route and asks for uncompressed audio, WAV preferred, mixed and mastered, radio edits required, plus bio, musician names, song comments, lyrics, album/live-show info and helpful links. The contact page links Music Submissions as a contact category, but no direct plaintext music-submission email was observed in the rendered page."
  }
];