import type { PlatformInput } from '../models/types.js';

export const run228BaseSeedPlatforms: PlatformInput[] = [
  {
    name: "KEXP Seattle Digital WAV Music Director Airplay Route",
    websiteUrl: "https://www.kexp.org/",
    submissionUrl: "https://www.kexp.org/about/submission-guidelines/",
    sourceUrl: "https://www.kexp.org/about/submission-guidelines/",
    sourceType: "automation_run_228_public_research",
    country: "United States / Seattle, Washington public independent radio",
    language: "en",
    genres: ["public-radio", "independent-radio", "radio-airplay", "music-director-email", "wav-download-link", "fcc-clean", "free-first", "manual-review"],
    submissionMethod: "kexp-seattle-digital-wav-music-director-airplay-route",
    feeRequired: false,
    feeAmount: "Free manual email/link route. Official KEXP submission guidance asks for digital links to music and does not list a submission payment requirement.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for outbound email, WAV streaming/download links, FCC-clean radio edits, lyric sheet, credits, bio/one-sheet, release-date metadata and Pacific Northwest/Bay Area show relevance. No email was sent and no files were transferred.",
    notes: "Official KEXP Contact and Submission Guidelines pages list md@kexp.org for music rotation consideration and request streaming/download WAV links, focus tracks, release dates, clean edits, lyric sheet, credits and bio/one-sheet. KEXP also states there is no guarantee of spins, does not accept physical submissions through this route, and cannot pay to play music."
  },
  {
    name: "The Line of Best Fit New Unsigned Artist Google Form Route",
    websiteUrl: "https://www.thelineofbestfit.com/",
    submissionUrl: "https://docs.google.com/forms/d/e/1FAIpQLSdnvDWw7n5iLoVqzjS_DlnOCgkyETJ7Es1a7YL0bgmkdbuawQ/viewform",
    sourceUrl: "https://www.thelineofbestfit.com/contact",
    sourceType: "automation_run_228_public_research",
    country: "United Kingdom / global new-music editorial platform",
    language: "en",
    genres: ["music-blog", "editorial", "new-music", "unsigned-artists", "google-form", "public-form", "track-link", "free-first", "manual-review"],
    submissionMethod: "the-line-of-best-fit-new-unsigned-artist-google-form-route",
    feeRequired: false,
    feeAmount: "Free public form route. Official contact page welcomes music from new and unsigned artists and links to a Google Form with no payment field observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for editorial fit, one-track-only rule, artist/manager/publicist role selection, contact data, newsletter consent choice and Google Forms session/privacy boundary. No form was submitted.",
    notes: "Official The Line of Best Fit Contact page links to a public form for new and unsigned artists. The Google Form asks for email, role, contact name, artist name, genre, one-sentence bio, Instagram/Bandcamp/Spotify links, one SoundCloud/Bandcamp/Spotify track link and track title; Google sign-in is offered only to save progress."
  },
  {
    name: "Music Xray Song Opportunity Paid A&R Submission Route",
    websiteUrl: "https://www.musicxray.com/",
    submissionUrl: "https://www.musicxray.com/",
    sourceUrl: "https://www.musicxray.com/",
    sourceType: "automation_run_228_public_research",
    country: "United States / global A&R song-to-opportunity platform",
    language: "en",
    genres: ["a-and-r", "song-opportunities", "industry-professionals", "guaranteed-listen", "paid-submission", "free-membership", "login-boundary", "payment-boundary", "manual-review"],
    submissionMethod: "music-xray-song-opportunity-paid-ar-submission-route",
    feeRequired: true,
    feeAmount: "Paid manual route. Public source material describes free membership but says musicians pay fees, often more than $10, to submit songs to industry professionals for guaranteed listen/response workflows.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for account/session, song upload, opportunity matching, industry-recipient fit, paid submission fee, response/critique expectations, rights ownership and any application/approval controls. No account was created, no song was uploaded and no payment workflow was initiated.",
    notes: "Public source material identifies Music Xray as an active online A&R platform where artists submit songs to industry professionals, with a song-to-opportunity matching system, free member accounts and paid guaranteed-listen/response submissions. The observed official site resolves to a public Music Xray/SmashHaus route but did not expose parseable submission detail in this run."
  },
  {
    name: "ReverbNation Artist Profile Opportunities Promotion Route",
    websiteUrl: "https://www.reverbnation.com/",
    submissionUrl: "https://www.reverbnation.com/",
    sourceUrl: "https://www.reverbnation.com/",
    sourceType: "automation_run_228_public_research",
    country: "Global / independent artist services and social music platform",
    language: "en",
    genres: ["artist-profile", "music-social-network", "artist-services", "promotion", "distribution", "opportunities", "free-first", "freemium", "login-boundary", "payment-boundary", "manual-review"],
    submissionMethod: "reverbnation-artist-profile-opportunities-promotion-route",
    feeRequired: true,
    feeAmount: "Freemium/paid manual route. Public source material identifies ReverbNation as an active independent-music site with optional registration/free artist tools and paid/artist-service style distribution and promotion functionality.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for artist account/session, profile creation, music upload, opportunity/promotion selection, distribution or paid service choices, rights ownership, fan-data privacy and subscription/payment controls. No account was created and no content was uploaded.",
    notes: "Public source material identifies ReverbNation as an active music/social-networking website owned by BandLab Technologies and focused on the independent music industry, with artist tools for promotion, fan management, distribution and career-management workflows."
  },
  {
    name: "Broadjam Licensing Contest Radio Play Artist Submission Route",
    websiteUrl: "https://www.broadjam.com/",
    submissionUrl: "https://www.broadjam.com/",
    sourceUrl: "https://www.broadjam.com/",
    sourceType: "automation_run_228_public_research",
    country: "United States / global independent musician community and licensing platform",
    language: "en",
    genres: ["music-community", "licensing-opportunities", "sync-placement", "contests", "radio-play", "professional-reviews", "artist-membership", "paid-manual", "login-boundary", "payment-boundary", "manual-review"],
    submissionMethod: "broadjam-licensing-contest-radio-play-artist-submission-route",
    feeRequired: true,
    feeAmount: "Paid/manual route. Public source material describes membership, contests, professional reviews, radio-play submissions and licensing/placement services; any fee, membership or placement terms require owner review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for account/session, membership tier, song upload, contest/licensing/radio-play/review selection, fee/payment terms, publishing rights, metadata, split ownership and placement/licensing terms. No account was created, no song was uploaded and no payment workflow was initiated.",
    notes: "Public source material describes Broadjam as an independent-musician community with contests, professional reviews, radio-play submissions and licensing opportunities for film, TV, advertising campaigns and video games. Direct official-site parsing was access-limited in this run, so it is queued for manual review."
  }
];
