import type { PlatformInput } from '../models/types.js';

export const run249BaseSeedPlatforms: PlatformInput[] = [
  {
    "name": "TAXI Paid A&R Industry Listings Sync Label Submission Route",
    "websiteUrl": "https://www.taxi.com/",
    "submissionUrl": "https://www.taxi.com/submit-music/",
    "sourceUrl": "https://www.taxi.com/",
    "sourceType": "automation_run_249_public_research",
    "country": "Global / US-based independent A&R, sync, publishing, label and production-music opportunity route",
    "language": "en",
    "genres": ["taxi", "a-and-r", "sync-licensing", "film-tv", "music-publishers", "record-labels", "production-libraries", "industry-listings", "paid-membership", "login-required", "payment-boundary", "manual-review"],
    "submissionMethod": "taxi-paid-a-and-r-industry-listings-sync-label-submission-route",
    "feeRequired": true,
    "feeAmount": "Official TAXI page exposes Join/Renew/Member Login and Submit Music routes; membership, listings and submission costs require owner approval before use.",
    "loginRequired": true,
    "captchaDetected": false,
    "paymentRequired": true,
    "manualReviewRequired": true,
    "manualReviewReason": "Owner review required for membership signup, paid account renewal, listing selection, song/instrumental upload, screening rules, A&R feedback, sync/licensing terms, publishing/label target fit and payment authorization. No account was created and no music was submitted.",
    "notes": "Official TAXI homepage says it gets music to major/indie labels, film/TV music supervisors, publishers, production music libraries, commercials, trailers and video games, and shows March 2026 featured member activity."
  },
  {
    "name": "Sonicbids Artist EPK Venue Festival Booking Submission Route",
    "websiteUrl": "https://www.sonicbids.com/",
    "submissionUrl": "https://app.sonicbids.com/",
    "sourceUrl": "https://www.sonicbids.com/",
    "sourceType": "automation_run_249_public_research",
    "country": "Global / artist EPK, venue, festival and booking opportunity route",
    "language": "en",
    "genres": ["sonicbids", "epk", "live-booking", "festivals", "venues", "performance-opportunities", "artist-profile", "freemium", "login-required", "app-boundary", "payment-boundary", "manual-review"],
    "submissionMethod": "sonicbids-artist-epk-venue-festival-booking-submission-route",
    "feeRequired": true,
    "feeAmount": "Official Sonicbids page exposes Sign Up, Sign In, Claim Your EPK and venue/booking submission language; pricing/submission terms require owner review inside the app.",
    "loginRequired": true,
    "captchaDetected": false,
    "paymentRequired": true,
    "manualReviewRequired": true,
    "manualReviewReason": "Owner review required for EPK claim, artist profile, app login, gig/festival/venue opportunities, booking calendar, submission terms, possible listing/submission fees, performance history, stage plots and contracts. No account was created and no booking submission was made.",
    "notes": "Official Sonicbids homepage shows 2026 copyright/status, 200,000+ artists, 1,500+ venues, Sign Up/Sign In, Claim Your EPK and 'Submit the Way Venues Want to Book' language."
  },
  {
    "name": "Music Xray Paid Song To Opportunity A&R Submission Route",
    "websiteUrl": "https://www.musicxray.com/",
    "submissionUrl": "https://www.musicxray.com/",
    "sourceUrl": "https://www.musicxray.com/",
    "sourceType": "automation_run_249_public_research",
    "country": "Global / A&R, industry professional and song-to-opportunity submission route",
    "language": "en",
    "genres": ["music-xray", "song-to-opportunity", "a-and-r", "industry-professionals", "song-analysis", "guaranteed-listen", "paid-submission", "freemium", "login-required", "payment-boundary", "manual-review"],
    "submissionMethod": "music-xray-paid-song-to-opportunity-a-and-r-submission-route",
    "feeRequired": true,
    "feeAmount": "Public source information describes free artist joining with paid song submissions, often more than $10, for guaranteed listen/response opportunities.",
    "loginRequired": true,
    "captchaDetected": false,
    "paymentRequired": true,
    "manualReviewRequired": true,
    "manualReviewReason": "Owner review required for account creation, paid opportunity selection, song upload, analysis/scoring terms, guaranteed listen/response expectations, critique options, rights, metadata and payment authorization. No account was created and no song was submitted.",
    "notes": "Music Xray official homepage resolved publicly but returned a JavaScript/empty page to the crawler; public indexed information describes an active platform where artists submit songs to industry professionals. No public music-submission email was observed."
  },
  {
    "name": "Songtradr Sync Licensing Artist Upload Marketplace Route",
    "websiteUrl": "https://www.songtradr.com/",
    "submissionUrl": "https://www.songtradr.com/",
    "sourceUrl": "https://www.songtradr.com/",
    "sourceType": "automation_run_249_public_research",
    "country": "Global / B2B music licensing, sync, brand, platform and creator marketplace route",
    "language": "en",
    "genres": ["songtradr", "sync-licensing", "music-licensing", "artist-upload", "b2b-marketplace", "film-tv-ads", "brands", "content-creators", "login-required", "javascript-app-boundary", "payment-boundary", "manual-review"],
    "submissionMethod": "songtradr-sync-licensing-artist-upload-marketplace-route",
    "feeRequired": true,
    "feeAmount": "Official site is app-gated and public source information describes artist upload/licensing marketplace behavior; fee, commission, plan and payout terms require owner review.",
    "loginRequired": true,
    "captchaDetected": false,
    "paymentRequired": true,
    "manualReviewRequired": true,
    "manualReviewReason": "Owner review required for app login, artist/catalog upload, sync/licensing opt-in, pricing, rights ownership, PRO/publishing splits, commission/payout terms, metadata and brand/content usage permissions. No account was created and no catalog was uploaded.",
    "notes": "Official Songtradr site requires JavaScript in the crawler. Public source information describes Songtradr as a music licensing marketplace where artists can upload music and set licensing fees. No direct public music-submission email was observed."
  },
  {
    "name": "Broadjam Licensing Contests Reviews Radio Opportunity Submission Route",
    "websiteUrl": "https://www.broadjam.com/",
    "submissionUrl": "https://www.broadjam.com/",
    "sourceUrl": "https://www.broadjam.com/",
    "sourceType": "automation_run_249_public_research",
    "country": "Global / independent artist community, licensing, contest, radio play and review opportunity route",
    "language": "en",
    "genres": ["broadjam", "music-licensing", "song-contests", "radio-play", "professional-reviews", "film-tv-ads", "video-games", "artist-community", "freemium", "login-required", "payment-boundary", "manual-review"],
    "submissionMethod": "broadjam-licensing-contests-reviews-radio-opportunity-submission-route",
    "feeRequired": true,
    "feeAmount": "Public source information describes artist memberships, contests, reviews, radio play and placement opportunities; paid/premium and submission terms require owner approval.",
    "loginRequired": true,
    "captchaDetected": false,
    "paymentRequired": true,
    "manualReviewRequired": true,
    "manualReviewReason": "Owner review required for account creation, song upload, contest/opportunity selection, review/radio/licensing routing, premium features, submission fees, rights, metadata and payout/licensing terms. No account was created and no song was submitted.",
    "notes": "Broadjam official homepage returned HTTP 403 to the crawler and was not bypassed. Public indexed information describes licensing opportunities for film, TV, advertising, video games, radio play, professional reviews and a large artist/song database."
  }
];