import type { PlatformInput } from '../models/types.js';

export const run218SeedPlatforms: PlatformInput[] = [
  {
    name: "BIRP Groover SubmitHub Monthly Indie Playlist Submission Route",
    websiteUrl: "https://birp.fm/",
    submissionUrl: "https://birp.fm/",
    sourceUrl: "https://birp.fm/",
    sourceType: "automation_run_218_public_research",
    country: "United States / global indie playlist and music blog outlet",
    language: "en",
    genres: ["indie-playlist", "music-blog", "groover", "submithub", "indie-electronic", "indie-pop", "playlist", "manual-review"],
    submissionMethod: "birp-groover-submithub-monthly-indie-playlist-submission-route",
    feeRequired: false,
    feeAmount: "Freemium/manual third-party submission route. Official BIRP page links artists to Groover and SubmitHub submission routes; third-party free/credit/payment choices may apply.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for choosing Groover versus SubmitHub, third-party account/session, possible credits/payment, playlist fit, unreleased/released track link, press metadata and rejection tolerance. No app login was opened and no submission was made.",
    notes: "Official BIRP homepage shows May 2026, April 2026, March 2026, February 2026 and January 2026 playlist activity, plus public links labelled Send us your music on Groover and Send us your music on SubmitHub."
  },
  {
    name: "alexrainbirdMusic Free Portal Playlist Submission Route",
    websiteUrl: "https://www.alexrainbirdmusic.com/",
    submissionUrl: "https://alexrainbirdmusic.portal.district.biz/",
    sourceUrl: "https://www.alexrainbirdmusic.com/",
    sourceType: "automation_run_218_public_research",
    country: "United Kingdom / global playlist and YouTube curation outlet",
    language: "en",
    genres: ["playlist", "youtube-curator", "indie", "pop", "folk", "electronic", "free-portal", "submithub", "manual-review"],
    submissionMethod: "alexrainbirdmusic-free-portal-playlist-submission-route",
    feeRequired: false,
    feeAmount: "Free-first/manual portal route. Official page says the submission portal is free of charge and that submitted music is listened to before an approval or decline email is sent; SubmitHub is listed as an alternative route.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for portal/session handling, playlist fit, metadata, track link or upload requirements inside the portal, consent/email response handling and optional SubmitHub alternative. No portal session was started and no submission was made.",
    notes: "Official alexrainbirdMusic page says it would love to consider music for playlists, provides a SUBMIT MUSIC portal link, states the route is free of charge, and lists alexrainbirdmusic@gmail.com publicly as a general contact."
  },
  {
    name: "DropTrack Artist Label Promo Campaign Upload Route",
    websiteUrl: "https://www.droptrack.com/",
    submissionUrl: "https://cloud.droptrack.com/signup",
    sourceUrl: "https://www.droptrack.com/",
    sourceType: "automation_run_218_public_research",
    country: "United States / global online music promotion platform",
    language: "en",
    genres: ["music-promotion", "dj-promo", "radio-promo", "playlist-curators", "bloggers", "labels", "artist-upload", "analytics", "manual-review"],
    submissionMethod: "droptrack-artist-label-promo-campaign-upload-route",
    feeRequired: false,
    feeAmount: "Freemium/free-trial/manual route. Official DropTrack pages advertise a free track analyzer and create-free-account route, while Pro/promotion/pricing and ad budget boundaries are visible.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for account/session, track upload, rights, campaign targeting, whether to use own contacts or DropTrack contact lists, playlist placement/ads/spend choices, analytics and data processing. No account was created, no track was uploaded and no campaign was started.",
    notes: "Official DropTrack page says artists and labels can reach DJs, labels, playlist curators, blogs and radio; it lists Analyze Your Track, Pricing, Log In, Sign Up and artist/label signup routes, plus campaign analytics and included contacts."
  },
  {
    name: "Radio Airplay Jango Internet Radio Promotion Upload Route",
    websiteUrl: "https://www.radioairplay.com/",
    submissionUrl: "https://www.radioairplay.com/music+promotion/guaranteed_airplay",
    sourceUrl: "https://www.radioairplay.com/",
    sourceType: "automation_run_218_public_research",
    country: "United States / global internet-radio promotion platform",
    language: "en",
    genres: ["internet-radio", "artist-upload", "radio-airplay", "song-reviews", "playlist-opportunities", "jango", "paid-promotion", "manual-review"],
    submissionMethod: "radio-airplay-jango-internet-radio-promotion-upload-route",
    feeRequired: false,
    feeAmount: "Free-first/manual paid-upgrade route. Official Radio Airplay page shows Free Sign Up, a free package with 100 sign-up bonus plays and paid Intro/Gold/Platinum/Multi-Platinum packages from $12 to $250.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for account/session, track upload, target artist-station matching, free versus paid package selection, monthly play commitments, reviews, fan messaging and promotion-spend boundaries. No account was created and no package was selected.",
    notes: "Official Radio Airplay page describes uploading tracks, matching to artist stations, guaranteed internet radio exposure, reports/fan insights, song reviews, free contests and visible package pricing. Public premium@radioairplay.com contact was observed only as a business/deal contact, not a music-submission inbox."
  },
  {
    name: "HAULIX Media Connect Artist Promo Page Industry Exposure Route",
    websiteUrl: "https://haulix.com/",
    submissionUrl: "https://mediaconnect.haulix.com/",
    sourceUrl: "https://haulix.com/",
    sourceType: "automation_run_218_public_research",
    country: "United States / global music promotion and promo-delivery platform",
    language: "en",
    genres: ["promo-delivery", "artist-promo", "radio-plugging", "press", "labels", "media-connect", "promo-page", "manual-review"],
    submissionMethod: "haulix-media-connect-artist-promo-page-industry-exposure-route",
    feeRequired: false,
    feeAmount: "Freemium/free-trial/manual route. Official HAULIX page exposes Get Started with no charge today/cancel anytime and Pricing + Sign up; paid workflow boundaries remain owner-controlled.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for account/session, pricing/trial terms, promo page creation, audio upload, rights, contact-list use, sender identity, promo invitations and release confidentiality. No account was created, no audio was uploaded and no invitations were sent.",
    notes: "Official HAULIX page describes artist, publicist and label solutions, uploading music to create promo pages, sending invitations to contacts or curated tastemaker lists, stream/download reporting and Media Connect exposure routes."
  }
];
