import type { PlatformInput } from '../models/types.js';

export const run206BaseSeedPlatforms: PlatformInput[] = [
  {
    name: "LANDR Global Music Distribution Release Upload Route",
    websiteUrl: "https://www.landr.com/",
    submissionUrl: "https://www.landr.com/music-distribution/",
    sourceUrl: "https://www.landr.com/music-distribution/",
    sourceType: "automation_run_206_public_research",
    country: "Global / Canada-based music creation, mastering and digital distribution platform",
    language: "en",
    genres: ["digital-distribution", "release-upload", "spotify", "apple-music", "tiktok", "youtube-music", "electronic", "reggae", "world", "manual-review"],
    submissionMethod: "official-landr-global-music-distribution-release-upload-route",
    feeRequired: true,
    feeAmount: "Paid/manual distribution route. Public validation shows LANDR Distribution releases and monetizes music on DSPs such as Spotify, Apple Music and TikTok; official route requires plan/subscription, account, rights and release review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for account/login boundary, paid plan selection, release metadata, audio/artwork readiness, UPC/ISRC/store selection, copyright ownership, royalty/payout setup and AI/mastering/distribution policy fit. No account, upload, release or payment action was taken.",
    notes: "Validated through public LANDR distribution information showing release/monetize workflow for Spotify, Apple Music, TikTok and other DSPs, plus official music-distribution route. Queued only for manual review."
  },
  {
    name: "Ditto Music Unlimited DSP Distribution Upload Route",
    websiteUrl: "https://dittomusic.com/",
    submissionUrl: "https://dittomusic.com/en/music-distribution",
    sourceUrl: "https://dittomusic.com/en/music-distribution",
    sourceType: "automation_run_206_public_research",
    country: "Global / UK-based digital music distribution and artist services platform",
    language: "en",
    genres: ["digital-distribution", "unlimited-releases", "spotify", "apple-music", "tiktok", "beatport", "audiomack", "electronic", "independent-artists", "manual-review"],
    submissionMethod: "official-ditto-music-unlimited-dsp-distribution-upload-route",
    feeRequired: true,
    feeAmount: "Paid/manual distribution route. Public validation describes Ditto as a worldwide online music distributor with unlimited releases to major stores through an annual subscription model while artists retain 100% of royalties.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for paid annual plan, account/session boundary, release upload, metadata, store selection, release date, rights ownership, royalty/payout details and optional label/PR/playlist services. No sign-up, upload, distribution or payment workflow was started.",
    notes: "Validated through public Ditto Music information showing online distribution to 150+ digital stores including Spotify, YouTube, Apple Music, TikTok, Audiomack, SoundCloud and Beatport, plus official music-distribution route. Queued only for manual review."
  },
  {
    name: "Symphonic Distribution Artist Label Application Route",
    websiteUrl: "https://symphonic.com/",
    submissionUrl: "https://symphonic.com/apply/",
    sourceUrl: "https://symphonic.com/",
    sourceType: "automation_run_206_public_research",
    country: "Global / US-based digital music distribution, label services, publishing and sync platform",
    language: "en",
    genres: ["digital-distribution", "label-services", "sync-licensing", "publishing-administration", "spotify", "beatport", "electronic", "independent-labels", "manual-review"],
    submissionMethod: "official-symphonic-distribution-artist-label-application-route",
    feeRequired: false,
    feeAmount: "Free-first/manual application route. Public validation describes Symphonic as a worldwide distributor for independent labels and musicians; commercial distribution, label services, royalty and sync terms require owner review after application.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for application/session boundary, eligibility, catalog quality, label/artist fit, distribution terms, store/territory choices, royalty splits, publishing/sync options, anti-fraud policy and release assets. No application, login, upload, agreement or payment workflow was started.",
    notes: "Validated through public Symphonic information showing worldwide distribution to Spotify, iTunes/Apple Music, Deezer, Pandora, Amazon and Beatport, plus sync/publishing services and official apply route. Queued only for manual review."
  },
  {
    name: "AWAL Selective Artist Services Application Route",
    websiteUrl: "https://www.awal.com/",
    submissionUrl: "https://www.awal.com/apply",
    sourceUrl: "https://www.awal.com/",
    sourceType: "automation_run_206_public_research",
    country: "Global / UK-origin artist services, distribution, marketing, A&R, playlist/radio and sync platform",
    language: "en",
    genres: ["artist-services", "selective-distribution", "a-and-r", "playlist-promotion", "radio-promotion", "sync-licensing", "electronic", "independent-artists", "manual-review"],
    submissionMethod: "official-awal-selective-artist-services-application-route",
    feeRequired: false,
    feeAmount: "Free-first/manual selective application route. Public validation describes AWAL as a global artist-services business with distribution, marketing, A&R, playlist/radio promotion, sync licensing and brand partnerships; acceptance and commercial terms require owner review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for selective application, artist metrics, release/catalog fit, ownership/control terms, marketing/radio/playlist/sync expectations, data access, representation conflicts and acceptance criteria. No application, account, upload or agreement workflow was started.",
    notes: "Validated through public AWAL information showing global artist-services model, distribution, marketing, A&R, playlist/radio promotion, sync licensing, brand partnerships and official apply route. Queued only for manual review."
  },
  {
    name: "Songtradr Music Licensing Marketplace Upload Route",
    websiteUrl: "https://www.songtradr.com/",
    submissionUrl: "https://www.songtradr.com/music-creators",
    sourceUrl: "https://www.songtradr.com/",
    sourceType: "automation_run_206_public_research",
    country: "Global / US-based B2B music licensing, creator marketplace and sync platform",
    language: "en",
    genres: ["sync-licensing", "music-licensing", "creator-marketplace", "film-tv-advertising", "brands", "electronic", "reggae", "world", "independent-artists", "manual-review"],
    submissionMethod: "official-songtradr-music-licensing-marketplace-upload-route",
    feeRequired: false,
    feeAmount: "Free-first/freemium/manual route. Public validation describes Songtradr as a music licensing marketplace where artists can upload music and set licensing fees; commercial licensing, subscription/commission and rights terms require owner review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for creator account, upload files, licensing rights, publishing/master ownership, PRO/collection-society details, pricing/licensing terms, explicit/clean metadata, sync suitability and platform agreement. No account, upload, license, message or payment workflow was started.",
    notes: "Validated through public Songtradr information showing B2B music licensing marketplace, artist uploads, licensing-fee setting and music use by brands/content creators/platforms. Queued only for manual review."
  }
];
