import type { PlatformInput } from '../models/types.js';

export const run214SeedPlatforms: PlatformInput[] = [
  {
    name: "WMSE Milwaukee CD Vinyl Digital Music Department Submission Route",
    websiteUrl: "https://wmse.org/",
    submissionUrl: "https://wmse.org/about-wmse-radio/music-department/",
    sourceUrl: "https://wmse.org/about-wmse-radio/music-department/",
    sourceType: "automation_run_214_public_research",
    country: "United States / Milwaukee independent listener-supported radio",
    language: "en",
    genres: ["college-radio", "community-radio", "electronic", "dub", "reggae", "world", "independent", "cd-submission", "vinyl-submission", "digital-download", "manual-review"],
    submissionMethod: "wmse-milwaukee-cd-vinyl-digital-music-department-submission-route",
    feeRequired: false,
    feeAmount: "Free-first/manual airplay consideration route. Official WMSE guidance accepts CD, vinyl, cassette and digital submissions by download/email route; no payment requirement was observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for choosing physical versus digital delivery, preparing FCC-clean track notes, selecting download links or one physical copy, release one-sheet, genre/show fit, follow-up timing and no-guarantee airplay expectations. No email was sent, no file was uploaded and no physical package was prepared or mailed.",
    notes: "Official WMSE pages show 2026 site activity, Music Director/contact details, weekly airplay charts and a How To Submit Music route accepting CD, vinyl, digital download and cassette submissions. Queued manual because the route requires artist-controlled assets and editorial fit review."
  },
  {
    name: "KXLU Los Angeles FCC Clean Physical Music Director Submission Route",
    websiteUrl: "https://kxlu.com/",
    submissionUrl: "https://kxlu.com/contact/",
    sourceUrl: "https://kxlu.com/contact/",
    sourceType: "automation_run_214_public_research",
    country: "United States / Los Angeles college and community radio",
    language: "en",
    genres: ["college-radio", "freeform-radio", "electronic", "dub", "reggae", "world", "hip-hop", "independent", "physical-submission", "manual-review"],
    submissionMethod: "kxlu-los-angeles-fcc-clean-physical-music-director-submission-route",
    feeRequired: false,
    feeAmount: "Free-first/manual physical submission route. Official KXLU contact guidance lists FCC-clean submissions and postal routes for General Submissions, Demolisten and specialty/vinyl submissions; no payment requirement was observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for FCC-clean confirmation, physical package preparation, route choice between Music Director/Demolisten/specialty-vinyl, release context, genre fit and contact details. No outbound email, package or submission was sent.",
    notes: "Official KXLU contact page shows 2026 station activity, current staff contacts, station address and submission instructions for FCC-clean material. Queued manual because the authorized route is primarily physical and requires human routing decisions."
  },
  {
    name: "CJSW Calgary Recent Album Digital Jotform Music Submission Route",
    websiteUrl: "https://cjsw.com/",
    submissionUrl: "https://cjsw.com/music/submit/",
    sourceUrl: "https://cjsw.com/music/submit/",
    sourceType: "automation_run_214_public_research",
    country: "Canada / Calgary campus and community radio",
    language: "en",
    genres: ["campus-radio", "community-radio", "electronic", "dub", "reggae", "world", "experimental", "independent", "jotform", "digital-submission", "manual-review"],
    submissionMethod: "cjsw-calgary-recent-album-digital-jotform-music-submission-route",
    feeRequired: false,
    feeAmount: "Free-first/manual public form route. Official CJSW guidance accepts digital music submissions for recent albums with three or more tracks via a linked Jotform upload route; no payment requirement was observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for release-date eligibility, album/EP completeness, MP3-only zip preparation, Jotform/manual form handling, metadata, rights, clean-content notes and independent/local positioning. No form was opened for submission, no file was uploaded and protected contact text was not decoded.",
    notes: "Official CJSW pages show active July 2026 programming/news context and a Music Submissions page requiring digital album submissions, MP3 format and .zip delivery via the public Jotform route. Queued manual because form submission and file upload require artist approval."
  },
  {
    name: "KVRX Austin Physical Digital Music Department Airplay Submission Route",
    websiteUrl: "https://www.kvrx.org/",
    submissionUrl: "https://www.kvrx.org/app/contact/",
    sourceUrl: "https://www.kvrx.org/app/contact/",
    sourceType: "automation_run_214_public_research",
    country: "United States / Austin student-run independent radio",
    language: "en",
    genres: ["student-radio", "college-radio", "underground", "electronic", "dub", "reggae", "world", "independent", "digital-submission", "physical-submission", "manual-review"],
    submissionMethod: "kvrx-austin-physical-digital-music-department-airplay-submission-route",
    feeRequired: false,
    feeAmount: "Free-first/manual public music-department route. Official KVRX contact guidance lists music@kvrx.org for airplay consideration and says both physical and digital submissions are being accepted; no payment requirement was observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for AI-generated/AI-assisted exclusion policy, physical versus digital delivery choice, clean-track notes, release fit, metadata, asset selection and outreach copy. No email was sent, no files were transferred and no physical package was prepared.",
    notes: "Official KVRX site shows current station activity and contact guidance stating that all music submissions for airplay consideration should go to the public music department route. Queued manual because the policy includes AI-related restrictions and delivery assets need owner confirmation."
  },
  {
    name: "Radio K Minneapolis Physical Digital Independent Release Submission Route",
    websiteUrl: "https://radiok.org/",
    submissionUrl: "https://radiok.org/submitting-music",
    sourceUrl: "https://radiok.org/submitting-music",
    sourceType: "automation_run_214_public_research",
    country: "United States / Minneapolis student-run college radio",
    language: "en",
    genres: ["college-radio", "independent-radio", "nacc", "electronic", "dub", "reggae", "world", "hip-hop", "physical-submission", "digital-download", "manual-review"],
    submissionMethod: "radio-k-minneapolis-physical-digital-independent-release-submission-route",
    feeRequired: false,
    feeAmount: "Free-first/manual airplay consideration route. Official Radio K guidance accepts physical releases by mail and digital releases by music-department email with Google Drive/Dropbox-style .zip links or Bandcamp download codes; no payment requirement was observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for station-fit check, physical versus digital delivery, lossless .wav/.flac or Bandcamp-code choice, FCC-clean/non-friendly track list, one-sheet, local/independent positioning and no-tracking-email expectations. No email was sent, no digital files were transferred and no physical package was prepared.",
    notes: "Official Radio K pages show 2026 activity, new additions/playlists and a Submitting Music page with physical and digital release instructions. Queued manual because submission assets and follow-up boundaries require artist approval."
  }
];
