import type { PlatformInput } from '../models/types.js';

export const run242BaseSeedPlatforms: PlatformInput[] = [
  {
    name: "NTS Radio Show Proposal Audio Links Submission Route",
    websiteUrl: "https://www.nts.live/",
    submissionUrl: "https://www.nts.live/contact",
    sourceUrl: "https://www.nts.live/contact",
    sourceType: "automation_run_242_public_research",
    country: "Global / UK-based independent online radio platform",
    language: "en",
    genres: ["nts", "radio-show-proposal", "audio-links", "soundcloud", "mixcloud", "youtube", "electronic", "dub", "reggae", "world", "hosted-radio", "manual-review"],
    submissionMethod: "nts-radio-show-proposal-audio-links-submission-route",
    feeRequired: false,
    feeAmount: "The public NTS contact page exposes a radio-show proposal form and audio-link fields; no fee or payment route was observed on the proposal form in this run.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for radio-show concept, demo-link suitability, hosted-radio format, genre description, personal/profile links, editorial fit, rights to all linked audio, and any NTS terms before sending. No form was submitted and no audio links were entered.",
    notes: "Official NTS contact page exposes a Radio Show Proposal route with a 600-character proposal field, show-type selection, audio links requiring SoundCloud, Mixcloud or YouTube, genre fields and a Send action. Treated as a legitimate public manual-review route for MarcsMusic mixes/show concepts rather than a direct single-track upload."
  },
  {
    name: "Radiooooo Community Curated Map Track Upload Route",
    websiteUrl: "https://app.radiooooo.com/",
    submissionUrl: "https://app.radiooooo.com/",
    sourceUrl: "https://app.radiooooo.com/",
    sourceType: "automation_run_242_public_research",
    country: "Global / France-based music discovery map and streaming app",
    language: "en",
    genres: ["radiooooo", "music-discovery", "community-curation", "track-upload", "global-map", "world", "electronic", "dub", "reggae", "javascript-app-boundary", "subscription-boundary", "manual-review"],
    submissionMethod: "radiooooo-community-curated-map-track-upload-route",
    feeRequired: false,
    feeAmount: "Public sources describe user uploads with community/DJ/producer curation and a free trial followed by subscription; exact account/subscription state requires owner review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for JavaScript app/login, country/decade metadata, copyright ownership, track eligibility, curation expectations, free-trial/subscription terms and profile settings. No account was created and no track was uploaded.",
    notes: "Public source material identifies Radiooooo as a music discovery website/app where users can upload songs or tracks that are curated by a community of DJs and producers and surfaced on a global map; the official app rendered a JavaScript boundary and was not bypassed."
  },
  {
    name: "ReverbNation Artist Profile Opportunities Promotion Route",
    websiteUrl: "https://www.reverbnation.com/",
    submissionUrl: "https://www.reverbnation.com/",
    sourceUrl: "https://www.reverbnation.com/",
    sourceType: "automation_run_242_public_research",
    country: "Global / independent-artist services and music networking platform",
    language: "en",
    genres: ["reverbnation", "artist-profile", "music-networking", "opportunities", "widgets", "independent-artists", "promotion", "electronic", "reggae", "world", "login-required", "payment-boundary", "manual-review"],
    submissionMethod: "reverbnation-artist-profile-opportunities-promotion-route",
    feeRequired: false,
    feeAmount: "Public source material identifies ReverbNation as an active independent music industry platform; optional promotional/opportunity services and any paid tiers require owner review before use.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for account/login, artist profile setup, uploaded tracks, widget/profile visibility, opportunity selection, promotional services, paid feature boundaries and messaging/networking terms. No account was used and no music, EPK or opportunity application was submitted.",
    notes: "Public source material identifies ReverbNation as an active music/social-networking website focused on the independent music industry, with musician/producer/venue collaboration features, optional registration and artist reach/influence/access/recency measurement. Official site returned a 403 to the research fetcher, so the route is queued manual."
  },
  {
    name: "Music Xray Paid Song To Opportunity A&R Submission Route",
    websiteUrl: "https://www.musicxray.com/",
    submissionUrl: "https://www.musicxray.com/",
    sourceUrl: "https://www.musicxray.com/",
    sourceType: "automation_run_242_public_research",
    country: "Global / US-based online A&R and song-to-opportunity matching platform",
    language: "en",
    genres: ["music-xray", "a-and-r", "song-to-opportunity", "industry-professionals", "guaranteed-listen", "song-analysis", "electronic", "hip-hop", "pop", "world", "login-required", "payment-required", "manual-review"],
    submissionMethod: "music-xray-paid-song-to-opportunity-a-r-submission-route",
    feeRequired: true,
    feeAmount: "Public source material states musicians often pay a fee to submit music to industry professionals for guaranteed listen/response and critiques; exact opportunity pricing requires owner approval.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for signup/login, paid opportunity selection, song ownership, genre fit, guaranteed-listen terms, critique/response expectations, data/analytics claims and payment authorization. No account was created, no payment was initiated and no song was submitted.",
    notes: "Public source material describes Music Xray as an online platform where artists submit songs to industry professionals, with song-to-opportunity matching, guaranteed listen/response, optional in-depth critiques and free fan/songwriter registration but paid musician submissions."
  },
  {
    name: "Broadjam Licensing Contest Radio Play Song Submission Route",
    websiteUrl: "https://www.broadjam.com/",
    submissionUrl: "https://www.broadjam.com/",
    sourceUrl: "https://www.broadjam.com/",
    sourceType: "automation_run_242_public_research",
    country: "Global / US-based independent musician community, licensing and contest platform",
    language: "en",
    genres: ["broadjam", "licensing", "song-contests", "radio-play", "professional-reviews", "film-tv-advertising-games", "artist-community", "electronic", "instrumental", "world", "login-required", "payment-boundary", "manual-review"],
    submissionMethod: "broadjam-licensing-contest-radio-play-song-submission-route",
    feeRequired: true,
    feeAmount: "Public source material describes contests, professional reviews, licensing opportunities and premium/member services; exact listing, membership or submission fees require owner approval.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for membership/login, song upload, contest/opportunity selection, licensing clearance for master and composition, professional review/radio play terms, regional/genre charts, premium hosting and fee/payment boundaries. No account was created and no track was submitted.",
    notes: "Public source material describes Broadjam as an independent-musician community offering contests, radio play, professional reviews and licensing placements in film, TV, advertising and games; musicians may submit songs for radio play, reviews or placement and music supervisors use the platform to find music."
  }
];
