import type { PlatformInput } from '../models/types.js';

export const run240BaseSeedPlatforms: PlatformInput[] = [
  {
    name: "SoundOn TikTok Global Artist Distribution Upload Route",
    websiteUrl: "https://www.soundon.global/",
    submissionUrl: "https://www.soundon.global/",
    sourceUrl: "https://www.soundon.global/",
    sourceType: "automation_run_240_public_research",
    country: "Global / TikTok-linked music distribution and artist services",
    language: "en",
    genres: ["soundon", "tiktok", "distribution", "artist-upload", "music-marketing", "copyright-retention", "analytics", "global-dsp-delivery", "login-required", "manual-review"],
    submissionMethod: "soundon-tiktok-global-artist-distribution-upload-route",
    feeRequired: false,
    feeAmount: "Public sources describe SoundOn as a distribution and artist-services route that lets artists upload music directly to TikTok and distribute to other platforms, with rights retained by artists. Commercial/royalty terms require owner review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for account creation/login, territory eligibility, royalty terms, copyright ownership, TikTok/DSP distribution selections, metadata/audio/artwork upload, tax/payment profile and promotional-service terms. No account was created and no files were uploaded.",
    notes: "Public source material identifies SoundOn as TikTok/ByteDance's music marketing and distribution platform where artists can upload music directly to TikTok, keep copyright, access audience insights and distribute to other platforms. The official homepage was treated as an app/registration boundary and was not bypassed."
  },
  {
    name: "Audiomack Creator Direct Upload Streaming Discovery Route",
    websiteUrl: "https://audiomack.com/",
    submissionUrl: "https://audiomack.com/",
    sourceUrl: "https://audiomack.com/",
    sourceType: "automation_run_240_public_research",
    country: "Global / streaming, discovery and creator-upload platform",
    language: "en",
    genres: ["audiomack", "creator-upload", "streaming", "discovery", "hip-hop", "r-and-b", "afrobeats", "latin", "creator-app", "free-storage", "manual-curation", "login-required", "manual-review"],
    submissionMethod: "audiomack-creator-direct-upload-streaming-discovery-route",
    feeRequired: false,
    feeAmount: "Public sources describe Audiomack creator uploads as free with no charge or storage limit for creators. A future/pro creator tier was observed as a pricing boundary.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for creator account/login, upload rights, fingerprinting/DMCA/manual-curation rules, metadata/audio quality, genre fit, monetization/Pro terms and artist-profile setup. No account was created and no music was uploaded.",
    notes: "Public source material describes Audiomack as an active streaming/audio discovery platform where artists can upload music through the website/Creator App, with free storage, fingerprinting, DMCA takedown and manual curation controls."
  },
  {
    name: "Jamendo Artist Creative Commons Licensing Upload Route",
    websiteUrl: "https://www.jamendo.com/",
    submissionUrl: "https://www.jamendo.com/",
    sourceUrl: "https://www.jamendo.com/",
    sourceType: "automation_run_240_public_research",
    country: "Global / Luxembourg-based free music and licensing platform",
    language: "en",
    genres: ["jamendo", "artist-upload", "creative-commons", "free-music", "licensing", "sync-licensing", "independent-artists", "artist-profile", "rights-society-boundary", "login-required", "manual-review"],
    submissionMethod: "jamendo-artist-creative-commons-licensing-upload-route",
    feeRequired: false,
    feeAmount: "Public sources describe Jamendo as a platform where artists can publish music for free and pursue discovery/licensing opportunities. Collecting-society and license-choice boundaries require manual review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner/legal review required for Creative Commons/free-use licensing, collecting-rights-society compatibility, commercial licensing participation, profile setup, metadata/audio upload and revenue/donation/licensing terms. No account was created and no catalog was uploaded.",
    notes: "Public source material identifies Jamendo as an open community of independent artists and music lovers, with artist profiles, uploaded albums/singles, free personal streaming/downloads and commercial licensing opportunities through Jamendo Licensing."
  },
  {
    name: "Bandcamp Artist Store Upload Direct Fan Sales Route",
    websiteUrl: "https://bandcamp.com/",
    submissionUrl: "https://bandcamp.com/artists",
    sourceUrl: "https://bandcamp.com/",
    sourceType: "automation_run_240_public_research",
    country: "Global / independent artist marketplace and discovery platform",
    language: "en",
    genres: ["bandcamp", "artist-upload", "direct-to-fan", "digital-store", "independent-artists", "pricing-control", "merch", "lossless-audio", "ai-content-policy", "commission-boundary", "login-required", "manual-review"],
    submissionMethod: "bandcamp-artist-store-upload-direct-fan-sales-route",
    feeRequired: false,
    feeAmount: "Registration is publicly described as free, while Bandcamp takes a sales commission and payment processing fees. Seller payout/tax and AI-content policy boundaries require manual review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for artist account/login, AI-content policy, seller/payment/tax setup, pricing, commission terms, file formats, artwork/metadata, email-gated downloads, merch options and release ownership. No account was created and no release was uploaded.",
    notes: "Public source material describes Bandcamp as a direct-to-fan platform where artists and labels upload music, set prices, sell downloads/merch and control their pages; recent 2026 coverage also indicates a strict AI-content policy boundary."
  },
  {
    name: "BandLab Social Music Publishing Collaboration Upload Route",
    websiteUrl: "https://www.bandlab.com/",
    submissionUrl: "https://www.bandlab.com/",
    sourceUrl: "https://www.bandlab.com/",
    sourceType: "automation_run_240_public_research",
    country: "Global / cloud DAW, social music and distribution-enabled creator platform",
    language: "en",
    genres: ["bandlab", "cloud-daw", "social-music", "collaboration", "music-publishing", "distribution-functions", "creator-upload", "freemium", "mobile-creation", "login-required", "manual-review"],
    submissionMethod: "bandlab-social-music-publishing-collaboration-upload-route",
    feeRequired: false,
    feeAmount: "Public sources describe BandLab as freemium with music creation, sharing, selling and distribution functions. Paid feature/account boundaries require manual review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for account/login, profile setup, collaboration permissions, publishing/distribution settings, upload/import formats, monetization/selling functions, freemium feature limits and rights ownership. No account was created, no collaboration started and no music was uploaded.",
    notes: "Public source material identifies BandLab as an active freemium online DAW and social creator platform with collaboration, sharing, selling and distribution functions, available via browser and mobile apps."
  }
];
