import type { PlatformInput } from '../models/types.js';

export const run237SeedPlatforms: PlatformInput[] = [
  {
    name: "TIDAL Upload Free US Artist Direct Publish Route",
    websiteUrl: "https://tidal.com/",
    submissionUrl: "https://tidal.com/upload",
    sourceUrl: "https://www.musicradar.com/music-tech/software-apps/no-your-uploaded-files-do-not-earn-royalties-tidal-launch-tidal-upload-an-artist-aimed-free-route-to-get-independent-music-on-its-platform-theres-cash-incentives-but-dont-expect-any-royalties",
    sourceType: "automation_run_237_public_research",
    country: "United States currently / TIDAL direct-to-platform artist upload route with broader global-streaming context",
    language: "en",
    genres: ["tidal", "direct-upload", "self-releasing-artists", "artist-upload", "streaming-platform", "playlist-spotlight", "upload-headliners", "rights-ownership", "us-18-plus-boundary", "login-session-app-boundary", "manual-review"],
    submissionMethod: "tidal-upload-free-us-artist-direct-publish-route",
    feeRequired: false,
    feeAmount: "Free public/manual route. Public 2025 coverage states TIDAL Upload is free at time of writing, with no streaming royalties for uploaded files and a U.S. 18+ availability boundary.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for TIDAL account/session, U.S. 18+ eligibility, rightsholder confirmation, public/private publishing controls, no-royalties economics, 5GB file and 200-track constraints, copyright/DMCA screening, editorial Spotlight review and Upload Headliners contest boundaries. No account was created and no track was uploaded.",
    notes: "Public source material says TIDAL Upload lets self-releasing artists, songwriters and creative stakeholders upload tracks directly to TIDAL, with metadata/catalogue functions, editorial playlist review, the Spotlight Program and a U.S.-based Upload Headliners contest. Strong manual-review route for owner-approved direct publishing only."
  },
  {
    name: "SubmitHub Free Premium Curator Playlist Blog Submission Route",
    websiteUrl: "https://www.submithub.com/",
    submissionUrl: "https://www.submithub.com/",
    sourceUrl: "https://www.submithub.com/",
    sourceType: "automation_run_237_public_research",
    country: "Global / curator, playlist, blog and influencer submission marketplace",
    language: "en",
    genres: ["submithub", "playlist-submission", "music-blogs", "curators", "social-media-influencers", "free-submissions", "premium-credits", "spotify-playlists", "feedback", "login-session-app-boundary", "payment-pricing-boundary", "manual-review"],
    submissionMethod: "submithub-free-premium-curator-playlist-blog-submission-route",
    feeRequired: false,
    feeAmount: "Freemium/manual route. Public source material describes SubmitHub as offering both free and paid submission options to playlist creators, music blogs and social media influencers.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for account/session, artist identity, song selection, curator targeting, free versus premium credit use, paid submission boundaries, anti-spam rules, playlist/blog fit, rights metadata, message content and no-guaranteed-placement expectations. No account was created, no curator was contacted and no music was submitted.",
    notes: "Public source material identifies SubmitHub as a submission marketplace where artists can submit to playlist creators, music blogs and social media influencers, with both free and paid submission paths. Relevant for MarcsMusic electronic, reggae, dubstep, chill/world and bass releases after manual curator-fit review."
  },
  {
    name: "Feature.fm Sponsored Songs Pre Save Music Marketing Route",
    websiteUrl: "https://feature.fm/",
    submissionUrl: "https://feature.fm/",
    sourceUrl: "https://feature.fm/",
    sourceType: "automation_run_237_public_research",
    country: "Global / music marketing, pre-save, contest and sponsored-song platform",
    language: "en",
    genres: ["feature-fm", "music-marketing", "smart-links", "pre-saves", "social-unlocks", "contests", "sponsored-songs", "native-advertising", "analytics", "retargeting", "payment-pricing-boundary", "login-session-app-boundary", "manual-review"],
    submissionMethod: "feature-fm-sponsored-songs-pre-save-music-marketing-route",
    feeRequired: true,
    feeAmount: "Paid/manual marketing route. Public source material describes Feature.fm as a music marketing and advertising platform with smart links, pre-saves, social unlocks, contests, sponsored songs, social advertising, retargeting and analytics.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for account/session, campaign objective, ad spend or plan pricing, sponsored-song placement, pre-save or social-unlock consent language, audience targeting, tracking pixels, analytics/privacy implications, landing-page copy and release-link accuracy. No account was created, no campaign was launched and no payment or ad spend was initiated.",
    notes: "Public source material identifies Feature.fm as an active music marketing, advertising and analytics platform for artists, labels and music marketers. It is a manual promotion route rather than an editorial submission queue, useful only after budget, targeting and release-goal approval."
  },
  {
    name: "Subvert Cooperative Artist Label Digital Download Marketplace Route",
    websiteUrl: "https://subvert.fm/",
    submissionUrl: "https://subvert.fm/",
    sourceUrl: "https://subvert.fm/",
    sourceType: "automation_run_237_public_research",
    country: "United States / global cooperative artist-label music marketplace",
    language: "en",
    genres: ["subvert", "cooperative-marketplace", "artist-label-membership", "digital-downloads", "pay-what-you-want", "sell-music", "free-downloads", "member-governance", "public-launch-2026", "commerce-boundary", "login-session-app-boundary", "manual-review"],
    submissionMethod: "subvert-cooperative-artist-label-digital-download-marketplace-route",
    feeRequired: false,
    feeAmount: "Free-first/manual commerce route. Public source material says artist and label membership is free, while buyer payments and optional checkout contributions create commerce and pricing boundaries.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for artist/label membership, cooperative terms, account/session, digital-download listing, price/pay-more/free-download settings, payout/tax/payment setup, AI-content restrictions, rights ownership, release metadata and storefront governance. No account was created, no music was listed and no commerce workflow was initiated.",
    notes: "Public source material describes Subvert as a members-owned cooperative online music distribution platform publicly launched on May 12, 2026, where independent musicians and labels can distribute, sell, set prices, offer pay-more options or free downloads. Strong direct-to-fan candidate after legal, pricing and catalog review."
  },
  {
    name: "Zedwap Zambia Artist Upload Streaming Download Route",
    websiteUrl: "https://zedwap.com/",
    submissionUrl: "https://zedwap.com/",
    sourceUrl: "https://zedwap.com/",
    sourceType: "automation_run_237_public_research",
    country: "Zambia / African music streaming and download discovery platform",
    language: "en",
    genres: ["zedwap", "zambian-music", "african-music", "artist-upload", "streaming", "downloads", "web-android", "registration-boundary", "login-session-app-boundary", "manual-review"],
    submissionMethod: "zedwap-zambia-artist-upload-streaming-download-route",
    feeRequired: false,
    feeAmount: "Free public/manual route. Public source material describes free ad-supported streaming/download features and artist-upload capability; no public upfront submission fee was observed.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for artist registration/upload, regional fit, African/Zambian audience relevance, metadata quality, rights ownership, public streaming/download availability, ad-supported terms and app/site account boundaries. No account was created and no track was uploaded.",
    notes: "Public source material identifies Zedwap as an active Zambian digital audio streaming and media service that allows artists to upload music and listeners to stream or download tracks, with web and Android clients and reported multi-million monthly user reach. Potential African discovery route for MarcsMusic world-fusion or Afro-influenced releases after manual fit review."
  }
];
