import type { PlatformInput } from '../models/types.js';

export const run205SeedPlatforms: PlatformInput[] = [
  {
    name: "MusoSoup Global Curator Press Playlist Campaign Route",
    websiteUrl: "https://musosoup.com/",
    submissionUrl: "https://app.musosoup.com/submit",
    sourceUrl: "https://musosoup.com/",
    sourceType: "automation_run_205_public_research",
    country: "Global / UK-based music promotion, curator, press, playlist and radio campaign platform",
    language: "en",
    genres: ["music-promotion", "curator-marketplace", "playlisting", "press", "radio", "electronic", "reggae", "world", "independent-artists", "manual-review"],
    submissionMethod: "official-musosoup-curator-press-playlist-campaign-route",
    feeRequired: false,
    feeAmount: "Free-first/freemium/manual route. Official MusoSoup pages say artists can submit music for free, then create an account and pay a campaign fee if the submission is accepted; free coverage options and paid offers/campaign fees are disclosed.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for app submission boundary, campaign activation fee, curator-offer terms, release timing, rights ownership, MP3/link assets, press context, AI/botted-playlist policy review and coverage fit. No account, upload, campaign or payment workflow was started.",
    notes: "Verified through official MusoSoup pages showing Submit music/Sign in links, independent-artist campaign flow, curator/press/playlist/radio coverage, 2026 blog activity, 85k artists/3k curators/120 countries claims and pricing/payment boundaries."
  },
  {
    name: "DailyPlaylists Free Spotify Curator Marketplace Submission Route",
    websiteUrl: "https://dailyplaylists.com/",
    submissionUrl: "https://dailyplaylists.com/",
    sourceUrl: "https://dailyplaylists.com/",
    sourceType: "automation_run_205_public_research",
    country: "Global / Spotify playlist pitching and curator marketplace platform",
    language: "en",
    genres: ["spotify-playlists", "playlist-pitching", "curator-marketplace", "electronic", "dubstep", "reggae", "afropop", "independent-artists", "manual-review"],
    submissionMethod: "official-dailyplaylists-free-spotify-curator-marketplace-route",
    feeRequired: false,
    feeAmount: "Free-first/freemium/manual route. Official page says artists can submit music for free through the Standard tier, with premium credits and professional tools available.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for Spotify track selection, sign-in/session boundary, playlist/curator matching, standard vs premium credit choices, professional-tier tools, consent/terms, track metadata and campaign-volume limits. No login, playlist submission, premium credit or payment action was taken.",
    notes: "Verified through official DailyPlaylists page showing Submit a Song, marketplace of 18,000+ playlists, 75M+ submissions, 500k+ artists, Standard/Premium/Professional tiers, 2026 copyright footer and public business contact info@dailyplaylists.com."
  },
  {
    name: "EmuBands Paid Low-Cost DSP Distribution Upload Route",
    websiteUrl: "https://www.emubands.com/",
    submissionUrl: "https://dashboard.emubands.com/signup",
    sourceUrl: "https://www.emubands.com/",
    sourceType: "automation_run_205_public_research",
    country: "Global / UK-based digital music distribution service for artists and labels",
    language: "en",
    genres: ["digital-distribution", "dsp-upload", "spotify", "apple-music", "amazon-music", "tiktok", "electronic", "reggae", "independent-artists", "manual-review"],
    submissionMethod: "official-emubands-paid-low-cost-dsp-distribution-upload-route",
    feeRequired: true,
    feeAmount: "Paid/manual distribution route. Official page describes low-cost distribution with either one-time setup fees per release or Premium unlimited distribution, while allowing artists to keep 100% of royalties.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for paid release setup, account/dashboard boundary, store selection, UPC/metadata, release date, copyright ownership, royalty/payout details, Premium-vs-one-time-fee decision and audio/artwork readiness. No signup, release upload or payment workflow was started.",
    notes: "Verified through official EmuBands homepage showing Pricing and Plans, Sign Up/Login, global DSP distribution to Spotify/Apple/Amazon and more, 100% royalties, one-time/Premium pricing models and July 6, 2026 news activity."
  },
  {
    name: "Record Union Global DSP Release Upload Pricing Route",
    websiteUrl: "https://www.recordunion.com/",
    submissionUrl: "https://www.recordunion.com/",
    sourceUrl: "https://www.recordunion.com/",
    sourceType: "automation_run_205_public_research",
    country: "Global / Sweden-based digital music distribution and release-upload platform",
    language: "en",
    genres: ["digital-distribution", "release-upload", "spotify", "beatport", "tiktok", "youtube-music", "electronic", "world", "independent-artists", "manual-review"],
    submissionMethod: "official-record-union-global-dsp-release-upload-pricing-route",
    feeRequired: true,
    feeAmount: "Free account/manual paid release route. Official page says artists can join free and pay nothing until ready to release tracks; Top Dog and World Domination annual per-release pricing plus UPC fee are disclosed.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for account/session boundary, release plan choice, UPC need, DSP/platform selection, release date, metadata, copyright ownership, royalty splits, playlist-pitch priority upsell and audio/artwork readiness. No account, upload, release or payment action was taken.",
    notes: "Verified through official Record Union page showing upload to Spotify and 20+ global music services, free join-until-release language, pricing tiers, Beatport/TikTok/YouTube Music delivery, EPK, royalty splits and 2026 footer."
  },
  {
    name: "UnitedMasters Independent Artist Distribution Brand Sync Route",
    websiteUrl: "https://unitedmasters.com/",
    submissionUrl: "https://unitedmasters.com/",
    sourceUrl: "https://unitedmasters.com/",
    sourceType: "automation_run_205_public_research",
    country: "Global / US-based independent artist distribution, marketing, brand and sync platform",
    language: "en",
    genres: ["digital-distribution", "brand-sync", "playlist-pitching", "artist-marketing", "spotify", "apple-music", "tidal", "hip-hop", "electronic", "manual-review"],
    submissionMethod: "official-unitedmasters-independent-artist-distribution-brand-sync-route",
    feeRequired: false,
    feeAmount: "Free-first/freemium/manual route. Official page shows paid DEBUT+/SELECT plans, invite-only PARTNER tier and a free social-distribution option; distribution to full DSPs requires plan and owner review.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for sign-up/login, plan selection, upload files/metadata/artwork, collaborator royalty splits, approval workflow, social-vs-full DSP distribution, playlist/radio pitching, brand/sync deal eligibility and payout setup. No account, upload, approval submission or payment action was taken.",
    notes: "Verified through official UnitedMasters page showing Sign Up/Login, distribution to Spotify/Apple/TIDAL/150+ services, DEBUT+/SELECT/PARTNER plans, free social distribution, brand/sync opportunities, playlist/radio pitching and 2026 footer."
  }
];
