import type { PlatformInput } from '../models/types.js';

export const run209BaseSeedPlatforms: PlatformInput[] = [
  {
    name: "BeatStars Global Producer Artist Licensing Marketplace Upload Route",
    websiteUrl: "https://www.beatstars.com/",
    submissionUrl: "https://www.beatstars.com/",
    sourceUrl: "https://www.beatstars.com/",
    sourceType: "automation_run_209_public_research",
    country: "Global / music licensing marketplace and creator collaboration platform",
    language: "en",
    genres: ["licensing", "beats", "collaboration", "hip-hop", "rnb", "pop", "electronic", "producer-marketplace", "manual-review"],
    submissionMethod: "beatstars-global-producer-artist-licensing-marketplace-upload-route",
    feeRequired: false,
    feeAmount: "Free-first/freemium/manual creator marketplace route. Public validation describes BeatStars as a global subscription-based music licensing platform with free and paying subscription models, non-exclusive/exclusive licensing, collaboration, distribution and publishing tools.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for account/login, producer versus artist positioning, upload/licensing route, rights and sample clearance, pricing/license terms, split/publishing metadata, catalog-fit review and paid-plan boundary. No account was created, no files were uploaded, no licenses were configured and no payment was initiated.",
    notes: "Queued for manual review as an authorized public creator marketplace route suitable for beats, instrumentals, collaborations, licensing and producer-led discovery. Activity was validated from public search results; no private portal was accessed."
  },
  {
    name: "ReverbNation Independent Artist Profile Opportunities Upload Route",
    websiteUrl: "https://www.reverbnation.com/",
    submissionUrl: "https://www.reverbnation.com/",
    sourceUrl: "https://www.reverbnation.com/",
    sourceType: "automation_run_209_public_research",
    country: "Global / independent artist services, profile and opportunity platform",
    language: "en",
    genres: ["artist-profile", "independent", "opportunities", "promotion", "sync", "events", "all-genres", "manual-review"],
    submissionMethod: "reverbnation-independent-artist-profile-opportunities-upload-route",
    feeRequired: false,
    feeAmount: "Free-first/manual artist-services route. Public validation describes ReverbNation as active and focused on the independent music industry, with musician/producer/venue collaboration and artist-discovery tools.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for profile/account control, artist biography, track upload, opportunity selection, rights, metadata, location/genre positioning, promotional settings and privacy boundaries. No account was created, no files were uploaded, no opportunity was submitted and no message was sent.",
    notes: "Queued as a legitimate manual artist-services route, especially for profile discovery, opportunities, shows, promotion and possible licensing/industry submissions. No login or private flow was accessed."
  },
  {
    name: "SoundClick Artist Upload Store Licensing Chart Profile Route",
    websiteUrl: "https://www.soundclick.com/",
    submissionUrl: "https://www.soundclick.com/",
    sourceUrl: "https://www.soundclick.com/",
    sourceType: "automation_run_209_public_research",
    country: "Global / music-based social community and artist upload platform",
    language: "en",
    genres: ["artist-upload", "social-music", "streaming", "downloads", "licensing", "charts", "electronic", "hip-hop", "reggae", "manual-review"],
    submissionMethod: "soundclick-artist-upload-store-licensing-chart-profile-route",
    feeRequired: false,
    feeAmount: "Free-first/freemium/manual artist upload route. Public validation says SoundClick allows unlimited MP3 uploads, streams/downloads/store sales/licensing and optional fee-based VIP services.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for account/login, MP3 upload choice, streaming/download/sale/license settings, artist profile setup, copyright/rights status, explicit/clean metadata, chart/genre positioning and optional VIP/payment boundary. No account was created, no upload occurred and no store/license settings were changed.",
    notes: "Queued as a public artist upload and discovery route with social/profile, stream, download, store and licensing options. Activity and legal-download context were validated from public sources."
  },
  {
    name: "ZIPDJ Global DJ Radio Promo Pool Label Servicing Route",
    websiteUrl: "https://www.zipdj.com/",
    submissionUrl: "https://www.zipdj.com/",
    sourceUrl: "https://www.zipdj.com/",
    sourceType: "automation_run_209_public_research",
    country: "Global / Canada-based DJ, club, commercial-radio, online-radio and college-radio promo pool",
    language: "en",
    genres: ["dj-pool", "promo-pool", "electronic", "club", "dance", "urban", "radio", "college-radio", "manual-review"],
    submissionMethod: "zipdj-global-dj-radio-promo-pool-label-servicing-route",
    feeRequired: true,
    feeAmount: "Paid/manual promo-pool route. Public validation describes ZIPDJ as an active subscription-based digital music pool distributing promotional releases to professional club, commercial radio, online radio and campus/college radio DJs, with label partners and feedback/data collection.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for label/artist eligibility, subscription or servicing terms, clean/club/radio edits, release timing, rights, metadata, territory/genre fit, promo-only status and reporting/feedback terms. No account was created, no promo was serviced, no files were uploaded and no payment was initiated.",
    notes: "Queued as a manual global DJ/radio promo-pool route relevant to electronic, dance, urban, club and radio-friendly MarcsMusic releases. No private record-pool access was attempted."
  },
  {
    name: "TopHit Global Radio TV Airplay Testing Upload Distribution Route",
    websiteUrl: "https://tophit.com/",
    submissionUrl: "https://tophit.com/",
    sourceUrl: "https://tophit.com/",
    sourceType: "automation_run_209_public_research",
    country: "Global / radio, TV, chart, airplay-monitoring and media-distribution platform",
    language: "en",
    genres: ["radio-distribution", "airplay-testing", "charts", "media", "pop", "dance", "electronic", "international", "manual-review"],
    submissionMethod: "tophit-global-radio-tv-airplay-testing-upload-distribution-route",
    feeRequired: false,
    feeAmount: "Manual app/upload route. Public validation describes TopHit as a worldwide-oriented platform where producers and rights holders upload music/video content, radio and TV partners review/download suitable songs, and airplay/streaming statistics are tracked across many countries.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for rightsholder registration, upload eligibility, country/territory strategy, radio-edit preparation, language/genre fit, metadata, publishing/label data, platform terms and media-testing implications. No account was created, no files were uploaded, no campaign was started and no payment was initiated.",
    notes: "Queued cautiously as a global media/radio distribution and testing route. Good candidate only after confirming terms, target territories, rights, release timing and MarcsMusic radio-edit readiness."
  }
];
