import type { PlatformInput } from '../models/types.js';

export const run231BaseSeedPlatforms: PlatformInput[] = [
  {
    name: "KLOF Magazine 320kbps Download Link Submission Email Route",
    websiteUrl: "https://klofmag.com/",
    submissionUrl: "https://klofmag.com/about-klof-magazine/",
    sourceUrl: "https://klofmag.com/about-klof-magazine/",
    sourceType: "automation_run_231_public_research",
    country: "United Kingdom / global independent music magazine",
    language: "en",
    genres: ["music-blog", "online-magazine", "album-review", "folk", "experimental", "ambient", "avant-garde", "jazz", "field-recordings", "electro-acoustic", "music-submission-email", "mp3-320-download-link", "bandcamp-code", "dropbox-link", "free-first", "cookie-consent-boundary", "manual-review"],
    submissionMethod: "klof-magazine-320kbps-download-link-submission-email-route",
    feeRequired: false,
    feeAmount: "Free manual editorial submission email route. Official KLOF About page lists submissions@klofmag.com and does not list a submission payment requirement.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for outbound email, 320kbps MP3/download-link selection, background/credits text, genre/editorial fit, Bandcamp/Dropbox link permissions and cookie/consent boundary. No email was sent and no files were transferred.",
    notes: "Official KLOF About page lists a submissions email and asks for MP3 320kbps download links such as Dropbox or Bandcamp codes, plus background and credits. The official site describes current coverage areas including folk, experimental, ambient, avant-garde, jazz, field recordings and electro-acoustic work, and the homepage/copyright/cookie surfaces show active 2026 publication context."
  },
  {
    name: "Soundplate Free Spotify Deezer Playlist Submission Route",
    websiteUrl: "https://play.soundplate.com/",
    submissionUrl: "https://play.soundplate.com/",
    sourceUrl: "https://play.soundplate.com/",
    sourceType: "automation_run_231_public_research",
    country: "United Kingdom / global playlist submission marketplace",
    language: "en",
    genres: ["playlist-submission", "spotify-playlist", "deezer-playlist", "independent-curators", "playlist-grid", "public-submission-app", "free-first", "no-spam-guidance", "manual-review"],
    submissionMethod: "soundplate-free-spotify-deezer-playlist-submission-route",
    feeRequired: false,
    feeAmount: "Free manual playlist-submission route. Official Play Soundplate page describes free submissions to Spotify and Deezer playlists and does not show a submission payment requirement on the public route.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for playlist selection, Spotify/Deezer track URL, curator-fit check, no-spam compliance, any per-playlist form/app boundary and consent/cookie handling. No form was submitted.",
    notes: "Official Play Soundplate page says artists can discover and submit music to Spotify and Deezer playlists, select a playlist from the grid, and submit to hundreds of independent curators for free, with guidance to use relevant playlists and avoid spamming curators."
  },
  {
    name: "RepostExchange SoundCloud Partner Credit Campaign Promotion Route",
    websiteUrl: "https://repostexchange.com/",
    submissionUrl: "https://repostexchange.com/welcome",
    sourceUrl: "https://repostexchange.com/welcome",
    sourceType: "automation_run_231_public_research",
    country: "United Kingdom / global SoundCloud creator promotion",
    language: "en",
    genres: ["soundcloud-promotion", "repost-campaign", "creator-network", "feedback", "credits", "official-soundcloud-partner", "free-first", "freemium", "paid-credits-boundary", "soundcloud-login-boundary", "manual-review"],
    submissionMethod: "repostexchange-soundcloud-partner-credit-campaign-promotion-route",
    feeRequired: false,
    feeAmount: "Freemium manual SoundCloud promotion route. Official RepostExchange page says it is free to use, offers starting credits, and has optional paid credits/plans for extra reach.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for SoundCloud OAuth/login, track choice, credit spending, repost/follow/like/comment permissions, campaign setup, optional paid-credit/plan boundary and anti-bot/fake-signup controls. No account was connected and no campaign/action was initiated.",
    notes: "Official RepostExchange page says it is an official SoundCloud partner, free to use, used by more than 500,000 SoundCloud creators, lets artists choose a track to promote with credits, and includes login/connect-with-SoundCloud plus optional paid credits/plans boundaries."
  },
  {
    name: "TopHit Rights Holder Upload Radio TV Distribution Route",
    websiteUrl: "https://tophit.com/",
    submissionUrl: "https://tophit.com/",
    sourceUrl: "https://tophit.com/",
    sourceType: "automation_run_231_public_research",
    country: "United States / international radio TV airplay distribution platform",
    language: "en",
    genres: ["radio-distribution", "tv-distribution", "airplay-monitoring", "rights-holder-upload", "artist-upload", "song-testing", "radio-station-download", "chart-platform", "login-session-app-boundary", "manual-review"],
    submissionMethod: "tophit-rights-holder-upload-radio-tv-distribution-route",
    feeRequired: false,
    feeAmount: "Manual rights-holder upload route. Public source material describes rights holders registering and uploading works to TopHit for radio/TV review and distribution; no public auto-submit or payment workflow was initiated.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for rights-holder registration/login, territory/language fit, master/metadata/video rights, possible commercial terms, radio/TV testing workflow and app access boundary. No account was created and no files were uploaded.",
    notes: "Public source material describes TopHit as a worldwide-oriented music distribution, airplay-monitoring and chart platform where artists, songwriters, DJs, labels and publishers upload works and radio/TV partners evaluate and download suitable tracks. The official public URL returned a 403/app-access boundary during this run, so no protected workflow was accessed."
  },
  {
    name: "Radiooooo Community Curated Global Map Upload Route",
    websiteUrl: "https://app.radiooooo.com/",
    submissionUrl: "https://app.radiooooo.com/",
    sourceUrl: "https://app.radiooooo.com/",
    sourceType: "automation_run_231_public_research",
    country: "France / global curated music discovery map",
    language: "en",
    genres: ["music-discovery", "curated-map", "community-upload", "global-music", "decade-country-metadata", "human-curation", "free-trial-boundary", "subscription-boundary", "javascript-app-boundary", "manual-review"],
    submissionMethod: "radiooooo-community-curated-global-map-upload-route",
    feeRequired: false,
    feeAmount: "Manual app-boundary upload/curation route. Public source material describes user uploads and community curation; the platform also has free-trial/subscription boundaries for use.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for app/login/session, upload eligibility, country/decade metadata, copyright/rights, curation fit and free-trial/subscription boundaries. No account was created, no login was used and no track was uploaded.",
    notes: "Public source material describes Radiooooo as a Paris-based music discovery website/app where users upload songs or tracks that are curated by DJs/producers for an interactive global map, while the official app route displayed a JavaScript application boundary during this run."
  }
];
