import type { PlatformInput } from '../models/types.js';

export const run20SeedPlatforms: PlatformInput[] = [
  {
    name: 'Bandcamp Artist Store Direct-to-Fan Upload Route',
    websiteUrl: 'https://bandcamp.com/artists',
    submissionUrl: 'https://bandcamp.com/artists',
    sourceUrl: 'https://bandcamp.com/artists',
    sourceType: 'automation_run_20_public_research',
    country: 'United States / global direct-to-fan reach',
    language: 'en',
    genres: ['electronic', 'reggae', 'dub', 'world', 'bass-music', 'independent'],
    submissionMethod: 'artist-account-upload-storefront-route-needs-manual-rights-pricing-and-policy-review',
    feeRequired: false,
    loginRequired: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Artist account, upload, rights ownership, pricing, release metadata, payout and current content-policy review are required before publishing music.',
    notes: 'Direct-to-fan upload/storefront opportunity. No account creation, upload, pricing action, terms acceptance or protected workflow was attempted.'
  },
  {
    name: 'SoundCloud Creator Upload and Artist Discovery Route',
    websiteUrl: 'https://soundcloud.com/for-artists',
    submissionUrl: 'https://soundcloud.com/for-artists',
    sourceUrl: 'https://soundcloud.com/for-artists',
    sourceType: 'automation_run_20_public_research',
    country: 'Germany / United States / global creator reach',
    language: 'en',
    genres: ['electronic', 'dubstep', 'drum-and-bass', 'house', 'reggae', 'dance', 'bass-music'],
    submissionMethod: 'creator-account-upload-profile-discovery-route-needs-manual-rights-and-terms-review',
    feeRequired: false,
    loginRequired: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Requires account access, track upload, rights confirmation, profile/release settings and current AI/terms review before publishing.',
    notes: 'Relevant as a discovery and streaming-link source for future submissions. No login, upload, repost, message, scraping or bypass was performed.'
  },
  {
    name: 'Audiomack Creator Upload and Emerging Artist Route',
    websiteUrl: 'https://audiomack.com/',
    submissionUrl: 'https://audiomack.com/',
    sourceUrl: 'https://audiomack.com/',
    sourceType: 'automation_run_20_public_research',
    country: 'United States / global with strong Africa and Caribbean reach',
    language: 'en',
    genres: ['afrobeats', 'dancehall', 'reggae', 'latin', 'electronic', 'hip-hop', 'world'],
    submissionMethod: 'creator-account-upload-and-promotion-route-needs-manual-rights-review',
    feeRequired: false,
    loginRequired: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Creator account, upload, monetization eligibility, ownership and platform policy review are required before using this route.',
    notes: 'Strong discovery route for global and Caribbean-adjacent genres. No upload, creator-login, follower messaging, promotion action or protected workflow was attempted.'
  },
  {
    name: 'SoundOn by TikTok Artist Distribution Route',
    websiteUrl: 'https://www.soundon.global/',
    submissionUrl: 'https://www.soundon.global/',
    sourceUrl: 'https://www.soundon.global/',
    sourceType: 'automation_run_20_public_research',
    country: 'Global with territory eligibility requirements',
    language: 'en',
    genres: ['electronic-pop', 'dance', 'afrobeats', 'latin', 'reggae', 'world', 'viral-music'],
    submissionMethod: 'distribution-upload-and-tiktok-marketing-route-needs-manual-territory-rights-review',
    feeRequired: false,
    loginRequired: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Requires account, territory eligibility, copyright ownership, distribution conflicts, release metadata and payout review before upload.',
    notes: 'Relevant for TikTok discovery and DSP distribution. No registration, upload, distributor switch, rights declaration or terms acceptance was performed.'
  },
  {
    name: 'TIDAL Upload Independent Artist Self-Publishing Route',
    websiteUrl: 'https://tidal.com/',
    submissionUrl: 'https://tidal.com/',
    sourceUrl: 'https://tidal.com/',
    sourceType: 'automation_run_20_public_research',
    country: 'United States eligibility / potential future global expansion',
    language: 'en',
    genres: ['electronic', 'dance', 'reggae', 'world', 'independent', 'pop'],
    submissionMethod: 'direct-upload-self-publishing-route-needs-eligibility-and-royalty-review',
    feeRequired: false,
    loginRequired: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Eligibility, territory, ownership, copyright compliance and no-royalty upload terms must be reviewed before publishing.',
    notes: 'Time-sensitive platform recheck for independent uploads. No account, upload, copyright declaration or application flow was attempted.'
  },
  {
    name: 'ReverbNation Artist Opportunities and Profile Route',
    websiteUrl: 'https://www.reverbnation.com/',
    submissionUrl: 'https://www.reverbnation.com/',
    sourceUrl: 'https://www.reverbnation.com/',
    sourceType: 'automation_run_20_public_research',
    country: 'United States / global independent artist reach',
    language: 'en',
    genres: ['independent', 'electronic', 'reggae', 'world', 'pop', 'rock', 'hip-hop'],
    submissionMethod: 'artist-profile-and-opportunity-marketplace-route-needs-account-fee-and-opportunity-review',
    feeRequired: false,
    loginRequired: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Artist account, EPK/profile setup, opportunity selection, possible fees/deadlines and rights terms require manual review.',
    notes: 'Opportunity marketplace and artist profile route. No signup, paid opportunity selection, submission, upload or automated outreach was performed.'
  },
  {
    name: 'Subvert.fm Cooperative Music Marketplace Artist Route',
    websiteUrl: 'https://subvert.fm/',
    submissionUrl: 'https://subvert.fm/',
    sourceUrl: 'https://subvert.fm/',
    sourceType: 'automation_run_20_public_research',
    country: 'United States / global cooperative marketplace reach',
    language: 'en',
    genres: ['independent', 'electronic', 'experimental', 'reggae', 'world', 'direct-to-fan'],
    submissionMethod: 'member-alpha-cooperative-marketplace-route-needs-manual-membership-review',
    feeRequired: false,
    loginRequired: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Member/alpha access, cooperative membership, storefront terms and platform-readiness need manual review before use.',
    notes: 'Emerging Bandcamp-alternative candidate. No membership, login, listing creation, payment, upload or protected workflow was attempted.'
  },
  {
    name: 'Mikseri.net Independent Music Upload Community Route',
    websiteUrl: 'https://www.mikseri.net/',
    submissionUrl: 'https://www.mikseri.net/',
    sourceUrl: 'https://www.mikseri.net/',
    sourceType: 'automation_run_20_public_research',
    country: 'Finland / global niche independent reach',
    language: 'fi',
    genres: ['independent', 'electronic', 'experimental', 'dance', 'demo-community'],
    submissionMethod: 'registered-user-upload-community-route-needs-language-account-and-license-review',
    feeRequired: false,
    loginRequired: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Finnish-language registration, upload format, licensing and community rules require manual review before publishing.',
    notes: 'Niche independent upload community. No registration, upload, translation-based form filling or protected workflow was attempted.'
  }
];
