import type { PlatformInput } from '../models/types.js';

export const run248BaseSeedPlatforms: PlatformInput[] = [
  {
    "name": "Fresh On The Net Listening Post Weekly Track Submission Route",
    "websiteUrl": "https://freshonthenet.co.uk/",
    "submissionUrl": "https://freshonthenet.co.uk/submit/",
    "sourceUrl": "https://freshonthenet.co.uk/submit/",
    "sourceType": "automation_run_248_public_research",
    "country": "Global / UK-based independent music blog, listening post and weekly moderator review route",
    "language": "en",
    "genres": ["fresh-on-the-net", "listening-post", "music-blog", "weekly-submission-window", "fresh-faves", "moderator-review", "free-first", "public-form", "limited-window", "email-observed", "manual-review"],
    "submissionMethod": "fresh-on-the-net-listening-post-weekly-track-submission-route",
    "feeRequired": false,
    "feeAmount": "Official submit page describes a free weekly one-track submission window, capped at 200 tracks or Wednesday evening; no paid route observed on the submission page.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "Owner review required because the inbox is window/cap limited, the page currently shows the inbox closed until Jul 13 while also noting the Listening Post opens on July 10, only one public worldwide track is allowed per week, AI-generated tracks are prohibited, repeat/remix/private/restricted tracks are excluded, and social/profile metadata must be checked. No form was submitted.",
    "notes": "Official Fresh On The Net submit page says any artist can send one track per week, the team listens, selected tracks go to the Listening Post and Fresh Faves review pipeline, and recent posts show July 2026 activity. A conditional radio-consideration email appears on-page but requires FOTN-first submission; it was not used or probed."
  },
  {
    "name": "KEXP Music Director Radio Rotation Consideration Email Route",
    "websiteUrl": "https://www.kexp.org/",
    "submissionUrl": "mailto:md@kexp.org",
    "sourceUrl": "https://www.kexp.org/contact/",
    "sourceType": "automation_run_248_public_research",
    "country": "Global / US-based listener-powered public radio rotation consideration route",
    "language": "en",
    "genres": ["kexp", "radio-airplay", "music-director", "rotation-consideration", "indie", "alternative", "electronic", "public-radio", "business-email-observed", "usable-public-submission-email", "free-first", "manual-review"],
    "submissionMethod": "kexp-music-director-radio-rotation-consideration-email-route",
    "feeRequired": false,
    "feeAmount": "No fee observed on the official KEXP contact route for music rotation consideration.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "Owner review required before sending any email, because KEXP provides a direct music-rotation consideration email and guidelines link; track format, clean/radio edit suitability, EPK link, metadata, pitch wording and anti-spam frequency must be owner approved. No outbound email was sent and no deliverability probing was performed.",
    "notes": "Official KEXP contact page says to submit music for KEXP rotation consideration by emailing Music Director Chris Sanley and the Music Department at md@kexp.org. Public direct submission email was observed and stored as a manual-review route only."
  },
  {
    "name": "Triple J Unearthed Australian Artist Upload Airplay Route",
    "websiteUrl": "https://www.abc.net.au/triplejunearthed",
    "submissionUrl": "https://www.abc.net.au/triplejunearthed",
    "sourceUrl": "https://www.abc.net.au/triplejunearthed",
    "sourceType": "automation_run_248_public_research",
    "country": "Australia / ABC triple j Unearthed artist upload, reviews, competitions and airplay route",
    "language": "en",
    "genres": ["triple-j-unearthed", "abc", "australian-artists", "track-upload", "staff-reviews", "airplay", "competitions", "indie", "electronic", "hip-hop", "free-first", "login-required", "manual-review"],
    "submissionMethod": "triple-j-unearthed-australian-artist-upload-airplay-route",
    "feeRequired": false,
    "feeAmount": "No fee observed on the public triple j Unearthed pages; upload/account eligibility requires owner review.",
    "loginRequired": true,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "Owner review required for Australia eligibility, artist account creation, upload terms, explicit tagging, track metadata, public profile, reviews, competition entry, ABC privacy/terms and potential airplay routing. No account was created and no track was uploaded.",
    "notes": "Official ABC triple j Unearthed homepage shows current July 2026 staff reviews, featured artists, Track of the Day, popular tracks, competitions and states the platform has over 170,000 tracks from around 85,000 artists. Public music-submission email was not observed; route is upload/account based."
  },
  {
    "name": "BBC Music Introducing UK Upload Tool Radio Network Route",
    "websiteUrl": "https://www.bbc.co.uk/introducing",
    "submissionUrl": "https://www.bbc.co.uk/introducing",
    "sourceUrl": "https://www.bbc.co.uk/introducing",
    "sourceType": "automation_run_248_public_research",
    "country": "United Kingdom / BBC Introducing local and national radio upload route",
    "language": "en",
    "genres": ["bbc-introducing", "radio-upload", "uk-artists", "local-radio", "radio-1", "1xtra", "radio-2", "6-music", "asian-network", "festival-stages", "free-first", "login-required", "ugc-boundary", "manual-review"],
    "submissionMethod": "bbc-music-introducing-uk-upload-tool-radio-network-route",
    "feeRequired": false,
    "feeAmount": "No fee observed for the BBC Introducing upload route; UGC terms and UK/postcode eligibility require owner review.",
    "loginRequired": true,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "Owner review required for UK/postcode eligibility, account registration, BBC UGC terms, upload rights, track selection, local show routing, national radio forwarding potential, AI/music policy fit and metadata. No account was created and no upload was attempted.",
    "notes": "Public BBC Introducing information describes an upload tool that routes music to local Introducing teams and may forward tracks to national BBC networks; current public references show the platform active with 2025 artist-of-the-year context. Public direct music-submission email was not observed."
  },
  {
    "name": "Amazing Radio Amazing Artists Upload Radio Discovery Route",
    "websiteUrl": "https://amazingradio.com/",
    "submissionUrl": "https://amazingradio.com/upload",
    "sourceUrl": "https://amazingradio.com/",
    "sourceType": "automation_run_248_public_research",
    "country": "Global / UK and US new-and-emerging artist radio upload and discovery route",
    "language": "en",
    "genres": ["amazing-radio", "amazing-artists", "radio-airplay", "new-and-emerging-artists", "unsigned-artists", "track-upload", "cmj", "free-first", "login-required", "javascript-app-boundary", "manual-review"],
    "submissionMethod": "amazing-radio-amazing-artists-upload-radio-discovery-route",
    "feeRequired": false,
    "feeAmount": "No fee observed from public homepage/searchable information for the artist upload route; account/upload details require owner review inside the app.",
    "loginRequired": true,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "Owner review required because the public homepage is JavaScript-app gated, the upload route likely requires artist account/session, track upload, rights/metadata, radio suitability and profile setup. No app session was initiated and no track was uploaded.",
    "notes": "Amazing Radio public homepage is active but JavaScript-gated in the crawler. Publicly indexed information describes Amazing Radio as an international station for new and emerging artists where artists can submit music via the website. Public music-submission email was not observed."
  }
];