import type { PlatformInput } from '../models/types.js';

export const run292SeedPlatforms: PlatformInput[] = [
  {
    "name": "Radio K / KUOM Official Digital and Physical Music Submission Route",
    "websiteUrl": "https://radiok.org/",
    "submissionUrl": "https://radiok.org/submitting-music",
    "sourceUrl": "https://radiok.org/submitting-music",
    "sourceType": "automation_run_292_public_research",
    "country": "United States / Minneapolis global-listener student-run independent radio",
    "language": "en",
    "genres": ["radio-k", "kuom", "college-radio", "independent", "electronic", "world", "reggae", "hip-hop", "digital-download-link", "lossless-audio", "physical-release", "protected-email", "manual-review"],
    "submissionMethod": "official-radio-k-music-department-email-or-physical-release-route",
    "feeRequired": false,
    "feeAmount": "No submission fee or payment requirement is stated in Radio K's official music-submission guidance.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "Radio K authorizes physical releases and digital submissions to its Music Department. Digital delivery must use a linked .zip file on Google Drive, Dropbox or a similar service with the highest-quality files available, preferably lossless WAV or FLAC; Bandcamp download codes or free-release links are also accepted. The official email is protected in the rendered page and was not decoded or copied into the automated dataset. A human must open the official page, confirm the live address, verify rights and link permissions, prepare the required metadata and avoid prohibited tracking follow-ups.",
    "notes": "Verified on 2026-07-11 from Radio K's official submission, contact and active homepage pages. The station publishes current June 2026 content and new electronic additions, accepts one physical copy or a compliant digital package, asks for a concise sheet with bio, contact details, comparable artists, FCC-unfriendly songs and 2-3 focus tracks, and says it cannot accept tracking-status emails. No email was sent, no link or file was delivered, no protected address was decoded and no physical package was prepared."
  },
  {
    "name": "WPRB 103.3 FM Official Music Director Email and Physical Submission Route",
    "websiteUrl": "https://wprb.com/",
    "submissionUrl": "mailto:music@wprb.com",
    "sourceUrl": "https://wprb.com/music-submissions/",
    "sourceType": "automation_run_292_public_research",
    "country": "United States / Princeton community-supported freeform independent radio",
    "language": "en",
    "genres": ["wprb", "college-radio", "freeform", "electronic", "reggae", "world", "hip-hop", "independent", "digital-email", "physical-media", "manual-review"],
    "submissionMethod": "official-wprb-music-director-email-or-prioritized-physical-media-route",
    "feeRequired": false,
    "feeAmount": "No submission fee or payment requirement is stated on WPRB's official music-submissions page.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "WPRB publicly authorizes music submissions by email to music@wprb.com and accepts CDs, CD-Rs, LPs, 12-inch, 10-inch and 7-inch physical media, with physical submissions explicitly prioritized. The page does not publish complete digital attachment, download-link, metadata or clean-edit requirements. A human must choose the route, confirm current digital delivery expectations before sending assets, verify rights and prepare any physical package.",
    "notes": "Verified on 2026-07-11 from WPRB's official music-submissions page and active station homepage. The station publishes freeform schedules and playlists spanning electronic, reggae, world, hip-hop and other independent genres, and the official page displays a 2026 copyright notice. The music@wprb.com business address is purpose-specific and publicly displayed. No email was sent, no attachment or link was delivered and no physical media was prepared."
  },
  {
    "name": "KALX 90.7 FM Official Physical-Only Airplay Submission Route",
    "websiteUrl": "https://kalx.berkeley.edu/",
    "submissionUrl": "https://kalx.berkeley.edu/about/contact/",
    "sourceUrl": "https://kalx.berkeley.edu/about/contact/",
    "sourceType": "automation_run_292_public_research",
    "country": "United States / Berkeley freeform community and student radio",
    "language": "en",
    "genres": ["kalx", "college-radio", "freeform", "electronic", "independent", "physical-only", "professionally-pressed-cd", "vinyl", "no-digital-submissions", "manual-review"],
    "submissionMethod": "official-kalx-professionally-pressed-cd-or-lp-mail-route",
    "feeRequired": false,
    "feeAmount": "No submission fee or payment requirement is stated in KALX's official airplay-submission instructions.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "KALX currently accepts only physical, professionally pressed CDs or LPs for airplay consideration. It explicitly rejects downloads, file transfers, Bandcamp or Spotify links, YouTube videos, CD-Rs and other digital formats. Although music@kalx.berkeley.edu is publicly listed for the Music Directors, the official instructions do not authorize digital delivery to that mailbox. A human must verify that the release is professionally pressed, prepare the physical package and use the published postal destination exactly.",
    "notes": "Verified on 2026-07-11 from KALX's official contact and FAQ pages and active homepage. The station shows current July 11 and July 17, 2026 programming and events, including an electronic live feature. The official page publishes current Music Directors and business contacts, while clearly separating submission, interview and general-contact routes. No email was sent, no digital link was supplied and no physical package was prepared."
  },
  {
    "name": "KVRX 91.7 FM Official Digital and Physical Airplay Submission Email Route",
    "websiteUrl": "https://www.kvrx.org/app/",
    "submissionUrl": "mailto:music@kvrx.org",
    "sourceUrl": "https://www.kvrx.org/app/contact/",
    "sourceType": "automation_run_292_public_research",
    "country": "United States / Austin student-run underground and independent radio",
    "language": "en",
    "genres": ["kvrx", "college-radio", "underground", "independent", "electronic", "digital-email", "physical-submission", "ai-music-restriction", "manual-review"],
    "submissionMethod": "official-kvrx-music-department-email-for-digital-or-physical-airplay-consideration",
    "feeRequired": false,
    "feeAmount": "No submission fee or payment requirement is stated on KVRX's official contact page.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "KVRX directs all airplay submissions to music@kvrx.org and states that it currently accepts both physical and digital submissions. It also explicitly rejects AI-assisted or AI-generated music. A human must verify that the selected MarcsMusic track complies with that restriction, confirm any missing file, link, metadata and clean-edit requirements with operations@kvrx.org when necessary, and prepare the submission without guessing undocumented specifications.",
    "notes": "Verified on 2026-07-11 from KVRX's official contact and active homepage pages. KVRX describes itself as a student-run station broadcasting underground music, live shows and local discoveries around the clock. The official page separately publishes the Music Department and operations addresses, plus its mailing address. No email was sent, no file, link or physical package was delivered and no claim was made about a track's AI status."
  },
  {
    "name": "KXUA 88.3 FM Music Director Pre-Submission Routing Inquiry",
    "websiteUrl": "https://kxua.com/",
    "submissionUrl": "mailto:charts@uark.edu",
    "sourceUrl": "https://kxua.com/about-contact/",
    "sourceType": "automation_run_292_public_research",
    "country": "United States / Fayetteville student-run eclectic radio",
    "language": "en",
    "genres": ["kxua", "college-radio", "eclectic", "independent", "electronic", "music-director", "routing-inquiry-only", "no-audio-assets", "manual-review"],
    "submissionMethod": "official-kxua-music-director-email-routing-inquiry-only",
    "feeRequired": false,
    "feeAmount": "No fee or payment requirement is stated for contacting KXUA's Music Directors.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "KXUA's official staff page publishes charts@uark.edu for its current Music Directors but does not state a complete unsolicited-music policy, accepted file or link formats, geographic eligibility, metadata rules or review expectations. This queue item is restricted to a short asset-free inquiry asking for the authorized submission route and requirements. A human must send no audio, attachment or track link until KXUA confirms the procedure.",
    "notes": "Verified on 2026-07-11 from KXUA's official staff and homepage pages. The site identifies current Music Directors and publishes album reviews dated March and April 2026, including an electronic release review. The general KXUA address was not substituted for the Music Director route. No email was sent, no music asset was supplied and no address was guessed."
  }
];
