import type { PlatformInput } from '../models/types.js';

export const run230BaseSeedPlatforms: PlatformInput[] = [
  {
    name: "KUTX Austin Music Director WAV Download Airplay Route",
    websiteUrl: "https://kutx.org/",
    submissionUrl: "https://kutx.org/submit-your-music/",
    sourceUrl: "https://kutx.org/submit-your-music/",
    sourceType: "automation_run_230_public_research",
    country: "United States / Austin, Texas public-radio music discovery",
    language: "en",
    genres: ["public-radio", "radio-airplay", "music-director-email", "wav-download-link", "streaming-link", "fcc-clean-radio-edit", "austin-texas-local-fit", "public-form-boundary", "free-first", "manual-review"],
    submissionMethod: "kutx-austin-music-director-wav-download-airplay-route",
    feeRequired: false,
    feeAmount: "Free manual music-director route. Official KUTX guidance lists music@kutx.org for on-air rotation submissions and does not list a submission payment requirement for the music route.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for outbound email, WAV download-link selection, streaming link, FCC-clean radio edit, final-master check, Austin/Texas/local-fit flagging and specialty-show/form routing. No email was sent and no files were transferred.",
    notes: "Official KUTX submission guidance asks artists to email the music director with a streaming link, WAV download link, bio/location/release notes/tour info and a highlighted top track; it asks for final mastered, new/upcoming, FCC-clean radio edits and notes that producers cannot respond to every submission. The same page exposes public specialty-show and event-form boundaries."
  },
  {
    name: "WXPN Philadelphia EPK Download Music Director Local Show Route",
    websiteUrl: "https://xpn.org/",
    submissionUrl: "https://xpn.org/contact/",
    sourceUrl: "https://xpn.org/contact/",
    sourceType: "automation_run_230_public_research",
    country: "United States / Philadelphia, Pennsylvania public radio",
    language: "en",
    genres: ["public-radio", "radio-airplay", "music-director-email-link", "epk-download-link", "local-show", "wav-high-quality-mp3", "non-plaintext-email-link", "free-first", "manual-review"],
    submissionMethod: "wxpn-philadelphia-epk-download-music-director-local-show-route",
    feeRequired: false,
    feeAmount: "Free manual email-link route. Official WXPN contact guidance requests EPK/download-link music submissions and does not list a submission payment requirement.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for the official non-plaintext email links, EPK/download-link content, Local Show fit, WAV/high-quality MP3 selection, event/calendar boundary and unsolicited-submission expectations. No protected email link was decoded and no outbound email was sent.",
    notes: "Official WXPN contact guidance says to submit music for airplay by sending an EPK including a link to digitally download music by email, states that unsolicited receipt/airplay cannot be confirmed, and separately routes Local Show submissions to a WAV or high-quality MP3 download link plus bio and show info."
  },
  {
    name: "WFMU Jersey City Physical Music Director Review Route",
    websiteUrl: "https://wfmu.org/",
    submissionUrl: "https://wfmu.org/sendmusic.html",
    sourceUrl: "https://wfmu.org/sendmusic.html",
    sourceType: "automation_run_230_public_research",
    country: "United States / Jersey City, New Jersey independent freeform radio",
    language: "en",
    genres: ["freeform-radio", "independent-radio", "music-director", "physical-submission", "vinyl", "cd", "cd-r", "cassette", "protected-mail-page", "free-first", "manual-review"],
    submissionMethod: "wfmu-jersey-city-physical-music-director-review-route",
    feeRequired: false,
    feeAmount: "Free manual physical-delivery route. Official WFMU Send Music guidance lists postal/UPS/FedEx routes and does not list a submission payment requirement.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for physical media/package preparation, shipping address choice, music-director attention routing, contact-mail-page handling and freeform station fit. No package was prepared and no protected contact route was decoded.",
    notes: "Official WFMU Send Music guidance welcomes review materials including vinyl, CD, CD-R and cassette, lists postal and UPS/FedEx addresses for the music director, and points contact to a Music Department Mail Page. The active official homepage shows current 2026 archives/playlists and a Send Us Music navigation link."
  },
  {
    name: "WNXP Nashville Clean Mastered WAV Email Airplay Route",
    websiteUrl: "https://wnxp.org/",
    submissionUrl: "https://wnxp.org/music-submissions/",
    sourceUrl: "https://wnxp.org/music-submissions/",
    sourceType: "automation_run_230_public_research",
    country: "United States / Nashville, Tennessee public-radio music discovery",
    language: "en",
    genres: ["public-radio", "radio-airplay", "music-submission-email", "wav-download-link", "clean-mastered-audio", "nashville-artist-fit", "no-mp3", "free-first", "manual-review"],
    submissionMethod: "wnxp-nashville-clean-mastered-wav-email-airplay-route",
    feeRequired: false,
    feeAmount: "Free manual email route. Official WNXP music-submission guidance lists submissions@wnxp.org and no submission payment requirement.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for outbound email, clean mastered 44.1k/16-bit stereo WAV download link, artist info, no-MP3 compliance, genre/style fit and Nashville emphasis. No email was sent and no file was transferred.",
    notes: "Official WNXP music-submission guidance asks for email to submissions@wnxp.org with a download link to a clean/no-cursing, mastered 44.1k/16-bit stereo WAV file and basic artist info, says no MP3s, asks submitters to listen for fit, and notes Nashville artists receive special emphasis but not guaranteed response."
  },
  {
    name: "WREK Atlanta Snail Mail Email Music Director Submission Route",
    websiteUrl: "https://www.wrek.org/",
    submissionUrl: "https://old.wrek.org/submissions/",
    sourceUrl: "https://old.wrek.org/submissions/",
    sourceType: "automation_run_230_public_research",
    country: "United States / Atlanta, Georgia student-run college radio",
    language: "en",
    genres: ["college-radio", "student-radio", "radio-airplay", "music-director-email", "physical-submission", "snail-mail", "cd-lp-priority", "all-common-media-formats", "free-first", "manual-review"],
    submissionMethod: "wrek-atlanta-snail-mail-email-music-director-submission-route",
    feeRequired: false,
    feeAmount: "Free manual physical/email route. Official WREK submission guidance lists snail-mail and music.director@wrek.org routes and does not list a submission payment requirement.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for physical or email delivery choice, common-media-format handling, CD/LP priority expectations, music-director contact, review timing and programming fit. No email was sent and no package was prepared.",
    notes: "Official WREK submission guidance says music can be submitted by snail mail or emailed to music.director@wrek.org, says WREK can handle common media formats while CDs and LPs have a better chance of airplay, and explains music directors randomly pull submissions for review. The active official WREK site shows current 2026 programming and playlist activity."
  }
];
