import type { PlatformInput } from '../models/types.js';

export const run223SeedPlatforms: PlatformInput[] = [
  {
    name: "Bandcamp for Artists Direct Store Upload Route",
    websiteUrl: "https://bandcamp.com/",
    submissionUrl: "https://bandcamp.com/artists?from=footer",
    sourceUrl: "https://bandcamp.com/artists?from=footer",
    sourceType: "automation_run_223_public_research",
    country: "United States / global direct-to-fan music marketplace",
    language: "en",
    genres: ["direct-to-fan", "artist-upload", "digital-music-store", "merch", "editorial-discovery", "login-boundary", "revenue-share", "freemium"],
    submissionMethod: "bandcamp-for-artists-direct-store-upload-route",
    feeRequired: false,
    feeAmount: "Free-first manual route. Official Bandcamp for Artists page says artist accounts are free; Bandcamp takes 15% on digital music and 10% on merch sales, payment processor fees separate, with optional Bandcamp Pro at $10/month.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for desktop sign-up/login, artist identity, upload rights, human-created-content policy, pricing, PayPal/payout, tax, direct-to-fan store terms, optional Pro, merch/shipping and editorial-discovery boundaries. No account was created and no audio/artwork/merch was uploaded.",
    notes: "Official Bandcamp pages show Sign up/Log in, Bandcamp for Artists, direct-to-fan store setup, free artist accounts, fan/community discovery, pricing/revenue share, July 8 2026 editorial activity and recent AI-generated-music policy coverage."
  },
  {
    name: "Mixcloud Creator DJ Mix Radio Show Upload Route",
    websiteUrl: "https://www.mixcloud.com/",
    submissionUrl: "https://www.mixcloud.com/upload/",
    sourceUrl: "https://www.mixcloud.com/upload/",
    sourceType: "automation_run_223_public_research",
    country: "United Kingdom / global DJ mix, radio show and podcast streaming",
    language: "en",
    genres: ["dj-mix", "radio-show", "podcast", "creator-upload", "streaming-only", "metadata-boundary", "login-boundary", "freemium"],
    submissionMethod: "mixcloud-creator-dj-mix-radio-show-upload-route",
    feeRequired: false,
    feeAmount: "Free-first/freemium manual route. Official upload page exposes Sign up for free, Login and Upload for free; Pro creator features and unlimited upload/live-streaming upgrade are separate paid boundaries.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for sign-up/login, DJ-mix or radio-show suitability, tracklist/artist metadata, licensing/streaming-only limits, upload format, profile settings, Pro upgrade choice and rights compliance. No account was created and no audio/show file was uploaded.",
    notes: "Official Mixcloud upload page exposes free sign-up/login/upload routes and creator-tool upgrades. Public reference material identifies Mixcloud as active worldwide and says registration is required to upload radio shows, DJ mixes and podcasts while preserving licensing metadata."
  },
  {
    name: "SoundCloud Public Track Upload Creator Growth Route",
    websiteUrl: "https://soundcloud.com/",
    submissionUrl: "https://soundcloud.com/upload",
    sourceUrl: "https://soundcloud.com/upload",
    sourceType: "automation_run_223_public_research",
    country: "Germany / global audio sharing and creator platform",
    language: "en",
    genres: ["artist-upload", "audio-sharing", "creator-tools", "fan-discovery", "distribution", "login-boundary", "pricing-boundary", "freemium"],
    submissionMethod: "soundcloud-public-track-upload-creator-growth-route",
    feeRequired: false,
    feeAmount: "Free-first/freemium manual route. Official upload page advertises 180 minutes of free uploads and a Try it free route; SoundCloud also exposes Pro/Next Pro plan and distribution/artist-services boundaries.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for login/session, profile identity, track upload, cover art, metadata, privacy/release timing, comments/messages, Pro/Next Pro/distribution choices, AI/terms policy and copyright/takedown exposure. No account was created and no audio/artwork/file was uploaded.",
    notes: "Official SoundCloud upload page says creators share tracks, get 180 minutes of free uploads, connect with fans and access creator tools; public reference material describes Next Pro as a paid global musician service with unlimited uploads, analytics and distribution."
  },
  {
    name: "BandLab Creator Publish Social Distribution Route",
    websiteUrl: "https://www.bandlab.com/",
    submissionUrl: "https://www.bandlab.com/",
    sourceUrl: "https://www.bandlab.com/",
    sourceType: "automation_run_223_public_research",
    country: "Singapore / global browser and mobile music creation platform",
    language: "en",
    genres: ["music-creation", "artist-upload", "publish", "social-music", "collaboration", "free-hosting", "distribution", "login-boundary", "freemium"],
    submissionMethod: "bandlab-creator-publish-social-distribution-route",
    feeRequired: false,
    feeAmount: "Free-first/freemium manual route. Public source material describes BandLab as freemium with free hosting, publishing/sharing/social tools and premium Pro/Max creator tiers.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for sign-up/session, artist/profile identity, upload/import format, publishing settings, collaboration permissions, samples/loops rights, distribution/sales eligibility, premium feature selection and AI/creator-tool terms. No account was created and no project/audio/file was uploaded.",
    notes: "Public source material identifies BandLab as an active freemium DAW/social platform with distribution functions for creating, sharing and selling music, free hosting of creations, 60M+ creators, browser/mobile access and recent 2026 coverage of built-in publishing and sharing tools."
  },
  {
    name: "Songtradr Licensing Marketplace Artist Upload Route",
    websiteUrl: "https://www.songtradr.com/",
    submissionUrl: "https://www.songtradr.com/",
    sourceUrl: "https://www.songtradr.com/",
    sourceType: "automation_run_223_public_research",
    country: "United States / global music licensing marketplace",
    language: "en",
    genres: ["sync-licensing", "artist-upload", "music-marketplace", "b2b-licensing", "rights-management", "login-boundary", "commercial-terms-boundary", "app-boundary"],
    submissionMethod: "songtradr-licensing-marketplace-artist-upload-route",
    feeRequired: false,
    feeAmount: "Commercial/licensing manual route. No public upfront music-submission fee was verified in this run, but licensing fees, payout settings, ownership, splits and commercial marketplace terms are owner-controlled boundaries.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for JavaScript app/session, artist onboarding, upload rights, publishing/master ownership, PRO/metadata, licensing fees, marketplace visibility, payout/tax settings, sync/licensing contracts and commercial restrictions. No account was created and no audio/artwork/file was uploaded.",
    notes: "Official Songtradr site exposed a JavaScript app boundary. Public reference material describes Songtradr as a B2B music licensing marketplace where artists can upload music and set licensing fees for uses in ads, film and television."
  }
];
