import type { PlatformInput } from '../models/types.js';

export const run202BaseSeedPlatforms: PlatformInput[] = [
  {
    name: "KZSC Santa Cruz Music Director Physical Form Submission Route",
    websiteUrl: "https://kzsc.org/contact/",
    submissionUrl: "https://kzsc.org/send-us-a-message/",
    sourceUrl: "https://kzsc.org/contact/",
    sourceType: "automation_run_202_public_research",
    country: "United States / Santa Cruz college-radio music-director route",
    language: "en",
    genres: ["college-radio", "santa-cruz", "freeform", "music-director", "physical-submissions", "public-form", "electronic", "rpm", "international", "reggae", "manual-review"],
    submissionMethod: "official-kzsc-music-director-physical-form-submission-route",
    feeRequired: false,
    feeAmount: "Free-first/manual college-radio route. Official KZSC pages list station music directors, a Music Submission form topic and package addresses for Music Directors. No submission fee was observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for correct music-director routing, physical versus form delivery, clean edit status, release metadata and whether to use the public Music Submission form. No form or package action was taken.",
    notes: "KZSC was verified through official 2026 contact pages. Music director contacts are visible on the official page but presented through protected/sanitized mailto rendering in the research output; no protected address was decoded."
  },
  {
    name: "KCR College Radio Digital MP3 Email Automated Playlist Submission Route",
    websiteUrl: "https://kcr.sdsu.edu/",
    submissionUrl: "https://kcr.sdsu.edu/contact/music-submissions/",
    sourceUrl: "https://kcr.sdsu.edu/contact/music-submissions/",
    sourceType: "automation_run_202_public_research",
    country: "United States / San Diego student-radio digital music submission route",
    language: "en",
    genres: ["college-radio", "san-diego", "student-radio", "digital-submission", "mp3", "fcc-clean", "automated-playlist", "electronic", "independent-artists", "manual-review"],
    submissionMethod: "official-kcr-college-radio-digital-mp3-email-submission-route",
    feeRequired: false,
    feeAmount: "Free-first/manual digital email route. Official KCR guidance says all musicians are encouraged to submit and that digital submissions are accepted via kcr@sdsu.edu. No fee was observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for FCC-clean confirmation, MP3 formatting, filename format, metadata, San Diego/local-fit note and whether the automated playlist route is appropriate. No outbound email or files were sent.",
    notes: "KCR was verified as an active SDSU student-run internet radio station with 2026 music coverage and an official Music Submissions page."
  },
  {
    name: "WXYC Chapel Hill Music Director Email Postal Submission Route",
    websiteUrl: "https://wxyc.org/",
    submissionUrl: "https://wxyc.org/contact",
    sourceUrl: "https://wxyc.org/contact",
    sourceType: "automation_run_202_public_research",
    country: "United States / Chapel Hill freeform college-radio music-director route",
    language: "en",
    genres: ["college-radio", "freeform", "chapel-hill", "music-director", "email-submission", "postal-submission", "electronic", "world", "reggae", "manual-review"],
    submissionMethod: "official-wxyc-music-director-email-postal-submission-route",
    feeRequired: false,
    feeAmount: "Free-first/manual music director route. Official WXYC contact page lists md@wxyc.org for music submissions or distribution concerns and a postal Music Department address. No fee was observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for email pitch content, track links/files, postal versus digital delivery, release metadata, clean status and fit with WXYC freeform programming. No email or package action was taken.",
    notes: "WXYC was verified as an active UNC-Chapel Hill student-run freeform station; the archive shows 2026 specialty-show activity and the contact page lists music-submission routing."
  },
  {
    name: "WTUL New Orleans Physical Digital Music Director CAPTCHA Contact Route",
    websiteUrl: "https://www.wtulneworleans.com/",
    submissionUrl: "https://www.wtulneworleans.com/contact-wtul",
    sourceUrl: "https://www.wtulneworleans.com/contact-wtul",
    sourceType: "automation_run_202_public_research",
    country: "United States / New Orleans college-radio music-director physical and digital route",
    language: "en",
    genres: ["college-radio", "new-orleans", "physical-submissions", "digital-submissions", "music-director", "world", "reggae", "electronic", "captcha-boundary", "manual-review"],
    submissionMethod: "official-wtul-physical-digital-music-director-captcha-contact-route",
    feeRequired: false,
    feeAmount: "Free-first/manual college-radio route. Official WTUL contact guidance gives a physical submission address and points digital submissions to the appropriate staff music director. No fee was observed.",
    loginRequired: false,
    captchaDetected: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for physical versus digital routing, choosing the correct music director, protected contact handling, contact-form CAPTCHA boundary, audio format and release metadata. No CAPTCHA, form, email or package action was taken.",
    notes: "WTUL was verified as active with 2025-2026 staff/current-site context, 2025 playlist/blog activity and official contact guidance for music submissions."
  },
  {
    name: "KCPR Cal Poly Music Programming Director Contact Submission Route",
    websiteUrl: "https://kcpr.org/",
    submissionUrl: "https://kcpr.org/contact/",
    sourceUrl: "https://kcpr.org/contact/",
    sourceType: "automation_run_202_public_research",
    country: "United States / San Luis Obispo college-radio music-programming contact route",
    language: "en",
    genres: ["college-radio", "cal-poly", "san-luis-obispo", "music-programming", "programming-director", "contact-route", "independent-artists", "electronic", "world", "manual-review"],
    submissionMethod: "official-kcpr-music-programming-director-contact-submission-route",
    feeRequired: false,
    feeAmount: "Free-first/manual station contact route. Official KCPR contact page lists Music and Programming plus a 2025-26 Programming and Music Director contact and mailing address. No submission fee was observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required because the official page exposes contact routes rather than a full automated submission workflow; music fit, message wording, clean status, metadata and delivery format must be reviewed before outreach. No email or package action was taken.",
    notes: "KCPR was verified as active via official June 2026 music/playlists/editorial posts and an official contact page with music/programming contacts."
  }
];
