import type { PlatformInput } from '../models/types.js';

export const run201BaseSeedPlatforms: PlatformInput[] = [
  {
    name: "KCRW Santa Monica Recording Airplay Consideration Route",
    websiteUrl: "https://www.kcrw.com/",
    submissionUrl: "https://www.kcrw.com/",
    sourceUrl: "https://www.kcrw.com/",
    sourceType: "automation_run_201_public_research",
    country: "United States / Los Angeles public-radio recording consideration route",
    language: "en",
    genres: ["public-radio", "los-angeles", "eclectic", "local-artists", "regional-artists", "recording-consideration", "electronic", "world", "reggae", "manual-review"],
    submissionMethod: "official-kcrw-recording-airplay-consideration-route",
    feeRequired: false,
    feeAmount: "Free-first/manual public-radio consideration route. Public station information says local and regional touring artists may send recordings to KCRW for airplay consideration. No submission fee was observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for local/regional fit, clean edit status, music-library fit, one-sheet and delivery path. No automated send action was taken.",
    notes: "KCRW was verified as an active Santa Monica public-radio music outlet with eclectic programming and a recording-consideration path for local/regional artists."
  },
  {
    name: "BBC Music Introducing UK Postcode Upload Tool Route",
    websiteUrl: "https://www.bbc.co.uk/introducing",
    submissionUrl: "https://www.bbc.co.uk/introducing",
    sourceUrl: "https://www.bbc.co.uk/introducing",
    sourceType: "automation_run_201_public_research",
    country: "United Kingdom / BBC unsigned artist upload platform",
    language: "en",
    genres: ["bbc-introducing", "uk-only", "unsigned-artists", "upload-tool", "postcode-routing", "radio-1", "6-music", "electronic", "independent-artists", "manual-review"],
    submissionMethod: "official-bbc-introducing-postcode-upload-tool-route",
    feeRequired: false,
    feeAmount: "Free-first/manual public broadcaster upload route for unsigned and under-the-radar UK music talent. No submission fee was observed.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for UK eligibility, postcode/local-show routing, rights, metadata, clean status and account consent. No login or upload action was taken.",
    notes: "BBC Music Introducing was verified as an active BBC new-music route with upload-tool and local-show routing context."
  },
  {
    name: "Amazing Radio New Emerging Artist Upload Airplay Route",
    websiteUrl: "https://amazingradio.com/",
    submissionUrl: "https://amazingradio.com/",
    sourceUrl: "https://amazingradio.com/",
    sourceType: "automation_run_201_public_research",
    country: "United Kingdom / United States / worldwide emerging-artist radio upload route",
    language: "en",
    genres: ["amazing-radio", "new-artists", "emerging-artists", "unsigned-artists", "artist-upload", "online-radio", "independent-artists", "electronic", "world", "manual-review"],
    submissionMethod: "official-amazing-radio-new-artist-upload-airplay-route",
    feeRequired: false,
    feeAmount: "Free-first/manual artist upload and radio consideration route. Public sources describe artist submission via the Amazing Radio website. No submission fee was observed.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for account terms, rights, profile data, track metadata and radio fit. No login or upload action was taken.",
    notes: "Amazing Radio was verified as an international new/emerging-artist radio platform with public artist-upload context."
  },
  {
    name: "TIDAL Upload Independent Artist Direct Publishing Spotlight Route",
    websiteUrl: "https://tidal.com/",
    submissionUrl: "https://tidal.com/",
    sourceUrl: "https://tidal.com/",
    sourceType: "automation_run_201_public_research",
    country: "United States initial availability / global streaming platform direct-upload route",
    language: "en",
    genres: ["tidal-upload", "direct-upload", "independent-artists", "streaming-platform", "spotlight-program", "rights-review", "electronic", "reggae", "world", "manual-review"],
    submissionMethod: "official-tidal-upload-independent-artist-direct-upload-route",
    feeRequired: false,
    feeAmount: "Free-first/manual direct-upload route. Public 2025-2026 reporting describes TIDAL Upload as free for eligible independent artists, with editorial spotlight possibilities. No paid submission requirement was observed.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for eligibility, rights, metadata, availability, platform terms and AI-labeling policy implications. No login, upload or publishing action was taken.",
    notes: "TIDAL Upload was verified from public 2025-2026 reporting as a direct-upload route with rights and policy boundaries."
  },
  {
    name: "Jamendo Artist Free Music Licensing Upload Route",
    websiteUrl: "https://www.jamendo.com/",
    submissionUrl: "https://www.jamendo.com/",
    sourceUrl: "https://www.jamendo.com/",
    sourceType: "automation_run_201_public_research",
    country: "Luxembourg / worldwide independent artist free-music and licensing platform",
    language: "multi",
    genres: ["jamendo", "independent-artists", "creative-commons", "music-licensing", "artist-profile", "global-platform", "sync-licensing", "instrumental", "electronic", "manual-review"],
    submissionMethod: "official-jamendo-artist-free-music-licensing-upload-route",
    feeRequired: false,
    feeAmount: "Free-first/manual artist upload/licensing route. Public Jamendo information describes an independent-artist community, artist profiles and commercial licensing opportunities. No submission fee was observed.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for account setup, license selection, collecting-society constraints, metadata, ownership and publishing settings. No login, license selection or upload action was taken.",
    notes: "Jamendo was verified as a worldwide independent-artist/free-music and licensing platform with artist-profile and licensing context."
  }
];
