import type { PlatformInput } from '../models/types.js';

export const run221BaseSeedPlatforms: PlatformInput[] = [
  {
    name: "Audiomack Creator Upload Free Streaming Discovery Route",
    websiteUrl: "https://audiomack.com/",
    submissionUrl: "https://creators.audiomack.com/",
    sourceUrl: "https://creators.audiomack.com/",
    sourceType: "automation_run_221_public_research",
    country: "Global / creator upload platform",
    language: "en",
    genres: ["streaming", "artist-upload", "creator-app", "music-discovery", "hip-hop", "afrobeats", "login-boundary", "free-first"],
    submissionMethod: "audiomack-creator-upload-free-streaming-discovery-route",
    feeRequired: false,
    feeAmount: "Free-first creator upload route. Official Audiomack public site exposes Sign Up, Sign In and Upload navigation and describes limitless artist/creator uploads; Plus, Pro, promotion and monetization options remain owner-controlled.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Account/session, verified artist/creator role, rights/ownership, audio upload, metadata, release visibility, monetization/supporter/AMP/promotion choices and platform policy compliance require owner approval. No form was submitted, no account was created and no audio/artwork/file was uploaded.",
    notes: "Official Audiomack homepage exposes Upload plus Sign Up/Sign In, Creator App and current trending/recently added activity; public source material reports 50M monthly active users as of January 2026."
  },
  {
    name: "Jamendo Artists One Stop Licensing In Store Content ID Route",
    websiteUrl: "https://www.jamendo.com/",
    submissionUrl: "https://artists.jamendo.com/",
    sourceUrl: "https://artists.jamendo.com/",
    sourceType: "automation_run_221_public_research",
    country: "Global / independent artist licensing and discovery",
    language: "en",
    genres: ["artist-services", "sync-licensing", "in-store", "content-id", "promotion", "revenue-share", "login-boundary", "pricing-terms-boundary", "free-first"],
    submissionMethod: "jamendo-artists-one-stop-licensing-in-store-content-id-route",
    feeRequired: false,
    feeAmount: "Free-first/manual artist-services route. Official Jamendo Artists page exposes Start Now/Sign In flows and artist licensing, in-store, Content ID and promotion services; commercial terms are manual.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for sign-in/start route, master and publishing rights, PRO/collecting-society status, licensing opt-in, in-store use, Content ID tracking, promotion choices, payout/tax terms and territory/rights conflicts. No form was submitted, no account was created and no audio/artwork/file was uploaded.",
    notes: "Official Jamendo Artists page shows Artist Services, One-Stop, Licensing, In-Store, Content ID and Start Now routes, plus audience/placement claims including over 7M music fans and 20K commercial spaces."
  },
  {
    name: "Pond5 Contributor Stock Music Sound Effects Licensing Upload Route",
    websiteUrl: "https://www.pond5.com/",
    submissionUrl: "https://contributor.pond5.com/",
    sourceUrl: "https://contributor.pond5.com/",
    sourceType: "automation_run_221_public_research",
    country: "Global / contributor stock media marketplace",
    language: "en",
    genres: ["stock-music", "sound-effects", "sync-licensing", "contributor-portal", "royalty-free", "identity-verification", "payouts", "login-boundary", "marketplace", "free-first"],
    submissionMethod: "pond5-contributor-stock-music-sound-effects-licensing-upload-route",
    feeRequired: false,
    feeAmount: "Free-first contributor route. Official Pond5 contributor guidance says there is no cost to upload work and start selling, but contributor identity, pricing, royalties and payout terms are manual.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for contributor account creation, identity verification, upload preparation, music/SFX metadata, tags, pricing, rights, AI policy, tax/payout method and marketplace license terms. No account, upload or identity step was attempted. No form was submitted, no account was created and no audio/artwork/file was uploaded.",
    notes: "Official Pond5 Sell Your Media and Contributor Portal pages cover Music and Sound Effects, Join/Login, upload/tagging/pricing, artist royalties, identity verification, payouts and 2026 contributor updates."
  },
  {
    name: "Amazing Radio Emerging Artist Website Upload Airplay Route",
    websiteUrl: "https://amazingradio.com/",
    submissionUrl: "https://amazingradio.com/",
    sourceUrl: "https://amazingradio.com/",
    sourceType: "automation_run_221_public_research",
    country: "United Kingdom / Ireland / United States / worldwide online radio",
    language: "en",
    genres: ["emerging-artists", "internet-radio", "dab-radio", "artist-upload", "new-music", "app-boundary", "login-boundary", "radio-airplay", "free-first"],
    submissionMethod: "amazing-radio-emerging-artist-website-upload-airplay-route",
    feeRequired: false,
    feeAmount: "Free-first/manual emerging-artist radio route. Public source material says artists submit via the Amazing Radio website; no payment path was observed.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for JavaScript/app route, artist account/session, upload eligibility, unreleased/released status, radio-fit, metadata, rights, privacy/terms and editorial airplay expectations. No app bypass, login or upload was attempted. No form was submitted, no account was created and no audio/artwork/file was uploaded.",
    notes: "Official Amazing Radio site presented a JavaScript/app boundary, while public source material describes worldwide online/DAB activity and artist submissions through the Amazing Radio website."
  },
  {
    name: "TIDAL Artist Home Upload Direct Artist Review Route",
    websiteUrl: "https://tidal.com/",
    submissionUrl: "https://artists.tidal.com/",
    sourceUrl: "https://artists.tidal.com/",
    sourceType: "automation_run_221_public_research",
    country: "Norway / United States / TIDAL Artist Home",
    language: "en",
    genres: ["artist-home", "direct-upload", "streaming", "creator-profile", "eligibility-boundary", "account-boundary", "rights-boundary", "free-first"],
    submissionMethod: "tidal-artist-home-upload-direct-artist-review-route",
    feeRequired: false,
    feeAmount: "Free-first/manual artist-home upload route. Official TIDAL Artist Home exposes sign-up/login to manage creator profiles, and public reporting describes TIDAL Upload as free but eligibility-limited.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for TIDAL Artist Home account/session, TIDAL Upload availability, country/age eligibility, ownership and sample/cover clearance, metadata, artwork, private/public visibility, no-royalty terms, editorial/contest timing and AI/fraud-policy boundaries. No form was submitted, no account was created and no audio/artwork/file was uploaded.",
    notes: "Official TIDAL Artist Home exposes email-based sign-up/login to manage creator profiles; public reporting in November 2025 describes TIDAL Upload as free, currently US-only, rights-checked and direct-to-platform."
  }
];
