import type { PlatformInput } from '../models/types.js';

export const run207SeedPlatforms: PlatformInput[] = [
  {
    name: "NCS NoCopyrightSounds LabelRadar Demo Submission Route",
    websiteUrl: "https://ncs.io/",
    submissionUrl: "https://www.labelradar.com/labels/ncs/portal",
    sourceUrl: "https://ncs.io/contact",
    sourceType: "automation_run_207_public_research",
    country: "Global / UK electronic music label and creator-friendly music channel",
    language: "en",
    genres: ["electronic", "edm", "dubstep", "drum-and-bass", "trap", "house", "label-demo", "creator-music", "manual-review"],
    submissionMethod: "official-ncs-labelradar-demo-submission-route",
    feeRequired: false,
    feeAmount: "Free-first/manual demo route. Official NCS contact page routes Demo Submissions to LabelRadar; LabelRadar/app login and A&R fit review require owner/manual handling before any upload.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for LabelRadar login/session boundary, demo eligibility, audio/link ownership, release status, genre fit, metadata, artwork/press assets, NCS usage/licensing expectations and platform policy. No login, upload, message or form submission was performed.",
    notes: "Official NCS contact route includes Demo Submissions via LabelRadar. Queued only for manual review because the destination is an authenticated third-party submission portal."
  },
  {
    name: "Monstercat LabelRadar Electronic Demo Portal Route",
    websiteUrl: "https://www.monstercat.com/",
    submissionUrl: "https://www.labelradar.com/labels/monstercat/portal",
    sourceUrl: "https://www.monstercat.com/",
    sourceType: "automation_run_207_public_research",
    country: "Global / Canada-based electronic label with Uncaged, Instinct and Silk brands",
    language: "en",
    genres: ["electronic", "edm", "dubstep", "future-bass", "trance", "progressive-house", "label-demo", "labelradar", "manual-review"],
    submissionMethod: "official-monstercat-labelradar-electronic-demo-portal-route",
    feeRequired: false,
    feeAmount: "Free-first/manual demo portal route. Public Monstercat pages show active 2026 releases and sign-in/session/cookie boundaries; the LabelRadar portal requires owner review before any demo upload.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for LabelRadar/app boundary, Monstercat brand fit, release/unreleased-demo status, rights ownership, metadata, clean/explicit state, audio quality, artist profile and submission policy. No cookies accepted, account used, upload or message sent.",
    notes: "Validated as an active electronic label through official Monstercat site activity and queued through the public LabelRadar portal URL only for manual review."
  },
  {
    name: "EARMILK SubmitHub Pillargram Music Submission Route",
    websiteUrl: "https://earmilk.com/",
    submissionUrl: "https://earmilk.com/submit-music/",
    sourceUrl: "https://earmilk.com/submit-music/",
    sourceType: "automation_run_207_public_research",
    country: "Global / US-based music publication covering electronic, dance, hip-hop, indie, pop and experimental music",
    language: "en",
    genres: ["electronic", "dance", "experimental", "hip-hop", "indie", "pop", "music-blog", "submithub", "pillargram", "manual-review"],
    submissionMethod: "official-earmilk-submithub-pillargram-music-submission-route",
    feeRequired: false,
    feeAmount: "Free-first/freemium/manual third-party submission route. EARMILK states it exclusively accepts submissions through SubmitHub or Pillargram and shows July 2026 activity; account, credit/payment and curator-review boundaries must be handled manually.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for SubmitHub/Pillargram account/session, possible credit/payment choice, track-link preparation, premiere/review positioning, genre fit, press assets, release date and publication terms. No account, form, credit spend or message was initiated.",
    notes: "Official EARMILK submit page points artists to SubmitHub/Pillargram and shows current July 2026 music activity. Queued for manual review only."
  },
  {
    name: "Dancing Astronaut Track Promo Music Email Route",
    websiteUrl: "https://dancingastronaut.com/",
    submissionUrl: "https://dancingastronaut.com/contact/",
    sourceUrl: "https://dancingastronaut.com/contact/",
    sourceType: "automation_run_207_public_research",
    country: "Global / US-based EDM, trap, techno, deep house and dubstep publication",
    language: "en",
    genres: ["edm", "trap", "techno", "deep-house", "dubstep", "electronic", "music-blog", "track-promo", "manual-review"],
    submissionMethod: "official-dancing-astronaut-track-promo-music-email-route",
    feeRequired: false,
    feeAmount: "Free-first/manual public email route. Official contact page lists a dedicated Track Promos & Submission email, but the route must be manually reviewed and pitched without automation.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for public email pitch wording, link-only delivery, genre fit, release status, clean/explicit state, press assets and avoidance of duplicate/misrouted submissions. No email or message was sent and no deliverability probing was performed.",
    notes: "Official contact page lists a specific music submission email and current music archive activity was observed. Logged as a public source-verified contact route, not SMTP-verified."
  },
  {
    name: "RepostExchange SoundCloud Partner Free Credits Promotion Route",
    websiteUrl: "https://repostexchange.com/",
    submissionUrl: "https://repostexchange.com/welcome",
    sourceUrl: "https://repostexchange.com/",
    sourceType: "automation_run_207_public_research",
    country: "Global / UK-based SoundCloud creator promotion, feedback and repost community platform",
    language: "en",
    genres: ["soundcloud", "music-promotion", "creator-community", "electronic", "edm", "dubstep", "feedback", "repost-campaigns", "manual-review"],
    submissionMethod: "official-repostexchange-soundcloud-partner-free-credits-promotion-route",
    feeRequired: false,
    feeAmount: "Free-first/freemium/manual promotion route. Official page says the service is free to use, uses credits, offers optional paid credits/plans and requires SoundCloud connection; no automated repost/follow/like/comment action is allowed or initiated.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for SoundCloud OAuth/session boundary, track choice, credit/campaign strategy, community guidelines, optional paid credits/plans and manual-only engagement controls. No SoundCloud connection, campaign, repost, follow, like, comment, credit spend or payment action was performed.",
    notes: "Official page states RepostExchange is an official SoundCloud partner, free to use, credit-based and manually controlled. Queued only for manual review because it is a connected-account promotion workflow."
  }
];
