import type { PlatformInput } from '../models/types.js';

export const run203SeedPlatforms: PlatformInput[] = [
  {
    name: "KBOO Portland Physical Genre Attention Music Submission Route",
    websiteUrl: "https://www.kboo.fm/",
    submissionUrl: "https://www.kboo.fm/submit-your-music",
    sourceUrl: "https://www.kboo.fm/submit-your-music",
    sourceType: "automation_run_203_public_research",
    country: "United States / Portland community-radio physical music submission route",
    language: "en",
    genres: ["community-radio", "portland", "freeform", "physical-submissions", "electronic", "world-music", "reggae", "hip-hop", "jazz", "manual-review"],
    submissionMethod: "official-kboo-physical-genre-attention-music-submission-route",
    feeRequired: false,
    feeAmount: "Free-first/manual physical mail route. Official KBOO guidance accepts mailed submissions by genre attention line and no submission fee was observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for physical package preparation, genre attention routing, release metadata, clean status, station-property/no-return terms and no-airplay-guarantee terms. No package was prepared or mailed.",
    notes: "KBOO was verified through its official site, active 2026 audio/playlist posts and official Submit Your Music page; KBOO says it does not yet have a digital library or capacity to download and burn digital submissions."
  },
  {
    name: "WMSE Milwaukee Physical Digital Music Director Airplay Submission Route",
    websiteUrl: "https://wmse.org/",
    submissionUrl: "https://wmse.org/about-wmse-radio/music-department/",
    sourceUrl: "https://wmse.org/about-wmse-radio/music-department/",
    sourceType: "automation_run_203_public_research",
    country: "United States / Milwaukee independent college-community radio route",
    language: "en",
    genres: ["college-radio", "community-radio", "milwaukee", "physical-submissions", "digital-download", "music-director", "fcc-clean", "world", "reggae", "electronic", "manual-review"],
    submissionMethod: "official-wmse-physical-digital-music-director-submission-route",
    feeRequired: false,
    feeAmount: "Free-first/manual music-director route. Official WMSE guidance accepts CD, vinyl, cassette and, when no physical release exists, digital download delivery to the Music Director. No submission fee was observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for FCC-clean track confirmation, physical versus digital delivery choice, one-sheet/tracklist, release metadata, local/genre fit and polite follow-up boundaries. No email, file transfer or physical submission was sent.",
    notes: "WMSE was verified via official 2026 site content, active event/airplay context, staff Music Director contact and official How To Submit Music guidance."
  },
  {
    name: "KCSU Fort Collins Monday Form Physical Airplay Submission Route",
    websiteUrl: "https://kcsufm.com/",
    submissionUrl: "https://kcsufm.com/submitmusic/",
    sourceUrl: "https://kcsufm.com/submitmusic/",
    sourceType: "automation_run_203_public_research",
    country: "United States / Fort Collins student-radio public form and physical route",
    language: "en",
    genres: ["college-radio", "student-radio", "fort-collins", "colorado", "public-form", "physical-submissions", "digital-library", "independent-artists", "electronic", "manual-review"],
    submissionMethod: "official-kcsu-monday-form-physical-airplay-submission-route",
    feeRequired: false,
    feeAmount: "Free-first/manual route. Official KCSU guidance welcomes tracks for airplay consideration through local/all-artist Monday.com forms or a physical mailbox. No submission fee was observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for choosing Colorado-local versus all-artist form, Monday.com third-party form boundary, physical mailbox option, metadata, rights, clean status and digital-library fit. No form, email, upload or package action was taken.",
    notes: "KCSU was verified through its official 2026 site, contact page, staff/contact context and official Submit Your Music for Air-Play page."
  },
  {
    name: "KRCL Salt Lake City Physical Utah Local Google Form Submission Route",
    websiteUrl: "https://krcl.org/",
    submissionUrl: "https://krcl.org/about/how-to-submit-music/",
    sourceUrl: "https://krcl.org/about/how-to-submit-music/",
    sourceType: "automation_run_203_public_research",
    country: "United States / Salt Lake City community-radio music department route",
    language: "en",
    genres: ["community-radio", "salt-lake-city", "utah-local", "physical-submissions", "google-form", "world", "reggae", "indie", "folk", "manual-review"],
    submissionMethod: "official-krcl-physical-utah-local-google-form-submission-route",
    feeRequired: false,
    feeAmount: "Free-first/manual route. Official KRCL guidance accepts physical CDs and has a digital upload path for Utah musicians and bands. No submission fee was observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for Utah-local eligibility, Google form boundary, physical CD requirements, no-demo/no-CD-R terms, station-property/no-return terms, release metadata and no-airplay-guarantee terms. No form or package action was taken.",
    notes: "KRCL was verified through official 2026 home-page activity and official How to Submit Music guidance."
  },
  {
    name: "WNCW Spindale CD WAV MP3 Programming Department Submission Route",
    websiteUrl: "https://www.wncw.org/",
    submissionUrl: "https://www.wncw.org/submit-music",
    sourceUrl: "https://www.wncw.org/submit-music",
    sourceType: "automation_run_203_public_research",
    country: "United States / Western North Carolina public-radio programming department route",
    language: "en",
    genres: ["public-radio", "adult-album-alternative", "americana", "folk", "blues", "jazz", "reggae", "world", "cd-submissions", "wav", "mp3", "manual-review"],
    submissionMethod: "official-wncw-cd-wav-mp3-programming-department-submission-route",
    feeRequired: false,
    feeAmount: "Free-first/manual programming-department route. Official WNCW guidance prefers CDs and also accepts WAV or MP3 files through a common download service. No submission fee was observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for CD versus digital delivery, common download-service link preparation, one-sheet, metadata, local/regional show context, single/EP/album fit and no-organized-request-campaign guidance. No email, file transfer or package action was taken.",
    notes: "WNCW was verified through official 2026 site activity, Submit Music navigation and official submission FAQ covering CDs plus WAV/MP3 links."
  }
];
