import type { PlatformInput } from '../models/types.js';

export const run283SeedPlatforms: PlatformInput[] = [
  {
    "name": "Radio WigWam Grassroots Artist Account Upload and Airplay Route",
    "websiteUrl": "https://radiowigwam.co.uk/",
    "submissionUrl": "https://radiowigwam.co.uk/_useradmin/?uploadtrack=true",
    "sourceUrl": "https://radiowigwam.co.uk/_useradmin/?uploadtrack=true",
    "sourceType": "automation_run_283_public_research",
    "country": "United Kingdom / global independent and grassroots artist online-radio account upload route",
    "language": "en",
    "genres": ["radio-wigwam", "independent-radio", "grassroots-artists", "electronic", "dance", "world-music", "rock", "account-upload", "freemium-boundary", "manual-review"],
    "submissionMethod": "official-public-artist-account-track-upload-route-with-free-and-paid-membership-boundaries",
    "feeRequired": false,
    "feeAmount": "The Basic Artist route is advertised as free with one submission per month; an optional Premiere Artist subscription is advertised at £5 per month with four submissions per month.",
    "loginRequired": true,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "Radio WigWam routes artists through a join/login workflow before track upload. The free Basic Artist allowance, optional paid tier, profile data, rights declarations, metadata, upload controls and any runtime human-verification or session checks require owner-controlled review. Do not create an account, log in, accept terms, upload a track or enter a payment flow automatically.",
    "notes": "The official homepage and artist-upload page were verified on 2026-07-11. They display active programming, 2026 station activity and an invitation for independent artists to join and upload music. A protected business contact is displayed but was not decoded. No account, login, upload, form submission or payment action was performed."
  },
  {
    "name": "Lonely Oak Radio MP3 WAV Song EP and Album Upload Route",
    "websiteUrl": "https://lonelyoakradio.com/",
    "submissionUrl": "https://lonelyoakradio.com/upload.html",
    "sourceUrl": "https://lonelyoakradio.com/upload.html",
    "sourceType": "automation_run_283_public_research",
    "country": "United States / Los Angeles global independent-music internet-radio upload route",
    "language": "en",
    "genres": ["lonely-oak-radio", "internet-radio", "independent-music", "rock", "alternative", "mp3", "wav", "single-upload", "album-upload", "paid-promotion-side-route", "manual-review"],
    "submissionMethod": "official-public-song-or-full-album-upload-workflow-with-optional-paid-promotion-side-route",
    "feeRequired": false,
    "feeAmount": "The primary song and album submission workflow is presented without a mandatory fee; optional paid promotion packages are separately advertised and require explicit owner approval.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "Lonely Oak publishes separate song and album upload workflows requesting MP3/WAV audio at 320 kbps or higher, an email account, a social account, metadata and optional biography material. The rendered upload pages are dynamic and a separate paid-promotion route exists. A human must inspect the live fields, permissions, rights language, upload limits and any challenge before supplying files; the contact form must not be used for music.",
    "notes": "The official submission and contact pages were verified on 2026-07-11. The station explicitly directs music to the upload workflow and states that its general contact form cannot accept music. Current program blocks include New Music, Indie Shuffle and Full Album programming. No files, forms, social credentials or payment details were supplied."
  },
  {
    "name": "Radio TFSC Indie Music MP3 Email Submission Route",
    "websiteUrl": "https://radiotfsc.com/",
    "submissionUrl": "mailto:radiotfsc@gmail.com",
    "sourceUrl": "https://radiotfsc.com/",
    "sourceType": "automation_run_283_public_research",
    "country": "Europe / global independent-music online-radio direct email submission route",
    "language": "en",
    "genres": ["radio-tfsc", "indie-radio", "independent-music", "electronic", "indie-pop", "indie-rock", "mp3-email", "metadata-required", "recaptcha-contact-boundary", "manual-review"],
    "submissionMethod": "official-public-mp3-email-submission-route-with-separate-recaptcha-protected-general-contact-form",
    "feeRequired": false,
    "feeAmount": "No music-submission fee is stated on the official submission instructions.",
    "loginRequired": false,
    "captchaDetected": true,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "Radio TFSC publishes a direct music email route and asks for MP3 files with complete Contributing Artist and Title metadata, no duplicate submissions and no expiring transfer links. A human must verify the final metadata, attachment size, clean/explicit status, rights and personalized email copy. The separate general contact form is protected by reCAPTCHA and must not be automated or used as a substitute for the music route.",
    "notes": "The official Radio TFSC homepage was verified on 2026-07-11. It publishes radiotfsc@gmail.com for music consideration, current weekly programming, an Indie of the Week feature and a 2026 copyright notice. The business email was recorded only because it is publicly published by the station; no SMTP/MX probe or email was sent."
  },
  {
    "name": "Reprezent Radio UK Underground Playlist Pre-Submission Routing Inquiry",
    "websiteUrl": "https://www.reprezent.org.uk/",
    "submissionUrl": "mailto:info@reprezent.org.uk",
    "sourceUrl": "https://www.reprezent.org.uk/contacts",
    "sourceType": "automation_run_283_public_research",
    "country": "United Kingdom / London youth-led radio and UK-underground playlist routing inquiry",
    "language": "en",
    "genres": ["reprezent-radio", "uk-underground", "afrobeats", "dancehall", "reggae", "grime", "dubstep", "rap", "pre-submission-inquiry", "uk-eligibility-boundary", "manual-review"],
    "submissionMethod": "official-public-general-business-email-asset-free-pre-submission-routing-inquiry",
    "feeRequired": false,
    "feeAmount": "No fee is stated for a general routing inquiry; no music-submission or promotional payment route is authorized by this record.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "Reprezent publishes current UK-underground playlists and public business contacts but does not publish a dedicated unsolicited-music submission workflow on the reviewed pages. MarcsMusic is not a UK-based act, so a human may send only a concise asset-free inquiry asking whether international independent releases are eligible and which authorized route applies. Do not attach audio, paste private links or treat general, marketing or partnership addresses as automatic submission permission.",
    "notes": "The official homepage, playlist and contact pages were verified on 2026-07-11. They show current July 2026 programming, a fortnightly curated UK-underground playlist and the public general address info@reprezent.org.uk. No inquiry, file, link or promotional request was sent."
  },
  {
    "name": "WNHU 88.7 University of New Haven Official Station Pre-Submission Routing Inquiry",
    "websiteUrl": "https://www.wnhu.org/",
    "submissionUrl": "https://www.wnhu.org/",
    "sourceUrl": "https://www.wnhu.org/",
    "sourceType": "automation_run_283_public_research",
    "country": "United States / West Haven, Connecticut university variety-radio asset-free routing inquiry",
    "language": "en",
    "genres": ["wnhu", "college-radio", "student-radio", "variety-radio", "independent-music", "electronic", "world-music", "official-social-contact", "pre-submission-inquiry", "manual-review"],
    "submissionMethod": "official-public-station-site-and-linked-social-channel-asset-free-pre-submission-routing-inquiry",
    "feeRequired": false,
    "feeAmount": "No inquiry or submission fee is stated on the reviewed official station pages.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "WNHU's official site confirms an active student-run variety station and links official social channels, but it does not publish a dedicated music-submission email, form or delivery specification. A human must first identify the current authorized station contact through the visible official site or linked official channel and send only an asset-free routing question. Do not guess staff addresses, send music by direct message, or supply files or links without explicit instructions.",
    "notes": "The official WNHU homepage, About page and schedule page were verified on 2026-07-11. They show current student-run shows, podcasts, station streaming and a schedule that the station says is updated regularly. No business email was guessed, no social message was sent and no music asset was delivered."
  }
];
