import type { PlatformInput } from '../models/types.js';

export const run208BaseSeedPlatforms: PlatformInput[] = [
  {
    name: "KSPC Claremont Album EP Digital Physical Music Submission Route",
    websiteUrl: "https://kspc.org/",
    submissionUrl: "https://kspc.org/contact/music-submissions/",
    sourceUrl: "https://kspc.org/contact/music-submissions/",
    sourceType: "automation_run_208_public_research",
    country: "United States / Claremont, California college-community freeform radio",
    language: "en",
    genres: ["college-radio", "freeform", "electronic", "hip-hop", "reggae", "independent", "album", "ep", "manual-review"],
    submissionMethod: "official-kspc-album-ep-digital-physical-music-submission-route",
    feeRequired: false,
    feeAmount: "Free-first/manual airplay consideration route. Official KSPC page accepts albums/EPs by physical mail or protected digital email/cloud-download route, excludes singles/demos/cassettes/AI-generated music, and states no payment is accepted for airplay.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for album/EP eligibility, protected email/contact handling, download-link preparation, clean/explicit state, AI-use disclosure, non-single requirement, physical-mail decision and no-payola compliance. No protected contact was decoded, no files were uploaded or transferred, and no email or package was sent.",
    notes: "Official KSPC music-submission page observed with current site footer, physical address, digital submission guidance, no-singles/no-demos policy and no-payment-for-airplay rule. Queued only for manual review."
  },
  {
    name: "KZSU Stanford Music Director Email Physical Send Music Route",
    websiteUrl: "https://kzsu.stanford.edu/",
    submissionUrl: "https://go.kzsu.fm/sendmusic",
    sourceUrl: "https://kzsu.stanford.edu/contact/",
    sourceType: "automation_run_208_public_research",
    country: "United States / Stanford, California freeform college radio",
    language: "en",
    genres: ["college-radio", "freeform", "independent", "new-releases", "electronic", "world", "hip-hop", "physical", "manual-review"],
    submissionMethod: "official-kzsu-music-director-email-physical-send-music-route",
    feeRequired: false,
    feeAmount: "Free-first/manual station route. Official contact page lists Music Directors, public music department email, PO Box/UPS mailing addresses and a public 'send us music' route; no payment route was observed.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for current music-director fit, email/list-selection discipline, physical versus digital route, send-music link review, release metadata, clean/explicit status, genre fit and duplicate-avoidance. No form was submitted, no account used, no files were uploaded, no email was sent and no deliverability probing was performed.",
    notes: "Official KZSU contact page lists the music directors and a public music@kzsu.stanford.edu route, plus PO Box/UPS addresses and a send-music link. Queued manual because route selection and release prep need owner review."
  },
  {
    name: "WUOG Athens Physical Album Music Director Airtime Route",
    websiteUrl: "https://wuog.org/",
    submissionUrl: "https://wuog.org/contact/",
    sourceUrl: "https://wuog.org/contact/",
    sourceType: "automation_run_208_public_research",
    country: "United States / Athens, Georgia college radio",
    language: "en",
    genres: ["college-radio", "alternative", "underground", "local-music", "independent", "album", "physical", "manual-review"],
    submissionMethod: "official-wuog-physical-album-music-director-airtime-route",
    feeRequired: false,
    feeAmount: "Free-first/manual physical album airplay-consideration route. Official WUOG contact page asks artists to mail albums to Music Directors or Local Music Directors for review and staff distribution.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for album format, physical-mail preparation, music versus local-music routing, FCC-clean status, release notes, station-fit assessment and outreach duplication control. No contact form was submitted, no email was sent and no physical package was prepared or mailed.",
    notes: "Official WUOG page shows July 2026 music activity, explains its smaller-artist airtime policy, lists Music Director/Local Music Director routes and provides a physical album submission address."
  },
  {
    name: "KDVS Davis Physical Only Music Department Submission Route",
    websiteUrl: "https://kdvs.org/",
    submissionUrl: "https://kdvs.org/contact",
    sourceUrl: "https://kdvs.org/contact",
    sourceType: "automation_run_208_public_research",
    country: "United States / Davis, California freeform college-community radio",
    language: "en",
    genres: ["college-radio", "freeform", "independent", "experimental", "electronic", "world", "physical-only", "manual-review"],
    submissionMethod: "official-kdvs-physical-only-music-department-submission-route",
    feeRequired: false,
    feeAmount: "Free-first/manual physical-only music department route. Official KDVS contact page lists music directors, public music-department email and explicitly says to send new music to the mailing address as physical submissions only.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for physical-only compliance, current mailing-address confirmation, album packaging, station/genre fit, clean/explicit state, release metadata and no-digital-route expectation. No email was sent, no package was prepared or mailed, and no deliverability probing was performed.",
    notes: "Official KDVS pages show active 2026 charts and a public musicdept@kdvs.org route, but the page states new music should be sent as physical submissions only. Queued manual to confirm current mailing and package details."
  },
  {
    name: "WCBN Ann Arbor Hard Copy Album Music Director Route",
    websiteUrl: "https://wcbn.org/",
    submissionUrl: "https://wcbn.org/c/",
    sourceUrl: "https://wcbn.org/c/",
    sourceType: "automation_run_208_public_research",
    country: "United States / Ann Arbor, Michigan freeform college radio",
    language: "en",
    genres: ["college-radio", "freeform", "independent", "local-music", "electronic", "hip-hop", "reggae", "hard-copy", "manual-review"],
    submissionMethod: "official-wcbn-hard-copy-album-music-director-route",
    feeRequired: false,
    feeAmount: "Free-first/manual hard-copy route. Official WCBN contact page says it accepts music from any musicians willing to send a hard copy, preferably CD or vinyl, and routes it to WCBN MUSIC / genre directors.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for hard-copy CD/vinyl preparation, genre-director routing, mailing decision, protected contact handling, release notes, clean/explicit state, station-fit review and duplicate-avoidance. No protected contact was decoded, no contact was messaged and no package was prepared or mailed.",
    notes: "Official WCBN page shows 24/7 active freeform station context, current 2025-2026 board context, protected music-director contacts and explicit hard-copy CD/vinyl submission guidance. Queued only for manual review."
  }
];
