import type { PlatformInput } from '../models/types.js';

export const run238SeedPlatforms: PlatformInput[] = [
  {
    name: "DailyPlaylists Free Spotify Curator Submission Marketplace Route",
    websiteUrl: "https://dailyplaylists.com/",
    submissionUrl: "https://dailyplaylists.com/",
    sourceUrl: "https://dailyplaylists.com/",
    sourceType: "automation_run_238_public_research",
    country: "Global / Spotify playlist curator submission marketplace",
    language: "en",
    genres: ["dailyplaylists", "spotify-playlists", "playlist-submission", "curators", "independent-artists", "free-standard-submissions", "premium-credits", "professional-tier", "artist-tools", "business-contact-email-observed", "login-session-app-boundary", "payment-pricing-boundary", "manual-review"],
    submissionMethod: "dailyplaylists-free-spotify-curator-submission-marketplace-route",
    feeRequired: false,
    feeAmount: "Free-first/freemium route. Official page says artists can submit music for free to an 18,000+ playlist marketplace, while Premium Credits and Professional features create optional paid boundaries.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for sign-in/account connection, Spotify track link selection, curator targeting, standard versus premium credit use, pricing, anti-spam fit, playlist relevance, business-contact handling and no-guaranteed-placement expectations. No account was created and no song was submitted.",
    notes: "Official DailyPlaylists page exposes Submit a Song, pricing, sign-in and contact surfaces, says the platform has facilitated 75M+ submissions and 500k+ artists submitting, and lists info@dailyplaylists.com as a public contact address. Useful for MarcsMusic Spotify playlist pitching after manual curator-fit review."
  },
  {
    name: "Indiemono Free Spotify Playlist Form Chill Electronic Route",
    websiteUrl: "https://indiemono.com/",
    submissionUrl: "https://indiemono.com/submit-music-chill-playlists/",
    sourceUrl: "https://indiemono.com/submit-music-chill-playlists/",
    sourceType: "automation_run_238_public_research",
    country: "Spain / global Spotify playlist submission route",
    language: "en",
    genres: ["indiemono", "spotify-playlists", "free-submit-music", "chill", "edm", "indie-alternative", "urban-rap-trap-rnb", "latino", "form-route", "cookie-consent-boundary", "no-email-submissions", "manual-review"],
    submissionMethod: "indiemono-free-spotify-playlist-form-chill-electronic-route",
    feeRequired: false,
    feeAmount: "Free public route. Official submission page states the system is free and that artists can send any amount of music through the forms.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for form fields, consent/privacy checkboxes, valid Spotify track URL, genre/category fit, optional agency/services interest fields, cookie/consent boundary and release suitability. No cookie choice was made and no form was submitted.",
    notes: "Official Indiemono route requests name/company, email, track name/artist, Spotify track URL and closest genre, and says they will not reply to email or Facebook submissions. Strong free playlist route for chill, EDM, indie/alternative, urban and related MarcsMusic releases."
  },
  {
    name: "A&R Factory Electronic Music Blog Free Paid Form Route",
    websiteUrl: "https://www.anrfactory.com/",
    submissionUrl: "https://www.anrfactory.com/submit-demo/electronic-music/",
    sourceUrl: "https://www.anrfactory.com/submit-demo/electronic-music/",
    sourceType: "automation_run_238_public_research",
    country: "United Kingdom / global independent music blog and A&R discovery route",
    language: "en",
    genres: ["a-and-r-factory", "music-blog", "electronic", "edm", "dance", "drum-and-bass", "house", "techno", "reggae", "world", "free-submission", "paid-standard", "premium-donation", "payment-pricing-boundary", "form-route", "manual-review"],
    submissionMethod: "a-r-factory-electronic-music-blog-free-paid-form-route",
    feeRequired: false,
    feeAmount: "Free-first route with paid options. Official form lists Free Submission, Standard Submission £20 and Premium Donation Submission £30 with card/PayPal payment fields.",
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for one-track review link, release status/date, EPK/bio/artwork/social links, email processing consent, package choice, budget/service questions and payment boundary if a paid package is selected. No form was submitted and no payment workflow was initiated.",
    notes: "Official A&R Factory page shows active July 2026 posts, describes itself as an independent/A&R blog for global discovery, and exposes genre-specific electronic submission forms with free and paid review/promotion paths. Good fit for MarcsMusic electronic, dubstep, EDM, world and reggae-adjacent releases after editorial-fit review."
  },
  {
    name: "Musosoup Independent Artist Curator Campaign Submission Route",
    websiteUrl: "https://musosoup.com/",
    submissionUrl: "https://app.musosoup.com/",
    sourceUrl: "https://musosoup.com/",
    sourceType: "automation_run_238_public_research",
    country: "United Kingdom / global music promotion and curator marketplace",
    language: "en",
    genres: ["musosoup", "curator-marketplace", "music-promotion", "blogs", "playlists", "radio", "reviews", "interviews", "spotify-playlisting", "free-upload", "campaign-fee", "login-session-app-boundary", "payment-pricing-boundary", "manual-review"],
    submissionMethod: "musosoup-independent-artist-curator-campaign-submission-route",
    feeRequired: true,
    feeAmount: "Free-to-submit/manual paid-campaign route. Official page says artists can upload a single, EP or album for free to get started, but successful campaigns require account creation and a campaign fee, with promotion starting around £42.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for artist account, MP3/link upload, review/approval stage, campaign fee, curator offers, free versus paid offers, marketplace services, release timing, refund/coverage terms, AI/botted-playlist policies and rights/metadata. No account was created, no music was uploaded and no campaign was activated.",
    notes: "Official Musosoup page presents a submit-music app route, independent-artist curator network, coverage across blogs/playlists/magazines/radio/social, 200+ genres including electronic, house, techno, hip hop, world and R&B, and active July 2026 blog posts. Strong manual promotion route only after budget and owner approval."
  },
  {
    name: "CD Baby Paid Global Digital Distribution Upload Route",
    websiteUrl: "https://cdbaby.com/",
    submissionUrl: "https://members.cdbaby.com/",
    sourceUrl: "https://cdbaby.com/music-distribution/",
    sourceType: "automation_run_238_public_research",
    country: "United States / global digital music distribution route",
    language: "en",
    genres: ["cd-baby", "digital-distribution", "spotify", "apple-music", "youtube-music", "tiktok", "deezer", "pandora", "150-plus-partners", "one-time-fee", "release-upload", "human-inspection", "login-session-app-boundary", "payment-pricing-boundary", "manual-review"],
    submissionMethod: "cd-baby-paid-global-digital-distribution-upload-route",
    feeRequired: true,
    feeAmount: "Paid/manual distribution route. Official page states distribution starts at $9.99 per release and describes $9.99 singles and $14.99 albums with no recurring subscription fees.",
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Owner review required for account/session, release type, per-release fee, audio/artwork upload, metadata, UPC/barcodes, rights/copyright checks, cover licensing if applicable, human inspection, DSP delivery timing and distributor overlap with existing MarcsMusic distribution. No account was created, no release was uploaded and no payment was initiated.",
    notes: "Official CD Baby pages state it distributes to 150+ streaming/download services worldwide, including Spotify, Apple Music, TikTok, Amazon, Pandora, YouTube and Deezer, and that submissions/files are inspected before delivery. This is a distribution route, not an editorial pitch, and should be used only after catalog/distributor strategy review."
  }
];
