import type { PlatformInput } from '../models/types.js';

export const run318SeedPlatforms: PlatformInput[] = [
  {
    name: 'KUTX On-Air Rotation and Electronic Specialty Submission',
    websiteUrl: 'https://kutx.org/',
    submissionUrl: 'https://kutx.org/submit-your-music/',
    sourceUrl: 'https://kutx.org/submit-your-music/',
    sourceType: 'automation_run_318_public_research',
    country: 'United States / Austin, Texas public music radio with worldwide online streams',
    language: 'en',
    genres: [
      'new-music',
      'electronic',
      'experimental',
      'beat-music',
      'hip-hop',
      'r-and-b',
      'latin',
      'indie',
      'jazz',
      'public-radio',
      'direct-email-submission',
      'specialty-show-routing',
      'manual-review'
    ],
    submissionMethod: 'official-public-music-director-email-with-specialty-show-routing',
    feeRequired: false,
    feeAmount: 'No music-submission fee is stated; optional third-party file hosting is sender-managed.',
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'KUTX accepts finished music through a purpose-specific Music Director email and permits separate pitching to relevant specialty shows. A human must approve the final email, confirm the release is mastered and FCC-clean, provide a working streaming link and WAV download, select the most relevant route, and avoid invitation-only or paid event-promotion workflows.',
    notes: 'Verified on 2026-07-13 from KUTX first-party submission and homepage pages. KUTX publishes music@kutx.org for on-air rotation and asks for the subject Music Submission - [Artist Name], a streaming link, a Dropbox or Google Drive WAV download rather than an MP3 attachment, a short biography and release context, and a highlighted top track when several are supplied. Only final mastered, new or upcoming, clean radio edits are requested. The same official page lists Soundfounder for electronic and experimental music, The Breaks for hip-hop, rap and R&B, Horizontes for Latin music, and other specialty routes; separate Qualtrics event and invitation-only session workflows were not classified as general music-submission routes. The address was verified as a plaintext, domain-matched, purpose-specific business email published by KUTX. Current activity was confirmed through dated articles and episodes from 2026-07-08 through 2026-07-11, including a 2026-07-08 Soundfounder episode featuring electronic and beat music from Austin and around the world. No email, WAV link, streaming link, biography or release material was prepared or sent.'
  },
  {
    name: 'Fresh On The Net Weekly Listening Post Submission',
    websiteUrl: 'https://freshonthenet.co.uk/',
    submissionUrl: 'https://freshonthenet.co.uk/submit/',
    sourceUrl: 'https://freshonthenet.co.uk/submit/',
    sourceType: 'automation_run_318_public_research',
    country: 'United Kingdom / worldwide online new-music discovery platform open to any artist',
    language: 'en',
    genres: [
      'new-music',
      'independent',
      'electronic',
      'ambient',
      'alternative',
      'pop',
      'hip-hop',
      'world',
      'reggae-adjacent',
      'weekly-submission-window',
      'public-streaming-link',
      'ai-origin-restriction',
      'manual-review'
    ],
    submissionMethod: 'official-windowed-first-party-track-submission-form',
    feeRequired: false,
    feeAmount: 'No submission fee is stated.',
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Fresh On The Net opens its first-party inbox only from Monday until 200 tracks are received or Wednesday evening, and it was closed during verification. A human must return during an open window, inspect the live form and any runtime controls, confirm the track is public worldwide and has not been submitted before, verify non-AI origin and eligibility, and complete the submission without attempting to influence community voting.',
    notes: 'Verified on 2026-07-13 from the Fresh On The Net first-party Send Us A Track and homepage pages. Any artist may submit one track per week; the team states that it listens to every accepted track. The inbox opens Monday morning and closes at 200 tracks or Wednesday evening, whichever comes first, and the official page displayed the inbox as closed during this check. Tracks must be publicly available in full worldwide, must not be private, SoundCloud Go-only or country-restricted, and repeat submissions, previously submitted remixes and AI-generated tracks are excluded. Artists featured in the Listening Post must not solicit votes. The page also publishes del.owusu@gmail.com for a conditional Exile FM radio submission only after the artist has first submitted to Fresh On The Net; that downstream address was recorded as an official-page-published conditional route, not a replacement for the primary form, and no mailbox-level probe was performed. Activity was confirmed through a Listening Post batch dated 2026-07-10 and other current July 2026 posts. No form, track, social profile, email or radio edit was supplied.'
  },
  {
    name: 'WRIR Music Department Email Submission',
    websiteUrl: 'https://www.wrir.org/',
    submissionUrl: 'https://www.wrir.org/station/contact/',
    sourceUrl: 'https://www.wrir.org/station/contact/',
    sourceType: 'automation_run_318_public_research',
    country: 'United States / Richmond, Virginia community radio with worldwide online streaming',
    language: 'en',
    genres: [
      'community-radio',
      'freeform',
      'electronic',
      'house',
      'drum-and-bass',
      'reggae',
      'world',
      'hip-hop',
      'independent',
      'experimental',
      'protected-email-route',
      'manual-review'
    ],
    submissionMethod: 'official-protected-first-party-music-department-email-route',
    feeRequired: false,
    feeAmount: 'No music-submission fee is stated.',
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'WRIR explicitly directs music submissions to its Music Department, but the first-party email address is protected in passive extraction. A human must open the official contact page, use the displayed authorized address without decoding or guessing it programmatically, confirm current submission expectations and suitable programming, prepare the pitch, and send it manually.',
    notes: 'Verified on 2026-07-13 from WRIR first-party Contact and homepage pages. The Contact page, marked updated in 2026, states that music submissions should be written to the Music Department and presents the address through a protected first-party email link. The address was not decoded, guessed or stored as plaintext. Advertising, PSA, ticket-giveaway, social-media and general-contact addresses are separately identified and were excluded from the music queue. WRIR operates a broad schedule relevant to MarcsMusic, including House Music Sessions, Frequency drum-and-bass programming, Ambiance Congo and other world-music shows, hip-hop, experimental and freeform programming. Current activity was confirmed by dated programming and playlists on 2026-07-11 and 2026-07-12, including Frequency #1123 focused on drum and bass. No email, music link, attachment, pitch or protected contact value was supplied or extracted.'
  }
];
