import type { PlatformInput } from '../models/types.js';

export const run348SeedPlatforms: PlatformInput[] = [
  {
    "name": "CKUT 90.3 FM Montreal Music Department Digital MP3 and Physical Airplay Route",
    "websiteUrl": "https://ckut.ca/",
    "submissionUrl": "https://ckut.ca/submit-music-to-ckut/",
    "sourceUrl": "https://ckut.ca/submit-music-to-ckut/",
    "sourceType": "automation_run_348_public_research",
    "country": "Canada / Montreal, Quebec / campus-community radio; the official page explicitly accepts recordings from artists and record companies around the world",
    "language": "en",
    "genres": [
      "electronic",
      "experimental",
      "techno",
      "electro",
      "house",
      "hip-hop",
      "reggae",
      "dancehall",
      "world-music",
      "indie",
      "campus-radio",
      "community-radio",
      "airplay-submission",
      "album-submission",
      "ep-submission",
      "digital-mp3-submission",
      "physical-submission",
      "manual-review"
    ],
    "submissionMethod": "official-music-department-email-for-320-kbps-mp3-release-with-optional-physical-delivery",
    "feeRequired": false,
    "feeAmount": "No submission fee, account, login or mandatory payment is stated for the official Music Department email or physical-delivery route.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "CKUT accepts digital releases by email only when they meet the station's library criteria: 320-kbps MP3 files, no singles, and at least three distinct tracks except for 7-inch vinyl. The public page does not fully specify the preferred digital delivery mechanism, attachment-size limits, required metadata, release window, rights language, content labels, AI-origin policy or response timing. A human must confirm the current rules, select an eligible MarcsMusic album or EP, prepare the permitted files or delivery link and release information, verify rights and content labels, and send manually. Optional CD, cassette or vinyl delivery also requires manual handling.",
    "notes": "Verified on 2026-07-14 from CKUT's official Submitting Music, Contact, Music Department, schedule and homepage pages. CKUT explicitly states that its DJs choose recordings sent by artists and record companies around the world. It accepts 320-kbps MP3 digital submissions at music@ckut.ca, evaluates them under the same criteria as physical releases, rejects singles and generally requires at least three distinct tracks; CDs, cassettes and 12-inch or 7-inch vinyl are also accepted. Current activity was confirmed through the active program schedule, a Music Department post dated 2026-07-05 promoting a 2026-07-12 edition, and 2026 station notices. Genre fit includes experimental and uncommon music, electronic, techno, electro, house, hip-hop, reggae, world and open-format programming. The business email was verified only through consistent official publication, valid syntax, first-party domain alignment and stated Music Department purpose; no SMTP, MX, catch-all, mailbox-level or deliverability probe was performed."
  },
  {
    "name": "CJAM 99.1 FM Windsor Music Director Digital Album and EP Download-Link Route",
    "websiteUrl": "https://www.cjam.ca/",
    "submissionUrl": "https://www.cjam.ca/submit/",
    "sourceUrl": "https://www.cjam.ca/submit/",
    "sourceType": "automation_run_348_public_research",
    "country": "Canada / Windsor, Ontario and Detroit coverage / campus-community radio; the official music page welcomes independent music of any genre created anywhere",
    "language": "en",
    "genres": [
      "electronic",
      "techno",
      "house",
      "bass-music",
      "dub",
      "hip-hop",
      "world-music",
      "indie",
      "experimental",
      "campus-radio",
      "community-radio",
      "airplay-submission",
      "album-submission",
      "ep-submission",
      "digital-download-submission",
      "manual-review"
    ],
    "submissionMethod": "official-music-director-gmail-for-downloadable-four-plus-track-release",
    "feeRequired": false,
    "feeAmount": "No submission fee, account, login or mandatory payment is stated for the official digital Music Director route.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "CJAM is digital-only and requires an email to its Music Director containing artist and release information plus a reliable download link. Spotify links and direct MP3 attachments are rejected; releases must contain at least four original tracks, use MP3 or AAC at 192 kbps minimum or FLAC, and include complete embedded tags. A human must confirm current requirements, select an eligible MarcsMusic album or EP, prepare a reliable Dropbox, WeTransfer or Google Drive download, verify file quality, tags, rights and content labels, and send manually. The destination is a publicly authorized role mailbox hosted on Gmail rather than the station domain, so official-page consistency must be rechecked immediately before use.",
    "notes": "Verified on 2026-07-14 from CJAM's official Submit, Music, Contact and homepage pages. CJAM has moved to digital-only submissions and publishes cjammd@gmail.com for Music Director Austin DiPietro. It requests a downloadable release with four or more original tracks, minimum 192-kbps MP3 or AAC or optional FLAC, embedded artist, title, album, track-number, composer and genre tags, and artist/release information in the message or a PDF EPK. Spotify-only links, direct MP3 attachments, shorter singles and album samplers are not accepted. Current activity was confirmed through the July 2026 Singles Club feature, charts covering 2026-06-29 through 2026-07-05, and current staffing. CJAM states that it shares independent music of any genre created anywhere and specifically programs electronic, techno, hip-hop, dub and other niche genres. The Gmail business address was verified only through identical publication on multiple official CJAM pages, valid syntax and explicit Music Director/submission purpose; no SMTP, MX, catch-all, mailbox-level or deliverability probe was performed."
  }
];
