import type { PlatformInput } from '../models/types.js';

export const run315SeedPlatforms: PlatformInput[] = [
  {
    name: 'WMBR Freeform Physical Music Submission',
    websiteUrl: 'https://wmbr.mit.edu/',
    submissionUrl: 'https://wmbr.mit.edu/www/md',
    sourceUrl: 'https://wmbr.mit.edu/www/md',
    sourceType: 'automation_run_315_public_research',
    country: 'United States / Cambridge, Massachusetts freeform college and community radio with worldwide streaming',
    language: 'en',
    genres: [
      'freeform',
      'independent',
      'unsigned',
      'electronic',
      'techno',
      'world',
      'experimental',
      'college-radio',
      'physical-submission',
      'manual-review'
    ],
    submissionMethod: 'official-physical-mail-music-director-submission',
    feeRequired: false,
    feeAmount: 'No submission fee is stated; physical media, packaging and international postage are sender-funded.',
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'WMBR urges artists and labels to submit music in tangible physical form and does not invite MP3 review. A human must confirm format and genre fit, prepare one physical release with a concise one-sheet, use the specific Music Director address published on the official submission page, approve postage, and avoid unsolicited mailing-list updates or request campaigns.',
    notes: 'Verified on 2026-07-12 from WMBR first-party Your Music, Contact and homepage pages. WMBR accepts unsigned artists on the same basis as label releases and directs physical music to Attn: Music Director, WMBR Radio, 3 Ames Street, Cambridge, MA 02142. It recommends a concise one-sheet and says glossy press kits are irrelevant. The station states that it lacks capacity to review MP3s and prefers tangible physical media. Its Music Department email is presented as a non-plaintext image link on the official contact page; it was not decoded or substituted for the physical route. Current operation was confirmed through a live stream, schedule, current special events and a homepage broadcast reference dated 2026-06-09. No package, email or submission was prepared or sent.'
  },
  {
    name: 'KVRX Non-AI Digital and Physical Music Submission',
    websiteUrl: 'https://kvrx.org/app/',
    submissionUrl: 'https://kvrx.org/app/contact/',
    sourceUrl: 'https://kvrx.org/app/contact/',
    sourceType: 'automation_run_315_public_research',
    country: 'United States / Austin, Texas student-run underground radio with worldwide online listening',
    language: 'en',
    genres: [
      'underground',
      'independent',
      'electronic',
      'world',
      'reggae',
      'hip-hop',
      'rock',
      'pop',
      'punk',
      'college-radio',
      'public-business-email',
      'physical-submission',
      'manual-review'
    ],
    submissionMethod: 'official-purpose-specific-public-email-or-physical-mail-submission',
    feeRequired: false,
    feeAmount: 'No submission fee is stated; optional physical media, packaging and postage are sender-funded.',
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'KVRX explicitly excludes AI-assisted or AI-generated music and accepts both digital and physical submissions. A human must verify the selected MarcsMusic track satisfies that origin rule, choose digital email or physical delivery, prepare only authorized assets, confirm any attachment or link expectations that are not stated on the page, and send only to the published Music Department route.',
    notes: 'Verified on 2026-07-12 from KVRX first-party Contact, homepage, schedule and blog pages. KVRX publishes music@kvrx.org for all music submissions considered for airplay and operations@kvrx.org for other submission questions. The page states that submissions sent to Programming will not be reviewed and that both physical and digital submissions are currently accepted. It also states that AI-assisted/generated music and submissions will not be considered. The physical address is KVRX, 2504 C Whitis Avenue - HSM 3.200, Mail Stop E4100, Austin, TX 78712. Activity was confirmed through a Summer 2026 schedule, live signal, and blog posts dated through 2026-06-30. The two business addresses were verified as first-party published and purpose-specific; no SMTP, MX, catch-all or mailbox-level probe was performed. No email, file, link or package was sent.'
  },
  {
    name: 'Radio K KUOM Digital and Physical Music Submission',
    websiteUrl: 'https://radiok.org/',
    submissionUrl: 'https://radiok.org/submitting-music',
    sourceUrl: 'https://radiok.org/submitting-music',
    sourceType: 'automation_run_315_public_research',
    country: 'United States / Minneapolis, Minnesota independent college radio with worldwide streaming',
    language: 'en',
    genres: [
      'independent',
      'eclectic',
      'electronic',
      'world',
      'specialty-radio',
      'college-radio',
      'digital-submission',
      'physical-submission',
      'protected-email-link',
      'manual-review'
    ],
    submissionMethod: 'official-protected-music-department-email-with-download-link-or-physical-mail-submission',
    feeRequired: false,
    feeAmount: 'No submission fee is stated; optional physical media, packaging, third-party hosting and postage may have sender costs.',
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Radio K accepts physical releases or a digital email containing a ZIP download link from Google Drive, Dropbox or a similar service, and prefers lossless WAV or FLAC files. A human must open the protected first-party Music Department email link without automated decoding, confirm genre fit, prepare the correct files and metadata, manage any external hosting session, flag non-FCC tracks, and approve the final email or package.',
    notes: 'Verified on 2026-07-12 from Radio K first-party Submitting Music, Contact, About and homepage pages. Physical releases go to Radio K - KUOM, University of Minnesota, 610 Rarig Center, 330 21st Ave. S, Minneapolis, MN 55455. Digital submissions must be emailed to the official Music Department with a ZIP link hosted on Google Drive, Dropbox or a similar service; the station prefers WAV or FLAC, and Bandcamp download codes or free-release links are accepted. The email address is protected through a non-plaintext first-party link and was not decoded or guessed. Radio K says it generally does not play classical or Top 40, asks for a short bio, contact information, comparable artists, non-FCC tracks and 2-3 focus tracks, and does not accept tracking-status requests. Activity was confirmed through live programming, current additions, events on 2026-07-12 and editorial posts dated through 2026-07-02. No hosting account, email, file, code, package or submission was used.'
  }
];
