import type { PlatformInput } from '../models/types.js';

export const run327SeedPlatforms: PlatformInput[] = [
  {
    "name": "Muti Music Public Demo and Inquiry Email/Form Route",
    "websiteUrl": "https://www.mutimusic.com/",
    "submissionUrl": "mailto:label@mutimusic.com",
    "sourceUrl": "https://www.mutimusic.com/contact/",
    "sourceType": "automation_run_327_public_research",
    "country": "United States / San Francisco independent global bass-music label",
    "language": "en",
    "genres": [
      "muti-music",
      "electronic",
      "bass-music",
      "halftime",
      "drum-and-bass",
      "dubstep",
      "uk-bass",
      "trap",
      "dub",
      "jungle",
      "garage",
      "2-step",
      "glitch-hop",
      "ragga",
      "experimental",
      "direct-email",
      "native-contact-form",
      "manual-review"
    ],
    "submissionMethod": "official-public-demos-inquiries-email-or-native-contact-form",
    "feeRequired": false,
    "feeAmount": "No demo-submission fee, login or payment requirement is stated on Muti Music's official contact page.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "Muti Music explicitly publishes label@mutimusic.com for Demos/Inquiries and also provides a native contact form, but the official page does not state definitive audio-format, attachment, link, release-status, submission-limit or rights-declaration rules. A human must choose the authorized email or form route, select a genuinely suitable track, approve the pitch and metadata, verify ownership and link permissions, and confirm the live route's current requirements before sending anything. No attachment or private/download link should be supplied automatically.",
    "notes": "Verified on 2026-07-13 from Muti Music's official contact, homepage, about and releases pages. The first-party contact page publishes label@mutimusic.com under Demos/Inquiries and exposes name, email, subject and message fields. The label describes itself as an independent San Francisco label established in 2002 and lists electronic and bass styles strongly aligned with MarcsMusic, including halftime, drum-and-bass, dubstep, UK bass, dub, jungle, garage, 2-step, glitch hop, ragga and experimental sounds. Current activity was confirmed through official news dated 19 June 2026 and 28 March 2026 and a releases catalogue with a 2026 filter and current titles. The mailbox was checked only for official publication, syntax, first-party domain alignment and purpose. No email, form, file or link was sent and no SMTP, MX, catch-all, mailbox or deliverability probe was performed."
  },
  {
    "name": "Odyzey Music Public Submission Email and Contact Form Route",
    "websiteUrl": "https://www.odyzeymusic.com/",
    "submissionUrl": "mailto:music@odyzeymusic.com",
    "sourceUrl": "https://www.odyzeymusic.com/contact",
    "sourceType": "automation_run_327_public_research",
    "country": "United States / global live-electronic and world-inspired independent label",
    "language": "en",
    "genres": [
      "odyzey-music",
      "electronic",
      "live-electronic",
      "world-inspired",
      "global-bass",
      "organic-electronic",
      "downtempo",
      "experimental-bass",
      "independent-label",
      "direct-email",
      "native-contact-form",
      "manual-review"
    ],
    "submissionMethod": "official-public-submission-email-with-optional-native-contact-form",
    "feeRequired": false,
    "feeAmount": "No submission fee, account, login or payment requirement is stated on Odyzey Music's official contact page.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "Odyzey Music explicitly publishes music@odyzeymusic.com for Submissions and provides a native contact form, but does not publish complete audio-format, link, attachment, release-status, rights, response-time or submission-limit instructions on the accessible page. A human must decide whether to use the dedicated mailbox or form, verify that the selected MarcsMusic track fits Odyzey's hybrid live/electronic and globally inspired direction, approve the pitch and metadata, confirm rights and link permissions, and inspect the live route before sending. No submission should be automated merely because the mailbox is public.",
    "notes": "Verified on 2026-07-13 from Odyzey Music's official homepage and contact page. The contact page publishes music@odyzeymusic.com specifically for Submissions and exposes name, email, subject and message fields. The official homepage states that the label was founded in 2020 and explores a hybrid of live and electronic elements with inspiration drawn from around the world, making it relevant to MarcsMusic's electronic, bass and world-fusion catalogue. Platform activity was verified through the live first-party label site, active public contact workflow and currently accessible artist/release presentation. The mailbox was checked only for official publication, syntax, first-party domain alignment and submission purpose. No email, form, asset, track link or file was sent and no SMTP, MX, catch-all, mailbox or deliverability probe was performed."
  }
];
