import type { PlatformInput } from '../models/types.js';

export const run323SeedPlatforms: PlatformInput[] = [
  {
    "name": "Radio One 91FM Music Department Airplay Submission",
    "websiteUrl": "https://www.r1.co.nz/",
    "submissionUrl": "https://www.r1.co.nz/contact",
    "sourceUrl": "https://d3r9t6niqlb7tz.cloudfront.net/media/documents/Getting_Airplay_on_Alt_Radio.pdf",
    "sourceType": "automation_run_323_public_research",
    "country": "New Zealand / Dunedin alternative student radio with public digital and physical music-submission routes",
    "language": "en",
    "genres": [
      "alternative",
      "independent",
      "electronic",
      "experimental",
      "hip-hop",
      "reggae",
      "world",
      "student-radio",
      "airplay",
      "email-submission",
      "physical-submission",
      "manual-review"
    ],
    "submissionMethod": "official-public-music-department-email-or-physical-delivery",
    "feeRequired": false,
    "feeAmount": "No submission fee or mandatory payment is stated; physical postage is optional and paid by the sender.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "Radio One publicly designates music@r1.co.nz for music submissions and also lists a physical delivery address. Its linked alternative-radio servicing guide asks for a personal email, contact details, a correctly named and tagged download at minimum 320 kbps MP3 quality, focus songs and a one-page information sheet. The guide is written around New Zealand artists, so a human must confirm whether the specific MarcsMusic release is eligible and relevant as an international submission, select the correct track and specialty-program fit, verify the current delivery preference, release timing, explicit-content policy, rights and AI-origin requirements, and approve the final message before any email or parcel is sent.",
    "notes": "Verified on 2026-07-13 from Radio One's official homepage, contact page and linked Getting Airplay on Alt Radio guide. The contact page names Maddy Barnes as Music Director, publishes music@r1.co.nz specifically under MUSIC SUBMISSIONS and provides PO Box 1436, Dunedin 9016 for physical music submissions. The station homepage and programme pages show an active 2026 service, current weekly programming, podcasts and a Top 11 countdown. The guide recommends a minimum 320 kbps MP3 download, correct metadata, a personal introduction, contact details, focus songs and a one-page information sheet. No email was sent, no track or download link was supplied, no physical package was prepared, and no mailbox, SMTP or MX probe was performed. Other staff addresses are retained only as business-contact evidence and are not alternative submission inboxes."
  },
  {
    "name": "Radio Control 99.4FM Music Submission",
    "websiteUrl": "https://www.radiocontrol.org.nz/",
    "submissionUrl": "https://www.radiocontrol.org.nz/contact",
    "sourceUrl": "https://www.radiocontrol.org.nz/contact",
    "sourceType": "automation_run_323_public_research",
    "country": "New Zealand / Palmerston North alternative student radio broadcasting locally and streaming worldwide",
    "language": "en",
    "genres": [
      "alternative",
      "independent",
      "electronic",
      "experimental",
      "hip-hop",
      "reggae",
      "world",
      "student-radio",
      "airplay",
      "email-submission",
      "physical-submission",
      "manual-review"
    ],
    "submissionMethod": "official-public-music-submission-email-or-snail-mail",
    "feeRequired": false,
    "feeAmount": "No submission fee or mandatory payment is stated; physical postage is optional and paid by the sender.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "Radio Control publicly lists music@radiocontrol.org.nz for Music Submissions and a station postal address, but the official contact page does not state the accepted audio format, attachment or download-link rules, release-age limits, explicit-content requirements, rights declarations, AI-origin policy or response expectations. A human must confirm the live submission requirements, choose a suitable alternative/electronic track, avoid large unsolicited attachments, approve the pitch and decide between email and optional physical delivery before contacting the station.",
    "notes": "Verified on 2026-07-13 from Radio Control's official homepage and contact page. The homepage states that the station broadcasts 24/7 from Massey University, streams worldwide and plays alternative music from Aotearoa and the rest of the world. It publishes current 2026 programming including an NZ Top Ten, live sessions and 100% NZ Music Week dated 25-31 May 2026. The contact page publishes music@radiocontrol.org.nz specifically for Music Submissions and a snail-mail address at Massey University. manager@radiocontrol.org.nz, pd@radiocontrol.org.nz and other staff addresses are general role contacts and are not queued as alternative music-delivery routes. No email or parcel was sent, no track, file, link or metadata was supplied, and no mailbox, SMTP or MX probe was performed."
  },
  {
    "name": "95bFM Official Submit Music Route",
    "websiteUrl": "https://www.95bfm.com/",
    "submissionUrl": "https://www.95bfm.com/news/how-do-you-do-submitting-music",
    "sourceUrl": "https://www.95bfm.com/",
    "sourceType": "automation_run_323_public_research",
    "country": "New Zealand / Auckland independent corporate-free alternative radio with an official Submit Music route",
    "language": "en",
    "genres": [
      "alternative",
      "independent",
      "electronic",
      "experimental",
      "hip-hop",
      "reggae",
      "world",
      "student-radio",
      "airplay",
      "official-submission-page",
      "protected-contact",
      "manual-review"
    ],
    "submissionMethod": "official-public-submit-music-page-with-runtime-requirements-manual",
    "feeRequired": false,
    "feeAmount": "No mandatory submission payment is visible from the official homepage route; any optional advertising, membership or support products are separate and must not be treated as submission requirements.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "95bFM exposes a first-party Submit Music link in its official site navigation, but the linked page could not be passively rendered during verification, so its current fields, accepted file or link formats, locality rules, consent language, CAPTCHA or anti-spam controls, login requirements and any optional commercial choices remain unverified. The site's public email link is Cloudflare-protected and was not decoded. A human must open the official page normally, review all live requirements and security controls, confirm MarcsMusic eligibility and track fit, and complete any submission without automation or bypassing protection.",
    "notes": "Verified on 2026-07-13 from 95bFM's official homepage. The site identifies 95bFM as an independent corporate-free broadcaster based at the University of Auckland and links directly to a dedicated Submit Music page. The homepage shows a live on-air schedule, current programme information, 2026 event promotion, a Top 10, podcasts and active station support pages. The dedicated submission page returned a passive cache/rendering failure in the research tool, so no hidden endpoint, field list or contact address was inferred. The footer email route is protected through a first-party Cloudflare email-protection path and was not decoded or used. No form, email or message was submitted; no account, CAPTCHA, anti-bot control, payment, track, file or private link was used; and no mailbox, SMTP or MX probe was performed."
  }
];
