import type { PlatformInput } from '../models/types.js';

export const run321SeedPlatforms: PlatformInput[] = [
  {
    "name": "4ZZZ General Music Department Airplay Submission",
    "websiteUrl": "https://4zzz.org.au/",
    "submissionUrl": "https://jeff.4zzz.org.au/form/submit-your-music-to-4zzz",
    "sourceUrl": "https://4zzz.org.au/music-submissions",
    "sourceType": "automation_run_321_public_research",
    "country": "Australia / Brisbane, Queensland community radio with worldwide streaming and an official digital submission form that states no Australian-only restriction",
    "language": "en",
    "genres": [
      "community-radio",
      "electronic",
      "experimental",
      "alternative",
      "hip-hop",
      "reggae",
      "dub",
      "world",
      "independent",
      "first-party-submission-form",
      "javascript-required",
      "public-follow-up-email",
      "manual-review"
    ],
    "submissionMethod": "official-first-party-javascript-music-submission-form",
    "feeRequired": false,
    "feeAmount": "No music-submission fee is stated.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "The official form requires JavaScript and asks for artist contact data, release metadata, optional identity information, pre-release airplay permission, content-warning details, a downloadable WAV or 320 kbps MP3 link, artwork, social links and an explicit airplay acknowledgement. A human must review privacy-sensitive fields, rights and file access, and complete any runtime validation controls. The published music-department address is follow-up only, not an alternative initial submission inbox.",
    "notes": "Verified on 2026-07-13 from the 4ZZZ first-party Music Submissions, form, Contact, Programs and homepage pages. The general Music Department form considers releases for inclusion in the station digital library and requires a downloadable stream or file link; non-downloadable streams and Spotify-only links are not accepted. It requests one contact email, artist name and location, release title/date/genres, label or distributor, member names and pronouns, optional demographic disclosures, biography or press-pack information, content warnings, downloadable WAV or 320 kbps MP3 access, optional download code, artwork and social links. The submitter must acknowledge permission for airplay on 102.1FM and Zed Digital. music-department@4zzz.org.au is officially published only for following up an existing submission, so it is not queued as the initial route. The separate Album of the Week form is limited to Australian artists and is excluded for MarcsMusic. Current activity was confirmed through live programming and on-demand listings dated 12 July 2026, a July 2026 Album of the Week and current station events. No form, email, permission, identity field, asset or link was submitted."
  },
  {
    "name": "2SER Digital Music Director Airplay Submission",
    "websiteUrl": "https://www.2ser.com/",
    "submissionUrl": "https://www.2ser.com/how-to-submit-music",
    "sourceUrl": "https://www.2ser.com/how-to-submit-music",
    "sourceType": "automation_run_321_public_research",
    "country": "Australia / Sydney, New South Wales community radio with an official digital form and public Music Director inbox; no international exclusion is stated",
    "language": "en",
    "genres": [
      "community-radio",
      "alternative",
      "electronic",
      "experimental",
      "hip-hop",
      "world",
      "independent",
      "first-party-submission-form",
      "direct-email-submission",
      "dynamic-form-boundary",
      "digital-only",
      "manual-review"
    ],
    "submissionMethod": "official-first-party-form-or-public-music-director-email",
    "feeRequired": false,
    "feeAmount": "No music-submission fee is stated.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "2SER publishes both a first-party submission form and submitmusic@2ser.com for digital airplay consideration. The embedded form is dynamically loaded and its complete upload/link constraints, consent text and runtime anti-spam controls are not fully visible in passive review. A human must choose one authorized route, approve personal and artist data, verify the music asset and release information, and avoid duplicate servicing. Physical copies must not be sent unless requested.",
    "notes": "Verified on 2026-07-13 from the 2SER first-party How to Submit Music, Contact and homepage pages. The form states that it is for airplay consideration and visibly requests first name, last name, email, a required music-submission field, location, release date, artist or band name, release title, artist bio and social links. The official Contact page publishes submitmusic@2ser.com specifically for digital delivery to the Music Director and instructs artists not to send physical copies unless requested. info@2ser.com and feedback@2ser.com were confirmed as general-purpose business contacts but are not music-submission routes. The site describes 2SER as a 24-hour Sydney community broadcaster and carries current 2026 programming and music content; a human should still assess fit because much of the station's music coverage emphasizes Australian and Sydney scenes. No email, form, audio, link, biography or physical copy was prepared or sent, and no runtime form control was handled."
  },
  {
    "name": "Triple R Station Music Service Submission",
    "websiteUrl": "https://www.rrr.org.au/",
    "submissionUrl": "https://www.rrr.org.au/get-involved/submit-music",
    "sourceUrl": "https://www.rrr.org.au/get-involved/submit-music",
    "sourceType": "automation_run_321_public_research",
    "country": "Australia / Melbourne, Victoria independent community radio with an official station-wide email route, presenter routes and worldwide streaming",
    "language": "en",
    "genres": [
      "community-radio",
      "electronic",
      "house",
      "jungle",
      "ambient",
      "experimental",
      "hip-hop",
      "dub",
      "reggae",
      "global",
      "independent",
      "direct-email-submission",
      "optional-presenter-outreach",
      "optional-physical-submission",
      "manual-review"
    ],
    "submissionMethod": "official-public-station-music-email-or-authorized-presenter-contact",
    "feeRequired": false,
    "feeAmount": "No editorial submission fee is stated; optional physical media and postage are sender costs.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "Triple R requires a human-written email with a clear subject, login-free stream, non-expiring high-quality download, correctly named files, biography and relevant gig details. A human must choose between the station-wide music@rrr.org.au route and a suitable presenter, verify file permissions and rights, and keep optional physical delivery separate. Large audio attachments must not be emailed.",
    "notes": "Verified on 2026-07-13 from Triple R first-party Submit Music, Contact, Programs and homepage pages. The station-wide authorized route is music@rrr.org.au. Triple R asks for a clear subject line, a stream that does not require login, a 320 kbps MP3 or WAV download through Dropbox, Google Drive, non-expiring WeTransfer or similar, clearly named files, a one-to-two-paragraph bio and gig or launch details. Large files must not be attached to email; a PDF press release is allowed but key information should be in the message body. Artists may instead service a relevant presenter through the public contact details on the program page, or mail physical copies to the Music Department. The official staff page identifies music@rrr.org.au as the shared Music Content Producer route; individual staff addresses were observed but are not queued because the shared purpose-specific inbox is sufficient. Current activity was confirmed through episodes dated 12-13 July 2026, videos dated 8 July 2026 and active programs spanning electronic, rave, techno, footwork, jungle, ambient, dub and global music. No email, presenter message, download link, file or physical package was prepared or sent."
  }
];
