import type { PlatformInput } from '../models/types.js';

export const run330SeedPlatforms: PlatformInput[] = [
  {
    "name": "Liquicity Records Official Label Engine Demo Upload Route",
    "websiteUrl": "https://liquicity.com/",
    "submissionUrl": "https://liquicityrecords.label-engine.com/demos?embed=1",
    "sourceUrl": "https://liquicity.com/demo/",
    "sourceType": "automation_run_330_public_research",
    "country": "Netherlands / global liquid and melodic drum-and-bass label and events platform",
    "language": "en",
    "genres": [
      "liquicity",
      "drum-and-bass",
      "liquid-drum-and-bass",
      "melodic-dnb",
      "dancefloor-dnb",
      "electronic",
      "label-engine",
      "third-party-upload-form",
      "manual-review"
    ],
    "submissionMethod": "official-liquicity-demo-page-link-to-label-engine-mp3-upload-form",
    "feeRequired": false,
    "feeAmount": "Liquicity states no submission fee, account, login or payment requirement on its official demo page or the passively rendered Label Engine form.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "Liquicity explicitly routes all music submissions to a Label Engine form that requests artist name, real name, email, up to five titled MP3 uploads, optional social profiles and a short message. The form displayed unresolved template variables during passive review, and its current file limits, privacy text, rights declarations and runtime anti-spam controls were not fully exposed. A human must verify that the form is correctly bound to Liquicity, select and upload only authorized final tracks, review consent and rights terms, approve personal data and submit manually.",
    "notes": "Verified on 2026-07-13 from Liquicity's official demo and releases pages and the linked Label Engine form. Liquicity says the form is the route for all music submissions, that every track is listened to, and that a response is not guaranteed. The external form allows up to five MP3 tracks and asks for artist name, real name, email, track titles, optional social profiles and a message of up to 500 characters. The form rendered unresolved {{demo.NAME}} placeholders, so operational status and current controls require human confirmation. Liquicity's official releases catalogue is active and contains a large current drum-and-bass catalogue. No public demo mailbox was published or inferred. No form, MP3, personal data, link, email, payment or CAPTCHA workflow was used, and no SMTP, MX, catch-all, mailbox or deliverability probe was performed."
  },
  {
    "name": "Circus Records / Circus Electric Official LabelRadar Demo Route",
    "websiteUrl": "https://www.circus-records.co.uk/",
    "submissionUrl": "https://www.labelradar.com/labels/circusrecords/profile",
    "sourceUrl": "https://www.circus-records.co.uk/about/",
    "sourceType": "automation_run_330_public_research",
    "country": "United Kingdom / global bass-music label family",
    "language": "en",
    "genres": [
      "circus-records",
      "circus-electric",
      "bass-music",
      "dubstep",
      "drum-and-bass",
      "electronic",
      "melodic-bass",
      "future-bass",
      "experimental-bass",
      "labelradar",
      "third-party-portal",
      "manual-review"
    ],
    "submissionMethod": "official-circus-about-page-labelradar-only-demo-route-for-circus-records-and-circus-electric",
    "feeRequired": false,
    "feeAmount": "Circus states that demos are accepted through LabelRadar only and does not state a mandatory label fee. LabelRadar may expose account allowances, submission credits or optional paid features; current access and pricing must be reviewed manually.",
    "loginRequired": true,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "Circus explicitly accepts demos through LabelRadar only. The Circus-specific portal rendered only a dynamic loading shell, creating an account, login, session, terms, privacy, submission-credit and possible optional-payment boundary. A human must authenticate through the authorized portal, confirm that the campaign is open, choose the correct Circus Records or Circus Electric fit, inspect current pricing and submission limits, review rights and consent terms, approve the track and metadata, and submit manually. The public general-information mailbox must not be repurposed as a demo-delivery route.",
    "notes": "Verified on 2026-07-13 from Circus Records' official about and releases pages and the linked LabelRadar destination. Circus says it accepts demos via LabelRadar only and identifies Circus Records, Circus Electric and DPMO as its label family. Circus Records focuses on memorable bass-driven dance-floor music, while Circus Electric focuses on futuristic, emotional and boundary-pushing bass. The active releases catalogue lists current Circus Records and Circus Electric singles and EPs across many catalogue pages. The official public address info@circus-records.co.uk is published for questions or requests, is syntactically valid and matches the first-party domain, but it is not a demo mailbox and was not queued for music delivery. The LabelRadar page rendered only a loading shell. No account, login, email, demo, track, form, payment or CAPTCHA workflow was used, and no SMTP, MX, catch-all, mailbox or deliverability probe was performed."
  },
  {
    "name": "Monstercat Uncaged / Instinct / Silk Official LabelRadar Demo Routes",
    "websiteUrl": "https://www.monstercat.com/",
    "submissionUrl": "https://www.labelradar.com/labels/monstercat/portal",
    "sourceUrl": "https://www.monstercat.com/contact-us",
    "sourceType": "automation_run_330_public_research",
    "country": "Canada / United States / global electronic-music label",
    "language": "en",
    "genres": [
      "monstercat",
      "uncaged",
      "instinct",
      "silk",
      "electronic",
      "dubstep",
      "drum-and-bass",
      "trap",
      "electro",
      "melodic-dance",
      "progressive-house",
      "deep-house",
      "trance",
      "ambient",
      "chillout",
      "labelradar",
      "third-party-portal",
      "manual-review"
    ],
    "submissionMethod": "official-monstercat-contact-and-brand-pages-link-to-uncaged-instinct-and-silk-labelradar-demo-portals",
    "feeRequired": false,
    "feeAmount": "Monstercat states no mandatory demo fee on its official contact or brand pages. LabelRadar is an account-based third-party platform that may expose submission allowances, credits or optional paid features; current access and pricing must be reviewed manually.",
    "loginRequired": true,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "Monstercat provides separate authorized LabelRadar routes for Uncaged, Instinct and Silk. The portals rendered only dynamic loading shells and require a human to handle the account, login, session, current campaign, possible submission-credit, terms, privacy and consent boundaries. A human must choose the correct imprint, verify that the work is original and represents the artist's best material, inspect current eligibility and pricing, approve rights and metadata, and submit manually. Support, press, event and general contact routes must not be used for demo delivery.",
    "notes": "Verified on 2026-07-13 from Monstercat's official contact, homepage and Uncaged, Instinct and Silk pages. Monstercat says it listens to every submitted demo and requests only the artist's best original work. Uncaged covers hard-hitting dubstep, drum-and-bass, trap and electro; Instinct focuses on contemporary melodic dance music; Silk covers progressive and deep house, chillout, trance and ambient. The homepage listed releases dated 3, 10 and 13 July 2026, confirming current activity. The Uncaged/Instinct LabelRadar destination and the separate Silk destination both returned dynamic loading shells. Official support, press and event contact links were not treated as demo routes, and protected addresses were not decoded or stored. No cookie choice, account, login, form, track, email, payment or CAPTCHA workflow was used, and no SMTP, MX, catch-all, mailbox or deliverability probe was performed."
  }
];
