import type { PlatformInput } from '../models/types.js';

export const run347SeedPlatforms: PlatformInput[] = [
  {
    "name": "CKUW 95.9 FM Winnipeg Music Director Digital Download and Physical Airplay Route",
    "websiteUrl": "https://ckuw.ca/",
    "submissionUrl": "https://ckuw.ca/contact",
    "sourceUrl": "https://ckuw.ca/contact",
    "sourceType": "automation_run_347_public_research",
    "country": "Canada / Winnipeg, Manitoba / campus-community radio; the official submission guidance is not stated to be local-only",
    "language": "en",
    "genres": [
      "electronic",
      "electronica",
      "ambient",
      "experimental",
      "hip-hop",
      "reggae",
      "dancehall",
      "world-music",
      "indie",
      "campus-radio",
      "community-radio",
      "airplay-submission",
      "digital-download-submission",
      "physical-submission",
      "manual-review"
    ],
    "submissionMethod": "official-purpose-bound-music-director-email-for-high-quality-download-links-with-optional-physical-delivery",
    "feeRequired": false,
    "feeAmount": "No submission fee, account, login or mandatory payment is stated for the Music Director email or physical-delivery route.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "CKUW explicitly rejects unsolicited MP3 attachments and directs digital submissions to its Music Director using a high-quality downloadable link. The public guidance does not specify complete accepted codecs, minimum bitrate, release age, rights language, metadata fields, response timing or AI-origin policy. A human must confirm current requirements, select a suitable MarcsMusic release, prepare a permitted high-quality download link and concise metadata, verify rights and content labels, and send manually. Optional cassette, CD, vinyl or reel-to-reel delivery also requires manual handling.",
    "notes": "Verified on 2026-07-14 from CKUW's official Contact, Staff, Programs and homepage pages. The Staff page publishes music@ckuw.ca for Music Director David Tymoshchuk, and the Contact page explicitly directs digital music submissions to the Music Director while prohibiting unsolicited MP3 attachments. CKUW also accepts cassette, CD, vinyl and reel-to-reel submissions. Current activity was confirmed through live programming, station news dated 2026-05-25 through 2026-06-09 and active electronic/exploratory, ambient, electronica, hip-hop, world and dancehall/reggae programming. The business email was validated only through official publication, syntax, first-party domain alignment and stated staff purpose; no SMTP, MX, catch-all, mailbox-level or deliverability probe was performed."
  },
  {
    "name": "101.5 UMFM CJUM Winnipeg Music Department Download-Link and Physical CD Route",
    "websiteUrl": "https://umfm.com/",
    "submissionUrl": "https://umfm.com/about/music-faq",
    "sourceUrl": "https://umfm.com/about/music-faq",
    "sourceType": "automation_run_347_public_research",
    "country": "Canada / Winnipeg, Manitoba / campus radio; the Music Department FAQ does not state that digital submissions are local-only",
    "language": "en",
    "genres": [
      "electronic",
      "breakbeat",
      "uk-garage",
      "house",
      "bass-music",
      "hip-hop",
      "world-music",
      "indie",
      "campus-radio",
      "airplay-submission",
      "album-submission",
      "ep-submission",
      "digital-download-submission",
      "physical-cd-submission",
      "manual-review"
    ],
    "submissionMethod": "official-music-department-email-link-for-secure-downloadable-release-links-with-optional-physical-cd-delivery",
    "feeRequired": false,
    "feeAmount": "No submission fee, account, login or mandatory payment is stated for the official digital-link or physical-CD routes.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "UMFM accepts digital submissions only through a secure downloadable link and rejects individual audio-file attachments. The official FAQ permits WeTransfer, Dropbox, Google Drive, Bandcamp, DISCO or embedded links, accepts physical EPs only when they contain at least four songs, and does not state complete codec, bitrate, metadata, rights, release-window, AI-origin or response requirements. The official email is exposed through a Cloudflare-protected link and was deliberately not decoded or stored. A human must open the authorized link on the official FAQ, confirm the current address and requirements, verify release eligibility and rights, prepare the download link and metadata, and send manually.",
    "notes": "Verified on 2026-07-14 from UMFM's official Music Department FAQ, program directory and homepage. The FAQ accepts physical CDs and secure downloadable digital links delivered through named transfer or hosting services, prohibits individual audio-file email attachments, rejects physical singles and accepts physical EPs with four or more songs. It states that volunteers choose airplay and that UMFM does not guarantee placement. Current activity was confirmed by homepage news dated 2026-07-06, active charts and programming, including electronic shows covering breakbeat, UK garage, bassy house, hip-hop and world music. The Music Department email link is protected by Cloudflare; it was classified as an authorized route but not decoded, guessed or stored, and no SMTP, MX, catch-all, mailbox-level or deliverability probe was performed."
  }
];
