import type { PlatformInput } from '../models/types.js';

export const run326SeedPlatforms: PlatformInput[] = [
  {
    "name": "Soundplate Free Spotify and Deezer Playlist Submission",
    "websiteUrl": "https://soundplate.com/",
    "submissionUrl": "https://play.soundplate.com/",
    "sourceUrl": "https://play.soundplate.com/",
    "sourceType": "automation_run_326_public_research",
    "country": "United Kingdom / London-founded global playlist-submission platform for independent artists",
    "language": "en",
    "genres": [
      "soundplate",
      "playlist-submission",
      "spotify",
      "deezer",
      "independent-curators",
      "electronic",
      "house",
      "techno",
      "drum-and-bass",
      "garage",
      "bass",
      "reggae",
      "dancehall",
      "ambient",
      "trip-hop",
      "synthwave",
      "oauth",
      "automatic-follow-actions",
      "manual-review"
    ],
    "submissionMethod": "official-free-playlist-selection-flow-with-spotify-or-deezer-oauth-and-disclosed-automatic-follow-actions",
    "feeRequired": false,
    "feeAmount": "Soundplate states that the standard playlist-submission service is free. Advertising, smart links, mastering and other promotional tools are separate optional products and are not required for this route.",
    "loginRequired": true,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "Each playlist must be selected for genuine genre fit. The final submission opens an authorized Spotify or Deezer account connection and discloses automatic following of Soundplate and designated playlists before submission. A human must review those actions, the platform terms, the selected curator and the track before consciously authorizing OAuth. No authentication, consent or automatic-follow action may be performed or bypassed by the agent.",
    "notes": "Verified on 2026-07-13 from Soundplate's official playlist directory, platform homepage and a live Garage & Bass submission page. Soundplate describes the service as free, lists hundreds of independent Spotify curators, says new playlists are added every day and currently exposes electronic, house, techno, drum-and-bass, garage, bass, reggae/dancehall, ambient, trip-hop and synthwave categories relevant to MarcsMusic. The live playlist page publishes fit data and the Spotify/Deezer authorization boundary before the Submit control. Current platform activity was corroborated through active releases, playlist listings and 2026 editorial content. No account was connected, no follow was created and no track was submitted. No public music-submission mailbox was identified or inferred, and no SMTP, MX or deliverability probe was performed."
  },
  {
    "name": "DailyPlaylists Free Standard Spotify Playlist Submission",
    "websiteUrl": "https://dailyplaylists.com/",
    "submissionUrl": "https://dailyplaylists.com/",
    "sourceUrl": "https://dailyplaylists.com/faq/",
    "sourceType": "automation_run_326_public_research",
    "country": "United Kingdom / global independent-artist and Spotify playlist-curator marketplace",
    "language": "en",
    "genres": [
      "dailyplaylists",
      "playlist-submission",
      "spotify",
      "independent-artists",
      "independent-curators",
      "released-tracks-only",
      "single-track",
      "free-tier",
      "freemium",
      "account-required",
      "spotify-api",
      "manual-review"
    ],
    "submissionMethod": "official-free-standard-playlist-marketplace-with-platform-account-and-connected-spotify-profile",
    "feeRequired": false,
    "feeAmount": "The free tier currently includes 10 Standard Submissions per week. Optional boundaries include $7.99 Standard Submission bundles, $19.99 Premium Credit bundles and a $19.99 monthly Professional tier; none is required for the free Standard route.",
    "loginRequired": true,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "DailyPlaylists requires a user account created with email, Google or Facebook and a connected Spotify account before music can be submitted. The track must already be released on Spotify, only an individual song can be submitted, and playlist targeting remains an editorial suitability decision. A human must authorize the account and Spotify API connection, select appropriate Standard curators, avoid optional paid credits or subscriptions unless separately approved and submit manually. No login or account boundary may be handled or bypassed by the agent.",
    "notes": "Verified on 2026-07-13 from DailyPlaylists' official homepage, pricing page and FAQ. The active platform advertises more than 18,000 playlists, a free Standard tier and a current 2026 site footer. Its FAQ states that users now sign in through email, Google or Facebook, must still connect Spotify for submissions, can revoke access, may submit only released individual Spotify tracks and receive no guaranteed response on free Standard submissions. The public address info@dailyplaylists.com was confirmed on the official site, checked for syntax, first-party domain alignment and business-support relevance, and classified as support rather than a music-delivery mailbox. No account, Spotify connection, submission, credit purchase or subscription was initiated, and no SMTP, MX, catch-all, mailbox or deliverability probe was performed."
  }
];
