import type { PlatformInput } from '../models/types.js';

export const run319SeedPlatforms: PlatformInput[] = [
  {
    name: 'CJSR 88.5 FM Album and EP Music Submission',
    websiteUrl: 'https://www.cjsr.com/',
    submissionUrl: 'https://www.cjsr.com/submit-music/',
    sourceUrl: 'https://www.cjsr.com/submit-music/',
    sourceType: 'automation_run_319_public_research',
    country: 'Canada / Edmonton, Alberta independent community radio with worldwide online streaming',
    language: 'en',
    genres: [
      'community-radio',
      'campus-radio',
      'electronic',
      'techno',
      'house',
      'trance',
      'drum-and-bass',
      'jungle',
      'hip-hop',
      'world',
      'independent',
      'album-or-ep-only',
      'direct-email-submission',
      'physical-submission',
      'manual-review'
    ],
    submissionMethod: 'official-public-music-department-email-or-physical-submission',
    feeRequired: false,
    feeAmount: 'No music-submission fee is stated; a separate optional local-advertising offer is excluded from the submission route.',
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'CJSR accepts albums and EPs rather than individual singles. A human must approve the pitch, confirm a non-expiring downloadable delivery method, provide complete metadata, focus tracks, track lengths and language warnings, choose digital or physical delivery, and keep the separate paid local-advertising offer outside the music-submission workflow.',
    notes: 'Verified on 2026-07-13 from CJSR first-party Submit Music, homepage and schedule pages. CJSR publishes music@cjsr.com specifically for digital album or EP submissions and also provides an official physical Music Department route. The station asks for downloadable files rather than paid-streaming-only access; Bandcamp download codes, Dropbox and Google Drive are accepted, while expiring transfer links are discouraged. Required information includes artist origin, focus tracks, track lengths, language warnings and correctly tagged MP3 metadata. The plaintext address was confirmed as a purpose-specific, first-party, domain-matched business email. Current activity and MarcsMusic relevance were confirmed through the active schedule, including underground electronic, dance, trance, drum-and-bass and jungle programming. No email, download code, file, physical package or submission was prepared or sent, and no SMTP, MX, catch-all or mailbox-level probe was performed.'
  },
  {
    name: 'CFUV 101.9 FM Independent Music Library Submission',
    websiteUrl: 'https://cfuv.uvic.ca/',
    submissionUrl: 'https://cfuv.uvic.ca/music-submissions/',
    sourceUrl: 'https://cfuv.uvic.ca/music-submissions/',
    sourceType: 'automation_run_319_public_research',
    country: 'Canada / Victoria, British Columbia campus-community radio with worldwide online streaming',
    language: 'en',
    genres: [
      'campus-radio',
      'community-radio',
      'electronic',
      'ambient',
      'synthwave',
      'dub',
      'reggae',
      'house',
      'hip-hop',
      'world',
      'experimental',
      'freeform',
      'minimum-three-tracks',
      'direct-email-submission',
      'manual-review'
    ],
    submissionMethod: 'official-public-music-director-email-with-download-link',
    feeRequired: false,
    feeAmount: 'No music-submission fee is stated; third-party file hosting is sender-managed.',
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'CFUV requires at least three unique tracks and properly prepared downloadable 320 kbps MP3 files. A human must verify release eligibility, track listing, biography, file access, metadata, rights and the distinction between the global digital route and the local-only physical-delivery exception before sending the Music Director pitch.',
    notes: 'Verified on 2026-07-13 from CFUV first-party Music Submissions, homepage, shows and charts pages. CFUV publishes music@cfuv.ca for all digital music submissions. The station requires a minimum of three unique tracks, MP3 files at 320 kbps or better, a working digital download link, a one-page biography and a proper track listing; incomplete track-list information is not considered. Physical submissions are restricted to artists from Victoria, Sooke, Duncan or the Gulf Islands, so MarcsMusic is queued only for the authorized digital route. The plaintext address was confirmed as a purpose-specific, first-party, domain-matched business email. Current activity and genre fit were confirmed through active programming covering electronica, ambient, synthwave, experimental music, dub, reggae, house, hip-hop and global music. No email, file link, biography, track list or submission was prepared or sent, and no SMTP, MX, catch-all or mailbox-level probe was performed.'
  },
  {
    name: 'KXCI 91.3 FM Digital Album and Physical Music Submission',
    websiteUrl: 'https://kxci.org/',
    submissionUrl: 'https://kxci.org/about/music-department/',
    sourceUrl: 'https://kxci.org/about/music-department/',
    sourceType: 'automation_run_319_public_research',
    country: 'United States / Tucson, Arizona community radio accepting music from worldwide artists',
    language: 'en',
    genres: [
      'community-radio',
      'freeform',
      'electronic',
      'downtempo',
      'world',
      'reggae',
      'independent',
      'digital-album-download',
      'physical-submission',
      'protected-email-route',
      'manual-review'
    ],
    submissionMethod: 'official-protected-music-department-email-or-physical-submission',
    feeRequired: false,
    feeAmount: 'No music-submission fee is stated; physical-media production and postage are sender costs.',
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'KXCI accepts digital albums by MP3 or WAV download link and physical CDs or vinyl, but the Music Department address is protected in passive extraction. A human must use the address displayed on the official page without decoding or guessing it programmatically, confirm album assets and explicit-language disclosures, approve the pitch and decide whether digital delivery alone or optional physical copies are appropriate.',
    notes: 'Verified on 2026-07-13 from KXCI first-party Music Department and homepage pages. KXCI accepts music from around the world and publishes a protected first-party Music Department email route for MP3 or WAV album-download links, plus official physical-delivery instructions for national and international CDs or vinyl. Required information includes artist name, album title, artwork, timed track list, label or self-release status, release date, genre and comparable artists, explicit-language details, a brief biography, social links and contact information. The protected address was not decoded, guessed or stored as plaintext. KXCI states that all submissions are reviewed for genre, quality and explicit content and prioritizes local and regional artists without excluding international submissions. Current activity was confirmed through its live playlist, two-week archive, July 2026 posts and active Electric Feel programming; the site also highlighted electronic crossover act Thievery Corporation in May 2026. No email, download link, artwork, album, CD, vinyl or submission was supplied, and no protected contact or anti-bot control was accessed.'
  }
];
