import type { PlatformInput } from '../models/types.js';

export const run332SeedPlatforms: PlatformInput[] = [
  {
    name: 'FUXWITHIT Premiere Feature and Interview Editorial Email Route',
    websiteUrl: 'https://fuxwithit.com/',
    submissionUrl: 'mailto:fuxwithitdotcom@gmail.com',
    sourceUrl: 'https://fuxwithit.com/contact/',
    sourceType: 'automation_run_332_public_research',
    country: 'Canada / global bass, trap, wave, dubstep and genre-blurring electronic publication and label',
    language: 'en',
    genres: [
      'fuxwithit',
      'electronic',
      'bass-music',
      'trap',
      'dubstep',
      'wave',
      'future-bass',
      'hip-hop-electronic',
      'global-electronic',
      'editorial-premiere',
      'feature-request',
      'interview-request',
      'direct-public-email',
      'manual-review'
    ],
    submissionMethod: 'official-public-purpose-specific-editorial-email-for-premieres-features-and-interviews',
    feeRequired: false,
    feeAmount: 'No editorial submission fee, account, login or mandatory payment is stated on the official contact page. Advertising inquiries share the same contact but are a separate commercial purpose.',
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'FUXWITHIT publicly invites premiere opportunities, feature requests and interview requests through fuxwithitdotcom@gmail.com, but it does not publish a complete music-delivery specification, response policy, release-window rule, file/link format, rights declaration or AI-content policy. A human must choose a strongly relevant MarcsMusic release and editorial angle, verify release and premiere availability, prepare an authorized private stream or non-expiring link and concise press context, approve all metadata and personal data, and send the email manually. Advertising must not be treated as an editorial shortcut.',
    notes: 'Verified on 2026-07-13 from FUXWITHIT official homepage and contact page. The homepage was active with FUXWITHITFRIDAYS editions dated 2026-07-10, 2026-07-03 and 2026-06-26, and current features covering bass, wave, dubstep, hip-hop/electronic hybrids and artists from multiple countries. The official contact page publishes fuxwithitdotcom@gmail.com specifically for premiere opportunities, feature requests, interview requests and advertising inquiries. The address has valid syntax and an explicitly published editorial purpose, although it uses Gmail rather than the publication domain. No address was inferred or guessed, and no SMTP, MX, catch-all, mailbox-level or deliverability probe was performed. No email, track, private stream, press release, artwork, biography, metadata or personal data was prepared or sent.'
  },
  {
    name: 'Run The Trap First-Party SoundCloud Music Submission Form Route',
    websiteUrl: 'https://runthetrap.com/',
    submissionUrl: 'https://runthetrap.com/contact-us/',
    sourceUrl: 'https://runthetrap.com/contact-us/',
    sourceType: 'automation_run_332_public_research',
    country: 'United States / global trap, bass, dubstep, house, future-bass, hip-hop and electronic publication',
    language: 'en',
    genres: [
      'run-the-trap',
      'trap',
      'bass-music',
      'dubstep',
      'future-bass',
      'house',
      'hip-hop',
      'uk-garage',
      'drum-and-bass',
      'reggae-dub',
      'melodic-bass',
      'editorial-submission',
      'first-party-contact-form',
      'soundcloud-stream',
      'manual-review'
    ],
    submissionMethod: 'official-first-party-contact-us-and-submit-music-form-with-private-or-live-soundcloud-stream',
    feeRequired: false,
    feeAmount: 'No submission fee, account, login or mandatory payment is stated on the official music-submission page.',
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Run The Trap accepts new music through its first-party Contact Us + Submit Music form and requires a private or live SoundCloud stream; MP3 attachments and social-media submissions are rejected. A human must inspect the live form for any runtime antispam or consent controls, choose a fitting track, write the requested descriptive subject and concise message, verify SoundCloud access and rights, confirm whether the release or mix is eligible, approve all personal data and submit manually. Mixes are accepted only from established artists and must be exclusive to the publication.',
    notes: 'Verified on 2026-07-13 from Run The Trap official homepage and Contact Us + Submit Music page. The homepage displayed current articles dated through 2026-06-27 and recent coverage spanning bass, trap, reggae/dub, drum-and-bass, UK garage, dubstep, melodic bass, house and hip-hop/electronic hybrids. The submission page explicitly invites new music, asks for a short description in the subject, accepts only private or live SoundCloud streams, rejects MP3 attachments and social-media submissions, and displays first-party fields for name, email, subject and message. It states that replies are not guaranteed and that no reply within three days generally means the material is not selected. No public purpose-specific submission email was displayed or guessed. No form, SoundCloud link, track, attachment, message, account, login, CAPTCHA, payment or runtime protection was used or bypassed.'
  }
];
