import type { PlatformInput } from '../models/types.js';

export const run320SeedPlatforms: PlatformInput[] = [
  {
    name: 'RTRFM 92.1 Global Digital Music Submission',
    websiteUrl: 'https://rtrfm.com.au/',
    submissionUrl: 'https://rtrfm.com.au/submit-your-music/',
    sourceUrl: 'https://rtrfm.com.au/submit-your-music/',
    sourceType: 'automation_run_320_public_research',
    country: 'Australia / Perth, Western Australia community radio with an official overseas submission option and worldwide streaming',
    language: 'en',
    genres: [
      'community-radio',
      'electronic',
      'ambient',
      'experimental',
      'dance',
      'hip-hop',
      'world',
      'independent',
      'first-party-submission-form',
      'protected-email-route',
      'honeypot-present',
      'optional-physical-submission',
      'manual-review'
    ],
    submissionMethod: 'official-first-party-upload-form-or-protected-music-team-email',
    feeRequired: false,
    feeAmount: 'No music-submission fee is stated; optional physical copies and postage are sender costs.',
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'RTRFM exposes an official form with a validation honeypot, personal-data fields, a biography upload and free stream/download-link requirements. A human must leave the anti-spam field untouched, approve the bio and links, confirm file access and rights, decide whether to use the form or the protected first-party email route, and keep optional physical delivery separate.',
    notes: 'Verified on 2026-07-13 from RTRFM first-party Submit Your Music and homepage pages. The form accepts overseas submissions and requests first name, surname, email, optional phone, city, state or Overseas, artist name, a PDF/DOC/DOCX biography upload, social links, upcoming gigs, a stream link and a free music-download link. RTRFM recommends downloadable WAV or high-quality MP3 files through services such as Google Drive, Dropbox, SoundCloud or Bandcamp and says not to attach audio to email. The page also publishes protected first-party Music Team and Music Director email links, but the addresses were masked in passive extraction and were not decoded or guessed. The form contains a Comments field explicitly marked as a validation field that must remain unchanged, so no automated form interaction is allowed. Optional physical CDs require a matching free digital submission. Current activity was confirmed through live programming, electronic and ambient shows, weekly featured music, current events and stories dated through 10 July 2026. No form, email, file, link, biography or physical package was prepared or sent.'
  },
  {
    name: 'FBi Radio Digital Music Submission',
    websiteUrl: 'https://www.fbi.radio/',
    submissionUrl: 'https://www.fbi.radio/pages/music-submissions',
    sourceUrl: 'https://www.fbi.radio/pages/music-submissions',
    sourceType: 'automation_run_320_public_research',
    country: 'Australia / Sydney, New South Wales independent community radio with a strong Sydney and Australian music mandate',
    language: 'en',
    genres: [
      'community-radio',
      'electronic',
      'experimental',
      'dance',
      'bass',
      'hip-hop',
      'world',
      'independent',
      'direct-email-submission',
      'digital-only',
      'manual-review'
    ],
    submissionMethod: 'official-public-music-submissions-email',
    feeRequired: false,
    feeAmount: 'No editorial music-submission fee is stated; separate optional promotional campaigns are excluded from the submission route.',
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'FBi Radio requires a human-written email pitch, a stream link and a free high-quality download link, with timing around its Wednesday audition process. A human must approve the subject line, biography, press image, release context, non-expiring file access and suitability for a general or specialist program while recognizing the station’s Sydney and Australian programming priority.',
    notes: 'Verified on 2026-07-13 from FBi Radio first-party Music Submissions, Contact and homepage pages. FBi publishes music@fbiradio.com specifically for music submissions. Required email content includes a clear artist and track or release subject, a short biography, press image and/or gig details, a stream link and a free high-quality 320 kbps MP3 or WAV download through a service such as Dropbox, Google Drive or non-expiring WeTransfer; SoundCloud downloads must be enabled. General playlist servicing is auditioned on Wednesdays, and specialist shows may be contacted through presenter addresses on their official program pages. FBi no longer accepts CD submissions. The address was confirmed as plaintext and purpose-specific on the official station site; its legacy fbiradio.com domain is organization-published even though the current website uses fbi.radio. Current activity was confirmed through live scheduling, episodes dated through 12 July 2026 and music articles dated through 10 July 2026, including electronic, bass-heavy and independent coverage. No email, stream, download link, image or submission was prepared or sent, and no SMTP, MX, catch-all or mailbox-level probe was performed.'
  },
  {
    name: 'PBS 106.7FM International Digital Music Submission',
    websiteUrl: 'https://www.pbsfm.org.au/',
    submissionUrl: 'https://www.pbsfm.org.au/submitmusic',
    sourceUrl: 'https://www.pbsfm.org.au/submitmusic',
    sourceType: 'automation_run_320_public_research',
    country: 'Australia / Melbourne, Victoria community radio explicitly accepting local and international acts',
    language: 'en',
    genres: [
      'community-radio',
      'electronic',
      'house',
      'bass',
      'hip-hop',
      'ambient',
      'experimental',
      'dub',
      'reggae',
      'global',
      'independent',
      'first-party-submission-form',
      'captcha-present',
      'honeypot-present',
      'optional-physical-submission',
      'manual-review'
    ],
    submissionMethod: 'official-first-party-music-submission-form-or-physical-delivery',
    feeRequired: false,
    feeAmount: 'No music-submission fee is stated; optional CDs, vinyl and postage are sender costs.',
    loginRequired: false,
    captchaDetected: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'PBS explicitly presents a human-verification CAPTCHA and an anti-spam field that must remain blank. A human must complete the form, approve personal details, biography, social and gig information, verify the stream and 320 kbps-or-better download link, decline or accept the optional newsletter separately, and decide whether optional physical copies are appropriate.',
    notes: 'Verified on 2026-07-13 from PBS first-party Submit Your Music, Contact, Program List and homepage pages. PBS explicitly invites music from local and international acts and prefers its digital form. The form requests email, first name, surname, optional phone, location, country, city or suburb, state, artist name, biography, social links, upcoming gigs, a stream link and a required high-quality download link. Streams may use SoundCloud, YouTube or Bandcamp, while Spotify and Deezer links are not accepted; downloads should be 320 kbps AAC, MP3, WAV or equivalent. The page contains both a Leave this field blank honeypot and a CAPTCHA described as human-visitor testing, so it is queued only for manual completion. A separate optional PBS eNews consent must not be preselected. PBS also accepts CDs or vinyl and recommends four to five copies plus a one-page press release or biography. The program list confirms extensive electronic, house, bass, hip-hop, ambient, dub, reggae, experimental and global programming. Current activity was confirmed through a feature album dated 13-19 July 2026, current events and scheduled interviews. No form, CAPTCHA, consent, file, link or physical package was handled or submitted.'
  }
];
