import type { PlatformInput } from '../models/types.js';

export const run314SeedPlatforms: PlatformInput[] = [
  {
    name: 'WFMU Physical Music Review Submission',
    websiteUrl: 'https://wfmu.org/',
    submissionUrl: 'https://wfmu.org/sendmusic.html',
    sourceUrl: 'https://wfmu.org/sendmusic.html',
    sourceType: 'automation_run_314_public_research',
    country: 'United States / Jersey City, New Jersey freeform radio with worldwide online distribution',
    language: 'en',
    genres: [
      'all-genres',
      'freeform',
      'experimental',
      'electronic',
      'world',
      'independent',
      'college-radio',
      'physical-submission',
      'manual-review'
    ],
    submissionMethod: 'official-physical-mail-review-submission',
    feeRequired: false,
    feeAmount: 'No submission fee is stated; physical media, packaging, courier service and postage are sender-funded.',
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'A human must select the appropriate MarcsMusic release and physical format, confirm international-shipping feasibility and music rights, choose the postal or UPS/FedEx address correctly, approve packaging and postage, and verify any current return or retention expectations. No package may be prepared or shipped automatically.',
    notes: 'Verified on 2026-07-12 from WFMU first-party Send Music and homepage pages. WFMU explicitly accepts vinyl, CD, CD-R and cassette materials for review and publishes separate postal and UPS/FedEx addresses for Music Director Jessica Romoff in Jersey City. No geographic eligibility restriction is stated. Current activity was confirmed through live streams, archives and playlists dated 2026-07-12. No public digital music-submission form or purpose-specific submission email was inferred from this route. No package, physical media, payment or shipment was prepared or sent.'
  },
  {
    name: 'KXLU FCC-Clean Physical Music Submission',
    websiteUrl: 'https://kxlu.com/',
    submissionUrl: 'https://kxlu.com/contact/',
    sourceUrl: 'https://kxlu.com/contact/',
    sourceType: 'automation_run_314_public_research',
    country: 'United States / Los Angeles college radio with an online livestream',
    language: 'en',
    genres: [
      'eclectic',
      'alternative',
      'electronic',
      'punk',
      'folk',
      'vinyl',
      'college-radio',
      'physical-submission',
      'manual-review'
    ],
    submissionMethod: 'official-routed-fcc-clean-physical-mail-submission',
    feeRequired: false,
    feeAmount: 'No submission fee is stated; physical media, packaging and postage are sender-funded.',
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'KXLU requires FCC-clean submissions and publishes separate physical routes for General Submissions, Demolisten and Punk/Folk/Vinyl. A human must choose the correct route, confirm a clean version and genre fit, approve physical media and postage, and re-check the current addressee. The public Music Director email is not labelled as a digital submission route and must not be used as a substitute without explicit human confirmation.',
    notes: 'Verified on 2026-07-12 from KXLU first-party Contact and homepage pages. The official page directs General Submissions to Attn: Music Director, Demolisten submissions to Attn: Demolisten and Punk/Folk/Vinyl submissions to Attn: A Fistful of Vinyl at One LMU Drive, Los Angeles, CA 90045. It states that submissions must be FCC clean. Carmela Michaeli and carmelakxlu@gmail.com are publicly listed as the current Music Director contact, but the page does not authorize that address as a digital music-submission route, so it was recorded only as an observed business contact. Current activity was confirmed through the live stream, current playlist and 2026 posts. No email or physical package was sent.'
  },
  {
    name: 'SomaFM Channel-Routed Digital Music Submission',
    websiteUrl: 'https://somafm.com/',
    submissionUrl: 'https://somafm.com/contact/submitmusic.html',
    sourceUrl: 'https://somafm.com/contact/submitmusic.html',
    sourceType: 'automation_run_314_public_research',
    country: 'United States / San Francisco internet radio broadcasting worldwide',
    language: 'en',
    genres: [
      'electronic',
      'ambient',
      'downtempo',
      'dubstep',
      'reggae',
      'soul',
      'indie',
      'folk',
      'metal',
      'jazz',
      'world',
      'internet-radio',
      'public-business-email',
      'manual-review'
    ],
    submissionMethod: 'official-channel-specific-public-email-with-bandcamp-yum-or-approved-download-link',
    feeRequired: false,
    feeAmount: 'No submission fee is stated. Optional third-party delivery services may have their own account or plan terms.',
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'A human must verify that the selected MarcsMusic track is not AI-generated, choose exactly one currently accepting SomaFM channel and its published recipient, prepare a Bandcamp link with YUM code or an approved WeTransfer/Dropbox download link, validate 256 kbps or V0 44.1 kHz MP3 metadata, and avoid disallowed hosts, formats and duplicate multi-recipient pitches. Any third-party asset-hosting account or session must remain manual.',
    notes: 'Verified on 2026-07-12 from SomaFM first-party Submit Music, Contact and homepage pages. SomaFM supports commercial, independent, emerging and unsigned artists but explicitly rejects AI-generated music. It accepts digital submissions only: preferably a Bandcamp link plus YUM download code, otherwise a WeTransfer or Dropbox shared link. Files must be high-bitrate 256 kbps or V0 44.1 kHz MP3 with accurate metadata; WAV, AIFF, FLAC, 128 kbps MP3, Haulix, Facebook, SoundCloud, YouTube and Mixcloud deliveries are excluded. Currently accepting channel routes include promosubmissions@somafm.com for multiple electronic and specialist channels, dion@somafm.com for 7-inch Soul and Heavyweight Reggae, shawn@somafm.com for Beat Blender and other channel-specific addresses published on the official page. SomaFM says sending the same release to multiple music directors will cause it to be ignored. The station currently operates more than 30 hand-curated channels broadcasting worldwide. Public addresses were verified as purpose-specific and first-party published; no SMTP, MX, catch-all or mailbox-level probe was performed. No email, music link, file or account session was used.'
  }
];
