import type { PlatformInput } from '../models/types.js';

export const run308SeedPlatforms: PlatformInput[] = [
  {
    name: 'Armada Music Official Demo Drop Navigation Route',
    websiteUrl: 'https://www.armadamusic.com/',
    submissionUrl: 'https://www.armadamusic.com/',
    sourceUrl: 'https://www.armadamusic.com/',
    sourceType: 'automation_run_308_public_research',
    country: 'Netherlands / global electronic dance music label group',
    language: 'en',
    genres: ['electronic', 'edm', 'house', 'trance', 'progressive-house', 'tech-house', 'techno', 'dance', 'label-demo', 'dynamic-form', 'manual-review'],
    submissionMethod: 'official-homepage-demo-drop-navigation-to-label-demo-workflow',
    feeRequired: false,
    feeAmount: 'No demo-submission fee is stated in the public homepage navigation. Any current account, pricing, credit or payment prompt must be confirmed in the live Demo Drop workflow before use.',
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Armada Music publishes a dedicated Demo drop entry in its official homepage navigation, but the destination fields, account state, asset requirements, rights declarations and runtime protections were not exposed in the passively retrieved page. A human must open the official navigation route, inspect the live workflow, select a suitable MarcsMusic track and approve every field, consent and possible commercial option.',
    notes: 'Verified on 2026-07-12 from the official Armada Music homepage. The site displayed current 2026 catalog activity, including a PAROOKAVILLE Anthem 2026 release, and linked Demo drop as a first-party navigation item. No public music-submission mailbox was identified on the reviewed page. The first-party homepage is stored as the route rather than guessing an unexposed form URL. No navigation click, account, login, cookie choice, form, file, track, metadata, rights acceptance, checkout or payment was used.'
  },
  {
    name: 'Black Hole Recordings Official On-Page Demo Submission Workflow',
    websiteUrl: 'https://www.blackholerecordings.com/',
    submissionUrl: 'https://www.blackholerecordings.com/about-us',
    sourceUrl: 'https://www.blackholerecordings.com/about-us',
    sourceType: 'automation_run_308_public_research',
    country: 'Netherlands / global electronic and trance label',
    language: 'en',
    genres: ['electronic', 'trance', 'progressive-house', 'melodic-techno', 'dance', 'label-demo', 'private-streaming-link', 'dynamic-form', 'manual-review'],
    submissionMethod: 'official-about-page-on-page-demo-channel-workflow',
    feeRequired: false,
    feeAmount: 'No submission fee or payment requirement is stated in the public demo instructions. Any live account or commercial prompt must be reviewed before submission.',
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Black Hole Recordings authorizes demos through the official channels embedded on its About page and recommends a private streaming link, short artist biography and relevant links. The complete live form controls, rights declarations, privacy choices and runtime protections are not fully represented in the static page extraction. A human must inspect the live workflow, verify genre fit and rights, approve the private link and supporting information, and submit only through the stated demo channel.',
    notes: 'Verified on 2026-07-12 from the official Black Hole Recordings About page. The page explicitly says Demo / Submit your demo today and its FAQ directs artists to the official demo channels on that page, recommends a private streaming link such as SoundCloud, a short bio and relevant links, and says A&R will contact suitable artists after review that may take several weeks. The page describes electronic, trance, progressive house and melodic techno and lists current 2026 events. A cookie banner was visible. No public music-submission email was identified and no cookie choice, form, private link, file, metadata, rights declaration or submission was used.'
  },
  {
    name: 'Enhanced Music Official Demmo Demo Upload Portal',
    websiteUrl: 'https://www.enhancedmusic.com/',
    submissionUrl: 'https://labels.demmo.link/enhanced-music/demos',
    sourceUrl: 'https://www.enhancedmusic.com/',
    sourceType: 'automation_run_308_public_research',
    country: 'United Kingdom / global electronic dance label group',
    language: 'en',
    genres: ['electronic', 'dance', 'edm', 'progressive-house', 'trance', 'melodic-house', 'label-demo', 'external-upload-portal', 'dynamic-form', 'manual-review'],
    submissionMethod: 'official-homepage-link-to-external-enhanced-demmo-demo-portal',
    feeRequired: false,
    feeAmount: 'Enhanced Music does not state a demo fee on its public homepage. Any current account, pricing, credit or payment requirement must be confirmed inside the external Demmo portal.',
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Enhanced Music explicitly directs demos to its external Demmo portal. The portal could not be passively retrieved, so its current login state, file limits, metadata, rights declarations, privacy terms, CAPTCHA and pricing cannot be assumed. A human must open the authorized portal, inspect every live requirement, choose a suitable track and approve the final upload. The public info and shop addresses are business contacts, not substitute demo routes.',
    notes: 'Verified on 2026-07-12 from the official Enhanced Music homepage, which labels Demos and links Upload Your Demos Here to the Enhanced-specific Demmo portal. The homepage was active with news dated 2026-07-03 and an event dated 2026-05-15. It publicly lists info@enhancedmusic.com and shop@enhancedmusic.com; both were validated as official business contacts but not classified as music-submission mailboxes because the site directs demos to the portal. An adjacent newsletter honeypot was observed and excluded from the demo workflow. The external portal returned a passive retrieval cache miss; no retry intended to bypass it, account, login, form, file, track, metadata, cookie, CAPTCHA, honeypot, checkout or payment was used.'
  },
];
