import type { PlatformInput } from '../models/types.js';

export const run44SeedPlatforms: PlatformInput[] = [
  {
    name: 'Groover Music Promotion Platform',
    websiteUrl: 'https://groover.co/en/',
    submissionUrl: 'https://groover.co/en/',
    sourceUrl: 'https://groover.co/en/',
    sourceType: 'automation_run_44_public_research',
    country: 'France / United States / global music promotion marketplace',
    language: 'en',
    genres: ['global', 'independent', 'electronic', 'reggae', 'dub', 'world', 'jazz', 'hip-hop', 'r-and-b', 'soul', 'rock', 'pop', 'playlisting', 'radio-pitching', 'press', 'label-pitching'],
    submissionMethod: 'official-public-paid-campaign-route-to-curators-radio-playlists-press-and-labels',
    feeRequired: true,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: 'Official Groover campaign flow requires signup, track/link upload or demo addition, paid Grooviz credits, curator targeting, rights checks and editorial-fit review before any use.',
    notes: 'Official source advertises sending music to 3,000+ curators/pros including playlists, radios, blogs, labels and other music professionals. Paid Grooviz route observed; no account, payment, upload or submission was attempted.'
  },
  {
    name: 'Musosoup Music Promotion Platform',
    websiteUrl: 'https://musosoup.com/',
    submissionUrl: 'https://app.musosoup.com/submissions/new',
    sourceUrl: 'https://musosoup.com/',
    sourceType: 'automation_run_44_public_research',
    country: 'United Kingdom / global curator marketplace',
    language: 'en',
    genres: ['global', 'independent', 'electronic', 'reggae', 'dub', 'world', 'hip-hop', 'r-and-b', 'soul', 'indie', 'alternative', 'playlisting', 'blogs', 'radio-promo', 'press'],
    submissionMethod: 'official-public-freemium-campaign-route-with-curator-offers',
    feeRequired: true,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: 'Official Musosoup flow allows a free initial music upload/link but successful submissions require account creation and campaign-fee activation, so human review is required for campaign fit, rights, paid/free curator offers and metadata before any use.',
    notes: 'Official source says artists can submit a single, EP or album for free by link or MP3, then submissions are reviewed and successful campaigns require account creation and payment. No account, payment, upload or submission was attempted.'
  },
  {
    name: 'DailyPlaylists Submit a Song',
    websiteUrl: 'https://dailyplaylists.com/',
    submissionUrl: 'https://dailyplaylists.com/',
    sourceUrl: 'https://dailyplaylists.com/',
    sourceType: 'automation_run_44_public_research',
    country: 'Global Spotify playlist pitching platform',
    language: 'en',
    genres: ['global', 'spotify', 'playlisting', 'independent', 'electronic', 'reggae', 'dub', 'world', 'hip-hop', 'pop', 'indie', 'r-and-b', 'soul'],
    submissionMethod: 'official-public-freemium-spotify-playlist-submission-marketplace',
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official marketplace requires sign-in/track lookup and has standard free submissions plus premium/pro tiers, so human review is required for account flow, song-link selection, curator targeting, usage limits and optional paid credits before any use.',
    notes: 'Official source states artists can submit music for free to an 18,000+ playlist marketplace and lists a public business email. Premium credits and professional tiers were observed as optional paths. No login, email, payment or submission action was attempted.'
  },
  {
    name: 'Playlist Push Music Promotion',
    websiteUrl: 'https://playlistpush.com/',
    submissionUrl: 'https://app.playlistpush.com/',
    sourceUrl: 'https://playlistpush.com/',
    sourceType: 'automation_run_44_public_research',
    country: 'United States / global Spotify and TikTok promotion platform',
    language: 'en',
    genres: ['global', 'spotify', 'tiktok', 'playlisting', 'independent', 'electronic', 'reggae', 'dub', 'world', 'hip-hop', 'pop', 'creator-campaigns'],
    submissionMethod: 'official-public-paid-spotify-playlist-and-tiktok-campaign-route',
    feeRequired: true,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: 'Official Playlist Push artist flow requires account/campaign setup, paid budget selection, song targeting, rights checks, dashboard review and curator or creator campaign approval before any use.',
    notes: 'Official source advertises Spotify playlist and TikTok promotion services, curated campaign dashboards and paid campaign pricing. No account, payment, upload, creator brief or submission was attempted.'
  },
  {
    name: 'Indiemono Free Submit Music',
    websiteUrl: 'https://indiemono.com/',
    submissionUrl: 'https://indiemono.com/submit-music-chill-playlists/',
    sourceUrl: 'https://indiemono.com/submit-music-chill-playlists/',
    sourceType: 'automation_run_44_public_research',
    country: 'Spain / global Spotify playlist submission route',
    language: 'en',
    genres: ['global', 'spotify', 'playlisting', 'chill', 'edm', 'electronic', 'indie', 'alternative', 'urban', 'rap', 'trap', 'r-and-b', 'folk', 'latin', 'sadlove', 'happy'],
    submissionMethod: 'official-public-free-spotify-track-url-submission-form',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official public form requires manual review for Spotify track URL validity, genre/service/territory selection, consent/privacy terms, newsletter permission, playlist-fit review and no-email-submission policy before any use.',
    notes: 'Official source says the submission system is free, requires a valid Spotify track URL and asks artists not to use email or Facebook submissions. Form fields were identified but no form submission was attempted.'
  }
];
