import type { PlatformInput } from '../models/types.js';

export const run489SeedPlatforms: PlatformInput[] = [
  {
    "name": "SoundChat Radio Global Caribbean Music Submission",
    "websiteUrl": "https://soundchatradio.com/",
    "submissionUrl": "https://soundchatradio.com/submit-music",
    "sourceUrl": "https://soundchatradio.com/submit-music",
    "sourceType": "automation_run_489_public_research",
    "country": "United States / Jamaica-linked global Caribbean radio platform; the official submission page promotes worldwide reach, while country-by-country submitter eligibility still requires review.",
    "language": "en",
    "genres": [
      "reggae",
      "dancehall",
      "soca",
      "Caribbean",
      "Afro-Caribbean",
      "R&B",
      "hip-hop",
      "clean radio edit",
      "streaming link",
      "manual-review"
    ],
    "submissionMethod": "official first-party free web form using a SoundCloud, Spotify, YouTube or direct-download track link plus artist metadata and a short bio",
    "feeRequired": false,
    "feeAmount": "Standard music submission is explicitly free; no mandatory submission fee is published for the canonical form.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "Caribbean and programme fit, clean-edit selection, track-link access, metadata and bio, rights and broadcast permission, AI eligibility, privacy/retention, hidden submit-time controls and the final form action require human review.",
    "notes": "Passively verified on 2026-07-18 from SoundChat Radio's official submission, music, home and contact pages. The first-party form accepts a SoundCloud, Spotify, YouTube or direct-download track link and asks for artist name, email, track title, genre and background information. The guidelines prefer MP3 320kbps or WAV source quality, request a radio edit alongside an explicit version where applicable, and require correct metadata, a short bio and social links. Submission confirms ownership and grants SoundChat permission to broadcast. Standard submission is explicitly free. info@SoundChatRadio.com and irishandchin@gmail.com are first-party published general contacts but were excluded as replacements for the official form. Activity is supported by a live 24/7 schedule and an official story dated March 16, 2026. First-party audience figures are stored only as unverified platform claims. No form field, track link, email or submission was sent."
  },
  {
    "name": "JAM Audio Live Worldwide Independent Music Submission",
    "websiteUrl": "https://jamaudio.live/",
    "submissionUrl": "https://jamaudio.live/artist-submissions",
    "sourceUrl": "https://jamaudio.live/artist-submissions",
    "sourceType": "automation_run_489_public_research",
    "country": "Worldwide / independent online-radio platform; the official site says artists from around the world are already in rotation and it broadcasts worldwide.",
    "language": "en",
    "genres": [
      "all genres",
      "electronic",
      "drum and bass",
      "hip-hop",
      "R&B",
      "rock",
      "metal",
      "pop",
      "indie",
      "experimental",
      "singer-songwriter",
      "external Google Form",
      "manual-review"
    ],
    "submissionMethod": "official first-party submission landing page leading to an external Google Form for link-based, human-reviewed consideration",
    "feeRequired": false,
    "feeAmount": "No mandatory fee is published for editorial submission; separate optional paid artist services are not part of the canonical route.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "The external Google Form's live fields, login/session state, CAPTCHA, consent and storage terms require manual inspection; genre fit, link access, explicit-content disclosure, rights, AI policy, privacy and the separate paid-services boundary also require human review.",
    "notes": "Passively verified on 2026-07-18 from JAM Audio Live's official artist-submission, home, about and artist-service pages. The landing page accepts independent artists from every genre and supports Spotify, Apple Music, SoundCloud, YouTube, Bandcamp, Dropbox, Google Drive or direct music links. It asks artists to include a short bio, origin and song story, mark explicit lyrics and ensure they have permission to submit. Every submission is described as human reviewed for possible live rotation, spotlights, charts, interviews and future broadcasts. The official call-to-action leads to a Google Form, but the form could not be passively loaded, so its fields, login, CAPTCHA, upload, consent and retention controls remain unknown. Optional paid services such as premium spotlights and audio services were recorded only as an adjacent pricing boundary. A protected contact address was not decoded. Activity is confirmed by a live 24/7 stream and June 2026 artist spotlights for artists from Croatia, Brazil and Glasgow. No form field, link, account, payment or submission was used."
  },
  {
    "name": "Discover YOU RADIO Free Rotation Evaluation",
    "websiteUrl": "https://discoveryouradio.com/",
    "submissionUrl": "https://discoveryouradio.com/artist-submissions",
    "sourceUrl": "https://discoveryouradio.com/artist-submissions",
    "sourceType": "automation_run_489_public_research",
    "country": "United States / independent online-radio and artist-promotion platform; universal international submission eligibility is not expressly guaranteed.",
    "language": "en",
    "genres": [
      "independent music",
      "all genres",
      "clean content",
      "radio-ready",
      "iTunes",
      "listener request catalog",
      "artist biography",
      "manual-review"
    ],
    "submissionMethod": "official first-party free rotation-evaluation form requiring a clean radio-ready track, iTunes or alternate music link, artist data, biography, lyrics and fit information",
    "feeRequired": false,
    "feeAmount": "The initial rotation evaluation is explicitly free; optional paid certificates, pitching and promotional services are separate and not required for canonical consideration.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "Clean radio-ready selection, iTunes or alternate-link access, lyrics and metadata, AI/Suno disclosure and label-interest choice, rights, mailing and paid-promotion opt-ins, optional paid-service separation, privacy/retention, hidden submit-time controls and final submission require human review.",
    "notes": "Passively verified on 2026-07-18 from Discover YOU RADIO's official artist-submission, artist-portal, real-radio, privacy and terms pages. The official page says initial rotation evaluation is free, only the official application is reviewed and general-contact or social-DM submissions can be disqualified. The visible form asks for artist/contact data, song title, iTunes or alternate link, biography, song inspiration, lyrics or instrumental status, one or two genres, optional ISRC, PRO, social and website links, purchase link, fit statement, Suno Pro/record-label interest and an explicit yes/no paid-promotional-opportunities choice. Tracks must be radio-ready and non-explicit. If selected, the station says it purchases the song on iTunes and adds it to rotation and its request catalog. submit@discoveryouradio.com and admin@discoveryouradio.com are first-party published in the privacy policy, but the official application remains canonical. The active Human Ear Queue, current request lineup, 2026 privacy policy and current 2026 briefing support activity. No form field, email, opt-in, purchase or submission was used."
  }
];
