import type { PlatformInput } from '../models/types.js';

export const run46SeedPlatforms: PlatformInput[] = [
  {
    name: 'WREK Atlanta Music Submissions',
    websiteUrl: 'https://www.wrek.org/',
    submissionUrl: 'https://www.wrek.org/music/',
    sourceUrl: 'https://www.wrek.org/music/',
    sourceType: 'automation_run_46_public_research',
    country: 'United States / Atlanta student-run freeform radio',
    language: 'en',
    genres: ['college-radio', 'freeform', 'independent', 'electronic', 'reggae', 'dub', 'world', 'hip-hop', 'experimental', 'specialty-shows', 'physical-submission', 'email-submission'],
    submissionMethod: 'official-public-email-and-physical-media-route-to-music-director',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official WREK route accepts music by email to the Music Director or by physical mail, but airplay is freeform/DJ-selected and requires human review for media format, physical packaging, metadata, station/show fit, clean-content notes and no-response expectations before any contact is made.',
    notes: 'Official WREK sources show active programming and specialty sound blocks including electronic, reggae/dub, international and other independent formats. The official submission page lists music.director@wrek.org and a station mailing address; no email, upload, form, phone call or physical shipment was attempted.'
  },
  {
    name: 'KFJC 89.7FM For Musicians',
    websiteUrl: 'https://kfjc.org/',
    submissionUrl: 'https://kfjc.org/for-musicians/',
    sourceUrl: 'https://kfjc.org/for-musicians/',
    sourceType: 'automation_run_46_public_research',
    country: 'United States / Los Altos Hills college and community radio',
    language: 'en',
    genres: ['college-radio', 'freeform', 'independent', 'experimental', 'electronic', 'world', 'reggae', 'dub', 'punk', 'jazz', 'underground', 'physical-submission'],
    submissionMethod: 'official-public-physical-media-only-route-to-music-director',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official KFJC route says the station can only accept physical media and cannot accommodate digital-only submissions yet; the related contact flow includes a no-robots control, so human review is required for physical packaging, Music Director routing, format fit, no-return policy and anti-bot-safe handling.',
    notes: 'Official KFJC pages show active 2026 station activity and a For Musicians route requiring CDs, vinyl or cassettes sent to the Music Director mailing address. No digital upload, contact form, no-robots control, phone call, email or physical mail action was attempted.'
  },
  {
    name: 'WMBR 88.1 FM MIT Your Music',
    websiteUrl: 'https://wmbr.org/',
    submissionUrl: 'https://wmbr.org/www/md',
    sourceUrl: 'https://wmbr.org/www/md',
    sourceType: 'automation_run_46_public_research',
    country: 'United States / Cambridge MIT campus radio',
    language: 'en',
    genres: ['college-radio', 'freeform', 'independent', 'experimental', 'electronic', 'techno', 'world', 'hip-hop', 'americana', 'folk', 'jazz', 'local', 'physical-submission'],
    submissionMethod: 'official-public-physical-cd-route-to-music-director',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official WMBR route is a freeform physical-media workflow; the page asks artists to send tangible physical music rather than MP3s, states DJs choose their own music, discourages mailing-list style updates and includes image-protected contact links that were not decoded, so packaging, one-sheet, show fit and protected-contact handling are manual.',
    notes: 'Official WMBR homepage shows 24/7 current programming and the Your Music page publishes the Music Director mailing address, confirms unsigned bands are accepted and asks for physical music plus an informational one-sheet. No protected email image was decoded and no email, request, form or physical shipment was attempted.'
  },
  {
    name: 'KSPC 88.7FM Music Submissions',
    websiteUrl: 'https://kspc.org/',
    submissionUrl: 'https://kspc.org/contact/music-submissions/',
    sourceUrl: 'https://kspc.org/contact/music-submissions/',
    sourceType: 'automation_run_46_public_research',
    country: 'United States / Claremont college and community radio',
    language: 'en',
    genres: ['college-radio', 'community-radio', 'independent', 'local', 'underrepresented', 'electronic', 'hip-hop', 'reggae', 'jazz', 'classical', 'americana', 'underground', 'album-submission', 'ep-submission'],
    submissionMethod: 'official-public-email-download-link-and-physical-album-ep-route',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official KSPC route accepts albums or EPs by mail or email/cloud-download link but rejects singles, demos, non-downloadable streaming links, iTunes/Spotify links, cassettes and substantially AI-generated work, so human review is required for eligibility, originality, file access, FCC-clean status and metadata.',
    notes: 'Official KSPC site shows recent 2026 activity and a dedicated Music Submissions page for all genres. The page explicitly states KSPC does not accept payment for airplay and that programmed music undergoes review before airplay. No email, upload, cloud link, form or physical shipment was attempted.'
  },
  {
    name: 'KXLU 88.9 FM Los Angeles Music Submissions',
    websiteUrl: 'https://kxlu.com/',
    submissionUrl: 'https://kxlu.com/contact/',
    sourceUrl: 'https://kxlu.com/contact/',
    sourceType: 'automation_run_46_public_research',
    country: 'United States / Los Angeles college and community radio',
    language: 'en',
    genres: ['college-radio', 'freeform', 'eclectic', 'independent', 'alternative', 'electronic', 'reggae', 'dub', 'latin', 'jazz', 'punk', 'folk', 'vinyl', 'demos', 'physical-submission'],
    submissionMethod: 'official-public-physical-mail-route-to-music-director-and-specialty-shows',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official KXLU contact page lists FCC-clean submission requirements and separate physical-mail routes for general Music Director, Demolisten and A Fistful of Vinyl submissions; human review is required for clean-radio status, routing choice, demo/vinyl fit, physical packaging, metadata and station-fit checks.',
    notes: 'Official KXLU homepage and contact page show active 2026 playlists/blog posts, current staff contacts and physical submission instructions. The public Music Director contact email is listed, but no email, contact action, form, upload, phone call or physical mail action was attempted.'
  }
];
