import type { PlatformInput } from '../models/types.js';

export const run482SeedPlatforms: PlatformInput[] = [
  {
    "name": "Resurge Audio Electronic Music Submission",
    "websiteUrl": "https://www.resurgeaudio.com/",
    "submissionUrl": "https://www.resurgeaudio.com/music-submission/",
    "sourceUrl": "https://www.resurgeaudio.com/music-submission/",
    "sourceType": "automation_run_482_public_research",
    "country": "Republic of Ireland / global-facing electronic music platform; the form requests artist location/country and the site describes a global electronic scene, but universal international eligibility is not stated as a separate rule.",
    "language": "en",
    "genres": [
      "electronic",
      "house",
      "tech house",
      "techno",
      "dance",
      "rave",
      "Spotify",
      "SoundCloud",
      "Disco",
      "Dropbox",
      "download-link",
      "form",
      "email",
      "manual-review"
    ],
    "submissionMethod": "official first-party electronic-music form with stream/download links and mandatory rights, submission and GDPR consent; official domain-aligned music mailbox is an alternative",
    "feeRequired": false,
    "feeAmount": "No mandatory submission fee or payment is published for the first-party form or music mailbox.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "International eligibility, exact house/tech-house/techno fit, hard AI prohibition, rights and Content ID, stream/download links, worldwide royalty-free promotional licence, GDPR consent, hidden form controls and final submission require human approval.",
    "notes": "Passively verified on 2026-07-18 from the official submission, terms, privacy, contact, homepage, playlist and 2026 editorial pages. The form rejects music generated in whole or part with AI and requires a non-exclusive worldwide royalty-free promotional licence plus rights and GDPR confirmations. music@resurgeaudio.com is first-party published, syntactically valid, domain-aligned and explicitly designated for submissions; the privacy page restricts email submissions to streamable links and rejects attachments or download-only email submissions. No SMTP, MX, catch-all, mailbox-level or deliverability probing was performed. No form field was filled, no consent was accepted, no link was shared and no email, payment or submission action occurred."
  },
  {
    "name": "Joshua Tree Live Global Audio Submission",
    "websiteUrl": "https://www.joshuatreelive.tv/",
    "submissionUrl": "https://www.joshuatreelive.tv/submit-media/",
    "sourceUrl": "https://www.joshuatreelive.tv/submit-media/",
    "sourceType": "automation_run_482_public_research",
    "country": "United States / Joshua Tree, California artist-first digital media and streaming platform; the official contact page states that creatives from all over the globe are welcome and the submission page seeks artists from every corner of the map.",
    "language": "en",
    "genres": [
      "independent",
      "electronic",
      "reggae",
      "world",
      "pop",
      "rock",
      "singer-songwriter",
      "audio show",
      "live interview",
      "MP3",
      "WAV",
      "MP4",
      "direct-upload",
      "manual-review"
    ],
    "submissionMethod": "official first-party JavaScript-dependent free media form with direct MP3/WAV/MP4 upload for audio-show, live-show or interview consideration",
    "feeRequired": false,
    "feeAmount": "The official route is described as free; no mandatory submission fee or payment is published.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "Track/show fit, direct upload and 500 MB limit, rights, broadcast/promotional scope, AI eligibility, privacy/retention, JavaScript controls, conflicting schedule details, contact-domain discrepancy and final submission require human approval.",
    "notes": "Passively verified on 2026-07-18 from the official submission, contact, terms, privacy, live-schedule, about and home pages. The route welcomes creatives globally, accepts MP3/WAV and MP4 up to 500 MB, and says artists retain ownership and revenue. The visible music page does not define a detailed broadcast/archival licence, while current schedule times differ from the submission-page description. media@joshuatreelive.tv is first-party published and domain-aligned for general media contact; a separate .io address on the About page was not treated as verified. No visible CAPTCHA appeared, but JavaScript-dependent submit-time controls remain unknown. No field was filled, no file was uploaded, no email was sent and no payment or submission action occurred."
  },
  {
    "name": "Global Entry Radio Groover Submission",
    "websiteUrl": "https://www.globalentryradio.com/",
    "submissionUrl": "https://groover.co/band/signup/referral/influencer/23557/",
    "sourceUrl": "https://www.globalentryradio.com/",
    "sourceType": "automation_run_482_public_research",
    "country": "International / monthly syndicated melodic electronic radio show broadcasting through more than 40 FM, DAB, TV and digital outlets in at least 15 countries; submissions are handled exclusively through Groover.",
    "language": "en",
    "genres": [
      "melodic house",
      "progressive house",
      "deep house",
      "melodic techno",
      "electronic",
      "international radio",
      "Groover",
      "paid-credits",
      "login",
      "manual-review"
    ],
    "submissionMethod": "official Global Entry Radio page links exclusively to its external Groover curator route for limited monthly melodic-electronic review and possible airplay",
    "feeRequired": true,
    "feeAmount": "Groover is a paid credit service. Groover currently documents €1 per Grooviz and normally 2 Grooviz per curator; the exact curator-specific price must be confirmed after login.",
    "loginRequired": true,
    "captchaDetected": false,
    "paymentRequired": true,
    "manualReviewRequired": true,
    "manualReviewReason": "Monthly capacity, melodic-electronic fit, exact curator identity, Groover login/account, current credit price and payment, track/campaign metadata, rights, AI policy, platform terms/privacy, hidden controls and final campaign require human approval.",
    "notes": "Passively verified on 2026-07-18 from the official Global Entry Radio page and official Groover help/terms pages. Global Entry Radio reviews a limited number of melodic-electronic submissions monthly through its exact Groover influencer route, and the show published episode 100 on 2026-07-03 while broadcasting through 40+ outlets in 15+ countries. Groover requires an account and paid Grooviz credits and guarantees review/feedback rather than airplay. The radio page exposes no direct submission email; its contact form is for syndication/partnerships. support@groover.co is platform support only. No login, CAPTCHA, account creation, payment or submission was attempted."
  }
];
