import type { PlatformInput } from '../models/types.js';

export const run497SeedPlatforms: PlatformInput[] = [
  {
    "name": "Dirty Disco Recordings All-Electronic Unreleased-Track Demo Form",
    "websiteUrl": "https://www.dirtydiscorecordings.com/",
    "submissionUrl": "https://www.dirtydiscorecordings.com/contact",
    "sourceUrl": "https://www.dirtydiscorecordings.com/contact",
    "sourceType": "automation_run_497_public_research",
    "country": "Australia / Melbourne independent electronic-dance label that states it develops talent from Australia and beyond; the submission page publishes no country restriction, but universal worldwide eligibility is not expressly guaranteed.",
    "language": "en",
    "genres": [
      "electronic dance music",
      "house",
      "tech house",
      "melodic techno",
      "big room",
      "underground electronic",
      "all electronic styles",
      "private streaming or download link",
      "first-party form",
      "manual-review"
    ],
    "submissionMethod": "official first-party demo form requesting first and last name, email, release message, track link, social profile and selection of Dirty Disco Main Label or Dirty Disco Imminent",
    "feeRequired": false,
    "feeAmount": "No mandatory submission, review or release fee is visible on the official demo route.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "Electronic-catalogue and imprint fit, unreleased/finished status, track-link access, ownership/control confirmation, master/composition/sample/contributor rights, Content ID, AI policy, privacy and retention, hidden or submit-time anti-spam controls, post-selection contract terms and the final form action require human review.",
    "notes": "Passively verified on 2026-07-19 from Dirty Disco Recordings' official contact/demo, home, about and catalogue pages plus current Beatport evidence. The canonical first-party form accepts all electronic styles and visibly requests first name, last name, email, a message explaining the release and label fit, a SoundCloud/Dropbox/WeTransfer-style link, a best social link and a choice between the main label and Dirty Disco Imminent. The page rejects unfinished or already-released music and requires the submitter to own or control the rights. No public business email was identified as an authorized alternative to the form. Activity is current: the official site shows active 2026 releases and Beatport lists POIZZONED - Techno Beat on April 10, 2026 and JAXX T - No Escape on March 27, 2026. No field, link, account, CAPTCHA, payment or submission was used."
  },
  {
    "name": "Play Records International Electronic / Dance LabelWorx Demo Form",
    "websiteUrl": "https://www.playrecords.net/",
    "submissionUrl": "https://www.playrecords.net/demos.php",
    "sourceUrl": "https://www.playrecords.net/demos.php",
    "sourceType": "automation_run_497_public_research",
    "country": "Canada / Toronto-based international electronic and dance label with a London studio operation and a multi-country artist catalogue.",
    "language": "en",
    "genres": [
      "house",
      "electronic dance music",
      "tech house",
      "big room",
      "nu disco",
      "techno",
      "progressive house",
      "phonk",
      "LabelWorx form",
      "manual-only submission",
      "manual-review"
    ],
    "submissionMethod": "official first-party demos page containing an externally hosted LabelWorx submission form; direct staff email and automated or third-party submission services are expressly rejected",
    "feeRequired": false,
    "feeAmount": "No mandatory submission, review or release fee is visible on the official demos page.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "Play Records expressly rejects automated and third-party demo services. A human must inspect and complete the LabelWorx form, confirm electronic/dance fit, 100-percent rights ownership, unreleased and completed status, remix/cover authorization, vocal-source disclosure, form fields, login/CAPTCHA state, privacy and data transfer, post-selection mastering and contract terms, and the final submission action.",
    "notes": "Passively verified on 2026-07-19 from Play Records' official demos, contact, privacy, music and about pages. The label accepts completed, unreleased electronic and dance music through the embedded LabelWorx form, rejects unauthorized remixes and covers, requires the submitter to guarantee 100% ownership, asks that uncredited vocal sources be disclosed and permits unmastered demos while requiring a mastered version if selected. The page explicitly says automated or third-party services are ignored, so this route is permanently manual-only. The privacy policy states that demo data is transferred directly to Play Records' LabelWorx account. melody@playrecords.net, simon@playrecords.net, sydney@playrecords.net and admin@playrecords.net are first-party published, syntactically valid and domain-aligned business contacts, but the official contact page forbids using staff email for demos. Activity is current: the official catalogue lists Angelo Maria Calderano - BOOM released July 17, 2026, Spirited scheduled July 24, 2026 and Summer Sessions 2026 Vol. 2 scheduled August 7, 2026. No form field, account, CAPTCHA, email, payment or submission was used."
  },
  {
    "name": "HEXAGON House / Bass House Trackstack Demo Inbox",
    "websiteUrl": "https://www.hexagonhq.com/",
    "submissionUrl": "https://www.hexagonhq.com/",
    "sourceUrl": "https://www.hexagonhq.com/",
    "sourceType": "automation_run_497_public_research",
    "country": "Netherlands / Amsterdam electronic label describing itself as a global movement; the public demo section does not expressly guarantee universal country eligibility.",
    "language": "en",
    "genres": [
      "house",
      "bass house",
      "club bangers",
      "future house",
      "electronic dance music",
      "Trackstack inbox",
      "external platform",
      "login/account boundary",
      "manual-review"
    ],
    "submissionMethod": "official first-party HEXAGON demo section embedding a Trackstack inbox for house, bass-house and club-banger submissions",
    "feeRequired": false,
    "feeAmount": "Trackstack states that artists can send tracks free to public inbox links; optional paid platform tiers exist but no mandatory HEXAGON review fee is published.",
    "loginRequired": true,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "The external Trackstack route is account-, terms- and platform-controlled and expressly prohibits automated use. A human must confirm the exact HEXAGON inbox, registration/login requirements, track upload and metadata, age eligibility, label fit, rights, Trackstack and receiver licences, privacy and retention, optional paid-tier separation, hidden verification, post-selection terms and the final send action.",
    "notes": "Passively verified on 2026-07-19 from HEXAGON's official homepage, about and events pages, current Beatport catalogue evidence and Trackstack's official help and terms. HEXAGON's first-party demo section states that demos are open, that Don Diablo opens every file, and that it seeks House, Bass House and Club Bangers through a Trackstack-powered inbox. Trackstack says tracks can be sent free to public inbox links, while its terms state that most functionality requires an account, users must be over 18, automated use is prohibited and artists grant limited platform and receiver review/promotional-performance licences. The exact embedded HEXAGON inbox fields, login flow and any CAPTCHA were not passively exposed. No public HEXAGON business email was identified as an authorized demo alternative; support@trackstack.app is provider support only. Activity is current: Beatport lists multiple HEXAGON releases through May 15, 2026, and the official site advertises a HEXAGON ADE label night on October 22, 2026. No account, track, form field, CAPTCHA, payment or submission was used."
  }
];