import type { PlatformInput } from '../models/types.js';

export const run43SeedPlatforms: PlatformInput[] = [
  {
    name: 'RTRFM 92.1 Perth Submit Your Music',
    websiteUrl: 'https://rtrfm.com.au/',
    submissionUrl: 'https://rtrfm.com.au/submit-your-music/',
    sourceUrl: 'https://rtrfm.com.au/submit-your-music/',
    sourceType: 'automation_run_43_public_research',
    country: 'Australia / Perth independent community radio',
    language: 'en',
    genres: ['perth', 'western-australia', 'independent', 'electronic', 'dub', 'reggae', 'hip-hop', 'jazz', 'world', 'community-radio', 'radio-airplay'],
    submissionMethod: 'official-public-submit-music-form-and-contact-route',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official form/contact route requires manual review for form behavior, downloadable WAV or high-quality MP3 link prep, no-attachment compliance, program fit, rights checks and runtime validation before any use.',
    notes: 'Official source says artists can use the form or contact route, asks for downloadable WAV/high-quality MP3 links and says not to attach files. Active 2026 site/programming observed. Protected contact links were not decoded and no submission action was attempted.'
  },
  {
    name: 'Edge Radio 99.3FM Hobart Submit Your Music',
    websiteUrl: 'https://www.edgeradio.org.au/',
    submissionUrl: 'https://www.edgeradio.org.au/submit-your-music/',
    sourceUrl: 'https://www.edgeradio.org.au/submit-your-music/',
    sourceType: 'automation_run_43_public_research',
    country: 'Australia / Hobart youth community radio',
    language: 'en',
    genres: ['tasmania', 'australian-music', 'independent', 'electronic', 'indie', 'alternative', 'youth-radio', 'community-radio', 'radio-airplay'],
    submissionMethod: 'official-public-digital-and-physical-music-submission-route',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official digital and physical submission rules require manual review for bio/gig info, stream link, high-quality download link, Tasmanian-submission labeling, rights checks and runtime validation before any use.',
    notes: 'Official source lists digital submission requirements and Music Department postal route for emerging artists in Tasmania, Australia and worldwide. 2026 activity observed. Protected contact links were not decoded and no submission action was attempted.'
  },
  {
    name: 'Three D Radio 93.7FM Adelaide Submit Your Music',
    websiteUrl: 'https://threedradio.com/',
    submissionUrl: 'https://threedradio.com/get-involved-page/submit-your-music/',
    sourceUrl: 'https://threedradio.com/get-involved-page/submit-your-music/',
    sourceType: 'automation_run_43_public_research',
    country: 'Australia / Adelaide progressive community radio',
    language: 'en',
    genres: ['south-australia', 'local-sa-music', 'progressive', 'alternative', 'electronic', 'folk', 'jazz', 'rock', 'community-radio', 'radio-airplay'],
    submissionMethod: 'official-public-digital-form-and-physical-library-route',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official route requires manual review because the digital form loads dynamically, only MP3 files are accepted, cloud/Bandcamp download requirements must be checked and direct-message delivery is explicitly disallowed.',
    notes: 'Official source prefers full albums/EPs, requires use of the form for digital music, rejects non-MP3 uploads and accepts physical CDs/vinyl by mail/drop-off. 2026 site/programming observed. No form, upload or physical action was attempted.'
  },
  {
    name: 'Radio Adelaide Submit Your Music',
    websiteUrl: 'https://www.radioadelaide.org.au/',
    submissionUrl: 'https://www.radioadelaide.org.au/submit-your-music/',
    sourceUrl: 'https://www.radioadelaide.org.au/submit-your-music/',
    sourceType: 'automation_run_43_public_research',
    country: 'Australia / Adelaide community radio',
    language: 'en',
    genres: ['adelaide', 'south-australia', 'australian-music', 'rock', 'hip-hop', 'electronic', 'jazz', 'folk', 'community-radio', 'radio-airplay'],
    submissionMethod: 'official-public-digital-transfer-guidelines-and-contact-route',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official route requires manual review for transfer-link permissions, WAV spec checks, filename/package prep, South Australian context, program targeting, rights checks and runtime validation before any use.',
    notes: 'Official source accepts independent Australian music via public transfer links, prefers WAV 44.1kHz stereo 16-bit and asks for bio, streams, Adelaide gig details and relevant program notes. April 2026 activity observed. Protected contact links were not decoded and no submission action was attempted.'
  },
  {
    name: '4ZZZ Brisbane Music Submissions',
    websiteUrl: 'https://4zzz.org.au/',
    submissionUrl: 'https://jeff.4zzz.org.au/form/submit-your-music-to-4zzz',
    sourceUrl: 'https://4zzz.org.au/music-submissions',
    sourceType: 'automation_run_43_public_research',
    country: 'Australia / Brisbane independent community radio',
    language: 'en',
    genres: ['brisbane', 'australian-music', 'independent', 'alternative', 'electronic', 'experimental', 'hip-hop', 'community-radio', 'radio-airplay'],
    submissionMethod: 'official-public-music-department-webform-with-downloadable-release-link-requirement',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official external form requires JavaScript and manual review for release metadata, release permissions, content/language warnings, downloadable WAV or 320kbps MP3 link/download code, cover art and social links.',
    notes: 'Official source says the Music Department considers submissions for the station library and rejects non-downloadable streams. External form fields were identified without completing or submitting them. June 2026 station activity observed.'
  }
];
