import type { PlatformInput } from '../models/types.js';

export const run48SeedPlatforms: PlatformInput[] = [
  {
    name: 'WMSE 91.7FM Milwaukee Music Department',
    websiteUrl: 'https://wmse.org/',
    submissionUrl: 'https://wmse.org/about-wmse-radio/music-department/',
    sourceUrl: 'https://wmse.org/about-wmse-radio/music-department/',
    sourceType: 'automation_run_48_public_research',
    country: 'United States / Milwaukee community radio',
    language: 'en',
    genres: ['community-radio', 'freeform-radio', 'independent', 'alternative', 'electronic', 'world', 'jazz', 'reggae', 'radio-airplay', 'physical-submission', 'digital-download'],
    submissionMethod: 'official-public-physical-mail-walk-in-and-digital-download-route-to-music-director',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official WMSE Music Department route accepts CDs, vinyl, cassette and digital downloads via WeTransfer/email, but every item must be reviewed for quality, content, FCC-clean tracks, metadata, format choice, Music Director routing and DJ/program fit before any contact, file link or physical package is used.',
    notes: 'Official WMSE page states new music submissions are encouraged, lists accepted formats and a Music Director route, and explains that volunteer program hosts decide what airs. No email was sent, no digital link was shared and no physical delivery or mailing was attempted.'
  },
  {
    name: 'KRUI 89.7FM Get Your Music Played',
    websiteUrl: 'https://krui.fm/',
    submissionUrl: 'https://krui.fm/about/music/',
    sourceUrl: 'https://krui.fm/about/music/',
    sourceType: 'automation_run_48_public_research',
    country: 'United States / Iowa City student radio',
    language: 'en',
    genres: ['student-radio', 'college-radio', 'independent', 'local', 'electronic', 'hip-hop', 'jazz', 'folk', 'radio-airplay', 'email-submission'],
    submissionMethod: 'official-public-music-director-email-route-with-tracklist-and-clean-content-notes',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official KRUI page asks artists to send music by email and notes tracklist and swearing/obscenity information; human review is required for track suitability, clean/explicit flags, remote/physical-media guidance, metadata, rights and no-response expectations.',
    notes: 'Official KRUI page shows recent 2026 activity and its Get your music played route with Music Director contact details. No email, file link or physical media was sent.'
  },
  {
    name: 'KXCI 91.3 Tucson Music Department Submissions',
    websiteUrl: 'https://kxci.org/',
    submissionUrl: 'https://kxci.org/about/music-department/',
    sourceUrl: 'https://kxci.org/about/music-department/',
    sourceType: 'automation_run_48_public_research',
    country: 'United States / Tucson community radio',
    language: 'en',
    genres: ['community-radio', 'independent', 'electronic', 'reggae', 'cumbia', 'latin', 'world', 'local-arizona', 'radio-airplay', 'email-submission', 'physical-submission'],
    submissionMethod: 'official-public-email-download-link-and-physical-route-to-music-department',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official KXCI Music Department route accepts music from around the world but prioritizes Tucson and Arizona artists; all music is reviewed by volunteers and staff, and human review is required for metadata, explicit-language notes, bio/social/contact details, MP3/WAV download links or physical copies, local-priority context and protected/redacted contact handling.',
    notes: 'Official KXCI page describes active music submission guidelines and physical/digital routes. The web extract rendered the email address as protected/redacted, so no protected contact was decoded, no email was sent and no physical copy was mailed.'
  },
  {
    name: 'WXDU 88.7FM Duke Radio Music Submissions',
    websiteUrl: 'https://www.wxdu.org/',
    submissionUrl: 'https://www.wxdu.org/contact.html',
    sourceUrl: 'https://www.wxdu.org/contact.html',
    sourceType: 'automation_run_48_public_research',
    country: 'United States / Durham college radio',
    language: 'en',
    genres: ['college-radio', 'progressive-alternative', 'independent', 'electronic', 'rpm', 'world', 'local-north-carolina', 'radio-airplay', 'bandcamp-yum', 'email-submission'],
    submissionMethod: 'official-public-airplay-submission-email-route-with-bandcamp-yum-code-preference',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official WXDU contact page asks airplay submissions to use Bandcamp YUM codes where possible and routes music by Music Director category; human review is required for download/YUM-code choice, rights, metadata, RPM/world/local category routing, station fit and email-send approval.',
    notes: 'Official WXDU pages show an active college radio station and a public airplay submission route. No email was sent, no Bandcamp code was used and no file link was shared.'
  },
  {
    name: 'KDVS 90.3FM Davis Music Department Physical Submissions',
    websiteUrl: 'https://kdvs.org/',
    submissionUrl: 'https://kdvs.org/contact',
    sourceUrl: 'https://kdvs.org/contact',
    sourceType: 'automation_run_48_public_research',
    country: 'United States / Davis freeform college radio',
    language: 'en',
    genres: ['freeform-radio', 'college-radio', 'independent', 'underground', 'electronic', 'experimental', 'reggae', 'world', 'record-label-contact', 'physical-submission'],
    submissionMethod: 'official-public-music-department-contact-and-physical-submission-only-route',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official KDVS contact page lists Music Directors for music review, library maintenance, mail sorting and record-label contact, and instructs that all new music should be sent to the mailing address as physical submissions only; human review is required for package preparation, format, metadata, rights, station fit and avoiding any digital-style workaround.',
    notes: 'Official KDVS contact page identifies Music Department responsibilities and a physical-submission-only rule for new music. No email, upload, file link or physical shipment was attempted.'
  }
];
