import type { PlatformInput } from '../models/types.js';

export const run47SeedPlatforms: PlatformInput[] = [
  {
    name: '95bFM Auckland Submit Music',
    websiteUrl: 'https://95bfm.com/',
    submissionUrl: 'https://95bfm.com/news/how-do-you-do-submitting-music',
    sourceUrl: 'https://95bfm.com/news/how-do-you-do-submitting-music',
    sourceType: 'automation_run_47_public_research',
    country: 'New Zealand / Auckland independent student radio',
    language: 'en',
    genres: ['student-radio', 'independent', 'alternative', 'electronic', 'reggae', 'dub', 'world', 'hip-hop', 'local', 'radio-airplay', 'email-submission'],
    submissionMethod: 'official-public-email-route-with-streaming-link-and-lossless-download-link',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official 95bFM route asks artists to email a streaming link plus a lossless download link and requires human review for public stream access, lossless WAV/FLAC availability, release-date window, metadata, paid-PR neutrality, show/playlist fit and no-feedback expectations before any contact is made.',
    notes: 'Official 95bFM sources show an active independent Auckland radio station and a Submit Music route. The submission page gives guidelines for streaming and lossless download links, but the public web extract redacted the address, so no protected or masked contact was decoded and no email, upload or submission was attempted.'
  },
  {
    name: 'Fresh On The Net Send Us A Track',
    websiteUrl: 'https://freshonthenet.co.uk/',
    submissionUrl: 'https://freshonthenet.co.uk/submit/',
    sourceUrl: 'https://freshonthenet.co.uk/submit/',
    sourceType: 'automation_run_47_public_research',
    country: 'United Kingdom / global independent music blog and listening post',
    language: 'en',
    genres: ['independent', 'electronic', 'reggae', 'dub', 'world', 'alternative', 'songwriting', 'blog', 'reader-vote', 'soundcloud-submission'],
    submissionMethod: 'official-public-weekly-soundcloud-track-submission-form',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official weekly form accepts one public embeddable SoundCloud track and requires Terms acceptance; human review is required for inbox-open timing, one-track-per-week limits, public/worldwide availability, no-repeat/no-remix rules, AI policy, SoundCloud embed permissions and track readiness.',
    notes: 'Official Fresh On The Net pages show recent Listening Post/Fresh Faves activity and a public submit form with artist name, track name and SoundCloud URL fields. No form was filled, no SoundCloud track was submitted and no downstream radio email route was used.'
  },
  {
    name: 'dublab Radio Promotional Materials',
    websiteUrl: 'https://www.dublab.com/',
    submissionUrl: 'https://www.dublab.com/about',
    sourceUrl: 'https://www.dublab.com/about',
    sourceType: 'automation_run_47_public_research',
    country: 'United States / Los Angeles global online freeform radio',
    language: 'en',
    genres: ['freeform-radio', 'electronic', 'experimental', 'ambient', 'reggae', 'dub', 'world', 'dj-mixes', 'community-radio', 'promotional-materials'],
    submissionMethod: 'official-public-promotional-materials-email-route',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official dublab contact page lists a promotional-materials route, but the workflow is freeform and program/DJ-selected, so human review is required for station/show fit, rights, EPK/audio-link packaging, clean/explicit notes and anti-spam-safe outreach before any contact is made.',
    notes: 'Official dublab pages describe an active community-supported internet radio station and creative collective with extensive freeform programming. The public promo route was observed only; no email, upload, account action or submission was attempted.'
  },
  {
    name: 'NTS Radio Show Proposal',
    websiteUrl: 'https://www.nts.live/',
    submissionUrl: 'https://www.nts.live/contact',
    sourceUrl: 'https://www.nts.live/contact',
    sourceType: 'automation_run_47_public_research',
    country: 'United Kingdom / global online radio',
    language: 'en',
    genres: ['online-radio', 'electronic', 'bass', 'dubstep', 'reggae', 'dub', 'world', 'ambient', 'experimental', 'dj-mix', 'radio-show-proposal'],
    submissionMethod: 'official-public-radio-show-proposal-form-with-audio-demo-links',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official NTS contact page exposes a Radio Show Proposal form with audio-demo link fields; human review is required because this is a programmed show proposal, requires creative fit, demo-link selection, rights checks and form submission, and cannot be auto-submitted safely.',
    notes: 'Official NTS route asks for proposal details, show type and up to three audio/demo web links. No form field was completed, no audio link was submitted and no account or login flow was used.'
  },
  {
    name: 'WFMU Send Music to WFMU',
    websiteUrl: 'https://wfmu.org/',
    submissionUrl: 'https://wfmu.org/sendmusic.html',
    sourceUrl: 'https://wfmu.org/sendmusic.html',
    sourceType: 'automation_run_47_public_research',
    country: 'United States / Jersey City independent freeform radio',
    language: 'en',
    genres: ['freeform-radio', 'independent', 'underground', 'experimental', 'electronic', 'reggae', 'dub', 'world', 'physical-submission', 'music-director-review'],
    submissionMethod: 'official-public-physical-media-review-route-to-music-director',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official WFMU route accepts physical materials for review through the Music Director mailing path; human review is required for physical package preparation, format choice, one-sheet/metadata, station fit, no-return expectations and avoiding unrelated login/contact routes.',
    notes: 'Official WFMU pages show active freeform radio programming and a Send Music page welcoming vinyl, CD, CD-R and cassette materials for review. No login, music department contact page action, email, upload or physical shipment was attempted.'
  }
];
