import type { PlatformInput } from '../models/types.js';
import { run472SeedPlatforms } from './run472PlatformSeeds.js';

export const run471SeedPlatforms: PlatformInput[] = [
  {
    name: 'WRIU 90.3 FM Genre Department Music Submissions',
    websiteUrl: 'https://wriufm.org/',
    submissionUrl: 'https://wriufm.org/submissions/',
    sourceUrl: 'https://wriufm.org/submissions/',
    sourceType: 'automation_run_471_public_research',
    country: 'United States (Kingston, Rhode Island); the page welcomes unsigned, local and independent artists but does not explicitly state international eligibility.',
    language: 'en',
    genres: [
      'electronic',
      'rpm',
      'world',
      'reggae',
      'indie',
      'college-radio',
      'radio-airplay',
      'genre-department-email',
      'manual-review'
    ],
    submissionMethod: 'official first-party public genre-department email routes',
    feeRequired: false,
    feeAmount: 'No fee, checkout or payment step is published on the first-party submission page.',
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'The route is active and first-party, with three relevant public submission mailboxes, but department choice, digital delivery specifications, content rules, international and AI eligibility, rights and every final email action require human approval.',
    notes: 'The official site carries a 2026 copyright notice, publishes current FM and RIU2 stream links, program archives, a program guide and active genre-department submission addresses. No form field was filled, no terms were accepted, no file or external link was uploaded, no email was sent, no login was used, no CAPTCHA was solved and no payment or submission action was performed.'
  },
  {
    name: 'The Edge 105.1 & 105.3 FM Music Submission',
    websiteUrl: 'https://edge105.com/',
    submissionUrl: 'https://edge105.com/submit-your-music/',
    sourceUrl: 'https://edge105.com/submit-your-music/',
    sourceType: 'automation_run_471_public_research',
    country: 'Jamaica; the station describes a global-reggae focus and discoveries across 82 countries, but requires membership in a Jamaican music-industry association.',
    language: 'en',
    genres: [
      'reggae',
      'reggae-fusion',
      'gospel',
      'triple-a',
      'global-reggae',
      'clean-radio',
      'single-only',
      'external-music-link',
      'public-form',
      'manual-review'
    ],
    submissionMethod: 'official first-party public music-submission form using a Dropbox or comparable music link',
    feeRequired: false,
    feeAmount: 'No submission fee or payment step is published on the first-party route.',
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'The active first-party form is genre-relevant, but a Jamaican music-industry-association membership prerequisite may block eligibility. Strict content rules, file quality, external-link permissions, rights, AI eligibility, hidden controls and final submission require human approval.',
    notes: 'The official site publishes a current Monday-Saturday programme schedule, daily live-stream access, named hosts and shows, and current nationwide FM frequencies plus online listening. No form field was filled, no terms were accepted, no file or external link was uploaded, no email was sent, no login was used, no CAPTCHA was solved and no payment or submission action was performed.'
  },
  {
    name: 'Indie Global 365 Free Music Submission',
    websiteUrl: 'https://indieglobal365.com/',
    submissionUrl: 'https://indieglobal365.com/music-submission/',
    sourceUrl: 'https://indieglobal365.com/music-submission/',
    sourceType: 'automation_run_471_public_research',
    country: 'Global independent-artist internet-radio platform; operator location is not clearly stated on the inspected pages.',
    language: 'en',
    genres: [
      'reggae',
      'soca',
      'caribbean',
      'afro-pop',
      'hip-hop',
      'r-and-b',
      'positive-music',
      'direct-upload',
      'artwork-upload',
      'rights-declaration',
      'manual-review'
    ],
    submissionMethod: 'official first-party free public upload form for up to two MP3 files and artwork',
    feeRequired: false,
    feeAmount: 'The submission page and home page label the music-submission route as free. A separate $15 artist-membership plan is optional.',
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'The route is current and explicitly free, but direct MP3 and artwork uploads, mandatory terms acceptance, rights and streaming warranties, inconsistent legacy policy text, optional paid membership, unpublished AI eligibility and hidden controls require human approval.',
    notes: 'The first-party home page displays a current-song area, states that free music submission is open, maintains a music catalog, free DJ submission, artist membership and a live-radio route. No form field was filled, no terms were accepted, no file or external link was uploaded, no email was sent, no login was used, no CAPTCHA was solved and no payment or submission action was performed.'
  },
  {
    name: 'Smooth Jazz Club International Radio Programme Submission',
    websiteUrl: 'https://www.smoothjazz.club/',
    submissionUrl: 'https://www.smoothjazz.club/submitmusic/amp/',
    sourceUrl: 'https://www.smoothjazz.club/submitmusic/amp/',
    sourceType: 'automation_run_471_public_research',
    country: 'El Salvador-based international smooth-jazz programming project syndicated to radio stations and digital platforms.',
    language: 'en',
    genres: [
      'smooth-jazz',
      'contemporary-jazz',
      'instrumental-jazz',
      'jazz-fusion',
      'chill',
      'lounge',
      'radio-airplay',
      'email',
      'external-download-link',
      'manual-review'
    ],
    submissionMethod: 'official first-party public email route with a high-quality audio download or private streaming link',
    feeRequired: false,
    feeAmount: 'No submission fee, checkout or payment requirement is published on the submission page.',
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'The route is active, international and first-party, with a published submission mailbox, but narrow genre fit, external link or file preparation, artwork and rights, unpublished AI eligibility and every final email action require human approval.',
    notes: 'The official contact page lists programme posts dated March 1-3, 2026, and the submission page states that its programmes are carried by 71 stations and reach more than 250,000 weekly listeners. No form field was filled, no terms were accepted, no file or external link was uploaded, no email was sent, no login was used, no CAPTCHA was solved and no payment or submission action was performed.'
  },
  ...run472SeedPlatforms
];
