import type { PlatformInput } from '../models/types.js';

export const run49SeedPlatforms: PlatformInput[] = [
  {
    name: 'WPRB 103.3 FM Princeton Music Submissions',
    websiteUrl: 'https://wprb.com/',
    submissionUrl: 'https://wprb.com/music-submissions/',
    sourceUrl: 'https://wprb.com/music-submissions/',
    sourceType: 'automation_run_49_public_research',
    country: 'United States / Princeton college radio',
    language: 'en',
    genres: ['college-radio', 'freeform-radio', 'independent', 'electronic', 'dance', 'reggae', 'world', 'alternative', 'radio-airplay', 'email-submission', 'physical-submission'],
    submissionMethod: 'official-public-music-director-email-and-physical-media-route-with-physical-priority',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official WPRB Music Submissions route accepts physical releases and a public Music Director email route, but physical submissions are prioritized and human review is required for media format, metadata, clean/explicit notes, rights, station fit and whether a digital contact or physical package is appropriate.',
    notes: 'Official WPRB page invites artists, labels and promoters to submit new music, lists acceptable physical formats and provides a public Music Director route. No email, file link or physical package was sent.'
  },
  {
    name: 'KZSU Stanford 90.1 FM Music Directors',
    websiteUrl: 'https://kzsu.stanford.edu/',
    submissionUrl: 'https://kzsu.stanford.edu/contact/',
    sourceUrl: 'https://kzsu.stanford.edu/contact/',
    sourceType: 'automation_run_49_public_research',
    country: 'United States / Stanford college radio',
    language: 'en',
    genres: ['college-radio', 'freeform-radio', 'independent', 'electronic', 'world', 'reggae', 'experimental', 'radio-airplay', 'music-director-route', 'physical-submission', 'email-submission'],
    submissionMethod: 'official-public-music-director-email-and-snail-mail-route-with-cookie-protected-guidelines-page',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official KZSU contact page routes music to Music Directors and snail mail, while the linked music-guidelines page requires cookies/session handling; human review is required for guideline access without bypassing controls, music director targeting, metadata, rights, media choice and anti-spam-safe contact handling.',
    notes: 'Official KZSU site shows an active station and public Music Director route. The music page returned a cookies-required notice, so no cookie/session restriction was bypassed and no email or physical package was sent.'
  },
  {
    name: 'WCBN-FM Ann Arbor Music Hard-Copy Submissions',
    websiteUrl: 'https://wcbn.org/',
    submissionUrl: 'https://wcbn.org/contact/',
    sourceUrl: 'https://wcbn.org/contact/',
    sourceType: 'automation_run_49_public_research',
    country: 'United States / Ann Arbor freeform college radio',
    language: 'en',
    genres: ['freeform-radio', 'college-radio', 'independent', 'experimental', 'electronic', 'jazz', 'hip-hop', 'reggae', 'world', 'physical-submission', 'music-director-route'],
    submissionMethod: 'official-public-hard-copy-album-route-with-music-director-and-genre-director-routing',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official WCBN contact page accepts music from musicians willing to send hard copies, preferably CD or vinyl, and routes genre-specific releases to directors; human review is required for physical package preparation, genre routing, metadata, rights, station fit and protected or masked email handling.',
    notes: 'Official WCBN pages show an active freeform station and hard-copy music submission guidance. The available extract displayed role emails as protected placeholders, so no protected contact was decoded, no email was sent and no physical copy was mailed.'
  },
  {
    name: 'WHRB 95.3 FM Harvard Radio Promo Submissions',
    websiteUrl: 'https://www.whrb.org/',
    submissionUrl: 'https://www.whrb.org/contact',
    sourceUrl: 'https://www.whrb.org/contact',
    sourceType: 'automation_run_49_public_research',
    country: 'United States / Cambridge college radio',
    language: 'en',
    genres: ['college-radio', 'independent', 'electronic', 'underground', 'jazz', 'blues', 'classical', 'alternative', 'radio-airplay', 'physical-submission', 'department-routing'],
    submissionMethod: 'official-public-department-addressed-physical-cd-or-lp-promo-submission-route',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official WHRB contact page says promotional music requests should use physical CDs or LPs addressed to the appropriate department or member; human review is required for department fit, physical package preparation, metadata, rights, clean-content status and avoiding misrouted generic submissions.',
    notes: 'Official WHRB pages show active 2026 station content and a public promo-submission mailing route with department guidance. No email, file link, upload or physical package was sent.'
  },
  {
    name: 'Soundplate Free Playlist Submission System',
    websiteUrl: 'https://soundplate.com/',
    submissionUrl: 'https://play.soundplate.com/',
    sourceUrl: 'https://play.soundplate.com/',
    sourceType: 'automation_run_49_public_research',
    country: 'United Kingdom / global playlist submission platform',
    language: 'en',
    genres: ['playlist-submission', 'spotify', 'deezer', 'electronic', 'house', 'garage', 'bass', 'festival', 'independent', 'free-promotion', 'curator-marketplace'],
    submissionMethod: 'official-public-free-spotify-and-deezer-playlist-submission-grid-with-curator-selection',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official Soundplate Play page offers free Spotify and Deezer playlist submissions through playlist selection, but human review is required for track URL readiness, playlist relevance, curator choice, anti-spam compliance, rights, metadata and any downstream form/session steps before submission.',
    notes: 'Official Soundplate Play page states the playlist submission service is free and asks artists to submit only to relevant playlists. No playlist was selected, no form was submitted and no track URL was shared.'
  }
];