import type { PlatformInput } from '../models/types.js';
import { run500SeedPlatforms } from './run500PlatformSeeds.js';

const run499NewSeedPlatforms: PlatformInput[] = [
  {
    "name": "7clouds Worldwide Multi-Channel Demo Submission Form",
    "websiteUrl": "https://7clouds.org/",
    "submissionUrl": "https://7clouds.org/",
    "sourceUrl": "https://7clouds.org/",
    "sourceType": "automation_run_499_public_research",
    "country": "Worldwide / internet-based global music-channel network with national and genre channels; the official site identifies its headquarters as the Internet, Worldwide.",
    "language": "en",
    "genres": [
      "drum and bass",
      "dubstep",
      "Afro House",
      "Afrobeats",
      "Amapiano",
      "dance",
      "future house",
      "tech house",
      "techno",
      "trance",
      "trap",
      "tropical",
      "phonk",
      "R&B",
      "rap",
      "chill",
      "first-party form",
      "stream link",
      "mandatory terms and privacy",
      "manual-review"
    ],
    "submissionMethod": "official first-party demo form requesting artist and contact details, track name, stream link, release status, artist status, desired 7clouds channel and additional context",
    "feeRequired": false,
    "feeAmount": "No mandatory submission, review or feature fee is visible on the official demo form or published terms.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "Channel and genre fit, release status, stream-link access, master/composition/sample/contributor rights, Content ID, generative-AI eligibility, mandatory Terms and Privacy acceptance, documented demo-data retention of up to two years, hidden or submit-time anti-spam controls and the final form action require human review."
  },
  {
    "name": "DNBB Music Group Global Drum & Bass / Bass LabelRadar Demo Portal",
    "websiteUrl": "https://dnbbrecords.com/",
    "submissionUrl": "https://www.labelradar.com/labels/dnbb/portal",
    "sourceUrl": "https://dnbbrecords.com/",
    "sourceType": "automation_run_499_public_research",
    "country": "Brazil / São Paulo-based global Drum & Bass and Bass Music ecosystem reporting listeners in 180 countries and worldwide distribution.",
    "language": "pt/en/es",
    "genres": [
      "drum and bass",
      "jungle",
      "dubstep",
      "breakbeat",
      "UK garage",
      "bass house",
      "house",
      "tech house",
      "progressive house",
      "Afro House",
      "techno",
      "melodic techno",
      "trance",
      "LabelRadar portal",
      "private SoundCloud or Dropbox link",
      "login/account boundary",
      "credit boundary",
      "manual-review"
    ],
    "submissionMethod": "official DNBB website linking to the external DNBB LabelRadar portal and publishing file, metadata, biography, social-link and private-link guidelines",
    "feeRequired": false,
    "feeAmount": "A direct LabelRadar label submission requires five credits. The free Lite plan provides five free monthly credits; additional credits and PRO are optional paid products.",
    "loginRequired": true,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "LabelRadar registration/login, available-credit balance, correct DNBB imprint and genre fit, WAV/MP3 preparation, BPM/key/title filename metadata, biography and socials, private-link access, release status, master/composition/sample/contributor rights, Content ID, generative-AI policy, privacy, hidden verification, post-selection terms and the final submission action require human review."
  },
  {
    "name": "Reggae Global Radio Worldwide Reggae Airplay Email Submission",
    "websiteUrl": "https://reggaeglobalradio.com/",
    "submissionUrl": "https://reggaeglobalradio.com/music-submission",
    "sourceUrl": "https://reggaeglobalradio.com/music-submission",
    "sourceType": "automation_run_499_public_research",
    "country": "United States / globally oriented online reggae radio station with worldwide presenters, streaming and audience positioning.",
    "language": "en",
    "genres": [
      "reggae",
      "roots reggae",
      "dub",
      "dancehall",
      "lovers rock",
      "Caribbean music",
      "radio airplay",
      "public submission email",
      "MP3 attachment",
      "custom station ID jingles",
      "manual-review"
    ],
    "submissionMethod": "official public music-submission mailbox requiring one complete email containing a biography, correctly named MP3 tracks, released or pre-release status and two correctly named Reggae Global Radio station-ID jingles",
    "feeRequired": false,
    "feeAmount": "No mandatory submission or airplay-review fee is published on the official music-submission page.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "Reggae fit, released/pre-release status, biography, MP3-only format and filename checks, creation and rights clearance for two custom station-ID jingles, one-email packaging, master/composition/sample/contributor and broadcast rights, Content ID, generative-AI disclosure, privacy/retention, editorial review and the final email action require human review."
  }
];

export const run499SeedPlatforms: PlatformInput[] = [
  ...run499NewSeedPlatforms,
  ...run500SeedPlatforms
];
