import type { PlatformInput } from '../models/types.js';

export const run484SeedPlatforms: PlatformInput[] = [
  {
    "name": "WHCR 90.3 FM Show-Directed Music Submission",
    "websiteUrl": "https://whcr.org/",
    "submissionUrl": "https://whcr.org/music-submissions/",
    "sourceUrl": "https://whcr.org/music-submissions/",
    "sourceType": "automation_run_484_public_research",
    "country": "United States / City College of New York community FM and online station in Harlem; the DNB NYC programme explicitly features local and international artists, while other programme eligibility must be checked show by show.",
    "language": "en",
    "genres": [
      "independent",
      "drum and bass",
      "jungle",
      "breaks",
      "house",
      "deep house",
      "soulful house",
      "reggae",
      "world music",
      "African",
      "Latin",
      "MP3",
      "email",
      "physical CD",
      "manual-review"
    ],
    "submissionMethod": "official first-party instructions directing artists to select a matching WHCR music show and email an MP3 to that show's published address, with an optional show-addressed CD route",
    "feeRequired": false,
    "feeAmount": "No mandatory submission fee or payment is published for the show-directed email or mail route.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "Programme selection, show-specific eligibility and recipient, MP3/CD packaging, international fit beyond DNB NYC, rights, AI policy, attachment safety, follow-up timing and the final email or postal action require human approval.",
    "notes": "Passively verified on 2026-07-18 from WHCR's official submission instructions, current 2026 station site and programme pages. WHCR requires artists to choose a matching show, email an MP3 directly to the show and follow up with that show; walk-in submissions are prohibited. DNB NYC publishes dnbnycradio@gmail.com and explicitly features local and international artists. House in Harlem publishes tinad903@gmail.com and features DJs from around the world. Mystic Vybes publishes mysticvybes@gmail.com. These addresses are first-party published and syntactically valid but use consumer Gmail domains, so domain alignment cannot be established. No SMTP, MX, catch-all, mailbox-level or deliverability probing was performed. No email or physical item was sent."
  },
  {
    "name": "VANTA Recordings Melodic House & Techno Demo Submission",
    "websiteUrl": "https://vantarecordings.com/",
    "submissionUrl": "https://vantarecordings.com/",
    "sourceUrl": "https://vantarecordings.com/",
    "sourceType": "automation_run_484_public_research",
    "country": "Germany / independent melodic house and techno label; the public demo route does not expressly state universal international-artist eligibility.",
    "language": "en",
    "genres": [
      "electronic",
      "melodic house",
      "melodic techno",
      "ethereal techno",
      "progressive house",
      "deep house",
      "private SoundCloud",
      "form",
      "email",
      "reCAPTCHA",
      "label demo",
      "manual-review"
    ],
    "submissionMethod": "official first-party demo form requiring a private SoundCloud link and protected by Google reCAPTCHA, with a domain-aligned demo mailbox also published",
    "feeRequired": false,
    "feeAmount": "No mandatory submission fee or payment is published for the official form or demo mailbox.",
    "loginRequired": false,
    "captchaDetected": true,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "Melodic-house/techno fit, original and unreleased-status checks, private-link access, rights and Content ID, AI policy, privacy/retention, Google reCAPTCHA and the final form or email action require human approval.",
    "notes": "Passively verified on 2026-07-18 from VANTA Recordings' official site and current release listings. The form requests name, email, a private SoundCloud link and social media and is protected by Google reCAPTCHA. demo@vantarecordings.com is first-party published, syntactically valid, domain-aligned and designated for demos/promos; paul@vantarecordings.com is general contact only. Beatport lists VANTA Recordings releases through 2026-06-19. No CAPTCHA was solved, no field was filled and no link or email was sent."
  },
  {
    "name": "YHV Music Group / YHV Records Demo Submission",
    "websiteUrl": "https://www.yhvmusic.group/",
    "submissionUrl": "https://www.yhvmusic.group/demo-submission",
    "sourceUrl": "https://www.yhvmusic.group/demo-submission",
    "sourceType": "automation_run_484_public_research",
    "country": "Indonesia / Bali-based, global-facing electronic label group; the group presents an international catalogue, but the public demo page does not state a separate universal country-eligibility rule.",
    "language": "en",
    "genres": [
      "electronic",
      "Afro House",
      "Afro Tech",
      "Afro Tribal",
      "Organic House",
      "Melodic House",
      "Progressive House",
      "Indie Dance",
      "Amapiano",
      "unreleased demo",
      "WAV",
      "extended mix",
      "email",
      "embedded form",
      "optional Groover",
      "manual-review"
    ],
    "submissionMethod": "official first-party demo mailbox and embedded form for unreleased electronic demos; an optional paid Groover review route is separate from the free direct route",
    "feeRequired": false,
    "feeAmount": "The direct first-party email/form route has no visible mandatory fee. An optional external Groover review route requires login and paid credits and is not the canonical free route.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "Unreleased-demo and extended-version eligibility, exact sublabel fit, WAV/link delivery, rights and Content ID, AI policy, embedded-form controls, privacy/retention, optional Groover login/payment separation and final submission require human approval.",
    "notes": "Passively verified on 2026-07-18 from YHV Music Group's official demo and YHV Records pages plus current catalogue records. The official route publishes demos@yhvmusic.group and states that electronic producers may submit by email or the embedded form. Current first-party guidance lists unreleased demos, WAV preferred and an extended version as requirements for YHV Records genres. demos@yhvmusic.group is first-party published, syntactically valid, domain-aligned and designated for demos; info@yhvmusic.group is general contact only. Beatport shows YHV Records releases through 2026-07-17 and upcoming releases dated 2026-07-24. No embedded field, login, Groover route, payment or submission was used."
  }
];
