import type { PlatformInput } from '../models/types.js';

export const run45SeedPlatforms: PlatformInput[] = [
  {
    name: 'CJSW 90.9 FM Calgary Music Submissions',
    websiteUrl: 'https://cjsw.com/',
    submissionUrl: 'https://cjsw.com/music/submit/',
    sourceUrl: 'https://cjsw.com/music/submit/',
    sourceType: 'automation_run_45_public_research',
    country: 'Canada / Calgary campus and community radio',
    language: 'en',
    genres: ['independent', 'freeform', 'electronic', 'reggae', 'dub', 'world', 'hip-hop', 'jazz', 'folk', 'rock', 'punk', 'experimental', 'local', 'album-submission'],
    submissionMethod: 'official-public-digital-album-ep-upload-form-via-jotform',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official CJSW route accepts only digital music submissions through an external upload form and only recent albums with at least three unique tracks in MP3 ZIP format, so human review is required for release age, album/EP eligibility, metadata, file packaging, external form controls and station-fit checks before any use.',
    notes: 'Official page says CJSW only accepts digital submissions, does not accept singles, requires MP3 ZIP album submissions and routes local/independent assistance to the Music & Performance Director. No form, upload, email or tracking signup action was attempted.'
  },
  {
    name: 'CFUV 101.9 FM Victoria Music Submissions',
    websiteUrl: 'https://cfuv.uvic.ca/',
    submissionUrl: 'https://cfuv.uvic.ca/music-submissions/',
    sourceUrl: 'https://cfuv.uvic.ca/music-submissions/',
    sourceType: 'automation_run_45_public_research',
    country: 'Canada / Victoria campus and community radio',
    language: 'en',
    genres: ['independent', 'underappreciated', 'electronic', 'world', 'reggae', 'dub', 'hip-hop', 'jazz', 'folk', 'roots', 'blues', 'rock', 'metal', 'classical', 'freeform'],
    submissionMethod: 'official-public-email-download-link-route-to-music-director',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official CFUV route requires email submission to the Music Director with digital download links, minimum three unique tracks, 320kbps MP3s, bio, artist/album/track metadata and freeform station-fit review, so it must remain manual.',
    notes: 'Official source lists music@cfuv.ca, says all submissions should be sent there, discourages physical submissions except local artists, requires at least three unique tracks and reviews for lyrical concerns, recording quality, criteria compliance and format fit. No email or file transfer was sent.'
  },
  {
    name: 'CJSR 88.5 FM Edmonton Submit Music',
    websiteUrl: 'https://www.cjsr.com/',
    submissionUrl: 'https://www.cjsr.com/submit-music/',
    sourceUrl: 'https://www.cjsr.com/submit-music/',
    sourceType: 'automation_run_45_public_research',
    country: 'Canada / Edmonton independent community radio',
    language: 'en',
    genres: ['eclectic', 'independent', 'freeform', 'reggae', 'dub', 'world', 'electronic', 'folktronica', 'hip-hop', 'folk', 'experimental', 'albums', 'eps'],
    submissionMethod: 'official-public-digital-album-ep-email-download-link-and-physical-mail-route',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official CJSR route accepts albums or EPs by physical mail/drop-off or digital files via music@cjsr.com, but rejects singles and paid streaming links, and CJSR has a January 2026 AI policy requiring human oversight and rejecting wholly AI-generated music, so manual rights, originality, file, metadata and clean-language review is required.',
    notes: 'Official source lists music@cjsr.com, physical mailing instructions, Bandcamp/cloud download link guidance, metadata tips, language warnings and a no-singles policy. No email, physical shipment, upload or DJ contact was attempted.'
  },
  {
    name: 'KBOO 90.7 FM Portland Submit Music',
    websiteUrl: 'https://kboo.fm/',
    submissionUrl: 'https://kboo.fm/submit-your-music',
    sourceUrl: 'https://kboo.fm/submit-your-music',
    sourceType: 'automation_run_45_public_research',
    country: 'United States / Portland community radio',
    language: 'en',
    genres: ['community-radio', 'emerging', 'world', 'reggae', 'electronic', 'rock', 'punk', 'folk', 'jazz', 'hip-hop', 'independent', 'physical-submission'],
    submissionMethod: 'official-public-physical-mail-route-to-genre-specific-music-reviewers',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official KBOO route is physical-mail only because KBOO says it does not yet have a digital library and lacks capacity to download and burn CDs of digital submissions; human review is required for physical packaging, genre addressee selection, one-sheet/FCC clean notes and no-airplay-guarantee acknowledgement.',
    notes: 'Official source lists the Portland mailing address and genre-specific ATTN routing, including World Music/Reggae and Electronic/other genres. It states submissions become KBOO property and are not returned. No physical mail, account, form or contact action was attempted.'
  },
  {
    name: 'KOOP 91.7 FM Austin Music Library Submissions',
    websiteUrl: 'https://koop.org/',
    submissionUrl: 'https://koop.org/about-us/contact/',
    sourceUrl: 'https://koop.org/about-us/contact/',
    sourceType: 'automation_run_45_public_research',
    country: 'United States / Austin community radio',
    language: 'en',
    genres: ['community-radio', 'independent', 'world', 'global-roots', 'electronic', 'reggae', 'dub', 'folk', 'jazz', 'experimental', 'local', 'library-submission'],
    submissionMethod: 'official-public-music-library-email-route',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official KOOP contact page says the Music Library welcomes music submissions at music@koop.org, but the page does not publish a complete static ingest workflow, so human review is required for pitch scope, file/link preference, metadata, clean-content notes, genre/show targeting and email validation before any outreach.',
    notes: 'Official source lists music@koop.org for Music Library submissions and info@koop.org for feedback/correspondence; homepage shows active 2026 programming and updates. No email or newsletter/form action was attempted.'
  }
];
