import type { PlatformInput } from '../models/types.js';
import { run482SeedPlatforms } from './run482PlatformSeeds.js';

const run481NewSeedPlatforms: PlatformInput[] = [
  {
    "name": "Camaradio 101.3FM Music Submission",
    "websiteUrl": "https://camaradio.org/",
    "submissionUrl": "https://camaradio.org/submissions/",
    "sourceUrl": "https://camaradio.org/submissions/",
    "sourceType": "automation_run_481_public_research",
    "country": "United States / Camarillo, California nonprofit LPFM and online community station; the official form asks whether the artist is Ventura County-based and permits a No answer, but international eligibility is not expressly confirmed.",
    "language": "en",
    "genres": [
      "electronic",
      "dance",
      "indie",
      "alternative",
      "rock",
      "pop",
      "jazz",
      "blues",
      "eclectic",
      "community radio",
      "MP3",
      "WAV",
      "download-link",
      "direct-upload",
      "manual-review"
    ],
    "submissionMethod": "official first-party public one-song form using direct WAV/MP3 upload or a downloadable music link for editorial airplay consideration",
    "feeRequired": false,
    "feeAmount": "No mandatory submission fee or payment is published for the official route.",
    "loginRequired": false,
    "captchaDetected": true,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "Nonlocal and international eligibility, one-track selection, WAV/MP3 technical limits, link/upload handling, rights, AI eligibility, privacy/licence terms, visible arithmetic human verification, hidden anti-spam controls and the final form submission require human approval.",
    "notes": "Passively verified on 2026-07-18 from the official submission, schedule, home, about, support and 2026 news/event pages. The form accepts one song by download link or WAV/MP3 upload at 44.1/48 kHz, 16-bit stereo and under 10 MB, requires a Ventura County yes/no answer, and includes visible arithmetic human verification. hello@camaradio.org is first-party published for sponsorship/general support, not as a music-submission mailbox. No SMTP, MX, catch-all, mailbox-level or deliverability probing was performed. No field was filled, no file or link was uploaded or shared, no CAPTCHA was completed or bypassed and no payment or submission action was performed."
  },
  {
    "name": "WUAG 103.1 FM Music Submission",
    "websiteUrl": "https://wuag.uncg.edu/",
    "submissionUrl": "https://wuag.uncg.edu/music-submissions/",
    "sourceUrl": "https://wuag.uncg.edu/music-submissions/",
    "sourceType": "automation_run_481_public_research",
    "country": "United States / Greensboro, North Carolina university and community radio station; the form explicitly accepts North Carolina and non-North-Carolina artists, while international eligibility is not separately confirmed.",
    "language": "en",
    "genres": [
      "electronic",
      "dance",
      "hip-hop",
      "reggae",
      "world",
      "experimental",
      "indie",
      "alternative",
      "rock",
      "jazz",
      "college radio",
      "MP3",
      "WAV",
      "direct-upload",
      "download-link",
      "manual-review"
    ],
    "submissionMethod": "official university-hosted first-party public form accepting a single, EP or album by WAV/MP3 upload or Dropbox/Google Drive download link",
    "feeRequired": false,
    "feeAmount": "No mandatory submission fee or payment is published for the official route.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "International eligibility, song-or-release selection, FCC and clean-content review, WAV/MP3 upload or cloud-link access, rights, AI eligibility, privacy/licence terms, possible hidden form controls and the final submission require human approval.",
    "notes": "Passively verified on 2026-07-18 from the official university-hosted submission, FAQ and current contact pages. WUAG accepts a single, EP or album by WAV/MP3 upload up to 2 GB or Dropbox/Google Drive download link, rejects YouTube, SoundCloud and Spotify links, and asks for FCC-violation disclosure. The form supports North Carolina and non-North-Carolina artists, while international eligibility remains unconfirmed. jdmonroe2@uncg.edu is first-party published as the current Music + Productions Director contact and was not substituted for the form. No visible CAPTCHA appeared in passive indexing; hidden submit-time controls remain unknown. No field was filled, no file or link was uploaded or shared and no payment or submission action was performed."
  },
  {
    "name": "KAZI 88.7 FM Untapped Music Submission",
    "websiteUrl": "https://kazifm.org/",
    "submissionUrl": "mailto:music@kazifm.org",
    "sourceUrl": "https://kazifm.org/untapped-music-submissions/",
    "sourceType": "automation_run_481_public_research",
    "country": "United States / Austin, Texas noncommercial community FM and online station; the official route supports independent music but does not expressly confirm international artist eligibility.",
    "language": "en",
    "genres": [
      "reggae",
      "hip-hop",
      "rap",
      "R&B",
      "soul",
      "Afro",
      "jazz",
      "house",
      "urban",
      "independent",
      "MP3",
      "WAV",
      "streaming-link",
      "download-link",
      "email",
      "manual-review"
    ],
    "submissionMethod": "official first-party domain-aligned music-submission mailbox requiring one radio-edited song, a stream and downloadable MP3/WAV",
    "feeRequired": false,
    "feeAmount": "No mandatory submission fee or payment is published for the official route.",
    "loginRequired": false,
    "captchaDetected": false,
    "paymentRequired": false,
    "manualReviewRequired": true,
    "manualReviewReason": "International eligibility, one radio-edited track, stream/download delivery, MP3/WAV quality, rights, AI eligibility, privacy/licence/retention terms, recipient verification and the final email send require human approval.",
    "notes": "Passively verified on 2026-07-18 from the official Untapped submission, live schedule, about and 2026 events pages. KAZI requests one new radio-edited song, a streaming link and downloadable MP3/WAV, plus artist and contact details. music@kazifm.org is first-party published, syntactically valid, domain-aligned and explicitly designated for music submissions; info@kazifm.org is general only. International eligibility, AI policy and submission-specific licence/retention terms remain unconfirmed. No SMTP, MX, catch-all, mailbox-level or deliverability probing was performed. No email was sent, no file or link was attached or shared and no payment or submission action was performed."
  }
];

export const run481SeedPlatforms: PlatformInput[] = [
  ...run481NewSeedPlatforms,
  ...run482SeedPlatforms
];
