import type { PlatformInput } from '../models/types.js';

export const run52SeedPlatforms: PlatformInput[] = [
  {
    name: 'SomaFM Submit Music for Airplay',
    websiteUrl: 'https://somafm.com/',
    submissionUrl: 'https://somafm.com/contact/submitmusic.html',
    sourceUrl: 'https://somafm.com/contact/submitmusic.html',
    sourceType: 'automation_run_52_public_research',
    country: 'United States / global listener-supported internet radio',
    language: 'en',
    genres: ['internet-radio', 'listener-supported-radio', 'independent', 'electronic', 'downtempo', 'ambient', 'idm', 'world', 'reggae', 'soul', 'radio-airplay', 'music-director-route', 'email-submission', 'download-link', 'bandcamp-yum-code'],
    submissionMethod: 'official-public-digital-music-submission-email-route-with-channel-specific-music-director-routing',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official SomaFM Submit Music page requires channel-specific music director routing and digital delivery via Bandcamp YUM/download code or WeTransfer/Dropbox link; human review is required for no-AI policy, channel fit, MP3 bitrate/metadata, no-SoundCloud/YouTube/Mixcloud files, duplicate-email avoidance, rights, clean/explicit status and contact validation before any outreach.',
    notes: 'Official SomaFM page says it supports commercial, independent, emerging and unsigned artists, requires digital submissions rather than CDs, lists active channel-specific submission addresses including electronic/world/reggae-adjacent channels, and warns not to send the same release to multiple music directors. No email, upload or file link was sent.'
  },
  {
    name: 'KVRX 91.7FM Austin Music Submissions',
    websiteUrl: 'https://kvrx.org/',
    submissionUrl: 'https://kvrx.org/app/contact/',
    sourceUrl: 'https://kvrx.org/app/contact/',
    sourceType: 'automation_run_52_public_research',
    country: 'United States / Austin college radio',
    language: 'en',
    genres: ['college-radio', 'student-radio', 'independent', 'local-music', 'electronic', 'world', 'reggae', 'hip-hop', 'radio-airplay', 'music-director-route', 'email-submission', 'physical-submission', 'digital-submission'],
    submissionMethod: 'official-public-music-department-email-route-with-physical-and-digital-submission-support',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official KVRX Contact page routes airplay submissions to the Music Department address and says both physical and digital submissions are being accepted; human review is required for AI-policy compliance, physical-versus-digital routing, metadata, rights, clean/explicit status, station fit and contact validation before any outreach or package preparation.',
    notes: 'Official KVRX pages show an active Austin college-radio station broadcasting online and on 91.7 FM, route all music submissions for airplay to music@kvrx.org, and state that AI-assisted or AI-generated music will not be considered. No email, upload, file link or physical package was sent.'
  },
  {
    name: 'WUSB 90.1FM Stony Brook Music Director Submissions',
    websiteUrl: 'https://wusb.fm/',
    submissionUrl: 'https://wusb.fm/node/78380',
    sourceUrl: 'https://wusb.fm/node/78380',
    sourceType: 'automation_run_52_public_research',
    country: 'United States / Long Island community radio',
    language: 'en',
    genres: ['community-radio', 'freeform-radio', 'college-radio', 'independent', 'electronic', 'world', 'reggae', 'hip-hop', 'radio-airplay', 'music-director-route', 'email-submission', 'physical-submission'],
    submissionMethod: 'official-public-music-director-email-and-physical-mail-route',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official WUSB Contact page accepts music by Music Director email or physical mail; human review is required for deciding email versus physical package, metadata, rights, clean/explicit status, station and show fit, address handling and contact validation before any outreach or mailing.',
    notes: 'Official WUSB site shows current station activity and the Contact page says to email music to md.wusbradio@gmail.com or send it to the station address with Attn: Music Director. No email, file link, upload or physical mail was sent.'
  },
  {
    name: 'KSCU 103.3FM Santa Clara Music Director Submissions',
    websiteUrl: 'https://kscu.org/',
    submissionUrl: 'https://kscu.org/about/',
    sourceUrl: 'https://kscu.org/about/',
    sourceType: 'automation_run_52_public_research',
    country: 'United States / Santa Clara college radio',
    language: 'en',
    genres: ['college-radio', 'student-radio', 'independent', 'eclectic', 'local-music', 'electronic', 'world', 'reggae', 'hip-hop', 'radio-airplay', 'music-director-route', 'email-submission'],
    submissionMethod: 'official-public-music-director-email-route-for-airplay-consideration',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official KSCU About page provides the Music Director address for airplay submissions, but human review is required for outreach packaging, metadata, rights, clean/explicit status, file/link preparation, station fit and public-contact validation before any email is sent.',
    notes: 'Official KSCU About page lists a 2025-2026 Music Director and says artists should email music@kscu.org to submit music for airplay. The station homepage describes an active Santa Clara student-run radio station with online and 103.3 FM broadcasting. No email, upload or file link was sent.'
  },
  {
    name: 'KZSC 88.1FM Santa Cruz Genre Music Directors',
    websiteUrl: 'https://kzsc.org/',
    submissionUrl: 'https://kzsc.org/contact/',
    sourceUrl: 'https://kzsc.org/contact/',
    sourceType: 'automation_run_52_public_research',
    country: 'United States / Santa Cruz college-community radio',
    language: 'en',
    genres: ['college-radio', 'community-radio', 'independent', 'rpm-electronic', 'international', 'hip-hop', 'hardcore', 'jazz', 'folk', 'radio-airplay', 'genre-director-route', 'protected-contact-route'],
    submissionMethod: 'official-public-genre-music-director-contact-route-with-protected-email-links',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official KZSC Contact page lists Station Music Directors by genre, including RPM & Electronic and International, but the extracted email links are protected/redacted; human review is required for authorized-contact handling without decoding, genre-director selection, metadata, rights, clean/explicit status, station fit and contact validation.',
    notes: 'Official KZSC Contact page exposes a genre-specific Station Music Directors route while the homepage shows 2026 station activity and recent interviews. Contact links were rendered as protected/redacted and were not decoded or guessed. No email, form, upload or file link was sent.'
  }
];
