import type { PlatformInput } from '../models/types.js';

export const run53SeedPlatforms: PlatformInput[] = [
  {
    name: 'KCSB-FM Santa Barbara Artist Inquiry',
    websiteUrl: 'https://www.kcsb.org/',
    submissionUrl: 'https://www.kcsb.org/contact/artist-inquiry/',
    sourceUrl: 'https://www.kcsb.org/contact/artist-inquiry/',
    sourceType: 'automation_run_53_public_research',
    country: 'United States / Santa Barbara college-community radio',
    language: 'en',
    genres: ['college-radio', 'community-radio', 'freeform-radio', 'independent', 'electronic', 'world', 'reggae', 'hip-hop', 'dj-music', 'radio-airplay', 'music-library', 'live-on-air', 'artist-inquiry', 'external-form'],
    submissionMethod: 'official-public-artist-inquiry-form-for-radio-music-library-live-air-and-premiere-consideration',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official KCSB Artist Inquiry page routes artists, bands and DJs to an external Google Form for live on-air performance, station events, music-library addition and KCSB.org premieres; human review is required for external-form handling, route selection, rights, metadata, clean/explicit status, artist-fit and form-field validation before any submission.',
    notes: 'Official KCSB page exposes a public artist inquiry route and links to a forms.gle form. No form was opened for submission, no upload was made and no protected contact was decoded.'
  },
  {
    name: 'WNCW 88.7 Submit Music',
    websiteUrl: 'https://www.wncw.org/',
    submissionUrl: 'https://www.wncw.org/submit-music',
    sourceUrl: 'https://www.wncw.org/submit-music',
    sourceType: 'automation_run_53_public_research',
    country: 'United States / Western North Carolina public radio',
    language: 'en',
    genres: ['public-radio', 'aaa-radio', 'americana', 'folk', 'blues', 'jazz', 'reggae', 'world', 'rock', 'indie', 'radio-airplay', 'programming-department-route', 'email-submission', 'physical-submission', 'download-link'],
    submissionMethod: 'official-public-programming-department-physical-mail-and-digital-download-email-route',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official WNCW Submit Music page prefers CD submissions but allows WAV/MP3 files by Music Department email via Dropbox or Google Drive; human review is required for physical-versus-digital routing, one-sheet/EPK packaging, file-link preparation, metadata, rights, clean/explicit status, station fit and contact validation before any outreach or package preparation.',
    notes: 'Official WNCW page says DJs hand-pick submitted music, provides CD mailing instructions and lists a public digital-file route through martin@wncw.org. No email, file link, upload or physical mail was sent.'
  },
  {
    name: 'WYEP Pittsburgh Area Music Submissions',
    websiteUrl: 'https://www.wyep.org/',
    submissionUrl: 'https://www.wyep.org/wyep-pittsburgh-area-music-submissions',
    sourceUrl: 'https://www.wyep.org/wyep-pittsburgh-area-music-submissions',
    sourceType: 'automation_run_53_public_research',
    country: 'United States / Pittsburgh public radio local-music route',
    language: 'en',
    genres: ['public-radio', 'aaa-radio', 'independent', 'local-music', 'pittsburgh-music', 'electronic', 'world', 'reggae', 'hip-hop', 'radio-airplay', 'local-feature', 'email-submission', 'physical-submission', 'specialty-show-route'],
    submissionMethod: 'official-public-local-music-email-and-hard-copy-route-for-airplay-and-local-feature-consideration',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official WYEP page is focused on Pittsburgh/Western Pennsylvania artists and accepts music links by local-music email or hard-copy mail; human review is required for regional eligibility, specialty-show targeting, FCC-clean edits, track-pick guidance, metadata, rights, station fit and contact validation before any outreach or mailing.',
    notes: 'Official WYEP page describes Local 913, Pittsburgh Music Hour and staff-voted airplay consideration, and lists localmusic@wyep.org plus a physical mail route. No email, file link, upload or physical mail was sent.'
  },
  {
    name: 'KUTX Austin Submit Your Music',
    websiteUrl: 'https://kutx.org/',
    submissionUrl: 'https://kutx.org/submit-your-music/',
    sourceUrl: 'https://kutx.org/submit-your-music/',
    sourceType: 'automation_run_53_public_research',
    country: 'United States / Austin public music radio',
    language: 'en',
    genres: ['public-radio', 'aaa-radio', 'austin-music', 'texas-music', 'independent', 'new-music', 'electronic', 'experimental', 'hip-hop', 'latin', 'world', 'reggae', 'radio-airplay', 'music-director-route', 'specialty-show-route', 'email-submission', 'download-link'],
    submissionMethod: 'official-public-music-director-email-route-with-wav-download-link-and-specialty-show-targeting',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official KUTX Submit Your Music page requires Music Director email packaging with a streaming link, downloadable WAV link, bio/release notes and optional specialty-show targeting; human review is required for WAV-link preparation, ATX/TX/local flagging, FCC-clean radio edit, mastered-track status, specialty-show fit, metadata, rights and contact validation before any outreach.',
    notes: 'Official KUTX page lists music@kutx.org for on-air rotation and names genre-specific specialty shows including Soundfounder for electronic/experimental music. No email, form, upload or file link was sent.'
  },
  {
    name: 'KXT 91.7 Dallas Music Submissions',
    websiteUrl: 'https://kxt.org/',
    submissionUrl: 'https://kxt.org/submissions/',
    sourceUrl: 'https://kxt.org/submissions/',
    sourceType: 'automation_run_53_public_research',
    country: 'United States / Dallas-Fort Worth public independent music radio',
    language: 'en',
    genres: ['public-radio', 'independent-radio', 'aaa-radio', 'north-texas-music', 'independent', 'world', 'latin', 'electronic', 'soul', 'reggae', 'radio-airplay', 'digital-form', 'streaming-link', 'wav-download-link', 'one-song-submission'],
    submissionMethod: 'official-public-digital-music-submission-form-for-airplay-consideration',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official KXT Music Submissions page uses a Wufoo online form and requires one-song-only consideration, streaming link, downloadable WAV file and authorization for KXT to air selected music; human review is required for external-form handling, WAV specs, one-song selection, rights authorization, metadata, station fit and form-field validation before any submission.',
    notes: 'Official KXT page says artists can submit one song for airplay consideration using the linked online form, with streaming and downloadable WAV requirements. No form was submitted, no upload was made and no account or payment flow was used.'
  }
];
