import type { PlatformInput } from '../models/types.js';

export const run58SeedPlatforms: PlatformInput[] = [
  {
    name: '2SER 107.3FM Sydney Submit Music for Airplay',
    websiteUrl: 'https://www.2ser.com/',
    submissionUrl: 'https://www.2ser.com/how-to-submit-music',
    sourceUrl: 'https://www.2ser.com/how-to-submit-music',
    sourceType: 'automation_run_58_public_research',
    country: 'Australia / New South Wales / Sydney community radio',
    language: 'en',
    genres: ['2ser', 'community-radio', 'sydney', 'radio-airplay', 'independent', 'alternative', 'experimental', 'electronic', 'world', 'reggae', 'web-form', 'manual-review'],
    submissionMethod: 'official-public-2ser-airplay-consideration-web-form-for-track-submissions',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: '2SER publishes an official Submit Your Music form for airplay consideration; human review is required because the route requires form completion with contact, location, release date, release title, artist bio and social metadata, plus rights and station-fit review before any submission.',
    notes: 'Public research confirmed active 2SER 2026 stories and episodes plus the official How to Submit Music page. No route action was taken.'
  },
  {
    name: 'CJSW 90.9FM Calgary Music Submissions',
    websiteUrl: 'https://cjsw.com/',
    submissionUrl: 'https://cjsw.com/music/submit/',
    sourceUrl: 'https://cjsw.com/music/submit/',
    sourceType: 'automation_run_58_public_research',
    country: 'Canada / Alberta / Calgary campus-community radio',
    language: 'en',
    genres: ['cjsw', 'campus-radio', 'community-radio', 'calgary', 'radio-airplay', 'independent', 'electronic', 'world', 'reggae', 'mp3', 'external-form', 'release-window', 'no-singles', 'manual-review'],
    submissionMethod: 'official-public-cjsw-digital-only-music-submissions-page-linking-to-external-form-route',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'CJSW publishes an official digital-only music submissions page; human review is required because the route uses an external form workflow and requires MP3 ZIP packaging, albums released within the last three months, at least three unique tracks, no singles, metadata, rights and station-fit checks.',
    notes: 'Public research confirmed active CJSW 2026 news and chart content plus the official Music Submissions page. The redacted director contact display was not used and no route action was taken.'
  },
  {
    name: 'Three D Radio Adelaide Submit Your Music',
    websiteUrl: 'https://threedradio.com/',
    submissionUrl: 'https://threedradio.com/get-involved-page/submit-your-music/',
    sourceUrl: 'https://threedradio.com/get-involved-page/submit-your-music/',
    sourceType: 'automation_run_58_public_research',
    country: 'Australia / South Australia / Adelaide community radio',
    language: 'en',
    genres: ['three-d-radio', 'community-radio', 'adelaide', 'south-australia', 'radio-airplay', 'local-priority', 'independent', 'electronic', 'dub', 'reggae', 'world', 'mp3', 'web-form', 'physical-mail', 'manual-review'],
    submissionMethod: 'official-public-three-d-radio-new-music-submission-form-plus-physical-mail-and-dropoff-route',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Three D Radio publishes official digital and physical music submission instructions; human review is required because the route involves a new-music submission form, MP3 file requirements, physical mail or drop-off alternatives, local-priority assessment, metadata, rights and announcer-fit review.',
    notes: 'Public research confirmed active Three D Radio 2026 site and chart content plus the official Submit Your Music page. No route action was taken.'
  },
  {
    name: 'CFUV 101.9FM Victoria Music Submissions',
    websiteUrl: 'https://cfuv.uvic.ca/',
    submissionUrl: 'https://cfuv.uvic.ca/music-submissions/',
    sourceUrl: 'https://cfuv.uvic.ca/music-submissions/',
    sourceType: 'automation_run_58_public_research',
    country: 'Canada / British Columbia / Victoria campus-community radio',
    language: 'en',
    genres: ['cfuv', 'campus-radio', 'community-radio', 'victoria', 'radio-airplay', 'independent', 'electronic', 'world', 'reggae', 'mp3-320', 'download-link', 'music-director', 'physical-local-only', 'manual-review'],
    submissionMethod: 'official-public-cfuv-music-director-route-with-digital-download-link-and-local-physical-exception',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'CFUV publishes official Music Director submission instructions; human review is required because the route requires digital package preparation, at least three unique tracks, 320kbps MP3s, one-sheet metadata, local-only physical exceptions, content and format review and DJ/program fit checks.',
    notes: 'Public research confirmed the official CFUV Music Submissions page and public Music Director route. No route action was taken and live SMTP/MX probing was not performed.'
  },
  {
    name: 'CJSR 88.5FM Edmonton Submit Music',
    websiteUrl: 'https://www.cjsr.com/',
    submissionUrl: 'https://www.cjsr.com/submit-music/',
    sourceUrl: 'https://www.cjsr.com/submit-music/',
    sourceType: 'automation_run_58_public_research',
    country: 'Canada / Alberta / Edmonton campus-community radio',
    language: 'en',
    genres: ['cjsr', 'campus-radio', 'community-radio', 'edmonton', 'radio-airplay', 'independent', 'folktronica', 'electronic', 'world', 'reggae', 'digital-album', 'physical-mail', 'manual-review'],
    submissionMethod: 'official-public-cjsr-music-department-physical-and-digital-album-ep-submission-route',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'CJSR publishes an official Submit Music page; human review is required because the route allows physical mail/drop-off or digital album/EP delivery, requires album/EP rather than singles, non-expiring file access, metadata, language warnings, track lengths and DJ-fit review.',
    notes: 'Public research confirmed active CJSR 2026 chart/news content and the official Submit Music page. No route action was taken and no paid advertising option was used.'
  }
];
