import type { PlatformInput } from '../models/types.js';

export const run50SeedPlatforms: PlatformInput[] = [
  {
    name: 'CJSF 90.1FM Burnaby Music CD Submissions',
    websiteUrl: 'https://www.cjsf.ca/',
    submissionUrl: 'https://www.cjsf.ca/contact-us/submission',
    sourceUrl: 'https://www.cjsf.ca/contact-us/submission',
    sourceType: 'automation_run_50_public_research',
    country: 'Canada / Burnaby campus-community radio',
    language: 'en',
    genres: ['campus-radio', 'community-radio', 'independent', 'college-radio', 'electronic', 'indie', 'world', 'reggae', 'alternative', 'radio-airplay', 'music-coordinator-route', 'email-submission', 'physical-submission'],
    submissionMethod: 'official-public-music-coordinator-email-and-physical-cd-submission-route',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official CJSF Submissions page routes music directly to the Music Coordinator by email or mail, but human review is required for physical-versus-digital routing, metadata, release format, rights, radio clean/explicit status, station fit and avoiding any outreach before Mailgun/SMTP validation.',
    notes: 'Official CJSF page lists Music CD Submissions with Music Coordinator mailing details and the public cjsfmusc@sfu.ca route. No email, file link or physical package was sent.'
  },
  {
    name: 'CHLY 101.7FM Nanaimo Submit Your Music',
    websiteUrl: 'https://www.chly.ca/',
    submissionUrl: 'https://www.chly.ca/submissions',
    sourceUrl: 'https://www.chly.ca/submissions',
    sourceType: 'automation_run_50_public_research',
    country: 'Canada / Nanaimo community radio',
    language: 'en',
    genres: ['community-radio', 'campus-radio', 'independent', 'freeform-radio', 'electronic', 'reggae', 'world', 'alternative', 'radio-airplay', 'digital-submission', 'physical-submission', 'submission-form'],
    submissionMethod: 'official-public-submit-music-form-with-digital-and-physical-submission-guidelines',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official CHLY Submit your Music page accepts physical and digital submissions, but human review is required for the public form workflow, high-quality MP3/AAC requirements, no-AI policy, explicit-language flags, local/CANCON/FemCon/QueerCon/Indigicon/FrancoCon/AfroCon metadata, rights and library-fit review.',
    notes: 'Official CHLY page states music sent without the form receives lower priority, lists music@chly.ca for issues, and explains physical and digital routes. No form was submitted, no upload was made and no email was sent.'
  },
  {
    name: 'CFRU 93.3FM Guelph Music Department Submissions',
    websiteUrl: 'https://www.cfru.ca/',
    submissionUrl: 'https://www.cfru.ca/music/',
    sourceUrl: 'https://www.cfru.ca/music/',
    sourceType: 'automation_run_50_public_research',
    country: 'Canada / Guelph campus-community radio',
    language: 'en',
    genres: ['campus-radio', 'community-radio', 'independent', 'electronic', 'drum-and-bass', 'reggae', 'world', 'hip-hop', 'alternative', 'radio-airplay', 'music-director-route', 'email-submission', 'local-form'],
    submissionMethod: 'official-public-music-director-download-link-route-with-local-music-submission-form',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official CFRU Music page accepts EP or album submissions via download links to the Music Director address and also exposes a local-only form; human review is required for album/EP minimum-track eligibility, local-versus-nonlocal routing, download-link packaging, metadata, rights and radio/station fit.',
    notes: 'Official CFRU page says submissions should be EPs or albums with at least three songs, include artist/album/contact info and send download links to music@cfru.ca. No email, local form, upload or download link was submitted.'
  },
  {
    name: 'CKUT 90.3FM Montreal Submit Music',
    websiteUrl: 'https://ckut.ca/',
    submissionUrl: 'https://ckut.ca/submit-music-to-ckut/',
    sourceUrl: 'https://ckut.ca/submit-music-to-ckut/',
    sourceType: 'automation_run_50_public_research',
    country: 'Canada / Montreal campus-community radio',
    language: 'en',
    genres: ['campus-radio', 'community-radio', 'freeform-radio', 'independent', 'electronic', 'techno', 'house', 'reggae', 'soca', 'dancehall', 'global', 'experimental', 'radio-airplay', 'email-submission', 'physical-submission'],
    submissionMethod: 'official-public-music-department-email-and-physical-media-route-with-no-singles-policy',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official CKUT Submit Music page accepts physical media and 320 MP3 digital submissions, but human review is required for the no-singles and minimum-three-distinct-tracks rules, physical-versus-digital routing, library criteria, metadata, rights, programmer-fit and clean/explicit status.',
    notes: 'Official CKUT page says DJs choose music from recordings sent by artists/labels, physical releases may get more attention, and digital submissions can go to music@ckut.ca. No email, file link, upload or physical package was sent.'
  },
  {
    name: 'CJAM 99.1FM Windsor Digital Music Submissions',
    websiteUrl: 'https://www.cjam.ca/',
    submissionUrl: 'https://www.cjam.ca/submit/',
    sourceUrl: 'https://www.cjam.ca/submit/',
    sourceType: 'automation_run_50_public_research',
    country: 'Canada / Windsor-Detroit campus-community radio',
    language: 'en',
    genres: ['campus-radio', 'community-radio', 'independent', 'electronic', 'top-30', 'jazz', 'loud', 'alternative', 'radio-airplay', 'music-director-route', 'email-submission', 'digital-only'],
    submissionMethod: 'official-public-digital-only-music-director-email-route-with-download-link-requirements',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official CJAM Submit page has moved to digital-only submissions, but human review is required for the four-or-more-original-tracks rule, no-Spotify-links requirement, download-link preparation, ID3 metadata, EPK/release info, rights, file quality and station fit.',
    notes: 'Official CJAM Submit page lists cjammd@gmail.com for artist and album information with a download link, requires 4+ songs and warns not to send Spotify links or direct MP3 attachments. No email or download link was sent.'
  }
];
