import type { PlatformInput } from '../models/types.js';

export const run51SeedPlatforms: PlatformInput[] = [
  {
    name: 'KEXP Seattle Music Director Airplay Consideration',
    websiteUrl: 'https://www.kexp.org/',
    submissionUrl: 'https://www.kexp.org/about/submission-guidelines/',
    sourceUrl: 'https://www.kexp.org/about/submission-guidelines/',
    sourceType: 'automation_run_51_public_research',
    country: 'United States / Seattle and Bay Area public radio',
    language: 'en',
    genres: ['public-radio', 'noncommercial-radio', 'independent', 'eclectic', 'electronic', 'world', 'reggae', 'latin', 'afrobeat', 'ambient', 'hip-hop', 'radio-airplay', 'music-director-route', 'email-submission', 'download-link'],
    submissionMethod: 'official-public-music-director-email-route-with-digital-download-guidelines',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official KEXP Submission Guidelines route music to the Music Director address for airplay consideration, but human review is required for freeform email outreach, streaming and downloadable WAV link preparation, release metadata, clean radio edits and lyric review, rights verification, DJ/show targeting, station fit and contact validation before any Mailgun/SMTP-verified outreach.',
    notes: 'Official KEXP contact and Submission Guidelines pages list md@kexp.org for rotation consideration, recommend streaming links and downloadable WAV files, and explicitly reject pay-to-play. No email, file link, upload or physical package was sent.'
  },
  {
    name: 'WXPN 88.5 Music Director and Local Show Submissions',
    websiteUrl: 'https://xpn.org/',
    submissionUrl: 'https://xpn.org/contact/',
    sourceUrl: 'https://xpn.org/contact/',
    sourceType: 'automation_run_51_public_research',
    country: 'United States / Philadelphia non-commercial AAA radio',
    language: 'en',
    genres: ['public-radio', 'noncommercial-radio', 'adult-album-alternative', 'independent', 'electronic', 'world', 'reggae', 'folk', 'local-music', 'radio-airplay', 'music-director-route', 'email-submission', 'download-link'],
    submissionMethod: 'official-public-music-director-and-local-show-email-download-link-route',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official WXPN Contact page provides Music Director and Local Show email routes for airplay consideration, but human review is required for EPK completeness, digital download-link packaging, local-versus-station-wide routing, WAV/high-quality MP3 checks, rights, release metadata, radio clean/explicit status and fit for WXPN programming.',
    notes: 'Official WXPN page asks artists to send an EPK with a digitally downloadable music link for Music Director review, and separate WAV/high-quality MP3 download links for The Local Show. No mailto address was decoded or extracted, and no email or file link was sent.'
  },
  {
    name: 'KALX 90.7FM Berkeley Physical Music Submissions',
    websiteUrl: 'https://kalx.berkeley.edu/',
    submissionUrl: 'https://kalx.berkeley.edu/about/contact/',
    sourceUrl: 'https://kalx.berkeley.edu/about/contact/',
    sourceType: 'automation_run_51_public_research',
    country: 'United States / Berkeley college-community radio',
    language: 'en',
    genres: ['college-radio', 'community-radio', 'freeform-radio', 'independent', 'electronic', 'experimental', 'world', 'reggae', 'radio-airplay', 'music-director-route', 'physical-submission', 'no-digital-submissions'],
    submissionMethod: 'official-public-physical-cd-lp-music-director-route-with-no-digital-submissions-policy',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official KALX Contact page accepts only physical professionally pressed CDs or LPs for airplay consideration and rejects downloads, file transfers, Bandcamp or Spotify links, YouTube links, CD-Rs and other digital forms; human review is required for physical-media preparation, mailing, metadata, rights, station fit and clean/explicit status.',
    notes: 'Official KALX page lists music@kalx.berkeley.edu and a physical Music Directors mailing route. No email, digital file link, physical package or mail action was sent.'
  },
  {
    name: 'UKF / Pilot Submit Your Demo',
    websiteUrl: 'https://ukf.com/',
    submissionUrl: 'https://ukf.com/submit-your-demo/',
    sourceUrl: 'https://ukf.com/submit-your-demo/',
    sourceType: 'automation_run_51_public_research',
    country: 'United Kingdom / global bass music label and promotional channel',
    language: 'en',
    genres: ['bass-music', 'dubstep', 'drum-and-bass', 'electronic', 'label-demo', 'music-promotion', 'ukf', 'pilot', 'demo-submission', 'submission-form', 'rights-review'],
    submissionMethod: 'official-public-demo-submission-form-for-ukf-or-pilot-release-consideration',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official UKF Submit Your Demo page requests the embedded public demo form for UKF or Pilot release consideration and warns not to send demos to the support address; human review is required for form workflow, track upload/link handling, bass-genre fit, rightsholder/licensing distinction, metadata, release-readiness and no-support-email compliance.',
    notes: 'Official UKF demo page exposes a public demo-submission form and clarifies UKF/Pilot release consideration. No form was submitted, no account was created, no upload was made and no support email was contacted.'
  },
  {
    name: 'KFAI Minneapolis Music Department and Music Library',
    websiteUrl: 'https://kfai.org/',
    submissionUrl: 'https://kfai.org/about/contact/',
    sourceUrl: 'https://kfai.org/about/contact/',
    sourceType: 'automation_run_51_public_research',
    country: 'United States / Minneapolis-Saint Paul community radio',
    language: 'en',
    genres: ['community-radio', 'public-radio', 'freeform-radio', 'independent', 'world', 'reggae', 'electronic', 'multicultural', 'radio-airplay', 'music-library-route', 'email-submission', 'manual-contact-route'],
    submissionMethod: 'official-public-music-department-and-music-library-contact-route',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official KFAI Contact page says artists can share music with the KFAI Music Department and Music Library by email, but the visible address is protected/redacted in the page extraction and human review is required for authorized-contact handling, email validation, metadata, rights, diverse-programming fit, file/link preparation and clean/explicit status.',
    notes: 'Official KFAI Contact page lists a Music Department & Music Library route for artists who want to share music. The rendered email was protected/redacted and was not decoded or guessed. No email, file link, upload, form or physical package was sent.'
  }
];
