import type { PlatformInput } from '../models/types.js';

export const run54SeedPlatforms: PlatformInput[] = [
  {
    name: 'WRSU 88.7FM Rutgers Music Director Submissions',
    websiteUrl: 'https://wrsu.org/',
    submissionUrl: 'https://wrsu.org/contact-us/',
    sourceUrl: 'https://wrsu.org/contact-us/',
    sourceType: 'automation_run_54_public_research',
    country: 'United States / New Brunswick college radio',
    language: 'en',
    genres: ['college-radio', 'student-radio', 'freeform-radio', 'independent', 'local-music', 'live-local-music', 'electronic', 'world', 'reggae', 'hip-hop', 'radio-airplay', 'music-director-route', 'email-submission', 'physical-mail'],
    submissionMethod: 'official-public-music-director-email-and-snail-mail-route-for-artist-label-promoter-submissions',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official WRSU Contact Us page says artist, label and promoter submissions should be sent exclusively to the Music Director; human review is required for email contact action, music-link or file packaging, metadata, rights, clean/explicit status, local/live-show fit, station fit and public-contact validation before any outreach.',
    notes: 'Official WRSU pages show active 2026 station/music content and list music@wrsu.org for the 2025-2026 Music Directors. No email, upload, form or physical mail was sent.'
  },
  {
    name: 'WHUS 91.7FM UConn New Music Committee',
    websiteUrl: 'https://whus.org/',
    submissionUrl: 'https://whus.org/new-music-committee/',
    sourceUrl: 'https://whus.org/new-music-committee/',
    sourceType: 'automation_run_54_public_research',
    country: 'United States / Storrs college-community radio',
    language: 'en',
    genres: ['college-radio', 'community-radio', 'freeform-radio', 'independent', 'new-music', 'album-review', 'promoter-submissions', 'electronic', 'world', 'reggae', 'hip-hop', 'radio-airplay', 'new-music-committee', 'music-director-route', 'email-submission'],
    submissionMethod: 'official-public-new-music-committee-and-music-director-email-route-for-promoter-album-review',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official WHUS New Music Committee page says the committee listens to brand new releases and reviews albums sent by promoters, and routes music-department contact to the Music Director; human review is required for email contact action, album-versus-single fit, metadata, rights, clean/explicit status, station fit and contact validation before any outreach.',
    notes: 'Official WHUS pages show active 2026 station content and list musicdirector@whus.org for the Music Director. No email, file link, upload or form was sent.'
  },
  {
    name: 'WESU 88.1FM Middletown Music Directors',
    websiteUrl: 'https://www.wesufm.org/',
    submissionUrl: 'https://www.wesufm.org/contact-us/',
    sourceUrl: 'https://www.wesufm.org/contact-us/',
    sourceType: 'automation_run_54_public_research',
    country: 'United States / Middletown college-community radio',
    language: 'en',
    genres: ['college-radio', 'community-radio', 'freeform-radio', 'independent', 'new-music', 'music-director-route', 'electronic', 'world', 'reggae', 'hip-hop', 'radio-airplay', 'email-submission', 'streaming-link', 'download-link'],
    submissionMethod: 'official-public-music-director-email-route-for-station-music-submissions-with-links-only-instruction',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official WESU Contact Us page explicitly instructs artists who want to submit music to contact the Music Directors and says to send links rather than attached files; human review is required for link preparation, no-attachment compliance, metadata, rights, clean/explicit status, station fit and public-contact validation before any outreach.',
    notes: 'Official WESU site shows active 2026 station posts and lists wesumd@wesufm.org for music submissions. No email, upload, form submission or file attachment was sent.'
  },
  {
    name: 'WXYC 89.3FM UNC Music Department',
    websiteUrl: 'https://wxyc.org/',
    submissionUrl: 'https://wxyc.org/',
    sourceUrl: 'https://wxyc.org/',
    sourceType: 'automation_run_54_public_research',
    country: 'United States / Chapel Hill student freeform radio',
    language: 'en',
    genres: ['college-radio', 'student-radio', 'freeform-radio', 'independent', 'eclectic', 'local-music', 'newly-released-music', 'electronic', 'world', 'reggae', 'dancehall', 'hip-hop', 'radio-airplay', 'music-department-route', 'physical-mail', 'email-contact'],
    submissionMethod: 'official-public-music-department-mailing-address-and-station-contact-route-for-freeform-radio-consideration',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official WXYC site identifies the station as UNC-Chapel Hill student-run freeform radio and publishes a WXYC Music Department mailing route plus general station contact; human review is required for physical-versus-email routing, package preparation, metadata, rights, clean/explicit status, station fit and contact validation before any outreach or mailing.',
    notes: 'Official WXYC site shows active Spring 2026 programming/blog activity and publishes info@wxyc.org plus a Music Department mailing address. No email, upload, form or physical mail was sent.'
  },
  {
    name: 'WUOG 90.5FM Athens Submit Music',
    websiteUrl: 'https://wuog.org/',
    submissionUrl: 'https://wuog.org/contact/',
    sourceUrl: 'https://wuog.org/contact/',
    sourceType: 'automation_run_54_public_research',
    country: 'United States / Athens college radio',
    language: 'en',
    genres: ['college-radio', 'student-radio', 'alternative-media', 'independent', 'local-music', 'smaller-artists', 'album-consideration', 'electronic', 'world', 'reggae', 'hip-hop', 'radio-airplay', 'music-director-route', 'local-music-director-route', 'physical-mail', 'email-submission'],
    submissionMethod: 'official-public-submit-music-route-with-music-director-and-local-music-director-review',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Official WUOG Contact page has a Submit Music section for album airplay consideration by Music Directors and Local Music Directors, with physical mail and public director email routes; human review is required for album/package selection, physical-versus-email routing, metadata, rights, eligibility against WUOG airtime rules, clean/explicit status and station fit before any outreach or mailing.',
    notes: 'Official WUOG site shows active 2025 music posts and says music directors review submitted albums for airtime consideration. Public music-director and local-music-director routes were observed. No email, upload, form or physical mail was sent.'
  }
];
