import type { PlatformInput } from '../models/types.js';

export const run56SeedPlatforms: PlatformInput[] = [
  {
    name: 'KRCL 90.9FM Salt Lake City How to Submit Music',
    websiteUrl: 'https://krcl.org/',
    submissionUrl: 'https://krcl.org/about/how-to-submit-music/',
    sourceUrl: 'https://krcl.org/about/how-to-submit-music/',
    sourceType: 'automation_run_56_public_research',
    country: 'United States / Utah / community radio',
    language: 'en',
    genres: ['krcl', 'community-radio', 'radio-airplay', 'utah-local-music', 'independent', 'electronic', 'world', 'reggae', 'folk', 'americana', 'physical-mail', 'google-form', 'local-restriction', 'manual-review'],
    submissionMethod: 'official-public-krcl-music-department-submission-route-with-physical-cd-and-utah-local-google-form-digital-options',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'KRCL publishes official instructions for submitting music to the station; human review is required because physical CD submissions, the Utah-local Google Form upload route, no-demo/no-CD-R restrictions, station/DJ fit, release metadata and ownership/rights packaging must be checked before any action.',
    notes: 'Public research confirmed an active KRCL how-to-submit-music page with physical Music Department mailing instructions and a digital local-music Google Form. No Google Form was opened for submission, no upload was performed and no physical mail was sent.'
  },
  {
    name: 'Radio Milwaukee 88Nine Music Submission',
    websiteUrl: 'https://radiomilwaukee.org/',
    submissionUrl: 'https://radiomilwaukee.org/music-submission',
    sourceUrl: 'https://radiomilwaukee.org/music-submission',
    sourceType: 'automation_run_56_public_research',
    country: 'United States / Wisconsin / public radio',
    language: 'en',
    genres: ['radio-milwaukee', 'public-radio', 'radio-airplay', 'independent', 'local-music', 'electronic', 'hip-hop', 'world', 'reggae', 'wav-required', 'radio-edit', 'manual-review'],
    submissionMethod: 'official-public-radio-milwaukee-music-submission-guidelines-for-digital-wav-review',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Radio Milwaukee publishes official music-submission requirements; human review is required for WAV-preferred audio, radio edits for explicit tracks, lyrics and artist-info document preparation, no-physical-media restriction, rights/metadata checks and station fit before any submission.',
    notes: 'Public research confirmed the official Radio Milwaukee music-submission page and recent 2026 site activity. No files, links, form entries or emails were sent.'
  },
  {
    name: 'WNXP 91.1FM Nashville Music Submissions',
    websiteUrl: 'https://wnxp.org/',
    submissionUrl: 'https://wnxp.org/music-submissions/',
    sourceUrl: 'https://wnxp.org/music-submissions/',
    sourceType: 'automation_run_56_public_research',
    country: 'United States / Tennessee / public music-discovery radio',
    language: 'en',
    genres: ['wnxp', 'nashville', 'public-radio', 'radio-airplay', 'music-discovery', 'independent', 'electronic', 'alternative', 'world', 'reggae', 'clean-edit', 'wav-required', 'email-route', 'manual-review'],
    submissionMethod: 'official-public-wnxp-email-route-for-clean-mastered-wav-download-link-airplay-consideration',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'WNXP publishes an official music-submissions email route; human review is required because the station asks for a download link to a clean mastered 44.1k/16-bit stereo WAV, excludes MP3s, applies genre/station-fit judgement and emphasizes but does not limit itself to Nashville artists.',
    notes: 'Public research confirmed active WNXP site programming and the public submissions@wnxp.org music route. No email was sent and no audio link was shared; live SMTP/MX probing was not performed.'
  },
  {
    name: 'KGNU Community Radio Contact Staff or DJ Music Department',
    websiteUrl: 'https://kgnu.org/',
    submissionUrl: 'https://kgnu.org/contact-us/',
    sourceUrl: 'https://kgnu.org/contact-us/',
    sourceType: 'automation_run_56_public_research',
    country: 'United States / Colorado / community radio',
    language: 'en',
    genres: ['kgnu', 'community-radio', 'radio-airplay', 'dj-contact', 'music-department', 'independent', 'local-music', 'electronic', 'world', 'reggae', 'bluegrass', 'contact-form', 'recaptcha', 'manual-review'],
    submissionMethod: 'official-public-kgnu-contact-staff-or-dj-form-with-music-department-option-for-manual-station-fit-routing',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'KGNU publishes a public Contact Staff or DJ form with a Music department option; human review is required because the route is a general contact form, uses reCaptcha v3, requires careful music-department/DJ routing and must not be submitted automatically.',
    notes: 'Public research confirmed active 2026 KGNU music pages, recent playlists and a contact form that includes Music as a department. No form was submitted, no reCaptcha was bypassed and no protected contacts were decoded.'
  },
  {
    name: 'WFUV New York Send Music to Music Department',
    websiteUrl: 'https://wfuv.org/',
    submissionUrl: 'https://wfuv.org/contactus',
    sourceUrl: 'https://wfuv.org/contactus',
    sourceType: 'automation_run_56_public_research',
    country: 'United States / New York / public radio',
    language: 'en',
    genres: ['wfuv', 'public-radio', 'music-discovery', 'radio-airplay', 'independent', 'aaa', 'world', 'reggae', 'electronic', 'snail-mail', 'music-department', 'physical-mail', 'manual-review'],
    submissionMethod: 'official-public-wfuv-send-music-snail-mail-route-to-music-department',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'WFUV publishes an official Send Music instruction to snail-mail music to the Music Department; human review is required for physical-package preparation, rights/metadata, station fit, follow-up call timing and because no physical mail or phone workflow may be automated.',
    notes: 'Public research confirmed active WFUV 2026 programming and the official Contact and Staff page with Send Music instructions. No physical mail, call, email or form submission was attempted.'
  }
];
