import type { PlatformInput } from '../models/types.js';

export const run57SeedPlatforms: PlatformInput[] = [
  {
    name: 'WERS 88.9FM Wicked Local Wednesday Submit Music',
    websiteUrl: 'https://wers.org/',
    submissionUrl: 'https://wers.org/wicked-local-wednesday/',
    sourceUrl: 'https://wers.org/wicked-local-wednesday/',
    sourceType: 'automation_run_57_public_research',
    country: 'United States / Massachusetts / Boston local radio',
    language: 'en',
    genres: ['wers', 'wicked-local-wednesday', 'local-radio', 'boston-area', 'radio-airplay', 'independent', 'electronic', 'alternative', 'world', 'reggae', 'mp3-upload', 'local-restriction', 'recaptcha', 'manual-review'],
    submissionMethod: 'official-public-wers-wicked-local-wednesday-local-artist-upload-form-for-boston-area-airplay-consideration',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'WERS publishes an official Wicked Local Wednesday music submission form for Boston-area artists; human review is required because the route is local-only, includes MP3 file upload fields, contact fields and site reCAPTCHA protection, and requires station/local-fit, rights and metadata review before any form action.',
    notes: 'Public research confirmed active WERS 2026 music posts and the official Wicked Local Wednesday Submit Your Music form. No form was submitted, no files were uploaded and no reCAPTCHA or validation control was bypassed.'
  },
  {
    name: 'KBOO Portland Submit Your Music',
    websiteUrl: 'https://kboo.fm/',
    submissionUrl: 'https://kboo.fm/submit-your-music',
    sourceUrl: 'https://kboo.fm/submit-your-music',
    sourceType: 'automation_run_57_public_research',
    country: 'United States / Oregon / community radio',
    language: 'en',
    genres: ['kboo', 'community-radio', 'radio-airplay', 'portland', 'independent', 'electronic', 'world', 'reggae', 'hip-hop', 'physical-mail', 'genre-routing', 'manual-review'],
    submissionMethod: 'official-public-kboo-physical-music-submission-route-with-genre-specific-programmer-routing',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'KBOO publishes an official Submit Your Music page; human review is required because the station says it does not yet have a digital library, asks for mailed physical submissions, requires genre-specific addressee routing, notes submissions become station property and leaves airplay/program fit to DJs.',
    notes: 'Public research confirmed active KBOO recent audio/playlists and the official physical mail route for submissions. No physical mail, phone call, email, upload or form submission was attempted.'
  },
  {
    name: 'CKUA Radio Getting Airplay',
    websiteUrl: 'https://ckua.com/',
    submissionUrl: 'https://ckua.com/our-story/library/getting-airplay/',
    sourceUrl: 'https://ckua.com/our-story/library/getting-airplay/',
    sourceType: 'automation_run_57_public_research',
    country: 'Canada / Alberta / community radio network',
    language: 'en',
    genres: ['ckua', 'community-radio', 'radio-airplay', 'canadian-artists', 'albertan-artists', 'independent', 'experimental-pop', 'world', 'reggae', 'electronic', 'clean-edit', 'download-link', 'music-committee', 'manual-review'],
    submissionMethod: 'official-public-ckua-digital-submission-route-with-music-committee-review-and-clean-radio-edit-requirements',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'CKUA publishes official Getting Airplay instructions; human review is required for the Send it Now email route, one-sheet/bio/website packaging, clean/radio-edit assessment, 320kbps download-link preparation, no-zip/no-large-attachment rule, program-host targeting and Music Committee fit review.',
    notes: 'Public research confirmed active CKUA 2026 site content and the official Getting Airplay page. No email was sent, no host was contacted, no physical mail was sent and live SMTP/MX probing was not performed.'
  },
  {
    name: 'PBS 106.7FM Melbourne Submit Your Music',
    websiteUrl: 'https://www.pbsfm.org.au/',
    submissionUrl: 'https://www.pbsfm.org.au/submitmusic',
    sourceUrl: 'https://www.pbsfm.org.au/submitmusic',
    sourceType: 'automation_run_57_public_research',
    country: 'Australia / Victoria / Melbourne community radio',
    language: 'en',
    genres: ['pbs-1067fm', 'community-radio', 'melbourne', 'radio-airplay', 'local-and-international', 'independent', 'electronic', 'dub', 'reggae', 'world', 'music-stream', 'download-link', 'captcha', 'physical-mail', 'manual-review'],
    submissionMethod: 'official-public-pbs-fm-digital-submission-form-plus-cd-vinyl-physical-route-for-airplay-consideration',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'PBS publishes an official Submit Your Music route for local and international acts; human review is required because the page contains a digital form with CAPTCHA, social/biography/location fields, no-Spotify/no-Deezer stream restriction, high-quality download-link requirements, optional eNews consent and physical CD/vinyl routing.',
    notes: 'Public research confirmed active PBS 2026 programming and the official Submit Your Music page. No form was submitted, no download or stream link was shared, no CAPTCHA was bypassed and no physical copy was sent.'
  },
  {
    name: '4ZZZ Brisbane Music Submissions',
    websiteUrl: 'https://4zzz.org.au/',
    submissionUrl: 'https://4zzz.org.au/music-submissions',
    sourceUrl: 'https://4zzz.org.au/music-submissions',
    sourceType: 'automation_run_57_public_research',
    country: 'Australia / Queensland / Brisbane community radio',
    language: 'en',
    genres: ['4zzz', 'community-radio', 'brisbane', 'radio-airplay', 'independent', 'local-communities', 'electronic', 'reggae', 'world', 'digital-library', 'downloadable-stream', 'external-form', 'album-of-the-week', 'manual-review'],
    submissionMethod: 'official-public-4zzz-music-department-submission-page-linking-to-external-js-form-for-digital-library-airplay-consideration',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: '4ZZZ publishes an official Music Submissions page; human review is required because the route links to an external JavaScript submission form, requires a downloadable music link rather than a non-downloadable stream, has Album of the Week/EP-album routing and leaves inclusion and announcer airplay to station judgement.',
    notes: 'Public research confirmed active 4ZZZ 2026 playlists/top-20 content and the official Music Submissions page. The external form was not submitted, no upload or music link was provided and no login, CAPTCHA or platform restriction was bypassed.'
  }
];
