import type { PlatformInput } from '../models/types.js';

export const run55SeedPlatforms: PlatformInput[] = [
  {
    name: 'BBC Music Introducing Uploader',
    websiteUrl: 'https://www.bbc.co.uk/introducing',
    submissionUrl: 'https://www.bbc.co.uk/music/introducing/uploader/',
    sourceUrl: 'https://www.bbc.co.uk/music/introducing/uploader/',
    sourceType: 'automation_run_55_public_research',
    country: 'United Kingdom / BBC new-music upload platform',
    language: 'en',
    genres: ['bbc', 'radio-airplay', 'new-music', 'unsigned-artists', 'independent', 'local-radio', 'electronic', 'dance', 'urban', 'world', 'reggae', 'festival-opportunities', 'upload-portal', 'account-required', 'manual-review'],
    submissionMethod: 'official-public-bbc-introducing-upload-portal-for-unsigned-under-the-radar-uk-music-talent',
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'BBC Music Introducing is an official BBC upload platform for unsigned and under-the-radar UK music talent; human review is required because the route uses an account/upload flow, postcode/local-show routing, UGC terms, eligibility checks, metadata, rights/originality assertions and possible BBC editorial routing before any submission.',
    notes: 'Public research confirmed the BBC Introducing upload-tool model and active platform status. No BBC account was created, no login wall was bypassed and no music was uploaded.'
  },
  {
    name: 'Amazing Radio Artist Uploads',
    websiteUrl: 'https://amazingradio.com/',
    submissionUrl: 'https://amazingradio.com/',
    sourceUrl: 'https://amazingradio.com/',
    sourceType: 'automation_run_55_public_research',
    country: 'United Kingdom / United States / global emerging-artist radio platform',
    language: 'en',
    genres: ['amazing-radio', 'internet-radio', 'emerging-artists', 'unsigned-artists', 'independent', 'new-music', 'electronic', 'pop', 'alternative', 'world', 'reggae', 'radio-airplay', 'artist-upload', 'account-required', 'manual-review'],
    submissionMethod: 'official-public-artist-upload-route-through-amazing-radio-website-for-emerging-artist-airplay-consideration',
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Amazing Radio is an official emerging-artist radio platform where artists submit through the website; human review is required for account/login flow, upload or track-link handling, rights/originality assertions, metadata, genre fit, territory fit and editorial airplay consideration before any submission.',
    notes: 'Public research confirmed the platform supports artist submissions via the Amazing Radio website and remains active across UK/US/global emerging-artist radio programming. No account, login, upload or submission action was attempted.'
  },
  {
    name: 'Triple J Unearthed Artist Upload Platform',
    websiteUrl: 'https://www.abc.net.au/triplejunearthed/',
    submissionUrl: 'https://www.abc.net.au/triplejunearthed/',
    sourceUrl: 'https://www.abc.net.au/triplejunearthed/',
    sourceType: 'automation_run_55_public_research',
    country: 'Australia / ABC independent Australian music platform',
    language: 'en',
    genres: ['triple-j', 'abc-radio', 'unearthed', 'independent-australian-music', 'unsigned-artists', 'electronic', 'dance', 'hip-hop', 'pop', 'radio-airplay', 'competition-opportunities', 'artist-upload', 'account-required', 'regional-restriction', 'manual-review'],
    submissionMethod: 'official-public-triple-j-unearthed-artist-upload-platform-for-independent-australian-music',
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Triple J Unearthed is an official ABC independent Australian music upload platform; human review is required because it is Australian-music focused and uses account/upload workflows, original-music eligibility, metadata, rights/originality checks, competition rules and editorial airplay consideration before any submission.',
    notes: 'Public research confirmed the platform exists for independent Australian music uploaded to the site and feeds Triple J Unearthed radio/discovery. No account was created and no upload or competition entry was attempted.'
  },
  {
    name: 'Audiomack Creator Upload Platform',
    websiteUrl: 'https://audiomack.com/',
    submissionUrl: 'https://audiomack.com/upload',
    sourceUrl: 'https://audiomack.com/',
    sourceType: 'automation_run_55_public_research',
    country: 'Global / creator upload and music discovery platform',
    language: 'en',
    genres: ['audiomack', 'streaming-platform', 'creator-upload', 'emerging-artists', 'independent', 'hip-hop', 'afrobeats', 'rnb', 'latin', 'electronic', 'world', 'reggae', 'charts', 'editorial-discovery', 'account-required', 'manual-review'],
    submissionMethod: 'official-public-creator-upload-route-for-direct-artist-music-hosting-and-discovery',
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Audiomack allows artists and users to upload music through its website/creator tooling; human review is required for account/login flow, upload action, rights/originality assertions, metadata, clean/explicit flags, content-policy review and any promotion/monetization choices before use.',
    notes: 'Public research confirmed active Audiomack creator upload support, free creator storage and ongoing platform activity. No account, login, upload, promotional action or monetization enrollment was attempted.'
  },
  {
    name: 'SoundOn Music Distribution and Artist Promotion',
    websiteUrl: 'https://www.soundon.global/',
    submissionUrl: 'https://www.soundon.global/',
    sourceUrl: 'https://www.soundon.global/',
    sourceType: 'automation_run_55_public_research',
    country: 'Multi-region / TikTok-powered artist distribution platform',
    language: 'en',
    genres: ['soundon', 'tiktok', 'music-distribution', 'artist-promotion', 'creator-upload', 'independent-artists', 'electronic', 'dance', 'pop', 'world', 'reggae', 'short-form-video', 'royalty-share', 'account-required', 'manual-review'],
    submissionMethod: 'official-public-soundon-artist-signup-and-music-distribution-route-for-tiktok-and-partner-platforms',
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'SoundOn is a TikTok-powered music distribution and artist-promotion route; human review is required for country availability, account/signup flow, distribution terms, royalty-share model, rights/originality assertions, metadata, release configuration, store/platform choices and payout/legal settings before any upload or release.',
    notes: 'Public research confirmed SoundOn is an active music marketing/distribution platform in multiple countries. No signup, login, upload, release creation, distribution action or payment/payout configuration was attempted.'
  }
];
