import type { PlatformInput } from '../models/types.js';

export const run59SeedPlatforms: PlatformInput[] = [
  {
    name: 'RTRFM 92.1 Perth Submit Your Music',
    websiteUrl: 'https://rtrfm.com.au/',
    submissionUrl: 'https://rtrfm.com.au/submit-your-music/',
    sourceUrl: 'https://rtrfm.com.au/submit-your-music/',
    sourceType: 'automation_run_59_public_research',
    country: 'Australia / Western Australia / Perth community radio',
    language: 'en',
    genres: ['rtrfm', 'community-radio', 'perth', 'radio-airplay', 'independent', 'electronic', 'dance', 'beats', 'world', 'reggae', 'web-form', 'download-link', 'physical-mail', 'manual-review'],
    submissionMethod: 'official-public-rtrfm-submit-your-music-web-form-plus-music-team-email-and-physical-copy-route',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'RTRFM publishes an official Submit Your Music form plus an email and physical-copy route; human review is required because the workflow includes public form completion, bio document upload, stream and free-download links, release timing, high-quality audio checks, metadata, rights/originality assertions, physical-copy handling and presenter/station-fit review.',
    notes: 'Public research confirmed active RTRFM 2026 stories, events and featured-music content plus the official Submit Your Music page. No route action was taken.'
  },
  {
    name: 'FBi Radio Sydney Music Submissions',
    websiteUrl: 'https://www.fbi.radio/',
    submissionUrl: 'https://www.fbi.radio/pages/music-submissions',
    sourceUrl: 'https://www.fbi.radio/pages/music-submissions',
    sourceType: 'automation_run_59_public_research',
    country: 'Australia / New South Wales / Sydney independent community radio',
    language: 'en',
    genres: ['fbi-radio', 'community-radio', 'sydney', 'radio-airplay', 'independent', 'electronic', 'dj', 'producer', 'world', 'reggae', 'playlist', 'download-link', 'email-route', 'manual-review'],
    submissionMethod: 'official-public-fbi-radio-music-director-email-route-for-digital-airplay-submissions',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'FBi Radio publishes official Music Submissions instructions; human review is required because the route requires email preparation with subject format, bio, press image, gig details, stream link, 320kbps MP3 or WAV free download link, Tuesday timing for weekly auditioning, direct-program routing choices, rights/originality checks and station-fit review.',
    notes: 'Public research confirmed active FBi 2026 episodes/articles and the official Music Submissions page. Paid promotional campaign information appears separately on the page but was not queued as an airplay-submission requirement.'
  },
  {
    name: 'Triple R 102.7FM Melbourne Submit Music',
    websiteUrl: 'https://www.rrr.org.au/',
    submissionUrl: 'https://www.rrr.org.au/get-involved/submit-music',
    sourceUrl: 'https://www.rrr.org.au/get-involved/submit-music',
    sourceType: 'automation_run_59_public_research',
    country: 'Australia / Victoria / Melbourne independent community radio',
    language: 'en',
    genres: ['triple-r', 'rrr', 'community-radio', 'melbourne', 'radio-airplay', 'independent', 'electronic', 'beats', 'hip-hop', 'world', 'reggae', 'email-route', 'physical-mail', 'manual-review'],
    submissionMethod: 'official-public-triple-r-station-service-email-route-plus-direct-presenter-and-physical-music-department-route',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Triple R publishes official Submit Music instructions; human review is required because the station is not playlisted and requires a choice between direct presenter servicing and station servicing, no-login stream links, 320kbps MP3 or WAV download links, file naming, bio/gig metadata, no large attachments, optional physical media and presenter-discretion fit review.',
    notes: 'Public research confirmed active Triple R 2026 site content, programs, events and the official Submit Music page. No route action was taken.'
  },
  {
    name: 'Edge Radio 99.3FM Hobart Submit Your Music',
    websiteUrl: 'https://www.edgeradio.org.au/',
    submissionUrl: 'https://www.edgeradio.org.au/submit-your-music/',
    sourceUrl: 'https://www.edgeradio.org.au/submit-your-music/',
    sourceType: 'automation_run_59_public_research',
    country: 'Australia / Tasmania / Hobart youth community radio',
    language: 'en',
    genres: ['edge-radio', 'community-radio', 'hobart', 'tasmania', 'youth-radio', 'radio-airplay', 'independent', 'electronic', 'world', 'reggae', 'download-link', 'physical-mail', 'manual-review'],
    submissionMethod: 'official-public-edge-radio-music-department-email-and-physical-copy-submission-route',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Edge Radio publishes official digital and physical music-submission instructions; human review is required because the route requires bio/gig metadata, stream link, high-quality download link in an accepted format, optional multiple CDs, Tasmanian-local subject marking only when eligible, physical package handling, rights/originality checks and Music Department fit review.',
    notes: 'Public research confirmed active Edge Radio 2026 site/social/news content and the official Submit Your Music page. Paid promotional campaign information appears separately on the page but was not queued as an airplay-submission requirement.'
  },
  {
    name: 'Radio Adelaide Submit Your Music',
    websiteUrl: 'https://www.radioadelaide.org.au/',
    submissionUrl: 'https://www.radioadelaide.org.au/submit-your-music/',
    sourceUrl: 'https://www.radioadelaide.org.au/submit-your-music/',
    sourceType: 'automation_run_59_public_research',
    country: 'Australia / South Australia / Adelaide community radio',
    language: 'en',
    genres: ['radio-adelaide', 'community-radio', 'adelaide', 'south-australia', 'radio-airplay', 'independent', 'electronic', 'jazz', 'folk', 'world', 'reggae', 'wav', 'download-link', 'manual-review'],
    submissionMethod: 'official-public-radio-adelaide-digital-music-enquiry-route-for-wav-or-cloud-link-submissions',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'Radio Adelaide publishes official Submit Your Music instructions; human review is required because the route requires email/cloud-link preparation, WAV preference with 44.1kHz stereo 16-bit specs, public Dropbox/Google Drive or WeTransfer setup, file naming, press/bio, stream links, upcoming Adelaide show details, South Australian local-priority marking, focus-track selection and program-fit review.',
    notes: 'Public research confirmed active Radio Adelaide 2026 broadcasts/stories and the official Submit Your Music page. No route action was taken.'
  }
];
