import type { PlatformInput } from '../models/types.js';

export const run67SeedPlatforms: PlatformInput[] = [
  {
    name: "A&R Factory Submit Your Music",
    websiteUrl: "https://www.anrfactory.com/",
    submissionUrl: "https://www.anrfactory.com/submit-demo/",
    sourceUrl: "https://www.anrfactory.com/submit-demo/",
    sourceType: "automation_run_67_public_research",
    country: "United Kingdom / global independent music blog and A&R-facing editorial platform",
    language: "en",
    genres: ["a-r-factory", "music-blog", "independent-artists", "electronic", "dance-edm", "drum-and-bass", "reggae", "world", "hip-hop", "pop", "rock", "one-track-review", "freemium", "manual-review"],
    submissionMethod: "official-a-r-factory-public-submit-your-music-form-with-free-standard-and-premium-editorial-review-package-options",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "A&R Factory provides a public multi-step submission form with a free option and optional paid Standard/Premium Donation packages; human review is required for one-track selection, release status/date, links/artwork/bio/EPK, budget/services fields, package choice, payment avoidance or approval, data-consent and editorial-fit assertions.",
    notes: "Public research confirmed the official Submit Your Music page, live form fields, broad genre/location acceptance, a Free Submission path, optional paid Standard/Premium paths and 2026 site copyright. No form was submitted, no payment path was entered, no email was sent and no SMTP/MX probe was performed."
  },
  {
    name: "WXPN Submit Music for Airplay",
    websiteUrl: "https://xpn.org/",
    submissionUrl: "https://xpn.org/submit-music/",
    sourceUrl: "https://xpn.org/submit-music/",
    sourceType: "automation_run_67_public_research",
    country: "United States / public AAA radio station and online music platform",
    language: "en",
    genres: ["wxpn", "radio-airplay", "aaa-radio", "public-radio", "independent-artists", "world-cafe-ecosystem", "form-submission", "free", "manual-review"],
    submissionMethod: "official-wxpn-submit-music-for-airplay-public-form-for-on-air-programming-consideration",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "WXPN provides an official public airplay consideration form; human review is required for form completion, track/link/package choice, clean metadata, rights/originality confirmation and station/programming fit before any submission.",
    notes: "Public research confirmed the official WXPN Submit Music for Airplay page, public form instructions and 2026 site copyright. No form was opened beyond public page inspection, no email was sent and no SMTP/MX probe was performed."
  },
  {
    name: "SomaFM Submit Music and Channel Music Director Contacts",
    websiteUrl: "https://somafm.com/",
    submissionUrl: "https://somafm.com/contact/",
    sourceUrl: "https://somafm.com/contact/",
    sourceType: "automation_run_67_public_research",
    country: "United States / global listener-supported internet radio network",
    language: "en",
    genres: ["somafm", "internet-radio", "electronic", "ambient", "dub", "reggae", "downtempo", "groove", "indie-pop", "channel-director-email", "free", "manual-review"],
    submissionMethod: "official-somafm-contact-route-with-submit-music-navigation-and-channel-specific-music-director-email-routing",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "SomaFM publishes channel-specific music director email routes and warns against mailing lists or duplicate emails; human review is required for choosing the right channel/director, preparing a targeted message, avoiding bulk outreach, rights/originality assertions and broadcast/channel fit.",
    notes: "Public research confirmed the official SomaFM contact page, Submit Music navigation, channel music director emails, anti-spam/no-duplicate-email instructions, a physical mailing address and 2000-2026 copyright. No email was sent, no mailing list was created, no physical mail was sent and no SMTP/MX probe was performed."
  },
  {
    name: "Radio Boise Submit Your Music",
    websiteUrl: "https://radioboise.org/",
    submissionUrl: "https://radioboise.org/support/submit-your-music/",
    sourceUrl: "https://radioboise.org/support/submit-your-music/",
    sourceType: "automation_run_67_public_research",
    country: "United States / Idaho community radio station with worldwide online listening",
    language: "en",
    genres: ["radio-boise", "community-radio", "radio-airplay", "independent-artists", "boise", "form-route", "free", "manual-review"],
    submissionMethod: "official-radio-boise-get-in-touch-submit-your-music-page-for-station-music-consideration",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Radio Boise exposes an official Submit Your Music route, but the public page content is JavaScript-loaded and displayed only as Loading during authorized inspection; human review is required to inspect the form safely, identify any CAPTCHA/login/upload fields, prepare metadata and confirm station fit without bypassing controls.",
    notes: "Public research confirmed Radio Boise's Get In Touch navigation includes Submit Your Music, the submit page is live, the station homepage shows 2026 activity and worldwide listening. The JS-loaded form was not interacted with, no controls were bypassed, no form was submitted, no email was sent and no SMTP/MX probe was performed."
  },
  {
    name: "RepostExchange SoundCloud Creator Promotion Campaigns",
    websiteUrl: "https://repostexchange.com/",
    submissionUrl: "https://repostexchange.com/welcome",
    sourceUrl: "https://repostexchange.com/welcome",
    sourceType: "automation_run_67_public_research",
    country: "United Kingdom / global SoundCloud creator promotion and feedback network",
    language: "en",
    genres: ["repostexchange", "soundcloud", "creator-promotion", "electronic", "edm", "deep-house", "trap", "hip-hop", "feedback", "credits", "freemium", "login-required", "manual-review"],
    submissionMethod: "official-repostexchange-connect-with-soundcloud-route-for-track-promotion-repost-requests-feedback-and-credit-based-campaigns",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "RepostExchange requires connecting a SoundCloud account and choosing tracks, credits, repost requests or campaigns; human review is required for OAuth/account access, permission scope, track selection, credit spend, optional paid boosts, platform rules and anti-bot/community-compliance boundaries.",
    notes: "Public research confirmed the official RepostExchange welcome route, Connect with SoundCloud workflow, free-to-use path, free credits, optional credits/plans, manual-permission claims, anti-fake-account policies and 2025 copyright. No account was connected, no campaign was created, no credits were spent, no action was automated and no SMTP/MX probe was performed."
  }
];