import type { PlatformInput } from '../models/types.js';

export const run62SeedPlatforms: PlatformInput[] = [
  {
    name: "WFMU Send Us Music",
    websiteUrl: "https://wfmu.org/",
    submissionUrl: "https://wfmu.org/sendmusic.html",
    sourceUrl: "https://wfmu.org/sendmusic.html",
    sourceType: "automation_run_62_public_research",
    country: "United States / global online freeform radio",
    language: "en",
    genres: ["wfmu", "freeform-radio", "college-radio", "independent", "experimental", "electronic", "world", "reggae", "physical-submissions", "music-director-review", "manual-review"],
    submissionMethod: "official-public-wfmu-send-us-music-physical-materials-route-for-music-director-review",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "WFMU publishes an official Send Us Music page for artists/labels to send review material to the Music Director by post; human review is required for deciding whether the release is appropriate for physical mailing, preparing package metadata, rights/originality notes, FCC/clean-language context and station-fit information, and because no physical mail should be sent automatically.",
    notes: "Public research confirmed an active WFMU site and official Send Us Music physical route. No email, form, file transfer, physical mail, payment or SMTP/MX probe was performed."
  },
  {
    name: "Bandcamp for Artists",
    websiteUrl: "https://bandcamp.com/",
    submissionUrl: "https://bandcamp.com/artists",
    sourceUrl: "https://bandcamp.com/artists",
    sourceType: "automation_run_62_public_research",
    country: "Global / direct-to-fan artist store and music community",
    language: "en",
    genres: ["bandcamp", "direct-to-fan", "artist-store", "independent", "electronic", "dance", "reggae", "world", "digital-music", "merch", "freemium", "login-route", "manual-review"],
    submissionMethod: "official-public-bandcamp-for-artists-signup-route-to-create-an-artist-store-and-release-digital-or-physical-music",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Bandcamp publishes an official Bandcamp for Artists route with free artist accounts, sign-up, store setup, pricing controls, optional Pro tier and revenue share; human review is required for account creation, catalog/upload choices, pricing, payout/tax setup, metadata, artwork, rights/originality and any Pro or paid-feature decisions.",
    notes: "Public research confirmed active Bandcamp for Artists content, sign-up route, free artist accounts, revenue-share pricing and optional Pro tier. No account, upload, release setup, payment or file transfer was attempted."
  },
  {
    name: "Jamendo Artists Services",
    websiteUrl: "https://www.jamendo.com/start",
    submissionUrl: "https://artists.jamendo.com/",
    sourceUrl: "https://artists.jamendo.com/",
    sourceType: "automation_run_62_public_research",
    country: "Global / Luxembourg independent artist and licensing platform",
    language: "en",
    genres: ["jamendo", "artist-services", "music-licensing", "sync-licensing", "in-store-placement", "content-id", "promotion", "independent", "electronic", "world", "reggae", "freemium", "login-route", "manual-review"],
    submissionMethod: "official-public-jamendo-artists-services-route-for-jamendo-music-licensing-in-store-content-id-and-promotion",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Jamendo publishes an official Artists Services route with sign-in/start-now flows for Jamendo Music, licensing, in-store placement, Content ID and promotion; human review is required for account access, upload/catalog selection, licensing opt-in/out choices, collecting-society/legal compatibility, metadata, rights/originality and monetization terms.",
    notes: "Public research confirmed active Jamendo Artists Services content, sign-in/start-now route and artist-service modules. No account, upload, license activation, payment or file transfer was attempted."
  },
  {
    name: "Newgrounds Audio Portal",
    websiteUrl: "https://www.newgrounds.com/audio",
    submissionUrl: "https://www.newgrounds.com/audio",
    sourceUrl: "https://www.newgrounds.com/audio",
    sourceType: "automation_run_62_public_research",
    country: "Global / creator community and audio portal",
    language: "en",
    genres: ["newgrounds", "audio-portal", "creator-community", "electronic", "dubstep", "drum-n-bass", "dance", "world", "experimental", "free-account", "manual-review"],
    submissionMethod: "official-public-newgrounds-audio-portal-free-account-route-for-music-audio-submissions-and-community-discovery",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Newgrounds exposes an active public Audio portal with login/sign-up, free-account prompts, current audio listings, category taxonomy and community discovery; human review is required for account creation, upload form handling, category/rating selection, rights/originality, explicit-content labeling and community/portal-fit checks.",
    notes: "Public research confirmed active 2026 Newgrounds Audio portal content, account route and genre categories including electronic, dance, drum n bass, dubstep and world. No login, upload, form submission, payment or file transfer was attempted."
  },
  {
    name: "SoundCloud Upload Your Music",
    websiteUrl: "https://soundcloud.com/",
    submissionUrl: "https://soundcloud.com/upload",
    sourceUrl: "https://soundcloud.com/upload",
    sourceType: "automation_run_62_public_research",
    country: "Global / creator upload and audio sharing platform",
    language: "en",
    genres: ["soundcloud", "creator-upload", "music-sharing", "independent", "electronic", "dance", "reggae", "world", "free-uploads", "pro-plans", "login-route", "manual-review"],
    submissionMethod: "official-public-soundcloud-upload-route-with-free-track-upload-and-optional-pro-plan-upgrade",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "SoundCloud publishes an official upload route with a free first-track CTA, 180 minutes of free uploads and optional Pro plans; human review is required for account/login, audio upload, metadata, artwork, public/private settings, rights/originality, explicit/content settings and optional paid-plan decisions.",
    notes: "Public research confirmed active SoundCloud upload page content, free upload allowance and optional Pro plan route. No account, upload, form submission, payment or file transfer was attempted."
  }
];
