import type { PlatformInput } from '../models/types.js';

export const run68SeedPlatforms: PlatformInput[] = [
  {
    name: "KEXP Music Director Rotation Consideration",
    websiteUrl: "https://www.kexp.org/",
    submissionUrl: "https://kexp.org/contact/",
    sourceUrl: "https://kexp.org/contact/",
    sourceType: "automation_run_68_public_research",
    country: "United States / Seattle and San Francisco listener-powered public music radio with global streaming",
    language: "en",
    genres: ["kexp", "public-radio", "radio-airplay", "independent-artists", "electronic", "world", "reggae", "hip-hop", "ambient", "latin", "free", "music-director-email", "manual-review"],
    submissionMethod: "official-kexp-contact-route-for-music-director-and-music-department-rotation-consideration-via-md-email",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "KEXP publishes a Music Director/Music Department route for rotation consideration; human review is required for targeted email preparation, release-link selection, metadata, clean/radio-edit labeling, rights/originality assertions and KEXP programming fit before any outreach.",
    notes: "Public research confirmed the official KEXP contact page, current 2026 site activity, Music Director/Music Department email route for rotation consideration and station programming breadth. No email was sent, no file was transferred, no account was created and no SMTP/MX probe was performed."
  },
  {
    name: "WPRB Princeton Music Submissions",
    websiteUrl: "https://wprb.com/",
    submissionUrl: "https://wprb.com/music-submissions/",
    sourceUrl: "https://wprb.com/music-submissions/",
    sourceType: "automation_run_68_public_research",
    country: "United States / Princeton independent freeform radio station",
    language: "en",
    genres: ["wprb", "freeform-radio", "college-radio", "radio-airplay", "electronic", "reggae", "ska", "world", "hip-hop", "experimental", "physical-mail", "music-director-email", "free", "manual-review"],
    submissionMethod: "official-wprb-music-submissions-route-prioritizing-physical-cds-vinyl-and-accepting-music-director-email",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "WPRB accepts new music through a public Music Submissions page but prioritizes physical submissions and also publishes a music email; human review is required for physical-vs-email route selection, package prep, metadata, clean/radio edit labeling, rights/originality assertions and freeform station fit.",
    notes: "Public research confirmed the official WPRB Music Submissions page, public Music Director mailing address, public music email route, live playlist/schedule activity and 2026 site copyright. No email was sent, no physical mail was sent, no upload was attempted and no SMTP/MX probe was performed."
  },
  {
    name: "KALX 90.7FM Berkeley Physical Music Submissions",
    websiteUrl: "https://kalx.berkeley.edu/",
    submissionUrl: "https://kalx.berkeley.edu/about/contact/",
    sourceUrl: "https://kalx.berkeley.edu/about/contact/",
    sourceType: "automation_run_68_public_research",
    country: "United States / UC Berkeley community and student radio station",
    language: "en",
    genres: ["kalx", "college-radio", "community-radio", "radio-airplay", "freeform", "physical-mail", "professional-cd", "lp", "no-digital", "free", "manual-review"],
    submissionMethod: "official-kalx-contact-route-for-physical-professionally-pressed-cd-or-lp-airplay-submissions",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "KALX explicitly accepts only physical professionally pressed CDs or LPs and rejects downloads, file transfers, Bandcamp/Spotify links, YouTube videos, CD-Rs and other digital forms; human review is required for package eligibility, format selection, mailing, metadata, rights/originality and station-fit checks.",
    notes: "Public research confirmed the official KALX contact page, Music Directors and music email, physical-only airplay submission rules, no-attachment guidance and 2026 copyright. No email was sent, no physical mail was sent, no file transfer was attempted and no SMTP/MX probe was performed."
  },
  {
    name: "CJSF 90.1FM Music CD Submissions",
    websiteUrl: "https://www.cjsf.ca/",
    submissionUrl: "https://www.cjsf.ca/contact-us/submission",
    sourceUrl: "https://www.cjsf.ca/contact-us/submission",
    sourceType: "automation_run_68_public_research",
    country: "Canada / Simon Fraser University campus-community radio station",
    language: "en",
    genres: ["cjsf", "campus-radio", "community-radio", "radio-airplay", "independent-artists", "underground", "world", "ethnic", "electronic", "physical-mail", "music-coordinator-email", "free", "manual-review"],
    submissionMethod: "official-cjsf-submissions-page-for-music-coordinator-physical-or-email-music-cd-submissions",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "CJSF publishes an official Music CD Submissions route with Music Coordinator mail and email contacts; human review is required for package/link choice, tracking-time expectations, metadata, rights/originality assertions and campus-community programming fit.",
    notes: "Public research confirmed the official CJSF Submissions page, Music Coordinator route, music email, physical mailing address, 2026 homepage/news/program activity and music department navigation. No email was sent, no upload was attempted, no physical mail was sent and no SMTP/MX probe was performed."
  },
  {
    name: "KVRX 91.7FM Austin Music Department Submissions",
    websiteUrl: "https://www.kvrx.org/",
    submissionUrl: "https://www.kvrx.org/app/contact/",
    sourceUrl: "https://www.kvrx.org/app/contact/",
    sourceType: "automation_run_68_public_research",
    country: "United States / UT Austin student-run underground and independent music radio",
    language: "en",
    genres: ["kvrx", "college-radio", "student-radio", "radio-airplay", "underground-music", "local-discovery", "digital-submission", "physical-submission", "no-ai", "free", "manual-review"],
    submissionMethod: "official-kvrx-contact-route-for-music-department-physical-and-digital-airplay-submissions-via-music-email",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "KVRX publishes an official music submission email and states it is currently taking both physical and digital submissions while excluding AI-assisted/generated music; human review is required for non-AI rights/originality confirmation, package format, metadata, clean labeling and underground/station-fit checks.",
    notes: "Public research confirmed the official KVRX contact page, music submission email, physical and digital submission acceptance, AI-assisted/generated exclusion, mailing address and 2025 site copyright. No email was sent, no file was transferred, no physical mail was sent and no SMTP/MX probe was performed."
  }
];
