import type { PlatformInput } from '../models/types.js';

export const run61SeedPlatforms: PlatformInput[] = [
  {
    name: "DailyPlaylists Free Spotify Playlist Submission System",
    websiteUrl: "https://dailyplaylists.com/",
    submissionUrl: "https://dailyplaylists.com/",
    sourceUrl: "https://dailyplaylists.com/",
    sourceType: "automation_run_61_public_research",
    country: "Global / Spotify playlist marketplace",
    language: "en",
    genres: ["dailyplaylists", "spotify-playlisting", "playlist-curators", "independent", "electronic", "dance", "reggae", "world", "pop", "free-standard-submissions", "premium-credits", "login-route", "manual-review"],
    submissionMethod: "official-public-dailyplaylists-submit-a-song-route-with-free-standard-submissions-and-optional-premium-credits",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "DailyPlaylists publishes an official Submit a Song route with free standard submissions plus optional paid submission add-ons and premium credits; human review is required because the workflow requires signing in, selecting a Spotify track, matching playlists/curators, avoiding irrelevant submissions, deciding whether to use paid credits and validating playlist fit before any submission.",
    notes: "Public research confirmed active DailyPlaylists site content, 2026 footer, free tier pricing and public business email on the official pricing page. No account, submission or payment action was taken."
  },
  {
    name: "Groover Music Promotion Curator Campaigns",
    websiteUrl: "https://groover.co/",
    submissionUrl: "https://groover.co/en/",
    sourceUrl: "https://groover.co/en/",
    sourceType: "automation_run_61_public_research",
    country: "Global / France and United States music promotion platform",
    language: "en",
    genres: ["groover", "music-promotion", "playlist-curators", "radio-stations", "blogs", "labels", "djs", "electronic", "world", "reggae", "paid-credits", "login-route", "manual-review"],
    submissionMethod: "official-public-groover-campaign-route-to-selected-curators-playlists-radios-labels-and-djs-using-paid-grooviz-credits",
    feeRequired: true,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Groover publishes an official artist campaign route to browse and contact curators, playlists, radios, labels and DJs using paid Grooviz credits; human review is required for account creation, music upload/link selection, budget approval, target filtering, curator/pro selection, rights/originality assertions, payment and campaign launch.",
    notes: "Public research confirmed active 2026 Groover site content, genre coverage including Electronic, World and Reggae, 3,000+ curators/pros and paid credit pricing. No account, upload, submission or payment action was taken."
  },
  {
    name: "Musosoup Artist Campaign Submission",
    websiteUrl: "https://musosoup.com/",
    submissionUrl: "https://musosoup.com/",
    sourceUrl: "https://musosoup.com/",
    sourceType: "automation_run_61_public_research",
    country: "Global / UK music promotion marketplace",
    language: "en",
    genres: ["musosoup", "music-promotion", "playlisting", "blogs", "reviews", "interviews", "curators", "electronic", "independent", "free-initial-submit", "paid-campaign-fee", "login-route", "manual-review"],
    submissionMethod: "official-public-musosoup-submit-music-route-with-free-initial-upload-review-and-paid-campaign-activation",
    feeRequired: true,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Musosoup publishes an official Submit music route with free initial upload/link submission, review up to 24 hours, account creation and paid campaign activation if accepted; human review is required for audio/link upload, release timing, campaign fee approval, free-vs-paid coverage choices, curator offer acceptance and rights/originality checks.",
    notes: "Public research confirmed active 2026 Musosoup site content, a current submit route, global curators and pricing/campaign rules. No account, upload, submission or payment action was taken."
  },
  {
    name: "SoundCampaign Spotify and TikTok Music Promotion",
    websiteUrl: "https://soundcamps.com/",
    submissionUrl: "https://soundcamps.com/",
    sourceUrl: "https://soundcamps.com/",
    sourceType: "automation_run_61_public_research",
    country: "Global / Spotify playlist and TikTok creator promotion platform",
    language: "en",
    genres: ["soundcampaign", "spotify-promotion", "playlist-curators", "tiktok-creators", "music-promotion", "electronic", "dance", "reggae", "world", "paid-campaign", "login-route", "manual-review"],
    submissionMethod: "official-public-soundcampaign-promotion-route-for-spotify-playlist-curator-and-tiktok-creator-review-campaigns",
    feeRequired: true,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "SoundCampaign publishes an official Get Started/Promote route for Spotify playlist curator and TikTok creator campaigns; human review is required for account creation, track selection, campaign budget, platform choice, campaign targeting, rights/originality confirmation, payment and review of playlist-consideration claims before launch.",
    notes: "Public research confirmed active SoundCampaign site content, current promotion routes, login route and stated playlist-curator/TikTok creator campaign model. No account, submission, file transfer or payment action was taken."
  },
  {
    name: "Playlist Push Spotify and TikTok Campaigns",
    websiteUrl: "https://playlistpush.com/",
    submissionUrl: "https://playlistpush.com/",
    sourceUrl: "https://playlistpush.com/",
    sourceType: "automation_run_61_public_research",
    country: "Global / Spotify playlist and TikTok creator promotion platform",
    language: "en",
    genres: ["playlist-push", "spotify-promotion", "tiktok-promotion", "playlist-curators", "creators", "electronic", "dance", "independent", "paid-campaign", "login-route", "manual-review"],
    submissionMethod: "official-public-playlist-push-promote-your-music-route-for-spotify-playlist-and-tiktok-creator-campaigns",
    feeRequired: true,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Playlist Push publishes an official Promote your Music route for Spotify playlist and TikTok campaigns; human review is required for account creation, artist dashboard setup, campaign budget approval, genre targeting, track submission, payment, platform-specific rights/originality checks and no-guarantee playlist consideration review.",
    notes: "Public research confirmed active Playlist Push site content, artist account route, Spotify/TikTok campaign routes, curator vetting claims and pricing guidance. No account, campaign setup or payment action was taken."
  }
];
