import type { PlatformInput } from '../models/types.js';

export const run66SeedPlatforms: PlatformInput[] = [
  {
    name: "EARMILK Submit Music",
    websiteUrl: "https://earmilk.com/",
    submissionUrl: "https://earmilk.com/submit-music/",
    sourceUrl: "https://earmilk.com/submit-music/",
    sourceType: "automation_run_66_public_research",
    country: "United States / global online music magazine",
    language: "en",
    genres: ["earmilk", "music-blog", "electronic", "dance", "experimental", "hip-hop", "indie", "pop", "rock", "submithub", "pillargram", "premiere-submissions", "freemium", "manual-review"],
    submissionMethod: "official-earmilk-submit-music-route-through-submithub-or-pillargram-for-editorial-review-and-premiere-consideration",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "EARMILK currently accepts music exclusively through SubmitHub or Pillargram; human review is required for third-party login/account access, track/link choice, possible premium credit decisions, premiere eligibility, metadata, editorial fit and rights/originality assertions.",
    notes: "Public research confirmed the official EARMILK Submit Music page, active 2026 posts and the exclusive SubmitHub/Pillargram submission route. No SubmitHub/Pillargram account was entered, no email was sent, no form was submitted, no payment was attempted and no SMTP/MX probe was performed."
  },
  {
    name: "Fresh On The Net Listening Post Submissions",
    websiteUrl: "https://freshonthenet.co.uk/",
    submissionUrl: "https://freshonthenet.co.uk/submit/",
    sourceUrl: "https://freshonthenet.co.uk/submit/",
    sourceType: "automation_run_66_public_research",
    country: "United Kingdom / global independent music blog and listening-post community",
    language: "en",
    genres: ["fresh-on-the-net", "listening-post", "fresh-faves", "independent-artists", "new-music", "soundcloud-link", "one-track-weekly", "radio-edit-side-route", "no-ai-generated-tracks", "manual-review"],
    submissionMethod: "official-fresh-on-the-net-send-us-a-track-listening-post-inbox-route-with-conditional-radio-play-side-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Fresh On The Net opens and closes its inbox on a weekly capacity window, limits artists to one track per week, requires public worldwide track availability, rejects AI-generated tracks and includes special voting/non-promotion rules; human review is required before any submission.",
    notes: "Public research confirmed the official Send Us A Track page, recent June 2026 activity, a scheduled July 2026 inbox window, one-track weekly limits and a conditional Exile FM clean-radio-edit email side route. No track was submitted, no email was sent and no SMTP/MX probe was performed."
  },
  {
    name: "Stereofox Music Submissions",
    websiteUrl: "https://www.stereofox.com/",
    submissionUrl: "https://www.stereofox.com/contact/",
    sourceUrl: "https://www.stereofox.com/contact/",
    sourceType: "automation_run_66_public_research",
    country: "Bulgaria / global human-curated music blog, playlists and label ecosystem",
    language: "en",
    genres: ["stereofox", "music-blog", "human-curated", "playlists", "electronic", "chill-electronica", "uk-garage", "progressive-house", "submithub", "groover", "freemium", "manual-review"],
    submissionMethod: "official-stereofox-submit-music-route-through-submithub-or-groover-with-no-email-or-discord-submissions",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Stereofox explicitly routes music submissions through SubmitHub or Groover and says email/Discord submissions are not processed; human review is required for third-party login, track targeting, possible paid-credit choices, playlist/editorial fit and rights/originality assertions.",
    notes: "Public research confirmed the official Stereofox contact page, active 2026 site content, a Submit Music navigation route and an instruction to use SubmitHub or Groover only. No third-party route was entered, no form was submitted, no payment was attempted and no SMTP/MX probe was performed."
  },
  {
    name: "Obscure Sound Music Submissions",
    websiteUrl: "https://www.obscuresound.com/",
    submissionUrl: "https://www.obscuresound.com/",
    sourceUrl: "https://www.obscuresound.com/",
    sourceType: "automation_run_66_public_research",
    country: "United States / global indie music blog",
    language: "en",
    genres: ["obscure-sound", "indie-blog", "electronic", "alt-pop", "dream-pop", "folk", "rock", "hip-hop", "submit-hub", "musosoup", "music-pr-services", "freemium", "manual-review"],
    submissionMethod: "official-obscure-sound-public-route-through-submithub-or-musosoup-for-blog-feature-consideration",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Obscure Sound points artists to SubmitHub or MusoSoup; human review is required for third-party account/login, track/EP selection, optional paid campaign or credit choices, blog-fit, metadata, rights and originality checks.",
    notes: "Public research confirmed the official Obscure Sound site, active June 2026 posts and footer submission links to SubmitHub and MusoSoup. MusoSoup was previously known as a manual campaign route, so this platform-specific editorial route remains manual-only. No third-party route was entered, no upload/form/email/payment or SMTP/MX probe was performed."
  },
  {
    name: "The Line of Best Fit New and Unsigned Artist Submissions",
    websiteUrl: "https://www.thelineofbestfit.com/",
    submissionUrl: "https://www.thelineofbestfit.com/contact",
    sourceUrl: "https://www.thelineofbestfit.com/contact",
    sourceType: "automation_run_66_public_research",
    country: "United Kingdom / global online music magazine",
    language: "en",
    genres: ["the-line-of-best-fit", "new-music", "unsigned-artists", "music-magazine", "google-form", "press-release-email", "pop", "indie", "electronic", "manual-review"],
    submissionMethod: "official-line-of-best-fit-contact-route-with-google-form-for-new-and-unsigned-artists-and-public-redacted-editorial-email-side-routes",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "The Line of Best Fit welcomes music from new and unsigned artists via a linked Google Form and publishes redacted editorial contact aliases; human review is required for form fields, track/link choice, press-release routing, anti-spam boundaries, rights and editorial fit.",
    notes: "Public research confirmed the official contact page, the linked Google Form for new and unsigned artists, public redacted news/hello/licensing email side routes and current 2026 site footer. No Google Form was opened/submitted, no redacted alias was decoded into an address, no email was sent and no SMTP/MX probe was performed."
  }
];
