import type { PlatformInput } from '../models/types.js';

export const run63SeedPlatforms: PlatformInput[] = [
  {
    name: "KSPC 88.7FM Claremont Music Submissions",
    websiteUrl: "https://kspc.org/",
    submissionUrl: "https://kspc.org/contact/music-submissions/",
    sourceUrl: "https://kspc.org/contact/music-submissions/",
    sourceType: "automation_run_63_public_research",
    country: "United States / California college and community radio",
    language: "en",
    genres: ["kspc", "college-radio", "community-radio", "independent", "local", "electronic", "hip-hop", "reggae", "world", "album-ep-submissions", "music-director-review", "manual-review"],
    submissionMethod: "official-public-kspc-music-submissions-route-for-cd-record-or-digital-album-ep-airplay-review",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "KSPC publishes an official Music Submissions page accepting albums or EPs by physical mail or downloadable digital submission; human review is required for album/EP eligibility, no-singles/no-demos/no-AI restrictions, downloadable-file preparation, metadata, rights/originality, station-fit and follow-up decisions.",
    notes: "Public research confirmed active KSPC site content and official Music Submissions instructions. The email address was protected/masked in extraction and was not decoded. No email, upload, form submission, payment, physical mail or SMTP/MX probe was performed."
  },
  {
    name: "KXLU 88.9FM Los Angeles Submissions",
    websiteUrl: "https://kxlu.com/",
    submissionUrl: "https://kxlu.com/contact/",
    sourceUrl: "https://kxlu.com/contact/",
    sourceType: "automation_run_63_public_research",
    country: "United States / Los Angeles college and freeform radio",
    language: "en",
    genres: ["kxlu", "college-radio", "freeform-radio", "independent", "electronic", "reggae", "dub", "punk", "folk", "vinyl", "demolisten", "physical-submissions", "music-director-review", "manual-review"],
    submissionMethod: "official-public-kxlu-contact-page-submissions-route-for-fcc-clean-general-demolisten-and-specialty-physical-review",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "KXLU publishes official submission instructions on its Contact page, including FCC-clean requirement and separate physical routes for general Music Director, Demolisten and specialty/punk/folk/vinyl submissions; human review is required for choosing the right route, clean-language/FCC labeling, package prep, rights/originality and station/show fit.",
    notes: "Public research confirmed active 2026 KXLU site content, Music Director contact details and official submission mailing routes. No email, upload, form submission, payment, physical mail or SMTP/MX probe was performed."
  },
  {
    name: "KDVS 90.3FM Davis Music Department Submissions",
    websiteUrl: "https://kdvs.org/",
    submissionUrl: "https://kdvs.org/contact",
    sourceUrl: "https://kdvs.org/contact",
    sourceType: "automation_run_63_public_research",
    country: "United States / California freeform college radio",
    language: "en",
    genres: ["kdvs", "college-radio", "freeform-radio", "independent", "physical-submissions", "music-department", "record-label-contact", "manual-review"],
    submissionMethod: "official-public-kdvs-contact-page-music-department-route-with-physical-submissions-only",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "KDVS publishes an official Music Directors/Music Department contact route and states that all new music should be sent to the mailing address as physical submissions only; human review is required for deciding whether to mail material, preparing physical release metadata, rights/originality notes and station-fit context.",
    notes: "Public research confirmed active KDVS site, staff/contact details, Music Department email and physical-submissions-only instruction. No email, form submission, file transfer, payment, physical mail or SMTP/MX probe was performed."
  },
  {
    name: "WREK 91.1FM Atlanta How To Submit Music",
    websiteUrl: "https://www.wrek.org/",
    submissionUrl: "https://old.wrek.org/submissions/",
    sourceUrl: "https://old.wrek.org/submissions/",
    sourceType: "automation_run_63_public_research",
    country: "United States / Atlanta student-run radio",
    language: "en",
    genres: ["wrek", "college-radio", "student-radio", "independent", "electronic", "ambient", "experimental", "reggae", "dub", "international", "physical-submissions", "music-director-review", "manual-review"],
    submissionMethod: "official-public-wrek-how-to-submit-music-route-by-snail-mail-or-music-director-email",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "WREK publishes an official How To Submit Music route with snail-mail and Music Director email options, while noting CDs/LPs have a better chance of airplay and submissions are randomly reviewed by Music Directors; human review is required for format choice, package/email prep, metadata, rights/originality, FCC/station-fit and follow-up timing.",
    notes: "Public research confirmed active WREK site, official submissions page, Music Director email route, physical address and selection/process notes. No email, upload, form submission, payment, physical mail or SMTP/MX probe was performed."
  },
  {
    name: "WMBR 88.1FM MIT Your Music",
    websiteUrl: "https://wmbr.org/",
    submissionUrl: "https://wmbr.org/www/md",
    sourceUrl: "https://wmbr.org/www/md",
    sourceType: "automation_run_63_public_research",
    country: "United States / Cambridge MIT freeform radio",
    language: "en",
    genres: ["wmbr", "college-radio", "freeform-radio", "independent", "unsigned-bands", "garage", "punk", "experimental", "rpm-techno", "world", "physical-submissions", "manual-review"],
    submissionMethod: "official-public-wmbr-how-to-get-your-music-played-physical-cd-route-for-dj-consideration",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "WMBR publishes an official Your Music page explaining its freeform DJ-selection process and instructs artists to send tangible physical music to the Music Director; human review is required for deciding whether to send a physical release, show/genre targeting, one-sheet preparation, rights/originality and avoiding unsolicited mailing-list/self-promotion issues.",
    notes: "Public research confirmed active WMBR site, official Your Music instructions, physical Music Director route and genre-contact section. Email contacts were image/protected in extraction and were not decoded. No email, upload, form submission, payment, physical mail or SMTP/MX probe was performed."
  }
];
