import type { PlatformInput } from '../models/types.js';

export const run64SeedPlatforms: PlatformInput[] = [
  {
    name: "Soundplate Play Spotify and Deezer Playlist Submissions",
    websiteUrl: "https://soundplate.com/",
    submissionUrl: "https://play.soundplate.com/",
    sourceUrl: "https://play.soundplate.com/",
    sourceType: "automation_run_64_public_research",
    country: "United Kingdom / global independent playlist submission platform",
    language: "en",
    genres: ["soundplate", "spotify-playlists", "deezer-playlists", "independent-curators", "electronic", "dance", "house", "playlist-submission", "free-submission", "manual-review"],
    submissionMethod: "official-public-soundplate-play-free-spotify-and-deezer-playlist-selection-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Soundplate Play publishes an official free playlist submission route where artists select relevant Spotify or Deezer playlists; human review is required for playlist/curator fit, track-link selection, anti-spam compliance, rights/originality and any per-playlist form behavior.",
    notes: "Public research confirmed an active Soundplate Play page, playlist grid and free submission language. No playlist was selected, no form was submitted, no account was created, no payment was attempted, no file was transferred and no SMTP/MX probe was performed."
  },
  {
    name: "Spinnin' Records Talent Pool Demo Dashboard",
    websiteUrl: "https://spinninrecords.com/",
    submissionUrl: "https://spinninrecords.com/releases/?label=spinnin-talent-pool",
    sourceUrl: "https://spinninrecords.com/releases/?label=spinnin-talent-pool",
    sourceType: "automation_run_64_public_research",
    country: "Netherlands / global EDM label and demo community",
    language: "en",
    genres: ["spinnin-records", "talent-pool", "edm", "dance", "house", "future-house", "electronic", "demo-submission", "label-review", "login-required", "manual-review"],
    submissionMethod: "official-public-spinnin-records-talent-pool-dashboard-route-for-edm-demo-and-contest-review",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Spinnin' Records exposes an official Talent Pool area with dashboard, FAQ and terms behind login; human review is required for account/login, demo selection, rights/originality, SoundCloud/link handling, contest/label-fit decisions and acceptance of platform terms.",
    notes: "Public research confirmed Spinnin' Records is an active EDM label with Talent Pool listed as a current imprint and official site navigation to Talent Pool dashboard/FAQ/terms. No login, upload, form submission, payment, protected-contact decoding or SMTP/MX probing was performed."
  },
  {
    name: "Spotify for Artists Editorial Playlist Pitching",
    websiteUrl: "https://artists.spotify.com/",
    submissionUrl: "https://artists.spotify.com/",
    sourceUrl: "https://artists.spotify.com/",
    sourceType: "automation_run_64_public_research",
    country: "Global / Spotify for Artists editorial playlist workflow",
    language: "en",
    genres: ["spotify", "spotify-for-artists", "editorial-playlist-pitching", "playlist-submission", "streaming", "release-planning", "login-required", "manual-review"],
    submissionMethod: "official-spotify-for-artists-dashboard-route-for-unreleased-track-editorial-playlist-pitching",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Spotify's playlist pitching workflow requires Spotify for Artists access, an unreleased distributed track, release timing, metadata and editorial pitch fields; human review is required for login, artist authorization, distributor/release readiness, rights/originality, pitch copy and territory/genre targeting.",
    notes: "Public research confirmed Spotify for Artists and the editorial playlist submission tool are active, but direct upload to Spotify is not available for artists without a distributor. No login, pitch, upload, payment, royalty-program enrollment, form submission or anti-bot interaction was attempted."
  },
  {
    name: "Mixcloud Creator Upload and Discovery Platform",
    websiteUrl: "https://www.mixcloud.com/",
    submissionUrl: "https://www.mixcloud.com/upload/",
    sourceUrl: "https://www.mixcloud.com/",
    sourceType: "automation_run_64_public_research",
    country: "United Kingdom / worldwide licensed audio streaming and creator upload platform",
    language: "en",
    genres: ["mixcloud", "dj-mixes", "radio-shows", "podcasts", "electronic", "dance", "reggae", "dub", "creator-upload", "login-required", "manual-review"],
    submissionMethod: "official-mixcloud-registered-creator-upload-route-for-radio-show-dj-mix-or-audio-program-distribution",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Mixcloud allows registered users to upload and distribute audio content and requires correct artist/song metadata for rights handling; human review is required for account/login, show/mix eligibility, metadata, rights/originality, public/private settings and any creator monetization choices.",
    notes: "Public research confirmed active Mixcloud status, worldwide reach, upload requirement for registered users and rights/metadata expectations. No account was created, no upload was attempted, no payment was attempted and no CAPTCHA or validation control was bypassed."
  },
  {
    name: "Vampr Publishing Sync and Artist Network Opportunities",
    websiteUrl: "https://vampr.me/",
    submissionUrl: "https://vampr.me/",
    sourceUrl: "https://vampr.me/",
    sourceType: "automation_run_64_public_research",
    country: "United States / global artist networking, publishing and sync opportunity platform",
    language: "en",
    genres: ["vampr", "music-networking", "sync-representation", "music-publishing", "artist-opportunities", "collaboration", "distribution", "promotion", "login-required", "manual-review"],
    submissionMethod: "official-vampr-account-route-for-music-networking-publishing-sync-representation-and-artist-opportunity-workflows",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Vampr is an artist/professional networking platform with publishing, distribution and marketing opportunity workflows; human review is required for account/login, profile setup, track/catalog eligibility, sync-representation choices, optional premium/distribution decisions, rights/originality and contact boundaries.",
    notes: "Public research confirmed Vampr's active global music-networking role, acquisition history, free publishing representation reference and tiered distribution/pro marketing side routes. No account, profile, submission, payment, direct message, file transfer or protected-contact action was performed."
  }
];
