import type { PlatformInput } from '../models/types.js';

export const run60SeedPlatforms: PlatformInput[] = [
  {
    name: 'KOPN 89.5FM Artist Submissions',
    websiteUrl: 'https://www.kopn.org/',
    submissionUrl: 'https://www.kopn.org/artist-submission/',
    sourceUrl: 'https://www.kopn.org/artist-submission/',
    sourceType: 'automation_run_60_public_research',
    country: 'United States / Missouri / Columbia community radio',
    language: 'en',
    genres: ['kopn', 'community-radio', 'columbia-missouri', 'radio-airplay', 'independent', 'freeform', 'electronic', 'world', 'reggae', 'physical-mail', 'email-route', 'manual-review'],
    submissionMethod: 'official-public-kopn-artist-submission-route-via-music-director-email-or-physical-media-mailing',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'KOPN publishes an official Artist Submissions page with Music Director email and physical mailing instructions; human review is required because the workflow includes physical package preparation, professionally manufactured CD requirements, no-CD-R/no-demo/no-single restrictions, booklet and track metadata, clean-language/FCC notes and freeform station-fit review.',
    notes: 'Public research confirmed active KOPN programming/playlists and the official Artist Submissions page. No route action was taken.'
  },
  {
    name: 'KAOS 89.3FM Olympia Submit Music',
    websiteUrl: 'https://www.kaosradio.org/',
    submissionUrl: 'https://www.kaosradio.org/submitmusic',
    sourceUrl: 'https://www.kaosradio.org/submitmusic',
    sourceType: 'automation_run_60_public_research',
    country: 'United States / Washington / Olympia community radio',
    language: 'en',
    genres: ['kaos', 'community-radio', 'olympia', 'pacific-northwest', 'radio-airplay', 'independent', 'freeform', 'electronic', 'beats', 'world', 'reggae', 'physical-mail', 'download-link', 'manual-review'],
    submissionMethod: 'official-public-kaos-submit-music-route-prioritizing-physical-submissions-with-digital-link-email-option',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'KAOS publishes official Submit Music instructions; human review is required because physical submissions are prioritized, digital submissions are accepted as time allows, singles are not accepted, no attachments should be sent, clean edits and FCC notes are required and local/PNW eligibility plus DJ/station-fit claims must be checked manually.',
    notes: 'Public research confirmed active KAOS 2026 Music Department posts and the official Submit Music page. No route action was taken.'
  },
  {
    name: 'WTJU 91.1FM Submit Music',
    websiteUrl: 'https://www.wtju.net/',
    submissionUrl: 'https://www.wtju.net/submit-music/',
    sourceUrl: 'https://www.wtju.net/submit-music/',
    sourceType: 'automation_run_60_public_research',
    country: 'United States / Virginia / Charlottesville community and university radio',
    language: 'en',
    genres: ['wtju', 'community-radio', 'university-radio', 'charlottesville', 'radio-airplay', 'independent', 'freeform', 'jazz', 'rock', 'world', 'electronic', 'digital-files', 'physical-mail', 'manual-review'],
    submissionMethod: 'official-public-wtju-submit-music-route-with-genre-director-email-routing-and-physical-mail-options',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'WTJU publishes official Submit Music instructions with genre-director contact routing and physical/digital submission options; human review is required because the route requires genre targeting, accepted-format checks, streaming-link-vs-broadcast-library handling, physical package decisions, timing expectations and station-fit review.',
    notes: 'Public research confirmed active WTJU 2026 site content and the official Submit Music page. No route action was taken.'
  },
  {
    name: 'WMNF 88.5FM Tampa Submit Your Music',
    websiteUrl: 'https://www.wmnf.org/',
    submissionUrl: 'https://www.wmnf.org/submit-your-music-to-wmnf/',
    sourceUrl: 'https://www.wmnf.org/submit-your-music-to-wmnf/',
    sourceType: 'automation_run_60_public_research',
    country: 'United States / Florida / Tampa community radio',
    language: 'en',
    genres: ['wmnf', 'community-radio', 'tampa', 'radio-airplay', 'independent', 'electronic', 'world', 'reggae', 'web-form', 'file-upload', 'email-route', 'manual-review'],
    submissionMethod: 'official-public-wmnf-submit-your-music-web-form-with-music-relations-email-route',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'WMNF publishes an official Submit Your Music page with a Music Department email route and file-upload form; human review is required because the workflow includes form completion, up to five music-file uploads, local/Tampa-root fields, artist metadata, rights/originality checks and Music Department or host-fit review.',
    notes: 'Public research confirmed active WMNF 2026 music/news content and the official Submit Your Music page. No form was submitted and no files were uploaded.'
  },
  {
    name: 'WMPG 90.9FM Music Department Submissions',
    websiteUrl: 'https://www.wmpg.org/',
    submissionUrl: 'https://www.wmpg.org/contact-us/music-department/',
    sourceUrl: 'https://www.wmpg.org/contact-us/music-department/',
    sourceType: 'automation_run_60_public_research',
    country: 'United States / Maine / Portland university community radio',
    language: 'en',
    genres: ['wmpg', 'community-radio', 'university-radio', 'portland-maine', 'radio-airplay', 'independent', 'freeform', 'electronic', 'world', 'reggae', 'mp3', 'wav', 'email-route', 'manual-review'],
    submissionMethod: 'official-public-wmpg-music-department-digital-file-download-link-email-route',
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: 'WMPG publishes official Music Department instructions and now only accepts digital files by download link; human review is required because the route requires MP3/WAV package preparation, subject-line genre tagging, download-link hygiene, metadata, rights/originality and DJ/station-fit review.',
    notes: 'Public research confirmed active WMPG 2026 site content and the official Music Department submission page. No email or file transfer was performed.'
  }
];
