import type { PlatformInput } from '../models/types.js';

export const run69SeedPlatforms: PlatformInput[] = [
  {
    name: "KUTX Submit Your Music for On-Air Rotation",
    websiteUrl: "https://kutx.org/",
    submissionUrl: "https://kutx.org/submit-your-music/",
    sourceUrl: "https://kutx.org/submit-your-music/",
    sourceType: "automation_run_69_public_research",
    country: "United States / Austin public music radio with global streaming",
    language: "en",
    genres: ["kutx", "public-radio", "radio-airplay", "independent-artists", "austin", "texas", "electronic", "hip-hop", "latin", "jazz", "world", "free", "music-director-email", "manual-review"],
    submissionMethod: "official-kutx-submit-your-music-route-for-on-air-rotation-via-music-director-email-with-streaming-link-and-wav-download-link",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "KUTX publishes a Submit Your Music route for on-air rotation through its Music Director email; human review is required for targeted email preparation, streaming and WAV download link selection, release notes, local ATX/TX subject labeling, clean/radio-edit confirmation, rights/originality assertions and KUTX programming fit.",
    notes: "Public research confirmed the official KUTX Submit Your Music page, current 2026 site activity, music@kutx.org route, streaming-link and WAV download-link requirements, no-MP3-attachment guidance, clean/FCC language requirement and specialty show routing. No email was sent, no form was submitted, no file was transferred and no SMTP/MX probe was performed."
  },
  {
    name: "Radio K KUOM Submitting Music",
    websiteUrl: "https://radiok.org/",
    submissionUrl: "https://radiok.org/submitting-music",
    sourceUrl: "https://radiok.org/submitting-music",
    sourceType: "automation_run_69_public_research",
    country: "United States / University of Minnesota student-run independent radio with global streaming",
    language: "en",
    genres: ["radio-k", "kuom", "college-radio", "student-radio", "radio-airplay", "independent-music", "electronic", "hip-hop", "world", "local", "physical-mail", "music-department-email", "free", "manual-review"],
    submissionMethod: "official-radio-k-submitting-music-route-for-physical-copy-or-digital-cloud-zip-release-to-music-department",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Radio K publishes an official Submitting Music route with physical-copy and digital-copy options; human review is required for deciding physical vs digital submission, building a cloud ZIP with high-quality WAV/FLAC files, FCC-unfriendly track labeling, local subject/package labeling, metadata, rights/originality assertions and station-fit checks.",
    notes: "Public research confirmed the official Radio K contact and Submitting Music pages, active 2026 homepage/new-rotation content, Music Department route, physical mailing address, digital cloud ZIP guidance, WAV/FLAC preference, Bandcamp download-code option and no-tracking-request guidance. No email was sent, no file was transferred, no physical mail was sent and no SMTP/MX probe was performed."
  },
  {
    name: "KCR College Radio Music Submissions",
    websiteUrl: "https://kcr.sdsu.edu/",
    submissionUrl: "https://kcr.sdsu.edu/contact/music-submissions/",
    sourceUrl: "https://kcr.sdsu.edu/contact/music-submissions/",
    sourceType: "automation_run_69_public_research",
    country: "United States / San Diego State University student-run college radio",
    language: "en",
    genres: ["kcr", "college-radio", "student-radio", "radio-airplay", "san-diego", "independent-artists", "electronic", "edm", "festival", "alternative", "mp3", "free", "music-submissions-email", "manual-review"],
    submissionMethod: "official-kcr-music-submissions-route-for-digital-email-submission-of-fcc-clean-mp3-files",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "KCR publishes an official Music Submissions page with a digital email route and strict FCC-clean/MP3 filename requirements; human review is required for selecting clean masters, confirming MP3 format, naming files correctly, preparing metadata, avoiding status calls, rights/originality assertions and playlist/library fit.",
    notes: "Public research confirmed the official KCR College Radio homepage, current 2026 blog activity, Music Submissions page, digital-only email route, FCC-clean MP3 requirement, filename format and automated playlist/library review process. No email was sent, no file was attached or transferred, no form was submitted and no SMTP/MX probe was performed."
  },
  {
    name: "KCSB Artist Inquiry Form",
    websiteUrl: "https://www.kcsb.org/",
    submissionUrl: "https://www.kcsb.org/contact/artist-inquiry/",
    sourceUrl: "https://www.kcsb.org/contact/artist-inquiry/",
    sourceType: "automation_run_69_public_research",
    country: "United States / UC Santa Barbara non-commercial college and community radio",
    language: "en",
    genres: ["kcsb", "college-radio", "community-radio", "radio-airplay", "live-on-air", "station-events", "music-library", "premiere", "independent-artists", "google-form", "free", "manual-review"],
    submissionMethod: "official-kcsb-artist-inquiry-route-linking-to-external-google-form-for-on-air-live-sessions-events-music-library-and-premieres",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "KCSB publishes an Artist Inquiry page that routes artists, bands and DJs to an external Google Form for live on-air performance, station events, music library adds and premieres; human review is required because the external form may present Google validation/anti-abuse controls and requires eligibility, route choice, metadata, rights/originality and event/library fit decisions.",
    notes: "Public research confirmed the official KCSB Artist Inquiry page, external forms.gle form link, live-on-air, event/concert, music-library and premiere opportunity categories, plus active 2026 homepage/blog/music department activity. The external form was identified but not opened for submission, no CAPTCHA or validation control was bypassed, no form was submitted and no account was created."
  },
  {
    name: "KZSC Santa Cruz Station Music Director Contacts",
    websiteUrl: "https://kzsc.org/",
    submissionUrl: "https://kzsc.org/contact/",
    sourceUrl: "https://kzsc.org/contact/",
    sourceType: "automation_run_69_public_research",
    country: "United States / UC Santa Cruz student-run community college radio",
    language: "en",
    genres: ["kzsc", "college-radio", "community-radio", "radio-airplay", "rock", "hardcore", "hip-hop", "rpm", "electronic", "jazz", "blues", "folk", "international", "music-director-email", "free", "manual-review"],
    submissionMethod: "official-kzsc-contact-route-with-public-station-music-director-and-genre-director-email-contacts-for-targeted-airplay-consideration",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "KZSC publishes current station Music Director and genre-director public contacts for rock, hardcore, hip-hop, RPM/electronic, jazz/blues, folk and international music; human review is required for selecting the correct director route, preparing a non-spam targeted pitch, metadata, clean/radio edit labeling, rights/originality assertions and programming fit.",
    notes: "Public research confirmed the official KZSC contact/staff page, current 2026 homepage/blog activity, public station music director and genre director email contacts, and an RPM/electronic director relevant to MarcsMusic. No email was sent, no form was submitted, no contact pattern was guessed and no SMTP/MX probe was performed."
  }
];
