import type { PlatformInput } from '../models/types.js';

export const run65SeedPlatforms: PlatformInput[] = [
  {
    name: "Songtradr Music Licensing Marketplace",
    websiteUrl: "https://www.songtradr.com/",
    submissionUrl: "https://www.songtradr.com/",
    sourceUrl: "https://www.songtradr.com/",
    sourceType: "automation_run_65_public_research",
    country: "United States / global music licensing marketplace",
    language: "en",
    genres: ["songtradr", "sync-licensing", "music-licensing", "catalog-upload", "film-tv-advertising", "brands", "creator-platforms", "independent-artists", "login-required", "manual-review"],
    submissionMethod: "official-songtradr-account-route-for-catalog-upload-and-music-licensing-marketplace-review",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Songtradr is a music licensing marketplace where artists can upload music and set licensing terms; human review is required for account/login, catalog eligibility, metadata, licensing fee choices, ownership splits, PRO/publishing conflicts, sync-fit and rights/originality assertions.",
    notes: "Public research confirmed Songtradr's active licensing marketplace role and artist upload/licensing model; the official public site loaded as a JavaScript app in the research environment, so all account, upload, catalog and licensing actions remain manual. No account was created, no form was submitted, no file was transferred, no payment was attempted and no SMTP/MX probe was performed."
  },
  {
    name: "ReverbNation Artist Opportunities and Profile Platform",
    websiteUrl: "https://www.reverbnation.com/",
    submissionUrl: "https://www.reverbnation.com/band-promotion/opportunities",
    sourceUrl: "https://www.reverbnation.com/",
    sourceType: "automation_run_65_public_research",
    country: "United States / global independent artist services platform",
    language: "en",
    genres: ["reverbnation", "artist-opportunities", "artist-profile", "music-promotion", "epk", "sync-opportunities", "independent-artists", "login-required", "freemium", "manual-review"],
    submissionMethod: "official-reverbnation-artist-account-route-for-profile-opportunities-and-music-promotion-workflows",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "ReverbNation is an active independent-music platform with artist profile and opportunity workflows; human review is required for artist account access, EPK/profile setup, track selection, opportunity eligibility, region/genre fit, optional promotion decisions and rights/originality assertions.",
    notes: "Public research confirmed ReverbNation's active independent-music platform status and BandLab ownership; the opportunity URL returned 403 to the research fetcher and was therefore queued manual-only. No login, profile creation, opportunity submission, upload, payment, protected-contact action or SMTP/MX probe was performed."
  },
  {
    name: "Broadjam Song Licensing and Placement Opportunities",
    websiteUrl: "https://www.broadjam.com/",
    submissionUrl: "https://www.broadjam.com/delivery/opportunities.php",
    sourceUrl: "https://www.broadjam.com/",
    sourceType: "automation_run_65_public_research",
    country: "United States / global independent musician licensing and placement community",
    language: "en",
    genres: ["broadjam", "song-licensing", "music-placement", "film-tv-advertising", "video-games", "radio-play", "professional-reviews", "independent-artists", "membership-required", "manual-review"],
    submissionMethod: "official-broadjam-member-route-for-song-licensing-placement-radio-play-and-review-opportunities",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Broadjam provides independent-musician community, contest, review, radio-play and licensing/placement opportunity workflows; human review is required for membership/login, song upload, opportunity targeting, possible paid membership or submission choices, metadata, placement-fit and rights/originality assertions.",
    notes: "Public research confirmed Broadjam's licensing, placement, radio-play and professional-review opportunity model for independent musicians; the official site returned 403 to the research fetcher, so the route is manual-only. No account, membership action, song upload, opportunity submission, payment or SMTP/MX probe was performed."
  },
  {
    name: "RouteNote Free-First Distribution and Publishing",
    websiteUrl: "https://www.routenote.com/",
    submissionUrl: "https://www.routenote.com/",
    sourceUrl: "https://www.routenote.com/",
    sourceType: "automation_run_65_public_research",
    country: "United Kingdom / worldwide digital music distribution and publishing platform",
    language: "en",
    genres: ["routenote", "digital-distribution", "music-publishing", "licensing", "spotify", "apple-music", "amazon-music", "free-distribution", "premium-option", "manual-review"],
    submissionMethod: "official-routenote-free-first-account-route-for-digital-distribution-publishing-and-store-delivery",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "RouteNote offers free and premium distribution and publishing workflows; human review is required for account/login, release upload, store and territory choices, UPC/ISRC handling, metadata, artwork, free-vs-premium royalty model decisions, Content ID choices and rights/originality assertions.",
    notes: "Public research confirmed RouteNote's active distribution site, free and premium plans, global store delivery and independent artist workflow. No account was created, no release was uploaded, no store delivery was configured, no payment was attempted and no SMTP/MX probe was performed."
  },
  {
    name: "Amuse Self-Service Distribution and Artist Services",
    websiteUrl: "https://www.amuse.io/",
    submissionUrl: "https://artist.amuse.io/",
    sourceUrl: "https://www.amuse.io/",
    sourceType: "automation_run_65_public_research",
    country: "Sweden / worldwide music distribution and artist services platform",
    language: "en",
    genres: ["amuse", "digital-distribution", "artist-services", "label-services", "streaming-services", "royalties", "release-strategy", "subscription-required", "paid-route", "manual-review"],
    submissionMethod: "official-amuse-paid-account-route-for-self-service-distribution-and-artist-label-services",
    feeRequired: true,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Amuse's current self-service distribution route is subscription-based and also exposes selective Artist & Label Services; human review is required for paid plan selection, account/login, release upload, metadata, royalty/payout setup, artist-services eligibility, rights/originality and contract/terms decisions.",
    notes: "Public research confirmed Amuse's active distribution and Artist & Label Services site, plans starting from a paid annual/monthly price, major-platform distribution and sign-in/get-started routes. No account, subscription, payment, upload, application, contract step or SMTP/MX probe was performed."
  }
];
