import type { PlatformInput } from '../models/types.js';

export const run74SeedPlatforms: PlatformInput[] = [
  {
    name: "WFMU Send Music to Music Director",
    websiteUrl: "https://wfmu.org/",
    submissionUrl: "https://wfmu.org/sendmusic.html",
    sourceUrl: "https://wfmu.org/sendmusic.html",
    sourceType: "automation_run_74_public_research",
    country: "United States / New Jersey and New York freeform independent radio airplay consideration route",
    language: "en",
    genres: ["wfmu", "freeform-radio", "independent-radio", "radio-airplay", "music-director", "physical-mail", "cd", "vinyl", "cassette", "cdr", "electronic", "dub", "reggae", "world", "experimental", "free", "manual-review"],
    submissionMethod: "official-wfmu-send-music-route-to-music-director-for-airplay-review",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "WFMU publishes an official Send Music route for material review by the Music Director; human review is required for physical package selection, address routing, CD/vinyl/cassette/CD-R preparation, release metadata, clean/explicit labeling, rights/originality assertions and station/freeform-program fit decisions.",
    notes: "Public research confirmed WFMU as an active independent freeform radio station with current 2026 schedule/archive activity and an official Send Music page listing Music Director review instructions and postal/UPS/FedEx routes. No package was mailed, no form was submitted, no email was sent, no contact page was decoded and no validation control was bypassed."
  },
  {
    name: "FBi Radio Music Submissions",
    websiteUrl: "https://www.fbi.radio/",
    submissionUrl: "https://www.fbi.radio/pages/music-submissions",
    sourceUrl: "https://www.fbi.radio/pages/music-submissions",
    sourceType: "automation_run_74_public_research",
    country: "Australia / Sydney community radio and emerging music discovery route",
    language: "en",
    genres: ["fbi-radio", "sydney", "community-radio", "radio-airplay", "music-submissions", "business-email", "emerging-music", "electronic", "dance", "hip-hop", "reggae", "world", "local-music", "free", "manual-review"],
    submissionMethod: "official-fbi-radio-music-submissions-email-route-for-airplay-consideration",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "FBi Radio publishes an official music submissions email and requirements; human review is required because outbound email must not be automated, track/package selection, high-quality stream/download link permissions, metadata, local/Sydney/Australian relevance, rights/originality assertions and station/presenter fit must be checked manually.",
    notes: "Public research confirmed FBi Radio as an active Sydney emerging-music community station with 2026 site activity and official music submission instructions using music@fbiradio.com. The page also shows separate paid campaign/promotion contacts, so this is queued as free-first/manual and no paid side route was activated. No email was sent, no file was transferred, no CD was mailed and no SMTP/MX probing was performed."
  },
  {
    name: "PBS 106.7FM Submit Your Music",
    websiteUrl: "https://www.pbsfm.org.au/",
    submissionUrl: "https://www.pbsfm.org.au/submitmusic",
    sourceUrl: "https://www.pbsfm.org.au/submitmusic",
    sourceType: "automation_run_74_public_research",
    country: "Australia / Melbourne community radio route accepting local and international music",
    language: "en",
    genres: ["pbs-fm", "melbourne", "community-radio", "radio-airplay", "submit-music-form", "physical-mail", "captcha", "electronic", "dub", "reggae", "world", "soul", "jazz", "independent-music", "free", "manual-review"],
    submissionMethod: "official-pbs-fm-submit-your-music-form-and-physical-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "PBS publishes an official Submit Your Music form and physical submission route; human review is required because the form includes CAPTCHA/anti-spam handling, track/download field completion, local/international context, physical-copy decisions, metadata, rights/originality assertions and station/program fit checks.",
    notes: "Public research confirmed PBS 106.7FM as an active Melbourne community broadcaster with current 2026 content and a public Submit Your Music page for local and international acts. The form fields and CAPTCHA were identified from the public page only. No form was submitted, no CAPTCHA was bypassed, no file was uploaded, no physical copy was mailed and no validation control was bypassed."
  },
  {
    name: "Triple R 102.7FM Submit Music",
    websiteUrl: "https://www.rrr.org.au/",
    submissionUrl: "https://www.rrr.org.au/get-involved/submit-music",
    sourceUrl: "https://www.rrr.org.au/get-involved/submit-music",
    sourceType: "automation_run_74_public_research",
    country: "Australia / Melbourne independent community radio music submission route",
    language: "en",
    genres: ["triple-r", "3rrr", "melbourne", "community-radio", "radio-airplay", "music-submissions", "business-email", "physical-mail", "electronic", "dance", "dub", "reggae", "world", "independent-music", "free", "manual-review"],
    submissionMethod: "official-triple-r-submit-music-email-and-physical-route-for-station-airplay-consideration",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Triple R publishes an official Submit Music page and station music email; human review is required because outbound email must not be automated, direct-presenter versus station-wide routing, stream/download permissions, metadata, high-quality download availability, optional physical copy handling, rights/originality assertions and presenter/station fit must be checked manually.",
    notes: "Public research confirmed Triple R as an active Melbourne station broadcasting on 102.7FM/digital/online, with current 2026 site activity and official instructions to submit music to music@rrr.org.au or by physical delivery. No email was sent, no physical copy was mailed, no file was transferred and no SMTP/MX probing was performed."
  },
  {
    name: "2SER Submit Your Music for Airplay Consideration",
    websiteUrl: "https://www.2ser.com/",
    submissionUrl: "https://www.2ser.com/how-to-submit-music",
    sourceUrl: "https://www.2ser.com/how-to-submit-music",
    sourceType: "automation_run_74_public_research",
    country: "Australia / Sydney community radio digital music submission route",
    language: "en",
    genres: ["2ser", "sydney", "community-radio", "radio-airplay", "submit-music-form", "music-director", "business-email", "electronic", "experimental", "pop", "world", "reggae", "independent-music", "free", "manual-review"],
    submissionMethod: "official-2ser-submit-your-music-form-and-music-director-email-route-for-airplay-consideration",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "2SER publishes an official Submit Your Music page and Music Director email route; human review is required because the form/email must not be submitted automatically, physical copies are discouraged unless requested, track metadata, artist bio/social links, location, release date, rights/originality assertions and station/music-director fit must be checked manually.",
    notes: "Public research confirmed 2SER as an active Sydney community broadcaster with recent 2026 site activity, a public Submit Your Music form and a contact page listing submitmusic@2ser.com for Music Director airplay consideration. No form was submitted, no email was sent, no file was uploaded, no physical copy was mailed and no SMTP/MX probing was performed."
  }
];
