import type { PlatformInput } from '../models/types.js';

export const run71SeedPlatforms: PlatformInput[] = [
  {
    name: "WMSE 91.7FM Music Department Submissions",
    websiteUrl: "https://wmse.org/",
    submissionUrl: "https://wmse.org/about-wmse-radio/music-department/",
    sourceUrl: "https://wmse.org/about-wmse-radio/music-department/",
    sourceType: "automation_run_71_public_research",
    country: "United States / Milwaukee non-commercial freeform and eclectic music radio with global streaming",
    language: "en",
    genres: ["wmse", "college-radio", "community-radio", "freeform", "radio-airplay", "milwaukee", "electronic", "world", "reggae", "indie", "alternative", "vinyl", "cd", "cassette", "wetransfer", "music-director-email", "physical-mail", "fcc-clean", "free", "manual-review"],
    submissionMethod: "official-wmse-music-department-route-accepting-cd-vinyl-cassette-or-digital-download-to-music-director-email",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "WMSE publishes an official Music Department submission route accepting physical releases and digital download submissions to the Music Director; human review is required for format selection, at least four FCC-clean tracks for CDs, explicit-language labeling, WeTransfer/email handling, tracklist and contact-info prep, local-vs-general relevance, rights/originality assertions and program-host/station-fit decisions.",
    notes: "Public research confirmed the official WMSE Music Department page, 2026 station footer, active weekly top airplay and Local/Live programming, Music Director contact route, physical mail/drop-off route, CD/vinyl/cassette/digital acceptance, FCC-clean guidance and non-guaranteed DJ-driven airplay model. No email was sent, no file was transferred, no physical mail was sent, no form was submitted and no SMTP/MX probe was performed."
  },
  {
    name: "KFAI Music Department and Music Library",
    websiteUrl: "https://kfai.org/",
    submissionUrl: "https://kfai.org/about/contact/",
    sourceUrl: "https://kfai.org/about/contact/",
    sourceType: "automation_run_71_public_research",
    country: "United States / Minneapolis-Saint Paul volunteer-based community radio with multilingual music and arts programming",
    language: "en",
    genres: ["kfai", "community-radio", "radio-airplay", "minneapolis", "saint-paul", "world", "reggae", "soul", "funk", "jazz", "blues", "electronic", "multilingual", "music-library", "protected-email-route", "free", "manual-review"],
    submissionMethod: "official-kfai-contact-page-music-department-and-music-library-route-for-sharing-artist-music",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "KFAI publishes an official Music Department & Music Library contact route for artists who want to share music, but the crawler displays the route as a protected email link; human review is required for route handling without decoding masked contact data, email/package preparation, metadata, rights/originality assertions, community/station-fit review and expectations around no receipt confirmation.",
    notes: "Public research confirmed the official KFAI homepage and Contact page, 2026 station footer, fresh 2026 activity, playlists, 24/7 programming, Music Department & Music Library route and no-confirmation expectation. The contact was treated as protected/masked in the crawler and was not decoded. No email was sent, no form was submitted, no file was transferred, no account was used and no SMTP/MX probe was performed."
  },
  {
    name: "KUNM 89.9FM Music Director Contact Route",
    websiteUrl: "https://www.kunm.org/",
    submissionUrl: "https://www.kunm.org/contact-info",
    sourceUrl: "https://www.kunm.org/contact-info",
    sourceType: "automation_run_71_public_research",
    country: "United States / New Mexico public radio variety station with music shows and online streams",
    language: "en",
    genres: ["kunm", "public-radio", "radio-airplay", "new-mexico", "variety", "world", "reggae", "latin", "electronic", "roots", "public-radio-music", "music-director-email", "free", "manual-review"],
    submissionMethod: "official-kunm-contact-info-music-director-email-route-for-music-department-consideration",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "KUNM publishes an official Contact Info page with Music Director phone and music@kunm.org route; human review is required for targeted email preparation, show/genre fit, clean/radio edit labeling, metadata, artist context, rights/originality assertions, New Mexico relevance where applicable and avoidance of PSA/news/general-feedback misrouting.",
    notes: "Public research confirmed the official KUNM homepage, 2026 footer, current live streams, fresh July 2026 news/activity, Music navigation/playlists, Contact Info page and public Music Director contact route. No email was sent, no form was submitted, no file was transferred, no phone contact was made, no account was used and no SMTP/MX probe was performed."
  },
  {
    name: "XRAY.fm Music Submissions",
    websiteUrl: "https://xray.fm/",
    submissionUrl: "https://xray.fm/contact",
    sourceUrl: "https://xray.fm/contact",
    sourceType: "automation_run_71_public_research",
    country: "United States / Portland and Nehalem community radio with freeform music programming and online streaming",
    language: "en",
    genres: ["xray-fm", "kxry", "community-radio", "freeform", "radio-airplay", "portland", "nehalem", "independent-music", "electronic", "hip-hop", "reggae", "world", "music-submissions-email", "external-guidelines", "free", "manual-review"],
    submissionMethod: "official-xray-fm-contact-page-music-submissions-email-route-with-linked-google-drive-guidelines",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "XRAY.fm publishes an official Music Submissions route to submissions@xray.fm and links external Google Drive submission guidelines; human review is required for guideline reading, email/package preparation, download or stream-link choice, metadata, rights/originality assertions, FCC/station fit and avoidance of unrelated DJ/volunteer/partner routes.",
    notes: "Public research confirmed the official XRAY.fm homepage, live/now-playing station pages, Contact page, KXRY 107.1/91.1 and 91.7 station details, public Music Submissions email route and external guidelines link. No email was sent, no external Google Drive guideline document was edited or bypassed, no file was transferred, no form was submitted and no SMTP/MX probe was performed."
  },
  {
    name: "WYEP Pittsburgh Area Music Submissions",
    websiteUrl: "https://www.wyep.org/",
    submissionUrl: "https://www.wyep.org/wyep-pittsburgh-area-music-submissions",
    sourceUrl: "https://www.wyep.org/wyep-pittsburgh-area-music-submissions",
    sourceType: "automation_run_71_public_research",
    country: "United States / Pittsburgh independent public music station with local-artist airplay route and online streaming",
    language: "en",
    genres: ["wyep", "public-radio", "indie-radio", "radio-airplay", "pittsburgh", "western-pennsylvania", "local-music", "indie", "americana", "rock", "soul", "world", "link-submission", "physical-mail", "fcc-clean", "free", "manual-review"],
    submissionMethod: "official-wyep-pittsburgh-area-music-submissions-route-via-localmusic-email-link-or-hard-copy-mail",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "WYEP publishes an official Pittsburgh Area Music Submissions route via localmusic@wyep.org or hard copy mail; human review is required for Pittsburgh/Western Pennsylvania eligibility, link vs physical routing, 2-3 radio-track suggestions, contact/location/artist bio prep, FCC-clean checks, specialty-show targeting, rights/originality assertions and station-fit decisions.",
    notes: "Public research confirmed the official WYEP homepage, 2026 footer, active current programming/news posts, Pittsburgh Music Submissions page, Local 913/Pittsburgh Music Hour support, localmusic@wyep.org route, hard-copy mail route, FCC-clean requirements and limited local-airplay eligibility. No email was sent, no form was submitted, no file was transferred, no physical mail was sent and no SMTP/MX probe was performed."
  }
];