import type { PlatformInput } from '../models/types.js';

export const run73SeedPlatforms: PlatformInput[] = [
  {
    name: "BBC Music Introducing Uploader",
    websiteUrl: "https://www.bbc.co.uk/introducing",
    submissionUrl: "https://www.bbc.co.uk/introducing/uploader",
    sourceUrl: "https://www.bbc.co.uk/introducing/uploader",
    sourceType: "automation_run_73_public_research",
    country: "United Kingdom / BBC local and national new-music discovery network for unsigned and under-the-radar UK talent",
    language: "en",
    genres: ["bbc", "bbc-introducing", "radio-airplay", "uk", "unsigned", "uploader", "new-music", "electronic", "dance", "alternative", "hip-hop", "world", "reggae", "account-login", "ugc-terms", "free", "manual-review"],
    submissionMethod: "official-bbc-music-introducing-uploader-account-route-for-uk-new-music",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "BBC Music Introducing is a public upload platform for unsigned and under-the-radar UK music; human review is required for BBC account/login, UK postcode/local-show eligibility, uploader access, UGC/terms acceptance, track selection, metadata, rights/originality assertions, clean/radio-edit labeling where needed and editorial/radio-fit decisions.",
    notes: "Public research confirmed BBC Music Introducing as an active BBC music upload platform and documented uploader workflow in which artists upload music for Introducing producers/presenters and provide postcode-based routing to the nearest show. Direct automated interaction with the uploader was not attempted. No account was created, no login was used, no upload was performed, no form was submitted, no email was sent and no CAPTCHA or validation control was bypassed."
  },
  {
    name: "Triple J Unearthed Artist Upload",
    websiteUrl: "https://triplejunearthed.com/",
    submissionUrl: "https://triplejunearthed.com/upload",
    sourceUrl: "https://triplejunearthed.com/upload",
    sourceType: "automation_run_73_public_research",
    country: "Australia / ABC Triple J independent Australian music discovery platform and digital radio route",
    language: "en",
    genres: ["triple-j", "unearthed", "abc-australia", "australia", "independent-music", "radio-airplay", "artist-upload", "digital-radio", "electronic", "dance", "hip-hop", "indie", "alternative", "world", "reggae", "account-login", "free", "manual-review"],
    submissionMethod: "official-triple-j-unearthed-upload-route-for-independent-australian-artists",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Triple J Unearthed is a public Australian independent-music upload and discovery platform; human review is required for account/profile login, Australian-artist eligibility, track upload, metadata, release context, rights/originality assertions, competition or airplay terms and editorial/radio-fit decisions.",
    notes: "Public research confirmed Triple J Unearthed as an active Australian digital radio and online music discovery platform for independent Australian musicians with uploaded music used for discovery and airplay consideration. No account was created, no login was used, no upload was performed, no form was submitted, no email was sent and no CAPTCHA or validation control was bypassed."
  },
  {
    name: "Audiomack Creator Upload",
    websiteUrl: "https://audiomack.com/",
    submissionUrl: "https://audiomack.com/upload",
    sourceUrl: "https://audiomack.com/upload",
    sourceType: "automation_run_73_public_research",
    country: "Worldwide / New York-based music streaming and audio discovery platform with creator upload tools",
    language: "en",
    genres: ["audiomack", "streaming", "creator-upload", "audio-discovery", "hip-hop", "afrobeats", "reggae", "dancehall", "electronic", "world", "latin", "free-upload", "monetization", "account-login", "dmca", "fingerprinting", "free", "manual-review"],
    submissionMethod: "official-audiomack-creator-upload-route-for-artist-track-and-release-distribution",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Audiomack provides public creator upload tools for artists and podcasters; human review is required for account/login, upload workflow, track/release metadata, rights/originality assertions, DMCA/fingerprinting/manual-curation boundaries, monetization settings, optional promotional choices and platform-fit decisions.",
    notes: "Public research confirmed Audiomack as an active registered-user streaming and audio discovery platform where artists can upload music, with free upload/storage positioning, DMCA/fingerprinting/manual curation controls and current platform activity signals. No account was created, no login was used, no upload was performed, no form was submitted, no email was sent and no anti-abuse or validation control was bypassed."
  },
  {
    name: "Bandcamp Artist and Label Upload Storefront",
    websiteUrl: "https://bandcamp.com/",
    submissionUrl: "https://bandcamp.com/artists",
    sourceUrl: "https://bandcamp.com/artists",
    sourceType: "automation_run_73_public_research",
    country: "Worldwide / artist and label storefront distribution platform with direct fan sales",
    language: "en",
    genres: ["bandcamp", "artist-storefront", "label-storefront", "direct-to-fan", "digital-download", "streaming", "electronic", "dub", "reggae", "world", "bass-music", "independent-music", "pricing", "commission", "payment-settings", "account-login", "freemium", "manual-review"],
    submissionMethod: "official-bandcamp-artist-and-label-account-route-for-uploading-music-and-storefront-releases",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Bandcamp provides public artist and label upload/storefront tools, but human review is required for account/login, release upload, pricing and payment settings, commission/sales implications, merch or download choices, metadata, rights/originality assertions, policy compliance including AI-generated-content restrictions and artist-brand fit.",
    notes: "Public research confirmed Bandcamp as an active artist/label upload and storefront platform where artists and labels upload music, control pricing and sales and operate under Bandcamp commission/sales mechanics. Recent public reporting also confirmed policy movement around AI-generated music restrictions, making rights/originality review mandatory. No account was created, no login was used, no upload was performed, no pricing/payment route was activated and no anti-abuse or validation control was bypassed."
  },
  {
    name: "Jamendo Artist Upload and Licensing",
    websiteUrl: "https://www.jamendo.com/",
    submissionUrl: "https://artists.jamendo.com/",
    sourceUrl: "https://artists.jamendo.com/",
    sourceType: "automation_run_73_public_research",
    country: "Worldwide / Luxembourg independent-artist streaming and music-licensing marketplace",
    language: "en",
    genres: ["jamendo", "artist-upload", "music-licensing", "sync-licensing", "creative-commons", "independent-music", "royalty-free", "commercial-license", "world", "electronic", "reggae", "dub", "cinematic", "account-login", "free", "manual-review"],
    submissionMethod: "official-jamendo-artist-platform-route-for-uploading-music-and-licensing-catalogs",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Jamendo provides public artist upload and licensing opportunities for independent music; human review is required for account/login, artist eligibility, upload workflow, Creative Commons or licensing choices, collecting-rights-society restrictions, metadata, sync/commercial license rights, originality assertions and catalog-fit decisions.",
    notes: "Public research confirmed Jamendo as an active worldwide independent-music and licensing platform for artists to become known and earn through licensing. Because licensing and rights-society eligibility can materially affect MarcsMusic rights, this route is queued only for manual review. No account was created, no login was used, no upload was performed, no license was selected, no form was submitted and no anti-abuse or validation control was bypassed."
  }
];
