import type { PlatformInput } from '../models/types.js';

export const run70SeedPlatforms: PlatformInput[] = [
  {
    name: "WNCW Submit Music",
    websiteUrl: "https://www.wncw.org/",
    submissionUrl: "https://www.wncw.org/submit-music",
    sourceUrl: "https://www.wncw.org/submit-music",
    sourceType: "automation_run_70_public_research",
    country: "United States / North Carolina public radio AAA and roots station with global streaming",
    language: "en",
    genres: ["wncw", "public-radio", "radio-airplay", "aaa", "americana", "folk", "blues", "jazz", "reggae", "world", "rock", "bluegrass", "indie", "physical-mail", "music-submissions-email", "download-link", "free", "manual-review"],
    submissionMethod: "official-wncw-submit-music-route-for-cd-physical-mail-or-wav-mp3-dropbox-google-drive-link-email-to-programming-department",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "WNCW publishes an official Submit Music route for CD submissions by mail and digital wav/mp3 links by email; human review is required for CD-vs-digital routing, Dropbox/Google Drive link selection, one-sheet/bio prep, release metadata, rights/originality assertions, local/show-detail context and station-fit decisions.",
    notes: "Public research confirmed the official WNCW Submit Music page, active station site/new-music programming, Programming Department physical mail route, digital wav/mp3 Dropbox or Google Drive email route, one-sheet/bio guidance, album/single/EP policy and no-airplay-status-request guidance. No email was sent, no form was submitted, no file was transferred, no physical mail was sent and no SMTP/MX probe was performed."
  },
  {
    name: "WXDU 88.7FM Music Submissions",
    websiteUrl: "https://www.wxdu.org/",
    submissionUrl: "https://www.wxdu.org/contact.html",
    sourceUrl: "https://www.wxdu.org/contact.html",
    sourceType: "automation_run_70_public_research",
    country: "United States / Duke University non-commercial college radio with online streaming",
    language: "en",
    genres: ["wxdu", "college-radio", "radio-airplay", "durham", "independent-music", "progressive", "alternative", "local-music", "bandcamp-yum-codes", "physical-mail", "music-director-email", "free", "manual-review"],
    submissionMethod: "official-wxdu-contact-and-faq-route-for-airplay-submissions-via-music-director-email-with-bandcamp-yum-codes-preferred-or-physical-mail",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "WXDU publishes an official airplay submission route via music@wxdu.org with Bandcamp YUM codes preferred, plus a Music Director physical-mail route; human review is required for email vs mail routing, Bandcamp code/download selection, music info and artwork prep, rights/originality assertions, touring/local context and freeform station-fit decisions.",
    notes: "Public research confirmed the official WXDU FAQ and Contact pages, station activity, Music Director route, music@wxdu.org airplay route, Bandcamp YUM-code preference and physical mailing address. No email was sent, no file/code was transferred, no form was submitted, no physical mail was sent and no SMTP/MX probe was performed."
  },
  {
    name: "WXYC 89.3FM Music Department Submissions",
    websiteUrl: "https://wxyc.org/",
    submissionUrl: "https://wxyc.org/contact",
    sourceUrl: "https://wxyc.org/contact",
    sourceType: "automation_run_70_public_research",
    country: "United States / UNC-Chapel Hill student-run freeform college radio with internet stream",
    language: "en",
    genres: ["wxyc", "college-radio", "freeform", "radio-airplay", "chapel-hill", "music-director-email", "physical-mail", "electronic", "hip-hop", "reggae", "dancehall", "world", "experimental", "free", "manual-review"],
    submissionMethod: "official-wxyc-contact-route-for-music-submissions-and-distribution-concerns-via-music-director-email-plus-physical-music-department-mail",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "WXYC publishes an official contact route for music submissions or distribution concerns through md@wxyc.org and a Music Department physical-mail address; human review is required for email vs physical route selection, non-PSA/non-outreach routing, metadata, rights/originality assertions, clean/edit labeling where needed and freeform programming fit.",
    notes: "Public research confirmed the official WXYC homepage and Contact page, 2026 schedule/activity, student-run freeform positioning, music submissions/distribution email route and Music Department mailing address. No email was sent, no form was submitted, no physical mail was sent, no file was transferred and no SMTP/MX probe was performed."
  },
  {
    name: "WUAG 103.1FM Music Submission Form",
    websiteUrl: "https://wuag.uncg.edu/",
    submissionUrl: "https://wuag.uncg.edu/music-submissions/",
    sourceUrl: "https://wuag.uncg.edu/music-submissions/",
    sourceType: "automation_run_70_public_research",
    country: "United States / UNC Greensboro student-run non-commercial campus radio with online streaming",
    language: "en",
    genres: ["wuag", "college-radio", "campus-radio", "radio-airplay", "greensboro", "local-music", "wav", "mp3", "upload-form", "google-drive", "dropbox", "fcc-clean", "free", "manual-review"],
    submissionMethod: "official-wuag-music-submission-form-with-wav-mp3-file-upload-or-dropbox-google-drive-link-fallback-for-radio-consideration",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "WUAG publishes an official Music Submission Form with wav/mp3 upload fields and Dropbox/Google Drive link fallback; human review is required for form completion, file upload or link permission setup, NC/local eligibility, FCC-clean edit assertions, track/release metadata, rights/originality assertions and station-fit decisions.",
    notes: "Public research confirmed the official WUAG homepage, About/FAQ pages, 24/7 station operation, Music + Productions Director contact, Music Submission Form, wav/mp3 upload option, Dropbox/Google Drive fallback, share-permission guidance and FCC-violation warning. The form was identified but not submitted, no file was uploaded, no link was transferred and no validation controls were bypassed."
  },
  {
    name: "WUOG 90.5FM Submit Music",
    websiteUrl: "https://wuog.org/",
    submissionUrl: "https://wuog.org/contact/",
    sourceUrl: "https://wuog.org/contact/",
    sourceType: "automation_run_70_public_research",
    country: "United States / University of Georgia student-run alternative college radio with web stream",
    language: "en",
    genres: ["wuog", "college-radio", "alternative-radio", "radio-airplay", "athens", "independent-artists", "local-music", "album-submission", "physical-mail", "music-director-email", "free", "manual-review"],
    submissionMethod: "official-wuog-contact-route-for-album-airtime-consideration-by-mail-to-music-directors-or-local-music-directors-with-public-director-contact-emails",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "WUOG publishes an official Submit Music route for album consideration by physical mail to Music Directors or Local Music Directors and lists public director contact emails; human review is required for album eligibility, physical package selection, local-vs-general routing, director contact boundaries, metadata, rights/originality assertions and WUOG airtime rules/station fit.",
    notes: "Public research confirmed the official WUOG homepage and Contact page, 26,000-watt student-run alternative station positioning, web stream, active recent station posts, WUOG airtime rules for smaller artists, Submit Music instructions, physical mailing route and public Music Director/Local Music Director contacts. No email was sent, no contact form was submitted, no physical mail was sent, no file was transferred and no SMTP/MX probe was performed."
  }
];