import type { PlatformInput } from '../models/types.js';

export const run77SeedPlatforms: PlatformInput[] = [
  {
    name: "Soho Radio Music Submission",
    websiteUrl: "https://sohoradio.com/",
    submissionUrl: "https://sohoradio.com/contact/",
    sourceUrl: "https://sohoradio.com/contact/",
    sourceType: "automation_run_77_public_research",
    country: "United Kingdom / London and New York independent online radio music submission email route",
    language: "en",
    genres: ["soho-radio", "london", "new-york", "independent-radio", "online-radio", "radio-airplay", "music-submission-email", "electronic", "dub", "reggae", "world", "soul", "jazz", "house", "free", "manual-review"],
    submissionMethod: "official-soho-radio-contact-page-music-submission-email-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Soho Radio publishes an official music submission email on its contact page, but human review is required for outbound email drafting, track selection, download or streaming link permissions, metadata, clean/explicit labeling, release context and station/show fit. No email should be sent automatically.",
    notes: "Public research confirmed Soho Radio has recent 2026 show activity and an official contact page listing music@sohoradiolondon.com for Music submission. The contact form and email route were identified only. No email was sent, no form was submitted, no file was transferred and no SMTP/MX probing was performed."
  },
  {
    name: "NTS Radio Show Proposal Form",
    websiteUrl: "https://www.nts.live/",
    submissionUrl: "https://www.nts.live/contact",
    sourceUrl: "https://www.nts.live/contact",
    sourceType: "automation_run_77_public_research",
    country: "United Kingdom / global online independent radio show proposal route with audio-link demo fields",
    language: "en",
    genres: ["nts", "online-radio", "radio-show-proposal", "dj-mix", "hosted-radio", "soundcloud", "mixcloud", "youtube", "electronic", "dub", "reggae", "world", "bass-music", "experimental", "free", "manual-review"],
    submissionMethod: "official-nts-radio-show-proposal-form-with-audio-demo-links",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "NTS publishes an official radio show proposal form with hosted/mainly-music options and audio demo links; human review is required because this is a curated show-proposal route rather than a simple track drop, and proposal copy, up to three SoundCloud/Mixcloud/YouTube links, genre tags, artist biography and editorial fit must be approved before form submission.",
    notes: "Public research confirmed NTS as an active 24/7 radio platform with an official Radio Show Proposal form requesting a proposal, show type, audio links and biography details. No proposal was submitted, no login was used, no audio link was posted through the form and no validation control was bypassed."
  },
  {
    name: "Groover Paid Music Promotion Submission Platform",
    websiteUrl: "https://groover.co/en/",
    submissionUrl: "https://groover.co/en/",
    sourceUrl: "https://groover.co/en/",
    sourceType: "automation_run_77_public_research",
    country: "France / global paid artist-to-curator, radio, playlist, label and DJ pitching marketplace",
    language: "en",
    genres: ["groover", "music-promotion", "curators", "playlist-pitching", "radio", "labels", "djs", "electronic", "dub", "reggae", "world", "hip-hop", "pop", "paid", "account-login", "manual-review"],
    submissionMethod: "official-groover-campaign-upload-and-paid-curator-credit-route",
    feeRequired: true,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Groover is a legitimate paid campaign platform where artists upload a song or demo and choose curators/pros using credits; human review is mandatory because account creation, curator selection, paid Grooviz credit purchase, budget approval, pitch copy, rights/originality, genre targeting and anti-payola/editorial-compliance checks cannot be automated.",
    notes: "Public research confirmed Groover's current official site, 2026 footer, 3,000+ curators/pros positioning, upload/pitch workflow and paid credit model starting at 2 Grooviz per contact. This route was queued as paid/manual only. No account was created, no payment was made, no campaign was started, no file was uploaded and no contact was messaged."
  },
  {
    name: "Musosoup Artist Campaign Submission",
    websiteUrl: "https://musosoup.com/",
    submissionUrl: "https://app.musosoup.com/",
    sourceUrl: "https://musosoup.com/",
    sourceType: "automation_run_77_public_research",
    country: "United Kingdom / global freemium music promotion platform connecting independent artists with curators, playlists, press and radio",
    language: "en",
    genres: ["musosoup", "music-promotion", "curators", "press", "playlisting", "radio", "campaign", "electronic", "house", "techno", "reggae", "world", "trip-hop", "downtempo", "freemium", "payment-approval", "account-login", "manual-review"],
    submissionMethod: "official-musosoup-artist-submission-review-and-campaign-activation-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Musosoup allows artists to submit music with no upfront cost, but campaign activation requires approval and a campaign fee if successful; human review is required for account creation, upload or music-link selection, campaign activation/payment approval, curator offers, release timing, AI/botted-playlist policy checks, metadata and brand fit.",
    notes: "Public research confirmed Musosoup's official Submit music route, free initial upload/link submission, review stage up to 24 hours, campaign fee after approval, free and paid curator offer mechanics, 2026 site footer and July 2026 blog activity. No account was created, no campaign was activated, no payment was made, no upload was performed and no curator offer was accepted."
  },
  {
    name: "Soundplate Free Playlist Submission System",
    websiteUrl: "https://soundplate.com/",
    submissionUrl: "https://play.soundplate.com/",
    sourceUrl: "https://soundplate.com/",
    sourceType: "automation_run_77_public_research",
    country: "United Kingdom / global playlist submission and music marketing tool for independent artists",
    language: "en",
    genres: ["soundplate", "playlist-submissions", "spotify-playlists", "deezer-playlists", "music-marketing", "house", "electronic", "dance", "reggae", "dancehall", "trip-hop", "downtempo", "synthwave", "free", "anti-bot-verification", "manual-review"],
    submissionMethod: "official-soundplate-submit-music-to-playlists-route-with-verification-gated-play-app",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Soundplate publishes free playlist submission routes, but the Play Soundplate submission app displayed request-verification/anti-bot handling; human review is required for playlist selection, Spotify/Deezer link choice, any app validation, genre fit, rights/originality and platform terms. Anti-bot checks must not be bypassed.",
    notes: "Public research confirmed Soundplate's official homepage lists Submit Music and Submit Music to Playlists routes, genre filters relevant to MarcsMusic including House/Electronic/Dance, Reggae/Dancehall and TripHop/Electronica/Downtempo, and 2026 site activity. The Play Soundplate route displayed request verification and was not interacted with. No form was submitted, no anti-bot control was bypassed, no playlist was contacted and no file was uploaded."
  }
];
