import type { PlatformInput } from '../models/types.js';

export const run72SeedPlatforms: PlatformInput[] = [
  {
    name: "CIUT 89.5 FM Toronto Music Submissions",
    websiteUrl: "https://ciut.fm/",
    submissionUrl: "https://ciut.fm/contact/",
    sourceUrl: "https://ciut.fm/contact/",
    sourceType: "automation_run_72_public_research",
    country: "Canada / Toronto campus and community radio with global online streaming",
    language: "en",
    genres: ["ciut", "campus-radio", "community-radio", "radio-airplay", "toronto", "canada", "world", "reggae", "electronic", "hip-hop", "latin", "folk", "new-music-email", "free", "manual-review"],
    submissionMethod: "official-ciut-contact-page-newmusic-email-route-for-music-submission",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "CIUT publishes an official Contact page route instructing artists to contact newmusic@ciut.fm to submit music; human review is required for targeted email preparation, track/package selection, metadata, artist bio, rights/originality assertions, clean/radio-edit labeling where needed, Toronto/community-radio fit and avoidance of unrelated advertising or general contact routes.",
    notes: "Public research confirmed the official CIUT Contact page, newmusic@ciut.fm route for music submissions, direct station contact list, mailing address, campus/community-radio identity and 2026 site footer. No email was sent, no form was submitted, no file was transferred, no physical mail was sent, no account was used and no SMTP/MX probe was performed."
  },
  {
    name: "KGNU Community Radio Music Department Contact Form",
    websiteUrl: "https://kgnu.org/",
    submissionUrl: "https://kgnu.org/contact-us/",
    sourceUrl: "https://kgnu.org/contact-us/",
    sourceType: "automation_run_72_public_research",
    country: "United States / Boulder and Denver independent community radio with online music programming",
    language: "en",
    genres: ["kgnu", "community-radio", "radio-airplay", "boulder", "denver", "colorado", "world", "reggae", "electronic", "hip-hop", "folk", "jazz", "local-music", "contact-form", "recaptcha-v3", "protected-email-route", "free", "manual-review"],
    submissionMethod: "official-kgnu-contact-staff-or-dj-form-with-music-department-routing",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "KGNU publishes an official Contact Staff or DJ form with Department routing that includes Music and visible reCaptcha v3 protection; human review is required for form completion, CAPTCHA handling without bypass, department/message routing, protected email handling without decoding, music-package preparation, metadata, rights/originality assertions and station/programming fit decisions.",
    notes: "Public research confirmed the official KGNU homepage, current live broadcast and music navigation, fresh July 2026 activity, Contact page, Contact Staff or DJ form, Music department routing and reCaptcha v3 marker. Protected contacts were not decoded. No form was submitted, no email was sent, no file was transferred, no account was used and no SMTP/MX probe was performed."
  },
  {
    name: "WPKN 89.5 Community Radio Music Submission",
    websiteUrl: "https://wpkn.org/",
    submissionUrl: "https://wpkn.org/contact-wpkn/",
    sourceUrl: "https://wpkn.org/contact-wpkn/",
    sourceType: "automation_run_72_public_research",
    country: "United States / Bridgeport Connecticut community radio with freeform programming and worldwide stream",
    language: "en",
    genres: ["wpkn", "community-radio", "freeform", "radio-airplay", "connecticut", "bridgeport", "world", "reggae", "jazz", "electronic", "roots", "library-airplay", "music-director", "protected-email-route", "physical-mail", "free", "manual-review"],
    submissionMethod: "official-wpkn-contact-page-music-director-route-and-physical-library-airplay-submissions",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "WPKN publishes an official Music Submission route on its Contact page, including a Music Director contact displayed as a protected email link and physical submissions for WPKN library/airplay consideration; human review is required for protected-contact handling without decoding, physical-vs-digital route selection, package prep, metadata, rights/originality assertions and freeform station-fit decisions.",
    notes: "Public research confirmed the official WPKN homepage, current schedule and playlist activity, 2026 page updates, Contact page, Music Submission route, Music Director protected email link and physical submissions to the station mailing address for library/airplay consideration. No protected contact was decoded, no email was sent, no physical mail was sent, no file was transferred and no SMTP/MX probe was performed."
  },
  {
    name: "WFUV Public Media Contact Form and Music Discovery Route",
    websiteUrl: "https://wfuv.org/",
    submissionUrl: "https://wfuv.org/contact",
    sourceUrl: "https://wfuv.org/contact",
    sourceType: "automation_run_72_public_research",
    country: "United States / New York listener-supported public media music discovery station with online music programming",
    language: "en",
    genres: ["wfuv", "public-radio", "music-discovery", "radio-airplay", "new-york", "aaa", "indie", "alternative", "world", "singer-songwriter", "contact-form", "javascript-required", "honeypot-antispam", "free", "manual-review"],
    submissionMethod: "official-wfuv-site-contact-form-for-music-related-outreach-and-editorial-routing",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "WFUV publishes an official Contact form on its Music Discovery public-media site; human review is required because the form requires JavaScript, includes an anti-spam blank field, does not expose a safe auto-submit music-specific workflow, and requires subject/message preparation, editorial/music fit review, metadata, rights/originality assertions and routing judgment.",
    notes: "Public research confirmed the official WFUV Contact page, Music Discovery positioning, music navigation, public contact form fields, JavaScript requirement and anti-spam blank-field behavior. No form was submitted, no account was used, no contact was guessed, no email was sent, no CAPTCHA or validation behavior was bypassed and no SMTP/MX probe was performed."
  },
  {
    name: "WRFL 88.1 FM Lexington Contact and Rotation Review Route",
    websiteUrl: "https://wrfl.fm/",
    submissionUrl: "https://wrfl.fm/contact",
    sourceUrl: "https://wrfl.fm/contact",
    sourceType: "automation_run_72_public_research",
    country: "United States / Lexington Kentucky student-run independent and alternative radio station with live streaming",
    language: "en",
    genres: ["wrfl", "college-radio", "student-radio", "independent-radio", "alternative", "radio-airplay", "lexington", "kentucky", "world", "electronic", "hip-hop", "local-music", "general-rotation", "specialty-rotation", "contact-email", "physical-mail", "free", "manual-review"],
    submissionMethod: "official-wrfl-contact-page-general-contact-route-for-appropriate-director-routing-and-station-fit-review",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "WRFL publishes an official Contact page advising users to contact the appropriate director and to use contact@wrfl.fm when unsure; human review is required for music-specific routing, local/general/specialty rotation fit, physical or digital package preparation, clean/radio edit labeling, metadata, rights/originality assertions and avoidance of sign-in or unrelated event/join/donation routes.",
    notes: "Public research confirmed the official WRFL homepage, active June/Summer 2026 programming and news, playlist/rotation sections, Contact page, public contact@wrfl.fm fallback route, station mailing address, independent/alternative station identity and sign-in route that was not used. No account was created, no email was sent, no form was submitted, no file was transferred, no physical mail was sent and no SMTP/MX probe was performed."
  }
];