import type { PlatformInput } from '../models/types.js';

export const run79SeedPlatforms: PlatformInput[] = [
  {
    name: "WPRB 103.3 FM Music Submissions",
    websiteUrl: "https://wprb.com/",
    submissionUrl: "https://wprb.com/music-submissions/",
    sourceUrl: "https://wprb.com/music-submissions/",
    sourceType: "automation_run_79_public_research",
    country: "United States / Princeton, New Jersey independent college freeform radio music submission route",
    language: "en",
    genres: ["wprb", "college-radio", "freeform-radio", "radio-airplay", "music-director-email", "physical-mail", "electronic", "dub", "reggae", "world", "bass-music", "indie", "alternative", "free", "manual-review"],
    submissionMethod: "official-wprb-music-submissions-page-email-and-physical-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required for physical-vs-email routing, outbound email approval, track/package selection, metadata, clean/explicit labeling, rights/originality assertions and freeform station fit.",
    notes: "Public research confirmed WPRB's official Music Submissions page, current site copyright/activity and public music@wprb.com route with physical submissions prioritized. No email was sent, no physical mail was prepared, no form was submitted and no SMTP/MX probing was performed."
  },
  {
    name: "KALX 90.7FM Berkeley Airplay Submissions",
    websiteUrl: "https://kalx.berkeley.edu/",
    submissionUrl: "https://kalx.berkeley.edu/about/contact/",
    sourceUrl: "https://kalx.berkeley.edu/about/contact/",
    sourceType: "automation_run_79_public_research",
    country: "United States / Berkeley college and community radio physical airplay submission route",
    language: "en",
    genres: ["kalx", "college-radio", "community-radio", "freeform-radio", "radio-airplay", "music-director-email", "physical-cd-lp", "electronic", "dub", "reggae", "world", "indie", "alternative", "free", "manual-review"],
    submissionMethod: "official-kalx-contact-page-music-director-physical-cd-lp-airplay-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KALX currently accepts only physical professionally pressed CDs or LPs for airplay, rejects downloads/file transfers/streaming links, and requires package prep, clean labeling, metadata and station-fit review.",
    notes: "Public research confirmed KALX's active 2026 site, recent playlist/programming, official Music Directors contact and strict physical-only airplay instructions. No email was sent, no physical mail was prepared, no digital route was attempted and no SMTP/MX probing was performed."
  },
  {
    name: "KSPC 88.7FM Music Submissions",
    websiteUrl: "https://kspc.org/",
    submissionUrl: "https://kspc.org/contact/music-submissions/",
    sourceUrl: "https://kspc.org/contact/music-submissions/",
    sourceType: "automation_run_79_public_research",
    country: "United States / Claremont California college and community radio album or EP submission route",
    language: "en",
    genres: ["kspc", "college-radio", "community-radio", "freeform-radio", "radio-airplay", "music-submission-email", "physical-mail", "cloud-download-link", "electronic", "dub", "reggae", "world", "indie", "alternative", "free", "manual-review"],
    submissionMethod: "official-kspc-music-submissions-page-digital-email-and-physical-cd-record-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KSPC accepts albums/EPs but not singles/demos, forbids pay-for-play and substantially AI-generated work, and requires protected-email handling, download permission checks, package prep, metadata and station fit.",
    notes: "Public research confirmed KSPC's official Music Submissions page and 2026 site activity. A protected email route was observed but not decoded. No email was sent, no cloud link was opened for upload/download, no physical mail was prepared and no SMTP/MX probing was performed."
  },
  {
    name: "WUSC 90.5 FM Outreach Music Director Submissions",
    websiteUrl: "https://www.wusc.fm/",
    submissionUrl: "https://www.wusc.fm/page/contact",
    sourceUrl: "https://www.wusc.fm/page/contact",
    sourceType: "automation_run_79_public_research",
    country: "United States / Columbia South Carolina student-run free-format noncommercial radio music library and airplay route",
    language: "en",
    genres: ["wusc", "college-radio", "student-radio", "free-format-radio", "radio-airplay", "music-library", "outreach-music-director-email", "electronic", "dub", "reggae", "world", "indie", "alternative", "free", "manual-review"],
    submissionMethod: "official-wusc-contact-page-outreach-music-director-email-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required for outbound email approval, selecting and addressing the Outreach Music Director, track/package selection, metadata, clean/explicit labeling, rights/originality assertions, music-library fit and station policy review.",
    notes: "Public research confirmed WUSC's active 2026 site, 24/7 free-format noncommercial radio positioning and official Outreach Music Director route for having music played on air or submitting music to the music library. No email was sent, no files were transferred and no SMTP/MX probing was performed."
  },
  {
    name: "KZSC Santa Cruz Genre Music Director Contacts",
    websiteUrl: "https://kzsc.org/",
    submissionUrl: "https://kzsc.org/contact/",
    sourceUrl: "https://kzsc.org/contact/",
    sourceType: "automation_run_79_public_research",
    country: "United States / Santa Cruz student-run community radio genre music director contact route",
    language: "en",
    genres: ["kzsc", "college-radio", "community-radio", "radio-airplay", "genre-music-directors", "rpm-electronic", "international", "jazz-blues", "hip-hop", "folk", "electronic", "dub", "reggae", "world", "free", "manual-review"],
    submissionMethod: "official-kzsc-staff-contact-page-genre-music-director-protected-email-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KZSC lists genre-specific protected staff contact links that must not be decoded automatically, and routing must choose the correct music director by genre before any outbound message is prepared.",
    notes: "Public research confirmed KZSC's active 2026 site, recent 2026 music/news posts and official staff contact page with genre music director links. Protected contacts were observed but not decoded. No email was sent, no form was submitted and no SMTP/MX probing was performed."
  }
];
