import type { PlatformInput } from '../models/types.js';

export const run76SeedPlatforms: PlatformInput[] = [
  {
    name: "Fresh On The Net Send Us A Track",
    websiteUrl: "https://freshonthenet.co.uk/",
    submissionUrl: "https://freshonthenet.co.uk/submit/",
    sourceUrl: "https://freshonthenet.co.uk/submit/",
    sourceType: "automation_run_76_public_research",
    country: "United Kingdom / global online new-music listening-post route with public-track eligibility",
    language: "en",
    genres: ["fresh-on-the-net", "uk", "new-music", "music-blog", "listening-post", "soundcloud", "independent-music", "electronic", "pop", "alternative", "world", "dub", "reggae", "free", "manual-review"],
    submissionMethod: "official-fresh-on-the-net-send-us-a-track-weekly-listening-post-submission-window",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Fresh On The Net publishes a weekly public Send Us A Track route but the inbox opens and closes by schedule and quota; human review is required to confirm the window is open, select one eligible public worldwide track, confirm no repeat/remix/AI-generated restrictions, verify SoundCloud profile readiness, metadata and editorial fit.",
    notes: "Public research confirmed the official Fresh On The Net Send Us A Track page, current July 2026 submission-window status and recent June 2026 activity. No inbox interaction, form submission, account login, file upload, payment, CAPTCHA bypass or validation bypass was attempted."
  },
  {
    name: "Radio Free Brooklyn Music Submission Form",
    websiteUrl: "https://www.radiofreebrooklyn.org/",
    submissionUrl: "https://submissions.radiofreebrooklyn.org/music-submission-form/",
    sourceUrl: "https://submissions.radiofreebrooklyn.org/music-submission-form/",
    sourceType: "automation_run_76_public_research",
    country: "United States / Brooklyn New York community radio music submission form and physical music-director route",
    language: "en",
    genres: ["radio-free-brooklyn", "brooklyn", "community-radio", "radio-airplay", "music-submission-form", "captcha", "reCAPTCHA", "download-link", "independent-music", "electronic", "dub", "reggae", "world", "hip-hop", "free", "manual-review"],
    submissionMethod: "official-radio-free-brooklyn-public-music-submission-form-with-recaptcha-and-download-link-requirement",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Radio Free Brooklyn publishes an official music submission form, but it includes visual-code/reCAPTCHA validation and requires a freely downloadable track link plus metadata; human review is required and anti-bot or validation controls must not be bypassed.",
    notes: "Public research confirmed Radio Free Brooklyn activity in 2026, a site footer Submit Music route and the official music submission form. The form fields and reCAPTCHA/visual-code controls were identified only. No form was submitted, no file or image was uploaded, no email was sent, no physical package was mailed and no anti-bot control was interacted with."
  },
  {
    name: "CKUT 90.3 FM Submitting Music",
    websiteUrl: "https://ckut.ca/",
    submissionUrl: "https://ckut.ca/submit-music-to-ckut/",
    sourceUrl: "https://ckut.ca/submit-music-to-ckut/",
    sourceType: "automation_run_76_public_research",
    country: "Canada / Montreal campus and community radio physical and digital music submission route",
    language: "en",
    genres: ["ckut", "montreal", "campus-radio", "community-radio", "radio-airplay", "music-library", "business-email", "physical-mail", "mp3-320", "digital-submission", "electronic", "dub", "reggae", "world", "hip-hop", "free", "manual-review"],
    submissionMethod: "official-ckut-music-department-physical-mail-and-music-email-route-for-radio-library-review",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "CKUT publishes an official music submission page with physical and digital routes; human review is required because outbound email or physical mail, three-distinct-track eligibility, no-single rules, 320kbps MP3 digital requirements, metadata, clean/explicit labeling, rights/originality and station/library fit must be checked manually.",
    notes: "Public research confirmed CKUT as an active Montreal campus/community station with 2025/2026 public activity and an official Submitting Music page listing physical formats and a public digital submission email music@ckut.ca. No email was sent, no file was transferred, no physical package was mailed and no SMTP/MX probing was performed."
  },
  {
    name: "CJSR FM 88 Submit Music",
    websiteUrl: "https://www.cjsr.com/",
    submissionUrl: "https://www.cjsr.com/submit-music/",
    sourceUrl: "https://www.cjsr.com/submit-music/",
    sourceType: "automation_run_76_public_research",
    country: "Canada / Edmonton campus and community radio physical and digital album submission route",
    language: "en",
    genres: ["cjsr", "edmonton", "campus-radio", "community-radio", "radio-airplay", "music-submissions", "business-email", "album", "ep", "bandcamp", "dropbox", "google-drive", "electronic", "dub", "reggae", "world", "free", "manual-review"],
    submissionMethod: "official-cjsr-music-department-physical-and-digital-album-ep-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "CJSR publishes an official Submit Music page with physical and digital album/EP routes; human review is required because outbound email, albums-or-EPs-only eligibility, no paid streaming links, download-link permissions, metadata, language warnings, clean/explicit labeling and station/library fit must remain manual.",
    notes: "Public research confirmed CJSR as active with June 2026 chart/public-site updates and an official Submit Music page listing music@cjsr.com, physical formats and accepted digital link types. A paid local advertising option was observed but not activated. No email was sent, no payment was made, no file was transferred, no physical package was mailed and no SMTP/MX probing was performed."
  },
  {
    name: "KXCI Music Department Submissions",
    websiteUrl: "https://kxci.org/",
    submissionUrl: "https://kxci.org/about/music-department/",
    sourceUrl: "https://kxci.org/about/music-department/",
    sourceType: "automation_run_76_public_research",
    country: "United States / Tucson Arizona community radio music department digital and physical submission route",
    language: "en",
    genres: ["kxci", "tucson", "community-radio", "radio-airplay", "music-department", "digital-download", "physical-mail", "mp3", "wav", "cd", "vinyl", "electronic", "dub", "reggae", "world", "latin", "free", "manual-review"],
    submissionMethod: "official-kxci-music-department-digital-download-link-and-physical-mail-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "KXCI publishes an official Music Department submission page and accepts digital download links plus CDs/vinyl; human review is required because the page displays protected email links, outbound email or physical mail must not be automated, and release metadata, explicit-language labeling, contact details, local/regional routing and station fit require manual checks.",
    notes: "Public research confirmed KXCI active with June 2026 programs/news and its official Music Department page. The page states KXCI accepts music from all over the world, asks for MP3/WAV download links or CDs/vinyl, and displays protected email links that were not decoded, guessed or probed. No email was sent, no file was transferred, no physical copy was mailed and no SMTP/MX probing was performed."
  }
];
