import type { PlatformInput } from '../models/types.js';

export const run75SeedPlatforms: PlatformInput[] = [
  {
    name: "KBOO Submit Your Music",
    websiteUrl: "https://www.kboo.fm/",
    submissionUrl: "https://www.kboo.fm/submit-your-music",
    sourceUrl: "https://www.kboo.fm/submit-your-music",
    sourceType: "automation_run_75_public_research",
    country: "United States / Portland Oregon community radio physical music submission route",
    language: "en",
    genres: ["kboo", "portland", "community-radio", "radio-airplay", "submit-music", "physical-mail", "music-library", "electronic", "dub", "reggae", "world", "hip-hop", "jazz", "folk", "free", "manual-review"],
    submissionMethod: "official-kboo-submit-your-music-physical-mail-route-with-genre-specific-music-library-routing",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "KBOO publishes an official Submit Your Music page and states it does not yet have a digital library or volunteer capacity to download and burn CDs from digital submissions; human review is required for physical package preparation, genre-specific attention routing, metadata, clean/explicit labeling, rights/originality assertions and station/show fit decisions.",
    notes: "Public research confirmed KBOO as an active Portland community radio station with a public Submit Your Music page. The page lists postal submission instructions, genre-specific attention names including world music/reggae and electronic routes, and no guarantee of airplay. No digital submission was attempted, no package was mailed, no email was sent and no SMTP/MX probing was performed."
  },
  {
    name: "KOOP Radio Music Library Submissions",
    websiteUrl: "https://koop.org/",
    submissionUrl: "https://koop.org/about-us/contact/",
    sourceUrl: "https://koop.org/about-us/contact/",
    sourceType: "automation_run_75_public_research",
    country: "United States / Austin Texas community radio music library submission route",
    language: "en",
    genres: ["koop", "austin", "community-radio", "radio-airplay", "music-library", "business-email", "independent-radio", "electronic", "dance", "dub", "reggae", "world", "hip-hop", "free", "manual-review"],
    submissionMethod: "official-koop-radio-music-library-email-route-for-airplay-library-consideration",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "KOOP publishes an official Music Library submission email; human review is required because outbound email must not be automated and track/package selection, download-link permissions, metadata, clean/explicit labeling, rights/originality assertions and station/library fit must be checked manually.",
    notes: "Public research confirmed KOOP as an active Austin community radio station with 2026 events, updates and program highlights, and an official contact page listing music@koop.org for Music Library submissions. No email was sent, no file was transferred, no mailing list form was used and no SMTP/MX probing was performed."
  },
  {
    name: "CJSW 90.9 FM Music Submissions",
    websiteUrl: "https://cjsw.com/",
    submissionUrl: "https://cjsw.com/music/submit/",
    sourceUrl: "https://cjsw.com/music/submit/",
    sourceType: "automation_run_75_public_research",
    country: "Canada / Calgary campus and community radio digital album submission route",
    language: "en",
    genres: ["cjsw", "calgary", "campus-radio", "community-radio", "radio-airplay", "music-submissions", "jotform", "digital-album", "mp3", "zip", "independent-music", "electronic", "dub", "reggae", "world", "free", "manual-review"],
    submissionMethod: "official-cjsw-digital-album-submission-form-for-freeform-radio-library-review",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "CJSW publishes an official Music Submissions page using an external Jotform upload route; human review is required because external form completion, release recency, three-or-more-unique-track album eligibility, MP3/ZIP formatting, metadata, rights/originality assertions and station/library fit must be checked manually.",
    notes: "Public research confirmed CJSW as an active Calgary campus/community station with current 2026 news and an official digital music submission page. The page says CJSW only accepts digital submissions, does not accept singles, requires recent releases with three or more unique tracks, MP3 format and ZIP albums. A protected/masked Music & Performance Director email appeared on the page and was not decoded, guessed or probed. No form was submitted and no upload was attempted."
  },
  {
    name: "CFUV Music Submissions",
    websiteUrl: "https://cfuv.uvic.ca/",
    submissionUrl: "https://cfuv.uvic.ca/music-submissions/",
    sourceUrl: "https://cfuv.uvic.ca/music-submissions/",
    sourceType: "automation_run_75_public_research",
    country: "Canada / Victoria British Columbia campus and community radio digital submission route",
    language: "en",
    genres: ["cfuv", "victoria-bc", "campus-radio", "community-radio", "radio-airplay", "music-submissions", "business-email", "music-director", "digital-download", "mp3-320", "independent-music", "electronic", "jazz", "world", "reggae", "hip-hop", "free", "manual-review"],
    submissionMethod: "official-cfuv-music-director-email-and-digital-download-link-route-for-airplay-library-consideration",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "CFUV publishes an official Music Submissions page and Music Director email; human review is required because outbound email, three-track minimum eligibility, 320kbps MP3/download-link requirements, tracklist/bio metadata, local-only physical exception handling, rights/originality assertions and station/freeform fit must be checked manually.",
    notes: "Public research confirmed CFUV as a Victoria nonprofit campus/community station and its official Music Submissions page lists music@cfuv.ca, digital download-link instructions, minimum track and format requirements, review expectations and physical/courier details for exceptions. No email was sent, no file was transferred, no physical copy was mailed and no SMTP/MX probing was performed."
  },
  {
    name: "4ZZZ Music Submissions",
    websiteUrl: "https://4zzz.org.au/",
    submissionUrl: "https://4zzz.org.au/music-submissions",
    sourceUrl: "https://4zzz.org.au/music-submissions",
    sourceType: "automation_run_75_public_research",
    country: "Australia / Brisbane community radio digital music submission and Album of the Week consideration route",
    language: "en",
    genres: ["4zzz", "brisbane", "community-radio", "radio-airplay", "music-submissions", "external-form", "digital-library", "album-of-the-week", "electronic", "alternative", "dub", "reggae", "world", "independent-music", "free", "manual-review"],
    submissionMethod: "official-4zzz-music-department-digital-submission-form-and-album-of-the-week-form-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "4ZZZ publishes an official Music Submissions page with external submission links; human review is required because form completion, downloadable music-link checks, Music Department processing, Album of the Week eligibility, metadata, rights/originality assertions and community-radio fit decisions must remain manual.",
    notes: "Public research confirmed 4ZZZ as an active Brisbane community station with June/July 2026 schedules, Top 20 and events, and an official Music Submissions page linking to submission forms on jeff.4zzz.org.au. No external form was opened beyond public link identification, no form was submitted, no file was uploaded and no anti-bot or validation control was interacted with."
  }
];
