import type { PlatformInput } from '../models/types.js';

export const run88SeedPlatforms: PlatformInput[] = [
  {
    name: "BIRP! Groover and SubmitHub Music Submission Route",
    websiteUrl: "https://birp.fm/",
    submissionUrl: "https://birp.fm/",
    sourceUrl: "https://birp.fm/",
    sourceType: "automation_run_88_public_research",
    country: "United States / global indie playlist and new-music blog submission route",
    language: "en",
    genres: ["birp", "indie-playlist", "new-music-blog", "monthly-playlists", "groover", "submithub", "external-curator-platform", "spotify", "soundcloud", "youtube", "indie", "electronic", "reggae", "world", "free-first", "freemium", "manual-review"],
    submissionMethod: "official-birp-groover-and-submithub-music-submission-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because BIRP! publishes official music-submission links to Groover and SubmitHub. Those external curator platforms require account/session handling, curator-route choice, pitch copy, possible credit/payment choices, music-link metadata, rights/originality confirmation and playlist/editorial fit review. No route should be auto-submitted or paid without owner approval.",
    notes: "Public research confirmed BIRP! is active with May 2026 playlist activity and a 2026 copyright footer. The official homepage includes public 'Send us your music on Groover' and 'Send us your music on SubmitHub' routes. No account was created, no login was used, no submission was made, no payment was initiated and no anti-bot/session control was interacted with."
  },
  {
    name: "Stereofox SubmitHub and Groover Music Submission Route",
    websiteUrl: "https://www.stereofox.com/",
    submissionUrl: "https://www.stereofox.com/contact/",
    sourceUrl: "https://www.stereofox.com/contact/",
    sourceType: "automation_run_88_public_research",
    country: "Bulgaria / global human-curated music blog, playlist and label submission route",
    language: "en",
    genres: ["stereofox", "music-blog", "playlists", "human-curated", "submithub", "groover", "external-curator-platform", "electronic", "electronica", "chill-electronica", "progressive-house", "uk-garage", "lofi", "jazzhop", "indie", "freemium", "manual-review"],
    submissionMethod: "official-stereofox-submithub-and-groover-music-submission-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Stereofox explicitly routes music submissions through SubmitHub and Groover rather than email or Discord. Submission requires external-platform account/session handling, curator targeting, pitch copy, music-link and metadata checks, possible credit/payment decisions, rights/originality confirmation and editorial or playlist fit review.",
    notes: "Public research confirmed Stereofox is active in 2026 with recent editorial posts, hand-picked new music, updated playlists and a contact page stating music submissions must use SubmitHub or Groover. No email was sent, no Discord route was used, no account/login was attempted, no submission was made and no payment route was activated."
  },
  {
    name: "A&R Factory Editorial Music Submission Form",
    websiteUrl: "https://www.anrfactory.com/",
    submissionUrl: "https://www.anrfactory.com/submit-demo/",
    sourceUrl: "https://www.anrfactory.com/submit-demo/",
    sourceType: "automation_run_88_public_research",
    country: "United Kingdom / global independent artist blog and A&R editorial submission form",
    language: "en",
    genres: ["a-and-r-factory", "music-blog", "a-and-r", "editorial-review", "submission-form", "free-submission", "paid-package-option", "dance-edm", "dancehall", "drum-and-bass", "electronic", "house", "reggae", "reggaeton", "world", "freemium", "manual-review"],
    submissionMethod: "official-a-and-r-factory-editorial-music-submission-form",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because A&R Factory exposes a public editorial submission form with artist, genre, release-status, track-link, social, artwork, EPK/bio and email fields, plus free and paid package choices. The payment/package step, marketing consent, one-track rule, release details, metadata, rights/originality and publication fit require manual owner review.",
    notes: "Public research confirmed A&R Factory is active with July 2026 posts and a public Submit Your Music workflow. The form lists broad genre coverage including Dance/EDM, Dancehall, Drum & Bass, Electronic, House, Reggae, Reggaeton and World, and includes a Free Submission option plus paid Premium/Standard package choices. No form was submitted and no payment method was touched."
  },
  {
    name: "musicto Free Global Playlist Track Submit Form",
    websiteUrl: "https://www.musicto.com/",
    submissionUrl: "https://www.musicto.com/submit-a-track/",
    sourceUrl: "https://www.musicto.com/submit-a-track/",
    sourceType: "automation_run_88_public_research",
    country: "United States / global people-powered playlist-curator submission form",
    language: "en",
    genres: ["musicto", "playlist-submission", "free", "global-curators", "spotify", "apple-music", "deezer", "tidal", "soundcloud", "amazon-music", "youtube-music", "mood-context", "electronic", "dance", "dub-reggae", "soul", "world", "free", "manual-review"],
    submissionMethod: "official-musicto-free-global-playlist-track-submit-form",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because musicto uses a JavaScript-enabled public form requesting artist/band name, email, track title, track link, story/context, reference artists and emotion/mood selections. Even though submission is free, the link choice, metadata, context copy, mood fit, rights/originality and curator-fit checks require manual review.",
    notes: "Public research confirmed musicto is active as a people-powered playlist network with a Track Submit page describing free submissions to a global community of curators across major streaming platforms. No form was submitted, no JavaScript form control was interacted with, no account was used and no email was sent."
  },
  {
    name: "Side-Line Magazine News and Review Material Submission Route",
    websiteUrl: "https://www.side-line.com/",
    submissionUrl: "https://www.side-line.com/contact-us/",
    sourceUrl: "https://www.side-line.com/contact-us/",
    sourceType: "automation_run_88_public_research",
    country: "Belgium / global industrial, electro, EBM, post-punk and darkwave news and review route",
    language: "en",
    genres: ["side-line", "music-magazine", "industrial", "electro", "ebm", "post-punk", "darkwave", "electropop", "news-submission", "review-material", "public-email", "electronic", "synth", "alternative", "free", "manual-review"],
    submissionMethod: "official-side-line-news-and-review-material-email-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Side-Line publishes public email routes for news and review material, while review material requires contacting for the full address. Message purpose, track/news angle, promo copy, press materials, rights/originality, genre fit and any follow-up address handling require manual review.",
    notes: "Public research confirmed Side-Line is active in 2026 with recent May 2026 posts and a contact page listing info@side-line.com for news and stef@side-line.com for review material. No email was sent, no address was requested, no files or links were delivered, no payment route was used and no SMTP/MX probing was performed."
  }
];
