import type { PlatformInput } from '../models/types.js';

export const run83SeedPlatforms: PlatformInput[] = [
  {
    name: "Tidal Upload Independent Artist Self-Publish Route",
    websiteUrl: "https://tidal.com/",
    submissionUrl: "https://tidal.com/upload",
    sourceUrl: "https://www.musicradar.com/music-tech/software-apps/no-your-uploaded-files-do-not-earn-royalties-tidal-launch-tidal-upload-an-artist-aimed-free-route-to-get-independent-music-on-its-platform-theres-cash-incentives-but-dont-expect-any-royalties",
    sourceType: "automation_run_83_public_research",
    country: "United States currently / Tidal direct-upload self-publishing route for independent artists; international expansion expected but not assumed",
    language: "en",
    genres: ["tidal-upload", "direct-upload", "self-publishing", "independent-artists", "streaming", "playlist-consideration", "artist-upload", "electronic", "reggae", "world", "dance", "free", "login-required", "rights-review", "ai-policy-review", "manual-review"],
    submissionMethod: "official-tidal-upload-independent-artist-direct-upload-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Tidal Upload is an authenticated direct-upload route with current U.S.-only/age eligibility constraints, no-royalty economics, track-rights ownership checks, copyright filtering, metadata and artwork decisions, public/private visibility choices, potential playlist/editorial review and updated AI-generated-music labeling/demonetization policy implications.",
    notes: "Public research confirmed Tidal Upload as a free route for independent artists to self-publish tracks directly to Tidal, with rights/tagging/copyright controls and no streaming royalties. Fresh 2026 reporting also confirmed Tidal's AI-generated-music labeling and demonetization policy. No login was used, no upload was started, no eligibility assertion was made and no track was submitted."
  },
  {
    name: "SoundOn by TikTok Artist Distribution Upload Route",
    websiteUrl: "https://www.soundon.global/",
    submissionUrl: "https://www.soundon.global/",
    sourceUrl: "https://en.wikipedia.org/wiki/SoundOn",
    sourceType: "automation_run_83_public_research",
    country: "Global / selected-market TikTok-powered music distribution and publishing administration route",
    language: "en",
    genres: ["soundon", "tiktok", "music-distribution", "artist-services", "publishing-administration", "artist-upload", "royalties", "social-music", "electronic", "reggae", "world", "dance", "free-and-paid", "login-required", "manual-review"],
    submissionMethod: "official-soundon-global-artist-music-distribution-upload-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because SoundOn is an authenticated music distribution and publishing workflow requiring account access, regional availability checks, rights ownership, royalty and payout setup, distributor/DSP metadata, release selection, TikTok/short-video fit, possible service terms and publishing administration approval.",
    notes: "Public research confirmed SoundOn as TikTok's music marketing and distribution platform where artists can upload music directly to TikTok, retain copyright, receive royalties and distribute to other platforms in supported markets. No account was created, no login was used, no track was uploaded and no release was distributed."
  },
  {
    name: "Subvert Cooperative Artist and Label Marketplace Route",
    websiteUrl: "https://subvert.fm/",
    submissionUrl: "https://subvert.fm/",
    sourceUrl: "https://en.wikipedia.org/wiki/Subvert_(music_marketplace)",
    sourceType: "automation_run_83_public_research",
    country: "Global / member-owned independent music marketplace in phased rollout",
    language: "en",
    genres: ["subvert", "bandcamp-alternative", "artist-storefront", "label-storefront", "digital-downloads", "cooperative", "direct-to-fan", "independent-artists", "electronic", "reggae", "world", "dance", "freemium", "membership-required", "ai-prohibited", "manual-review"],
    submissionMethod: "official-subvert-artist-label-membership-marketplace-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Subvert is a member-owned marketplace in phased/member-only rollout with artist/label membership, account setup, storefront/release upload, direct-to-fan pricing, payout, governance and strict AI-generated music/artwork prohibition checks before any MarcsMusic catalog can be onboarded.",
    notes: "Public research confirmed Subvert as a cooperatively owned online music marketplace for independent musicians, labels and supporters, with free artist/label membership, 0% platform fee model, member-only alpha/phased rollout in 2026 and AI-generated music/artwork prohibition. No membership was requested, no account was created, no release was uploaded and no sale route was activated."
  },
  {
    name: "StreetVoice Independent Music Upload and Demo Publishing Route",
    websiteUrl: "https://www.streetvoice.com/",
    submissionUrl: "https://www.streetvoice.com/",
    sourceUrl: "https://en.wikipedia.org/wiki/StreetVoice",
    sourceType: "automation_run_83_public_research",
    country: "Taiwan / Mandarin-speaking and global independent music sharing, demo and UGC platform",
    language: "zh/en",
    genres: ["streetvoice", "independent-music", "demo-upload", "ugc-platform", "music-streaming", "artist-profile", "creative-commons", "electronic", "dance", "hip-hop", "world", "reggae-fusion", "free", "login-required", "manual-review"],
    submissionMethod: "official-streetvoice-member-content-music-upload-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because StreetVoice requires member-account handling, language/market fit review, upload and profile setup, genre classification, copyright/member-content warranties, Creative Commons/licensing choices where applicable and manual assessment of whether MarcsMusic's catalog fits the platform audience.",
    notes: "Public research confirmed StreetVoice as a free UGC music streaming/social platform where registered members can upload music/audio/member content, with independent musicians using it to release demos and original music. No account was created, no member content was uploaded and no license setting was selected."
  },
  {
    name: "SoundClick Artist Profile Music Upload and Store Route",
    websiteUrl: "https://www.soundclick.com/",
    submissionUrl: "https://www.soundclick.com/",
    sourceUrl: "https://en.wikipedia.org/wiki/SoundClick",
    sourceType: "automation_run_83_public_research",
    country: "Global / artist profile, streaming, download and music-store upload route",
    language: "en",
    genres: ["soundclick", "artist-profile", "mp3-upload", "music-store", "creative-commons", "direct-downloads", "streaming", "beats", "electronic", "reggae", "world", "dance", "freemium", "login-required", "manual-review"],
    submissionMethod: "official-soundclick-artist-profile-mp3-upload-storefront-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because SoundClick uses artist profile/account workflows, MP3 upload, stream/download/sale settings, Creative Commons or paid licensing choices, optional VIP upgrades, store pricing and PayPal/payout configuration that must be approved before any MarcsMusic upload.",
    notes: "Public research confirmed SoundClick allows artists to upload MP3 songs, offer streams/free downloads/sales, license songs under free Creative Commons or paid licenses, and use optional fee-based VIP services. No account was created, no MP3 was uploaded, no store/pricing/licensing route was activated and no payment setup was touched."
  }
];
