import type { PlatformInput } from '../models/types.js';

export const run80SeedPlatforms: PlatformInput[] = [
  {
    name: "WREK Atlanta How To Submit Music",
    websiteUrl: "https://www.wrek.org/",
    submissionUrl: "https://old.wrek.org/submissions/",
    sourceUrl: "https://old.wrek.org/submissions/",
    sourceType: "automation_run_80_public_research",
    country: "United States / Atlanta Georgia Tech student-managed college radio music director submission route",
    language: "en",
    genres: ["wrek", "college-radio", "student-radio", "freeform-radio", "radio-airplay", "music-director-email", "physical-mail", "electronic", "dub", "reggae", "world", "experimental", "indie", "alternative", "free", "manual-review"],
    submissionMethod: "official-wrek-how-to-submit-music-email-and-physical-mail-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required for outbound email approval, physical-vs-email routing, track/package selection, metadata, clean/explicit labeling, rights/originality assertions and freeform station fit.",
    notes: "Public research confirmed WREK's active current site, official music page and official How To Submit Music route via music.director@wrek.org or physical mail to the Music Director. No email was sent, no physical mail was prepared, no file was transferred and no SMTP/MX probing was performed."
  },
  {
    name: "WMBR 88.1 FM How To Get Your Music Played",
    websiteUrl: "https://wmbr.org/",
    submissionUrl: "https://wmbr.org/www/md",
    sourceUrl: "https://wmbr.org/www/md",
    sourceType: "automation_run_80_public_research",
    country: "United States / Cambridge Massachusetts MIT freeform community radio physical music submission route",
    language: "en",
    genres: ["wmbr", "college-radio", "community-radio", "freeform-radio", "radio-airplay", "music-director", "physical-mail", "unsigned-artists", "rpm-techno", "world", "experimental", "garage", "punk", "electronic", "dub", "reggae", "free", "manual-review"],
    submissionMethod: "official-wmbr-your-music-physical-mail-music-director-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WMBR urges tangible physical submissions, does not want MP3 review requests, uses freeform DJ-by-DJ selection, lists protected image-based contacts for genre/chart follow-up and requires show-fit review.",
    notes: "Public research confirmed WMBR's active 2026 site and official Your Music route with physical Music Director address and unsigned-band eligibility. Protected image-based contacts were observed but not decoded. No email was sent, no physical mail was prepared, no files were transferred and no SMTP/MX probing was performed."
  },
  {
    name: "WRCT 88.3 FM Pittsburgh Music Director Submissions",
    websiteUrl: "https://www.wrct.org/",
    submissionUrl: "https://www.wrct.org/contact/",
    sourceUrl: "https://www.wrct.org/contact/",
    sourceType: "automation_run_80_public_research",
    country: "United States / Pittsburgh Carnegie Mellon freeform noncommercial radio music director route",
    language: "en",
    genres: ["wrct", "college-radio", "freeform-radio", "noncommercial-radio", "radio-airplay", "music-director-email", "genre-directors", "experimental", "international", "rpm", "reggae", "rock", "electronic", "world", "hip-hop", "free", "manual-review"],
    submissionMethod: "official-wrct-contact-page-music-director-and-genre-director-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because submissions are routed through protected/masked Music Director and genre-director contacts, and director selection, outbound email, track/package selection, metadata and station fit need approval.",
    notes: "Public research confirmed WRCT's active 2026 site, recent programming/posts, official Contact page and Submit Music route to the Music Director, with additional genre directors including experimental, international, reggae and RPM. Protected/masked contacts were not decoded. No email was sent, no form was submitted and no SMTP/MX probing was performed."
  },
  {
    name: "KUTX Submit Your Music for On-Air Rotation",
    websiteUrl: "https://kutx.org/",
    submissionUrl: "https://kutx.org/submit-your-music/",
    sourceUrl: "https://kutx.org/submit-your-music/",
    sourceType: "automation_run_80_public_research",
    country: "United States / Austin Texas public radio music-discovery airplay submission route",
    language: "en",
    genres: ["kutx", "public-radio", "aaa-radio", "music-discovery", "radio-airplay", "music-director-email", "specialty-shows", "electronic", "experimental", "latin", "world", "hip-hop", "indie", "alternative", "free", "paid-side-route-observed", "manual-review"],
    submissionMethod: "official-kutx-submit-your-music-email-route-with-specialty-show-side-routes",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required for outbound email approval, streaming and WAV download-link prep, FCC-clean/radio-edit checks, top-pick selection, specialty-show routing and avoiding paid sponsorship/event-promo side routes unless approved.",
    notes: "Public research confirmed KUTX's active 2026 site and official Submit Your Music route via music@kutx.org with specific WAV, bio, release-note and clean-edit requirements. External specialty/event forms and paid sponsorship side routes were observed but not activated. No email was sent, no form was submitted, no file was transferred and no SMTP/MX probing was performed."
  },
  {
    name: "KDVS 90.3 FM Music Department Physical Submissions",
    websiteUrl: "https://kdvs.org/",
    submissionUrl: "https://kdvs.org/contact",
    sourceUrl: "https://kdvs.org/contact",
    sourceType: "automation_run_80_public_research",
    country: "United States / Davis California UC Davis freeform college-community radio music department route",
    language: "en",
    genres: ["kdvs", "college-radio", "community-radio", "freeform-radio", "radio-airplay", "music-director-email", "physical-submissions-only", "library-maintenance", "electronic", "dub", "reggae", "world", "indie", "experimental", "free", "manual-review"],
    submissionMethod: "official-kdvs-contact-page-music-directors-email-and-physical-submissions-only-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KDVS lists Music Directors and musicdept@kdvs.org but says to send all new music to the mailing address as physical submissions only, requiring package prep, routing, metadata and station/library fit checks.",
    notes: "Public research confirmed KDVS's active official site, streaming/charts surface, official Contact page and Music Directors route via musicdept@kdvs.org, with physical submissions only for new music. No email was sent, no physical mail was prepared, no files were transferred and no SMTP/MX probing was performed."
  }
];