import type { PlatformInput } from '../models/types.js';

export const run85SeedPlatforms: PlatformInput[] = [
  {
    name: "WERS Wicked Local Wednesday Submit Music Form",
    websiteUrl: "https://wers.org/",
    submissionUrl: "https://wers.org/wicked-local-wednesday/",
    sourceUrl: "https://wers.org/wicked-local-wednesday/",
    sourceType: "automation_run_85_public_research",
    country: "United States / Boston local public-radio music submission form route",
    language: "en",
    genres: ["wers", "public-radio", "college-radio", "local-music", "boston", "wicked-local-wednesday", "airplay", "upload-form", "mp3", "electronic", "reggae", "world", "dance", "free", "captcha", "manual-review"],
    submissionMethod: "official-wers-wicked-local-wednesday-submit-music-form-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WERS provides a public Wicked Local Wednesday music-submission form for local Boston artists, with required artist/contact/location fields, song title, social links, streaming links, MP3 upload constraints and site-level reCAPTCHA handling; local eligibility, file choice, clean/explicit labeling, metadata and station fit must be reviewed before any action.",
    notes: "Public research confirmed WERS is active with 2026 site content and an official Submit Music route for Wicked Local Wednesday. The form accepts required contact and music fields plus MP3 upload up to 39 MB. No form was submitted, no CAPTCHA/reCAPTCHA was interacted with and no file was uploaded."
  },
  {
    name: "Radio Milwaukee Music Submission Route",
    websiteUrl: "https://radiomilwaukee.org/",
    submissionUrl: "https://radiomilwaukee.org/music-submission",
    sourceUrl: "https://radiomilwaukee.org/music-submission",
    sourceType: "automation_run_85_public_research",
    country: "United States / Milwaukee independent public-radio music submission route",
    language: "en",
    genres: ["radio-milwaukee", "public-radio", "independent-radio", "airplay", "music-submission", "wav", "uncompressed-audio", "radio-edit", "electronic", "reggae", "world", "dance", "free", "manual-review"],
    submissionMethod: "official-radio-milwaukee-music-submission-guidelines-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Radio Milwaukee's official music-submission page specifies uncompressed audio, WAV preference, mixed/mastered tracks, radio edits, artist/bio/lyrics/context links and no physical media; the fetched page did not expose a safe complete auto-submit endpoint, so route mechanics, package prep, metadata and station fit require manual review.",
    notes: "Public research confirmed Radio Milwaukee is active with 2026 site footer/menu and an official Music Submission page describing required audio and artist information. No route was activated, no form endpoint was inferred, no files were uploaded and no email or probing was attempted."
  },
  {
    name: "WTJU 91.1 FM Genre Music Director Submission Route",
    websiteUrl: "https://www.wtju.net/",
    submissionUrl: "https://www.wtju.net/submit-music/",
    sourceUrl: "https://www.wtju.net/submit-music/",
    sourceType: "automation_run_85_public_research",
    country: "United States / Charlottesville public-radio genre-director submission route",
    language: "en",
    genres: ["wtju", "public-radio", "community-radio", "genre-director", "music-director", "airplay", "physical-mail", "email-route", "mp3", "wav", "flac", "electronic", "reggae", "world", "dance", "free", "manual-review"],
    submissionMethod: "official-wtju-genre-music-director-email-and-physical-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WTJU provides genre-specific music director emails plus U.S. mail and UPS/private-carrier submission addresses, with accepted media formats and streaming-link limitations; genre routing, physical/digital package choice, downloadable-file permissions, clean/explicit labeling, metadata and station/library fit require review.",
    notes: "Public research confirmed WTJU is active with July 2026 site content and its official Submit Music page lists physical addresses, accepted CD/LP/digital formats, genre contacts and public department emails including world and general routes. No email was sent, no files were transferred and no physical mail was sent."
  },
  {
    name: "WYEP Pittsburgh Area Music Submissions Route",
    websiteUrl: "https://www.wyep.org/",
    submissionUrl: "https://www.wyep.org/wyep-pittsburgh-area-music-submissions",
    sourceUrl: "https://www.wyep.org/wyep-pittsburgh-area-music-submissions",
    sourceType: "automation_run_85_public_research",
    country: "United States / Pittsburgh public-radio local music airplay submission route",
    language: "en",
    genres: ["wyep", "public-radio", "local-913", "pittsburgh-music", "airplay", "email-route", "physical-mail", "fcc-clean", "specialty-shows", "electronic", "reggae", "world", "dance", "free", "manual-review"],
    submissionMethod: "official-wyep-localmusic-email-and-hard-copy-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WYEP provides a public localmusic@wyep.org route and hard-copy address for Pittsburgh-area musicians, asks for contact/location/context, recommends 2-3 tracks for album submissions, references specialty-show targeting and requires FCC-clean edits; local eligibility, track selection, show fit, metadata and clean labeling must be approved.",
    notes: "Public research confirmed WYEP is active with 2026 site content and its official Pittsburgh Area Music Submissions page lists localmusic@wyep.org, a hard-copy route and explicit FCC-clean/local-airplay criteria. No email was sent, no files were transferred and no physical mail was sent."
  },
  {
    name: "KZSU Stanford 90.1 FM Music Director Submission Route",
    websiteUrl: "https://kzsu.stanford.edu/",
    submissionUrl: "https://kzsu.stanford.edu/contact/",
    sourceUrl: "https://kzsu.stanford.edu/contact/",
    sourceType: "automation_run_85_public_research",
    country: "United States / Stanford freeform college-radio music director submission route",
    language: "en",
    genres: ["kzsu", "college-radio", "freeform-radio", "music-director", "physical-mail", "email-route", "independent-music", "electronic", "reggae", "world", "dance", "free", "cookie-gated-guidelines", "manual-review"],
    submissionMethod: "official-kzsu-music-director-email-and-physical-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KZSU's official contact page lists KZSU Music physical addresses and music@kzsu.stanford.edu, while the music/guidelines route redirected to a cookie/Turnstile-protected zookeeper session; contact targeting, package selection, metadata, clean/explicit labeling, rights/originality and station fit require review without bypassing session controls.",
    notes: "Public research confirmed KZSU's official Stanford Radio site is active, lists a Music Director send-us-music route, public music@kzsu.stanford.edu address and physical mailing addresses, while the related music page required a temporary cookie/secure session. No email was sent, no files were transferred, no physical mail was sent and no session/anti-bot controls were bypassed."
  }
];
