import type { PlatformInput } from '../models/types.js';

export const run86SeedPlatforms: PlatformInput[] = [
  {
    name: "WCBN-FM Ann Arbor Music Director Hard-Copy Submission Route",
    websiteUrl: "https://wcbn.org/",
    submissionUrl: "https://wcbn.org/c/",
    sourceUrl: "https://wcbn.org/c/",
    sourceType: "automation_run_86_public_research",
    country: "United States / Ann Arbor college freeform radio hard-copy music director route",
    language: "en",
    genres: ["wcbn", "college-radio", "freeform-radio", "music-director", "physical-mail", "hard-copy", "cd", "vinyl", "electronic", "reggae", "world", "dance", "free", "protected-contact", "manual-review"],
    submissionMethod: "official-wcbn-music-director-hard-copy-cd-vinyl-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WCBN's official contact page routes music submissions through Music Directors and says it accepts hard-copy albums, preferably CD or vinyl, from any and all musicians; genre-specific care-of routing, physical package prep, metadata, clean/explicit labeling, rights/originality and freeform-radio fit require review, and protected email links were not decoded.",
    notes: "Public research confirmed WCBN-FM is active, broadcasts 24/7, identifies as the University of Michigan student-run freeform station and provides an official Music Directors hard-copy submission route. No protected contacts were decoded, no email was sent, no files were transferred and no physical mail was sent."
  },
  {
    name: "WUAG 103.1 at UNCG Music Submission Form",
    websiteUrl: "https://wuag.uncg.edu/",
    submissionUrl: "https://wuag.uncg.edu/music-submissions/",
    sourceUrl: "https://wuag.uncg.edu/music-submissions/",
    sourceType: "automation_run_86_public_research",
    country: "United States / Greensboro student-run campus radio music submission form route",
    language: "en",
    genres: ["wuag", "college-radio", "student-radio", "campus-radio", "music-submission-form", "upload-form", "wav", "mp3", "dropbox", "google-drive", "fcc-clean", "north-carolina", "electronic", "reggae", "world", "dance", "free", "manual-review"],
    submissionMethod: "official-wuag-music-submission-form-and-music-productions-director-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WUAG provides an official music submission form with required email, artist, North Carolina status, single/album choice, title, genre, WAV/MP3 upload up to 2 GB, downloadable Dropbox/Google Drive fallback and FCC-clean/editing notes; file selection, permissions, local eligibility, metadata and station fit require review.",
    notes: "Public research confirmed WUAG is an active student-run UNC Greensboro campus radio station with 2026 site footer content, a Music + Productions Director email route and an official Music Submissions form. No form was submitted, no file was uploaded, no email was sent and no storage-link permissions were changed."
  },
  {
    name: "KRCL 90.9FM How to Submit Music",
    websiteUrl: "https://krcl.org/",
    submissionUrl: "https://krcl.org/about/how-to-submit-music/",
    sourceUrl: "https://krcl.org/about/how-to-submit-music/",
    sourceType: "automation_run_86_public_research",
    country: "United States / Salt Lake City community radio physical and Utah-local digital submission route",
    language: "en",
    genres: ["krcl", "community-radio", "listener-supported-radio", "physical-mail", "music-department", "cd", "no-demos", "no-cdr", "utah-local", "google-form", "dj-selected", "electronic", "reggae", "world", "dance", "free", "manual-review"],
    submissionMethod: "official-krcl-physical-cd-and-utah-local-digital-upload-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KRCL's official page gives separate physical CD instructions and a Utah-local digital upload route, states music is reviewed for airplay and selected by DJs at their discretion, rejects demos/CD-Rs for physical submissions, and treats submitted music as station property; local eligibility, route choice, package prep, metadata and station fit require review.",
    notes: "Public research confirmed KRCL's official How to Submit Music page is active, lists physical Music Department CD instructions and a digital upload route for Utah musicians and bands. No Google form was opened for completion, no files were uploaded, no physical mail was sent and no rights/terms were accepted."
  },
  {
    name: "The Line of Best Fit New and Unsigned Artists Submission Form",
    websiteUrl: "https://www.thelineofbestfit.com/",
    submissionUrl: "https://www.thelineofbestfit.com/contact",
    sourceUrl: "https://www.thelineofbestfit.com/contact",
    sourceType: "automation_run_86_public_research",
    country: "United Kingdom / global online music publication new-and-unsigned artist submission route",
    language: "en",
    genres: ["the-line-of-best-fit", "music-magazine", "new-music", "new-unsigned-artists", "google-form", "one-track-only", "soundcloud", "bandcamp", "spotify", "jazz-world", "dance-club", "pop", "indie", "rap-rnb-hip-hop", "free", "manual-review"],
    submissionMethod: "official-line-of-best-fit-new-and-unsigned-artist-google-form-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because The Line of Best Fit's official contact page links to a Google Form for music from new and unsigned artists; the form asks for email, role, artist details, genre, one-sentence bio, social/profile links and one track only via SoundCloud, Bandcamp or Spotify, with optional Google sign-in to save progress and newsletter consent choices.",
    notes: "Public research confirmed The Line of Best Fit is active with 2026 content and provides an official new-and-unsigned artist Google Form. No form was submitted, no Google sign-in was used, no newsletter choice was made, no contact emails were de-obfuscated and no track link was delivered."
  },
  {
    name: "Obscure Sound Contact and Submissions Route",
    websiteUrl: "https://www.obscuresound.com/",
    submissionUrl: "https://www.obscuresound.com/about/contact/",
    sourceUrl: "https://www.obscuresound.com/about/contact/",
    sourceType: "automation_run_86_public_research",
    country: "United States / global independent music blog editorial submission route",
    language: "en",
    genres: ["obscure-sound", "music-blog", "independent-music", "contact-submissions", "submithub", "musosoup", "direct-email", "singles", "albums", "eps", "electronic", "ambient", "alt-rnb", "hip-hop", "indie-pop", "free", "freemium", "manual-review"],
    submissionMethod: "official-obscure-sound-free-direct-email-submithub-musosoup-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Obscure Sound provides multiple editorial submission paths: SubmitHub for singles, SubmitHub Marketplace for albums/EPs, MusoSoup for singles/albums and a free direct email path using a specific subject line; platform choice, possible credits/campaign options, pitch copy, streaming link, press photo, release context and genre fit require review.",
    notes: "Public research confirmed Obscure Sound is active with June 2026 music coverage and an official Contact/Submissions page. The route is free-first through direct email, with freemium/manual SubmitHub and MusoSoup options and paid PR services as a separate side route requiring owner approval. No email was sent, no SubmitHub/MusoSoup flow was opened for submission, no paid campaign was activated and no contact was probed."
  }
];
