import type { PlatformInput } from '../models/types.js';

export const run89SeedPlatforms: PlatformInput[] = [
  {
    name: "Monstercat Uncaged Instinct Silk LabelRadar Demo Submission Route",
    websiteUrl: "https://www.monstercat.com/",
    submissionUrl: "https://www.monstercat.com/contact-us",
    sourceUrl: "https://www.monstercat.com/contact-us",
    sourceType: "automation_run_89_public_research",
    country: "Canada / global electronic label demo submission route",
    language: "en",
    genres: ["monstercat", "labelradar", "demo-submission", "electronic", "edm", "bass", "dubstep", "drum-and-bass", "house", "future-bass", "progressive-house", "silk", "uncaged", "instinct", "free-first", "login-required", "manual-review"],
    submissionMethod: "official-monstercat-labelradar-demo-submission-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Monstercat publishes official Uncaged, Instinct and Silk demo routes through LabelRadar. External LabelRadar account/session handling, brand-route selection, original-work checks, rights/originality assertions, metadata, track-link/upload choice and label fit require owner review. Protected support/press/event contact placeholders were observed but not decoded or stored.",
    notes: "Public research confirmed Monstercat is active with July 3, 2026 Uncaged and Instinct releases plus a June 30, 2026 Silk release. The official Contact Us page says Monstercat listens to every demo submitted, asks for best original work only, and links Uncaged Demo, Instinct Demo and Silk Demo on LabelRadar. No account was created, no login was used, no submission was made, no email was sent, no file/link was delivered and no anti-bot or session controls were interacted with."
  },
  {
    name: "Spinnin Records Talent Pool Demo Upload Route",
    websiteUrl: "https://spinninrecords.com/",
    submissionUrl: "https://spinninrecords.com/talentpool/",
    sourceUrl: "https://spinninrecords.com/talentpool/",
    sourceType: "automation_run_89_public_research",
    country: "Netherlands / global dance label community demo upload route",
    language: "en",
    genres: ["spinnin-records", "talent-pool", "demo-upload", "dance", "edm", "house", "future-house", "deep-house", "electronic", "producer-community", "contest", "free-first", "login-required", "manual-review"],
    submissionMethod: "official-spinnin-records-talent-pool-demo-upload-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Spinnin Records Talent Pool requires account creation or login before demo submission. Uploading a track, choosing SoundCloud/demo assets, entering metadata, accepting terms, checking contest/community context, confirming rights/originality and evaluating label fit must remain manual.",
    notes: "Public research confirmed Spinnin Records shows current release and upcoming-release activity with a 2026 site footer. The Talent Pool page explicitly says users must create an account first and log in to submit a demo, and it shows active Most popular and Latest additions demo sections. No account was created, no login was used, no track was uploaded, no email was sent and no platform restrictions were bypassed."
  },
  {
    name: "STMPD RCRDS SoundCloud Demo Drop Route",
    websiteUrl: "https://stmpdrcrds.com/",
    submissionUrl: "https://demo.stmpdrcrds.com/",
    sourceUrl: "https://demo.stmpdrcrds.com/",
    sourceType: "automation_run_89_public_research",
    country: "Netherlands / global electronic label demo-drop route",
    language: "en",
    genres: ["stmpd-rcrds", "demo-drop", "soundcloud-login", "electronic", "house", "future-house", "bass", "progressive-house", "martin-garrix", "free-first", "login-required", "manual-review"],
    submissionMethod: "official-stmpd-rcrds-soundcloud-demo-drop-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because the STMPD RCRDS demo drop uses SoundCloud connection/login and requires original demo tracks only, with no remixes or bootlegs. SoundCloud account/session handling, terms acceptance, track choice, metadata, rights/originality and label fit require owner review.",
    notes: "Public research confirmed STMPD RCRDS is active with a June 26, 2026 release listed on the official site and an official link to demo.stmpdrcrds.com. The Demo Drop page says to send original demo tracks for review and uses SoundCloud to listen and review the track. No SoundCloud login was used, no demo was submitted, no file/link was delivered, no account was created and no cookie/session or platform restriction was bypassed."
  },
  {
    name: "Revealed Recordings Account-Gated Demo Submission Route",
    websiteUrl: "https://www.revealedrecordings.com/",
    submissionUrl: "https://www.revealedrecordings.com/demo",
    sourceUrl: "https://www.revealedrecordings.com/demo",
    sourceType: "automation_run_89_public_research",
    country: "Netherlands / global electronic label account-gated demo route",
    language: "en",
    genres: ["revealed-recordings", "hardwell", "demo-submission", "account-gated", "spotify-login", "big-room", "electro-house", "progressive-house", "bass-house", "dance-pop", "techno", "freemium", "login-required", "manual-review"],
    submissionMethod: "official-revealed-recordings-account-gated-demo-submission-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because the official Revealed Recordings Demo route redirects to a sign-in flow with email/password or Spotify connection. Account/session handling, possible Pro side-route evaluation, metadata, track choice, rights/originality confirmation, label fit and terms acceptance require owner review.",
    notes: "Public research confirmed Revealed Recordings exposes a Demo navigation route, Sign in/Create account controls, active release listings and Pro side routes. Opening the Demo route redirected to a login page with email/password and Spotify connection options. No account was created, no login or Spotify connection was used, no demo was uploaded, no payment route was activated and no authentication or platform restriction was bypassed."
  },
  {
    name: "NCS LabelRadar Demo Submission Route",
    websiteUrl: "https://ncs.io/",
    submissionUrl: "https://ncs.io/contact",
    sourceUrl: "https://ncs.io/contact",
    sourceType: "automation_run_89_public_research",
    country: "United Kingdom / global copyright-free electronic label demo submission route",
    language: "en",
    genres: ["nocopyrightsounds", "ncs", "labelradar", "demo-submission", "copyright-free", "electronic", "edm", "house", "drum-and-bass", "dubstep", "trap", "dance-pop", "future-bass", "creator-music", "free-first", "login-required", "manual-review"],
    submissionMethod: "official-ncs-labelradar-demo-submission-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because NCS routes Demo Submissions to LabelRadar, while NCS account controls and external LabelRadar handling may require login/session steps. Track selection, metadata, rights/originality, copyright-free usage implications, label fit and terms acceptance require owner review.",
    notes: "Public research confirmed NCS is active with recent releases, works with artists across all genres of electronic music, and lists Demo Submissions as a LabelRadar route on its official contact page. No NCS or LabelRadar account was created, no login was used, no demo was submitted, no file/link was delivered, no email was sent and no anti-bot/session controls were interacted with."
  }
];
