import type { PlatformInput } from '../models/types.js';

export const run81SeedPlatforms: PlatformInput[] = [
  {
    name: "Spotify for Artists Playlist Pitching",
    websiteUrl: "https://artists.spotify.com/",
    submissionUrl: "https://artists.spotify.com/playlisting",
    sourceUrl: "https://artists.spotify.com/playlisting",
    sourceType: "automation_run_81_public_research",
    country: "Global / official Spotify editorial playlist pitching route through Spotify for Artists",
    language: "en",
    genres: ["spotify-for-artists", "playlist-pitching", "editorial-playlists", "streaming-platform", "global", "release-pitch", "electronic", "reggae", "dub", "world", "pop", "dance", "free", "login-required", "manual-review"],
    submissionMethod: "official-spotify-for-artists-playlist-pitch-tool",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Spotify for Artists requires authenticated artist/team access, unreleased music selection, one-song-per-release choice, location/story/genre metadata, release timing and editorial fit decisions.",
    notes: "Public research confirmed Spotify for Artists states it is the only way to submit new music for Spotify playlisting and describes a global pitch workflow with song choice, location, story, genre and editor review. No login was used, no pitch was submitted, no upload was made and no validation control was interacted with."
  },
  {
    name: "DropTrack Artist and Label Targeted Submissions",
    websiteUrl: "https://www.droptrack.com/",
    submissionUrl: "https://www.droptrack.com/",
    sourceUrl: "https://www.droptrack.com/",
    sourceType: "automation_run_81_public_research",
    country: "Global / artist and label music-promotion platform for DJs, labels, playlist curators, blogs and radio contacts",
    language: "en",
    genres: ["droptrack", "music-promotion", "targeted-submissions", "djs", "labels", "playlist-curators", "blogs", "radio-contacts", "campaigns", "analytics", "electronic", "reggae", "dub", "world", "dance", "freemium", "login-required", "payment-side-route", "manual-review"],
    submissionMethod: "official-droptrack-artist-label-signup-and-targeted-submission-campaign-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because DropTrack requires account signup, campaign setup, contact targeting, possible paid/pro choices, playlist-placement or ad-budget decisions, metadata, track-link/package prep and consent before sending any campaign.",
    notes: "Public research confirmed DropTrack's active 2026 official site, artist/label signup routes, targeted submissions to DJs, labels, playlist curators, blogs and radio, campaign analytics and pricing/pro side routes. No account was created, no campaign was launched, no contacts were messaged and no payment route was activated."
  },
  {
    name: "Amazing Radio Artist Upload Route",
    websiteUrl: "https://amazingradio.com/",
    submissionUrl: "https://amazingradio.com/",
    sourceUrl: "https://amazingradio.com/",
    sourceType: "automation_run_81_public_research",
    country: "United Kingdom / United States / global emerging-artist radio upload platform",
    language: "en",
    genres: ["amazing-radio", "emerging-artists", "unsigned-artists", "radio-airplay", "artist-upload", "discovery-platform", "independent-music", "electronic", "reggae", "dub", "world", "dance", "free", "javascript-app", "login-required", "manual-review"],
    submissionMethod: "official-amazing-radio-javascript-artist-upload-and-radio-discovery-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because the official Amazing Radio route is a JavaScript/authenticated upload workflow, requiring account access, track upload, metadata, rights/originality assertions, profile fit and editorial/radio suitability checks.",
    notes: "Public research confirmed the official Amazing Radio web app is active but JavaScript-gated, and independent reference material identifies Amazing Radio as an international radio platform where unsigned artists can submit music through the Amazing Radio website. No account was created, no upload was attempted and no JavaScript/login barrier was bypassed."
  },
  {
    name: "Music Xray Song Opportunity Submissions",
    websiteUrl: "https://musicxray.com/",
    submissionUrl: "https://musicxray.com/",
    sourceUrl: "https://musicxray.com/",
    sourceType: "automation_run_81_public_research",
    country: "Global / New York-based A&R and music-industry opportunity submission marketplace",
    language: "en",
    genres: ["music-xray", "a-and-r", "song-opportunities", "industry-professionals", "guaranteed-listen", "critiques", "songwriter-opportunities", "sync", "labels", "publishers", "electronic", "reggae", "dub", "world", "paid", "login-required", "manual-review"],
    submissionMethod: "official-music-xray-song-opportunities-paid-submission-marketplace-route",
    feeRequired: true,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Music Xray is a paid opportunity marketplace with login, opportunity selection, fee/payment approval, rights and song-fit checks, pitch/package preparation and review of critique/guaranteed-listen terms.",
    notes: "Public research confirmed Music Xray's official site is reachable and independent reference material describes Music Xray as active and as an online platform where artists submit songs to industry professionals for a fee in exchange for a guaranteed listen and response. No signup, payment, upload or submission was attempted."
  },
  {
    name: "SubmitHub Curator Submission Platform",
    websiteUrl: "https://www.submithub.com/",
    submissionUrl: "https://www.submithub.com/submit",
    sourceUrl: "https://www.submithub.com/submit",
    sourceType: "automation_run_81_public_research",
    country: "Global / curator submission marketplace for blogs, playlists, influencers and labels",
    language: "en",
    genres: ["submithub", "curator-submissions", "music-blogs", "spotify-playlists", "influencers", "labels", "playlist-pitching", "electronic", "reggae", "dub", "world", "dance", "freemium", "paid-credits", "login-required", "manual-review"],
    submissionMethod: "official-submithub-submit-route-for-curator-pitches",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because SubmitHub requires account/session handling, curator selection, possible paid-credit approval, genre targeting, pitch copy, rights/metadata review and manual acceptance of platform terms before any submission.",
    notes: "Public research confirmed the official SubmitHub submit route is reachable, while independent reporting describes artists submitting through SubmitHub to blogs/playlists with paid submission credits commonly used. No account was created, no credits were purchased, no curator was selected and no submission was made."
  }
];
