import type { PlatformInput } from '../models/types.js';

export const run84SeedPlatforms: PlatformInput[] = [
  {
    name: "EARMILK Submit Music via SubmitHub and Pillargram",
    websiteUrl: "https://earmilk.com/",
    submissionUrl: "https://earmilk.com/submit-music/",
    sourceUrl: "https://earmilk.com/submit-music/",
    sourceType: "automation_run_84_public_research",
    country: "United States / global online music publication and curator submission route",
    language: "en",
    genres: ["earmilk", "music-blog", "curator", "submithub", "pillargram", "premiere-submission", "electronic", "dance", "hip-hop", "indie", "pop", "rock", "freemium", "login-required", "manual-review"],
    submissionMethod: "official-earmilk-submit-music-through-submithub-pillargram-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because EARMILK currently routes submissions exclusively through third-party SubmitHub or Pillargram workflows, requiring account/session handling, curator/publication targeting, pitch copy, premiere/release context, track-link/package review, possible credit/payment choices and editorial fit assessment.",
    notes: "Public research confirmed EARMILK's Submit Music page says submissions are currently accepted exclusively through SubmitHub or Pillargram, with fresh July 2026 music activity visible on the same page. No SubmitHub or Pillargram account was created, no login was used, no pitch was sent and no paid-credit route was activated."
  },
  {
    name: "WXPN Airplay Music Director and Local Show Submission Route",
    websiteUrl: "https://xpn.org/",
    submissionUrl: "https://xpn.org/contact/",
    sourceUrl: "https://xpn.org/contact/",
    sourceType: "automation_run_84_public_research",
    country: "United States / Philadelphia public radio airplay submission route",
    language: "en",
    genres: ["wxpn", "public-radio", "noncommercial-radio", "airplay", "music-director", "local-show", "epk", "download-link", "electronic", "reggae", "world", "dance", "free", "email-route", "protected-mailto", "manual-review"],
    submissionMethod: "official-wxpn-music-director-local-show-email-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WXPN instructs artists to send an EPK and digital download link by email to the Music Director or Local Show host, requiring route choice, WAV/high-quality MP3 link preparation, artist bio, local-show relevance, metadata, FCC-clean/explicit labeling and station-fit review.",
    notes: "Public research confirmed WXPN's contact page has a Submitting Music for Airplay section and a Local Show submission route, while current July 2026 site activity confirmed the platform is active. Mailto routes were observed but not decoded. No email was sent, no files were uploaded and no SMTP/MX probing was performed."
  },
  {
    name: "KFAI Music Department and Music Library Submission Route",
    websiteUrl: "https://kfai.org/",
    submissionUrl: "https://kfai.org/about/contact/",
    sourceUrl: "https://kfai.org/about/contact/",
    sourceType: "automation_run_84_public_research",
    country: "United States / Minneapolis community radio music department route",
    language: "en",
    genres: ["kfai", "community-radio", "music-library", "music-department", "airplay", "independent-music", "electronic", "reggae", "world", "dance", "free", "email-route", "redacted-email-link", "manual-review"],
    submissionMethod: "official-kfai-music-department-music-library-email-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KFAI provides a Music Department and Music Library route for artists to share music, but the fetched public email link was redacted; outbound email, track/package selection, metadata, clean/explicit labeling, download-link permissions and station-library fit require human approval.",
    notes: "Public research confirmed KFAI's contact page invites artists to share music with the KFAI Music Department and Music Library, and the site shows current July 2026 activity. The public email link was observed as redacted by the fetched page. No email was decoded or sent, no files were transferred and no SMTP/MX probing was performed."
  },
  {
    name: "KGNU Music Department Staff and DJ Contact Form Route",
    websiteUrl: "https://kgnu.org/",
    submissionUrl: "https://kgnu.org/contact-us/",
    sourceUrl: "https://kgnu.org/contact-us/",
    sourceType: "automation_run_84_public_research",
    country: "United States / Boulder-Denver independent community radio contact route",
    language: "en",
    genres: ["kgnu", "community-radio", "music-department", "dj-contact", "staff-contact", "contact-form", "electronic", "reggae", "world", "dance", "free", "captcha", "manual-review"],
    submissionMethod: "official-kgnu-music-department-staff-dj-contact-form-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KGNU exposes a staff/DJ contact form with a Music department option and reCAPTCHA v3, so the form must not be automated or bypassed; message copy, track links, metadata, routing and DJ/station fit require review.",
    notes: "Public research confirmed KGNU is active with July 2026 music/news content and provides a contact form with Department choices including Music plus reCAPTCHA v3. No CAPTCHA was interacted with, no form was submitted, no email was sent and no anti-bot controls were bypassed."
  },
  {
    name: "WMNF Submit Your Music to Music Department Route",
    websiteUrl: "https://www.wmnf.org/",
    submissionUrl: "https://www.wmnf.org/submit-your-music-to-wmnf/",
    sourceUrl: "https://www.wmnf.org/submit-your-music-to-wmnf/",
    sourceType: "automation_run_84_public_research",
    country: "United States / Tampa community radio music department submission route",
    language: "en",
    genres: ["wmnf", "community-radio", "music-department", "airplay", "upload-form", "musicrelations", "electronic", "reggae", "world", "dance", "free", "email-route", "file-upload", "manual-review"],
    submissionMethod: "official-wmnf-submit-music-form-and-musicrelations-email-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WMNF provides a public upload form and musicrelations email route, requiring artist/location context, Tampa Bay roots/show-date questions, audio file selection, contact email, metadata, file-size/format compliance, clean/explicit labeling and station-fit review.",
    notes: "Public research confirmed WMNF's Submit Your Music page invites artists and representatives to submit music to WMNF's Music Department, lists musicrelations@wmnf.org, and includes a file-upload form accepting mp3, wav, flac, aac, aiff, wma and m4a files up to 50 MB with a maximum of five files. No email was sent, no form was submitted, no file was uploaded and no route was activated."
  }
];
