import type { PlatformInput } from '../models/types.js';

export const run87SeedPlatforms: PlatformInput[] = [
  {
    name: "SomaFM Digital Airplay Submission Route",
    websiteUrl: "https://somafm.com/",
    submissionUrl: "https://somafm.com/contact/submitmusic.html",
    sourceUrl: "https://somafm.com/contact/submitmusic.html",
    sourceType: "automation_run_87_public_research",
    country: "United States / global listener-supported internet radio digital airplay submission route",
    language: "en",
    genres: ["somafm", "internet-radio", "listener-supported", "commercial-free", "underground-radio", "digital-submission", "music-director-email", "bandcamp-yum-code", "dropbox", "wetransfer", "high-bitrate-mp3", "electronic", "ambient", "downtempo", "reggae", "world", "indie-pop", "metal", "free", "no-ai", "manual-review"],
    submissionMethod: "official-somafm-digital-airplay-music-director-email-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because SomaFM publishes official channel-specific music-director email routes and strict digital-submission requirements: no AI music, no CDs, high-bitrate MP3 downloads via Bandcamp/YUM, WeTransfer or Dropbox, correct metadata, no low-bitrate/streaming-only files and no duplicate mass-emailing across music directors. Channel routing, track/package selection, rights/originality, no-AI eligibility, metadata and station fit require review.",
    notes: "Public research confirmed SomaFM is active, listener-supported, commercial-free and hand-curated, with a 2026 copyright footer and live channel activity. Official submission and contact pages list public music-director routes. No email was sent, no download link was delivered, no file was transferred, no physical media was sent and no SMTP/MX probing was performed."
  },
  {
    name: "WRTC-FM Trinity College Music Director and Genre Coordinator Route",
    websiteUrl: "https://wrtcfm.com/",
    submissionUrl: "https://wrtcfm.com/about-contacts",
    sourceUrl: "https://wrtcfm.com/about-contacts",
    sourceType: "automation_run_87_public_research",
    country: "United States / Hartford non-commercial college radio music director and genre coordinator route",
    language: "en",
    genres: ["wrtc", "college-radio", "non-commercial-radio", "freeform", "music-director", "genre-coordinator", "physical-mail", "world", "latin", "jazz", "rock", "gospel", "soul", "funk", "electronic", "reggae", "free", "manual-review"],
    submissionMethod: "official-wrtc-music-director-genre-coordinator-and-physical-mail-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WRTC's official contact page tells people with music they wish WRTC to have to contact the appropriate genre coordinator or send music to Attn: Music Director at the station mailing address. Genre routing, physical package prep, metadata, clean/explicit labeling, rights/originality and non-commercial college-radio fit require review.",
    notes: "Public research confirmed WRTC-FM is active as Trinity College's non-commercial station with recent 2025 programming posts and an official About & Contacts page naming Music Director/genre-coordinator routing. No email was sent, no physical mail was sent, no protected or obfuscated contact was decoded and no SMTP/MX probing was performed."
  },
  {
    name: "WMFO Tufts Freeform Music Department Submission Route",
    websiteUrl: "https://www.wmfo.org/",
    submissionUrl: "https://www.wmfo.org/contact/",
    sourceUrl: "https://www.wmfo.org/contact/",
    sourceType: "automation_run_87_public_research",
    country: "United States / Medford Tufts freeform college radio music department route",
    language: "en",
    genres: ["wmfo", "college-radio", "freeform-radio", "music-department", "music-director-email", "cd", "vinyl", "digital-media", "rivendell", "electronic", "reggae", "world", "dance", "hip-hop", "indie", "free", "manual-review"],
    submissionMethod: "official-wmfo-music-director-email-and-music-department-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WMFO's official site lists active 2025-2026 station leadership, a public Music Director email route, and describes a Music Department that receives CDs, occasional vinyl/cassettes and adds digital media to its Rivendell database. Submission-package choice, audio format/link choice, metadata, clean/explicit labeling, rights/originality and freeform-radio fit require review.",
    notes: "Public research confirmed WMFO is active with a 2026 footer, round-the-clock freeform broadcasting, a Music Department, and public Music Director email md@wmfo.org. No email was sent, no file was transferred, no media was mailed, no account/session was used and no SMTP/MX probing was performed."
  },
  {
    name: "WESU 88.1FM Music Directors Submission Route",
    websiteUrl: "https://www.wesufm.org/",
    submissionUrl: "https://www.wesufm.org/contact-us/",
    sourceUrl: "https://www.wesufm.org/contact-us/",
    sourceType: "automation_run_87_public_research",
    country: "United States / Middletown Wesleyan community and college radio music-director submission route",
    language: "en",
    genres: ["wesu", "college-radio", "community-radio", "freeform-radio", "music-director-email", "dropbox", "google-drive", "streaming-link", "physical-mail", "electronic", "reggae", "world", "dance", "hip-hop", "indie", "free", "manual-review"],
    submissionMethod: "official-wesu-music-directors-email-link-and-mailing-address-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WESU's official contact page explicitly tells artists who want to submit music to contact the Music Directors, gives the public music-director email, asks submitters to send links rather than files, and also lists station and mailing addresses. Link choice, storage permissions, no-attachment compliance, metadata, rights/originality, clean/explicit labeling and station fit require review.",
    notes: "Public research confirmed WESU is active with 2026 posts, identifies as a Wesleyan community service since 1939 and provides an official Music Directors submission route via wesumd@wesufm.org plus mailing addresses. No email was sent, no links or files were delivered, no physical mail was sent and no SMTP/MX probing was performed."
  },
  {
    name: "WXYC 89.3FM Music Department Submission Route",
    websiteUrl: "https://wxyc.org/",
    submissionUrl: "https://wxyc.org/contact",
    sourceUrl: "https://wxyc.org/contact",
    sourceType: "automation_run_87_public_research",
    country: "United States / Chapel Hill student-run freeform radio music department submission route",
    language: "en",
    genres: ["wxyc", "college-radio", "student-radio", "freeform-radio", "music-department", "music-director-email", "physical-mail", "electronic", "reggae", "world", "dancehall", "hip-hop", "jazz", "blues", "metal", "experimental", "free", "manual-review"],
    submissionMethod: "official-wxyc-music-department-email-and-physical-mail-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WXYC's official contact page explicitly says to email music submissions or distribution concerns to the Music Director address and also lists a physical WXYC Music Department address. Email/package choice, track selection, metadata, clean/explicit labeling, rights/originality and freeform station fit require review.",
    notes: "Public research confirmed WXYC is active as UNC-Chapel Hill's student-run freeform station with recent blog content and an official contact page listing md@wxyc.org and a WXYC Music Department address. No email was sent, no file/link was delivered, no physical mail was sent and no SMTP/MX probing was performed."
  }
];
