import type { PlatformInput } from '../models/types.js';

export const run82SeedPlatforms: PlatformInput[] = [
  {
    name: "TAXI Independent A&R Industry Listings",
    websiteUrl: "https://www.taxi.com/",
    submissionUrl: "https://www.taxi.com/industry",
    sourceUrl: "https://www.taxi.com/industry",
    sourceType: "automation_run_82_public_research",
    country: "Global / independent A&R, sync, publisher, label and music-library opportunity listings",
    language: "en",
    genres: ["taxi", "a-and-r", "sync-licensing", "music-industry-listings", "publishers", "record-labels", "music-libraries", "film-tv", "electronic", "reggae", "world", "pop", "dance", "paid", "membership-required", "manual-review"],
    submissionMethod: "official-taxi-industry-listing-submit-music-route",
    feeRequired: true,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because TAXI uses membership-gated industry listings with join/member-submit flows, per-opportunity briefs, deadlines, rights/originality assertions, genre and production-fit checks, AI-use restrictions, possible CD/online submission choices and payment/member approval before any submission.",
    notes: "Public research confirmed TAXI's official Industry Listings were updated March 17, 2026 and include Submit Your Music / Join to submit / Members submit here routes for labels, publishers, music supervisors, music libraries and sync opportunities. No membership was purchased, no login was used, no music was uploaded and no submission was made."
  },
  {
    name: "Sonicbids Artist Gig and EPK Opportunity Submissions",
    websiteUrl: "https://www.sonicbids.com/",
    submissionUrl: "https://www.sonicbids.com/find-gigs/",
    sourceUrl: "https://www.sonicbids.com/find-gigs/",
    sourceType: "automation_run_82_public_research",
    country: "Global / artist EPK, gig booking and industry-exposure opportunity platform",
    language: "en",
    genres: ["sonicbids", "gig-booking", "epk", "artist-profile", "promoters", "music-opportunities", "industry-exposure", "electronic", "reggae", "world", "dance", "free-and-paid", "login-required", "manual-review"],
    submissionMethod: "official-sonicbids-find-gigs-and-artist-profile-application-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Sonicbids requires account/profile creation, musician/band profile and EPK preparation, gig/opportunity selection, possible free and paid pricing paths, promoter fit checks, terms review and consent before any application or outreach.",
    notes: "Public research confirmed Sonicbids' official Find gigs and Join routes are active, include sign-in/join flows, and state that sign-up/profile handling is used to verify genuine musicians and bands. No account was created, no EPK/profile was submitted, no opportunity was applied to and no payment route was activated."
  },
  {
    name: "Songtradr Music Licensing Marketplace Upload Route",
    websiteUrl: "https://www.songtradr.com/",
    submissionUrl: "https://www.songtradr.com/",
    sourceUrl: "https://www.songtradr.com/",
    sourceType: "automation_run_82_public_research",
    country: "Global / music licensing and sync marketplace for artists, labels and rightsholders",
    language: "en",
    genres: ["songtradr", "music-licensing", "sync", "marketplace", "brands", "content-creators", "rights-management", "song-upload", "electronic", "reggae", "world", "dance", "free-and-paid", "javascript-app", "login-required", "manual-review"],
    submissionMethod: "official-songtradr-javascript-music-licensing-marketplace-upload-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Songtradr is a JavaScript/authenticated licensing marketplace involving account setup, music upload, rights ownership, licensing fee settings, metadata, songwriter/publisher splits, possible free and paid account paths and sync suitability decisions.",
    notes: "Public research confirmed Songtradr's official site is active but JavaScript-gated, and independent reference material describes artists uploading music and setting licensing fees on the platform. No JavaScript barrier was bypassed, no account was created, no track was uploaded and no licensing terms were set."
  },
  {
    name: "Nialler9 Music Promo and Release Submission Route",
    websiteUrl: "https://nialler9.com/",
    submissionUrl: "https://nialler9.com/contact/",
    sourceUrl: "https://nialler9.com/contact/",
    sourceType: "automation_run_82_public_research",
    country: "Ireland / global independent music blog, playlists and release coverage route",
    language: "en",
    genres: ["nialler9", "music-blog", "playlists", "new-music", "promo-email", "premieres", "album-links", "release-coverage", "electronic", "reggae", "world", "dance", "free", "protected-contact", "manual-review"],
    submissionMethod: "official-nialler9-protected-email-link-promo-release-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because the route is outbound email to protected public contact links and requires release selection, advance timing, streaming/download links, bio, release dates, socials, hi-res assets, no-attachment compliance and editorial fit review.",
    notes: "Public research confirmed Nialler9's official contact page is active with 2026 site activity and lists public music/promo/release contact routes plus guidance for streaming links, downloadable assets, release context and no chase-ups. Protected email links were observed but not decoded; no email was sent and no SMTP/MX probing was performed."
  },
  {
    name: "LabelRadar Artist Demo Submission Platform",
    websiteUrl: "https://www.labelradar.com/",
    submissionUrl: "https://www.labelradar.com/artists",
    sourceUrl: "https://www.labelradar.com/artists",
    sourceType: "automation_run_82_public_research",
    country: "Global / electronic, dance and label demo submission platform",
    language: "en",
    genres: ["labelradar", "demo-submissions", "record-labels", "artist-upload", "electronic", "dance", "edm", "house", "dubstep", "bass-music", "reggae-fusion", "free-and-paid", "javascript-app", "login-required", "manual-review"],
    submissionMethod: "official-labelradar-javascript-artist-demo-submission-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because LabelRadar's artist route is a JavaScript/authenticated demo-submission workflow requiring account access, demo upload, label targeting, genre fit, rights/originality review, possible free and paid account choices and platform terms approval.",
    notes: "Public research confirmed the official LabelRadar artist route is reachable but JavaScript-gated. No account was created, no demo was uploaded, no label was targeted, no payment route was activated and no validation control was interacted with."
  }
];
