import type { PlatformInput } from '../models/types.js';

export const run99SeedPlatforms: PlatformInput[] = [
  {
    name: "Spotify for Artists Editorial Playlist Pitching Route",
    websiteUrl: "https://artists.spotify.com/",
    submissionUrl: "https://artists.spotify.com/playlisting",
    sourceUrl: "https://support.spotify.com/us/artists/article/pitching-music-to-playlist-editors/",
    sourceType: "automation_run_99_public_research",
    country: "Sweden / United States / global streaming and editorial playlist pitching platform",
    language: "en",
    genres: ["spotify-for-artists", "editorial-playlists", "release-radar", "global", "electronic", "reggae", "dub", "dancehall", "world", "playlist-pitching", "unreleased-music", "login-required", "free-first", "manual-review"],
    submissionMethod: "official-spotify-for-artists-unreleased-song-editorial-playlist-pitch-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Spotify's official playlist-pitching route requires Spotify for Artists Admin or Editor access, an upcoming unreleased release delivered through a distributor, one-song-at-a-time selection, release-date timing and detailed genre/mood/story metadata. Login/session handling, rights verification, distributor status, release timing, song choice and pitch copy must remain manual.",
    notes: "Public research confirmed Spotify for Artists is the official route to pitch upcoming unreleased music to playlist editors, asks artists to log in, requires delivery at least 7 days before release, limits pitches to one song at a time, and does not guarantee placement. No login was used, no pitch was created, no distributor action was taken, no emails were sent and no SMTP or MX probing was performed."
  },
  {
    name: "MusoSoup Artist Campaign Music Submission Route",
    websiteUrl: "https://musosoup.com/",
    submissionUrl: "https://app.musosoup.com/",
    sourceUrl: "https://musosoup.com/",
    sourceType: "automation_run_99_public_research",
    country: "United Kingdom / global curator, playlist, press and radio campaign platform",
    language: "en",
    genres: ["musosoup", "curator-marketplace", "playlisting", "press", "radio", "independent-artists", "electronic", "house", "techno", "world-music", "reggae", "latin", "campaign", "login-required", "payment-side-route", "freemium", "free-first", "manual-review"],
    submissionMethod: "official-musosoup-submit-music-campaign-review-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because MusoSoup allows free initial submission but later requires account creation and campaign activation/payment if accepted. The route also exposes paid and free curator offers, MP3/link upload, release timing up to 90 days, coverage guarantees, AI/botted-playlist policies and curator-marketplace choices. Submission, account creation, campaign-fee approval, paid/free offer selection and pitch materials must remain manual.",
    notes: "Public research confirmed MusoSoup connects artists with global curators, playlists and press, offers a Submit music route, says artists can upload a single, EP or album for free by sharing a link or MP3, says reviews may take up to 24 hours, and says successful campaigns require account creation and a campaign fee. The site showed July 2026 blog activity. No account was created, no track was uploaded, no campaign was activated, no curator offer was accepted, no payment was made and no SMTP or MX probing was performed."
  },
  {
    name: "DailyPlaylists Free Spotify Playlist Submission Route",
    websiteUrl: "https://dailyplaylists.com/",
    submissionUrl: "https://dailyplaylists.com/submit-song/add-song/",
    sourceUrl: "https://dailyplaylists.com/",
    sourceType: "automation_run_99_public_research",
    country: "Global Spotify playlist pitching and curator marketplace platform",
    language: "en",
    genres: ["dailyplaylists", "spotify-playlists", "curator-marketplace", "playlist-pitching", "independent-artists", "electronic", "dance", "reggae", "world", "submit-song", "login-required", "premium-credits", "freemium", "free-first", "manual-review"],
    submissionMethod: "official-dailyplaylists-submit-song-free-standard-submission-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because DailyPlaylists exposes a free Submit a Song workflow but requires sign-in, Spotify track selection/search, curator/playlist relevance decisions, weekly standard-submission limits and optional paid standard submissions, Premium Credits or Professional subscription choices. Login, playlist targeting, anti-spam/relevance checks, paid add-ons and any business contact use must remain manual.",
    notes: "Public research confirmed DailyPlaylists says artists can submit music for free, lists a marketplace of more than 18,000 playlists, shows +75M total submissions and +500k artists submitting, exposes a Submit a Song route, lists Free tier 10 standard submissions weekly, and publishes info@dailyplaylists.com plus 2026 footer/pricing pages. No sign-in was used, no song was searched or submitted, no playlist was selected, no credits or subscriptions were purchased and no SMTP or MX probing was performed."
  },
  {
    name: "KBOO Portland Physical Music Submission Route",
    websiteUrl: "https://kboo.fm/",
    submissionUrl: "https://kboo.fm/submit-your-music",
    sourceUrl: "https://kboo.fm/submit-your-music",
    sourceType: "automation_run_99_public_research",
    country: "United States / Portland Oregon community radio with online listening",
    language: "en",
    genres: ["kboo", "community-radio", "physical-mail", "electronic", "rock", "punk", "world-music", "reggae", "hip-hop", "jazz", "programmer-review", "free-first", "manual-review"],
    submissionMethod: "official-kboo-submit-your-music-physical-mail-genre-attention-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KBOO does not yet have a digital library and explicitly says it lacks capacity to download and burn CDs of digital submissions. Submissions must be physically mailed with the correct genre attention line, and all submissions become KBOO property with no guarantee of airplay. Physical package preparation, genre routing, risk acceptance and show targeting must remain manual.",
    notes: "Public research confirmed KBOO's official Submit Your Music page gives a physical mailing address, asks senders to address submissions by genre, includes Electronic/other, Rock/Punk/Electronic, World Music/Reggae, Hip-hop and Jazz routing, states submissions are not returned, and says no airplay guarantee is expressed or implied. No physical mail was sent, no login was used, no files or links were delivered and no SMTP or MX probing was performed."
  },
  {
    name: "WRIR Richmond Music Department Submission Route",
    websiteUrl: "https://www.wrir.org/",
    submissionUrl: "https://www.wrir.org/station/contact/",
    sourceUrl: "https://www.wrir.org/station/contact/",
    sourceType: "automation_run_99_public_research",
    country: "United States / Richmond Virginia independent community radio with worldwide stream",
    language: "en",
    genres: ["wrir", "richmond", "community-radio", "music-department", "public-email", "physical-mail", "world", "house", "hip-hop", "electronic", "indie", "reggae", "dj-mixes", "protected-contact", "free-first", "manual-review"],
    submissionMethod: "official-wrir-music-department-email-and-mailing-address-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WRIR's contact page points music submissions to its Music Department email and lists a physical mailing address, but the fetched page redacted the public email address. The contact must not be decoded or guessed. Email/package copy, genre/show fit, link or file policy, physical-mail choice and station relevance require manual review.",
    notes: "Public research confirmed WRIR's official contact page was updated in 2026, says to submit music to the music department by email, lists a mailing address, and shows active schedule/programming with electronic, world, hip-hop, house and DJ-oriented shows. The email was protected/redacted by the fetch layer, so it was not decoded or guessed. No email was sent, no files or links were delivered, no physical mail was sent, no cookie/session controls were interacted with and no SMTP or MX probing was performed."
  }
];
