import type { PlatformInput } from '../models/types.js';

export const run94SeedPlatforms: PlatformInput[] = [
  {
    name: "95bFM Submit Music Email Route",
    websiteUrl: "https://95bfm.com/",
    submissionUrl: "https://95bfm.com/news/how-do-you-do-submitting-music",
    sourceUrl: "https://95bfm.com/news/how-do-you-do-submitting-music",
    sourceType: "automation_run_94_public_research",
    country: "New Zealand / Auckland independent corporate-free broadcaster",
    language: "en",
    genres: ["95bfm", "auckland", "new-zealand", "independent-radio", "alternative", "electronic", "reggae", "world", "streaming-link", "lossless-download", "public-email", "protected-contact", "free-first", "manual-review"],
    submissionMethod: "official-95bfm-submit-music-email-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because 95bFM asks artists to email a streaming link and a download link to a lossless file, avoids account-gated streaming/download services and passworded Dropbox sync, asks for release and origin context only, and treats A/B playlisting eligibility differently for tracks older than one month. The official public email was redacted by the fetch layer and must not be decoded or guessed. Link permissions, release timing, track fit, no-password/no-login constraints and protected-contact boundaries must remain manual.",
    notes: "Public research confirmed 95bFM's official Submit Music page gives authorized music-submission guidance, and the active 2026 homepage describes 95bFM as New Zealand's oldest corporate-free broadcaster dedicated to alternative music and independent journalism. No email was sent, no public email was decoded beyond what the page safely exposed, no files or download links were delivered, no bCard/login route was used and no SMTP or MX probing was performed."
  },
  {
    name: "WFMU Send Music Music Director Review Route",
    websiteUrl: "https://wfmu.org/",
    submissionUrl: "https://wfmu.org/sendmusic.html",
    sourceUrl: "https://wfmu.org/sendmusic.html",
    sourceType: "automation_run_94_public_research",
    country: "United States / New Jersey and New York freeform independent radio",
    language: "en",
    genres: ["wfmu", "freeform-radio", "independent-radio", "music-director", "physical-mail", "vinyl", "cd", "cassette", "electronic", "reggae", "world", "js-required-contact-form", "free-first", "manual-review"],
    submissionMethod: "official-wfmu-music-director-physical-review-and-js-mail-page-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WFMU's official route welcomes physical review materials through the Music Director, while the Music Department contact page is a JavaScript-required message form. Physical package preparation, format choice, contact-form/session behavior, Music Director routing, release/package fit, mailing address verification and no-form-submission boundaries must remain manual.",
    notes: "Public research confirmed WFMU's official Send Music page invites mainstream and marginal music for review and lists vinyl, CD, CD-R and cassette formats plus Music Director physical mailing addresses. The linked WFMU Music Department Mail Page exposes a public message workflow but requires JavaScript. No form was submitted, no email was sent, no physical mail was sent, no login/register route was used, no file or link was delivered and no SMTP or MX probing was performed."
  },
  {
    name: "KEXP Airplay Rotation Submission Guidelines Route",
    websiteUrl: "https://www.kexp.org/",
    submissionUrl: "https://www.kexp.org/about/submission-guidelines/",
    sourceUrl: "https://www.kexp.org/about/submission-guidelines/",
    sourceType: "automation_run_94_public_research",
    country: "United States / Seattle and Bay Area listener-powered independent radio",
    language: "en",
    genres: ["kexp", "seattle", "bay-area", "listener-powered", "independent-radio", "music-director", "rotation-consideration", "electronic", "reggae", "world", "public-email", "wav-download", "fcc-clean", "free-first", "manual-review"],
    submissionMethod: "official-kexp-music-director-digital-airplay-consideration-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KEXP's official Music Director route asks for streaming and WAV download links, no attachments, artist/pronoun metadata, release details, focus tracks, clean edits for FCC violations, lyrics, credits, press assets and relevant Pacific Northwest or Bay Area show context. Link permissions, clean-edit checks, one-sheet quality, host targeting, no-physical-submission handling and no-payola/payment-boundary compliance must remain manual.",
    notes: "Public research confirmed KEXP's official Contact page lists md@kexp.org for rotation consideration and the Submission Guidelines page provides detailed Music Director instructions, explicitly says there is no guarantee of spins and says artists cannot pay KEXP to play music. No email was sent, no files or links were delivered, no physical materials were sent, no donation/sponsor/payment route was used and no SMTP or MX probing was performed."
  },
  {
    name: "triple j Unearthed Artist Upload and Airplay Route",
    websiteUrl: "https://www.abc.net.au/triplejunearthed",
    submissionUrl: "https://help.abc.net.au/hc/en-us/articles/360001154256-How-do-I-upload-my-music-to-triple-j-Unearthed",
    sourceUrl: "https://help.abc.net.au/hc/en-us/articles/360001154256-How-do-I-upload-my-music-to-triple-j-Unearthed",
    sourceType: "automation_run_94_public_research",
    country: "Australia / national independent Australian music discovery platform",
    language: "en",
    genres: ["triple-j-unearthed", "abc", "australia", "independent-artists", "artist-profile", "track-upload", "airplay-consideration", "electronic", "pop", "hip-hop", "beats", "rnb", "account-required", "eligibility-restricted", "free-first", "manual-review"],
    submissionMethod: "official-triple-j-unearthed-abc-account-artist-profile-upload-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because triple j Unearthed requires an ABC account login, an artist profile, an audio upload and completion of the track form before the Unearthed team listens and approves the track. The official FAQ also limits artist uploading to Australian citizens or residents and applies an original-track/no-major-label eligibility boundary. Account creation, residency eligibility, artist profile setup, rights checks, metadata and upload-form handling must remain manual.",
    notes: "Public research confirmed the active triple j Unearthed site shows current 3 July 2026 staff reviews and describes a large discovery platform for Australian musicians. Official ABC Help articles explain how to create an account/profile, upload music, get airplay consideration, and who can enter. No ABC account was created, no login was used, no upload form was submitted, no files were transferred and no CAPTCHA/session controls were bypassed."
  },
  {
    name: "NTS Radio Mixtape Submission Call Route",
    websiteUrl: "https://www.nts.live/",
    submissionUrl: "https://www.nts.live/",
    sourceUrl: "https://www.nts.live/",
    sourceType: "automation_run_94_public_research",
    country: "United Kingdom / global online underground radio platform",
    language: "en",
    genres: ["nts-radio", "global-online-radio", "underground", "mixtape-submission", "trap", "rap", "electronica", "ambient", "dub", "reggae", "reggaeton", "house", "rnb", "js-apply-route", "free-first", "manual-review"],
    submissionMethod: "official-nts-radio-public-mixtape-submission-call-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because the official NTS homepage shows an active 'Now taking submissions - send us a mixtape' call with an Apply Now prompt, but the safe fetched page did not expose a complete static submission endpoint. The site also shows My NTS/supporter/session features that must not be used without approval. Submission target resolution, show/genre fit, mixtape rights, tracklist/context, any login/session boundary and apply-form behavior must remain manual.",
    notes: "Public research confirmed the official NTS homepage is active, exposes the mixtape submission call, and shows genre areas relevant to MarcsMusic including rap/trap, electronica/ambient, dub/reggae, reggaeton, house and R&B. No Apply Now route was activated beyond observing the public page, no account/session/supporter route was used, no form was submitted, no files or links were delivered and no anti-bot control was bypassed."
  }
];
