import type { PlatformInput } from '../models/types.js';

export const run95SeedPlatforms: PlatformInput[] = [
  {
    name: "KZSC Santa Cruz Music Directors and Music Submission Form Route",
    websiteUrl: "https://kzsc.org/",
    submissionUrl: "https://kzsc.org/send-us-a-message/",
    sourceUrl: "https://kzsc.org/contact/",
    sourceType: "automation_run_95_public_research",
    country: "United States / Santa Cruz student-run community radio",
    language: "en",
    genres: ["kzsc", "santa-cruz", "college-radio", "community-radio", "music-directors", "rpm-electronic", "international", "hip-hop", "folk", "jazz", "blues", "public-contact-form", "physical-mail", "protected-contact", "free-first", "manual-review"],
    submissionMethod: "official-kzsc-music-directors-physical-mail-and-music-submission-contact-form-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KZSC exposes multiple genre-specific Music Director routes whose email links were redacted by the fetch layer, plus physical package addresses and a public contact form with a Music Submission option. Genre routing, protected-contact boundaries, package preparation, form validation, message copy, metadata, FCC-clean fit and station/editorial fit must remain manual.",
    notes: "Public research confirmed KZSC's official site is active with 2026 music/news content, official Station Music Director listings for Music/Rock, Hardcore, Hip Hop, RPM/Electronic, Jazz/Blues/Folk and International routes, plus official USPS/UPS package addresses and a contact form with a Music Submission category. No protected email was decoded or guessed, no form was submitted, no physical mail was sent, no files or links were delivered and no SMTP or MX probing was performed."
  },
  {
    name: "KALX Berkeley Physical Airplay Submission Route",
    websiteUrl: "https://kalx.berkeley.edu/",
    submissionUrl: "https://kalx.berkeley.edu/about/contact/",
    sourceUrl: "https://kalx.berkeley.edu/about/contact/",
    sourceType: "automation_run_95_public_research",
    country: "United States / Berkeley non-commercial freeform college radio",
    language: "en",
    genres: ["kalx", "berkeley", "college-radio", "freeform-radio", "music-director", "physical-only", "cd", "lp", "electronic", "reggae", "world", "hip-hop", "experimental", "public-email", "free-first", "manual-review"],
    submissionMethod: "official-kalx-music-director-physical-cd-lp-airplay-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KALX states airplay submissions are accepted only as physical professionally pressed CDs or LPs and explicitly rejects downloads, file-transfer services, Bandcamp, Spotify, YouTube, CD-Rs and digital submissions. Package format, mailing address, Music Director routing, no-attachment/plain-text email boundaries, metadata and freeform station fit must remain manual.",
    notes: "Public research confirmed KALX's official site is active with 2026 scheduling and chart activity, lists music@kalx.berkeley.edu for Music Directors and gives a physical music-submission policy and mailing address. No email was sent, no digital files or links were delivered, no physical mail was sent, no rejected digital route was used and no SMTP or MX probing was performed."
  },
  {
    name: "KVRX 91.7FM Austin Music Department Submission Route",
    websiteUrl: "https://www.kvrx.org/",
    submissionUrl: "https://www.kvrx.org/app/contact/",
    sourceUrl: "https://www.kvrx.org/app/contact/",
    sourceType: "automation_run_95_public_research",
    country: "United States / Austin student-run underground radio",
    language: "en",
    genres: ["kvrx", "austin", "student-radio", "underground-music", "local-discovery", "music-department", "electronic", "hip-hop", "reggae", "world", "physical-submission", "digital-submission", "no-ai", "public-email", "free-first", "manual-review"],
    submissionMethod: "official-kvrx-music-department-digital-and-physical-airplay-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KVRX gives an official Music Department submission email and mailing route, states that Music staff take physical and digital submissions, and explicitly says AI-assisted/generated music submissions will not be considered. AI-origin checks, rights/originality review, physical-vs-digital package choice, metadata, FCC-clean fit and station fit must remain manual.",
    notes: "Public research confirmed the official KVRX site describes student-run radio broadcasting underground music, live shows and local discoveries around the clock, and the official contact page lists music@kvrx.org for music submissions plus a Music Director route handling physical and digital submissions. No email was sent, no files or links were delivered, no physical mail was sent, no login was used and no SMTP or MX probing was performed."
  },
  {
    name: "KXLU 88.9FM Los Angeles Music Director and Demolisten Submission Route",
    websiteUrl: "https://kxlu.com/",
    submissionUrl: "https://kxlu.com/contact/",
    sourceUrl: "https://kxlu.com/contact/",
    sourceType: "automation_run_95_public_research",
    country: "United States / Los Angeles non-commercial educational radio",
    language: "en",
    genres: ["kxlu", "los-angeles", "college-radio", "non-commercial", "music-director", "demolisten", "unsigned-demos", "physical-mail", "fcc-clean", "electronic", "reggae", "world", "latin", "punk", "public-email", "free-first", "manual-review"],
    submissionMethod: "official-kxlu-music-director-physical-demolisten-and-genre-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KXLU separates general Music Director submissions, FCC-clean physical submissions, Demolisten unsigned-demo submissions, and punk/folk/vinyl specialty routing. Correct route selection, physical package prep, FCC-clean review, demo/genre fit, metadata, email copy and no-outbound-action boundaries must remain manual.",
    notes: "Public research confirmed KXLU is an active 24/7 non-commercial educational station with programming across world, electronic, jazz, punk, psychedelic, reggae and alternative music. Its official Contact page lists a Music Director contact, a physical mailing route, FCC-clean-only instruction and separate Demolisten and specialty-format submission instructions. No email was sent, no physical mail was sent, no files or links were delivered and no SMTP or MX probing was performed."
  },
  {
    name: "KCSB-FM Santa Barbara Artist Inquiry and Music Director Submission Route",
    websiteUrl: "https://www.kcsb.org/",
    submissionUrl: "https://www.kcsb.org/contact/artist-inquiry/",
    sourceUrl: "https://www.kcsb.org/contact/",
    sourceType: "automation_run_95_public_research",
    country: "United States / Santa Barbara community and university radio",
    language: "en",
    genres: ["kcsb", "santa-barbara", "college-radio", "community-radio", "music-director", "music-library", "artist-inquiry", "live-on-air", "music-library-addition", "premiere", "external-google-form", "physical-mail", "public-email", "free-first", "manual-review"],
    submissionMethod: "official-kcsb-music-director-email-physical-mail-contact-form-and-artist-inquiry-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KCSB exposes a Music Director email route, physical mailing addresses, a public contact form with Music Submission selection, and an Artist Inquiry flow via an external Google Form for live on-air performance, station events, music-library addition and premieres. External form handling, route selection, metadata, rights, performance/library/premiere fit, physical package prep and contact-form boundaries must remain manual.",
    notes: "Public research confirmed KCSB's official site is active with 2026 music reviews, playlists, fund-drive/news items and an Artist Inquiry page for artists, bands and DJs. The official Contact page says new releases and demos in all formats are welcome through the Music Director and lists USPS/UPS mailing addresses plus a Music Submission contact-form category. No external form was submitted, no email was sent, no files or links were delivered, no physical mail was sent and no SMTP or MX probing was performed."
  }
];
