import type { PlatformInput } from '../models/types.js';

export const run96SeedPlatforms: PlatformInput[] = [
  {
    name: "CJSW Calgary Digital Music Submission Upload Route",
    websiteUrl: "https://cjsw.com/",
    submissionUrl: "https://cjsw.com/music/submit/",
    sourceUrl: "https://cjsw.com/music/submit/",
    sourceType: "automation_run_96_public_research",
    country: "Canada / Calgary campus and community radio",
    language: "en",
    genres: ["cjsw", "calgary", "campus-radio", "community-radio", "freeform-radio", "reggae", "hip-hop", "electronic", "jazz", "experimental", "digital-upload", "jotform", "public-email-route", "protected-contact", "free-first", "manual-review"],
    submissionMethod: "official-cjsw-digital-album-upload-and-music-performance-director-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because CJSW accepts only digital album releases through an external Jotform upload route, rejects singles, requires releases from the last three months with three or more unique tracks, MP3-only ZIP packaging and review-rotation handling. The Music & Performance Director email route was observed but redacted by the fetch layer, so no protected contact should be decoded or guessed. External-form/session handling, package preparation, release recency, track-count rules, metadata and station/library fit must remain manual.",
    notes: "Public research confirmed CJSW's official site is active with 2026 news, schedules, reggae and electronic-adjacent programming, and a Music Submissions page. The route states CJSW only accepts digital music submissions, does not accept singles, requires a new album released within the last three months with at least three unique tracks, MP3 ZIP delivery and an external upload form. No Jotform was submitted, no email was sent, no file was uploaded, no protected email was decoded and no SMTP or MX probing was performed."
  },
  {
    name: "CKUT 90.3FM Music Department Physical and Digital Submission Route",
    websiteUrl: "https://ckut.ca/",
    submissionUrl: "https://ckut.ca/submit-music-to-ckut/",
    sourceUrl: "https://ckut.ca/submit-music-to-ckut/",
    sourceType: "automation_run_96_public_research",
    country: "Canada / Montreal campus-community radio",
    language: "en",
    genres: ["ckut", "montreal", "campus-community-radio", "freeform-radio", "reggae", "soca-dancehall", "latin", "global", "house", "techno", "experimental", "physical-mail", "digital-submission", "public-email", "free-first", "manual-review"],
    submissionMethod: "official-ckut-music-department-physical-and-320-mp3-digital-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because CKUT accepts both physical releases and 320 MP3 digital submissions but applies library criteria, rejects most singles except vinyl 7-inch releases, requires at least three distinct tracks for most formats, and says remixes do not count. Format choice, track-count validation, physical package prep, email copy, metadata, rights/originality and library/station fit must remain manual.",
    notes: "Public research confirmed CKUT's official site is active with 2026 station news, events, playlists, reggae/global/electronic programming categories and a dedicated Submitting Music to CKUT page. The official route lists the Music Department mailing address and public music@ckut.ca digital-submission route. No email was sent, no files or links were delivered, no physical mail was sent and no SMTP or MX probing was performed."
  },
  {
    name: "WMBR MIT Physical Music Director and Genre Contact Route",
    websiteUrl: "https://wmbr.org/",
    submissionUrl: "https://wmbr.org/www/md",
    sourceUrl: "https://wmbr.org/www/md",
    sourceType: "automation_run_96_public_research",
    country: "United States / Cambridge MIT freeform college radio",
    language: "en",
    genres: ["wmbr", "mit", "cambridge", "college-radio", "freeform-radio", "physical-mail", "music-director", "genre-directors", "rpm-techno", "world", "hip-hop", "experimental", "unsigned-bands", "protected-contact", "free-first", "manual-review"],
    submissionMethod: "official-wmbr-music-director-physical-release-and-genre-director-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WMBR strongly prefers tangible physical releases, discourages MP3 review requests, exposes several genre-specific contact routes as protected image links, and leaves airplay decisions to freeform DJs. Physical package prep, one-sheet copy, genre-director selection, unsigned-band fit, protected-contact boundaries and no-self-promotion/list-addition rules must remain manual.",
    notes: "Public research confirmed WMBR's official site is active, currently lists live programming and 2026 contact/staff updates, and its 'How To Get Your Music Played on WMBR' page gives an official Music Director physical address and genre director categories including RPM/Techno and World. The contact page shows Music Department email as protected image content; it was not decoded or guessed. No physical mail was sent, no email was sent, no files or links were delivered and no SMTP or MX probing was performed."
  },
  {
    name: "WMSE 91.7FM Music Department Submission Route",
    websiteUrl: "https://wmse.org/",
    submissionUrl: "https://wmse.org/about-wmse-radio/music-department/",
    sourceUrl: "https://wmse.org/about-wmse-radio/music-department/",
    sourceType: "automation_run_96_public_research",
    country: "United States / Milwaukee listener-supported independent radio",
    language: "en",
    genres: ["wmse", "milwaukee", "independent-radio", "frontier-radio", "music-director", "physical-mail", "digital-download", "vinyl", "cassette", "cd", "fcc-clean", "local-live", "public-email", "contact-form", "captcha", "free-first", "manual-review"],
    submissionMethod: "official-wmse-music-department-physical-digital-download-and-contact-form-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WMSE accepts multiple formats, including physical drop-off/mail, CD, vinyl, cassette and digital download via the Music Director, requires at least four FCC-clean CD tracks, previews submissions for quality/content, and exposes a public contact form with CAPTCHA. Format selection, FCC-clean review, digital-transfer choice, contact-form CAPTCHA boundaries, metadata, local/live-interview fit and package prep must remain manual.",
    notes: "Public research confirmed WMSE's official site is active with a 2026 footer, events, airplay chart and Music Department page. The page lists Music Director Sid McCain, public email mccain@msoe.edu, physical mailing instructions, digital download handling and review expectations. The contact page includes a Music Department option and CAPTCHA. No form was submitted, no CAPTCHA was interacted with, no email was sent, no files or links were delivered, no physical mail was sent and no SMTP or MX probing was performed."
  },
  {
    name: "WRPI Troy Music Director Contact and Station Mail Route",
    websiteUrl: "https://wrpi.org/",
    submissionUrl: "https://www.wrpi.org/contact/",
    sourceUrl: "https://www.wrpi.org/contact/",
    sourceType: "automation_run_96_public_research",
    country: "United States / Troy New York student-run college radio",
    language: "en",
    genres: ["wrpi", "troy", "college-radio", "student-run-radio", "upstate-underground", "music-director", "public-email", "station-mail", "modern-radio", "community-radio", "electronic", "underground", "free-first", "manual-review"],
    submissionMethod: "official-wrpi-music-director-contact-and-station-mail-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WRPI exposes an official Music Director contact route and station mailing address but does not publish a complete music-submission form or detailed packaging rules on the fetched public page. Outreach copy, whether to use email or station mail, music fit, metadata, attachment/link policy and authorization boundaries must be verified manually before any action.",
    notes: "Public research confirmed WRPI's official site describes a student-run 91.5 FM station serving the New York Capital Region, Southwestern Vermont and Western Massachusetts, lists its station address, and provides a public Music Director email route on the official contact page. No email was sent, no files or links were delivered, no physical mail was sent, no contact was guessed and no SMTP or MX probing was performed."
  }
];
