import type { PlatformInput } from '../models/types.js';

export const run92SeedPlatforms: PlatformInput[] = [
  {
    name: "CJSR 88.5 FM Submit Music Route",
    websiteUrl: "https://www.cjsr.com/",
    submissionUrl: "https://www.cjsr.com/submit-music/",
    sourceUrl: "https://www.cjsr.com/submit-music/",
    sourceType: "automation_run_92_public_research",
    country: "Canada / Edmonton campus and community radio",
    language: "en",
    genres: ["cjsr", "edmonton", "campus-radio", "community-radio", "eclectic", "electronic", "folktronica", "reggae", "world", "hip-hop", "albums", "eps", "public-email", "physical-mail", "bandcamp-download-codes", "free-first", "manual-review"],
    submissionMethod: "official-cjsr-music-department-email-and-physical-mail-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because CJSR accepts albums or EPs through official Music Department email and physical mail routes, rejects single tracks, asks for files or stable cloud links rather than paid streaming links, and requires metadata, focus-track, language-warning and no-expiry download-link checks. Email copy, file/link permissions, album/EP eligibility, physical package preparation, customs labeling for non-Canada mail, DJ targeting and station/library fit must remain manual.",
    notes: "Public research confirmed CJSR's official Submit Music page invites music for its eclectic Edmonton station, lists physical delivery to the Music Department, and gives music@cjsr.com for digital albums or EPs with files, Bandcamp download codes, Dropbox/Google Drive/cloud links. The page says not to send Spotify/Tidal/paid streaming links, not to send expiring services like WeTransfer, and not to send single tracks. No email was sent, no files or links were delivered, no physical mail was sent, no paid local advertising side-route was activated and no account was used."
  },
  {
    name: "CFUV 101.9 FM Music Submissions Route",
    websiteUrl: "https://cfuv.uvic.ca/",
    submissionUrl: "https://cfuv.uvic.ca/music-submissions/",
    sourceUrl: "https://cfuv.uvic.ca/music-submissions/",
    sourceType: "automation_run_92_public_research",
    country: "Canada / Victoria campus and community radio",
    language: "en",
    genres: ["cfuv", "victoria", "campus-radio", "community-radio", "freeform", "independent", "electronic", "jazz", "world", "hip-hop", "reggae", "digital-download-link", "public-email", "physical-mail-local-only", "free-first", "manual-review"],
    submissionMethod: "official-cfuv-music-director-digital-download-link-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because CFUV routes all formats through its Music Director, requires at least three unique tracks, prefers digital 320 kbps MP3 download links, and generally no longer accepts physical submissions except local artists or special cases. Metadata, track listing, one-page bio, digital-link permissions, local physical-mail eligibility, lyrical/recording-quality concerns and freeform station fit must be reviewed manually.",
    notes: "Public research confirmed CFUV's official Music Submissions page lists Music Director contact details, says all submissions go to music@cfuv.ca, requires at least three unique tracks, asks for digital download links, prefers 320 kbps MP3s, asks for artist/album/track listing metadata, and says accepted releases are placed internally for freeform programmers rather than fixed playlist rotation. No email was sent, no files or links were delivered, no physical package was prepared and no account was used."
  },
  {
    name: "CJAM 99.1 FM Digital Music Submission Route",
    websiteUrl: "https://www.cjam.ca/",
    submissionUrl: "https://www.cjam.ca/submit/",
    sourceUrl: "https://www.cjam.ca/submit/",
    sourceType: "automation_run_92_public_research",
    country: "Canada / Windsor-Detroit campus and community radio",
    language: "en",
    genres: ["cjam", "windsor", "detroit", "campus-radio", "community-radio", "independent", "electronic", "reggae", "world", "hip-hop", "albums", "eps", "digital-only", "public-email", "free-first", "manual-review"],
    submissionMethod: "official-cjam-digital-music-director-email-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because CJAM is digital-only, asks artists to email the Music Director with release information and a reliable download link, rejects Spotify links and direct MP3 attachments, and requires four or more original tracks with file-quality and ID3-tag checks. Email copy, download-link permissions, EP/album eligibility, metadata, file tags and station fit must remain manual.",
    notes: "Public research confirmed CJAM's official Submit page says it has moved to digital-only submissions, instructs artists to send cjammd@gmail.com release information plus a reliable album download link, rejects Spotify links and directly emailed MP3s, requires four or more original tracks, and asks for MP3/AAC minimum 192 kbps or FLAC plus embedded ID tags. No email was sent, no files or links were delivered and no account was used."
  },
  {
    name: "CFRU 93.3 FM Music Department Submission Route",
    websiteUrl: "https://www.cfru.ca/",
    submissionUrl: "https://www.cfru.ca/music/",
    sourceUrl: "https://www.cfru.ca/music/",
    sourceType: "automation_run_92_public_research",
    country: "Canada / Guelph campus and community radio",
    language: "en",
    genres: ["cfru", "guelph", "campus-radio", "community-radio", "digital-library", "local-form", "electronic", "global-rare-grooves", "reggae", "world", "albums", "eps", "public-email", "public-form", "free-first", "manual-review"],
    submissionMethod: "official-cfru-music-director-email-and-local-upload-form-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because CFRU accepts EPs/albums through Music Director email with high-quality download links, has a separate local-musician upload/download-link form, and includes programmer-only database login resources that must not be used. Email/form routing, local eligibility within 50 km, minimum three-track requirement, 320 kbps MP3 preference, metadata/contact details, file permissions and library fit require manual review.",
    notes: "Public research confirmed CFRU's official Music page says questions go to music@cfru.ca, submissions should be EPs or albums with at least three different songs, artist/album/track/contact info, and high-quality MP3 download links to music@cfru.ca. It also exposes a local music submission form for Guelph-area musicians and notes that digital submissions are accepted except in rare physical circumstances. No email was sent, no local form was submitted, no programmer login was used, and no files or links were delivered."
  },
  {
    name: "Radio Western 94.9 FM Music Submission Email Route",
    websiteUrl: "https://radiowestern.ca/",
    submissionUrl: "https://radiowestern.ca/",
    sourceUrl: "https://radiowestern.ca/",
    sourceType: "automation_run_92_public_research",
    country: "Canada / London Ontario campus and community radio",
    language: "en",
    genres: ["radio-western", "london-ontario", "campus-radio", "community-radio", "independent", "electronic", "world", "reggae", "music-director", "temporary-site", "public-email", "free-first", "manual-review"],
    submissionMethod: "official-radio-western-music-submission-email-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Radio Western's temporary official site explicitly warns not to send new music submissions to the general address and instead routes submissions to music@radiowestern.ca. Since the full site is temporarily unavailable, email copy, release context, file/link format, metadata, station activity verification and station/library fit must be reviewed manually before outreach.",
    notes: "Public research confirmed Radio Western's official temporary page says the web server is damaged but the station still streams through radio apps, lists a general address, explicitly says not to send new music submissions or promotion to that address, and directs that material to music@radiowestern.ca. No email was sent, no files or links were delivered and no account was used."
  }
];
