import type { PlatformInput } from '../models/types.js';

export const run97SeedPlatforms: PlatformInput[] = [
  {
    name: "Soundplate Play Free Spotify and Deezer Playlist Submission Route",
    websiteUrl: "https://play.soundplate.com/",
    submissionUrl: "https://play.soundplate.com/",
    sourceUrl: "https://play.soundplate.com/",
    sourceType: "automation_run_97_public_research",
    country: "United Kingdom / global playlist-submission platform",
    language: "en",
    genres: ["soundplate", "spotify", "deezer", "playlist-submission", "independent-curators", "dance", "house", "deep-house", "garage", "bass", "festival", "free-first", "manual-review"],
    submissionMethod: "official-soundplate-play-free-playlist-submission-selector-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Soundplate Play is a public playlist selector/submit workflow where the artist must pick only musically relevant Spotify or Deezer playlists and avoid spam. Playlist fit, release-link readiness, track metadata, curator targeting, platform/session behavior and any per-playlist submission constraints must remain manual before any submission action.",
    notes: "Public research confirmed Soundplate Play is an official free service for submitting music to Spotify and Deezer playlists, with active playlist categories including deep house, garage, bass, festival and dance-adjacent playlists. The page explicitly asks artists to submit only to relevant playlists and not spam. No playlist was selected, no form was submitted, no account was used, no emails were sent, no payments were activated and no SMTP or MX probing was performed."
  },
  {
    name: "KXCI Tucson Music Department Digital and Physical Submission Route",
    websiteUrl: "https://kxci.org/",
    submissionUrl: "https://kxci.org/about/music-department/",
    sourceUrl: "https://kxci.org/about/music-department/",
    sourceType: "automation_run_97_public_research",
    country: "United States / Tucson Arizona community radio",
    language: "en",
    genres: ["kxci", "tucson", "community-radio", "independent-radio", "world", "reggae", "latin", "electronic", "digital-download", "physical-mail", "public-email-route", "protected-contact", "free-first", "manual-review"],
    submissionMethod: "official-kxci-music-department-digital-download-and-physical-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KXCI accepts CDs, vinyl with digital download, and MP3/WAV download links, but all music is reviewed for genre, quality and explicit language. The Music Department email route was visible as protected/redacted mailto content in the fetch layer. Metadata, lyrics/explicit-language review, release-date details, local-vs-international routing, physical package choice and protected-contact boundaries must remain manual.",
    notes: "Public research confirmed KXCI's official Music Department page says it accepts and broadcasts music from all over the world, with priority for Tucson, regional and Arizona artists. The page lists required metadata, digital MP3/WAV download-link requirements, local-submission subject guidance and physical-mail routes. No protected email was decoded or guessed, no email was sent, no files or links were delivered, no physical mail was sent and no SMTP or MX probing was performed."
  },
  {
    name: "KUTX Austin On-Air Rotation Music Submission Route",
    websiteUrl: "https://kutx.org/",
    submissionUrl: "https://kutx.org/submit-your-music/",
    sourceUrl: "https://kutx.org/submit-your-music/",
    sourceType: "automation_run_97_public_research",
    country: "United States / Austin Texas public music radio",
    language: "en",
    genres: ["kutx", "austin", "public-radio", "music-director", "electronic", "experimental", "latin", "hip-hop", "rnb", "jazz", "streaming-link", "wav-download", "public-email", "qualtrics-side-route", "paid-sponsorship-side-route", "free-first", "manual-review"],
    submissionMethod: "official-kutx-music-director-email-and-specialty-show-routing-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KUTX asks artists to email the Music Director with a specific subject format, streaming link, WAV download link, bio, release notes and a clean radio edit. The page also separates specialty-show, event, in-kind and paid sponsorship routes, so the free editorial/on-air route must stay distinct from paid promotion. Email copy, WAV permissions, FCC-clean review, top-track selection, specialty-show fit and paid-route avoidance must remain manual.",
    notes: "Public research confirmed KUTX's official Submit Your Music page lists music@kutx.org for Music Director on-air rotation consideration, asks for streaming and WAV download links rather than MP3 attachments, requests final mastered clean/radio edits, and lists specialty shows including hip-hop/R&B, Latin and electronic/experimental. No email was sent, no forms were submitted, no files or links were delivered, no paid event or underwriting route was activated and no SMTP or MX probing was performed."
  },
  {
    name: "Audiomack Free Creator Upload and Trending Consideration Route",
    websiteUrl: "https://audiomack.com/",
    submissionUrl: "https://audiomack.com/about",
    sourceUrl: "https://audiomack.com/about",
    sourceType: "automation_run_97_public_research",
    country: "United States / global creator upload and discovery platform",
    language: "en",
    genres: ["audiomack", "creator-upload", "streaming-platform", "artist-dashboard", "trending-consideration", "hip-hop", "afrobeats", "latin", "electronic", "global", "login-required", "free-first", "manual-review"],
    submissionMethod: "official-audiomack-free-creator-upload-and-trending-consideration-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Audiomack is a creator-upload route that requires sign-up/sign-in and rights/metadata review before any upload. The route is free, but account creation, audio upload, artist-profile handling, trending-consideration choices, monetization settings and copyright/authorization checks must remain manual.",
    notes: "Public research confirmed Audiomack's official About page describes the platform as artist-first, links to creator upload, says artists can upload music for free without premium creator accounts, and references free artist dashboard, stats, monetization and trending consideration. No account was created, no login was used, no audio was uploaded, no profile was edited, no monetization route was activated and no SMTP or MX probing was performed."
  },
  {
    name: "Groover Paid Curator and Music Pro Pitch Submission Route",
    websiteUrl: "https://groover.co/",
    submissionUrl: "https://groover.co/en/",
    sourceUrl: "https://groover.co/en/",
    sourceType: "automation_run_97_public_research",
    country: "France / United States / global paid music-promotion platform",
    language: "en",
    genres: ["groover", "music-promotion", "curators", "blogs", "radio", "labels", "playlist-curators", "electronic", "world", "reggae", "hip-hop", "paid-route", "login-required", "manual-review"],
    submissionMethod: "official-groover-paid-credit-curator-and-music-pro-pitch-route",
    feeRequired: true,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: true,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Groover is an account-based paid-credit route where the artist chooses curators or music professionals, uploads a song/demo and sends a pitch using purchased Grooviz credits. Curator targeting, budget approval, payment authorization, pitch text, upload handling, genre fit, rights metadata and campaign scope must remain manual.",
    notes: "Public research confirmed Groover's official site presents access to curators, playlists and music professionals across genres including Electronic, World/Spiritual and Reggae, and says artists pick pros, add/upload a song with a short pitch and need to purchase Grooviz credits to send tracks. No account was created, no login was used, no song was uploaded, no curator was selected, no credits were purchased, no payment was activated and no SMTP or MX probing was performed."
  }
];
