import type { PlatformInput } from '../models/types.js';

export const run93SeedPlatforms: PlatformInput[] = [
  {
    name: "Fresh On The Net Send Us A Track Listening Post Route",
    websiteUrl: "https://freshonthenet.co.uk/",
    submissionUrl: "https://freshonthenet.co.uk/submit/",
    sourceUrl: "https://freshonthenet.co.uk/submit/",
    sourceType: "automation_run_93_public_research",
    country: "United Kingdom / global independent music blog and Listening Post",
    language: "en",
    genres: ["fresh-on-the-net", "uk-music-blog", "listening-post", "independent", "electronic", "reggae", "world", "new-music", "one-track-weekly", "public-form", "closed-window", "no-ai", "free-first", "manual-review"],
    submissionMethod: "official-fresh-on-the-net-send-us-a-track-weekly-form-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Fresh On The Net uses a weekly Send Us A Track inbox that opens and closes by time/volume, allows only one unreleased-or-current track per act per week, requires the track to be publicly available worldwide, prohibits repeats/remixes and AI-generated tracks, and asks artists not to manipulate public voting. Open-window timing, track eligibility, SoundCloud/social-profile details, release status, rights/origin and anti-spam compliance must remain manual.",
    notes: "Public research confirmed the official Fresh On The Net Submit page describes the weekly Listening Post route, says the inbox opens Monday and closes at 200 tracks or Wednesday evening, shows current 2026 blog activity, lists detailed terms, and states the route was closed at time of research. A related public radio-consideration email route was observed on the same page for Del's Exile FM show, but no email was sent, no form was submitted, no track link was delivered and no account was used."
  },
  {
    name: "Resonance FM Promos and Programme Maker Submission Route",
    websiteUrl: "https://www.resonancefm.com/",
    submissionUrl: "https://www.resonancefm.com/about",
    sourceUrl: "https://www.resonancefm.com/about",
    sourceType: "automation_run_93_public_research",
    country: "United Kingdom / London arts and experimental community radio",
    language: "en",
    genres: ["resonance-fm", "london", "community-radio", "arts-radio", "experimental", "radio-art", "electronic", "global", "world", "avant-garde", "public-email", "physical-mail", "free-first", "manual-review"],
    submissionMethod: "official-resonance-fm-promos-email-and-physical-mail-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Resonance FM routes promos, press releases and physical material through official station emails and mail, encourages indicating the relevant presenter or programme, and separates show ideas from ordinary music/promotional material. Presenter targeting, programme fit, email/package copy, file/link permissions, physical package decisions and donation/payment-route avoidance must remain manual.",
    notes: "Public research confirmed Resonance FM is an active 24/7 London station with current 2026 site activity, a large weekly programme schedule, official contact emails for promos, show ideas and programme-maker routing, plus a physical mailing address. No email was sent, no file or download link was delivered, no physical mail was sent, no donation/payment route was used and no account was created."
  },
  {
    name: "Louder Than War New Artists and New Releases Submission Route",
    websiteUrl: "https://louderthanwar.com/",
    submissionUrl: "https://louderthanwar.com/contact/",
    sourceUrl: "https://louderthanwar.com/contact/",
    sourceType: "automation_run_93_public_research",
    country: "United Kingdom / global alternative music publication",
    language: "en",
    genres: ["louder-than-war", "music-publication", "alternative", "independent", "new-artists", "new-releases", "electronic", "reggae", "world", "punk", "post-punk", "public-email", "login-boundary", "free-first", "manual-review"],
    submissionMethod: "official-louder-than-war-new-artists-editor-email-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Louder Than War asks new artists to provide a download or stream link, short release description and enough lead time before release, while routing coverage through specific public editor addresses. Editor selection, lead-time fit, pitch copy, release date, image/press assets, link permissions and visible login/register widgets that are not needed for submission must remain manually reviewed.",
    notes: "Public research confirmed Louder Than War has current 2026 music publication activity, says it actively seeks new music, and its official Contact page lists public editorial addresses plus New Artists guidance requesting a link to download or stream the music, a short description and at least one month lead time. No editor email was sent, no account or login widget was used, no file or link was delivered and no payment route was activated."
  },
  {
    name: "God Is In The TV Contact Form and New Music Submission Route",
    websiteUrl: "https://www.godisinthetvzine.co.uk/",
    submissionUrl: "https://www.godisinthetvzine.co.uk/contact/",
    sourceUrl: "https://www.godisinthetvzine.co.uk/contact/",
    sourceType: "automation_run_93_public_research",
    country: "United Kingdom / Cardiff-based independent music zine",
    language: "en",
    genres: ["god-is-in-the-tv", "music-zine", "independent", "unsigned-artists", "new-music", "electronic", "reggae", "world", "reviews", "contact-form", "anti-spam", "free-first", "manual-review"],
    submissionMethod: "official-god-is-in-the-tv-contact-form-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: true,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because the official contact route is a Contact Form 7 workflow with newsletter anti-spam/honeypot and cookie/privacy controls, and the publication covers independent and unsigned artists alongside larger releases. Form/session handling, anti-spam control respect, pitch copy, release assets, editor fit, consent and file/link permissions must remain manual.",
    notes: "Public research confirmed God Is In The TV has active 2026 new-music and review coverage, its official Contact page exposes a Contact Form 7 route, and the site describes coverage ranging from unsigned and independent artists to major releases. No contact form was submitted, no anti-spam or cookie controls were interacted with or bypassed, no email was guessed, no file or link was delivered and no account was used."
  },
  {
    name: "NARC Magazine Submission Guidelines and Contact Form Route",
    websiteUrl: "https://narcmagazine.com/",
    submissionUrl: "https://narcmagazine.com/contact/",
    sourceUrl: "https://narcmagazine.com/contact/",
    sourceType: "automation_run_93_public_research",
    country: "United Kingdom / North East music and creative arts publication",
    language: "en",
    genres: ["narc-magazine", "north-east-uk", "music-publication", "alternative", "independent", "creative-arts", "electronic", "reggae", "world", "submission-guidelines", "contact-form", "protected-contact", "free-first", "manual-review"],
    submissionMethod: "official-narc-magazine-contact-form-and-submission-guidelines-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because NARC Magazine provides submission guidelines and a public contact form, while the fetched official contact email was protected/redacted and must not be decoded or guessed. North East relevance, timing, monthly deadline fit, high-resolution image availability, pitch copy, release/event context, regional-cultural fit and protected-contact boundaries must remain manual.",
    notes: "Public research confirmed NARC Magazine's official Contact page provides a public contact form and submission guidelines asking artists and culture makers to have finished work ready, describe the project, include press information/high-resolution imagery and keep deadlines in mind. The official email link was protected/redacted by the fetch layer and was not decoded or guessed. No form was submitted, no email was sent, no file or link was delivered and no account was used."
  }
];
