import type { PlatformInput } from '../models/types.js';

export const run90SeedPlatforms: PlatformInput[] = [
  {
    name: "WXDU 88.7 FM Music Airplay Submission Route",
    websiteUrl: "https://www.wxdu.org/",
    submissionUrl: "https://www.wxdu.org/contact.html",
    sourceUrl: "https://www.wxdu.org/contact.html",
    sourceType: "automation_run_90_public_research",
    country: "United States / Duke University progressive alternative college radio",
    language: "en",
    genres: ["wxdu", "duke-university", "college-radio", "progressive-alternative", "electronic", "rpm", "world", "latin", "north-carolina", "bandcamp-yum-codes", "public-email", "physical-mail", "free-first", "manual-review"],
    submissionMethod: "official-wxdu-music-airplay-email-and-mail-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WXDU publishes an official music-airplay route, prefers Bandcamp YUM codes over other downloads, and provides a public music email plus mailing address. Track choice, YUM-code or download-link selection, email copy, metadata, clean/explicit labeling, genre-director routing and station-fit review must remain manual.",
    notes: "Public research confirmed WXDU is active as Duke University radio, lists progressive alternative radio programming and says it maintains good music-industry relations without compromising programming integrity. The official Contact Us page says to submit music for airplay via Bandcamp YUM codes and music@wxdu.org, and lists the station mailing address. No email was sent, no file/link was delivered, no account was used and no submission was made."
  },
  {
    name: "KTRU 96.1 FM Physical Music Submission Route",
    websiteUrl: "https://ktru.org/",
    submissionUrl: "https://ktru.org/contact/",
    sourceUrl: "https://ktru.org/contact/",
    sourceType: "automation_run_90_public_research",
    country: "United States / Rice University freeform college radio",
    language: "en",
    genres: ["ktru", "rice-university", "college-radio", "freeform", "physical-submission", "cd", "lp", "7-inch", "experimental", "indie", "reggae", "world", "electronic", "local-music", "free-first", "manual-review"],
    submissionMethod: "official-ktru-physical-music-submission-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KTRU states that music submissions should use physical formats only, specifically CD, LP or 7-inch, routed to the Music Department. Physical package preparation, format eligibility, postal/courier choice, metadata, clean/explicit labeling and station/library fit require manual review.",
    notes: "Public research confirmed KTRU is active in 2026 with recent music coverage and a public contact route. The official contact page includes a contact form and states that all music submissions should go through snail mail in physical formats, with USPS and UPS addresses. No form was submitted, no physical mail was sent, no files were uploaded and no email was sent."
  },
  {
    name: "WHPK 88.5 FM Music Submissions Contact Route",
    websiteUrl: "https://www.whpk.org/",
    submissionUrl: "https://www.whpk.org/contact",
    sourceUrl: "https://www.whpk.org/",
    sourceType: "automation_run_90_public_research",
    country: "United States / University of Chicago college and community radio",
    language: "en",
    genres: ["whpk", "university-of-chicago", "college-radio", "community-radio", "electronic", "rap", "jazz", "international", "folk", "rock", "public-affairs", "music-submissions", "free-first", "manual-review"],
    submissionMethod: "official-whpk-music-submissions-contact-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WHPK's official site points users away from station-manager contact for music submissions and exposes a music-submissions contact route, while the contact-route fetch produced a cache-miss/verification edge case. Route confirmation, genre/program targeting, package/link selection, metadata and station-fit review must remain manual.",
    notes: "Public research confirmed WHPK is active with current now-playing data, schedule blocks and genre categories including Electronic, Rap, Jazz, Folk, Rock and International. The official home page says not to contact the station manager for music submissions and links a music-submissions route. No protected contact was decoded, no message was sent, no form was submitted and no session or verification control was bypassed."
  },
  {
    name: "WICB 91.7 FM Submit Music Route",
    websiteUrl: "https://wicb.org/",
    submissionUrl: "https://wicb.org/submit-music/",
    sourceUrl: "https://wicb.org/contact/",
    sourceType: "automation_run_90_public_research",
    country: "United States / Ithaca College alternative and specialty college radio",
    language: "en",
    genres: ["wicb", "ithaca-college", "college-radio", "submit-music", "alternative", "reggae", "jazz", "hip-hop", "blues", "local-music", "specialty-shows", "free-first", "manual-review"],
    submissionMethod: "official-wicb-submit-music-site-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because WICB exposes an official Submit Music navigation route, but the fetched contact page did not expose a complete safe auto-submit endpoint. The submission page, eligibility, contact or upload fields, track metadata, clean/explicit edits and specialty-show fit must be reviewed manually.",
    notes: "Public research confirmed WICB's official site navigation includes Submit Music and Contact links. Additional public research confirms WICB is an active Ithaca College station with alternative programming plus reggae, jazz, blues, hip-hop and local-music support. No form was submitted, no email was sent, no files were uploaded and no contacts were guessed."
  },
  {
    name: "KCRW Music Airplay Recording Consideration Route",
    websiteUrl: "https://www.kcrw.com/",
    submissionUrl: "https://www.kcrw.com/contact",
    sourceUrl: "https://www.kcrw.com/contact",
    sourceType: "automation_run_90_public_research",
    country: "United States / Southern California public radio music-discovery route",
    language: "en",
    genres: ["kcrw", "public-radio", "music-discovery", "morning-becomes-eclectic", "electronic", "dance", "reggae", "world", "eclectic", "local-regional-artists", "airplay-consideration", "free-first", "manual-review"],
    submissionMethod: "kcrw-public-contact-and-airplay-consideration-route",
    feeRequired: false,
    loginRequired: false,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because KCRW's public contact route and public airplay-consideration references require careful route validation before any outreach. Local or regional eligibility, recording/package selection, no-attachment/download-link choice, metadata, clean/explicit edits and programmer fit must remain manual.",
    notes: "Public research confirmed KCRW's official site is active in 2026 with current music playlists, music shows and DJ pages, plus a public Contact Us page. Public station reference material says local and regional touring artists can send recordings to KCRW for airplay consideration. No contact form was submitted, no email was sent, no audio/link was delivered and no route was activated."
  }
];
