import type { PlatformInput } from '../models/types.js';

export const run98SeedPlatforms: PlatformInput[] = [
  {
    name: "SoundCloud Creator Upload and Fan Discovery Route",
    websiteUrl: "https://soundcloud.com/",
    submissionUrl: "https://soundcloud.com/upload",
    sourceUrl: "https://soundcloud.com/upload",
    sourceType: "automation_run_98_public_research",
    country: "Germany / United States / global creator-upload and fan-discovery platform",
    language: "en",
    genres: ["soundcloud", "creator-upload", "fan-discovery", "independent-artists", "electronic", "dubstep", "bass", "reggae", "dancehall", "global", "login-required", "freemium", "free-first", "manual-review"],
    submissionMethod: "official-soundcloud-upload-your-first-track-creator-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because SoundCloud's official upload route requires a creator session and exposes free upload capacity plus Pro plan side-routes. Track upload, account/profile selection, copyright/authorization checks, title/genre/tag metadata, private/public visibility, download permissions, direct-fan messaging and optional promotion/Pro-plan choices must remain manual.",
    notes: "Public research confirmed SoundCloud's official upload page invites creators to share tracks with the world, shows an upload-your-first-track route, says creators can connect with audiences for free, lists 180 minutes of free uploads, and exposes Pro-plan links. The page requires JavaScript/session handling. No account was created, no login was used, no track was uploaded, no Pro plan was selected, no messages were sent and no SMTP or MX probing was performed."
  },
  {
    name: "Bandcamp Artist Store and Direct-to-Fan Release Route",
    websiteUrl: "https://bandcamp.com/",
    submissionUrl: "https://bandcamp.com/artists",
    sourceUrl: "https://bandcamp.com/artists",
    sourceType: "automation_run_98_public_research",
    country: "United States / global direct-to-fan artist store and music marketplace",
    language: "en",
    genres: ["bandcamp", "direct-to-fan", "artist-store", "digital-release", "merch", "independent-artists", "electronic", "dub", "reggae", "world", "fan-community", "login-required", "revenue-share", "freemium", "free-first", "manual-review"],
    submissionMethod: "official-bandcamp-for-artists-sign-up-release-store-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Bandcamp requires artist account setup and release/store configuration. Audio upload, pricing, currency, merch/digital choices, payout setup, copyright and AI-policy compliance, album/track metadata, private-streaming/Pro choices, fan email/data handling and revenue-share implications must remain manual.",
    notes: "Public research confirmed Bandcamp's official artist page says artists get a customizable direct-to-fan store, become part of the marketplace, artist accounts are free, digital music uses a 15% revenue share, merch uses a 10% revenue share, and Bandcamp Pro is an optional premium tier. It also says sign-up requires a desktop browser. No account was created, no login was used, no music or merch was uploaded, no pricing/payout settings were changed, no fan messages were sent and no SMTP or MX probing was performed."
  },
  {
    name: "Jamendo Artist Services Music Licensing and In-Store Route",
    websiteUrl: "https://www.jamendo.com/",
    submissionUrl: "https://artists.jamendo.com/",
    sourceUrl: "https://artists.jamendo.com/",
    sourceType: "automation_run_98_public_research",
    country: "Luxembourg / global independent artist services and licensing marketplace",
    language: "en",
    genres: ["jamendo", "artist-services", "music-licensing", "sync", "in-store", "content-id", "independent-artists", "world", "electronic", "reggae", "dub", "commercial-licensing", "login-required", "free-first", "manual-review"],
    submissionMethod: "official-jamendo-artist-services-start-now-and-sign-in-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Jamendo Artist Services requires sign-in/start-now account handling and may route music into streaming, licensing, in-store placement, Content ID and release-promotion workflows. Rights ownership, collecting-society constraints, commercial-license choices, revenue-share expectations, metadata, territory and YouTube Content ID authorization must remain manual.",
    notes: "Public research confirmed Jamendo's official artist-services page offers a one-stop space for DIY musicians, routes users through sign-in/start-now actions, says artists can reach over 7 million music fans, reach sync professionals, place music in more than 20,000 commercial spaces, promote releases, and receive up to 65% of each licensing sale plus 80% of eligible Content ID revenue. No account was created, no login was used, no track was uploaded, no licensing or Content ID route was activated, no payment settings were changed and no SMTP or MX probing was performed."
  },
  {
    name: "Mixcloud DJ Mix Radio Show and Podcast Upload Route",
    websiteUrl: "https://www.mixcloud.com/",
    submissionUrl: "https://www.mixcloud.com/upload/",
    sourceUrl: "https://www.mixcloud.com/upload/",
    sourceType: "automation_run_98_public_research",
    country: "United Kingdom / global DJ mix, radio show and podcast upload platform",
    language: "en",
    genres: ["mixcloud", "dj-mixes", "radio-shows", "podcasts", "creator-upload", "electronic", "dub", "reggae", "dancehall", "bass", "festival", "login-required", "pro-side-route", "freemium", "free-first", "manual-review"],
    submissionMethod: "official-mixcloud-upload-for-free-dj-mix-radio-show-podcast-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because Mixcloud's official route allows free uploads but requires sign-up/login and is best suited to DJ mixes, radio shows and podcasts rather than ordinary single-track distribution. Rights, tracklist metadata, show title/description, genre targeting, upload limits, takedown/licensing implications, Pro upgrade choices and fan-monetization settings must remain manual.",
    notes: "Public research confirmed Mixcloud's official upload page offers sign-up/login, an Upload for free route, creator tools for unlimited uploads, live streaming, HQ audio, monetization, stats and host tagging, plus a Pro creator upgrade shown at $11.25/month when paid annually. No account was created, no login was used, no show or track was uploaded, no Pro plan was selected, no live stream was started and no SMTP or MX probing was performed."
  },
  {
    name: "hearthis.at Artist Upload and Music Community Route",
    websiteUrl: "https://hearthis.at/",
    submissionUrl: "https://hearthis.at/",
    sourceUrl: "https://hearthis.at/",
    sourceType: "automation_run_98_public_research",
    country: "Germany / global music community, DJ set and track upload platform",
    language: "en",
    genres: ["hearthis-at", "creator-upload", "dj-sets", "tracks", "music-community", "electronic", "edm", "dubstep", "drum-and-bass", "reggae", "dancehall", "world", "login-required", "freemium", "free-first", "manual-review"],
    submissionMethod: "official-hearthis-at-create-account-upload-your-own-music-route",
    feeRequired: false,
    loginRequired: true,
    captchaDetected: false,
    paymentRequired: false,
    manualReviewRequired: true,
    manualReviewReason: "Human review is required because hearthis.at provides public upload and account creation routes, but publishing requires sign-up/sign-in and rights/metadata control. Genre classification, file-format/size, free weekly upload limit, download permissions, fan-shop/subscription settings, live-stream/replay options and copyright-compliance boundaries must remain manual.",
    notes: "Public research confirmed hearthis.at exposes Upload, Sign in and Create Account routes, lists free account creation, says users can upload their own music, offers up to 400 MB of music uploads each week for free, shows ACRCloud copyright compliance, and lists relevant genres including Drum & Bass, Dubstep/Bass, Dub, Reggae/Dancehall, EDM, World and Electronic. No account was created, no login was used, no music was uploaded, no subscription/fan-shop options were enabled and no SMTP or MX probing was performed."
  }
];
